### ISSUE TITLE
modopenssl no longer packaged in 2022.02?

### ISSUE THREAD

**Issue by patricegautier** [pi-hole/docker-pi-hole#1001]
This is a: Run Issue

## Details

Updating my container to 2022.2, it fails to start looping on:

Starting lighttpd
2022-02-12 13:03:13: plugin.c.195) dlopen() failed for: /usr/lib/lighttpd/mod_openssl.so /usr/lib/lighttpd/mod_openssl.so: cannot open shared object file: No such file or directory
2022-02-12 13:03:13: server.c.1238) loading plugins finally failed
Stopping lighttpd
lighttpd: no process found

rolling back to 2022.01.1 solves the issue..

I do specify mod_openssl in my lighthttpd.conf:
..
server.modules += ( "mod_openssl" )
..

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: DSM 7.01 
  * Hardware: Synology
  * Kernel Architecture: x86_64
  * Docker Install Info and version:  Docker version 20.10.3, build b455053

**Comment by PromoFaux** [comment]
Ah, yes this may be because the base image is now Bullseye (therefore different `lighttpd` version) https://github.com/pi-hole/docker-pi-hole/pull/976

**Comment by edgd1er** [comment]
I've just tried the new version, no problem on my armv7. 
I'm not using ssl mod.
your lighttpd configuration file seems to reference mod_openssl.

On the instance I ran, this module is not installed:
```
root@8ef10aa7ba2f:/usr/lib/lighttpd# dpkg -l lighttpd-mod-openssl
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                 Version      Architecture Description
+++-====================-============-============-=================================
un  lighttpd-mod-openssl <none>       <none>       (no description available)
```

I have no idea though if that module used to be installed or not on previous version.

**Comment by edgd1er** [comment]
I'm afraid it was in an earlier version:
here is the output of mod_openssl status for 2022.01 on arm.

```
Linux 7bb822b899f0 5.10.92-v7+ #1514 SMP Mon Jan 17 17:36:39 GMT 2022 armv7l GNU/Linux

root@7bb822b899f0:/# dpkg -l lighttpd-mod-openssl
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                 Version      Architecture Description
+++-====================-============-============-=================================
un  lighttpd-mod-openssl <none>       <none>       (no description available)

root@7bb822b899f0:/# echo $PIHOLE_DOCKER_TAG 
2022.01
```

**Comment by PromoFaux** [comment]
Sorry, had some teething troubles reverting to buster. Please try the :dev image, which is now based on buster, and see if that makes any difference

**Comment by patricegautier** [comment]
I confirm happiness has returned with :dev on armv7l, including mod_openssl

**Comment by edgd1er** [comment]
an unexplained mecanism is activating ssl on buster because by default, it is not:

```
root@bd08ec33e92c:/# echo $PIHOLE_DOCKER_TAG 
dev
root@bd08ec33e92c:/# cat /etc/os-release    
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@bd08ec33e92c:/# lighty-enable-mod 
Disabled modules: accesslog auth cgi debian-doc dir-listing evasive evhost expire extforward flv-streaming no-www proxy rewrite rrdtool simple-vhost sockproxy ssi ssl status userdir usertrack 
Enabled modules: fastcgi fastcgi-php unconfigured
```

**Comment by PromoFaux** [comment]
One difference between the `buster` image and the `bullseye` image, is that in `buster` we run `c_rehash`, due to a bug in armhf-buster's `curl` binary:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923479

It is possible. I guess that this issue persists into bullseye...

**Comment by edgd1er** [comment]
well this may explain things: 
`openssl support was historically built into the core of lighttpd 1.4.x, but is now a standalone module (mod_openssl) since lighttpd 1.4.46.`
https://redmine.lighttpd.net/projects/1/wiki/docs_ssl

ssl was included, not anymore, need to be added in the install.sh in pihole_webs_deps var.

**Comment by rdwebdesign** [comment]
Good information.

**Comment by edgd1er** [comment]
> Cool that would solve this issue - however #1002 would still be an issue it seems

I suspect a particuliar combination of system/settings ending in that problem for 1002.

**Comment by UnlimitedCookies** [comment]
Yep, on bullseye you just need to install [lighttpd-mod-openssl](https://packages.debian.org/bullseye/lighttpd-mod-openssl).

**Comment by edgd1er** [comment]
you may add in line 71 of install.sh the hereunder code, that won't work if you have already a certificate ( need to rework on that)

```
#setup ssl with default certificate if needed
if [ ! -e /etc/lighttpd/server.pem ]; then
  apt-get install -y --no-install-recommends lighttpd-mod-openssl
  lighty-enable-mod ssl
  openssl req -x509 -newkey rsa:4096 -nodes -keyout /etc/lighttpd/key.pem -out /etc/lighttpd/certificate.pem -sha256 -days 3650 -subj "/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=www.example.com"
  cat /etc/lighttpd/certificate.pem /etc/lighttpd/key.pem > /etc/lighttpd/server.pem
  chown -R www-data:www-data /etc/lighttpd
  chmod 0600 /etc/lighttpd/*.pem
fi
``` 
I might do a PR for that soon...
