### ISSUE TITLE
Latest docker release (2022.02) breaks on armv7

### ISSUE THREAD

**Issue by Willsr71** [pi-hole/docker-pi-hole#1002]
This is a: Bug

The latest docker image fails to start on armv7. I have not tested on other platforms, but it fails on touching the lighttpd config. Presumably related to [this pr](https://github.com/pi-hole/docker-pi-hole/pull/991).

## Details

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 05-changer-uid-gid.sh: executing... 
[cont-init.d] 05-changer-uid-gid.sh: exited 0.
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole
Assigning random password: Ni39nCvh

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
touch: setting times of '/etc/lighttpd/external.conf': Operation not permitted
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 20.04
  * Hardware: Raspberry Pi 4b+
  * Kernel Architecture: armv7
  * Docker Install Info and version: 
    - Software source: official docker
    - Supplimentary Software: none
  * Hardware architecture: x86_64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
    pihole:
        image: pihole/pihole:2022.01.1
        #build: "./images/pihole-speedtest"
        hostname: "pihole"
        ports:
            - "53:53"
            - "53:53/udp"
            - "67:67/udp"
            - "80:80"
            - "443:443"
        volumes:
            - /home/pi/pihole/config:/etc/pihole
            - /home/pi/pihole/dnsmasq:/etc/dnsmasq.d
        cap_add:
            - NET_ADMIN
        dns:
            - 127.0.0.1
            - 1.1.1.1
        restart: "always"
```

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by PromoFaux** [comment]
> touch: setting times of '/etc/lighttpd/external.conf': Operation not permitted

Hmmm. That PR doens't touch `external.conf`, though. Let me try on my 4b+...

**Comment by PromoFaux** [comment]
In the mean time, can you set the environment variable `PH_VERBOSE` to `1` and start up the container again, should give us a bit more detail in the output

**Comment by patricegautier** [comment]
This is the tail end of the logs..

```
+ chmod 644 /etc/pihole/dns-servers.conf
+ [[ ! -r /etc/pihole/pihole-FTL.conf ]]
+ [[ ! -r /etc/pihole/custom.list ]]
+ [[ true == true ]]
+ [[ ! -d /etc/lighttpd ]]
+ [[ -f /etc/lighttpd/lighttpd.conf ]]
+ mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.orig
+ install -D -m 644 -T /etc/.pihole/advanced/lighttpd.conf.debian /etc/lighttpd/lighttpd.conf
+ touch /etc/lighttpd/external.conf
touch: setting times of '/etc/lighttpd/external.conf': Operation not permitted
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by patricegautier** [comment]
I do have this mapping in the docker-compose.yml:

      - '${HOME}/Deployment/pihole/lighthttpd299.conf:/etc/lighttpd/external.conf'

which was working fine until today's release

**Comment by PromoFaux** [comment]
Oh, ah. Yes that might explain it. I've seen issues in the past with mounting single files to a container and odd stuff happening

Let me see if I can dig out previous discussion...

**Comment by patricegautier** [comment]
For what it's worth I tried playing with ownership and permissions of that mounted file from the outside to no avail.

Also, from the logs it does look like the install process is trying to replace it, which is not desirable I don't think.

**Comment by PromoFaux** [comment]
Hmm. nope, that section of code has not been touched for 3 years!

https://github.com/pi-hole/pi-hole/blob/c3c5342b48b226f482bc0d44ca8b5bed13b60a08/automated%20install/basic-install.sh#L1333-L1334

**Comment by PromoFaux** [comment]
No wait... that wouldn't (shouldn't) actually run at this point in the docker startup. Back to the drawing board.

**Comment by patricegautier** [comment]
So given those log lines:

+ [[ -f /etc/lighttpd/lighttpd.conf ]]
+ mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.orig
+ install -D -m 644 -T /etc/.pihole/advanced/lighttpd.conf.debian /etc/lighttpd/lighttpd.conf
+ touch /etc/lighttpd/external.conf

the permission issue makes sense.. the question is why they are being run now

**Comment by jvanenckevort** [comment]
> So given those log lines:
> 
> * [[ -f /etc/lighttpd/lighttpd.conf ]]
> * mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.orig
> * install -D -m 644 -T /etc/.pihole/advanced/lighttpd.conf.debian /etc/lighttpd/lighttpd.conf
> * touch /etc/lighttpd/external.conf
> 
> the permission issue makes sense.. the question is why they are being run now

There is also a lot of permission / group changes in the latest commits. It could be that underwater the user does not have the same permissions as it had before, not immediately visible ofcourse.

**Comment by edgd1er** [comment]
I've just tried the new version, no problem on my armv7. 
I'm not using ssl mod.
your lighttpd configuration file seems to reference mod_openssl.

On the instance I ran, this module is not installed:
```
root@8ef10aa7ba2f:/usr/lib/lighttpd# dpkg -l lighttpd-mod-openssl
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                 Version      Architecture Description
+++-====================-============-============-=================================
un  lighttpd-mod-openssl <none>       <none>       (no description available)
```

I have no idea though if that module used to be installed or not on previous version.

**Comment by jvanenckevort** [comment]
File permissions in 2022.01 (still working):

drwxr-xr-x 2 root   root 4096 Jan  2 13:06 conf-available
drwxr-xr-x 1 root   root 4096 Feb 12 22:40 conf-enabled
-rw-r--r-- 1 root   root    0 Feb 12 22:40 external.conf
-rw-r--r-- 1 root   root 3692 Feb 12 22:40 lighttpd.conf
-rw-r--r-- 1 root   root 3692 Jan  3 21:23 lighttpd.conf.orig

File permissions in 2022.02:

drwxr-xr-x  2 pi   pi   4096 Feb 12 22:51 .
drwxr-xr-x 26 pi   pi   4096 Feb 12 22:49 ..
-rw-r--r--  1 root root    0 Feb 12 22:51 external.conf
-rw-r--r--  1 root root 3692 Feb 12 22:51 lighttpd.conf
-rw-r--r--  1 root root 3692 Feb 12 22:51 lighttpd.conf.orig

Permissions for external.conf look the same.
Are we sure the root user is still running that particular part of the installation?

**Comment by MrFly72** [comment]
Mine also breaks. Interestingly ports redirection into docker disappear after some time. Right after start docker ps shows the ports, after short time, docker ps shows no ports at all anymore.
Do not have time to investigate currently (family weekend), but going back to 2022.01 brings it back on.

**Comment by jvanenckevort** [comment]
Debug log 2022.01 (working):

```
...
Cloudflare (DNSSEC);1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001'
+ chmod 644 /etc/pihole/dns-servers.conf
+ [[ ! -r /etc/pihole/pihole-FTL.conf ]]
+ [[ ! -r /etc/pihole/custom.list ]]
+ [[ true == true ]]
+ [[ ! -d /etc/lighttpd ]]
+ [[ -f /etc/lighttpd/lighttpd.conf ]]
+ mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.orig
+ install -D -m 644 -T /etc/.pihole/advanced/lighttpd.conf.debian /etc/lighttpd/lighttpd.conf
**+ touch /etc/lighttpd/external.conf**
+ chmod 644 /etc/lighttpd/external.conf
+ [[ -f /var/www/html/pihole/custom.php ]]
+ mkdir -p /run/lighttpd
+ chown www-data:www-data /run/lighttpd
+ mkdir -p /var/cache/lighttpd/compress
+ chown www-data:www-data /var/cache/lighttpd/compress
+ mkdir -p /var/cache/lighttpd/uploads
+ chown www-data:www-data /var/cache/lighttpd/uploads
...
```

Debug log 2022.02 (broken):

```
...
Cloudflare (DNSSEC);1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001'
+ chmod 644 /etc/pihole/dns-servers.conf
+ [[ ! -r /etc/pihole/pihole-FTL.conf ]]
+ install -d -m 0755 /etc/pihole
+ install -T -o pihole -m 664 /etc/.pihole/advanced/Templates/pihole-FTL.conf /etc/pihole/pihole-FTL.conf
+ [[ ! -r /etc/pihole/custom.list ]]
+ install -o root -m 644 /dev/null /etc/pihole/custom.list
+ [[ true == true ]]
+ [[ ! -d /etc/lighttpd ]]
+ [[ -f /etc/lighttpd/lighttpd.conf ]]
+ mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.orig
+ install -D -m 644 -T /etc/.pihole/advanced/lighttpd.conf.debian /etc/lighttpd/lighttpd.conf
+ touch /etc/lighttpd/external.conf
**touch: setting times of '/etc/lighttpd/external.conf': Operation not permitted**
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
...

```

**Comment by PromoFaux** [comment]
Have just done some local testing with @rdwebdesign who was seeing the same thing and it seems that this may be caused by the OS bump to bullseye. In the process of building another image based on buster for wider testing

**Comment by Jossec101** [comment]
+1 Same issue here, I had to revert back to an older version (5 weeks ago) on mi RPI 4

**Comment by jvanenckevort** [comment]
@PromoFaux in the old situation the lighttpd user is not modified, in the new situation it is. Log traces from the start of the container show exactly what is going on there.

Container 2022.02 (broken):

```
...
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 05-changer-uid-gid.sh: executing...
+ modifyUser www-data
+ declare username=www-data newId=
+ [[ -z www-data ]]
+ [[ -z '' ]]
+ return
+ modifyGroup www-data
+ declare groupname=www-data newId=
+ [[ -z www-data ]]
+ [[ -z '' ]]
+ return
+ modifyUser pihole
+ declare username=pihole newId=
+ [[ -z pihole ]]
+ [[ -z '' ]]
+ return
+ modifyGroup pihole
+ declare groupname=pihole newId=
+ [[ -z pihole ]]
+ [[ -z '' ]]
+ return
[cont-init.d] 05-changer-uid-gid.sh: exited 0.
[cont-init.d] 20-start.sh: executing...
+ bashCmd='bash -e -x'
+ bash -e -x /start.sh
...
```

Container 2022.01 (working):

```
...
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 1.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
+ bashCmd='bash -e -x'
+ bash -e -x /start.sh
...
```

**Comment by PromoFaux** [comment]
That's not actually changing anything, it's hitting the `return`:

https://github.com/pi-hole/docker-pi-hole/blob/fe1676b9ede084f84962d4ba824dd06e44564531/s6/debian-root/etc/cont-init.d/05-changer-uid-gid.sh#L2-L35

It will only change the lighttpd user if the env var is set

**Comment by jvanenckevort** [comment]
> It will only change the lighttpd user if the env var is set

You are correct, my bad. Getting late here.

**Comment by edgd1er** [comment]
/etc/lighttpd/ belongs to the image.

This is very strange. cont-init.d scripts are ran with root on a local file, there is no reason a touch cannot be performed.

touch: setting times of '/etc/lighttpd/external.conf': Operation not permitted` , the error is quite clear, the access time cannot be set on the file.
Are you mounting the file or the dir ?
Looking on google for this type of error, they seem related to a nfs mounted dir/file.

**Comment by pedropombeiro** [comment]
I'm also seeing problems on an ARM architecture with 2022.2:

```shell
# podman exec pihole ls -al
total 0
d????????? ? ? ? ?            ? .
d????????? ? ? ? ?            ? ..
-????????? ? ? ? ?            ? bash_functions.sh
d????????? ? ? ? ?            ? bin
d????????? ? ? ? ?            ? boot
d????????? ? ? ? ?            ? dev
d????????? ? ? ? ?            ? etc
d????????? ? ? ? ?            ? home
d????????? ? ? ? ?            ? lib
d????????? ? ? ? ?            ? libexec
d????????? ? ? ? ?            ? media
d????????? ? ? ? ?            ? mnt
d????????? ? ? ? ?            ? opt
d????????? ? ? ? ?            ? proc
d????????? ? ? ? ?            ? root
d????????? ? ? ? ?            ? run
-????????? ? ? ? ?            ? s6-init
d????????? ? ? ? ?            ? sbin
d????????? ? ? ? ?            ? srv
-????????? ? ? ? ?            ? start.sh
d????????? ? ? ? ?            ? sys
d????????? ? ? ? ?            ? tmp
d????????? ? ? ? ?            ? usr
d????????? ? ? ? ?            ? var
ls: cannot access 'dev': Operation not permitted
ls: cannot access 'tmp': Operation not permitted
ls: cannot access '.': Operation not permitted
ls: cannot access 'usr': Operation not permitted
ls: cannot access 'home': Operation not permitted
ls: cannot access 'lib': Operation not permitted
ls: cannot access 'boot': Operation not permitted
ls: cannot access 'root': Operation not permitted
ls: cannot access 'var': Operation not permitted
ls: cannot access 'media': Operation not permitted
ls: cannot access 'run': Operation not permitted
ls: cannot access 'sys': Operation not permitted
ls: cannot access 'etc': Operation not permitted
ls: cannot access 'bin': Operation not permitted
ls: cannot access 'opt': Operation not permitted
ls: cannot access 'proc': Operation not permitted
ls: cannot access '..': Operation not permitted
ls: cannot access 'sbin': Operation not permitted
ls: cannot access 'mnt': Operation not permitted
ls: cannot access 'srv': Operation not permitted
ls: cannot access 'bash_functions.sh': Operation not permitted
ls: cannot access 'start.sh': Operation not permitted
ls: cannot access 's6-init': Operation not permitted
ls: cannot access 'libexec': Operation not permitted
Error: non zero exit code: 1: OCI runtime error
```

Reverting back to 2022.01.1 fixes it:

```shell
# podman exec -ti pihole ls -al /
total 124
drwxr-xr-x   1 root root  4096 Feb 13 00:50 .
drwxr-xr-x   1 root root  4096 Feb 13 00:50 ..
-rw-r--r--   1 root root 13631 Jan  6 00:05 bash_functions.sh
drwxr-xr-x   1 root root 12288 Jan 22  2021 bin
drwxr-xr-x   2 root root  4096 Oct  3 11:00 boot
drwxr-xr-x   5 root root   320 Feb 13 00:50 dev
drwxr-xr-x   1 root root  4096 Feb 13 00:50 etc
drwxr-xr-x   2 root root  4096 Oct  3 11:00 home
drwxr-xr-x   1 root root  4096 Jan  5 17:47 lib
drwxr-xr-x   2 root root  4096 Jan 22  2021 libexec
drwxr-xr-x   2 root root  4096 Dec 20 01:00 media
drwxr-xr-x   2 root root  4096 Dec 20 01:00 mnt
drwxr-xr-x   1 root root  4096 Feb 13 00:50 opt
dr-xr-xr-x 218 root root     0 Feb 13 00:50 proc
drwx------   2 root root  4096 Dec 20 01:00 root
drwxr-xr-x   1 root root  4096 Feb 13 00:50 run
-rwxr-xr-x   1 root root   389 Feb 15  2021 s6-init
drwxr-xr-x   1 root root  4096 Jan  6 00:07 sbin
drwxr-xr-x   2 root root  4096 Dec 20 01:00 srv
-rwxr-xr-x   1 root root  7846 Jan  6 00:05 start.sh
dr-xr-xr-x  12 root root     0 Feb 13 00:48 sys
drwxrwxrwt   1 root root  4096 Feb 13 00:51 tmp
drwxr-xr-x   1 root root  4096 Jan 22  2021 usr
drwxr-xr-x   1 root root  4096 Jan  5 17:48 var
```

**Comment by edgd1er** [comment]
> I'm also seeing problems on an ARM architecture with 2022.2:
> 
> ```shell
> # podman exec pihole ls -al
> total 0
> d????????? ? ? ? ?            ? .
> d????????? ? ? ? ?            ? ..
> -????????? ? ? ? ?            ? bash_functions.sh
> d????????? ? ? ? ?            ? bin
> d????????? ? ? ? ?            ? boot
> d????????? ? ? ? ?            ? dev
> d????????? ? ? ? ?            ? etc
> d????????? ? ? ? ?            ? home
> d????????? ? ? ? ?            ? lib
> d????????? ? ? ? ?            ? libexec
> d????????? ? ? ? ?            ? media
> d????????? ? ? ? ?            ? mnt
> d????????? ? ? ? ?            ? opt
> d????????? ? ? ? ?            ? proc
> d????????? ? ? ? ?            ? root
> d????????? ? ? ? ?            ? run
> -????????? ? ? ? ?            ? s6-init
> d????????? ? ? ? ?            ? sbin
> d????????? ? ? ? ?            ? srv
> -????????? ? ? ? ?            ? start.sh
> d????????? ? ? ? ?            ? sys
> d????????? ? ? ? ?            ? tmp
> d????????? ? ? ? ?            ? usr
> d????????? ? ? ? ?            ? var
> ls: cannot access 'dev': Operation not permitted
> ls: cannot access 'tmp': Operation not permitted
> ls: cannot access '.': Operation not permitted
> ls: cannot access 'usr': Operation not permitted
> ls: cannot access 'home': Operation not permitted
> ls: cannot access 'lib': Operation not permitted
> ls: cannot access 'boot': Operation not permitted
> ls: cannot access 'root': Operation not permitted
> ls: cannot access 'var': Operation not permitted
> ls: cannot access 'media': Operation not permitted
> ls: cannot access 'run': Operation not permitted
> ls: cannot access 'sys': Operation not permitted
> ls: cannot access 'etc': Operation not permitted
> ls: cannot access 'bin': Operation not permitted
> ls: cannot access 'opt': Operation not permitted
> ls: cannot access 'proc': Operation not permitted
> ls: cannot access '..': Operation not permitted
> ls: cannot access 'sbin': Operation not permitted
> ls: cannot access 'mnt': Operation not permitted
> ls: cannot access 'srv': Operation not permitted
> ls: cannot access 'bash_functions.sh': Operation not permitted
> ls: cannot access 'start.sh': Operation not permitted
> ls: cannot access 's6-init': Operation not permitted
> ls: cannot access 'libexec': Operation not permitted
> Error: non zero exit code: 1: OCI runtime error
> ```
> 
> Reverting back to 2022.01.1 fixes it:
> 
> ```shell
> # podman exec pihole ls -al /
> total 124
> drwxr-xr-x   1 root root  4096 Feb 13 00:50 .
> drwxr-xr-x   1 root root  4096 Feb 13 00:50 ..
> -rw-r--r--   1 root root 13631 Jan  6 00:05 bash_functions.sh
> drwxr-xr-x   1 root root 12288 Jan 22  2021 bin
> drwxr-xr-x   2 root root  4096 Oct  3 11:00 boot
> drwxr-xr-x   5 root root   320 Feb 13 00:50 dev
> drwxr-xr-x   1 root root  4096 Feb 13 00:50 etc
> drwxr-xr-x   2 root root  4096 Oct  3 11:00 home
> drwxr-xr-x   1 root root  4096 Jan  5 17:47 lib
> drwxr-xr-x   2 root root  4096 Jan 22  2021 libexec
> drwxr-xr-x   2 root root  4096 Dec 20 01:00 media
> drwxr-xr-x   2 root root  4096 Dec 20 01:00 mnt
> drwxr-xr-x   1 root root  4096 Feb 13 00:50 opt
> dr-xr-xr-x 218 root root     0 Feb 13 00:50 proc
> drwx------   2 root root  4096 Dec 20 01:00 root
> drwxr-xr-x   1 root root  4096 Feb 13 00:50 run
> -rwxr-xr-x   1 root root   389 Feb 15  2021 s6-init
> drwxr-xr-x   1 root root  4096 Jan  6 00:07 sbin
> drwxr-xr-x   2 root root  4096 Dec 20 01:00 srv
> -rwxr-xr-x   1 root root  7846 Jan  6 00:05 start.sh
> dr-xr-xr-x  12 root root     0 Feb 13 00:48 sys
> drwxrwxrwt   1 root root  4096 Feb 13 00:51 tmp
> drwxr-xr-x   1 root root  4096 Jan 22  2021 usr
> drwxr-xr-x   1 root root  4096 Jan  5 17:48 var
> ```

execution right for others on folders is missing. why it was removed is a good question...

**Comment by patricegautier** [comment]
I confirm happiness has returned with :dev on armv7l

**Comment by PromoFaux** [comment]
Cool, so it is looking like the switch to `bullseye` caused some issues here - but I am not yet sure what. I guess we can do some more testing later (already past midnight here!)

**Comment by patricegautier** [comment]
The midnight oil is much appreciated!

**Comment by jvanenckevort** [comment]
> ```shell
> podman exec pihole ls -al
> ```

Good find, what does the following command output?

`podman exec pihole id`

**Comment by PromoFaux** [comment]
`2022.02.1`/`latest` is now even with `dev`, and should fix this issue

**Comment by MrFly72** [comment]
2022.02.1 fixed it for me, too. Thanks!

**Comment by salcatroppa** [comment]
Neither _2022.02.1_ nor _dev_ fixed this for me - @sha256:a02faea91d505d0bfc1583049f3e943f2c3afe03df574e625ffa828b16b85832 is the latest working, on amd64 though.

**Comment by PromoFaux** [comment]
@salcatroppa - likely a different problem. Please open a new issue with more details about the problem you are seeing

**Comment by PromoFaux** [comment]
@Willsr71 / @patricegautier / @jvanenckevort (and anyone else still wtchiung this issue)

I've just rebuilt `:dev` based on bullseye. Can you please tell me if the specific issue reported by the OP is applicable? I am personally unable to reproduce

![image](https://user-images.githubusercontent.com/1998970/160494739-e0c64eb5-6963-41e1-985b-f4aa98d91e41.png)

```yml
version: '3.3'
services:

  pihole:
    container_name: pihole
    hostname: pihole-docker
    image: pihole/pihole:dev
    environment:
      TZ: europe/London
      FTLCONF_REPLY_ADDR4: 192.168.1.253 
      REV_SERVER: 'true'
      REV_SERVER_DOMAIN: lan
      REV_SERVER_TARGET: 192.168.0.1
      REV_SERVER_CIDR: 192.168.0.0/16
      SKIPGRAVITYONBOOT: 1
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
    volumes:
      - ./configs/pihole/:/etc/pihole/
      - ./configs/dnsmasq.d:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    mac_address: d0:ca:ab:cd:ef:fe
    dns:
     - 8.8.8.8
    networks:
      home:
        ipv4_address: 192.168.1.253
    restart: always
```

**Comment by Willsr71** [comment]
Unfortunately it looks like the dev branch still has the issue, the debug logs look identical for that section

**Comment by PromoFaux** [comment]
Thanks for confirming. It's odd - we're seeing mixed results with this on identical hardware :D

Hopefully some other fixes in the pipeline. too, that will take us towards resolving this

**Comment by MPatzek** [comment]
I got that problem too on dev and latest:
`+ mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.orig
+ install -D -m 644 -T /etc/.pihole/advanced/lighttpd.conf.debian /etc/lighttpd/lighttpd.conf
+ touch /etc/lighttpd/external.conf
touch: setting times of '/etc/lighttpd/external.conf': Operation not permitted
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

any idea, where to dig?

**Comment by PromoFaux** [comment]
Apparently it is an issue with the `touch` command in `bullseye`. Top minds have a solution, and are working on a fix as we speak!
