### ISSUE TITLE
REV_SERVER creates invalid dnsmasq config

### ISSUE THREAD

**Issue by ssedrick** [pi-hole/docker-pi-hole#1008]
This is a: **Bug**  

## Details

I've noticed since upgrading from 2021.11 to 2022.01.1 and now 2022.02. Using the `REV_SERVER=true` and `REV_SERVER_TARGET=192.168.1.1` environment variables results in an invalid `/etc/dnsmasq.d/01-pihole.conf`

Start command:
```sh
/usr/bin/podman run --name=pihole --hostname=pihole -e TZ=America/Chicago -e ServerIP=192.168.1.14 -e WEBPASSWORD=wKR9iRrtabxPtyyeQ4grDXmWZu5J9U -e DNSSEC=false -e REV_SERVER=true -e REV_SERVER_TARGET=192.168.1.1 -e TEMPERATUREUNIT=f -e PIHOLE_DNS_="1.1.1.3;1.0.0.3" -e DNSMASQ_USER=root -v /etc/pihole:/etc/pihole:Z -v /etc/dnsmasq.d:/etc/dnsmasq.d:Z -p 80:80/tcp -p 53:53/tcp -p 53:53/udp docker.io/pihole/pihole:2022.02.1
```

This results in the following file:
```
addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list


localise-queries


no-resolv



cache-size=10000

log-queries
log-facility=/var/log/pihole.log

log-async
server=1.1.1.3
server=1.0.0.3
interface=eth0
rev-server=,192.168.1.1
server=//192.168.1.1
```
Notice that `rev-server` has an erroneous `,` before the rev server.

The error from the logs points to that line as the error:

> dnsmasq: error at line 41 of /etc/dnsmasq.d/01-pihole.conf

I've tried removing the REV_SERVER* env variables but that doesn't seem to fix it either.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

#974

## How to reproduce the issue 

1. Environment data
  * Operating System: **Fedora** 
  * Hardware: RasPi 3B+ 
  * Kernel Architecture: ArmV7 
  * Docker Install Info and version: 
    - Software source: Fedora Repository for Podman 
    - Supplimentary Software: 
  * Hardware architecture: ARMv7 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

**Comment by ssedrick** [comment]
I tried running without the dnsmasq volumen mounts, and it get's past the dnsmasq issue, but ends with a different error.

**Comment by dschaper** [comment]
You need to specify the subnet that you want to use the reverse server for.

**Comment by ssedrick** [comment]
@dschaper That is indeed the issue, thank you for pointing that out.
