### ISSUE TITLE
Fix log flush with new query database schema

### ISSUE THREAD

**Issue by DFlexy** [pi-hole/docker-pi-hole#1010]
Pls fix bug flush logs from docker

https://github.com/pi-hole/pi-hole/pull/4609/commits/f4286a4d1256d2629272d7286a4ad12bbe4aef24

**Comment by PromoFaux** [comment]
That commit is in `development`, once it hits `master` then we will release a new docker image.

the `nightly` tag has all the latest `development` commits if you're desperate for it

**Comment by DFlexy** [comment]
ty i will w8 ;)
