### ISSUE TITLE
Workaround for pihole setting its IPv4 address to 0.0.0.0

### ISSUE THREAD

**Issue by bscottm** [pi-hole/docker-pi-hole#1017]
`pihole-FTL` works outstandingly, but `pihole` in a container with `network_mode: host` has the same issue: the IPv4 address of "pi.hole" host is "0.0.0.0". The IPv6 address is "::1". Generating a debug log is inoperative within the container.

All of the configuration files are the same; I simply copied the `/etc/dnsmasq.d` and `/etc/pihole` directories to local `etc-dnsmasq.d` and `etc-pihole` as specified in the quick start `docker-compose.yml`.

Workaround: `FTLCONF_REPLY_ADDR4` should be set to the pi.hole host's appropriate IP address. `FTLCONF_REPLY_ADDR4` is probably not just recommended; it's probably mandatory.

_Originally posted by @bscottm in https://github.com/pi-hole/docker-pi-hole/issues/770#issuecomment-1065970880_

**Comment by ksejan** [comment]
Hey I'm not a tech savyy person and I didn't understand what you said, could you please explain it to me how i can fix when my pihole is set to 0.0.0.0?
