### ISSUE TITLE
PiHole Broken after docker update to 20.10.14

### ISSUE THREAD

**Issue by whizzzkid** [pi-hole/docker-pi-hole#1019]
### Versions

- Pi-hole:  v5.9 (pihole/pihole:latest)
- AdminLTE: v5.11 (pihole/pihole:latest) 
- FTL:  v5.14 (pihole/pihole:latest)

### Platform
- OS and version:  Debin Buster
- Platform:  [Docker:20.10.14](https://docs.docker.com/engine/release-notes/#201014)

### Expected behavior

Pihole service should start.

### Actual behavior / bug

Startup script fails with:
```
Starting pihole-FTL (no-daemon) as pihole
pihole-FTL: No process found
Stopping pihole-FTL
```

### Steps to reproduce

Run pihole using `docker-compose` using: https://github.com/whizzzkid/home-infrastructure/blob/main/docker-compose.yaml#L158

## Debug Token

I couldn't capture the debug as the image crashed

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

At first I thought it was a bad pihole update, but turns out it's a breaking `docker-ce` update, downgrading to `docker-ce=5:20.10.13~3-0~debian-buster` fixed the issue.
The problem looks similar to:
- https://github.com/pi-hole/pi-hole/issues/1809
- https://discourse.pi-hole.net/t/pi-hole-wont-start-after-docker-update/44454

**Comment by PromoFaux** [comment]
I'm not going to be able to troubleshoot this much, I'm currently on lunch at work and then away for the weekend... But can someone try setting the env var `DNSMASQ_USER` to `root` to see if that makes any difference?

**Comment by PromoFaux** [comment]
> Maybe the image simply needs to be rebuilt with a newer Docker version,

By all means try it locally.. I'm not sure if we can do this on GHA just yet, seems to be on 20.10.11:

https://github.com/pi-hole/docker-pi-hole/runs/5670188780?check_suite_focus=true#step:5:10

**Comment by DFlexy** [comment]
Tests OK with 
  -e DNSMASQ_USER=root \
