### ISSUE TITLE
Gravity update fails - /usr/bin/pihole-FTL: Operation not permitted

### ISSUE THREAD

**Issue by pietermsft** [pi-hole/docker-pi-hole#1040]
This is a: Bug, Run issue
  
## Details

This system has been running and updating just fine for several months. 
Pulled the latest docker image, after running a gravity DB update getting this: 

`/etc/.pihole/advanced/Scripts/database_migration/gravity-db.sh: line 22: /usr/bin/pihole-FTL: Operation not permitted
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range
  [i] No source list found, or it is empty

  [i] Preparing new gravity database...
  [✗] Unable to create new database /etc/pihole/gravity.db_temp
  /opt/pihole/gravity.sh: line 410: /usr/bin/pihole-FTL: Operation not permitted
  [✓] Cleaning up stray matter
  [✗] DNS service is NOT running`

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Windows 10, version 21H2 
  * Hardware: PC, 8GB 
  * Kernel Architecture: x86 
  * Docker Install Info and version: 
    - Software source: Office docker 
    - Supplimentary Software: 
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce

This is my update script:
`docker stop pihole
docker rm pihole

REM Clear out the Docker cache and all unused images (i.e. the out of date version of pi-hole).
docker image prune -a --force

REM Pull latest pihole container, make sure your host can resolve DNS at this point!
docker pull pihole/pihole

REM Run pihole with customized parameters (change this to match your environment)
docker run -d --name pihole -e ServerIP=192.168.1.4 -e WEBPASSWORD=xxxxxxxx -e TZ=Europe/Amsterdam -e DNS1=127.17.0.1 -e DNS2=x.x.x.x -e DNS3=x.x.x.x -p 80:80 -p 53:53/tcp -p 53:53/udp -p 443:443 --restart=unless-stopped pihole/pihole:latest

docker exec pihole pihole updateGravity
`

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by wessel145** [comment]
Experiencing the same, for me rolling back to a previous build (pihole/pihole:2022.01) fixed the problem.

**Comment by PromoFaux** [comment]
I've just pushed a new dev build that should hopefully solve this issue once and for all. It only attempts to set capabilities if they are available to the container.

Please try the dev - for those of you that don't need NET_ADMIN, please also unset this when trying the newest dev

Thanks all for your continued patience!

**Comment by pietermsft** [comment]
Pulled the dev and it's working again, thanks for not only fixing but also in a record time with 21 minutes after reporting.

**Comment by fire1ce** [comment]
> 

dev build seems to slove the problem.

**Comment by fire1ce** [comment]
> I've just pushed a new dev build that should hopefully solve this issue once and for all. It only attempts to set capabilities if they are available to the container.
> 
> Please try the dev - for those of you that don't need NET_ADMIN, please also unset this when trying the newest dev
> 
> Thanks all for your continued patience!


dev build seems to slove the problem.

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.04.1
