### ISSUE TITLE
Bug  - Clear logs and API settings tab teleporter

### ISSUE THREAD

**Issue by DFlexy** [pi-hole/docker-pi-hole#1055]
Hello pls fix bug for clear logs queries

[i] Flushing /var/log/pihole.log ...Error: in prepare, cannot modify queries because it is a view (1)

test in dev dont work - update today
test in lasted dont work - update today

test in nightly WORK (only this) - update today

![image](https://user-images.githubusercontent.com/50220928/161551333-6366e88c-3a30-478e-8cff-8e661b153558.png)

Enjoying the topic
The teleporter option is not exporting the API settings tab

**Comment by PromoFaux** [comment]
It works in nightly because it is part of a change in the development branches of the main repositories.

See here: https://discourse.pi-hole.net/t/new-docker-version-does-not-solve-pihole-flush/54654/2?u=promofaux
