### ISSUE TITLE
SSL_ERROR_INTERNAL_ERROR_ALERT after upgrade

### ISSUE THREAD

**Issue by farmerbean** [pi-hole/docker-pi-hole#1062]
### Versions

- Pi-hole:  5.9.1
- AdminLTE:  5.11
- FTL:  5.14

### Platform

- OS and version:  Docker
- Platform:  Synology + Docker

### Expected behavior

I can browse to https://pihole.fqdn.com/admin and see the admin page

### Actual behavior / bug

I get an error SSL_ERROR_INTERNAL_ERROR_ALERT in firefox and a generic 'page cannot be displayed' in other browsers

### Steps to reproduce

open browser, do not profit 

## Debug Token

- URL:  https://tricorder.pi-hole.net/jlWEMNN3/

### Screenshots

<img width="862" alt="image" src="https://user-images.githubusercontent.com/17742334/162004181-3eb5bb7d-0767-4c02-8329-3e46a0838e8b.png">

Though this may be unrelated

### Additional context

This error happened after an in-place pi-hole upgrade to the latest version (using docker pull pihole/pihole). Has been working 10/10 previously.

**Comment by thomasmerz** [comment]
Still no working solution (for me) in issue #1046 😞

**Comment by thomasmerz** [comment]
Has this issue been closed because it will still be worked on this in #1046 ? 🤔

**Comment by PromoFaux** [comment]
Because the OP reported that they were no longer seeing this issue:

https://github.com/pi-hole/docker-pi-hole/issues/1046#issuecomment-1112071363

This one is technically a duplicate of #1046, no need for two.
