### ISSUE TITLE
Multiple Server IP's or DDNS Support

### ISSUE THREAD

**Issue by JoeStratton** [pi-hole/docker-pi-hole#109]
If you give the SERVER_IP variable  a DDNS address you receive the following error on loading:

Failed Host Check: domain.duckdns.org vs 192.168.1.X, , , pi.hole, localhost, 192.168.1.X

Any way to add support for this?

**Comment by diginc** [comment]
Sure, This is possible.  Here are some technical notes if anyone tries to tackle this before I get a chance:

It requires a change in [pi-hole/AdminLTE](https://github.com/pi-hole/AdminLTE) too.  something as simple of splitting SERVER_IP into an array when a comma is found would work I'd think.

pi-hole core moved all their variables to a /etc/pihole/serverVars.txt file, we should just move SERVER_IP from PHP's env to that too if any refactoring is happening...adds a little extra work but makes it slightly easier to add/remove/change the variable.

**Comment by derkostka** [comment]
I second this. I've got pi-hole up within docker on a Synology diskstation. There, I also run an openvpn server. Now I want VPN clients to use the pi-hole DNS, thus I need two server IPs, the local LAN and the VPN Ip to be used.
