### ISSUE TITLE
Can't resolve names with AWS DNS

### ISSUE THREAD

**Issue by EvyBongers** [pi-hole/docker-pi-hole#1097]
### Versions

- Pi-hole:  v5.10
- AdminLTE:  v5.12
- FTL:  v5.15

### Platform
- Platform: Docker (`pihole/pihole:latest`)

### Expected behavior

I expect DNS names to resolve

### Actual behavior / bug

For some domains, I get no answer.

### Steps to reproduce

1. Do a DNS lookup for `slack.com`
2. Observe no response
3. Open Pi-hole admin query log
4. Search `slack.com`
5. See error `OK, answered by one.one.one.one#53 BOGUS (DNSSEC signature expired)`

## Debug Token

- URL: https://tricorder.pi-hole.net/jNthqyw1/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

DNSviz reports no errors for this domain: https://dnsviz.net/d/slack.com/dnssec/

```
$ for record_type in A DS NS; {
      dig +noall +cmd +answer +dnssec ${record_type} slack.com
}

; <<>> DiG 9.18.2 <<>> +noall +cmd +answer +dnssec A slack.com
;; global options: +cmd

; <<>> DiG 9.18.2 <<>> +noall +cmd +answer +dnssec DS slack.com
;; global options: +cmd
slack.com.		80758	IN	DS	296 13 2 601D7EC07E7DEE6E1AB6A3E5B2DA170F8353375FEA63AF2B732FAA5A 22898EA0
slack.com.		80758	IN	RRSIG	DS 8 2 86400 20220519053801 20220512042801 37269 com. pHCyawIFVnxKDu/mZC+PQpdg0qzKgEyGkT5HRmy+apqBQTz086fcKZj0 hPkOMg3j4hMZMyoEUnQr3wP5s/EdzF5fDoxzIikRH79C73DBTNf3fJWT c4rpsr/Vhlxx9MhBZnDPj0O2uZFYPn3RVOCSiBDE547IVw6LEg6X5GST 6Ffpe040rFDHzGatFowPCPenGZJ4/abAh+qIc47ir9H3Xw==

; <<>> DiG 9.18.2 <<>> +noall +cmd +answer +dnssec NS slack.com
;; global options: +cmd
slack.com.		3600	IN	NS	ns-166.awsdns-20.com.
slack.com.		3600	IN	NS	ns-606.awsdns-11.net.
slack.com.		3600	IN	NS	ns-1493.awsdns-58.org.
slack.com.		3600	IN	NS	ns-1901.awsdns-45.co.uk.
slack.com.		3600	IN	RRSIG	NS 13 2 3600 20220513125103 20220513095103 60766 slack.com. JBhPGp17tAU9rtTuq/IGWBv9HvzE51BKQKmunnqSDM2zvWxBAayJGHsz xMCoah2LRqcAMdfA6dlhWd9wnFpSBw==
```

**Comment by dschaper** [comment]
Check your date/time on the docker container and host. DNSSEC is highly dependent upon an accurate system clock.

**Comment by EvyBongers** [comment]
Time was out of sync indeed. After enabling ntp and forcing sync, it started working.
