### ISSUE TITLE
2022.04.3 only shows it's local IP (172.18.0.1) in the querys

### ISSUE THREAD

**Issue by JohnDoeIsKIng** [pi-hole/docker-pi-hole#1099]
With the current pihole version I'm only getting it's local ip in the querys. Actually I want to use pihole not as DHCP but send all querys to a firewall appliance which is also acting as DHCP.

My local net is 192.168.178.0/24, the ip of my DHCP is 192.168.178.1.

This is a: **Bug**.  

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://github.com/pi-hole/docker-pi-hole/issues/135

## How to reproduce the issue 

1. Environment data
  * Operating System: **Linux DS918plus 4.4.180+ #42661 SMP Fri Apr 1 15:33:06 CST 2022 x86_64 GNU/Linux synology_apollolake_918+** 
  * Hardware: Synology Diskstation 918+ 
  * Kernel Architecture: Intel Celeron 
  * Docker Install Info and version:
 ```Context:    default
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.3
 Storage Driver: btrfs
  Build Version: Btrfs v4.0
  Library Version: 101
 Logging Driver: db
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs db fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3fa00912415f3e9c6f82dd72119179d599efd13b
 runc version: 31cc25f16f5eba4d0f53e35374532873744f4b31
 init version: ed96d00 (expected: de40ad0)
 Security Options:
  apparmor
 Kernel Version: 4.4.180+
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.688GiB
 Name: DS918plus
 ID: GAJ3:THYJ:AK7H:EJHU:NYEF:ZFOS:FBCU:B4VU:NP4R:AWCZ:XYRI:B62F
 Docker Root Dir: /volume4/@docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory TCP limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

  - Software source: DSM7 
  - Supplimentary Software: Synology DS918+
  * Hardware architecture:  x86 

2. docker-compose.yml:
```
version: "3"

  services:
    pihole:
      container_name: pihole
      image: pihole/pihole:latest
      ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "8080:80/tcp"
      environment:
        TZ: 'Europe/Berlin'
        DNSMASQ_USER: 'root'
        DNSMASQ_LISTENING: 'local'
        WEBPASSWORD: 'HackMe'
        PIHOLE_DNS_: 9.9.9.9
        FTLCONF_REPLY_ADDR4: NAS-IP
      volumes:
        - './etc-pihole:/etc/pihole'
        - './etc-dnsmasq.d:/etc/dnsmasq.d'
      restart: unless-stopped
```
5. 
6. any additional info to help reproduce
I've used the Conditional Forwarding with 192.168.178.0/24 as local network and 192.168.178.1 as IP address oof my local DHCP Server.

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
Although the pihole seems to work as intended, i.e. filtering DNS querys, I'd like to see my real IP's as clients.
Any hint is warmly appreciated.
Best regards

JD.

**Comment by dschaper** [comment]
This is a configuration issue and not a bug. Can you please open a thread at https://discourse.pi-hole.net, referencing this issue's URL?

Please use the Docker section and our support team and community can help you with the proper configuration.

Thanks
