### ISSUE TITLE
Wifi?

### ISSUE THREAD

**Issue by lzunsec** [pi-hole/docker-pi-hole#1100]
Hello, is it possible to get wifi working? I just started this and I don't know how to use it. There's no information about how spawn a wifi network backed by pi-hole. Is this project for ethernet only? If so, where does the pi get the internet from? From wifi? I think this should be explicit on the readme

thanks!

**Comment by rdwebdesign** [comment]
Please, ask your questions about configuration at our [Discourse Forum](https://discourse.pi-hole.net/).

As a free open-source project run by volunteers we have very limited resources.
Thank you for your understanding.

---

**Pi-hole links:**
- Discourse Forum: https://discourse.pi-hole.net/
- Documentation: https://docs.pi-hole.net/
- Feature Requests: https://discourse.pi-hole.net/c/feature-requests/8
