### ISSUE TITLE
[cont-init.d] 05-changer-uid-gid.sh: exited 267. - Will not start

### ISSUE THREAD

**Issue by four43** [pi-hole/docker-pi-hole#1103]

**Comment by PromoFaux** [comment]
Apologies - yeah I don't think I had my reading glasses on properly earlier, I thought this issue _was_ created in the repository for the Docker repo (I have now transferred it)

> And even though I'm running a newer version of Raspberry Pi OS, I'm guessing that hardware isn't supporting something properly.

Did you try the second half of the upgrade notes in the readme, that suggests updating `libseccomp2` via backports? I put a "do so at your own risk" warning on here, but it is a relatively benign change to make (that said, don't hold me responsible if your shoes catch fire!)

> If you absolutely cannot do this, some users https://github.com/pi-hole/docker-pi-hole/issues/1042#issuecomment-1086728157 success in updating libseccomp2 via backports on debian, or similar via updates on Ubuntu. You can try this workaround at your own risk (Note, you may also find that you need the latest docker.io (more details [here](https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/))
