### ISSUE TITLE
Web GUI: "Read only Database" errors when data dir on NFS Storage

### ISSUE THREAD

**Issue by t0mcat1337** [pi-hole/docker-pi-hole#1107]
This is a: Bug

## Details
When the data volume which is mounted in the container at `/etc/pihole` is on an NFS mounted FS on the docker host, one gets strange "Read Only Database" Errors in the Web GUI.
Stumbled accross this when running pihole in a Kubernetes Cluster and using NFS as shared storage for volumes.
But this is reproducable with plain docker, too.

## How to reproduce the issue 

1. Environment data docker machine
  * Operating System: Ubuntu 22.04 LTS
  * Hardware: PC
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: OS provided
    - Supplimentary Software: docker-compose
  * Hardware architecture: x86
2. On another machine (also Ubuntu in my case) create a NFS export like this:
```
mkdir /tmp/t
vi /etc/exports
-----
....
/tmp/t	192.168.42.0/24(rw,no_root_squash,no_subtree_check,async)
-----
service nfs-server reload
```
3. On the docker machine mount the NFS export:
```
mount 192.168.42.100:/tmp/t /root/docker/pihole/data
```
4. Use this docker-compose.yml (under /root/docker/pihole)
```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
      - "1080:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'test1234'
    # Volumes store your data between container upgrades
    volumes:
      - '/root/docker/pihole/data/etc-pihole:/etc/pihole'
      - '/root/docker/pihole/data/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    restart: unless-stopped

```
5. Bring container up
```
docker-compose up -d
```

6. Notice: Initial setup works fine, all files (conf, db....) are created with default permissions:
```
root@docker:~/docker/pihole/data/etc-pihole# ls -al
insgesamt 13616
drwxrwxr-x 3  999  999     4096 Mai 30 20:56 .
drwxr-xr-x 4 root root     4096 Mai 30 20:38 ..
-rw-r--r-- 1 root root        0 Mai 30 20:38 custom.list
-rw-r--r-- 1  999  999        0 Mai 30 20:38 dhcp.leases
-rw-r--r-- 1 root root      651 Mai 30 20:38 dns-servers.conf
-rw-r--r-- 1 root root       17 Mai 30 20:38 GitHubVersions
-rw-rw-r-- 1  999  999 10002432 Mai 30 20:38 gravity.db
-rw-rw-r-- 1  999  999    94208 Mai 30 20:38 gravity_old.db
-rw-r--r-- 1 root root  3711089 Mai 30 20:38 list.1.raw.githubusercontent.com.domains
-rw-r--r-- 1 root root       95 Mai 30 20:38 list.1.raw.githubusercontent.com.domains.sha1
-rw-r--r-- 1 root root       20 Mai 30 20:50 localbranches
-rw-r--r-- 1 root root       65 Mai 30 20:38 local.list
-rw-r--r-- 1 root root       39 Mai 30 20:50 localversions
drwxr-xr-x 2 root root     4096 Mai 30 20:38 migration_backup
-rw-rw-r-- 1  999 root      132 Mai 30 20:38 pihole-FTL.conf
-rw-rw-r-- 1  999  999    81920 Mai 30 20:56 pihole-FTL.db
-rw-r--r-- 1 root root      233 Mai 30 20:38 setupVars.conf
-rw-r--r-- 1 root root        0 Mai 30 20:38 setupVars.conf.update.bak

```
7. Enter the GUI
8. Try to add a domain to whitelist
9. Error "Read only database":
![image](https://user-images.githubusercontent.com/3826246/171048040-6796c4f2-78a3-4862-a239-f0c420da6f90.png)

## Temporary Fix
1. Give 777 permissions to base dir `etc-pihole` and 666 to file `etc-pihole/gravity.db`:
```
root@docker:~/docker/pihole/data/# chmod 777 etc-pihole
root@docker:~/docker/pihole/data/# cd etc-pihole
root@docker:~/docker/pihole/data/etc-pihole# chmod 666 gravity.db
root@docker:~/docker/pihole/data/etc-pihole# ls -al
insgesamt 13616
drwxrwxrwx 3  999  999     4096 Mai 30 21:48 .
drwxr-xr-x 4 root root     4096 Mai 30 21:46 ..
-rw-r--r-- 1 root root        0 Mai 30 21:46 custom.list
-rw-r--r-- 1  999  999        0 Mai 30 21:46 dhcp.leases
-rw-r--r-- 1 root root      651 Mai 30 21:46 dns-servers.conf
-rw-r--r-- 1 root root       17 Mai 30 21:46 GitHubVersions
-rw-rw-rw- 1  999  999 10002432 Mai 30 21:46 gravity.db
-rw-rw-r-- 1  999  999    94208 Mai 30 21:46 gravity_old.db
-rw-r--r-- 1 root root  3711089 Mai 30 21:46 list.1.raw.githubusercontent.com.domains
-rw-r--r-- 1 root root       95 Mai 30 21:46 list.1.raw.githubusercontent.com.domains.sha1
-rw-r--r-- 1 root root       13 Mai 30 21:46 localbranches
-rw-r--r-- 1 root root       65 Mai 30 21:46 local.list
-rw-r--r-- 1 root root       22 Mai 30 21:46 localversions
drwxr-xr-x 2 root root     4096 Mai 30 21:46 migration_backup
-rw-rw-r-- 1  999 root      132 Mai 30 21:46 pihole-FTL.conf
-rw-rw-r-- 1  999  999    81920 Mai 30 21:48 pihole-FTL.db
-rw-r--r-- 1 root root      233 Mai 30 21:46 setupVars.conf
-rw-r--r-- 1 root root        0 Mai 30 21:46 setupVars.conf.update.bak
```
2. Try steps 7. - 9. again
3. Works:
![image](https://user-images.githubusercontent.com/3826246/171051595-1fc7370d-fc85-4706-b94e-31fe10979f84.png)

But when gravity.db is recreated (after updating domain lists for example), permissions are default again and the Gui shows errors again.

**Comment by dschaper** [comment]
What are the UID/GID of the directory owners on the mounted filesystem and what UID/GID are you passing in as Environment Variables for the container?

https://github.com/pi-hole/docker-pi-hole#experimental-variables

**Comment by t0mcat1337** [comment]
As you can see under my point 6, the UID/GUID of the "etc-pihole" directory is "999:999" (this line: `drwxrwxrwx 3  999  999     4096 Mai 30 21:48 .`)
As you can see in the pasted docker-compose.yml, I didn't change the images default UID/GID; there is no env-var changing it. So the default UID/GID of 999/999 (which both is named "pihole" in the container) is used. 

When doing exact the same steps just without mounting an NFS Filesystem under `/root/docker/pihole/data`, but using the local ext4 Filesystem of the docker machine, then the GUI works always as expected without having "Read only database" errors and without "fixing" any permissions

So this behaviour has to be something to do with NFS, IMHO.

**Comment by rdwebdesign** [comment]
What is the output of `docker info`?

**Comment by dschaper** [comment]
The fact that a `chmod 777` gives access to the files leads me to believe that this is a user permission issue. I'd double check that uid:gid 999 can write to the NFS mount. It appears that user is being seen as Other instead of a User or Group member.

**Comment by t0mcat1337** [comment]
> What is the output of `docker info`?

```
root@docker:~/docker/pihole/data# docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-27-generic
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.658GiB
 Name: docker
 ID: WHNA:5BT7:KQNH:BOLE:VHF7:YU6U:RD57:6XNZ:ETOM:WRLF:PXIX:DWIX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by rdwebdesign** [comment]
I thought you were using "Storage Driver" `aufs`, but that's not the case.

Looks like it must really be a permissions issue.

**Comment by t0mcat1337** [comment]
> The fact that a `chmod 777` gives access to the files leads me to believe that this is a user permission issue. I'd double check that uid:gid 999 can write to the NFS mount. It appears that user is being seen as Other instead of a User or Group member.

I just tried:
1.) Bring down the container: `docker-compose down`
2.) Completely empty "/root/docker/pihole/data/" ('`root@docker:~/docker/pihole/data# rm -r *`'), so dirs "etc-pihole" and "etc-dnsmasq.d" were gone, mountpoint "data" for NFS is completely empty
3.) Bring the container back up (`docker-compose up -d`), dirs were created and filled with the inital stuff and permissions:
```
root@docker:~/docker/pihole/data# ls -al
insgesamt 16
drwxr-xr-x 4 root root 4096 Mai 30 23:53 .
drwxr-xr-x 3 root root 4096 Mai 30 23:51 ..
drwxr-xr-x 2 root root 4096 Mai 30 23:53 etc-dnsmasq.d
drwxrwxr-x 3  999  999 4096 Mai 31 00:00 etc-pihole
root@docker:~/docker/pihole/data# cd etc-pihole/
root@obelix:~/docker/pihole/data/etc-pihole# ls -al
insgesamt 13616
drwxrwxr-x 3  999  999     4096 Mai 31 00:01 .
drwxr-xr-x 4 root root     4096 Mai 30 23:53 ..
-rw-r--r-- 1 root root        0 Mai 30 23:53 custom.list
-rw-r--r-- 1  999  999        0 Mai 30 23:53 dhcp.leases
-rw-r--r-- 1 root root      651 Mai 30 23:53 dns-servers.conf
-rw-r--r-- 1 root root       12 Mai 30 23:54 GitHubVersions
-rw-rw-r-- 1  999  999 10002432 Mai 30 23:54 gravity.db
-rw-rw-r-- 1  999  999    94208 Mai 30 23:53 gravity_old.db
-rw-r--r-- 1 root root  3711089 Mai 30 23:53 list.1.raw.githubusercontent.com.domains
-rw-r--r-- 1 root root       95 Mai 30 23:53 list.1.raw.githubusercontent.com.domains.sha1
-rw-r--r-- 1 root root       20 Mai 31 00:00 localbranches
-rw-r--r-- 1 root root       65 Mai 30 23:53 local.list
-rw-r--r-- 1 root root       39 Mai 31 00:00 localversions
drwxr-xr-x 2 root root     4096 Mai 30 23:53 migration_backup
-rw-rw-r-- 1  999 root      132 Mai 30 23:53 pihole-FTL.conf
-rw-rw-r-- 1  999  999    81920 Mai 31 00:01 pihole-FTL.db
-rw-r--r-- 1 root root      233 Mai 30 23:54 setupVars.conf
-rw-r--r-- 1 root root        0 Mai 30 23:53 setupVars.conf.update.bak

```
4.) Enter the container: `root@docker:~/docker/pihole/data# docker exec -it pihole bash`:
5.) Enabled user "pihole" (which is UID 999): `root@b2fc5405a7dc:/# usermod -s /bin/bash pihole`
6.) Switch to user "pihole": `root@b2fc5405a7dc:/# su pihole`
7.) Enter dir "/etc/pihole", create a file "aa", which works:

```
pihole@b2fc5405a7dc:/$ cd /etc/pihole
pihole@b2fc5405a7dc:/etc/pihole$ touch aaa
pihole@b2fc5405a7dc:/etc/pihole$ ls -al
total 13620
drwxrwxr-x 3 pihole pihole     4096 May 30  2022 .
drwxr-xr-x 1 root   root       4096 May 30 23:56 ..
-rw-r--r-- 1 root   root         12 May 30 23:54 GitHubVersions
-rw-r--r-- 1 pihole pihole        0 May 30  2022 aaa
-rw-r--r-- 1 root   root          0 May 30 23:53 custom.list
-rw-r--r-- 1 pihole pihole        0 May 30 23:53 dhcp.leases
-rw-r--r-- 1 root   root        651 May 30 23:53 dns-servers.conf
-rw-rw-r-- 1 pihole pihole 10002432 May 30 23:54 gravity.db
-rw-rw-r-- 1 pihole pihole    94208 May 30 23:53 gravity_old.db
-rw-r--r-- 1 root   root    3711089 May 30 23:53 list.1.raw.githubusercontent.com.domains
-rw-r--r-- 1 root   root         95 May 30 23:53 list.1.raw.githubusercontent.com.domains.sha1
-rw-r--r-- 1 root   root         65 May 30 23:53 local.list
-rw-r--r-- 1 root   root         13 May 30 23:53 localbranches
-rw-r--r-- 1 root   root         22 May 30 23:53 localversions
drwxr-xr-x 2 root   root       4096 May 30 23:53 migration_backup
-rw-rw-r-- 1 pihole root        132 May 30 23:53 pihole-FTL.conf
-rw-rw-r-- 1 pihole pihole    81920 May 30 23:57 pihole-FTL.db
-rw-r--r-- 1 root   root        233 May 30 23:54 setupVars.conf
-rw-r--r-- 1 root   root          0 May 30 23:53 setupVars.conf.update.bak

```
8.) Leave the container and look at the newly created file in the NFS mounted FS:
```
pihole@b2fc5405a7dc:/etc/pihole$ 
exit
root@b2fc5405a7dc:/# 
exit
root@docker:~/docker/pihole/data# cd etc-pihole/
root@docker:~/docker/pihole/data/etc-pihole# ls -al
insgesamt 13616
drwxrwxr-x 3  999  999     4096 Mai 31 00:07 .
drwxr-xr-x 4 root root     4096 Mai 30 23:53 ..
-rw-r--r-- 1  999  999        0 Mai 30 23:57 aaa
-rw-r--r-- 1 root root        0 Mai 30 23:53 custom.list
-rw-r--r-- 1  999  999        0 Mai 30 23:53 dhcp.leases
-rw-r--r-- 1 root root      651 Mai 30 23:53 dns-servers.conf
-rw-r--r-- 1 root root       12 Mai 30 23:54 GitHubVersions
-rw-rw-r-- 1  999  999 10002432 Mai 30 23:54 gravity.db
-rw-rw-r-- 1  999  999    94208 Mai 30 23:53 gravity_old.db
-rw-r--r-- 1 root root  3711089 Mai 30 23:53 list.1.raw.githubusercontent.com.domains
-rw-r--r-- 1 root root       95 Mai 30 23:53 list.1.raw.githubusercontent.com.domains.sha1
-rw-r--r-- 1 root root       20 Mai 31 00:00 localbranches
-rw-r--r-- 1 root root       65 Mai 30 23:53 local.list
-rw-r--r-- 1 root root       39 Mai 31 00:00 localversions
drwxr-xr-x 2 root root     4096 Mai 30 23:53 migration_backup
-rw-rw-r-- 1  999 root      132 Mai 30 23:53 pihole-FTL.conf
-rw-rw-r-- 1  999  999    81920 Mai 31 00:07 pihole-FTL.db
-rw-r--r-- 1 root root      233 Mai 30 23:54 setupVars.conf
-rw-r--r-- 1 root root        0 Mai 30 23:53 setupVars.conf.update.bak

```
---> Conclusion: As you can see, in the running container the user with GID 999 is able to create a file in the directory, which cames from the docker volume on the NFS mounted FS. So this is very strange, as the GUI still give "Read only Database" errors at this moment:
![grafik](https://user-images.githubusercontent.com/3826246/171063602-0db47b27-adb8-4cae-922d-3315e0f3ea59.png)

**Comment by rdwebdesign** [comment]
I'm not used to NFS mounts with docker, but I found some links that might help you:
- https://en-wiki.ikoula.com/en/Create_and_use_an_NFS_Docker_volume
- https://geko.cloud/en/nfs-volumes-docker-containers/

**Comment by t0mcat1337** [comment]
> I thought you were using "Storage Driver" `aufs`, but that's not the case.
> 
> Looks like it must really be a permissions issue.

I'm not really sure, if in case of mounted volumes, especially when they are not named volumes and so are not managed by docker (lying in "/var/lib/docker/volumes") the storage driver plays a role. The overlay fs would come into play, when creating a file in the container in a dir not mounted from the outside by a volume. But of course this file then isn't persistent and goes away when the container dies. 
So in this case, the storage driver isn't important, IMHO.

**Comment by t0mcat1337** [comment]
> I'm not used to NFS mounts with docker, but I found some links that might help you:
> 
>     * https://docs.docker.com/storage/volumes/#create-a-service-which-creates-an-nfs-volume
> 
>     * https://en-wiki.ikoula.com/en/Create_and_use_an_NFS_Docker_volume
> 
>     * https://geko.cloud/en/nfs-volumes-docker-containers/

These links deals mainly with named volumes... but for simplicity I didn't use "docker volume...." commands for creating docker - managed volumes, but simply mount an absolute FS Path, which is a NFS mounted FS. (see my docker-compose.yml, there ist no global "volumes:" section beside "services:")

**Comment by t0mcat1337** [comment]
I think I'm a little step further.... the Web Gui runs as "www-data" (the php-cgi processes, correct?) 
And so, everything coming from the Web GUI uses effectively "www-data", too.

When entering the container again, enabling the "www-data" user, switch to him and try to create a file under "/etc/pihol", this DON'T work:

```
root@docker:~/docker/pihole/data/etc-pihole# docker exec -it pihole bash
root@b2fc5405a7dc:/# usermod -s /bin/bash www-data
root@b2fc5405a7dc:/etc/pihole# su - www-data
www-data@b2fc5405a7dc:~$ cd /etc/pihole/
www-data@b2fc5405a7dc:/etc/pihole$ touch bbb
touch: cannot touch 'bbb': Permission denied
```
BUT:
The dir "/etc/pihole" is owned by "pihole:pihole", the group has write access:
```
www-data@b2fc5405a7dc:/etc$ ls -ald pihole/
drwxrwxr-x 3 pihole pihole 4096 May 30 22:36 pihole/
```
The user "www-data" is in the group "pihole":
```
www-data@b2fc5405a7dc:/etc$ groups
www-data pihole
www-data@b2fc5405a7dc:/etc$ cat /etc/group 
...
pihole:x:999:www-data
```

**Comment by rdwebdesign** [comment]
Did you try to use any of these variables?
 
<html><body>


Variable | Default | Value | Description
-- | -- | -- | --
DNSMASQ_USER | unset | <pihole\|root> | Allows changing the user that FTLDNS runs as. Default: pihole
PIHOLE_UID | debian system value | Number | Overrides image's default pihole user id to match a host user id
PIHOLE_GID | debian system value | Number | Overrides image's default pihole group id to match a host group id
WEB_UID | debian system value | Number | Overrides image's default www-data user id to match a host user id
WEB_GID | debian system value | Number | Overrides image's default www-data group id to match a host group id


</body>
</html>

**Comment by t0mcat1337** [comment]
Even though I was skeptical I changed th UID/GIDs as proposed like this in docker-compose.yml:

```
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'test1234'
      PIHOLE_UID: 1337
      PIHOLE_GID: 1337
      WEB_UID: 1342
      WEB_GID: 1342

```
As always I emptied the data dir and then started the container. Now the etc-pihole dir was created with the new UID/GID ownerships:

```
root@nfs-server:/tmp/t# ls -al
insgesamt 80
drwxr-xr-x  4 root root  4096 Mai 31 17:37 .
drwxrwxrwt 21 root root 69632 Mai 31 17:37 ..
drwxr-xr-x  2 root root  4096 Mai 31 17:37 etc-dnsmasq.d
drwxrwxr-x  3 1337 1337  4096 Mai 31 17:37 etc-pihole
root@nfs-server:/tmp/t/etc-pihole# ls -al
insgesamt 13616
drwxrwxr-x 3 1337 1337     4096 Mai 31 17:42 .
drwxr-xr-x 4 root root     4096 Mai 31 17:37 ..
-rw-r--r-- 1 root root        0 Mai 31 17:37 custom.list
-rw-r--r-- 1 1337 1337        0 Mai 31 17:37 dhcp.leases
-rw-r--r-- 1 root root      651 Mai 31 17:37 dns-servers.conf
-rw-r--r-- 1 root root       17 Mai 31 17:37 GitHubVersions
-rw-rw-r-- 1 1337 1337 10002432 Mai 31 17:37 gravity.db
-rw-rw-r-- 1 1337 1337    94208 Mai 31 17:37 gravity_old.db
-rw-r--r-- 1 root root  3711089 Mai 31 17:37 list.1.raw.githubusercontent.com.domains
-rw-r--r-- 1 root root       95 Mai 31 17:37 list.1.raw.githubusercontent.com.domains.sha1
-rw-r--r-- 1 root root       20 Mai 31 17:40 localbranches
-rw-r--r-- 1 root root       65 Mai 31 17:37 local.list
-rw-r--r-- 1 root root       39 Mai 31 17:40 localversions
drwxr-xr-x 2 root root     4096 Mai 31 17:37 migration_backup
-rw-rw-r-- 1 1337 root      132 Mai 31 17:37 pihole-FTL.conf
-rw-rw-r-- 1 1337 1337    81920 Mai 31 17:42 pihole-FTL.db
-rw-r--r-- 1 root root      233 Mai 31 17:37 setupVars.conf
-rw-r--r-- 1 root root        0 Mai 31 17:37 setupVars.conf.update.bak
```
But the WebGUI behaves identical, again "Read only Database". I mean... this was quite expectable... what would be the difference, if a UID 999 (or 33 in case of www-data) gets a "Permission denied" or a UID 1337?

I strongly assume this has somthing to do with the group ownership of the WebUser (www-data, UID 33 per default) in the PIHOLE_GID (Group pihole, 999 per default), which - as a plus - is not the primary group, but an additional one as can be checked inside the container like this:
```
root@9a8f72409e72:/# id pihole
uid=999(pihole) gid=999(pihole) groups=999(pihole)
root@9a8f72409e72:/# id www-data
uid=33(www-data) gid=33(www-data) groups=33(www-data),999(pihole)
```

The write permission to "gravity.db" for "www-data" is granted by the group "pihole", as gravity.db group ownership is "pihole" and permissions set to 664. Somewhere between the Container and the NFS Server this additional group "pihole" of "www-data" seems to get lost, so that the group - granted permission gets lost.


BTW: When changing "DNSMASQ_USER" in docker-compose.yml (lets say to 1338) the container doesn't start at all, even if the UID exists on the docker host. But that's another story .... :
```
root@docker:~/docker/pihole# docker logs pihole 
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 05-changer-uid-gid.sh: executing... 
[cont-init.d] 05-changer-uid-gid.sh: exited 0.
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole
cap[cap_net_admin] not permitted
cap[cap_sys_nice] not permitted

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
Creating empty /etc/pihole/setupVars.conf file.
Configuring default DNS servers: 8.8.8.8, 8.8.4.4
  [✓] New password set
DNSMasq binding to default interface: eth0
Added ENV to php:
			"TZ" => "Europe/Berlin",
			"PIHOLE_DOCKER_TAG" => "2022.05",
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "0.0.0.0",
			"CORS_HOSTS" => "",
			"VIRTUAL_HOST" => "0.0.0.0",
Using IPv4 and IPv6
::: setup_blocklists now setting default blocklists up: 
::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
::: Blocklists (/etc/pihole/adlists.list) now set to:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
::: Enabling Query Logging
  [i] Enabling logging...
  [✓] Logging has been enabled!
 ::: Docker start setup complete
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
  Pi-hole version is v5.10 (Latest: v5.10)
  AdminLTE version is v5.12 (Latest: v5.12)
  FTL version is v5.15 (Latest: v5.15)
  Container tag is: 2022.05
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting lighttpd
Starting pihole-FTL (no-daemon) as 1338
Starting crond
[services.d] done.
User [1338] not known
Stopping pihole-FTL
Starting pihole-FTL (no-daemon) as 1338
User [1338] not known
Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as 1338
User [1338] not known
Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as 1338
User [1338] not known
Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as 1338
User [1338] not known
Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as 1338
User [1338] not known
Stopping pihole-FTL
pihole-FTL: no process found
```

**Comment by t0mcat1337** [comment]
So in the end this (additional) group thing led to the right direction... in Debian/Ubuntu systems the NFS Server (or exactly: the rpc.mountd) is started with "--manage-gid" option. 
I don't really know, what it is good for, but removing this from "RPCMOUNTDOPTS" in /etc/default/nfs-kerner-server and restarting the NFS Server gave the www-data write permission by its group membership and so the WebGUI works as expected without errors.

Very confusing...

**Comment by rdwebdesign** [comment]
Sometimes it gets really complicated to manage permissions if we mix different file systems, especially when it involves docker.

Is it working now?

**Comment by t0mcat1337** [comment]
Yes.... with removing this Option from the NFS Server stuff, the database is writeable from the WebGUI and pihole even works normally in a Kubernetes Cluster

**Comment by rdwebdesign** [comment]
I'm glad you solve it.

I will close this issue.
Feel free to reopen it if you need.
