### ISSUE TITLE
Access denied on blocked url

### ISSUE THREAD

**Issue by ankx7** [pi-hole/docker-pi-hole#1108]
Hi!
When visit a blocked url, instead of the block page, appear this error:

Access denied!
You do not have the necessary permissions to access the requested directory or the index document does not exist.
If you think this is a server error, please contact the webmaster.
Error 403

I've tried with docker image 2022.04.3 and 2022.05
Thanks in advance

**Comment by dschaper** [comment]
You'll need to fill out the template in full for us to begin to help you.

**Comment by PromoFaux** [comment]
> When visit a blocked url, instead of the block page, appear this error:

This is intended behaviour https://docs.pi-hole.net/ftldns/blockingmode/
