### ISSUE TITLE
Still using Google DNS with PIHOLE_DNS_ variable

### ISSUE THREAD

**Issue by gelator** [pi-hole/docker-pi-hole#1116]
I'm using the PIHOLE_DNS_  environnement variable but in the web UI still, Google is stil enabled in the Upstream DNS Servers and requests are logging : "OK, answered by dns.google#53"

After disabling Google with the WebUI, requests are using the DNS resolver I mentionned in the PIHOLE_DNS_  var.

**Comment by PromoFaux** [comment]
CN you provide some more details please?.what doe your compose file look like? Startup logs? Currently we have nothing to go on....
