### ISSUE TITLE
How I can update phiole? not README

### ISSUE THREAD

**Issue by asyba** [pi-hole/docker-pi-hole#1120]
from README is missing how I can update this docker template.
If I have this running on a server for example rpi4 I have version installed [v5.3.1] but the last one is 5.10
How I can update this?
My template already have the :latest tag.
README should have steps to update, its a basic instruccion that it should be there.

**Comment by dschaper** [comment]
https://github.com/pi-hole/docker-pi-hole#upgrading-persistence-and-customizations

**Comment by iAmSaugata** [comment]
If you have Portainer installed, then you can just redeploy the container with update image option, it will download the latest image and recreate container with updated image.

**Comment by shayaknyc** [comment]
Weird, I've been running these commands for years, but suddenly, it's not updating. I keep getting a notice in the footer that there's an update, and I run all the update commands, like I have with every previous version, but after it spins up the updated container, I still see the footer notice that there's an update....am I doing something wrong?

![image](https://user-images.githubusercontent.com/13590551/178012622-18516849-12d0-4a96-9af1-0254470115ed.png)

**Comment by PromoFaux** [comment]
>I would guess that no new tag was pushed since latest versions were published

Correct

>I guess a new docker version will be released soon, unless we'll have to wait

Soon™ - going to look at it now
