### ISSUE TITLE
macvendor.db is not created

### ISSUE THREAD

**Issue by moritzbeck01** [pi-hole/docker-pi-hole#1137]
This is a: **Bug**  

## Details

The `macvendor.db` file is missing from the `/etc/pihole` directory in the container and is not automatically created on container startup or (re-)creation.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

[Reddit - macvendor.db missing](https://www.reddit.com/r/pihole/comments/co48l1/macvendordb_missing/)
[GitHub - Recent PR and how I noticed this issue](https://github.com/pi-hole/FTL/issues/1351) 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Raspberry Pi OS 64-bit Lite** 
  * Hardware: **Raspberry Pi 4 Model B 4GB RAM** 
  * Kernel Architecture: **aarch64** 
  * Docker Install Info and version: 
    - Software source: **official Docker convenience script** 
    - Supplimentary Software: **nothing that interfaces Pi-hole directly, a nginx reverse proxy for the web interface** 
  * Hardware architecture: **ARMv8**

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

docker run script:
(I use the same template for all my containers and then just change the variables at the top - sorry for formatting)
```
image=pihole/pihole:latest
name=pihole
#number=10
volume1=pihole
volume2=dnsmasq.d
docker pull $image
docker stop $name
docker rm -f $name
docker run \
        --detach \
        --dns 8.8.8.8 \
        --dns 8.8.4.4 \
        --env-file $name.env \
        --hostname $name \
        --ip 10.0.10.$number \
        --mac-address 02:42:10:00:10:$number \
        --name $name \
        --network macvlan \
        --restart unless-stopped \
        --volume $(pwd)/$name/$volume1:/etc/$volume1 \
        --volume $(pwd)/$name/$volume2:/etc/$volume2 \
        --cap-add NET_ADMIN \
        $image
```

3. any additional info to help reproduce

docker environment file:
(sorry for formatting again)
```
TZ=Europe/Berlin
WEBPASSWORD=censored
FTLCONF_REPLY_ADDR4=10.0.10.10
ADMIN_EMAIL=censored
PIHOLE_DNS_=8.8.8.8;8.8.4.4
DNSSEC=true
DNS_BOGUS_PRIV=true
DNS_FQDN_REQUIRED=true
REV_SERVER=false
DHCP_ACTIVE=true
DHCP_START=10.0.9.10
DHCP_END=10.0.9.99
DHCP_ROUTER=10.0.0.1
DHCP_LEASETIME=24
PIHOLE_DOMAIN=lan
DHCP_IPv6=false
DHCP_rapid_commit=true
VIRTUAL_HOST=censored
IPv6=true
TEMPERATUREUNIT=c
WEBUIBOXEDLAYOUT=boxed
QUERY_LOGGING=true
WEBTHEME=default-darker
```

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
- [x] Changed the DNS server IPs passed to the container from only Pi-hole's IP to only Google's IPs to eliminate the possibility that Pi-hole could not serve itself DNS to the URL of the file while running the underlying script at startup.
- [x] Checked the containers Docker logs, nothing related or anything interesting really shows up there.

**Comment by PromoFaux** [comment]
Actually, the image comes with `macvendor,db` already inside `/etc/pihole`,  however what you are observing here is that going walkies when you mount that volume to your host...

I wonder if there is a way to prevent this, let me give it some thought!

**Comment by PromoFaux** [comment]
Found it, fixed it :) Will be in the next docker release

**Comment by moritzbeck01** [comment]
> Found it, fixed it :) Will be in the next docker release

Awesome, thanks, that was fast!

Let me try to reflect:
This (probably) happened because I changed system and used the files (and not e.g. the Teleporter) from another install where I probably didn't deem the `macvendor.db` file as important enough to backup since I relied on it being recreated like all the other files that don't include any custom data from me?
And it failed because when mounting a docker volume that already contains files the whole folder is getting overwritten in the container instead of the files getting merged?
Does this also apply to other files that might not be present? Or is this special because `macvendor.db` is the only file that can be downloaded afterwards?

**Comment by PromoFaux** [comment]
>And it failed because when mounting a docker volume that already contains files the whole folder is getting overwritten in the container instead of the files getting merged?

I'm no world class expert on Docker but as far as I understand it - when you mount a directory, you replace it in it's entirety. Pi-hole has no way to know that you have done this (other than missing files it expects to see of course)

This code is run on every container start to ensure missing files/configs are set up - I guess `macvendor.db` was overlooked:

https://github.com/pi-hole/docker-pi-hole/blob/7e69551be1b76d175fffc1b8c53733e74ee82520/bash_functions.sh#L40-L72

`installConfigs` is a function sourced from the main installer, here:

https://github.com/pi-hole/pi-hole/blob/aefbe1f5b6225b7476fe08264c62da84aaa61fa0/automated%20install/basic-install.sh#L1478-L1539

**Comment by moritzbeck01** [comment]
> I'm no world class expert on Docker but as far as I understand it - when you mount a directory, you replace it in it's entirety. Pi-hole has no way to know that you have done this (other than missing files it expects to see of course)

I thought so too, but after just looking into it that seems to not be the case (from [Docker Documentation - Use volumes](https://docs.docker.com/storage/volumes/#populate-a-volume-using-a-container)):

> If you start a container which creates a new volume, as above, and the container has files or directories in the directory to be mounted (such as /app/ above), the directory’s contents are copied into the volume. The container then mounts and uses the volume, and other containers which use the volume also have access to the pre-populated content.

Or am I misinterpreting this statement?

**Comment by rdwebdesign** [comment]
If you are using a host directory (already populated with files) as a volume, then Docker calls it [`bind mount`](https://docs.docker.com/storage/bind-mounts/).

To be sure, what is the output of ` docker inspect --format="{{json .Mounts}}" [name_of_container] | jq`?

**Comment by moritzbeck01** [comment]
> If you are using a host directory (already populated with files) as a volume, then Docker calls it [`bind mount`](https://docs.docker.com/storage/bind-mounts/).
> 
> To be sure, what is the output of ` docker inspect --format="{{json .Mounts}}" [name_of_container] | jq`?

Ahh I see, the documentation for bind mounts you linked even mentions the different behavior from volumes ([Mount into a non-empty directory on the container](https://docs.docker.com/storage/bind-mounts/#mount-into-a-non-empty-directory-on-the-container)), unlike the volumes documentation:

> If you bind-mount into a non-empty directory on the container, the directory’s existing contents are obscured by the bind mount. This can be beneficial, such as when you want to test a new version of your application without building a new image. However, it can also be surprising and this behavior differs from that of [docker volumes](https://docs.docker.com/storage/volumes/).

The command then obviously returns that it's a bind mount:

`[
  {
    "Type": "bind",
    "Source": "directory/dnsmasq.d",
    "Destination": "/etc/dnsmasq.d",
    "Mode": "",
    "RW": true,
    "Propagation": "rprivate"
  },
  {
    "Type": "bind",
    "Source": "directory/pihole",
    "Destination": "/etc/pihole",
    "Mode": "",
    "RW": true,
    "Propagation": "rprivate"
  }
]`

So this will always happen to any file (where the existence is not checked and it is not (re-)created at startup) when using a bind mount with a non-empty directory.
Maybe a hint could be added to always first create the container with empty directories as bind mounts and then restore any files that one would like when coming from another system? Or do you consider this too much of an edge-case?

**Comment by moritzbeck01** [comment]
Just tested this with a container that has nothing special but DNS, volumes and networking stuff specified. Seems like this even happens when binding a previously not existing (=empty) directory using the `--volumes` flag and bind mounts... which is even used in the example?
Maybe this affects not only people that are restoring but is just not noticed since it's not logged anywhere? Can anyone confirm?

This is my tested docker run script:
```
image=pihole/pihole:latest
name=test
number=90
volume1=pihole
volume2=dnsmasq.d

docker pull $image

docker stop $name
docker rm -f $name

docker run \
	--detach \
	--dns 8.8.8.8 \
	--name $name \
	--network macvlan \
	--volume $(pwd)/$name/$volume1:/etc/$volume1 \
	--volume $(pwd)/$name/$volume2:/etc/$volume2 \
	$image
```

and this is what I have in my specified directory after container startup:
```
ls -a pihole
.               dns-servers.conf                               local.list        pihole-FTL.db
..              gravity.db                                     localbranches     setupVars.conf
GitHubVersions  gravity_old.db                                 localversions     setupVars.conf.update.bak
custom.list     list.1.raw.githubusercontent.com.domains       migration_backup
dhcp.leases     list.1.raw.githubusercontent.com.domains.sha1  pihole-FTL.conf
```

**Comment by rdwebdesign** [comment]
Did you inspect the new container? Are you sure the volumes are not `binds`?

I tested using `:latest` tag and a host directory as a volume (they appear as binds).

**Test 1:**
The host directory had all files (including `macvendor.db`) before I created the container.
The container was created and the file (`macvendor.db`) was there, inside the container.

**Test 2:**
Then I stopped the container, deleted `macvendor.db` file on host directory and started a new container.
The file was not inside the container.

---

If you start the container with an empty directory (as a bind) the container will see an empty directory, but pi-hole installer will create some files if they aren't present.

**Note:** there's a new PR to create `macvendor.db`, if it's not present.

**Comment by moritzbeck01** [comment]
> Did you inspect the new container? Are you sure the volumes are not `binds`?
> 
> I tested using `:latest` tag and a host directory as a volume (they appear as binds).
> 
> **Test 1:** The host directory had all files (including `macvendor.db`) before I created the container. The container was created and the file (`macvendor.db`) was there, inside the container.
> 
> **Test 2:** Then I stopped the container, deleted `macvendor.db` file on host directory and started a new container. The file was not inside the container.

Yes, they are also bind mounts on my side, which explain your and my previous test results (at least for now until the mentioned PR is merged into master), but I was talking about something else.

> If you start the container with an empty directory (as a bind) the container will see an empty directory (this is how docker works), but pi-hole installer will create some files if they aren't present.

When creating a completely new container (like the one in the example or in my recent docker run script above) with no files or directory present, the `macvendor.db` file is not generated, at least not for me. I don't think that is expected behavior, or am I missing something?
What happens when you run my docker run script and, if needed, adjust the parameters accordingly, so `--volumes` references a not existing directory? Do you get a `macvendor.db` file?

I know this is also gonna get fixed with the PR, but wasn't that one aimed at fixing existing installations that got broken for whatever reason? I am pointing towards something being wrong with the Docker image. As far as I know, the `macvendor.db` file should be present in the base image, which, for me and as far as I can test, it is not right now. In addition, if the file is actually missing for however many Docker installations are out there (also no clue on what the statistics on Docker vs bare metal installations are), they will all pull start pulling the file from https://ftl.pi-hole.net on the next update instead of getting it distributed through the Docker Hub images.

**Comment by rdwebdesign** [comment]
Using `:latest` tag:
- If I start the container without any volumes, the file is present.
- If I start the container using an recently created **volume**, the file is present.
- If I start the container using a **bind** to a host empty directory, there is no file (as expected).

**Comment by PromoFaux** [comment]
I've been thinking some more about this, and might actually replace it with a different mechanism entirely.

When the image is built, we could copy the installed macvrndor.db to a different/backup location - and then simply source if from there in the startup script (if it is missing or out of date) rather than download from ftl.pi-hole.net each time.

> As far as I know, the macvendor.db file should be present in the base image

It should be, correct. Try spinning up a container with zero volume or host mounts - you should (famous last words!) see it in /etc/pihole/macvendor.db

**Comment by moritzbeck01** [comment]
> * If I start the container without any volumes, the file is present.

> It should be, correct. Try spinning up a container with zero volume or host mounts - you should (famous last words!) see it in /etc/pihole/macvendor.db

Good idea, I didn't think about that!
Does that mean that the Docker documentation for bind mounts is wrong and already present files are still being overwritten even when the directory is empty? As of now I can't think of any other reason that could cause the missing `macvendor.db`.

> * If I start the container using an recently created **volume**, the file is present.
> * If I start the container using a **bind** to a host empty directory, there is no file (as expected).

Yes, but the file is only present because it has been created at some point prior to that. Why isn't it created now anymore?
Sorry, I can't seem to follow you. In what scope is this behavior expected? Do you mean because this bug report is about that? Surely the

**Comment by moritzbeck01** [comment]
> I've been thinking some more about this, and might actually replace it with a different mechanism entirely.
> 
> When the image is built, we could copy the installed macvrndor.db to a different/backup location - and then simply source if from there in the startup script (if it is missing or out of date) rather than download from ftl.pi-hole.net each time.

How about using a symlink to save some space (about 3% of the current image size) and then (optionally) use the previous script to download it if it's outdated or missing from there?

**Comment by moritzbeck01** [comment]
Btw., by comparing a fresh container with and without bind mounts, I found out that there are even more files that are getting overwritten:

- `adlists.list`
- `install.log`
- `logrotate`
- `macvendor.db`

Maybe this needs to be fundamentally changed: The container ships with no files in the /etc/pihole (dnsmasq.d seems to be fine) and everything needed is either newly created or, if there is something with a specific content, symlinked/copied from another directory on Pi-hole startup.

**Comment by PromoFaux** [comment]
> however, I'm going to look at adding it to prevent the `pihole.log` and `FTL.log` file sizes getting out of hand on a long running container

Actually, thinking about it - this does not matter. There is a daily cron job that runs at 00:00 to flush the logs, the only thing is they don't get rotated as they do on bare metal. Nobody has yet complained that the rotated files are missing, but might still be worth having it for completeness.

**Comment by moritzbeck01** [comment]
> As discussed above. A symlink may work - although that will prevent the host machine actually being able to interact with this file - not sure if that is a problem at this stage tbh

It does limit the ability to update macvendor.db yourself outside of image updates, but I can't think of a better way other than just simply copying it.

I will need to completely delete my network table once these changes are in the latest image, right? I believe the vendor information is only checked against when entering a new device into the db.
