### ISSUE TITLE
pihole on docker not starting anymore

### ISSUE THREAD

**Issue by Darkmagister** [pi-hole/docker-pi-hole#1145]
This is a: Run Issue

## Details

i have docker v 20.10.17 on my nas, and pihole latest image, few days ago i noticed that i have issue in starting the container, i've tried few solution found here (adding net_admin cap to the container, setting the dnsmasq user to root, reverting back to an older image of pihole) but nothing worked
i get this error
```
Starting pihole-FTL (no-daemon) as root
Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as root
Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as root
Stopping pihole-FTL
pihole-FTL: no process found
```

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://github.com/pi-hole/docker-pi-hole/issues/1019

## How to reproduce the issue 

1. Environment data
  * Operating System: linux asustor nas
  * Hardware: asustor nas
  * Kernel Architecture: amd64
  * Docker Install Info and version: 
    - Software source: 20.10.17
    - Supplimentary Software: portainer
  * Hardware architecture: amd64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/docker-pi-hole/issues/1042#issuecomment-1086728157

**Comment by PromoFaux** [comment]
Also, do you have something else (host, another container?) listening on port 53? That can cause issues, too.

**Comment by Darkmagister** [comment]
> Also, do you have something else (host, another container?) listening on port 53? That can cause issues, too.

yes that was the issue i had a subsystem ubuntu with a resolver at port 53 ... disabling it now pihole work again thanks
