### ISSUE TITLE
Container not starting

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/docker-pi-hole#1153]
```
Existing DNS servers detected in setupVars.conf. Leaving them alone
::: Pre existing WEBPASSWORD found
DNSMasq binding to default interface: eth0
Added ENV to php:
			"TZ" => "",
			"PIHOLE_DOCKER_TAG" => "2022.04.3",
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "0.0.0.0",
			"CORS_HOSTS" => "",
			"VIRTUAL_HOST" => "0.0.0.0",
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
::: Enabling Query Logging
  [i] Enabling logging...

  [✓] Logging has been enabled!
 ::: Docker start setup complete
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.1 (Latest: v5.16.1)
  Container tag is: 2022.04.3
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting lighttpd
Starting pihole-FTL (no-daemon) as pihole
Starting crond
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
Stopping lighttpd
s6-svc: fatal: unable to control /var/run/s6/services/lighttpd-access-log: supervisor not listening
s6-svc: fatal: unable to control /var/run/s6/services/lighttpd-error-log: supervisor not listening
Stopping pihole-FTL
Stopping cron
s6-svwait: fatal: supervisor died
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 05-changer-uid-gid.sh: executing... 
[cont-init.d] 05-changer-uid-gid.sh: exited 0.
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [i] Installing /etc/dnsmasq.d/01-pihole.conf...
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [i] Installing /etc/.pihole/advanced/06-rfc6761.conf...
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
Applying pihole-FTL.conf setting REPLY_ADDR4=0.0.0.0
Existing DNS servers detected in setupVars.conf. Leaving them alone
::: Pre existing WEBPASSWORD found
DNSMasq binding to default interface: eth0
Added ENV to php:
			"TZ" => "",
			"PIHOLE_DOCKER_TAG" => "2022.04.3",
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "0.0.0.0",
			"CORS_HOSTS" => "",
			"VIRTUAL_HOST" => "0.0.0.0",
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
::: Enabling Query Logging
  [i] Enabling logging...

  [✓] Logging has been enabled!
 ::: Docker start setup complete
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.1 (Latest: v5.16.1)
  Container tag is: 2022.04.3
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting crond
Starting pihole-FTL (no-daemon) as pihole
Starting lighttpd
[services.d] done.
Stopping lighttpd
Stopping cron
Stopping pihole-FTL
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svc: fatal: unable to control /var/run/s6/services/lighttpd-access-log: supervisor not listening
s6-svc: fatal: unable to control /var/run/s6/services/lighttpd-error-log: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

If I restart the Pi then the container does not start with the message in the log
```
s6-svc: fatal: unable to control /var/run/s6/services/lighttpd-access-log: supervisor not listening
s6-svc: fatal: unable to control /var/run/s6/services/lighttpd-error-log: supervisor not listening
```

_Originally posted by @SnakeEate98r in https://github.com/pi-hole/docker-pi-hole/issues/1072#issuecomment-1191820636_

**Comment by PromoFaux** [comment]
@SnakeEate98r, please try the :dev tag once the following job has completed building:

https://github.com/pi-hole/docker-pi-hole/runs/7456030015?check_suite_focus=true

---

```
[✓] Pi-hole blocking is enabled
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service _gravityonboot: stopping
s6-rc: info: service lighttpd: stopping
s6-rc: info: service cron: stopping
s6-rc: info: service _gravityonboot successfully stopped
Stopping lighttpd
Stopping cron
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service cron successfully stopped
s6-rc: info: service lighttpd successfully stopped
s6-rc: info: service pihole-FTL: stopping
Stopping pihole-FTL
s6-rc: info: service pihole-FTL successfully stopped
s6-rc: info: service _startup: stopping
s6-rc: info: service _startup successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

Not Working

---

> How long after seeing [✓] Pi-hole blocking is enabled do things start stopping? Please open a new issue as this might be something different (include logs from /var/log/pihole if you can, please. (you might need to mount that directory to the host)

---

>the problem occurred when I changed the dev channel and then completely restarted the server

**Comment by PromoFaux** [comment]
@SnakeEate98r - I'm pretty sure we have a different issue here. Can you please try and get the requested logs?

**Comment by SnakeEate98r** [comment]
[i] Target: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 2190 domains
  [i] List stayed unchanged

  [i] Target: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
  [i] Status: Pending...
  [✓] Status: No changes detected
  [i] Analyzed 63 domains

  [i] Target: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADomains.txt
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 53945 domains
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 8214 domains
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 57 domains
  [i] List stayed unchanged

  [i] Target: https://urlhaus.abuse.ch/downloads/hostfile/
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 1087 domains
  [i] List has been updated

  [i] Target: https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/domains.txt
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 1438 domains
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/namePlayer/dhl-scamlist/main/dns-blocklists/pihole-blacklist
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 127 domains
  [i] List stayed unchanged

  [i] Target: https://zerodot1.gitlab.io/CoinBlockerLists/hosts
  [i] Status: Pending...
  [✓] Status: No changes detected
  [i] Analyzed 273733 domains

  [i] Target: https://dbl.oisd.nl/
  [i] Status: Pending...
  [✓] Status: No changes detected
  [i] Analyzed 1269885 domains

  [i] Target: https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/multi.txt
  [i] Status: Pending...
  [✗] Status: Not found
  [✗] List download failed: no cached list available

  [i] Target: https://v.firebog.net/hosts/static/w3kbl.txt
  [i] Status: Pending...
  [✓] Status: No changes detected
  [i] Analyzed 356 domains

  [i] Target: https://raw.githubusercontent.com/SoftCreatR/fakerando-domains/main/all.txt
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 57579 domains
  [i] List stayed unchanged

  [i] Creating new gravity databases...
  [✓] Creating new gravity databases
  [i] Storing downloaded domains in new gravity database...
  [✓] Storing downloaded domains in new gravity database
  [i] Building tree...
  [✓] Building tree
  [i] Swapping databases...
  [✓] Swapping databases
  [✓] The old database remains available.
  [i] Number of gravity domains: 10831640 (9394059 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 7
  [i] Number of regex whitelist filters: 0
  [i] Cleaning up stray matter...
  [✓] Cleaning up stray matter

  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service _gravityonboot: stopping
s6-rc: info: service lighttpd: stopping
s6-rc: info: service cron: stopping
s6-rc: info: service _gravityonboot successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
Stopping lighttpd
Stopping cron
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service cron successfully stopped
s6-rc: info: service lighttpd successfully stopped
s6-rc: info: service pihole-FTL: stopping
Stopping pihole-FTL
s6-rc: info: service pihole-FTL successfully stopped
s6-rc: info: service _startup: stopping
s6-rc: info: service _startup successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by SnakeEate98r** [comment]
After restarting the entire server, the error comes

I'm in the dev channel
Server up to date


os : Rapianos
raspberry PI 3b

**Comment by PromoFaux** [comment]
OK, lets try another angle.

Please provide the docker-compose or docker run script you are using to create/start the container.

**Comment by SnakeEate98r** [comment]
![Unbenannt](https://user-images.githubusercontent.com/21102847/180308119-ffd9a1d6-5eea-4804-acd7-1600c0f0b0b3.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/21102847/180308122-e0333ca9-03c3-4fd5-87d2-7d3bd467eb6e.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/21102847/180308128-778318a8-549f-48eb-a4f1-c6757bdf9e16.PNG)
![Unbenannt5](https://user-images.githubusercontent.com/21102847/180308134-c5ffd2eb-df19-4c76-a14a-9a3738bdde41.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/21102847/180308137-b8013f91-7639-41c1-ab15-934c18b44904.PNG)

**Comment by SnakeEate98r** [comment]
i use portainer

**Comment by SnakeEate98r** [comment]
do you have Discord?

**Comment by PromoFaux** [comment]
Your env still has old variables in it. You need to _completely destroy_ the container (docker stop pihole && docker rm pihole) and then create a new one when you change image/upgrade

**Comment by SnakeEate98r** [comment]
what is the new env?

**Comment by rdwebdesign** [comment]
To test using Portainer, I recommend you to start a new test container:

- Go to "Containers" and click on your current Pi-hole container to view its details.
- In "Container details ", click on `Duplicate/Edit` button.
- You will create a new container, so CHANGE the name of the container to `piholetest`, for example.
- Make sure you are using the correct image `pihole/pihole:dev`;
- Scroll down to "Advanced container settings":
    - **Volumes tab:** remove all volumes (we don't need them to this first test);
    - **Env tab:** remove all ENV variables (lets use the default values);
    - **Labels tab:** remove all labels;
- Scroll up a little and click on `Deploy the container` button.

**Comment by SnakeEate98r** [comment]
[i] Target: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 2190 domains
  [i] List stayed unchanged

  [i] Target: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
  [i] Status: Pending...
  [✓] Status: No changes detected
  [i] Analyzed 63 domains

  [i] Target: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADomains.txt
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 53963 domains
  [i] List has been updated

  [i] Target: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 8214 domains
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 57 domains
  [i] List stayed unchanged

  [i] Target: https://urlhaus.abuse.ch/downloads/hostfile/
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 1081 domains
  [i] List has been updated

  [i] Target: https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/domains.txt
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 1438 domains
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/namePlayer/dhl-scamlist/main/dns-blocklists/pihole-blacklist
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 127 domains
  [i] List stayed unchanged

  [i] Target: https://zerodot1.gitlab.io/CoinBlockerLists/hosts
  [i] Status: Pending...
  [✓] Status: No changes detected
  [i] Analyzed 273733 domains

  [i] Target: https://dbl.oisd.nl/
  [i] Status: Pending...
  [✓] Status: No changes detected
  [i] Analyzed 1269885 domains

  [i] Target: https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/multi.txt
  [i] Status: Pending...
  [✗] Status: Not found
  [✗] List download failed: no cached list available

  [i] Target: https://v.firebog.net/hosts/static/w3kbl.txt
  [i] Status: Pending...
  [✓] Status: No changes detected
  [i] Analyzed 356 domains

  [i] Target: https://raw.githubusercontent.com/SoftCreatR/fakerando-domains/main/all.txt
  [i] Status: Pending...
  [✓] Status: Retrieval successful
  [i] Analyzed 57579 domains
  [i] List stayed unchanged

  [i] Creating new gravity databases...
  [✓] Creating new gravity databases
  [i] Storing downloaded domains in new gravity database...
  [✓] Storing downloaded domains in new gravity database
  [i] Building tree...
  [✓] Building tree
  [i] Swapping databases...
  [✓] Swapping databases
  [✓] The old database remains available.
  [i] Number of gravity domains: 10831652 (9394077 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 7
  [i] Number of regex whitelist filters: 0
  [i] Cleaning up stray matter...
  [✓] Cleaning up stray matter

  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service _gravityonboot: stopping
s6-rc: info: service lighttpd: stopping
s6-rc: info: service cron: stopping
s6-rc: info: service _gravityonboot successfully stopped
Stopping cron
s6-rc: info: service cron successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
Stopping lighttpd
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service lighttpd successfully stopped
s6-rc: info: service pihole-FTL: stopping
Stopping pihole-FTL
s6-rc: info: service pihole-FTL successfully stopped
s6-rc: info: service _startup: stopping
s6-rc: info: service _startup successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
![Unbenannt](https://user-images.githubusercontent.com/21102847/180312142-b5420b9a-7d91-447e-905d-cd0cb0f06180.PNG)

**Comment by rdwebdesign** [comment]
Did you really removed all volumes?

**Comment by SnakeEate98r** [comment]
new container with dev channel first start annd reboot of my full server pihole dont started

**Comment by rdwebdesign** [comment]
You need to REMOVE your volumes. They are still there:
![image](https://user-images.githubusercontent.com/1385443/180313117-2c8a6b0d-00e9-4f06-b120-afc45c638316.png)

**Comment by SnakeEate98r** [comment]
I made the container new 2nd instance with separate volumes that are not on the main pihole I didn't have the folder until the creation

**Comment by SnakeEate98r** [comment]
can be closed was an error in portainer thanks anyway
