### ISSUE TITLE
Latest docker tag is on FTL 5.16.1

### ISSUE THREAD

**Issue by himuura** [pi-hole/docker-pi-hole#1177]
Weird issue, RPI 4, Raspbian OS 64 bit with docker + docker compose, whenever i try to pull the new docker image it's still the 2022.07.1 with FTL 5.16.1. I cannot, for the life of me, figure what the heck is going on with the docker image...
Any help?

EDIT: switching the tag from pihole/pihole:latest to pihole/pihole:2022.08 did the trick but the latest tag is not working correctly i think...at least in my case.

**Comment by PromoFaux** [comment]
Did you `docker pull pihole/pihole:latest` before _recreating_ the container?

**Comment by rdwebdesign** [comment]
Today, `latest` = `2022.08`.

You are probably using the image you already have on your system. You need to update your local image using the command above.

**Comment by himuura** [comment]
Yes mate, I did a pull before creating. It said I had the latest image...no change on the Sha key and doing a docker-compose up -d always used the same image, dunno why. Will try to delete manually and recreate the container. The composer file is using pihole/pihole:latest as well...it's a strange issue indeed

**Comment by PromoFaux** [comment]
Just to confirm that the images are definitely correct on docker hub..

![image](https://user-images.githubusercontent.com/1998970/186509179-24c6dda5-7f71-4115-a185-5bc0f2110c44.png)

![image](https://user-images.githubusercontent.com/1998970/186509213-e5116bd2-7020-453c-8c61-aa021347fe36.png)

I'm going to close this issue out as it's not really an issue with the code, but perhaps an issue with your configuration.

For docker compose, one should upgrade the container with the following:

```
docker-compose pull
docker-compose down
docker-compose up -d
```

**Comment by himuura** [comment]
Will do, thanks mate!

**Comment by dschaper** [comment]
`docker compose up --force-recreate`
