### ISSUE TITLE
container version 2022.08.2 does not start anymore

### ISSUE THREAD

**Issue by HolgerHees** [pi-hole/docker-pi-hole#1184]
I guess it is related to my container config but I have no idea how to debug. If I start the image with docker run, it works. But if I create a container with a macvlan I get the error below. Container with image version 2022.07.1 works fine. Has anyone an idea how to debug? 

```
s6-rc: info: service cron: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service cron successfully started
Starting crond
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service _startup: starting
fix-attrs: info: applying /etc/fix-attrs.d/01-resolver-resolv
fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/05-changer-uid-gid.sh
cont-init: info: /etc/cont-init.d/05-changer-uid-gid.sh exited 0
 ::: Starting docker specific checks & setup for docker pihole/pihole
s6-rc: info: service legacy-cont-init successfully started
  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
  [i] Installing latest logrotate script...
        [i] Existing logrotate file found. No changes made.
::: Assigning password defined by Environment Variable
  [✓] New password set
Added ENV to php:
                        "TZ" => "Europe/Berlin",
                        "PIHOLE_DOCKER_TAG" => "2022.08.2",
                        "PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
                        "CORS_HOSTS" => "",
                        "VIRTUAL_HOST" => "0.0.0.0",
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Converting DNS1 to PIHOLE_DNS_
Setting DNS servers based on PIHOLE_DNS_ variable
Applying pihole-FTL.conf setting LOCAL_IPV4=0.0.0.0
FTL binding to default interface: eth0
::: Enabling Query Logging
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
::: Docker start setup complete
  Pi-hole version is v5.11.4 (Latest: ERROR)
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: warning: unable to start service _startup: command exited 111
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service cron: stopping
Stopping cron
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service cron successfully stopped
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by PromoFaux** [comment]
Something very wonky there - what does your run command/compose script look like?

Are you completely destroying the old container (except volumes) before bringing this one up?

**Comment by HolgerHees** [comment]
I'm using ansible for it

- name: create docker container
  docker_container:
    name: pihole
    image: "pihole/pihole:{{pihole_version}}"
    state: present
#    recreate: true
    env:
      TZ: "{{timezone}}"
      WEBPASSWORD: "{{vault_pihole_password}}"
      DNS1: "127.0.0.11"
      DNS2: "no"
    #capabilities:
    #  - NET_ADMIN
    log_driver: journald
    log_options:
      tag: pihole
    container_default_behavior: "compatibility"
    network_mode: "default"
    networks:
      - name: "macvlan"
        ipv4_address: "{{pihole_ip}}"
    networks_cli_compatible: yes
    volumes:
      - '{{ global_etc }}pihole/:/etc/pihole/:z'
      - '{{ global_etc }}pihole/dnsmasq.d/:/etc/dnsmasq.d/:z'
    exposed_ports:
      - "53/tcp"
      - "53/udp"
    # - "67:67/udp"
      - "80/tcp"
      - "443/tcp"
  notify: "restart pihole"

**Comment by PromoFaux** [comment]
:) I can't be much help there then as I've never used ansible.

The only thing I can hint at is to start afresh and see if you see the same things:

also to note `DNS1` and `DNS2` environment variables are deprecated, you should use the `PIHOLE_DNS_` one instead (detailed in README)

In fact, after typing this that might have given me a clue...

```
::: Docker start setup complete
  Pi-hole version is v5.11.4 (Latest: ERROR)
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
```

That suggests there is no outward connectivity from within the container, either DNS resolution or actual connection. Might be worth adding something like:

```
    dns:
     - 8.8.8.8
```

to you container definition to see if that has an effect

**Comment by HolgerHees** [comment]
I thing I found the issues.

It is, because my macvlan is blocking outgoing connections. This is normally not a problem. This is a wanted behavior. The only allowed outgoing connection is the dns forwarder connection to my other local running named. Everything else is forbidden.

With version 2022.07.1 this was working, because this was not crashing the startup. It was just showing

```
  Pi-hole version is v5.11.4 (Latest: ERROR)
  AdminLTE version is v5.13 (Latest: ERROR)
  FTL version is v5.16.1 (Latest: ERROR)
```

but was still starting.

I also not want to check for updates. Because I check for updates in dockerhub.

Do you thing there is a way to disable this update check during startup?

**Comment by PromoFaux** [comment]
An outbound connection is required to download/update adlists... how is your Pi-hole functioning with a complete outgoing connection block?

That said, I may have something to stop it from throwing the error on that call to `pihole -v`

**Comment by HolgerHees** [comment]
in my setup, only inbound connections from clients are allowed. Pihole is forwarding dns request only locally to an additional named running on the same machine.

In addition, I have an automated check which informs me, if a new pihole version is available on docker hub. This is how I update my adlists. I get a fresh version only with pihole container updates. (nearly every month)

**Comment by PromoFaux** [comment]
>this is how I update my adlists. I get a fresh version only with pihole container updates. (nearly every month)

This is not achieving what you think it is achieving...

```
volumes:
      - '{{ global_etc }}pihole/:/etc/pihole/:z'
```

While the container comes with a populated `gravity.db` inside `/etc/pihole`, you are effectively overwriting this with whatever is inside your volume mount (If you mount an empty volume to a fresh Pi-hole container, you will find that `/etc/pihole` is initially empty because of this)

What do you do if you want to add an additional adlist to your setup? 

Far be it from me to tell anyone how to run their own network - but I don't really understand the purpose of disabling outbound internet connectivity from the Pi-hole container (I guess what I'm saying is the software was never designed to be run "offline")

> for me it would help if the startup just proceed like with the previous version.

I'll think about how this can be achieved, though currently I would class this as an edge-case at best!

**Comment by HolgerHees** [comment]
sorry. I have to correct myself a bit. I think, we can close this ticket.

The described scenario is almost valid (e.g. my described update procedure) In addition, outgoing connections are not blocked on my production machine. Everything works as expected.

On my staging machine, which is a VM, outgoing connection from a macvlan are blocked and in the past, pihole was starting fine with it. This is why my CI test was not catching it. Now pihole does not start. But I will fine a workaround for it.

Thanks again a lot for your time.

I was just confused in the beginning because I was not aware about this changed behavior.

b.t.w. this is my private project where I use pihole

https://github.com/HolgerHees/smartserver
