### ISSUE TITLE
Latest Docker image fails to start on aarch64

### ISSUE THREAD

**Issue by pwestrich** [pi-hole/docker-pi-hole#1187]
This is a: **BUG**  

## Details
The latest Docker image at the time of writing fails to start due to what seems to me a missing library in the container.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar
- #1186 may be related

## How to reproduce the issue 
1. Environment data
  * Operating System: Unifi OS
  * Hardware: Unifi UDM Pro
  * Kernel Architecture: 4.19.152-al-linux-v10.2.0-v1.12.22.4309-4105ace
  * Docker Install Info and version: 
    - Software source: Docker tag 2022.08.02
    - Supplimentary Software: 
  * Hardware architecture: aarch64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here: [update_pihole.sh](https://github.com/pi-hole/docker-pi-hole/files/9438506/update_pihole.txt)

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

It appears this starts with tag 2022.08, as 2022.07.1 does not seem to exhibit the issue for me.

[Container log](https://github.com/pi-hole/docker-pi-hole/files/9438503/docker.log)

`lighttpd` is having trouble starting: `var/log/lighttpd/error-pihole.log` contains one line over and over:
`gw_backend.c.475) unlink /run/lighttpd/php.socket-0 after connect failed: Connection refused`

This would likely indicate that `php-cgi` is not starting correctly. `usr/bin/php-cgi` in the container eventually resolves to `usr/bin/php-cgi7.4`, and when you run it you get the error:
`./usr/bin/php-cgi7.4: error while loading shared libraries: libargon2.so.1: cannot open shared object file: No such file or directory`

It doesn't seem`libargon` is present anywhere within the Docker container, which is the likely culprit.

**Comment by unrelentingfox** [comment]
I am experiencing the same issue on tag:latest. My pinhole container is stuck on a reboot loop.

Changing to tag 2022.07.01 fixes the issue.

**Comment by rdwebdesign** [comment]
@pwestrich 

Your log show permission errors related to `10-dote.sh` file:
```
cont-init: info: running /etc/cont-init.d/10-dote.sh
/package/admin/s6-overlay-3.1.1.2/etc/s6-rc/scripts/cont-init: 14: /etc/cont-init.d/10-dote.sh: Permission denied
cont-init: info: /etc/cont-init.d/10-dote.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
```

This file is not part of a pi-hole image.

Try fix/change permissions for this file and try again.

**Comment by rdwebdesign** [comment]
@unrelentingfox

Are you sure you have the same issue? Are you using the same Operating System ("Unifi OS") and same hardware ("Unifi UDM Pro")?

**Comment by unrelentingfox** [comment]
Perhaps you're right, I'm experiencing a similar issue with the latest tag that seemed to be resolved by moving back to the 2022.07.1 tag.

OS: Raspbian 10 armv71
Host: Raspberry Pi 2 Model B Rev 1.1
Kernel: 5.10.103-v7+

**Comment by rdwebdesign** [comment]
@unrelentingfox 

You probably have a different issue.

I didn't saw your error messages, but I think they are different from the error messages from this issue.

Can you please verify your error messages and compare to these similar issues: #1184 and #1186?
If you find the same error messages, you can follow the solution/progress for those issues.
If your messages are different from every issue, please open a new one.

**Comment by pwestrich** [comment]
Interesting, I hadn't noticed that permission error before. It's not currently present on my currently running 2022.07.1 install and permissions currently seem correct. I'll have to see if it persists in 2022.08 next I can break the internet at home long enough to inspect it.

I still think there's something up with `lighttpd` and `php-cgi` given the other errors present. I'm pretty sure I tried the container unmodified at one point too, unfortunately I hadn't gathered that log before it disappeared into the ether.

**Comment by rdwebdesign** [comment]
For testing purposes only:
Can you try to run a different container, using the same network, but without external modifications (do not include DoTe) and without volumes?

Does it start?

**Comment by rsf123** [comment]
I'm seeing this same issue running on a k8s cluster.  My k8s environment is based on Ubuntu 20.04.

Can also confirm that rolling back to 2022.07.1 allows the containers to start on the cluster.

**Comment by pwestrich** [comment]
Running unmodified it seems to get past lighttpd starting, but stuck on "DNS resolution is currently unavailable" which I'm pretty certain is my fault.

**Comment by pwestrich** [comment]
Modified start script (`dns2` is a duplicated network with a bumped IP and MAC):
```
#!/bin/sh

set -xe

NAME='pihole2'
HOSTNAME='pi2.hole'
CONTAINER='pihole:latest'
IPv4='[REDACTED]'
IPv6='[REDACTED]'
DATA_DIR="/mnt/data/${NAME}"

cat > "${tmpdir}/Dockerfile" <<EOF
FROM "pihole/${CONTAINER}"
EOF

podman pull "pihole/${CONTAINER}"
podman build -t "${CONTAINER}" --format docker -f "${tmpdir}/Dockerfile" "${tmpdir}"
rm -rf "${tmpdir}"

set +e

podman stop "${NAME}"
podman rm "${NAME}"
podman run -d \
    --network dns2 \
    --restart always \
    --name "${NAME}" \
    --hostname "${HOSTNAME}" \
    --dns='127.0.0.1' \
    --dns='::1' \
    -e TZ='America/Chicago' \
    -e VIRTUAL_HOST="${HOSTNAME}" \
    -e PROXY_LOCATION="${HOSTNAME}" \
    -e FTLCONF_REPLY_ADDR4="${IPv4}" \
    -e FTLCONF_REPLY_ADDR6="${IPv6}" \
    -e ServerIP="${IPv4}" \
    -e ServerIPv6="${IPv6}" \
    -e WEBTHEME='default-dark' \
    "${CONTAINER}"
```

**Comment by rdwebdesign** [comment]
I think you DNS issue is your are using `127.0.0.1`, but the localhost doesn't have DNS resolution. Try adding `PIHOLE_DNS_=8.8.8.8;8.8.4.4` to your test config.

**Comment by pwestrich** [comment]
Added `-e PIHOLE_DNS_='8.8.8.8;8.8.4.4'` still no DNS resolution available... it ended up being a routing issue. Fixed that, seems to have started successfully.

Apologies for it being all my fault; I saw that error about failing to connect to the socket then the missing library when invoked manually and figured something was off. I'll see about fixing that other error you pointed out and if the issue persists... either way, might not be your problem.

**Comment by rdwebdesign** [comment]
OK.

I will close your issue, since the unmodified config works on your system.

**Suggestion:**
Use this test config as a base and try to modify it _one item_ at a time, until you get all the items you want.
Add one change and test it again.
If it's not broken, add another modification and try again.
If something breaks, try to fix it or try a different alternative.

**Comment by pwestrich** [comment]
Will do, thanks for the help.
