### ISSUE TITLE
s6-svscan: warning: unable to iopause: Operation not permitted

### ISSUE THREAD

**Issue by madzodiac** [pi-hole/docker-pi-hole#1194]
This is a: **Bug**  

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Raspian** 
  * Hardware: RasPi 3B
  * Kernel Architecture: ArmV7
  * Docker Install Info and version: Docker version 20.10.17, build 100c701
    - Software source: OS provided package
    - Supplimentary Software: 
  * Hardware architecture: ARMv7

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here3. 
```
docker run -d \
    --name pihole \
    -p 53:53/tcp -p 53:53/udp \
    -p 8099:80 \
    -v "/etc-pihole/:/etc/pihole/" \
    -v "/etc-dnsmasq.d/:/etc/dnsmasq.d/" \
    -e TZ="Europe/Berlin" \
    --dns=192.168.178.1 \
    --restart=unless-stopped \
    --hostname pi.hole \
    -e VIRTUAL_HOST="xyz.fritz.box" \
    -e PROXY_LOCATION="pi.hole" \
    -e FTLCONF_LOCAL_IPV4="192.168.178.45" \
    -e WEBPASSWORD="xyz" \
    -e PIHOLE_DNS_="9.9.9.11;149.112.112.11" \
    -e REV_SERVER=true \
    -e REV_SERVER_DOMAIN="fritz.box" \
    -e REV_SERVER_TARGET="192.168.178.1" \
    -e REV_SERVER_CIDR="192.168.178.0/24" \
    -e PIHOLE_BASE=/opt/pihole-storage  \
    pihole/pihole:latest
```

4. any additional info to help reproduce

Even still with latest release 2022.08.3 I get these log entries over and over again.
When using 2022.07.1 everything works perfectly fine.
```
"log":"s6-svscan: warning: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:03.266195824Z"}
{"log":"s6-svscan: warning: executing into .s6-svscan/crash\n","stream":"stderr","time":"2022-08-29T18:05:03.266469157Z"}
{"log":"s6-svscan crashed. Killing everything and exiting.\n","stream":"stderr","time":"2022-08-29T18:05:03.266509Z"}
{"log":"s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:03.267052487Z"}
{"log":"s6-svscan: warning: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:05.309636253Z"}
{"log":"s6-svscan: warning: executing into .s6-svscan/crash\n","stream":"stderr","time":"2022-08-29T18:05:05.30991297Z"}
{"log":"s6-svscan crashed. Killing everything and exiting.\n","stream":"stderr","time":"2022-08-29T18:05:05.31022625Z"}
{"log":"s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:05.312543115Z"}
{"log":"s6-svscan: warning: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:07.360553834Z"}
{"log":"s6-svscan: warning: executing into .s6-svscan/crash\n","stream":"stderr","time":"2022-08-29T18:05:07.360760188Z"}
{"log":"s6-svscan crashed. Killing everything and exiting.\n","stream":"stderr","time":"2022-08-29T18:05:07.362018255Z"}
{"log":"s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:07.364250484Z"}
{"log":"s6-svscan: warning: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:09.335345769Z"}
{"log":"s6-svscan: warning: executing into .s6-svscan/crash\n","stream":"stderr","time":"2022-08-29T18:05:09.335646184Z"}
{"log":"s6-svscan crashed. Killing everything and exiting.\n","stream":"stderr","time":"2022-08-29T18:05:09.338236537Z"}
{"log":"s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:09.339996737Z"}
{"log":"s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:09.34131944Z"}
{"log":"s6-svscan: warning: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:11.569470596Z"}
{"log":"s6-svscan: warning: executing into .s6-svscan/crash\n","stream":"stderr","time":"2022-08-29T18:05:11.569694033Z"}
{"log":"s6-svscan crashed. Killing everything and exiting.\n","stream":"stderr","time":"2022-08-29T18:05:11.571981366Z"}
{"log":"s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:11.574089377Z"}
{"log":"s6-svscan: warning: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:14.658955057Z"}
{"log":"s6-svscan: warning: executing into .s6-svscan/crash\n","stream":"stderr","time":"2022-08-29T18:05:14.659159483Z"}
{"log":"s6-svscan crashed. Killing everything and exiting.\n","stream":"stderr","time":"2022-08-29T18:05:14.660385259Z"}
{"log":"s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:14.663281704Z"}
{"log":"s6-svscan: warning: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:19.248281765Z"}
{"log":"s6-svscan: warning: executing into .s6-svscan/crash\n","stream":"stderr","time":"2022-08-29T18:05:19.24848515Z"}
{"log":"s6-svscan crashed. Killing everything and exiting.\n","stream":"stderr","time":"2022-08-29T18:05:19.250391391Z"}
{"log":"s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:19.252531954Z"}
{"log":"s6-svscan: warning: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:27.050841378Z"}
{"log":"s6-svscan: warning: executing into .s6-svscan/crash\n","stream":"stderr","time":"2022-08-29T18:05:27.051058564Z"}
{"log":"s6-svscan crashed. Killing everything and exiting.\n","stream":"stderr","time":"2022-08-29T18:05:27.05109622Z"}
{"log":"s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:27.053291158Z"}
{"log":"s6-svscan: warning: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:41.266843456Z"}
{"log":"s6-svscan: warning: executing into .s6-svscan/crash\n","stream":"stderr","time":"2022-08-29T18:05:41.267096111Z"}
{"log":"s6-svscan crashed. Killing everything and exiting.\n","stream":"stderr","time":"2022-08-29T18:05:41.269320163Z"}
{"log":"s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:05:41.272063588Z"}
{"log":"s6-svscan: warning: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:06:08.303466998Z"}
{"log":"s6-svscan: warning: executing into .s6-svscan/crash\n","stream":"stderr","time":"2022-08-29T18:06:08.303714185Z"}
{"log":"s6-svscan crashed. Killing everything and exiting.\n","stream":"stderr","time":"2022-08-29T18:06:08.303749445Z"}
{"log":"s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:06:08.309426398Z"}
{"log":"s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:06:08.322112643Z"}
{"log":"s6-svscan: warning: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:07:01.748393488Z"}
{"log":"s6-svscan: warning: executing into .s6-svscan/crash\n","stream":"stderr","time":"2022-08-29T18:07:01.748718122Z"}
{"log":"s6-svscan crashed. Killing everything and exiting.\n","stream":"stderr","time":"2022-08-29T18:07:01.75237571Z"}
{"log":"s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:07:01.754983354Z"}
{"log":"s6-svscan: warning: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:08:03.986092015Z"}
{"log":"s6-svscan: warning: executing into .s6-svscan/crash\n","stream":"stderr","time":"2022-08-29T18:08:03.986459773Z"}
{"log":"s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:08:03.992410996Z"}
{"log":"s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:08:03.992546933Z"}
{"log":"s6-svscan crashed. Killing everything and exiting.\n","stream":"stderr","time":"2022-08-29T18:08:03.996829518Z"}
{"log":"s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted\n","stream":"stderr","time":"2022-08-29T18:08:04.000432314Z"}
```
## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by PromoFaux** [comment]
```
 -e PIHOLE_BASE=/opt/pihole-storage  \
```

What are you attempting to do here? I think it may be the root of your issue....

**Comment by madzodiac** [comment]
I removed the line and tried again, but unfortunately with the same result:
"log":"s6-svscan: warning: unable to iopause: Operation not permitted\n","stream":"stderr","time":"2022-08-29T19:24:33.376675307Z"}
{"log":"s6-svscan: warning: executing into .s6-svscan/crash\n","stream":"stderr","time":"2022-08-29T19:24:33.376947337Z"}
{"log":"s6-svscan crashed. Killing everything and exiting.\n","stream":"stderr","time":"2022-08-29T19:24:33.37860264Z"}
{"log":"s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted\n","stream":"stderr","time":"2022-08-29T19:24:33.381178615Z"}

**Comment by PromoFaux** [comment]
Is there anything else in your logs? From container start to container finish.

**Comment by rdwebdesign** [comment]
What is the output of `apt list -a libseccomp2` on your host?

**Comment by madzodiac** [comment]
> What is the output of `apt list -a libseccomp2` on your host?

libseccomp2/unstable 2.5.4-1+b1 armhf
libseccomp2/oldstable,now 2.3.3-4 armhf  [installiert]

**Comment by madzodiac** [comment]
> Is there anything else in your logs? From container start to container finish.

sudo docker logs pihole just brings up this:
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-svscan crashed. Killing everything and exiting.
s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan crashed. Killing everything and exiting.
s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan crashed. Killing everything and exiting.
s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan crashed. Killing everything and exiting.
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan crashed. Killing everything and exiting.
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan crashed. Killing everything and exiting.
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan crashed. Killing everything and exiting.
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted

**Comment by rdwebdesign** [comment]
There is a known issue with `libseccomp2 v2.3.3-4`.

You need to install the backports version 2.5.x.

**Comment by PromoFaux** [comment]
There is a permissions issue somewhere. Can you try and run it without your volume mounts to confirm that the container starts, please?

**Comment by PromoFaux** [comment]
Also, are you using the exact same run command line when starting `2022.07.1`?

**Comment by madzodiac** [comment]
When running 2022.07.1 the logs are showing this:
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 05-changer-uid-gid.sh: executing... 
[cont-init.d] 05-changer-uid-gid.sh: exited 0.
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
Applying pihole-FTL.conf setting LOCAL_IPV4=192.168.178.45
Setting DNS servers based on PIHOLE_DNS_ variable
::: Assigning password defined by Environment Variable
  [✓] New password set
DNSMasq binding to default interface: eth0
Added ENV to php:
                        "TZ" => "Europe/Berlin",
                        "PIHOLE_DOCKER_TAG" => "2022.07.1",
                        "PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
                        "ServerIP" => "0.0.0.0",
                        "CORS_HOSTS" => "",
                        "VIRTUAL_HOST" => "xyz.fritz.box",
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
::: Enabling Query Logging
  [i] Enabling logging...
  [✓] Logging has been enabled!
 ::: Docker start setup complete
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.1 (Latest: v5.16.3)
  Container tag is: 2022.07.1
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting pihole-FTL (no-daemon) as pihole
Starting lighttpd
Starting crond
[services.d] done.

**Comment by madzodiac** [comment]
> Also, are you using the exact same run command line when starting `2022.07.1`?

except for the version, yes

**Comment by rdwebdesign** [comment]
Please, follow the instructions at the second paragraph here:
https://github.com/pi-hole/docker-pi-hole/blob/b18d9bd419fb76f1ad6a6df3a035204884837547/README.md#upgrade-notes

**Comment by madzodiac** [comment]
> There is a known issue with `libseccomp2 v2.3.3-4`.
> 
> You need to install the backports version 2.5.x.

This was the perfect hint. It works for me. Thanks a lot!
libseccomp2/unstable,now 2.5.4-1+b1 armhf  [installiert]

**Comment by ljakab** [comment]
New user here, just tried out pi-hole today with Docker. I ran into this issue, and checked if downgrading to 2022.07.1 image helps. It did. Ok, then I did the steps mentioned by @rdwebdesign and upgraded my `libseccomp2` package:

```
$ apt list -a libseccomp2
Listing... Done
libseccomp2/buster-backports,now 2.5.1-1~bpo10+1 armhf [installed,automatic]
libseccomp2/oldstable 2.3.3-4 armhf
```

I'm on a Raspberry Pi 2, with Raspbian 10.

**Comment by im-n1** [comment]
I can confirm @ljakab report that latest image doesn't work even with upgraded `libseccomp2`  in version `2.5.1.1`.

I did investigate a bit futher and indeed first most-recernt image that at least run on my odroidhc2 (armv7) is `2022.07.1` however it's UI is complete mess - probably missing some JS - see here.

![pihole_errors](https://user-images.githubusercontent.com/198654/197264862-31355496-982f-41f8-920f-cbeb8717b153.png)

I stepped down to `2022.04.2` where the UI is still mess but it seems like I can click around a bit - see here:

![pihole_errors_1](https://user-images.githubusercontent.com/198654/197265237-60f55ad8-024e-4c00-b859-ad4c645e142b.png)

Hope this helps to solve this issue quickly

**Comment by rdwebdesign** [comment]
This issue was closed by the OP, because it was solved.

If you think you have a similar problem, **please open a new issue** and don't forget to add a debug token.

**Comment by rdwebdesign** [comment]
> I can confirm **ljakab** report that latest image doesn't work...

He never said that.


What he said was:

1. _New user here, just tried out pi-hole today with Docker._
    Looks like it was his first attempt to run pi-hole docker image.

2. _I ran into this issue_
    OK. He thought he was having the same issue the OP had.

3. _and checked if downgrading to 2022.07.1 image helps. It did._
    He tested the old image and it worked for him, just like the original issue (Looks like he confirmed the issue is the same).
    (In your case, the old image is not working correctly. It is a different issue.)

4. _then I did the steps mentioned by **rdwebdesign** and upgraded my libseccomp2 package_
    He tried the fix mentioned above.

He **never** said the last step failed.

You have a different problem, please open a new issue!

**Comment by ljakab** [comment]
In case anyone lands on this issue via a search engine, I just want to say that the proper solution is to upgrade to Raspbian Bullseye. However, I didn't have the time to deal with the associated risks, so I found this workaround that helped me: https://github.com/moby/moby/issues/40734#issuecomment-868037977

**Comment by jshenabc** [comment]
> > There is a known issue with `libseccomp2 v2.3.3-4`.
> > You need to install the backports version 2.5.x.
> 
> This was the perfect hint. It works for me. Thanks a lot! libseccomp2/unstable,now 2.5.4-1+b1 armhf [installiert]

can you show me how to install the backports version 2.5.x.

**Comment by rdwebdesign** [comment]
@jshenabc 

**Note:**
This is an old issue, fixed on most recent OS versions. 
My first suggestion would be to upgrade your Operating System.

> can you show me how to install the backports version 2.5.x.

If you can't upgrade, the correct way to install the new `libseccomp2` version depends on the Linux distribution you are using (Debian, Ubuntu, CentOS, etc.).

I only installed the backports on Debian, almost one year ago.

Follow one of the Options on https://docs.linuxserver.io/faq#libseccomp
I think the best way to do it is using `apt`.
I used "Option 2",  but fell free to try the other options if you like.

**Comment by DXShelley** [comment]
> backports

https://packages.debian.org/zh-cn/bullseye/armhf/libseccomp2/download
