### ISSUE TITLE
Incomplete chart in "dashboard" and missing all graphics in "long-term data" since 2022.09

### ISSUE THREAD

**Issue by thomasmerz** [pi-hole/docker-pi-hole#1197]
Starting with 2022.09 the **chart on dashboard** for "Total queries over last 24 hours" are incomplete and **graphics in long-term data** are totally missing:

![image](https://user-images.githubusercontent.com/18568381/188223939-2041a5b6-9c5f-4a4f-86a2-cc2f9d2939aa.png)

Or totally empty for all time spans (long-term):

![image](https://user-images.githubusercontent.com/18568381/188224405-443895dd-028c-408b-8db0-6cb6b5acd403.png)

Running:
> Docker Tag 2022.09 Pi-hole [v5.12](https://github.com/pi-hole/pi-hole/releases/v5.12) FTL [v5.17](https://github.com/pi-hole/FTL/releases/v5.17) Web Interface [v5.14](https://github.com/pi-hole/AdminLTE/releases/v5.14)

Container was recreated/updated today at:
> 2022-09-02T19:17:43.051067414Z (local time: 9pm)

This is a: **Bug**  

Some other Pi-hole installations running on 2022.08.02 and 2022.08.03 have complete charts and no graphics missing.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 
  * Update to 2022.09 and have a look at the dashboard and the long-term data graphics

## These common fixes didn't work for my issue

- [ ] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

**Comment by rdwebdesign** [comment]
Are you sure your new container is accessing the same data?

My graphs are showing all data.

**Comment by thomasmerz** [comment]
Here's a **before**:

![image](https://user-images.githubusercontent.com/18568381/188226854-7e805640-f373-4f44-9ed9-65ff36552b51.png)

![image](https://user-images.githubusercontent.com/18568381/188227248-a637c4c7-f47c-41a5-a925-a8d2d4f21625.png)

And **after of some other Pi-hole instances** (recreated at 2022-09-02T19:53:43.145389124Z which is 9pm local time / 2022-09-02T19:56:38.121027743Z which is 9pm):

![image](https://user-images.githubusercontent.com/18568381/188227019-c879891c-b949-4ded-903b-40f0d2b69daf.png)

![image](https://user-images.githubusercontent.com/18568381/188227549-3cfeb629-b5a5-4d58-8e40-917730be0592.png)


Weird… both productive instances look pretty ok. So I close this issue and search/look why this single one test-installation is so curious… 🤷🏼‍♂️
