### ISSUE TITLE
Web interface version number displays as vDev if setupVars.conf already exists when creating a new container

### ISSUE THREAD

**Issue by DarkVortex127** [pi-hole/docker-pi-hole#1209]
This is a: **Run issue**

## Details

If the setupVars.conf file already exists when creating a new Pihole docker container, the WEB_ values inside the versions file are not included, which results in the web interface version number displaying as vDev on the admin web interface.

This results in the following versions file:

```
CORE_BRANCH=master
FTL_BRANCH=master
CORE_VERSION=v5.12-0-gf998eee
FTL_VERSION=v5.17
GITHUB_CORE_VERSION=v5.12
GITHUB_FTL_VERSION=v5.17
GITHUB_DOCKER_VERSION=2022.09.2
```
The following is what the versions file is expected to look like:
```
CORE_BRANCH=master
WEB_BRANCH=master
FTL_BRANCH=master
CORE_VERSION=v5.12-0-gf998eee
WEB_VERSION=v5.14.2-0-g37dbfc8
FTL_VERSION=v5.17
GITHUB_CORE_VERSION=v5.12
GITHUB_WEB_VERSION=v5.14.2
GITHUB_FTL_VERSION=v5.17
GITHUB_DOCKER_VERSION=2022.09.2
``` 

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue
```
rm -rf "$HOME/test"
mkdir -p "$HOME/test"
touch "$HOME/test/setupVars.conf"
docker run -d --name test -v "$HOME/test:/etc/pihole" pihole/pihole:2022.09.2
docker exec test cat /etc/pihole/versions
```

1. Environment data
  * Operating System: **Void Linux** 
  * Hardware: **Raspberry Pi 4 Model B Rev 1.4** 
  * Kernel Architecture: **Aarch64 Musl** 
  * Docker Install Info and version: 
    - Software source: **OS provided package** 
  * Hardware architecture: **Aarch64** 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
rm -rf "$HOME/test"
mkdir -p "$HOME/test"
touch "$HOME/test/setupVars.conf"
docker run -d --name test -v "$HOME/test:/etc/pihole" pihole/pihole:2022.09.2
```
You can read the versions file using either one of the following commands:
```
docker exec test cat /etc/pihole/versions
cat "$HOME/test/versions"
```

## These common fixes didn't work for my issue

- [ ] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

Affect versions 2022.09 and beyond. If you create a new container **without** the setupVars.conf file, then the WEB_ values inside the versions file are filled in just fine, which result in the admin web interface displaying the correct web interface version number.

If you create a new container but the setupVars.conf file **already** exists, then the WEB_ values inside the versions file are not filled in, which results in the admin web interface displaying the web interface version number as vDev.

**Comment by DarkVortex127** [comment]
I came across this issue when I noticed the admin web interface was displaying the web interface version number as vDev. My docker run shell script always manually creates the setupVars.conf file as I like to manually add the WEBPASSWORD variable inside the setupVars.conf file as I strongly prefer to store the WEBPASSWORD as a hash rather than in plain text.

The following are links to my two previous forum posts regarding the issue:
https://www.reddit.com/r/pihole/comments/xal1x9/docker_2022092_weird_web_interface_version_number/
https://discourse.pi-hole.net/t/admin-panel-displays-incorrect-web-interface-version-number/57809/3

Running the following commands do **not** solve the issue:
```
docker exec -it resolver bash
pihole updatechecker && pihole updatechecker remote
```

**Comment by rdwebdesign** [comment]
**First of all:**
store the hash is not really safer than store the password. Both can allow the access to the web interface.
As I said you before on Discourse, you should set the password on your docker command or compose file. 

**Second:**
the issue is not a pi-hole error.

After testing I found out the problem is on your process, creating an incomplete `setupVars.conf` and causing the issue.

The issue never happens if I copy a `setupVars.conf` file from other container into the volume and start the container.

When you manually created the file, you added only a few options (including WEBPASSWORD), but you left out some options needed inside a docker container.
You didn't include the "INSTALL_WEB_INTERFACE=true" option, that's why you saw `vDev` on the footer.


If you insist in set the password using the file, you need to include `INSTALL_WEB_INTERFACE` variable.

**Comment by DarkVortex127** [comment]
> you need to include `INSTALL_WEB_INTERFACE` variable

This was the answer I was looking for. This solves the issue.

**Comment by DarkVortex127** [comment]
Can one of the devs delete this issue and all of my comments? I am wanting to delete my Github account, but would like to delete all of my posts, issues, and comments first though.

Thank you very much <3
