### ISSUE TITLE
DNSMASQ_LISTENING is ignored on docker start

### ISSUE THREAD

**Issue by Links2004** [pi-hole/docker-pi-hole#1211]
### Versions
-  Pi-hole version is v5.12.1 (Latest: v5.12.1)
-  AdminLTE version is v5.15 (Latest: v5.15)
-  FTL version is v5.18 (Latest: v5.18)

### Platform
- OS and version:  Debian 11
- Platform:  Docker / K8S

### Actual behavior / bug

the env DNSMASQ_LISTENING does not setup `/etc/dnsmasq.d/01-pihole.conf` correctly.
e.g. 
```
interface=eth0
```
is included and the 
```
except-interface nonexisting
```
is missing.

looks like that the problem is a mismatch in the cfg generator between `automated%20install/basic-install.sh` and `advanced/Scripts/webpage.sh`

what makes the problem worse is the fact that the UI shows the DNSMASQ_LISTENING settings correct, but the underling system is not configured that way.

### Expected behavior

setting the env `DNSMASQ_LISTENING` too `àll` results in the correct configuration for dnsmasq.

### Steps to reproduce

start a fresh docker container with the DNSMASQ_LISTENING=all env and look at the dnsmasq configs

### Screenshots

![image](https://user-images.githubusercontent.com/974709/190923721-3893d4be-7fec-46fb-9add-65b5ef0379da.png)

### Additional context

pressing save once in the UI configures dnsmasq correctly, so its clearly a startup problem.
But pressing Save in the UI after each start is not good, especially since I run the docker container in a Kubernetes cluster which can restart the container at will for scheduling.

**Comment by rdwebdesign** [comment]
I'm unable to reproduce your issue.

I just started a new container, using `:latest` tag. I added `DNSMASQ_LISTENING=all`.

That's the output of `cat /etc/dnsmasq.d/01-pihole.conf` (initial comments removed):
```
addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list

localise-queries

no-resolv

cache-size=10000

log-queries
log-facility=/var/log/pihole/pihole.log

log-async
server=8.8.8.8
domain-needed
expand-hosts
bogus-priv
except-interface=nonexisting
```

---

Can you please generate and post a debug token?
Also post the docker command or compose file you are using to start your container.

**Comment by Links2004** [comment]
the container is running inside k8s so no docker command ;) 
the pihole.txt is the k8s deployment yaml.

[pihole.txt](https://github.com/pi-hole/docker-pi-hole/files/9595177/pihole.txt)
[startup.log](https://github.com/pi-hole/docker-pi-hole/files/9595172/startup.log)

Note: v5.8.1 where working fin, with the setup (yes its old)

I can try to recreate it with a docker command again tomorrow.

**Comment by rdwebdesign** [comment]
No need to use a docker command, but it would be good test to create a new container without Volumes mounted.

**Comment by Links2004** [comment]
I tried with a empty pvc / mount same result. 

finde below the docker script that reproduces it.
I basically only adapted the volumes to work like k8s.

```bash
#!/bin/bash

PIHOLE_BASE="${PIHOLE_BASE:-$(pwd)/test}"
[[ -d "$PIHOLE_BASE" ]] || mkdir -p "$PIHOLE_BASE" || { echo "Couldn't create storage directory: $PIHOLE_BASE"; exit 1; }

touch ${PIHOLE_BASE}/pihole-FTL.conf

# Note: FTLCONF_LOCAL_IPV4 should be replaced with your external ip.
docker run -d \
    --rm \
    --name pihole \
    -v "${PIHOLE_BASE}/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro" \
    -v "${PIHOLE_BASE}/etc-pihole:/etc/pihole" \
    -v "${PIHOLE_BASE}/etc-dnsmasq.d:/etc/dnsmasq.d" \
    --dns=127.0.0.1 --dns=1.1.1.1 \
    --hostname pi.hole \
    -e VIRTUAL_HOST="pi.hole" \
    -e PROXY_LOCATION="pi.hole" \
    -e FTLCONF_LOCAL_IPV4="127.0.0.1" \
    -e DNSMASQ_LISTENING="all" \
    pihole/pihole:latest

docker logs -f pihole &

printf 'Starting up pihole container '
for i in $(seq 1 20); do
    if [ "$(docker inspect -f "{{.State.Health.Status}}" pihole)" == "healthy" ] ; then
        printf ' OK'
        cat ${PIHOLE_BASE}/etc-dnsmasq.d/01-pihole.conf
        exit 0
    else
        sleep 3
        printf '.'
    fi

    if [ $i -eq 20 ] ; then
        echo -e "\nTimed out waiting for Pi-hole start, consult your container logs for more info (\`docker logs pihole\`)"
        exit 1
    fi
done;
```

**Comment by PromoFaux** [comment]
Just for fun, can you set environment `PH_VERBOSE` to `1`? This runs all the startup scripts as `bash -x`, and might provide some more insight into what is happening!

**Comment by Links2004** [comment]
looks like the problem comes from the fact how mounted config maps in k8s work.
the `/etc/pihole/pihole-FTL.conf` is a symlink to a read only file.

and the `basic-install.sh` can not handle this correctly, more or less failing silently.
with the only hint in the log being:
```
sed: cannot rename /etc/pihole/sedLLT0kx: Device or resource busy
```

which is coming from this line:
https://github.com/pi-hole/pi-hole/blob/d88629e23fcfbf52b97bf14800bfc510b0284be6/automated%20install/basic-install.sh#L1809-L1810

**Comment by PromoFaux** [comment]
Ah, yes of course - mounting a single file. You've jogged my memory:

https://github.com/pi-hole/docker-pi-hole/issues/972#issuecomment-1008013410

The line you have linked to is not run as part of the container startup script - but you're along the right lines. I note you have set the `FTLCONF_LOCAL_IPV4` environment variable, which means the error is coming from this function:

https://github.com/pi-hole/docker-pi-hole/blob/a9ecd4e7a20ccdd5b404aa70169f11b938f3e70d/src/s6/debian-root/usr/local/bin/bash_functions.sh#L208-L217

setting `PH_VERBOSE` to `1` and starting the container should confirm that it's that function that's falling over.

No reason why we can't put a bit of guarding in there to make it more obvious if the file cannot be written to, but read through the last few comments on my first link.

(Note - I don't really see why you are mounting `pihole-FTL.conf` separately from the volume mount to `/etc/pihole` - as the file lives in that mounted directory)

**Comment by Links2004** [comment]
reworked the deployment to use only the `FTLCONF_` env and as a result no need to mount the `pihole-FTL.conf` ro any more.
the only question left is will changing the env update the `pihole-FTL.conf` on every container start?

**Comment by PromoFaux** [comment]
If you change the env, the value is read into `pihole-FTL.conf` via the `changeFTLsetting` function on container start. `changeFTLsetting` is a wrapper around [this function](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/utils.sh#L19-L41) in the core repository

**Comment by igiannakas** [comment]
Having the same issue. DNSMASQ_LISTENING is reset to local after each container restart. Running the [pihole/pihole:latest] image on a Synology NAS using the built in docker service. Any help would be much appreciated!

**Comment by Links2004** [comment]
thanks for the help

**Comment by ilbarone87** [comment]
@Links2004 are you still experiencing this issue?
I've added FTLCONF_SOCKET_LISTENING to my configmap, but still not being able to get replies from outside the pod

**Comment by ilbarone87** [comment]
@Links2004 do you mind sharing your full deployment?
I've added also LOCAL_IPV4 but still same behaviour
