### ISSUE TITLE
Missing `docker_run.sh`

### ISSUE THREAD

**Issue by proofrock** [pi-hole/docker-pi-hole#1217]
This is a: **Documentation issue**  

## Details

The documentation at [docker hub](https://hub.docker.com/r/pihole/pihole) points to a non-existent "docker run script" that should be at `https://github.com/pi-hole/docker-pi-hole/blob/master/docker_run.sh`. But it's not there, and it's not in the current commit of `master` it seems.

Thanks for all your work, by the way!

**Comment by PromoFaux** [comment]
Thanks for pointing it out... I always forget to update the Docker Hub readme file (doing it automatically doesn't work because it is too big for the API)

I've updated it now, thanks!

**Comment by proofrock** [comment]
No worries, and thanks!!
