### ISSUE TITLE
Can't read or write any settings 

### ISSUE THREAD

**Issue by celsomiranda** [pi-hole/docker-pi-hole#1220]
This is a: Bug

## Details

My pi-hole admin is throwing the following error when I access the settings:

> There was a problem applying your settings.
> Debugging information:
> PHP error (2): parse_ini_file(/etc/pihole/setupVars.conf): failed to open stream: Permission denied in /var/www/html/admin/settings.php:17 

It can't read any of the settings. I even have a password defined and I access the admin panel as if it was not defined, even if I give full permissions to all files in the config directory and the "dir" itself.

## How to reproduce the issue 

1. Environment data
  * Operating System: DOCKER ARM 
  * Hardware: QNAP
  * Kernel Architecture: ArmV8 64bit
  * Docker Install Info and version: 
    - Software source: OS provided package - Container Station
    - Supplimentary Software: portainer 
    - Hardware architecture: ARMv8 64bit

2. DOCKER RUN SHELL SCRIPT
```bash
#!/bin/bash

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

PIHOLE_BASE="/share/configs/pihoe"
[[ -d "$PIHOLE_BASE" ]] || mkdir -p "$PIHOLE_BASE" || { echo "Couldn't create storage directory: $PIHOLE_BASE"; exit 1; }

docker run -d \
    --name pihole \
    --network=apps \
    --ip=172.21.0.2 \
    -e TZ="Europe/Lisbon" \
    -v "${PIHOLE_BASE}/etc-pihole:/etc/pihole" \
    -v "${PIHOLE_BASE}/etc-dnsmasq.d:/etc/dnsmasq.d" \
    --dns=127.0.0.1 --dns=1.1.1.1 \
    --restart=unless-stopped \
    --hostname pi.hole \
    -e VIRTUAL_HOST="pi.hole" \
    -e PROXY_LOCATION="pi.hole" \
    -e FTLCONF_LOCAL_IPV4="172.21.0.2" \
    -e WEBPASSWORD="papabear" \
    -e DNSMASQ_USER=root \
    -e PIHOLE_UID=0 \
    pihole/pihole:latest

printf 'Starting up pihole container '
for i in $(seq 1 20); do
    if [ "$(docker inspect -f "{{.State.Health.Status}}" pihole)" == "healthy" ] ; then
        printf ' OK'
        echo -e "\n$(docker logs pihole 2> /dev/null | grep 'password:') for your pi-hole: http://${IP}/admin/"
        exit 0
    else
        sleep 3
        printf '.'
    fi

    if [ $i -eq 20 ] ; then
        echo -e "\nTimed out waiting for Pi-hole start, consult your container logs for more info (\`docker logs pihole\`)"
        exit 1
    fi
done;
```

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

**Comment by rdwebdesign** [comment]
This looks like a permission error on your volume `${PIHOLE_BASE}/etc-pihole`.

As a test, remove both lines starting with `-v `, try again and post the results here.

**Comment by celsomiranda** [comment]
If I remove the volumes, it works.
I was sure it was one of the first things I tried. 😕 

This also happens if I delete the volume, restart the container and let it recreate it.

```bash
docker container stop pihole
rm -rf /share/configs/pihoe
docker container start pihole 
```
This recreates all the files inside the volume but it's the same as if I create the folders using the bash script. My bet is it's something during the creation of the files on the volume.

I also have to add `DNSMASQ_USER=root` and `PIHOLE_UID=0` so FTL doesn't fail to start.

**Comment by celsomiranda** [comment]
OK I managed to solve this by manipulating the `PIHOLE_GID` and `PIHOLE_UID`.

This is the resulting shell script:
```bash 

#!/bin/bash

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

PIHOLE_BASE="/share/configs/pihoe"
[[ -d "$PIHOLE_BASE" ]] || mkdir -p "$PIHOLE_BASE" || { echo "Couldn't create storage directory: $PIHOLE_BASE"; exit 1; }

docker run -d \
    --name pihole \
    --network=apps \
    --ip=172.21.0.2 \
    -e TZ="Europe/Lisbon" \
    --dns=127.0.0.1 --dns=1.1.1.1 \
    --restart=unless-stopped \
    --hostname pi.hole \
    -e VIRTUAL_HOST="pi.hole" \
    -e PROXY_LOCATION="pi.hole" \
    -e FTLCONF_LOCAL_IPV4="172.21.0.2" \
    -e WEBPASSWORD="PASSWORD" \
    -e DNSMASQ_USER=root \
    -e PIHOLE_UID=1000 \
    -e PIHOLE_GID=0 \
    -v "${PIHOLE_BASE}/etc-pihole:/etc/pihole" \
    -v "${PIHOLE_BASE}/etc-dnsmasq.d:/etc/dnsmasq.d" \
    pihole/pihole:latest

printf 'Starting up pihole container '
for i in $(seq 1 20); do
    if [ "$(docker inspect -f "{{.State.Health.Status}}" pihole)" == "healthy" ] ; then
        printf ' OK'
        echo -e "\n$(docker logs pihole 2> /dev/null | grep 'password:') for your pi-hole: http://${IP}/admin/"
        exit 0
    else
        sleep 3
        printf '.'
    fi

    if [ $i -eq 20 ] ; then
        echo -e "\nTimed out waiting for Pi-hole start, consult your container logs for more info (\`docker logs pihole\`)"
        exit 1
    fi
done;
```
