### ISSUE TITLE
Setting FTLCONF_LOCAL_IPV4 solves DNS issue, but adds Traefik proxy issue

### ISSUE THREAD

**Issue by cernst1980** [pi-hole/docker-pi-hole#1244]
I´m using pihole as DNS and DHCP server.
Therefore, I have configured host networking for the docker container.
I noticed, that the docker host itself cannot be resolved by the DNS server, although added to the local DNS records.
The hostname always gets resolved to IP 0.0.0.0 and the IP to pi.hole.

As suggested, this can be solved by setting the environment variable FTLCONF_LOCAL_IPV4 to the IP of the docker host.
Then, the name resolution is working as expected.

But now, the WebUI of pihole is not reachable by Traefik container anymore, as these containers are connected via docker bridge network, and the lighttpd listens only on the primary host and loopback interface.

When setting FTLCONF_LOCAL_IPV4 to 0.0.0.0, proxy is working, but name resolution of docker host not.

https://github.com/pi-hole/docker-pi-hole/blob/41aa699aab8346e7a9a32574d9ec168fc54490cc/src/s6/debian-root/usr/local/bin/bash_functions.sh#L345

Is there a solution, that both is working correctly, e.g. by additionally adding the docker0 IP 172.17.0.1 in /etc/lighttpd/lighttpd.conf or adding new independent variable for lighttpd bind address?

**Comment by rdwebdesign** [comment]
Did you try `macvlan` network?

**Comment by cernst1980** [comment]
Not yet.

Then I will have problems with keepalived, because traffic to virtual IP needs then to be forwarded to macvlan IP of container...

**Comment by cernst1980** [comment]
Maybe one step back.

What I originally want is bind FTL and lighttpd to all interfaces and IPs in host network mode of docker with working name resolution.

So why is the hostname and FQDN of the docker host then resolved to 0.0.0.0, even when a correct entry exists in local DNS records? (can be proved with nslookup)
Is this a bug?

Imho, setting FTLCONF_LOCAL_IPV4 is only a workaround to fix the name resolution, but it also configures the bind address for the daemons, what is not what I want and need.

Unfortunately, I was not using pihole for some time, but in the past, everything was working as expected in this mode (docker with host network).

So I guess, that the changes from ServerIP and FTLCONF_REPLY_ADDR4 to FTLCONF_LOCAL_IPV4 are the cause, because the remaining variable has multiple functions.

**Comment by PromoFaux** [comment]
> So why is the hostname and FQDN of the docker host then resolved to 0.0.0.0

https://github.com/pi-hole/docker-pi-hole/blob/41aa699aab8346e7a9a32574d9ec168fc54490cc/src/Dockerfile#L32

`FTLCONF_LOCAL_IPV4` has a default value of `0.0.0.0` (I don't know why - it's just always been this way, even back when we used `ServerIP`

> So I guess, that the changes from ServerIP and FTLCONF_REPLY_ADDR4 to FTLCONF_LOCAL_IPV4 some time ago are the cause,

I'm not so certain. The function for binding lighttpd remains the same, it's just the source of the IP address has changed...

Looking back at an old tag (randomly picked 2022.01), we can see:

https://github.com/pi-hole/docker-pi-hole/blob/2a7ea09d00f0d4f9b70259960e315f090048ed06/start.sh#L177

https://github.com/pi-hole/docker-pi-hole/blob/2a7ea09d00f0d4f9b70259960e315f090048ed06/bash_functions.sh#L187-L195

The only difference here now is the name of the variable:

https://github.com/pi-hole/docker-pi-hole/blob/41aa699aab8346e7a9a32574d9ec168fc54490cc/src/s6/debian-root/usr/local/bin/_startup.sh#L42

https://github.com/pi-hole/docker-pi-hole/blob/41aa699aab8346e7a9a32574d9ec168fc54490cc/src/s6/debian-root/usr/local/bin/bash_functions.sh#L340-L348

And actually, I still can't get it to work on an image as old as that. That said, I have only ever used `macvlan` - `host` is just too painful. and I have no idea what I'm doing there... Did a quick start with a `bridge` network type, and that also works fine.

![image](https://user-images.githubusercontent.com/1998970/204083059-e449fda8-ccac-4405-ab56-6fb7da295342.png)

**Comment by moglifreitag** [comment]
Already closed, but I had the same issue and ended up here looking for a solution.... 

This is fixed with using WEB_BIND_ADDR 
https://github.com/pi-hole/docker-pi-hole/pull/1293 

Alternatively solution: 
Instead of using host-gateway as extra host use host.containers.internal:*IPAddress* (same value as FTLCONF_LOCAL_IPV4)
