### ISSUE TITLE
Date based tag like "2022.04" is absolute and does not receive bugfix updates

### ISSUE THREAD

**Issue by quotidian-ennui** [pi-hole/docker-pi-hole#1249]
It appears that the ghcr.io images don't match the desired state that the documentation suggests.

This differs from what's in the documentation about versioning 

> 2022.04 : Date-based release that can receive bugfix updates

I _believe_ that it might be as easy as having in your github action that gets emits the docker metadata

https://github.com/pi-hole/docker-pi-hole/blob/a787e29aad4604a42eee6f553fd6df6f08461b1e/.github/workflows/test-and-build.yaml#L56-L59

```
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=schedule 
          type=ref,event=branch,enable=${{ github.event_name != 'schedule' }} 
          type=ref,event=tag 
```

This should generate the tags `2022.11.2 2022.11` against the same image.

## Details

Check the build date and digest for the images 2022.11 && 2022.11.2 in the github package registry (the dates differ).

This also appears to be the case for the associated images from hub.docker.com

(sorry I didn't fill in the rest of the template).

**Comment by PromoFaux** [comment]
It might just need the documentation updating.

In all reality the version number is only to differentiate from the previous build. The number after the month could just as easily be the day of the month - it doesn't really follow semantic versioning, and so 2022.01.1 does not nessacerily constitute re-tagging 2022.01

There is no real sensible way to do semantic versioning with this image - as it is an omni-container with three distinct packages, each with their own versions, inside. 

General rule of thumb is first build of the month gets `yyyy.mm` any additional builds that month get an incremented number at the end.

**Comment by PromoFaux** [comment]
And just to further add - I would not want to retag any known working tag with something thay could potentially be broken (it happens, we aren't perfect). As it is right now, people always have the option to roll back to the previous known working image.

**Comment by rdwebdesign** [comment]
I think the highlighted text creates a confusion: 
_"Date-based release **that can receive bugfix updates**"_.

If an update is released, there will be a new label tag. I would be wrong to change the contents of a previous image.

**Comment by PromoFaux** [comment]
Absolutely - that's the part that needs rewording. Feel free to PR something if you think of anything - I am currently on the sofa and cannot be bothered to move to the computer!

**Comment by dschaper** [comment]
I think we discussed this before as "floating tags".

So 2022.04 will float to always point to the latest bugfix release. You just pull 2022.04 again to get the 2022.04.0x, no need to edit any yaml's or bump versions.

Where things get wonky for us is that 2022.04.0x may not actually be a bug fix. It's possible that it's a change in features or updates because it contains `FTL` that was a breaking change or something similar. So good for discussion if there are ways to have a happy medium.

**Comment by quotidian-ennui** [comment]
Cool, docker tags are immutable (which I had assumed, but since your documentation said otherwise...). 

I'd argue against floating tags, given your comment chain here. Retagging 2022.11 would have caused a side-effect in that you might have had to change your "this is not the latest docker image" logic in the WebUI as well... (am I really the latest version of 2022.11, or is there a 2022.11.2 out there that's been tagged as me).

So long as `| sort -Vr | head -n 1` still works on the list of tags, I'm happy ;)

**Comment by PromoFaux** [comment]
Wording changed in #1250 , should be clearer now
