### ISSUE TITLE
Docker tag is not displayed correctly on Web UI for Version 2022.11.2

### ISSUE THREAD

**Issue by dapacman** [pi-hole/docker-pi-hole#1253]
# Docker tag is not displayed correctly on Web UI Image Tag `2022.11.2`

💡 Sorry for not using the template because it is such a small bug 💡  

## Setup

docker-compose Version:  

```bash
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
```
docker Version:  

```bash
Version:           20.10.21
```

OS Version:

```bash
PRETTY_NAME="Ubuntu 22.04.1 LTS"
```

## What i did

- Edit docker-compose `image: pihole/pihole:2022.10` to image: `pihole/pihole:2022.11.2`
- Run `docker-compose down` and `docker-compose up -d`
- Took a look on Web-UI
  - (Yes checked with different Browsers + Incognito Mode and cleared cache & also restarted Raspi)

## Screenshots

1. Web UI Screenshot (bottom of `admin` page):

![Screenshot 2022-12-15 at 10 52 18](https://user-images.githubusercontent.com/22543540/207828567-f6d2bc72-c5f3-4703-84ea-76e630c5a5b2.png)  

2. output of docker-compose ps:

![Screenshot 2022-12-15 at 10 52 50](https://user-images.githubusercontent.com/22543540/207828582-b464a888-d303-4a75-9587-49a8bacabd91.png)  

#### BTW

❗ **Thank U, nice Project!**  👍

**Comment by dapacman** [comment]
```bash
docker exec 63f3c57b862c cat /etc/pihole/versions
CORE_BRANCH=master
WEB_BRANCH=master
FTL_BRANCH=master
CORE_VERSION=v5.14.2
WEB_VERSION=v5.17
FTL_VERSION=v5.19.2
DOCKER_VERSION=2022.11.2
GITHUB_CORE_VERSION=
GITHUB_WEB_VERSION=
GITHUB_FTL_VERSION=
GITHUB_DOCKER_VERSION=
CORE_HASH=00345387
GITHUB_CORE_HASH=
WEB_HASH=da2764e5
GITHUB_WEB_HASH=
FTL_HASH=844c8b9f
GITHUB_FTL_HASH=
```

**Comment by dapacman** [comment]
It has healed itself... 🚔  I guess I was too impatient. 🚨  Thanks!

**Comment by PromoFaux** [comment]
Interesting, do the `GITHUB_` settings in `versions` now show values?

On container startup it's suppose to update that file:

https://github.com/pi-hole/docker-pi-hole/blob/a787e29aad4604a42eee6f553fd6df6f08461b1e/src/s6/debian-root/usr/local/bin/_postFTL.sh#L26-L29

Just to satisfy my curiousity - what does your compose file look like, and how are you recreating it after pointing to the newer image?

**Comment by dapacman** [comment]
current `/etc/pihole/versions`:

```bash
docker exec 63f3c57b862c cat /etc/pihole/versions
CORE_BRANCH=master
WEB_BRANCH=master
FTL_BRANCH=master
CORE_VERSION=v5.14.2
WEB_VERSION=v5.17
FTL_VERSION=v5.19.2
DOCKER_VERSION=2022.11.2
GITHUB_CORE_VERSION=
GITHUB_WEB_VERSION=
GITHUB_FTL_VERSION=
GITHUB_DOCKER_VERSION=
CORE_HASH=00345387
GITHUB_CORE_HASH=
WEB_HASH=da2764e5
GITHUB_WEB_HASH=
FTL_HASH=844c8b9f
GITHUB_FTL_HASH=
```

docker-compose File:

```bash
cat docker-compose.yml 
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole01.dahoam.docker
    hostname: pihole01.dahoam.docker
    image: pihole/pihole:2022.11.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
# using nginx proxy
#      - "8001:80/tcp"
    networks:
      - piholenet
      - nginx01_proxyconnect
    dns:
      - 172.0.0.11 
    environment:
      TZ: 'Europe/Berlin'
      PIHOLE_DNS_: '1.1.1.2;1.0.0.2'
      VIRTUAL_HOST: 'pihole.dahoam'
#     VIRTUAL_HOST: 'pihole.dahoam'
#     WEBPASSWORD: 'set a secure password here or it will be random'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
#   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
#    cap_add:
#      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

networks:
  piholenet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.42.0.0/24
         gateway: 172.42.0.1
  nginx01_proxyconnect:
    external: true
```

Editing `docker-compose.yaml` and recreate Container:  

I edit the file via `vim` or `sed` and only modify the Image Tag like `sed -i /path/to/docker-compose.yaml 's/<old.image.tag>/<new.image.tag>/g'`  

```bash
docker-compose down (remove all containers, networks and so on)
docker-compose up -d
```
(I guess I could also just do a `docker-compose up -d` but because I don't need a highly available solution and want to have it always clean I do it with the `down` followed by `up -d`.)

**Comment by PromoFaux** [comment]
Destroying and recreating is the correct way to do it in any case so that is good!

There may be some connectivity issues inside your container - though I am not sure how to begin troubleshooting. My `versions` file for comparrision:

```
admin@fappotron:~$ docker exec -it pihole cat /etc/pihole/versions
CORE_BRANCH=master
CORE_HASH=00345387
WEB_BRANCH=master
WEB_HASH=da2764e5
FTL_BRANCH=master
FTL_HASH=844c8b9f
CORE_VERSION=v5.14.2
WEB_VERSION=v5.17
FTL_VERSION=v5.19.2
GITHUB_CORE_VERSION=v5.14.2
GITHUB_CORE_HASH=00345387
GITHUB_WEB_VERSION=v5.17
GITHUB_WEB_HASH=da2764e5
GITHUB_FTL_VERSION=v5.19.2
GITHUB_FTL_HASH=844c8b9f
DOCKER_VERSION=2022.11.2
GITHUB_DOCKER_VERSION=2022.11.2
```

So the file should be being populated. May even be an acces permission on the volume...

Can I see the output of `bash -ex updatecheck.sh`, please?

**Comment by dapacman** [comment]
☃️ **With pleasure! Thank you for the support.** 🎄  

Output `bash -ex updatecheck.sh` : [pihole-issue-1253.updatecheck.txt](https://github.com/pi-hole/docker-pi-hole/files/10236973/pihole-issue-1253.updatecheck.txt)  


Files in Pihole Volumes (Host FS):  

```bash
tree
.
├── docker-compose.yml
├── etc-dnsmasq.d
│   ├── 01-pihole.conf
│   └── 06-rfc6761.conf
└── etc-pihole
    ├── adlists.list
    ├── custom.list
    ├── dhcp.leases
    ├── dns-servers.conf
    ├── gravity.db
    ├── list.1.raw.githubusercontent.com.domains
    ├── list.1.raw.githubusercontent.com.domains.sha1
    ├── local.list
    ├── logrotate
    ├── macvendor.db -> /macvendor.db
    ├── migration_backup
    │   └── adlists.list
    ├── pihole-FTL.conf
    ├── pihole-FTL.db
    ├── setupVars.conf
    ├── setupVars.conf.update.bak
    └── versions

3 directories, 19 files
```

`etc-pihole` files / Permissions:  

```bash
-rw-r--r-- 1 root root               65 Aug 19 12:15 adlists.list
-rw-r--r-- 1 root root              873 Nov  6 16:36 custom.list
-rw-r--r-- 1 lxd  docker              0 Aug 19 12:10 dhcp.leases
-rw-r--r-- 1 root root              651 Dec 15 10:43 dns-servers.conf
-rw-rw-r-- 1 lxd  docker       10194944 Sep 12 06:48 gravity.db
-rw-r--r-- 1 root root          3836905 Sep 11 17:26 list.1.raw.githubusercontent.com.domains
-rw-r--r-- 1 root root               95 Sep 11 16:42 list.1.raw.githubusercontent.com.domains.sha1
-rw-r--r-- 1 root root               65 Sep 11 17:26 local.list
-rw-r--r-- 1 root root              241 Aug 23 08:22 logrotate
lrwxrwxrwx 1 root root               13 Dec 15 10:43 macvendor.db -> /macvendor.db
drwxr-xr-x 2 root root             4096 Aug 19 12:10 migration_backup
-rw-rw-r-- 1 lxd  root              151 Dec 15 10:43 pihole-FTL.conf
-rw-rw-r-- 1 lxd  docker      201986048 Dec 15 13:38 pihole-FTL.db
-rw-r--r-- 1 root root              233 Dec 15 10:43 setupVars.conf
-rw-r--r-- 1 root root              233 Dec 15 10:43 setupVars.conf.update.bak
-rw-r--r-- 1 root root              330 Dec 15 13:32 versions
```

`etc-dnsmasq.d` files / Permissions:  

```bash
-rw-r--r-- 1 root root        1343 Dec 15 10:43 01-pihole.conf
-rw-r--r-- 1 root root        2190 Dec 15 10:43 06-rfc6761.conf
```

"versions" File in Host FS Volume `etc-pihole`:  

```bash
CORE_BRANCH=master
WEB_BRANCH=master
FTL_BRANCH=master
CORE_VERSION=v5.14.2
WEB_VERSION=v5.17
FTL_VERSION=v5.19.2
DOCKER_VERSION=2022.11.2
GITHUB_CORE_VERSION=
GITHUB_WEB_VERSION=
GITHUB_FTL_VERSION=
GITHUB_DOCKER_VERSION=
CORE_HASH=00345387
GITHUB_CORE_HASH=
WEB_HASH=da2764e5
GITHUB_WEB_HASH=
FTL_HASH=844c8b9f
GITHUB_FTL_HASH=
```

`docker-compose logs` Output : [pihole-issue-1253.composelogs.txt](https://github.com/pi-hole/docker-pi-hole/files/10237076/pihole-issue-1253.composelogs.txt)

**Comment by PromoFaux** [comment]
```
pihole01.dahoam.docker |   [✗] DNS resolution is currently unavailable
  [✗] DNS resolution is not available
```

What is the device you are using for the _container's_ DNS? :

```
    dns:
      - 172.0.0.11 
```

Because it isn't answering

(confim this wish something like `docker exec [containerid] nslookup pi-hole.net`)

**Comment by PromoFaux** [comment]
It's possibly related, yes - but it is difficult to tell! I have not personally seen an issue with the version information shown in the web inteface footer between upgrades.

Personally I just point the Pi-hole container at a public DNS server (1.1.1.1 or 8.8.8.8)

**Comment by dapacman** [comment]
Hi @PromoFaux
thanks again for the support 👍  🥇 and sorry for the late feedback. My RaspberryPi destroyed three SD cards in three days (so the Pi is broken..) So I switched to another (also more performant) x86 hardware with nvm-e. 👈 

Anyway.. 🙂 
I think the DNS was the issue and it was my own fault. The DNS resolution was not possible from the container. I now also use 8.8.8.8 or 8.8.4.4 or 1.1.1.1 etc as DNS in docker-compose for the container and it works fine.

Thank you and BR
