### ISSUE TITLE
upstream DNS set as env are not set properly after regeneration/restart of container

### ISSUE THREAD

**Issue by bitdruid** [pi-hole/docker-pi-hole#1275]
This is a: BUG 

## Details

The pihole container is set up, envs for upstream DNS were set according to readme. After the container starts/restarts or is regenerated the env seems to be set up "visually" - i can see my settings in the pihole settings-interface (for me e.g. 9.9.9.9 and 1.1.1.1) but pihole throws following warning until i click on ,,save". Until then no dns-resolution by pihole:

DNSMASQ_WARN	Warning in dnsmasq core:
no upstream servers configured

## Related Issues
- [x]  I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Rasbian bullseye 
  * Hardware: Raspi 4B 2GB
  * Kernel Architecture: ARMv8, aarch64, Kernel 5.15.84-v8+ 
  * Docker Install Info and version: 
    - Software source: docker.io official latest 20.10.22 
    - Supplimentary Software: portainer 2.16.2 community
  * Hardware architecture: ARMv8

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

> version: "3.6"
> services:
>   pihole:
>  cap_drop:
>       - "AUDIT_CONTROL"
>       - "BLOCK_SUSPEND"
>       - "DAC_READ_SEARCH"
>       - "IPC_LOCK"
>       - "IPC_OWNER"
>       - "LEASE"
>       - "LINUX_IMMUTABLE"
>       - "MAC_ADMIN"
>       - "MAC_OVERRIDE"
>       - "NET_ADMIN"
>       - "NET_BROADCAST"
>       - "SYSLOG"
>       - "SYS_ADMIN"
>       - "SYS_BOOT"
>       - "SYS_MODULE"
>       - "SYS_NICE"
>       - "SYS_PACCT"
>       - "SYS_PTRACE"
>       - "SYS_RAWIO"
>       - "SYS_RESOURCE"
>       - "SYS_TIME"
>       - "SYS_TTY_CONFIG"
>       - "WAKE_ALARM"
>     container_name: "pihole"
>     environment:
>       - "PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
>       - "phpver=php"
>       - "PHP_ENV_CONFIG=/etc/lighttpd/conf-enabled/15-fastcgi-php.conf"
>       - "PHP_ERROR_LOG=/var/log/lighttpd/error-pihole.log"
>       - "IPv6=False"
>       - "S6_KEEP_ENV=1"
>       - "S6_BEHAVIOUR_IF_STAGE2_FAILS=2"
>       - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
>       - "FTLCONF_LOCAL_IPV4=127.0.0.1"
>       - "FTL_CMD=no-daemon"
>       - "DNSMASQ_USER=pihole"
>       - "TZ=Europe/Berlin"
>       - "DNSMASQ_LISTENING=all"
>       - "PIHOLE_DNS_=1.1.1.1;9.9.9.9"
>     hostname: "pihole"
>     image: "docker.io/pihole/pihole:latest"
>     network_mode: "bridge"
>     ports:
>       - "53:53/tcp"
>       - "53:53/udp"
>       - "50001:80/tcp"
>     restart: "unless-stopped"
>     volumes:
>       - "pihole_dnsmasq:/etc/dnsmasq.d"
>       - "pihole_etc:/etc/pihole"

4. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

Debug-Log in addition (could not provide a token because no upstreams - was before clicking ,,save")

[pihole_diagnostic.txt](https://github.com/pi-hole/docker-pi-hole/files/10427086/pihole_diagnostic.txt)

![Screenshot 2023-01-16 155617](https://user-images.githubusercontent.com/49254050/212713211-d832d316-a1db-4c9d-a654-e599d223a627.png)
![Screenshot 2023-01-16 155252](https://user-images.githubusercontent.com/49254050/212713217-071f8fe6-e1c0-45db-a738-41fe73f6ab37.png)

**Comment by PromoFaux** [comment]
This is the third such case I've seen of this - but still am unable to reproduce.

@rdwebdesign saw it happen on one of his containers, and now he is unable to reproduce it again

**Comment by PromoFaux** [comment]
My only thought is maybe some sort of permissions issue on the volume. 

I was seeing some issues on one my install in the error log - but I cleared down and recreated the volumes and the errors have gone away (ignore the warnings about the config-key, those will be sorted in the next release)

![image](https://user-images.githubusercontent.com/1998970/212726061-e29dc25a-f6e3-4f0e-928b-14b4685e0afa.png)

**Comment by rdwebdesign** [comment]
I'm not sure if I can help, because I don't know what happened and I can't replicate the issue now.

I saw the same warning message when I updated one of my Pi-hole containers.
The other one, on a different Raspberry Pi was updated without issues.

**Details:**
After updating the image (from 2022.12.1 to 2023.01), the error appeared.

Using web interface **_Settings_** Page (**_DNS tab_**), I saved the same config (without changes, I just clicked on the Save button) and the warning disappeared, but restarting the image (or rebooting the machine) the warning reappeared every time.

I was using bind volumes. I didn't checked the permissions when I saw the error.

To compare the behavior, I decided to go back to the previous image (`2022.12.1`). It worked without warnings.
When I change back to `2023.01` again, the warning never appeared again. I can't replicate the previous state.

**Comment by bitdruid** [comment]
> My only thought is maybe some sort of permissions issue on the volume.
> 
> I was seeing some issues on one my install in the error log - but I cleared down and recreated the volumes and the errors have gone away (ignore the warnings about the config-key, those will be sorted in the next release)
> 
> ![image](https://user-images.githubusercontent.com/1998970/212726061-e29dc25a-f6e3-4f0e-928b-14b4685e0afa.png)

thanks for your reply! if it were necessary I could provide some logs. I rebuilt the container without persistent storage (so I doubt permission problems in the volumes?). the error remained... i took a snapshot of the system state and reverted back to my non-docker configuration. i will try to rebuild the container from scratch tomorrow

**Comment by Bortinio** [comment]
I had the same issue with 2023.01 and reverted back to 2022.12.1. Although set by the env variable PIHOLE_DNS_ the server was not written to /etc/dnsmasq.d/01-pihole.conf and as such queries did not get answered. I also noticed that the setting interface= was not set by 2023.01. With 2022.12.1 it was set to interface=eth0, although I did not set it by an env variable in the docker compose.

**Comment by djrm05** [comment]
> I had the same issue with 2023.01 and reverted back to 2022.12.1. Although set by the env variable PIHOLE_DNS_ the server was not written to /etc/dnsmasq.d/01-pihole.conf and as such queries did not get answered. I also noticed that the setting interface= was not set by 2023.01. With 2022.12.1 it was set to interface=eth0, although I did not set it by an env variable in the docker compose.

I have seen the same in 2 different containers. Just going to settings-DNS and saving fix the issue, but it appears if container is restarted.

**Comment by rdwebdesign** [comment]
@djrm05 

How are you storing the config files? using bind volumes?

Can you please post the output of `ls -ls` on the directory holding the `dnsmasq.d` config?

**Comment by Szesi111** [comment]
I have the same issue.

volumes
/home/homeassistant/pihole/etc-dnsmasq.d     /etc/dnsmasq.d
/home/homeassistant/pihole/etc-pihole            /etc/pihole


**************************************************************************
After container restart (without save):

**ls -l /home/homeassistant/pihole/etc-dnsmasq.d**
-rw-r--r-- 1 root root 1455 jan   17 09.27 01-pihole.conf
-rw-r--r-- 1 root root 2190 jan   17 09.27 06-rfc6761.conf

**cat 01-pihole.conf** 
addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list
domain-needed
localise-queries
bogus-priv
no-resolv
log-queries
log-facility=/var/log/pihole/pihole.log
log-async
interface=
cache-size=10000

******************************************************************
After save:
**ls -l /home/homeassistant/pihole/etc-dnsmasq.d**
-rw-r--r-- 1 root root 1455 jan   17 10.46 01-pihole.conf
-rw-r--r-- 1 root root 2190 jan   17 10.45 06-rfc6761.conf

**cat 01-pihole.conf** 
addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list
localise-queries
no-resolv
log-queries
log-facility=/var/log/pihole/pihole.log
log-async
cache-size=10000
server=208.67.222.222
server=208.67.220.220
interface=eth0
rev-server=192.168.199.0/24,192.168.199.1
server=/home.local/192.168.199.1
server=//192.168.199.1

**Comment by djrm05** [comment]
I'm using standard volumes (no bind).

***@***.***:/var/lib/docker/volumes/pihole_dnsmasqd/_data# ls -ls
total 16
4 -rw-r--r-- 1 root root 1352 ene 17 11:14 01-pihole.conf
4 -rwxrwxrwx 1 root root   35 ene 30  2022 02-custom.conf
4 -rw-r--r-- 1 root root 2190 ene 17 11:14 06-rfc6761.conf
4 -rw-r--r-- 1 root root   21 feb  5  2022 99-edns.conf

**Comment by kwlorenz** [comment]
Same problem here with latest pihole, had to go back to 2022.12.1, problem gone ...

**Comment by MisterBearBear** [comment]
Having the exact same problem after I've upgraded to 2023.01. Had the same observations from others:

1. The "no upstream servers configured" happened every time the container recreated or restarted. Pi-hole will run but it will not be able to handle any DNS requests (look at the blank period in the screenshot below)

![image](https://user-images.githubusercontent.com/5254176/213096178-506968b2-f40a-4629-9fa2-0cd8e3ab0663.png)

2. Go to Settings and the DNS tab, my previous upstream DNS server configurations was there even though the "no upstream servers configured" occurred.

![image](https://user-images.githubusercontent.com/5254176/213096726-1728d826-11d0-4802-8d58-6dd4180bb126.png)

3. Simply click the Save button on the Upstream DNS Server page will resolve the issue. But it will come back after the container recreated or restarted.

Hope this helps.

Hardware and Software Info:
- Raspberry Pi 4 Model B 4GB
- OSMC (Debian Bullseye) 2022.10-1
- Kernel 5.10.78-7-osmc
- Docker version 20.10.22, build 3a2c30b
- portainer.io Community Edition 2.16.2

**Comment by GitHubAppleDreamer** [comment]
I have the same problem.
MisterBearBear describes the error exactly as it appears on my system.
I use Pi-Hole in Docker on a Synology.

**Comment by PromoFaux** [comment]
I have just seen this in somebodies [logs on Reddit](https://www.reddit.com/r/pihole/comments/10ctmiq/comment/j4ukgm9/?utm_source=reddit&utm_medium=web2x&context=3):

>grep: /etc/lighttpd/conf-enabled/15-fastcgi-php.conf: No such file or directory

We changed the default value of an environment variable in the Dockerfile (actually - I don't really know why this is an environment variable thinking about it....) But it explains why it's failing for some folk and not others...

The `PHP_ENV_CONFIG` variable used to have the value `/etc/lighttpd/conf-enabled/15-fastcgi-php.conf`, it now has `/etc/lighttpd/conf-enabled/15-pihole-admin.conf`... anyone seeing this issue is likely retaining this old value.

Are all of you _completely destoying_ your containers before building them again, per the upgrade section in the Readme?

But to go back to wahat I said - I don't really see why this is an environment variable anyway - the value doesn't need to be configurable - I'll fix it

**Comment by MisterBearBear** [comment]
I "recreated" the container in Portainer to pull the latest image so it might keep the old ENV variables.

Now I have the PHP_ENV_CONFIG deleted and it works fine now. Thanks.

**Comment by PromoFaux** [comment]
Thanks, that confirms the issue - Can somebody that is also seeing this issue please try the `:dev` tag before I push it to a new version?

**Comment by djrm05** [comment]
I recreated the container in portainer like @MisterBearBear did.
I have just tested :dev tag without removing the PHP_ENV_CONFIG in one of the containers that had the issue and is working perfectly.

**Comment by PromoFaux** [comment]
`2023.01.1` building as we speak https://github.com/pi-hole/docker-pi-hole/actions/runs/3950828292

**Comment by MisterBearBear** [comment]
> `2023.01.1` building as we speak https://github.com/pi-hole/docker-pi-hole/actions/runs/3950828292

Thanks for the help and the great work!

**Comment by MisterBearBear** [comment]
Just updated to 2023.01.1. It is working without issues. Thanks again.

**Comment by Bortinio** [comment]
I can confirm that 2023.01.1 also fixed it for me now. Thanks a lot!

**Comment by rdwebdesign** [comment]
Yeah... we will need to re-tag it.

Thanks.

**Comment by PromoFaux** [comment]
I made it 18 days into the year before I wrote the year down wrong.

**Comment by Szesi111** [comment]
2023.01.1 and 2023.01.2 also fixed it.
Thanks!

**Comment by ppuschmann** [comment]
🤔 somehow I still have this issue, running pi-hole in k8s.

If I use the env-var `PIHOLE_DNS_`, the upstream-servers aren't set.

If I use the (old) env-vars like `PIHOLE_DNS_1`, `PIHOLE_DNS_2` and so on, pi-hole will come up running just fine, with all upstream servers configured.

Version: 2023.03.1

**Comment by dschaper** [comment]
> If I use the env-var `PIHOLE_DNS_`, the upstream-servers aren't set.
> 
> If I use the (old) env-vars like `PIHOLE_DNS_1`, `PIHOLE_DNS_2` and so on, pi-hole will come up ~running just fine~, with all upstream servers configured.

Can you please post the exact configuration lines/yaml that you are using?

**Comment by sebastianliebscher** [comment]
I have never had this error before, but now with release of `2023.11.0` I get the same issue on my deployment.

After a restart or stop+start of the Docker stack, I get the following error:

- web UI: `"Warning in dnsmasq core:  no upstream servers configured"`
- docker compose logs

```bash
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service cron: starting
s6-rc: info: service cron successfully started
s6-rc: info: service _uid-gid-changer: starting
s6-rc: info: service _uid-gid-changer successfully started
s6-rc: info: service _startup: starting
  [i] Starting docker specific checks & setup for docker pihole/pihole
  [i] Setting capabilities on pihole-FTL where possible
  [i] Applying the following caps to pihole-FTL:
        * CAP_CHOWN
        * CAP_NET_BIND_SERVICE
        * CAP_NET_RAW
  [i] Ensuring basic configuration by re-running select functions from basic-install.sh
  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [i] Installing /etc/dnsmasq.d/01-pihole.conf...
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [i] Installing /etc/.pihole/advanced/06-rfc6761.conf...
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
s6-rc: info: service _startup successfully started
s6-rc: info: service pihole-FTL: starting
s6-rc: info: service pihole-FTL successfully started
s6-rc: info: service lighttpd: starting
s6-rc: info: service lighttpd successfully started
s6-rc: info: service _postFTL: starting
s6-rc: info: service _postFTL successfully started
s6-rc: info: service legacy-services: starting
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
s6-rc: info: service legacy-services successfully started
  [✗] DNS resolution is currently unavailable
  [i] Time until retry: 120
```

Even if the correct setting is displayed in the UI, one must first manually save to apply the setting.

![upstream-ip](https://github.com/pi-hole/docker-pi-hole/assets/112352529/2b7aca0a-4342-4e80-a13c-601be364afd7)

Also, note how I specified upstream DNS `hostnames` (Docker service names are supported) but in the UI their `IP` is shown. Maybe it is related to the issue, maybe not.

**Steps to reproduce:**

0. (have a successfully running `docker-pi-hole` prior to `2023.11.0`)
1. upgrade to `2023.11.0`: `docker-compose.yml`

```yaml
services:
  pihole:
    image: pihole/pihole:2023.11.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8888:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      PIHOLE_DNS_: hostname-1;hostname-2
      DNSSEC: true
    volumes:
      - '/some/dir/:/etc/pihole/'
      - '/some/dir2/:/etc/dnsmasq.d/'
    restart: unless-stopped
```
3. restart the stack
4. get the error

**Comment by PromoFaux** [comment]
> Maybe it is related to the issue, maybe not.

The docker hostnames are converted to IP addresses on container start (this may be different with the v6 containers, I don't remember off hand)

What version of the container were you running before upgrade to `2023.11.0`? There have been no docker specific changes for a while

**Comment by PromoFaux** [comment]
> latest stable version.

Just as a point of clarification - the version numbers [are just date based](https://github.com/pi-hole/docker-pi-hole?tab=readme-ov-file#docker-tags-and-versioning), not semantic. Any release is considered "stable" (until proven otherwise 😉 🫣)

What are the contents of `/etc/dnsmasq.d/01-pihole.conf`?

And no, that's normal - have just started up my 2022.11.0 container:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service cron: starting
s6-rc: info: service cron successfully started
s6-rc: info: service _uid-gid-changer: starting
s6-rc: info: service _uid-gid-changer successfully started
s6-rc: info: service _startup: starting
  [i] Starting docker specific checks & setup for docker pihole/pihole
  [i] Setting capabilities on pihole-FTL where possible
  [i] Applying the following caps to pihole-FTL:
        * CAP_CHOWN
        * CAP_NET_BIND_SERVICE
        * CAP_NET_RAW
        * CAP_NET_ADMIN
  [i] Ensuring basic configuration by re-running select functions from basic-install.sh
  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [i] Installing /etc/dnsmasq.d/01-pihole.conf...
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [i] Installing /etc/.pihole/advanced/06-rfc6761.conf...
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
  [i] Installing latest logrotate script...
	[i] Existing logrotate file found. No changes made.
  [i] Assigning password defined by Environment Variable
  [✓] New password set
  [i] Added ENV to php:
                    "TZ" => "europe/London",
                    "PIHOLE_DOCKER_TAG" => "",
                    "PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
                    "CORS_HOSTS" => "",
                    "VIRTUAL_HOST" => "docker-pihole-pi4.lan",

```


I think we might be seeing a slightly different issue to the OP here, can you please create a new issue and we can troubleshoot there if needs be - just to stop the notification noise for everyone else in this thread... :)
