### ISSUE TITLE
lighttpd external.conf not working

### ISSUE THREAD

**Issue by Szesi111** [pi-hole/docker-pi-hole#1277]
The external.conf setting not working with 2023.01 release. It was working with 2022.12.

This is a: BUG

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Rasbian 
  * Hardware: RasPI2B 
  * Kernel Architecture: ARM
  * Docker Install Info and version: 
    - Software source: OS provided 20.10.22
    - Supplimentary Software: portainer-ce 2.16.2
  * Hardware architecture: ARM 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce
Port configuration 	
0.0.0.0:53 53/tcp
:::53 53/tcp
0.0.0.0:53 53/udp
:::53 53/udp
0.0.0.0:8000 80/tcp
:::8000 80/tcp

volumes
/home/homeassistant/pihole/etc-dnsmasq.d 	               /etc/dnsmasq.d
/home/homeassistant/pihole/etc-lighttpd/external.conf 	/etc/lighttpd/external.conf
/home/homeassistant/pihole/etc-pihole 	                       /etc/pihole

external.conf:
$HTTP["url"] =~ "^/admin/" {
    setenv.set-response-header = (
        "X-Frame-Options" => "ALLOW"
    )
}

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

2022.12 release setenv settings are in the /etc/lighttpd/lighttpd.conf file. The external.conf is working well.
2023.01 release has modified lighttpd settings. The /etc/lighttpd/lighttpd.conf not containing the setenv settings, the settings are in the /etc/lighttp/conf-enabled directory configuration files.
The 2023.01 conf files does not include external.conf.

**Comment by PromoFaux** [comment]
Ah - yes of course, `external.conf` is not a default lighttpd option. That was an oversight...

Can you try adding that file to `/etc/lighttpd/conf-enabled/` instead please?

**Comment by Szesi111** [comment]
It"s working with modified volume:
/home/homeassistant/pihole/etc-lighttpd/external.conf 	/etc/lighttpd/conf-enabled/external.conf

thx

**Comment by PromoFaux** [comment]
Super - thanks for reporting back. I've added an extra note to the release and will look at adding this to the Readme file, too.

**Comment by PromoFaux** [comment]
Note added to the readme: https://github.com/pi-hole/docker-pi-hole/commit/f70e9b37b845fa0ec5e475833f990d07a08a628c

**Comment by digininja** [comment]
This probably isn't the official docs for getting SSL working, but it is the first reference I found when googling how to do it, so it is probably worth putting a note in here as well. At least point them to this bug report.

https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771
