### ISSUE TITLE
"invalid domains" found when retrieving the list with Pi-hole from included StevenBlack-List(s)

### ISSUE THREAD

**Issue by thomasmerz** [pi-hole/docker-pi-hole#1280]
This is a: **BUG**

## Details
Please have a look at https://github.com/StevenBlack/hosts/issues/2208 (and some more issue 😱) for details. This is really disturbing some users… 🤔 

```
  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 168834 domains, 15 domains invalid!
      Sample of invalid domains:
      - 0.0.0.0
      - broadcasthost
      - fe
      - ff
  [i] List stayed unchanged
```

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar

**Comment by rdwebdesign** [comment]
Those are really invalid domains.

They are considered valid hostnames, but not valid domains.

**Comment by yubiuser** [comment]
https://github.com/pi-hole/pi-hole/pull/5009

**Comment by thomasmerz** [comment]
Hm, but before 2023.x nobody noticed this… So is Pi-hole behaving different than before? I couldn't find any changes in this hosts-list in the near past that might provoked this messages.

`git blame` for StevenBlack's `hosts` file:
```
e946d6fa8 (Steven Black 2016-03-13 03:02:26 -0400     15) 127.0.0.1 localhost
e946d6fa8 (Steven Black 2016-03-13 03:02:26 -0400     16) 127.0.0.1 localhost.localdomain
6d737188d (Steven Black 2016-03-24 10:30:39 -0400     17) 127.0.0.1 local
e946d6fa8 (Steven Black 2016-03-13 03:02:26 -0400     18) 255.255.255.255 broadcasthost
280e938a5 (StevenBlack  2018-04-16 22:24:33 -0400     19) ::1 localhost
280e938a5 (StevenBlack  2018-04-16 22:24:33 -0400     20) ::1 ip6-localhost
280e938a5 (StevenBlack  2018-04-16 22:24:33 -0400     21) ::1 ip6-loopback
e946d6fa8 (Steven Black 2016-03-13 03:02:26 -0400     22) fe80::1%lo0 localhost
280e938a5 (StevenBlack  2018-04-16 22:24:33 -0400     23) ff00::0 ip6-localnet
280e938a5 (StevenBlack  2018-04-16 22:24:33 -0400     24) ff00::0 ip6-mcastprefix
38869f636 (Steven Black 2018-02-09 13:53:48 -0500     25) ff02::1 ip6-allnodes
38869f636 (Steven Black 2018-02-09 13:53:48 -0500     26) ff02::2 ip6-allrouters
280e938a5 (StevenBlack  2018-04-16 22:24:33 -0400     27) ff02::3 ip6-allhosts
eb849c741 (Steven Black 2017-04-13 21:26:20 -0400     28) 0.0.0.0 0.0.0.0
```

**Comment by thomasmerz** [comment]
Ok, this was confusing me (and others), but it's no error at all. Thanks for keeping me uptodate ❤️

**Comment by rdwebdesign** [comment]
Just to be clear:

There is nothing wrong with the original list, but Pi-hole uses domains and do not use these hostnames. 
The message is simply warning some items were ignored.
