### ISSUE TITLE
An unknown error occurred while loading the data.

### ISSUE THREAD

**Issue by madzodiac** [pi-hole/docker-pi-hole#1295]
This is a: Bug  

## Details
After upgrading to the latest Docker image version 2023.01.6 „ An unknown error occurred while loading the data.“ is displayed when clicking on various menu items, e.g. Network under Tools.

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Raspbian 
  * Hardware: RasPi 3B 
  * Kernel Architecture: ArmV8 32bit 
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software: 
  * Hardware architecture: ARM 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

docker run -d \
    --name pihole \
    -p 53:53/tcp -p 53:53/udp \
    -p 8099:80 \
    -v "/etc-pihole/:/etc/pihole/" \
    -v "/etc-dnsmasq.d/:/etc/dnsmasq.d/" \
    -e TZ="Europe/Berlin" \
    --dns=192.168.178.1 \
    --restart=unless-stopped \
    --hostname pi.hole \
    -e VIRTUAL_HOST="pi.home.box" \
    -e PROXY_LOCATION="pi.hole" \
    -e FTLCONF_LOCAL_IPV4="192.168.178.5" \
    -e WEBPASSWORD="*****" \
    -e PIHOLE_DNS_="9.9.9.11;149.112.112.11;2620:fe::11;2620:fe::fe:11" \
    -e REV_SERVER=true \
    -e REV_SERVER_DOMAIN="home.box" \
    -e REV_SERVER_TARGET="192.168.1.1" \
    -e REV_SERVER_CIDR="192.168.1.0/24" \
    -e BLOCK_ICLOUD_PR=false \
    pihole/pihole:latest

4. any additional info to help reproduce

## These common fixes didn't work for my issue

- [ x] I have tried removing/destroying my container, and re-creating a new container
- [x ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by PromoFaux** [comment]
Not relevant to your issue, but instead of `BLOCK_ICLOUD_PR`, you should be using `FTLCONF_BLOCK_ICLOUD_PR`, otherwise it is not recognised/used 

As for the reported issue - I cannot reproduce it. Can you try running without the volume mounts to see if that still displays this issue?

**Comment by madzodiac** [comment]
Thanks for the hint regarding the FTLCONF.

Without the volumes it works.

**Comment by madzodiac** [comment]
I generated the debug log, et voila there is the reason:
```
*** [ DIAGNOSING ]: Pi-hole FTL Query Database
-rw-rw-r-- 1 pihole pihole 1.4G Jan 21 10:51 /etc/pihole/pihole-FTL.db
[i] Checking integrity of /etc/pihole/pihole-FTL.db ... (this can take several minutes)
[✗] Integrity errors in /etc/pihole/pihole-FTL.db found.
```

Sorry for bothering.
