### ISSUE TITLE
Web Frontend  missing in pihole/pihole:latest

### ISSUE THREAD

**Issue by praxis88** [pi-hole/docker-pi-hole#1305]
When bringing up the container, the web frontend is just a placeholder page

This is a: Bug

## Details

root@91c4a2b5e8e6:/# ls /var/www/html
admin  index.lighttpd.html

Rolling back to an image from a month ago brings the pihole folder back and removing the index.lighttpd.html makes the frontend work again

## Related Issues
- [x ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Debian 11 & Arch
  * Hardware: RPi4b and Dell optiplex
  * Kernel Architecture: x86/amd64 & ArmV8 64bit
  * Docker Install Info and version: 
    - Software source: Docker version 20.10.23, build 715524332f & build 7155243
    - Supplimentary Software: Portainer
  * Hardware architecture: x86/amd64 & ArmV8 64bit

2.

version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'password'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    
    
![image](https://user-images.githubusercontent.com/58380825/214609070-a2491349-244d-4e57-9410-5da0ddb5d026.png)

root@91c4a2b5e8e6:/# ls /var/www/html
admin  index.lighttpd.html

3. I reproduced this on my desktop which has never had pihole running on it before, after hitting this on my rpi4 homeserver. The issue occured sometime in the last month, because pulling a month old image readded the pihole folder in /var/www/html

## These common fixes didn't work for my issue

- [x ] I have tried removing/destroying my container, and re-creating a new container
- [ x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by praxis88** [comment]
Interesting. I never knew it was in /admin. I had always gotten to it from just the ip address for years. This is a much smaller issue than the whole folder being missing

I can just update my bookmarks and test to see if that works. 

I guess the one question I have is why

**Comment by rdwebdesign** [comment]
Because the same code installed on docker is used on "bare metal" installs and the content of `/var/www/html` is used by other applications.

The old config shipped with Pi-hole used to broke the pages on this this directory (or caused conflicts with them). The new config only uses `/admin` for Pi-hole and other directories are not touched. The placeholder page is just part of the normal `lighttpd` installation.

**Comment by PromoFaux** [comment]
I guess it's not so much an issue on the docker side of things, but changes were made upstream to prevent us from clobbering `lighttpd`'s config every time someone updated on bare metal. 

This has been a source of frustration for years, particularly if people have customisations in the config (despite the big warning at the top saying not to - but I think we all know people don't like to read warnings/documentation/release notes 😏)

Set the environment variable FTLCONF_LOCAL_IPV4 to your IP address, and it will be automatically redirected to /admin

**Comment by praxis88** [comment]
>Set the environment variable FTLCONF_LOCAL_IPV4 to your IP address, and it will be automatically redirected to /admin

This worked well

I guess I just didnt see any advantage to this change in docker, but did see a disadvantage, but if it is being pushed down from bare-metal usage cases that makes sense. 

Although I dont understand why people are running services on baremetal in 2023, there's almost no upside to that
