### ISSUE TITLE
Logging in at web UI page redirects right back to login page

### ISSUE THREAD

**Issue by StrikeAgainst** [pi-hole/docker-pi-hole#1310]
This is a: Bug

## Details

I installed the pihole container for the first time about a week ago, that's when the web UI was still functioning fine. Now previously I was setting up my docker containers back up again after moving around the docker storage. When I fired the pihole container back up (with the latest version `2023.01.10`), I initially had the issue that entering the admin page returned a "503 Service Unavailable". Seeing issue #1299, I updated the pihole image and retried.

Now while I can enter the admin page, everytime I try to login I get redirected right to that very login page. This differs from a wrong password input by the fact that any error indication is missing. Setting up a new container without volumes did not work (see compose file below).

When downgrading to `2023.01.5`, the login only works when I check the mark to remember my login for 7 days - IIRC that problem persisted before, but I didn't care too much for it at first. Showing my local DNS records alerts me a JSON error from the JS DataTables library, I assume this might be a version dependent compatibility issue though.

## Related Issues
- #1299

## How to reproduce the issue 

1. Environment data
  * Operating System: openmediavault 6 (Debian 11) 
  * Hardware: TerraMaster F2-210 
  * Kernel Architecture: amd64 
  * Docker Install Info and version: 
    - Software source: omv-extras 
    - Supplimentary Software: Portainer
  * Hardware architecture: x86_64 

2. My compose file I tried a clean test with looks like this:
```
version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    environment:
      TZ: 'Germany/Berlin'
      WEBPASSWORD: 'admin'
    restart: unless-stopped
```
3. I switched the docker storage from my system SSD to a freshly set up, mirrored HDD RAID before first encountering this issue, though I'd rule out this to be causing any issues...

EDIT: It turned out that some more web UIs across my containers are faulty (at least another one with a login issue), so this might be a general docker issue instead. I'm further investigating on this.

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

- [x] I have tried clearing the browser cache

**Comment by rdwebdesign** [comment]
> When downgrading to `2023.01.5`, the login only works when I check the mark to remember my login for 7 days - IIRC that problem persisted before, but I didn't care too much for it at first. 

1. Why did you downgraded to `2023.01.5`? There was many small fixes and new images. Please try again using `2023.01.10`.
2. No one else reported a similar problem before. Maybe this is a problem with the files on your volumes.

**Comment by StrikeAgainst** [comment]
@rdwebdesign 
1. I assumed it was the version I originally had installed when I initially built the container. Might have been `2023.01.6` as well, but I didn't deem it necessary to check on that after the login worked on `2023.01.5`. I didn't specify it clear enough, but of course I was using `2023.01.10` after moving the storage, that's when the login failed for me no matter what.
2. You might actually be right with that, I've encountered this issue across multiple different containers now. Updated my issue accordingly. Weirdly enough, the login was still working with the downgraded version though...

**Comment by DL6ER** [comment]
Simply from reading the title of this issue, I wonder if your disk is full. In this case, Pi-hole will continue to work fine, however, the web interface will have no possibility to store a new session for you, leading to the symptoms you described. That other containers behave the same also fits to my assumption of a full disk.

**Comment by StrikeAgainst** [comment]
> Simply from reading the title of this issue, I wonder if your disk is full. In this case, Pi-hole will continue to work fine, however, the web interface will have no possibility to store a new session for you, leading to the symptoms you described. That other containers behave the same also fits to my assumption of a full disk.

I've read about this before, the file system is quite new and empty though. Maybe it's a permission issue after all, with the containers not allowed to put down any data on the file system.

**Comment by RootOperator** [comment]
I'm having the same problem.
remembering for 7 days seems to log me in but I am then unable to do anything.
It will give errors when trying to add urls to blacklist or even chaning settings.
it will say "Wrong token! Please re-login on the Pi-hole dashboard."

and the weird thing is it does work normally when I open the site in a private tab.
but it does not work in a normal tab even with all my extensions disabled.

**Comment by rdwebdesign** [comment]
> and the weird thing is it does work normally when I open the site in a private tab.
but it does not work in a normal tab even with all my extensions disabled.

Did you try to use a different browser?

This seems to be a problem with browser cache (or browser `localstorage`). 
Please, cleanup cache and `localstorage` and try again.

**Comment by haifisch88** [comment]
I have the same problem...
