### ISSUE TITLE
Example Caddyfile mistakenly forwards to external port

### ISSUE THREAD

**Issue by juliankrieger** [pi-hole/docker-pi-hole#1315]
This is a: Bug

## Details

When using pihole with docker and the example Caddy configuration, I noticed that the Caddyfile forwards requests to `pihole:8081`. This is wrong, because 8081 is the external port that binds to port 80 in the pihole service. Since we use a bridge network with caddy_net, it should instead directly forward to `pihole:80`

**Comment by rdwebdesign** [comment]
Are you talking about port 8081 in `docker-compose-caddy-proxy.yml` file?

https://github.com/pi-hole/docker-pi-hole/blob/4961bf4b1ad394e62b9fee0de60d2be9c84d61b1/examples/docker-compose-caddy-proxy.yml#L36

Or on `Caddyfile`?

https://github.com/pi-hole/docker-pi-hole/blob/4961bf4b1ad394e62b9fee0de60d2be9c84d61b1/examples/Caddyfile#L4

Or both?

**Comment by krishnachandiran** [comment]
This is true. After changing  `reverse_proxy pihole:8081`  to   `reverse_proxy pihole:80` . it worked.
