### ISSUE TITLE
Settings-DNS-Interface settings reset after container update

### ISSUE THREAD

**Issue by To-Azamat** [pi-hole/docker-pi-hole#1321]
I have "Permit all origins" set in "Interface settings". After container update it resets to "Allow only local requests". All other settings are maintained. This is the second consecutive update with such behavior. 

Update is via monthly scheduled Watchtower run.

Container is running on Synology 916+, DSM 6.2.4, Docker 20.10.3

**Comment by dschaper** [comment]
First, don't update Pi-hole via Watchtower. https://github.com/pi-hole/docker-pi-hole#note-on-watchtower

Second, you'll need to provide some kind of information we can look at to begin to help. What is your compose/docker run/configuration setup? What environment variables have you set? What is your volume mount for persisting data?

**Comment by To-Azamat** [comment]
Mounted volumes:
/docker/pihole/dnsmasq -> /etc/dnsmasq.d
/docker/pihole/pihole -> /etc/pihole 

Env. variables:
PIHOLE_DOCKER_TAG=2022.07.1                                                                                                           
S6_BEHAVIOUR_IF_STAGE2_FAILS=2                                                                                                        
HOSTNAME=pihole                                                                                                                       
S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0                                                                                                    
S6_LOGGING=0                                                                                                                          
HOME=/root                                                                                                                            
INTERFACE=ovs_bond0                                                                                                                   
FTLCONF_LOCAL_IPV4=0.0.0.0                                                                                                            
TERM=xterm                                                                                                                            
FTL_CMD=no-daemon                                                                                                                     
IPv6=False                                                                                                                            
PHP_ERROR_LOG=/var/log/lighttpd/error-pihole.log                                                                                      
SHLVL=1                                                                                                                               
WEB_PORT=5500                                                                                                                         
phpver=php                                                                                                                            
DNSMASQ_USER=pihole                                                                                                                   
PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                                         
S6_OVERLAY_VERSION=v2.1.0.2                                                                                                           
S6_KEEP_ENV=1                                                                                                                         
ServerIP=192.168.1.7

There is also DNSMASQ_LISTENING that was set to =local and I suppose that was resetting Interface settings. I set it to =all yesterday and after a restart all seems fine. I did not change/add any e-vars on initial container creation, just used defaults that were offered.

**Comment by rdwebdesign** [comment]
Note:

If you didn't manually set these variables, they were automatically created by the image using the default values. This is normal.

If you want `DNSMASQ_LISTENING=all` on every update, you need to set this variable, like said on the third item of the **Quick Start**: https://github.com/pi-hole/docker-pi-hole#quick-start

**Comment by To-Azamat** [comment]
Yes, it looks like the E-var was overriding GUI settings on every restart. Thank you for the help!

If I may suggest, it can reduce future possible confusion if GUI would check if E-var was set and warn that any changes to Interface settings would default to set by variable on restart. 

Btw, is it safe to remove DNSMASQ_LISTENING e-var from container config?

**Comment by PromoFaux** [comment]
> Btw, is it safe to remove DNSMASQ_LISTENING e-var from container config?

You can just leave it as `DNSMASQ_LISTENING=all` if that is what you want that setting to be - the beauty of defining your settings via environment variables is that you can ensure they are consistent if you drop/create the container or reproduce it on another machine

General rule of thumb: Environment variable trumps everything else

I'm working on some general improvements for the V6 version of Pi-hole - along with that will come a complete overhaul of the README file
