### ISSUE TITLE
'bind-interfaces' not set in dnsmasq, even when DNSMASQ_LISTENING=single is set.

### ISSUE THREAD

**Issue by iUnknwn** [pi-hole/docker-pi-hole#1324]
This is a: **Run Issue**  

## Details
I'm attempting to run pihole in a docker image. The machine also has VMs running, with dnsmasq running on some of the VM interfaces. 

Pi-hole fails to start, unless I run `echo bind-interfaces >> etc-dnsmasq.d/07-bind.conf` as described https://docs.pi-hole.net/ftldns/interfaces/

Even if I set `DNSMASQ_LISTENING=single` as an env variable, it still fails to add that to the auto-generated configuration.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Centos Stream Release 8** 
  * Hardware: HP t730
  * Kernel Architecture: amd64
  * Docker Install Info and version: podman version 4.0.0-dev
    - Software source: official docker hub
    - Supplimentary Software: N/A
  * Hardware architecture: x86/amd64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```
podman run \
 -p 53/tcp \
 -p 53/udp \
 -p 8001:80/tcp \
 -e 'TZ=America/Los_Angeles' \
 -v /srv/pihole/etc-pihole:/etc/pihole:z \
 -v /srv/pihole/etc-dnsmasq.d:/etc/dnsmasq.d:z \
 --name pihole \
 -e 'FTLCONF_REPLY_ADDR4=192.168.1.16' \
 -e "FTLCONF_REPLY_ADDR6=fddf:e103:2623::16" \
 -e "WEB_PORT=8001" \
 -e "DNSMASQ_LISTENING=single" -e "INTERFACE=enp1s0" \
 --rm --net=host pihole/pihole:2023.02.2
```

## These common fixes didn't work for my issue
- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Running without net host doesn't generate this problem. 

Add any other debugging steps you've taken or theories on root cause that may help.
I think the single variable might just not be adding the line into the dnsmasq config.

**Comment by PromoFaux** [comment]
Interesting, I wonder if this is a bug in the core repo rather than docker-specifc.

When you start the container, what are the contents of `/etc/pihole/setupVars.conf`?

**Comment by iUnknwn** [comment]
Sure thing - here's what's in `setupVars.conf` just using what I showed above (without having configured anything myself, I used new mounts):

```
INSTALL_WEB_INTERFACE=true
WEBPASSWORD=f841ab50103639d91de814473b90bdf584ee13214a26a05374fc7c3f32910d2f
PIHOLE_DNS_1=8.8.8.8
PIHOLE_DNS_2=8.8.4.4
PIHOLE_INTERFACE=enp1s0
DNSMASQ_LISTENING=single
QUERY_LOGGING=true
BLOCKING_ENABLED=true
```

And here's the generated `/etc/dnsmasq.d/01-pihole.conf`:
```
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Dnsmasq config for Pi-hole's FTLDNS
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

###############################################################################
#      FILE AUTOMATICALLY POPULATED BY PI-HOLE INSTALL/UPDATE PROCEDURE.      #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#        IF YOU WISH TO CHANGE THE UPSTREAM SERVERS, CHANGE THEM IN:          #
#                      /etc/pihole/setupVars.conf                             #
#                                                                             #
#        ANY OTHER CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE           #
#                    WITHIN /etc/dnsmasq.d/yourname.conf                      #
###############################################################################

addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list


localise-queries


no-resolv

log-queries
log-facility=/var/log/pihole/pihole.log

log-async
cache-size=10000
server=8.8.8.8
server=8.8.4.4
interface=enp1s0
```

**Comment by iUnknwn** [comment]
Is there any more information needed on this bug?
