### ISSUE TITLE
"Domains on Adlists" = 0 after pull

### ISSUE THREAD

**Issue by blademan007** [pi-hole/docker-pi-hole#1328]
This is a: **FILL ME IN**  
This is a Build issue

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 22.04.1 LTS 
  * Hardware: PC 
  * Kernel Architecture: x86 
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software: 
  * Hardware architecture: x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce

Ran:
```
docker pull pihole/pihole
docker rm -f pihole
docker pihole/pihole (failed)
docker compose up -d
```

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by dschaper** [comment]
And the information requested please:

> 2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

**Comment by blademan007** [comment]
> `docker pihole/pihole (failed)`
> 
> That's not a docker command so I would expect it to fail.

Thanks. Then what's the recommended steps to update the container?

**Comment by dschaper** [comment]
https://github.com/pi-hole/docker-pi-hole#upgrading-persistence-and-customizations

**Comment by blademan007** [comment]
I followed that documentation. My error. The command I used was not correct.
`docker pihole/pihole (failed)`
Actual command run that failed was:
`docker run pihole/pihole `
Attached CLI log shows container is up, but no ports are open. Can only get container up using `docker compose up -d`
[docker run.odt](https://github.com/pi-hole/docker-pi-hole/files/10788091/docker.run.odt)

**Comment by dschaper** [comment]
If you use docker compose then yes, `docker compose up -d` is the correct command. I don't know what you are using because you have twice ignored the request for information to be able to help you.

**Comment by dschaper** [comment]
```plain
root@pi-hole-CT:~/docker-pi-hole# docker ps
CONTAINER ID   IMAGE           COMMAND      CREATED         STATUS                            PORTS                            NAMES
7c8c318b3c9a   pihole/pihole   "/s6-init"   4 seconds ago   Up 4 seconds (health: starting)   53/udp, 53/tcp, 80/tcp, 67/udp   admiring_chatelet
```

That looks fine to me, as does:
```plain
  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Imported 183304 domains, ignoring 1 non-domain entries
      Sample of non-domain entries:
        - 0.0.0.0
  [i] List has been updated

  [✓] Creating new gravity databases
  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [✓] The old database remains available.
  [i] Number of gravity domains: 183304 (183304 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Cleaning up stray matter

  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [i] Pi-hole blocking will be enabled
  [i] Enabling blocking
  [✓] Pi-hole Enabled

  Pi-hole version is v5.15.5 (Latest: v5.15.5)
  AdminLTE version is v5.18.4 (Latest: v5.18.4)
  FTL version is v5.21 (Latest: v5.21)
  Container tag is: 2023.02.2
```

So, third try:

> 2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

**Comment by blademan007** [comment]
docker-compose.yml:
`root@pi-hole-CT:~/docker-pi-hole# more docker-compose.yml 
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
     # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'US/Pacific'
      WEBPASSWORD: XXX 
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped`
docker run shell command:
`docker run pihole/pihole`

**Comment by rdwebdesign** [comment]
The command `docker run pihole/pihole` (without any extra options) will create a container using only the default values. The compose file with your options won't be used.

To use the contents of the compose file, you need to run [`docker compose up` command](https://docs.docker.com/engine/reference/commandline/compose_up/).
