### ISSUE TITLE
2023.02.2 no longer works

### ISSUE THREAD

**Issue by xamindar** [pi-hole/docker-pi-hole#1332]
This version will start up, load all the pihole services, and then shut them all down again, rinse and repeat.
I have to go back to 2023.02.1 for pihole to work again.

**Comment by rdwebdesign** [comment]
We need more info to try to debug your case.

Are you using the command line or some web interface to start your container?
Please post the compose file, or docker command used start your container.

**Comment by xamindar** [comment]
Sorry for the sparse details. I run the container on kubernetes and didn't want to go back and test things at the time I posted. 
The problem ended up being a simple liveness/readyness probe issue, which was pointing at the root of the container's web instead of /admin. 
Previous versions of pihole threw up the lighttpd default page at that locastion, and even older versions threw up a page telling you to go to /admin to manage the pihole. Both of which satisfied the liveness probes in the past.
