### ISSUE TITLE
typo in the /etc/resolv.conf file

### ISSUE THREAD

**Issue by pippo73** [pi-hole/docker-pi-hole#1347]
This is a: there is a typo in the /etc/resolv.conf file.

```

# cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
```

Easy to fix it. Just change the 11 to 1 ;-)

**Comment by pluim003** [comment]
This has been mentioned before, f.e. in https://github.com/pi-hole/docker-pi-hole/issues/497
