### ISSUE TITLE
WebUI does't work, “Fatal Error Unable to create lock file: Bad file descriptor (9)”

### ISSUE THREAD

**Issue by youziqiepian** [pi-hole/docker-pi-hole#1348]
This is a: **Run Issue**  

## Details

"I installed pihole in NAS (not Synology), using latest version of the image and the container configuration is shown in the figure. After starting the container, it prompted 'Fatal Error Unable to create lock file: Bad file descriptor (9)'. According to the methods on the forum, I modified the permissions of /tmp and /var/tmp folders to 1777. Then I can open the webui page, but cannot log in without any error prompts. I checked the disk space and found that the space usage of NAS is 93%. When I restarted the container, the permissions of /tmp and /var/tmp were reset to the original permissions (not 1777). I used chattr to lock the permissions, but the problem still exists, and it still prompts 'Fatal Error Unable to create lock file: Bad file descriptor (9)'. "
This problem has been bothering me for a long time, I really need help, ths.

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://discourse.pi-hole.net/t/login-to-gui-issue-not-password-error-just-redirects-back-to-login-page/47503/2

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian** 
  * Hardware: 
  * Kernel Architecture: 
  * Docker Install Info and version: 
    - Software source: 
    - Supplimentary Software: 
  * Hardware architecture: 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce
![pihole](https://user-images.githubusercontent.com/19603126/233828151-68e19b22-0fa8-4f8d-9cb3-c1ee49136add.png)
![pihole2](https://user-images.githubusercontent.com/19603126/233828160-52610226-f3ba-435f-b81b-eea45556f9e1.png)
![pihole-d](https://user-images.githubusercontent.com/19603126/233828163-baa78837-6414-4036-a5ea-2fe5ca431df8.png)
![pihole-port](https://user-images.githubusercontent.com/19603126/233828167-b504c1d3-63db-492c-ad05-f4ffc4b4e2a6.png)
![pihole-env](https://user-images.githubusercontent.com/19603126/233828168-45539c73-cff9-4a10-9007-c0ab990f21ca.png)

## These common fixes didn't work for my issue

- [ ] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
debug token is: https://tricorder.pi-hole.net/Yu02tJNL/
If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by edgd1er** [comment]
I used to have pihole running without any problem on a debian system with hdd.
I reinstalled my system (openmediavault) on a ssd, and I set /var/lib/docker to an hdd partition.
I was wandering if the mount options could be the cause of this problem.:

`defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl`

on another system, I set docker data-root to an usb drive mount with options: `defaults,noatime,commit=60 0 2`

@youziqiepian did you also moved the /var/lib/docker to another location ?

**Comment by edgd1er** [comment]
@youziqiepian , I solved my problem, by stopping docker daemon and removing all "/var/lib/docker" contents.

docker's daemon rebuilt all its subdirectories and needed contents. now pihole has no more this error.

**Comment by youziqiepian** [comment]
> @youziqiepian , I solved my problem, by stopping docker daemon and removing all "/var/lib/docker" contents.，我通过停止 docker 守护程序并删除所有“/var/lib/docker”内容解决了我的问题。
> 
> docker's daemon rebuilt all its subdirectories and needed contents. now pihole has no more this error.Docker的守护进程重建了它所有的子目录和需要的内容。现在皮霍尔不再有这个错误了。

thanks for your help，i will try it.

**Comment by slime3000fly** [comment]
Hello,

I am experiencing persistent issues with the Pi-hole Docker container, which results in a 503 error when accessing the web interface at port 8080. I've followed the suggestions from issue #1348, but unfortunately, they did not resolve the problem. The Docker logs show the following error: 
`Fatal Error Unable to create lock file: Bad file descriptor (9) `

Environment:

    Docker version: (provide your Docker version, e.g., 27.3.1)
    Docker Compose version: (provide your Docker Compose version, e.g., 1.29.2)
    Pi-hole Docker image: pihole/pihole:latest
    Raspberry Pi model: (specify your model, e.g., Raspberry Pi 3B+)

**Comment by slime3000fly** [comment]
Ok, so in my case, the problem was with the volume - '/script:/tmp'. The issue arises because when Docker creates this directory, it has incorrect permissions. It should be `drwxrwxr-x`, but by default, it is set to `drwxr-xr-x`. Therefore, you may need to execute `sudo chmod o+w script/` as a workaround.

**Comment by Gloobyy** [comment]
I am having the same problem. this is literally the only thing I've found about this error. however, I do not have a script directory.

**Comment by slime3000fly** [comment]
@Gloobyy Check if every volume Docker creates has the correct permissions

**Comment by Gloobyy** [comment]
yeah I just solved this by nuking the whole server. this was a while ago tho and now I use it in an lxc container instead of docker with no issues
