### ISSUE TITLE
Docker container unhealthy

### ISSUE THREAD

**Issue by jvcsw** [pi-hole/docker-pi-hole#1349]
Hi everyone,

this error has been appearing for a few days:

/run/s6/basedir/scripts/rc.init: 35: s6-rc-compile: not found

Pihloe won't start. I've tried with a new container with no previous configuration and I get the same error.

I also tried it with the latest version and it doesn't work either.

Any idea?

**Comment by jvcsw** [comment]
I have stopped using it, it seems that this is the way.

**Comment by PromoFaux** [comment]
> /run/s6/basedir/scripts/rc.init: 35: s6-rc-compile: not found

Ideally when reporting an issue it is useful to provide information such as details about the hardware you are running on, the method you are using to start your container (i.e a run script or docker-compose file - and the contents of said script/file), as is laid out in the issue template you are presented when creating a new issue.

The error above is not usual, and certainly not one I have come across, With little information to go on, it is difficult to troubleshoot/point you in the right direction.

> I have stopped using it, it seems that this is the way.

Sorry, this one somehow passed me by.

**Comment by jvcsw** [comment]
After a few days I updated the docker image and it worked...

**Comment by PromoFaux** [comment]
Cool, well - could have been anything then, but glad it's working for you now!
