### ISSUE TITLE
No internet access from pihole container

### ISSUE THREAD

**Issue by ssmall** [pi-hole/docker-pi-hole#1351]
This is a:  Bug

## Details

pihole is only able to resolve DNS via default gateway (10.0.0.1) but any IP address outside the local subnet (10.0.0.0/24) is unreachable. The podman host does not have this issue and can reach the internet with no problems.

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Debian
  * Hardware: PC
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: OS provided package
    - Supplimentary Software: podman
  * Hardware architecture:  x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
$ cat /etc/systemd/system/pihole.service
# container-pihole.service
# autogenerated by Podman 3.0.1
# Wed Feb  9 20:05:15 PST 2022

[Unit]
Description=Podman container-pihole.service
Documentation=man:podman-generate-systemd(1)
Wants=network.target
After=network-online.target

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStartPre=/bin/rm -f %t/container-pihole.pid %t/container-pihole.ctr-id
ExecStart=/usr/bin/podman run --conmon-pidfile %t/container-pihole.pid --cidfile %t/container-pihole.ctr-id --cgroups=no-conmon --replace -d --name pihole --restart unless-stopped --network omadanetwork --ip 10.0.0.251 -p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 80:80/tcp -e FTLCONF_REPLY_ADDR4=10.0.0.251 -e SERVERIP=10.0.0.251 -e TZ=America/Los_Angeles -e DNSSEC=true -e TEMPERATUREUNIT=f -e WEBTHEME=default-dark -v pihole-base:/etc/pihole -v pihole-dnsmasq:/etc/dnsmasq.d ghcr.io/pi-hole/pihole@sha256:a74dde4800f54d3c0b0839babbac9f2cc7e4b8239ab4a5bc2c25c7328ec1c019
ExecStop=/usr/bin/podman stop --ignore --cidfile %t/container-pihole.ctr-id -t 10
ExecStopPost=/usr/bin/podman rm --ignore -f --cidfile %t/container-pihole.ctr-id
PIDFile=%t/container-pihole.pid
Type=forking

[Install]
WantedBy=multi-user.target default.target
```
4. any additional info to help reproduce
```
$ sudo podman network inspect omadanetwork
[
    {
        "cniVersion": "0.4.0",
        "name": "omadanetwork",
        "plugins": [
            {
                "ipam": {
                    "ranges": [
                        [
                            {
                                "gateway": "10.0.0.1",
                                "rangeEnd": "10.0.0.254",
                                "rangeStart": "10.0.0.246",
                                "subnet": "10.0.0.0/24"
                            }
                        ]
                    ],
                    "resolvConf": "/etc/resolv.conf",
                    "type": "host-local"
                },
                "master": "ens1",
                "type": "macvlan"
            }
        ]
    }
]
```

From inside pihole container:
```
root@f03ec6f74250:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 8a:b2:dc:fb:99:5e brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.0.0.251/24 brd 10.0.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fdf5:7388:66e1:b9ff:88b2:dcff:fefb:995e/64 scope global dynamic mngtmpaddr
       valid_lft 1790sec preferred_lft 1790sec
    inet6 fd52:5dc9:467f:49e5:88b2:dcff:fefb:995e/64 scope global dynamic mngtmpaddr
       valid_lft 1573sec preferred_lft 74sec
    inet6 fe80::88b2:dcff:fefb:995e/64 scope link
       valid_lft forever preferred_lft forever
```

debug log: https://pastebin.com/nB51G7Sg

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by tkuraku** [comment]
I had pihole running using podman on RHEL/Rocky flawlessly. I switched to Debian and couldn't get podman to work well. I had similar issues to you. I ended up switching to docker proper and it all worked. Seems like there might be something with the configuration on podman on Debian.
