### ISSUE TITLE
Docker Pi-hole V6 Tracker

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/docker-pi-hole#1358]
Project can be found here: https://github.com/orgs/pi-hole/projects/22/views/1

**Comment by PromoFaux** [comment]
@pi-hole/docker-maintainers work towards V6 will be happening in `development-v6`.

Looking at this as a good opportunity to start from the ground up. You may or may not have been following along with `v6-alpine-play` - it was mostly just an experiment to see "What if?" (And there have been calls to go alpine-based for years), now is as good a time as any.

There is still a long way to go, and lots of things that need doing (Tests, anyone? I am bad at tests...) which I will try to keep updated above, but for now the image builds and runs and _appears_ to work...  That is to say, It's at a stop where I'm going to stop directly pushing to the branch, which should hopefully go some way to making it easier to keep up with development via PRs, and even contribute... if anyone feels like dusting off their ol' coding fingers.

**Comment by edgd1er** [comment]
I'm just starting to play with this version, I was wandering if variables, as it is in the current version, will be uppercase.
For the moment I added a simple lowercase transformation in the start script (tr): 
```
  declare -px | grep FTLCONF_ | sed -E 's/declare -x FTLCONF_([^=]+)=\"(|.+)\"/\1 \2/' | tr '[:upper:]' '[:lower:]' | while read -r name value
``` 
I'm afraid with variables using upper and lower cases, something more efficient will be required. Here are variables with both lower and upper case, many other exist:
```
dns.EDNS0ECS = true
dns.ignoreLocalhost = false
dns.showDNSSEC = true
dns.analyzeOnlyAandAAAA = false
```
May be you already have an idea for processing FTL_<variable> ?
