### ISSUE TITLE
Unable to update gravity from the web interface

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/docker-pi-hole#1369]
![image](https://github.com/pi-hole/docker-pi-hole/assets/1998970/fd80fa6a-9d99-47db-aaad-58f9fa23e113)

**Comment by PromoFaux** [comment]
Log excerpt with API Debugging enabled:

```
ph-development-v6  | 2023-07-17 16:53:14.491 [232/T244] DEBUG_API: Requested API URI: POST /api/action/gravity ? (null) (Content-Type (null))
ph-development-v6  | 2023-07-17 16:53:14.491 [232/T244] DEBUG_API: Received no payload
ph-development-v6  | 2023-07-17 16:53:14.491 [232/T244] DEBUG_API: Read sid="lXcu+5i8B3hw3YEPDi9vBQ=" from cookie
ph-development-v6  | 2023-07-17 16:53:14.491 [232/T244] DEBUG_API: API Authentication: FAIL (Cookie authentication without CSRF token)
ph-development-v6  | 2023-07-17 16:53:14.491 [232/T244] WARNING: API: Unauthorized
```

@DL6ER is this a configuration issue, or an FTL bug?

**Comment by PromoFaux** [comment]
Ah, if I set a blank password (thereby removing authentication), I also get the following

![image](https://github.com/pi-hole/docker-pi-hole/assets/1998970/9be24e55-ab43-414f-9e1a-d67b318fdff2)

Though I believe this is _possibly_ unrelated

**Comment by rdwebdesign** [comment]
> Ah, if I set a blank password (thereby removing authentication), I also get the following

Without password, but using `DNSMASQ_USER=root` I was able to run gravity

**Comment by PromoFaux** [comment]
The issue was in core. Fixed with https://github.com/pi-hole/pi-hole/pull/5341
