### ISSUE TITLE
Look into using `tini` init system

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/docker-pi-hole#1397]

**Comment by edgd1er** [comment]
looks like tini implementation is rather simple: add tini to package and
change `ENTRYPOINT [ "/usr/bin/start.sh"]` to
```
ENTRYPOINT [ "tini", "--" ]
CMD [ "/usr/bin/start.sh" ]
```
according to https://computingforgeeks.com/use-tini-init-system-in-docker-containers/?expand_article=1
much easier to use that s6svc or supervisorctl.

Where is the catch ?

**Comment by PromoFaux** [comment]
> Where is the catch ?

I've been too lazy to remember to look into it, is all 😉

**Comment by edgd1er** [comment]
v6 is a big overhaul, I understand time is not limitless :)
I realise that the phrase "where is the catch ?" may be be understood as an unpleasant remark. This is absolutely not my intention.

**Comment by magikid** [comment]
Should this issue be closed since it seems to be done or at least no longer relevant?
