### ISSUE TITLE
[development-v6]: 

### ISSUE THREAD

**Issue by edgd1er** [pi-hole/docker-pi-hole#1398]
### Versions

- Pi-hole:  development-v6
- AdminLTE:  development-v6
- FTL:  development-v6

### Platform

- OS and version:  Alpine 3.18

- Platform:  docker

### Expected behavior

_A clear and concise description of what you expected to happen._
Domain should be listed

### Actual behavior / bug
Domain is not listed:"Loading..." is always displayed.

_A clear and concise description of what the bug is._
pihole-FTL cannot fetch information from sql3 database.
```
pihole-pihole-1  | 2023-07-25 08:05:02.491 [193/T204] ERR: gravityDB_readTable(10 => (N/A)) - SQL error prepare (1): SELECT id,address,enabled,date_added,date_modified,comment,(SELECT GROUP_CONCAT(group_id) FROM adlist_by_group g WHERE g.adlist_id = a.id) AS group_ids,date_updated,number,invalid_domains,status,abp_entries FROM adlist a; => no such column: abp_entries
pihole-pihole-1  | 2023-07-25 08:05:02.491 [193/T204] WARNING: API: Could not read domains from database table (no such column: abp_entries)
```
### Steps to reproduce

1. Go to 'https://pihole.net/admin/groups/adlists'
3. Scroll down to 'List of adlists '

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._
![image](https://github.com/pi-hole/FTL/assets/3601462/377a5f12-59c9-4246-9248-fd875a1fd7d5)

### Additional context

_Add any other context about the problem here._
I was using pihole bundle in its latest version : Pi-hole v5.17.1 FTL v5.23 Web Interface v5.20.1 through docker-pi-hole image.
I then build and ran docker-pi-hole image with pihole-FTL base on branch development-v6.

I may have overlooked setup steps when using this version.
I realize that pihole-ftl v6 is still in his early stage and migration procedure might not be developped yet.
feel free to close this issue, if this is already known and not planned for the moment.

I've edited the gravity.db to add the missing columns, all seem ok.
`ALTER TABLE adlist ADD abp_entries INTEGER DEFAULT (0);`

**Comment by DL6ER** [comment]
@PromoFaux We should carefully investigate the effect of `SKIP_GRAVITY_ON_BOOT`. It could have caused issues during previous v5.x upgrades, too (assuming the feature is around for long enough)

**Comment by PromoFaux** [comment]
Yeah, it's been around for quite some time

https://github.com/pi-hole/docker-pi-hole/pull/672

But I think maybe a more sensible implementation going forward would be to add an `else if` to this section that reads out the version of existing database and checks it against the version from the migrations script - which would still allow users to skip on boot but force them to upgrade the db schema

https://github.com/pi-hole/docker-pi-hole/blob/a317129a41eac72d8a8b3f9097e4a7f1e1b1ed98/src/start.sh#L85-L95

**Comment by edgd1er** [comment]
I guess I have the first side effect of having modified the sqlite db manually.
Although the update is properly conducted, and stats seemed coherent, the adlist on domain is showing a -2

update through the web interface:
```
[i] Building tree...
  [✓] Building tree
  [i] Swapping databases...
  [✓] Swapping databases
  [✓] The old database remains available
  [i] Number of gravity domains: 811582 (478328 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 8
  [i] Number of exact whitelisted domains: 24
  [i] Number of regex whitelist filters: 2
  [i] Cleaning up stray matter...
  [✓] Cleaning up stray matter
 ```

I've with a backup of the databases (no manual intervention), and got the same result, no error during bdd upgrade + adlist update, -2 in number of blocked domains (`<span class="label bg-yellow pull-right" id="num_gravity" title="Total number of domains blocked by your Pi-hole">-2</span>`)
the value was given by /api/stats/summary:  ..."gravity":{"domains_being_blocked":-2}...
api_stats_summary , I believe, uses the sql query used is "SELECT COUNT(DISTINCT domain) FROM query_storage" or querystr = "SELECT value FROM info WHERE property = 'gravity_count';";

Here is the logs showing pihole-FTL noticed a problem:
```
docker-pi-hole-pihole-1  | 2023-07-25 18:40:51.091 [174/T175] INFO: Gravity database has been updated, reloading now
docker-pi-hole-pihole-1  | 2023-07-25 18:40:51.094 [174/T175] ERR: gravityDB_count(SELECT value FROM info WHERE property = 'gravity_count';) - SQL error step no more rows available
docker-pi-hole-pihole-1  | 2023-07-25 18:40:51.094 [174/T175] WARNING: Count of gravity domains not available. Please run pihole -g
docker-pi-hole-pihole-1  | 2023-07-25 18:40:51.101 [174/T175] INFO: Compiled 2 allow and 6 deny regex for 0 client in 3.3 msec
docker-pi-hole-pihole-1  | 2023-07-25 18:40:51.101 [174/T175] WARNING: Adlist with ID 35 (https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt) was inaccessible during last gravity run
```

problem was solved after a restart, gravity_count from info is populated after a restart.
This is a very small glitch and easily solved by a restart.

**Comment by edgd1er** [comment]
> I guess I have the first side effect of having modified the sqlite db manually. Although the update is properly conducted, and stats seemed coherent, the adlist on domain is showing a -2
> 
> update through the web interface:
> 
> ```
> [i] Building tree...
>   [✓] Building tree
>   [i] Swapping databases...
>   [✓] Swapping databases
>   [✓] The old database remains available
>   [i] Number of gravity domains: 811582 (478328 unique domains)
>   [i] Number of exact blacklisted domains: 0
>   [i] Number of regex blacklist filters: 8
>   [i] Number of exact whitelisted domains: 24
>   [i] Number of regex whitelist filters: 2
>   [i] Cleaning up stray matter...
>   [✓] Cleaning up stray matter
> ```
> 
> I've with a backup of the databases (no manual intervention), and got the same result, no error during bdd upgrade + adlist update, -2 in number of blocked domains (`<span class="label bg-yellow pull-right" id="num_gravity" title="Total number of domains blocked by your Pi-hole">-2</span>`) the value was given by /api/stats/summary: ..."gravity":{"domains_being_blocked":-2}... api_stats_summary , I believe, uses the sql query used is "SELECT COUNT(DISTINCT domain) FROM query_storage" or querystr = "SELECT value FROM info WHERE property = 'gravity_count';";
> 
> Here is the logs showing pihole-FTL noticed a problem:
> 
> ```
> docker-pi-hole-pihole-1  | 2023-07-25 18:40:51.091 [174/T175] INFO: Gravity database has been updated, reloading now
> docker-pi-hole-pihole-1  | 2023-07-25 18:40:51.094 [174/T175] ERR: gravityDB_count(SELECT value FROM info WHERE property = 'gravity_count';) - SQL error step no more rows available
> docker-pi-hole-pihole-1  | 2023-07-25 18:40:51.094 [174/T175] WARNING: Count of gravity domains not available. Please run pihole -g
> docker-pi-hole-pihole-1  | 2023-07-25 18:40:51.101 [174/T175] INFO: Compiled 2 allow and 6 deny regex for 0 client in 3.3 msec
> docker-pi-hole-pihole-1  | 2023-07-25 18:40:51.101 [174/T175] WARNING: Adlist with ID 35 (https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt) was inaccessible during last gravity run
> ```
> 
> problem was solved after a restart, gravity_count from info is populated after a restart. This is a very small glitch and easily solved by a restart.

after some tests, info is update after pihole -g but the webserver has a value in cache that won't update.

> Or simply always run
> 
> https://github.com/pi-hole/pi-hole/blob/eda83a4141747f2a73a39cdbe0c2dfd2375151e3/advanced/Scripts/database_migration/gravity-db.sh

something like that would upgrade database if needed, but is not very nice:
```
#migrate Database if needed:
gravityDBfile=$(getFTLConfigValue files.gravity)
piholeDir=/etc/pihole
source ${piholeDir}/utils.sh
source /etc/.pihole/advanced/Scripts/database_migration/gravity-db.sh
upgrade_gravityDB "${gravityDBfile}" "${piholeDir}"
```

**Comment by edgd1er** [comment]
> Or simply always run
> 
> https://github.com/pi-hole/pi-hole/blob/eda83a4141747f2a73a39cdbe0c2dfd2375151e3/advanced/Scripts/database_migration/gravity-db.sh

something like that would upgrade database if needed, but is not very nice:
```
#migrate Database if needed:
gravityDBfile=$(getFTLConfigValue files.gravity)
piholeDir=/etc/pihole
source ${piholeDir}/utils.sh
source /etc/.pihole/advanced/Scripts/database_migration/gravity-db.sh
upgrade_gravityDB "${gravityDBfile}" "${piholeDir}"
```
