### ISSUE TITLE
musl-libs support for arm64 arch

### ISSUE THREAD

**Issue by mjeveritt** [pi-hole/docker-pi-hole#1400]
hi, I appreciate this isn't the best place for this submission, but I've been looking into issues surrounding the dockerised version of pi-hole available at https://gitlab.com/yvelon/pi-hole and associated Alpine support (and related musl-libc issues).

I see that you've managed to get an amd64-musl build of FTL going successfully here, but would it be possible to extend that down to arm64 at least ? (since most pi's are indeed aarch64 architecture, and anyone running a musl-variant on their board would obviously benefit out-of-the-gate). Building on https://github.com/pi-hole/FTL/pull/553 shouldn't be a huge issue, as much of the principle portability changes are already made.

If there's anything I can do to ease this request on, please let me know - I've been working with arm[64] for quite a while now, and am quite able to do development/testing on real hardware if that is advantageous.

I'm hoping we can get some similar CI set up for the dockerised versions too, and I see you have quite a good system for ftl/pi-hole going, and I wonder if there may be some ideas we can utilise over on the gitlab instance too.

Thanks in anticipation!

**Comment by PromoFaux** [comment]
Well, the good news here is that we're working towards alpine for the official image.

Lots going on in the background and we will have a more official announcement soon but check out the (very much work in progress) `development-v6` branch of this repo for more details.

**Comment by mjeveritt** [comment]
ah that sounds awesome .. tagging here the other issue for reference, and to avoid too much duplication - https://gitlab.com/yvelon/pi-hole/-/issues/32

**Comment by mjeveritt** [comment]
I think it's fair to say this will be covered in the new branch as detailed above.

Multi-arch looks well covered in https://github.com/pi-hole/docker-pi-hole/blob/9c46f8b9ba097fe1d2172a96b255b012172c10ae/src/Dockerfile#L46-L51
