### ISSUE TITLE
DataTables warning: table id=domainsTable - Invalid JSON response.

### ISSUE THREAD

**Issue by therealthingy** [pi-hole/docker-pi-hole#1411]
### Versions

  Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)

### Platform

- OS and version:  Debian bullseye (Raspberry Pi OS Lite 64 bit)

- Platform:  Docker version 24.0.5, build ced0996

### Expected behavior
The page *Domain management* (URL path: admin/groups-domains.php) lists all domains.

### Actual behavior / bug
The page doesn't display the URLs (see screenshot).
This seems to be a serialization issue, as the json appears to be malformed (as shown in the Network tab in the screenshort).

### Screenshots
<img width="1412" alt="Screenshot 2023-07-31 at 11 46 52 AM" src="https://github.com/pi-hole/pi-hole/assets/45701117/b5627834-8ce5-406d-aee5-ab93b2b7bf65">
<img width="1349" alt="Screenshot 2023-07-31 at 11 53 04 AM" src="https://github.com/pi-hole/pi-hole/assets/45701117/8ea515ae-c270-4631-b098-f45a4157ff16">

### Additional context
MAY be related to: https://discourse.pi-hole.net/t/pihole-5-upgrade-error-datatables-warning-table-id-groupstable-ajax-error-for-more-information-about-this-error/32275/24

**Comment by PromoFaux** [comment]
> PIHOLE_UID: 1000
>       WEB_UID: 1000
>       PIHOLE_GID: 1000
>       WEB_GID: 1000

See the notes on the README here about the UID/GID variables: https://github.com/pi-hole/docker-pi-hole#experimental-variables
Short version, PIHOLE and WEB cannot have the same U/GID

**Comment by therealthingy** [comment]
> > PIHOLE_UID: 1000
> > WEB_UID: 1000
> > PIHOLE_GID: 1000
> > WEB_GID: 1000

Removing these fixed the issue

Thanks!
