### ISSUE TITLE
FTL failed to start due to bad option at line 1 of /etc/dnsmasq.d/dns-servers.conf	

### ISSUE THREAD

**Issue by CodingLappen** [pi-hole/docker-pi-hole#1424]
I have used the doh version and built it. 
I ran it and possibly the version is pretty old, but I don't understand why it doesnt run. 
RW - rights are set to 644 for root:root, so anyone should be able to read the file. 

Google (ECS, DNSSEC);8.8.8.8;8.8.4.4;2001:4860:4860:0:0:0:0:8888;2001:4860:4860:0:0:0:0:8844
OpenDNS (ECS, DNSSEC);208.67.222.222;208.67.220.220;2620:119:35::35;2620:119:53::53
Level3;4.2.2.1;4.2.2.2;;
Comodo;8.26.56.26;8.20.247.20;;
DNS.WATCH (DNSSEC);84.200.69.80;84.200.70.40;2001:1608:10:25:0:0:1c04:b12f;2001:1608:10:25:0:0:9249:d69b
Quad9 (filtered, DNSSEC);9.9.9.9;149.112.112.112;2620:fe::fe;2620:fe::9
Quad9 (unfiltered, no DNSSEC);9.9.9.10;149.112.112.10;2620:fe::10;2620:fe::fe:10
Quad9 (filtered, ECS, DNSSEC);9.9.9.11;149.112.112.11;2620:fe::11;2620:fe::fe:11
Cloudflare (DNSSEC);1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001

That are the contents of the file. 
I dunno what I did wrong here. 

Can you help me?

**Comment by PromoFaux** [comment]
I have a couple of questions:

 > I have used the doh version and built it.

From where? Pi-hole does not have any out of the box doh capabilities.

> /etc/dnsmasq.d/dns-servers.conf

What is this file doing here? It should be in `/etc/pihole`

How have you set up your container? What does your compose file/run script look like?
