### ISSUE TITLE
Pi-hole redownloads adlists too frequently/unnecessarily

### ISSUE THREAD

**Issue by DevKyleS** [pi-hole/docker-pi-hole#1425]
### Expected behavior

* Pi-hole doesn't re-download an adlist unnecessarily when it just downloaded seconds or minutes prior, wasting bandwidth and slowing startup/readiness time.
* Pi-hole/gravity.sh caches or tracks the last time it redownloaded each adlist, even if it hasn't completed updating the gravity database yet.
* Update frequency interval is controllable by a configuration for how frequent to update adlists (eg, default to every 10min, and can force updating by ui/cli).

### Actual behavior / bug

Pi-hole is redownloading every adlist upon service startup

### Steps to reproduce

1. Start pi-hole
2. Stop pi-hole before it runs the `update_gravity_timestamp` function in `gravity.sh`
3. Start pi-hole

**Comment by yubiuser** [comment]
Set the environment variable `SKIPGRAVITYONBOOT` and it won't download on container start.
See the Readme https://github.com/pi-hole/docker-pi-hole#advanced-variables
