### ISSUE TITLE
Wrong architecture check for i386

### ISSUE THREAD

**Issue by Etn40ff** [pi-hole/docker-pi-hole#1445]
I encountered the following bug while running on an old i386 thinclient:
```
# docker run -it pihole/pihole:latest
Unable to find image 'pihole/pihole:latest' locally
latest: Pulling from pihole/pihole
0f5d158483bd: Pull complete
d4d969cfc411: Pull complete
4f4fb700ef54: Pull complete
061a6a1d9010: Pull complete
8b1e64a56394: Pull complete
620dc3b85829: Pull complete
bf935e2a4a6f: Pull complete
1e0496e1bab5: Pull complete
7a48f0a3e41a: Pull complete
Digest: sha256:8bc45afe1625487aef62859a5bf02f3d7b3429e480f4e29e4689635ab86ec312
Status: Downloaded newer image for pihole/pihole:latest
/s6-init: 37: exec: s6-overlay-suexec: Exec format error
```

I think it might be related to the line https://github.com/pi-hole/docker-pi-hole/blob/master/src/s6/debian-root/usr/local/bin/install.sh#L21C15-L21C15 

Is that a typo? shoul it read  `S6_ARCH="i386";;` instead?

**Comment by PromoFaux** [comment]
Interesting. S6 don't provide an i386 binary, which is why I used i686 (https://github.com/just-containers/s6-overlay/releases)

Goes to show how many people are 32 bit machines that this is the first we've come across the issue :)

For version 6 (currently under test on the branch `development-v6`) we're dropping S6 entirely and going for an alpine base. Can you try `docker run -it pihole/pihole:development-v6`?

**Comment by Etn40ff** [comment]
> Goes to show how many people are 32 bit machines that this is the first we've come across the issue :)

Yep i386 is a dead arch I suppose.

 
> For version 6 (currently under test on the branch `development-v6`) we're dropping S6 entirely and going for an alpine base. 

Do you mean that soon™ I will be able to run pihole directly from alpine?

> Can you try `docker run -it pihole/pihole:development-v6`?

This seems to work fine

**Comment by PromoFaux** [comment]
OK, feel free to test out using the development-v6 branch (there is some update info in the README about this version) on your i386 hardware. It's a moving target at the moment, but it's been running fine on my systems for a few months now
