### ISSUE TITLE
Placeholder page appears on fresh install of v5.17.1

### ISSUE THREAD

**Issue by jjarokergc** [pi-hole/docker-pi-hole#1447]
### Versions
  Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)

### Platform
Ubuntu 22.04

### Actual behavior / bug
A fresh installation of v5.17.1 on a new container running Ubuntu 22.04 displays the lighttpd placeholder page when accessing pihole's main interface (not admin).

_A clear and concise description of what the bug is._

It appears that the `pihole` directory is missing in `/var/www/html`

When upgrading to v5.17.1 from an older version, this directory is present and the pihole logo is displayed when accessing the main url.

### Steps to reproduce
Fresh install of pihole using the `basic-install.sh` script

## Debug Token

- URL:  Your debug token is: https://tricorder.pi-hole.net/EMavyWN6/

**Comment by yubiuser** [comment]
Your `lighttpd` config still contains
```
$HTTP["host"] == "pi.hole" {
       $HTTP["url"] == "/" {
           url.redirect = ("" => "/admin/")
       }
   }
```

Which should handle the redirect. What URL are you accessing when it fails?

**Comment by jjarokergc** [comment]
Hello,

I noticed that this was transferred to the docker project, but I install directly in a ubuntu workstation.  

I have several piholes in different VLANs and access them using a URL such as http://pihole0.staging or even the IP address.  In previous versions, I would see the pihole logo.  If I enter http://pi.hole then I am redirected to the admin page, which is not useful since I sometimes need to access dns for a specific vlan.

Is this the intended functionality?  It is unexpected because it is different from the previous versions.

**Comment by rdwebdesign** [comment]
The web interface should be accessed using `http://pi.hole/admin` or `http://<pihole_IP>/admin`.
The `/admin` part can be omitted **only** when the domain is `pi.hole` (look at the code in ***yubiuser***'s comment above).

If you changed `lighttpd` configuration, or if you are using a different hostname, or if you are using a reverse proxy you need to adapt your config.

**Comment by rdwebdesign** [comment]
> Is this the intended functionality?

Yes.

> It is unexpected because it is different from the previous versions.

Actually, this was announced in more than one place, more than 9 months ago:

- https://discourse.pi-hole.net/t/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/60495
- https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/

**Comment by snil1984** [comment]
Hello, congratulations on the project. However, I report that we followed the steps mentioned to redirect the blocks to a customized page, however, with no effect.
Would there be any other steps, without being mentioned in the links provided?

Environment: Ubuntu Server, installed pihole on docker. Access normally and blocks are also done, however, when access to blocked pages on the personalized page does not appear.
Follow these steps:

https://discourse.pi-hole.net/t/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/60495
https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/#page-content

--Add
https://www.knowcitrix.com/posts/pihole-custom-block-page/

Thank you for your help
