### ISSUE TITLE
Web interface not accessible after container restart until the lists in the background are downloaded

### ISSUE THREAD

**Issue by LizenzFass78851** [pi-hole/docker-pi-hole#1463]
### Versions

- Pi-hole: development-v6 ed5d794
- web: development-v6 a2567bf
- FTL: development-v6 vDev-baea4a8

### Platform

- OS and version:  Ubuntu 22.04 amd64

- Platform:  Docker (using docker compose)

### Expected behavior

When you restart the pihole container, the web interface should be accessible immediately, as is the case with v5. Even if it reloads or synchronizes the block lists in the background after restarting the container.

### Actual behavior / bug

When the Pihole container restarts, it downloads the lists in the background, which is not the problem, but while Pihole is doing this, the web interface is not reachable (and apparently the pihole as a DNS server is also not reachable)

### Steps to reproduce

1. I go to the `Lists` menu item
2. I remove the default list from stevenblocks
3. I add a large collection of [blocklists](https://github.com/RPiList/specials/blob/master/Blocklisten.md) from @RPiList
4. I go to the console and download the lists with `pihole -g`. (Meanwhile, the web interface is still accessible during and after the list update)
5. I stop and restart the pihole container with the commands `docker-compose down && docker-compose up -d`.
6. in `docker logs (container name)` you can see that it is comparing the lists again (and from then on the web interface is not accessible and DNS queries don't work either until the download or the comparison for the lists in the background is finished.)

## Debug Token

- URL1: https://tricorder.pi-hole.net/VK2OneYu
- URL2: https://tricorder.pi-hole.net/6a8AwzR9

### Additional context

It may be a strange error, but I would like to mention it because in pihole version 5 it worked as I described above.
It would be bad if someone entered a lot of block lists, which also helps protect the internet and the pihole in v6 can no longer work properly with large lists or the reactions described above occur.

**Comment by yubiuser** [comment]
Set `SKIPGRAVITYONBOOT=true` as environment variable to prevent list downloading and parsing during container start.

**Comment by LizenzFass78851** [comment]
Thanks. It worked. 
Even though I find it strange that this procedure with the background download of the lists after the container restart does not work as well as with v5 (where the web interface / FTL was also active during the background downloads)

**Comment by PromoFaux** [comment]
It's only on container start, because FTL is not started until after the gravity check.

Maybe we can look at starting FTL first, but would need to look into the knock on effects there.

How often are you restarting the container that this causes a serious issue? I get that the beta build updates more frequently, but ordinarily one doesn't actually need to restart the container all that often...

**Comment by LizenzFass78851** [comment]
actually different.
Sometimes when an update of the container was made via watchtower or manually or for various reasons when the host computer needs to be restarted, including through updates, maintenance, etc.

**Comment by PromoFaux** [comment]
Per the readme (which also mentions the skip gravity env var)... We recommend you do not use watchtower to update your Pi-hole container.

**Comment by RPiList** [comment]
> We recommend you do not use watchtower to update your Pi-hole container.

Why? Whats the problem with watchtower and more important: What do you recommend to use to update containers?

Greetings

**Comment by PromoFaux** [comment]
Watchtower is fine for most things, but we don't think you should use it for keeping Pi-hole up to date. It's all right there on the Readme of this repo... ;)

https://github.com/pi-hole/docker-pi-hole#note-on-watchtower

**Comment by RPiList** [comment]
> https://github.com/pi-hole/docker-pi-hole#note-on-watchtower

Thx, thought there might be a problem with Watchtower. But yeah... Don't do important stuff (like updating your pihole) when not around to check if update went well.

Thx and greetings

**Comment by dschaper** [comment]
Watchtower is fine when set to notify only for that container. The guides show a few different ways to make that happen, you can disable updates for all containers and mark certain ones to be updated or update all containers and mark certain ones to not update. I use this on Synology and Portainer because Synology breaks horribly if you try to update the Portainer container in any way other than manually.
