### ISSUE TITLE
Error during building

### ISSUE THREAD

**Issue by m0li13** [pi-hole/docker-pi-hole#1496]
**Error during Pi-hole Deployment**  

## Details
While executing the build-and-test.sh script, there is an error which stop the docker build proccess.
![image](https://github.com/pi-hole/docker-pi-hole/assets/152263975/8679f28f-98c6-4b1e-bd23-52092ae2110e)

## How to resolve this
It is needed to edit the Dockerfile, placed in test directory. in order to use the latest docker version:
**COPY --from=docker:latest /usr/local/bin/docker /usr/local/bin/**

## How to reproduce the issue 

1. Environment data
  * Operating System: **Raspbian** 
  * Hardware: **RasPi /3B/**
  * Docker Install Info and version: 
    - **Docker version 24.0.7**

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by jd-apprentice** [comment]
I don't think using the `:latest` is a good idea, it more secure that someone will encounter an error if every build runs on a different version
