### ISSUE TITLE
Seeing blank screen on homepage with 2024.01.0 image

### ISSUE THREAD

**Issue by jhawk7** [pi-hole/docker-pi-hole#1530]
I'm getting a blank screen on the homepage with the latest docker image which I believe is [2024.01.0.](https://hub.docker.com/layers/pihole/pihole/2024.01.0/images/sha256-3c6c30c6d80e02692e8da43bdad1e1abeb85258bae507d9a252a45ac5b1c5ddf?context=explore). Rolling back to a previous build fixed the issue. I'm running pihole on kubernetes via this [helm chart ](https://artifacthub.io/packages/helm/mojo2600/pihole) which pulls the latest image.

Using latest build (2024.01.0)
![Screen Shot 2024-01-13 at 12 55 04 PM](https://github.com/pi-hole/docker-pi-hole/assets/13038876/c5a31d1e-0470-43d1-af6f-7e34035a6a40)

Using prev build (2023.11.0)

![Screen Shot 2024-01-13 at 12 58 40 PM](https://github.com/pi-hole/docker-pi-hole/assets/13038876/ab2dbfcf-5180-41e4-9be2-4cc852be71f2)

This is a: **Run Issue**  

## How to reproduce the issue 

1. Environment data
  * Operating System: **Rasbian** 
  * Hardware: RasPi 4B 
  * Kernel Architecture: ArmV8 64bit 
  * Docker Install Info and version: 
    - Software source: official pihole docker image; latest build(2024.01.0) 
    - Supplimentary Software: 
  * Hardware architecture: 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

- Rolling back to a previous build fixed the issue. I believe there a may be an issue with the static files for the latest build.

**Comment by PromoFaux** [comment]
Nothing has changed, but is this still an issue in 2024.02.0?
