### ISSUE TITLE
cant make changes

### ISSUE THREAD

**Issue by yggdrasil75** [pi-hole/docker-pi-hole#1537]
This is a: Bug

## Details

I just switched from windows to ubuntu and tried to set copy over an existing docker of pihole. when I then tried making changes, I got errors about "read only database"
I deleted the folder and made it anew, adding a new docker compose with defaults and ran it. same error
## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

#1012 
This is similar, I can use sudo from within docker, and I have tried setting the user id to my user and web userid to 033 manually. I still get the error

## How to reproduce the issue 

1. Environment data
  * Operating System: **ubuntu** 
  * Hardware: PC 
  * Kernel Architecture:amd64 
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: 
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
default compose from the issue, with only change being adding my own password
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause (when I did this, I suddenly didnt have any queries except "dgo-4.cfd")

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by rdwebdesign** [comment]
1. Can you please post the Compose file or `docker run` command used to start the container?

2. Also, generate a debug log:

    **Using the command line (inside the container):**
    - use `pihole -d` command.
    - when asked to upload the log, answer <kbd>Y</kbd>.
    - **copy **only the token** and paste here.
    
    **Using the web interface:**
    - click on _**Tools > Generate Debug Log**_ menu.
    - then mark the second checkbox to upload the log and click on the big button.
    - when finished, **copy only the token** and paste here.

**Comment by rdwebdesign** [comment]
Your issue is probably related to permissions:

```
*** [ DIAGNOSING ]: Pi-hole FTL Query Database
-rw-rw-r--+ 1 pihole pihole 556K Feb  6 10:21 /etc/pihole/pihole-FTL.db

*** [ DIAGNOSING ]: Gravity Database
-rw-rw-r--+ 1 pihole pihole 9.3M Feb  6 09:27 /etc/pihole/gravity.db
```

The `+` in `-rw-rw-r--+` means you have some special permissions set (Access Control List - ACL).

These permissions (set on the host) are probably creating problems inside the container.

As a test, try without volumes.

**Comment by rdwebdesign** [comment]
This is what I have in my container:
```console
root@pihole:/# ls -lah /etc/pihole/
total 264M
drwxrwsr-x 2 pihole pihole 4.0K Feb  6 15:08 .
drwxr-xr-x 1 root   root   4.0K Jan 22 12:22 ..
-rw-r--r-- 1 root   root    65 Sep 12  2022 adlists.list
-rw-r--r-- 1 root   root   737 Sep 12  2022 custom.list
-rw-r--r-- 1 pihole pihole    0 Sep 12  2022 dhcp.leases
-rw-r--r-- 1 root   root   651 Jan 22 12:22 dns-servers.conf
-rw-r--r-- 1 root   root     7 May 30  2023 ftlbranch
-rw-rw-r-- 1 pihole pihole 9.6M Feb  4 03:11 gravity.db
-rw-r--r-- 1 root   pihole  799 May 30  2023 install.log
-rw-r--r-- 1 root   root    65 Feb  4 03:11 local.list
-rw-r--r-- 1 root   root   241 Sep 12  2022 logrotate
-rw-r--r-- 1 pihole pihole 3.0M May 30  2023 macvendor.db
-rw-r--r-- 1 root   root   197 Jan 22 12:22 pihole-FTL.conf
-rw-rw-r-- 1 pihole pihole 239M Feb  6 15:08 pihole-FTL.db
-rw-r--r-- 1 root   root   528 Jan 22 21:21 setupVars.conf
-rw-r--r-- 1 root   root   528 Jan 22 12:22 setupVars.conf.update.bak
-rw-r--r-- 1 root   root   379 Feb  5 17:49 versions
```
