### ISSUE TITLE
WEBTHEME not recognizing lcars-picard

### ISSUE THREAD

**Issue by kenpachizero** [pi-hole/docker-pi-hole#1543]
Bug, 
This is a: Issue with the WEBTHEME environment variable in pihole

## Details
Set the WEBTHEME to lcars-picard and i get this error in the logs:

 [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [i] Installing /etc/dnsmasq.d/01-pihole.conf...
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [i] Installing /etc/.pihole/advanced/06-rfc6761.conf...
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
  [i] Installing latest logrotate script...
	[i] Existing logrotate file found. No changes made.
  [i] Assigning password defined by Environment Variable
  [✓] New password set
  [!] Invalid theme name supplied: lcars-picard, falling back to default-light.
  [i] Added ENV to php:
                    "TZ" => "",
                    "PIHOLE_DOCKER_TAG" => "",
                    "PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
                    "CORS_HOSTS" => "",
                    "VIRTUAL_HOST" => "pihole",
  [i] Using IPv4 and IPv6
  [i] Installing latest Cron script...

## How to reproduce the issue 

1. Environment data
  * Operating System: Apline
  * Hardware: Raspberry Pi 4B
  * Kernel Architecture: ArmV8 64bit
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: portainer
  * Hardware architecture: ArmV8 64bit

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
screenshots attached
![2](https://github.com/pi-hole/docker-pi-hole/assets/34297518/7b40d2d6-9c8a-4052-ad7a-b7b59505fcca)
![3](https://github.com/pi-hole/docker-pi-hole/assets/34297518/155bd374-3bae-4251-9d16-44effb20c534)
![1](https://github.com/pi-hole/docker-pi-hole/assets/34297518/03ae7405-1e23-4ddd-9ef6-9817431febe1)

3. any additional info to help reproduce

## These common fixes didn't work for my issue
- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have checked web/scripts/pi-hole/php/theme.php and can see the line: $available_themes['lcars-picard'] = array('Star Trek Picard LCARS theme (dark)', true, 'lcars-picard', '#53596C');
- [x] ![4](https://github.com/pi-hole/docker-pi-hole/assets/34297518/d24c5415-3274-444e-993f-2225a636c81b)

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by PromoFaux** [comment]
Please try again in the latest image - this should now be fixed!

**Comment by kenpachizero** [comment]
Yes that did work, Thank you.
