### ISSUE TITLE
DNS Resolving not work after docker restart with readonly /etc/cron.d/pihole

### ISSUE THREAD

**Issue by mEDI-S** [pi-hole/docker-pi-hole#1560]
Hello, i have an  issue with my server setup and know not the problem
after any restart hang the dns resolving, ony after settings->DNS->save config work it

i use pi-hole in my server and start it via systemd
 i have 3 directorys and files mounted

       -v "/home/docker/%p/etc-pihole:/etc/pihole" \
       -v "/home/docker/%p/dnsmasq:/etc/dnsmasq.d" \
       -v "/home/docker/%p/pihole.cron:/etc/cron.d/pihole" \

remove the old docker and volumes at start

     ExecStartPre=-/bin/sh -c "/usr/bin/docker rm %p"

and run it with --rm

    ExecStart=/usr/bin/docker run  --rm \

so no more old volumes from the docker before existing!

i use other ports for my docker, on frond have i a dns cache with powerdns

    -p 127.0.0.1:5310:53/tcp -p 127.0.0.1:5310:53/udp \
    -p 127.0.0.1:8053:80 \

the result if he found his config not or hangs after restart. if i go to settings->dns and save the config, the settings ui know the last config, work pi-hole again.

on wat location if the missing config saved? not in /etc/pihole or /etc/dnsmasq.d
the log say notting
wat files create the button on settings->dns->save ?

the log say after restart and saved config only this

`
  [i] Starting docker specific checks & setup for docker pihole/pihole
  [i] Setting capabilities on pihole-FTL where possible
  [i] Applying the following caps to pihole-FTL:
        * CAP_CHOWN
        * CAP_NET_BIND_SERVICE
        * CAP_NET_RAW
  [i] Ensuring basic configuration by re-running select functions from basic-install.sh

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf

  [i] Installing latest logrotate script...
        [i] Existing logrotate file found. No changes made.
  [i] Assigning password defined by Environment Variable
  [✓] New password set
  [i] Added ENV to php:
                    "TZ" => "Europe/Berlin",
                    "PIHOLE_DOCKER_TAG" => "",
                    "PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
                    "CORS_HOSTS" => "",
  [i] Using IPv4 and IPv6

install: cannot remove '/etc/cron.d/pihole': Device or resource busy
s6-rc: info: service _startup successfully started
s6-rc: info: service pihole-FTL: starting
s6-rc: info: service pihole-FTL successfully started
s6-rc: info: service lighttpd: starting
s6-rc: info: service lighttpd successfully started
s6-rc: info: service _postFTL: starting
s6-rc: info: service _postFTL successfully started
s6-rc: info: service legacy-services: starting
  [i] Installing latest Cron script...  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
s6-rc: info: service legacy-services successfully started
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [✓] Creating new gravity databases

...
## he get all gravity files

  [✓] Building tree
  [✓] Swapping databases
  [✓] The old database remains available
  [i] Number of gravity domains: 3900726 (2338073 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 1
  [i] Number of regex whitelist filters: 0
  [✓] Cleaning up stray matter

  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled

  Pi-hole version is v5.18.1 (Latest: v5.18.1)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.25.1 (Latest: v5.25.1)
  Container tag is: 2024.03.1

#### my settings->-dns->save
Stopping pihole-FTL
Terminated

`

i try my test with

    dig @127.0.0.1 -p 5310 heise.de

from host it give a timeout if the problem existing

PS: the problem is old and not new

**Comment by PromoFaux** [comment]
What does your entire docker run command look like?

Another question - why are you mounting cron.d?

**Comment by mEDI-S** [comment]
this if the systemd service

`[Unit]
Description=%p container
Requires=network-online.target
After=network-online.target

[Service]
Restart=always
RestartSec=10s
TimeoutStartSec=0
ExecStartPre=-/bin/sh -c "mkdir -p /home/docker/%p/etc-pihole /home/docker/%p/dnsmasq"
ExecStartPre=-/bin/sh -c "/usr/bin/docker rm %p"
ExecStart=/usr/bin/docker run \
    --rm \
    --name %p \
    -p 127.0.0.1:5310:53/tcp -p 127.0.0.1:5310:53/udp \
    -p 127.0.0.1:8053:80 \
    -e TZ="Europe/Berlin" \
    -v "/home/docker/%p/etc-pihole:/etc/pihole" \
    -v "/home/docker/%p/dnsmasq:/etc/dnsmasq.d" \
    -v "/home/docker/%p/pihole.cron:/etc/cron.d/pihole" \
    --hostname mydnsdomain \
    -e VIRTUAL_HOST="mydnsdomain" \
    pihole/pihole:latest
ExecStop=/usr/bin/docker stop %p

[Install]
WantedBy=multi-user.target`


to the conjob. i update my lists all 24h, pishing/scam/spam protection is useless with weekly upgrade interwall ;)

**Comment by PromoFaux** [comment]
Interesting, I've not come across a docker container as a systemd service before - any reason you're not just using compose or run with restart:always? 

Also noticed: `install: cannot remove '/etc/cron.d/pihole': Device or resource busy` in your log output. Do you have the same issues if you _don't_ mount the cron file?

**Comment by rdwebdesign** [comment]
Maybe it is similar to this one:
https://docs.docker.com/storage/troubleshooting_volume_errors/#error-unable-to-remove-filesystem

**Comment by mEDI-S** [comment]
Hello, yes the cronjob install step is the break i cange my mount option to

    -v "/home/docker/%p/cron.d:/etc/cron.d" \

and mount the dierctory, now hav i the problem, he overwrite always my changes and write his own cronjob :)

existing a way to force the pull time or do not owerwrite a existing cronjob or hmm any other way (do not fail on ro cronjob file) heh :)

happy easter

**Comment by PromoFaux** [comment]
Might I suggest trying the v6 beta image? (`development-v6` branch). Make sure you read the Readme on that branch first as some of the variables have changed etc, but the image has been redesigned from the ground up.

With the v6 image I _think_ you should be able to get away with mounting something to `/crontab.txt` - the only change that happens to that file on startup is that the gravity and updatechecker times are randomised before it is read with `/usr/bin/crontab`  

https://github.com/pi-hole/docker-pi-hole/blob/2004ba2515d71066802e4b5547222f98a69f6b53/src/start.sh#L64-L71

**Comment by rdwebdesign** [comment]
Why are you trying to change the cronjob inside the container?

I think you can create a cronjob on the host OS to execute a `docker exec ...` command.

**Comment by PromoFaux** [comment]
> I think you can create a cronjob on the host OS to execute a `docker exec ...` command.

Ah yes, this is also a good alternative

**Comment by mEDI-S** [comment]
> Might I suggest trying the v6 beta image? (`development-v6` branch). Make sure you read the Readme on that branch first as some of the variables have changed etc, but the image has been redesigned from the ground up.

the direct migration fail from stable to the development-v6 version

2024-04-02 18:17:38.792 [159M] ERROR: SQLite3: no such table: main.antigravity in "SELECT adlist_id from vw_antigravity WHERE domain = ? AND group_id IN (0);" (1)
2024-04-02 18:17:38.792 [159M] ERROR: gravityDB_open("SELECT(... vw_antigravity ...)") - SQL error prepare: SQL logic error
2024-04-02 18:17:38.792 [159M] ERROR: Gravity database not available (allowlist)

i add the cronjob on host to pull the lists.

Thanks for the help
