### ISSUE TITLE
Cannot lunch DHCP SERVER / FTL failed to start  NET_ADMIN

### ISSUE THREAD

**Issue by AR404lab** [pi-hole/docker-pi-hole#1561]
### Versions

- Pi-hole:  v5.18.1 (Latest: v5.18.1)
- AdminLTE:  v5.21 (Latest: v5.21)
- FTL:  v5.25.1 (Latest: v5.25.1)

### Platform

- OS and version:  Debian 12

- Platform:  Proxmox (v8.1.4) / Portainer (v2.16.2)

### Expected behavior

PHP error (2): fsockopen(): unable to connect to 127.0.0.1:4711 (Connection refused) in /var/www/html/admin/scripts/pi-hole/php/FTL.php:47

### Actual behavior / bug

![image](https://github.com/pi-hole/FTL/assets/97963753/6264e15c-de20-417c-b847-8f9358761821)

[log.txt](https://github.com/pi-hole/FTL/files/14816384/log.txt)

**Comment by AR404lab** [comment]
I'm not familiar with the docker environment yet, I don't know if I proceeded the right way, I added NET_ADMIN in the ENV section of portainer but I still have the same problem, it doesn't seem to launch the FTL function. 

![image](https://github.com/pi-hole/docker-pi-hole/assets/97963753/5882df66-ed45-494e-8463-2dd336d5a175)

**Comment by PromoFaux** [comment]
Are you using the portainer GUI to create the container? Or is it set up using a stack? The latter is effectively docker-compose.

If the former, when you create the container you need to scroll down to the Advanced Container Settings, and select the Capabilities tab.... from there you will need to toggle on `NET_ADMIN`

![caps](https://github.com/pi-hole/docker-pi-hole/assets/1998970/f3893163-a15a-4fdb-9d7e-e63e5bdbad23)

If the latter then use the docker quick start example from the readme to get you started

https://github.com/pi-hole/docker-pi-hole#quick-start
