### ISSUE TITLE
_uid-gid-changer.sh id -g ${groupname} gives wrong gid back

### ISSUE THREAD

**Issue by alst-ovh** [pi-hole/docker-pi-hole#1570]
Set PIHOLE_UID and PIHOLE_GID to 0
then id -g pihole gives back 0 but thats wrong, it's always 1000

Change 
#local currentId=$(id -g ${groupname})
to
  local currentId=$(getent group ${groupname} | cut -d: -f3)

then it works

**Comment by PromoFaux** [comment]
Can you test this against the beta (`development-v6`) image please (check over the Readme first as there are a few changes from v5->v6)
