### ISSUE TITLE
Stop working in latest Docker Desktop release.

### ISSUE THREAD

**Issue by PatricioooAG** [pi-hole/docker-pi-hole#1578]
I try to install the latest releases of Docker but after a few hours PiHole stop working, and I need update Gravity or restart the container. The last release I can use fine is 17. I don’t getting error in console. 

This is a: **FILL ME IN**  
Run issue

## Related Issues
- [x ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

I know VirtioFS have permission problem but I can’t get too much info. 

## How to reproduce the issue 

1. Environment data
  * Operating System: **ENTER HERE** MacOs Sonoma
  * Hardware: Mac M series
  * Kernel Architecture: 
  * Docker Install Info and version: 
    - Software source: 
    - Supplimentary Software: 
  * Hardware architecture: 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here 

```
docker run -d --name pihole 
  -e ServerIP=10.0.0.1  -e TZ=Europe/Madrid  -e DNS1=10.0.0.1 
  -p 8087:80 
  -p 10.0.0.18:53:53/tcp 
  -p 10.0.0.18:53:53/udp 
  -p 443:443 
  -v ~/pihole/:/etc/pihole/  -v ~/dnsmasq.d:/etc/dnsmasq.d  
  --dns=127.0.0.1  --dns=127.0.0.1  --dns=1.1.1.1 
  --restart=unless-stopped 
  pihole/pihole:latest
```
3. any additional info to help reproduce

## These common fixes didn't work for my issue
I try different sharing implementation like VirtioFS and gRPC FUSE. I try too without virtualization on and off. 
- [x ] I have tried removing/destroying my container, and re-creating a new container
- [ x] i have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by PromoFaux** [comment]
I don't have a machine running MacOS to be able to test/troubleshoot this. Is it only an issue on the `:latest` tag?

**Comment by PatricioooAG** [comment]
> I don't have a machine running MacOS to be able to test/troubleshoot this. Is it only an issue on the `:latest` tag?

Yes. 4.17 is working and the problem are from 4.20 to the latest 4.31. Pihole is in latest too.

**Comment by PromoFaux** [comment]
I am confused. Where are these version numbers from?

**Comment by PatricioooAG** [comment]
> I am confused. Where are these version numbers from?

Sorry, I’m Spanish with poor English. https://docs.docker.com/desktop/release-notes/

**Comment by PromoFaux** [comment]
Oh, I see. So it's an update to the actual docker engine that is causing issues with the Pi-hole image? Or are you having issues with all containers?

What are the exact symptoms? When it stops working, is there anything interesting to see in the log files? `/var/log/pihole*`

Does it relate at all to this issue? https://github.com/pi-hole/docker-pi-hole/issues/951

Maybe it's time to buy myself a Macbook..... 😬

**Comment by PatricioooAG** [comment]
> Oh, I see. So it's an update to the actual docker engine that is causing issues with the Pi-hole image? Or are you having issues with all containers?
> 
> What are the exact symptoms? When it stops working, is there anything interesting to see in the log files? `/var/log/pihole*`
> 
> Does it relate at all to this issue? #951
> 
> Maybe it's time to buy myself a Macbook..... 😬

So, other images containers are working fine. No logs or messages. The symptoms are the stop opening webs in a few hours after run the image. I need some time to try the disk solution #951 or log; between you buy a MacOS I can test if you need… Thanks.

**Comment by PatricioooAG** [comment]
Docker Desktop 4.32.0 (157355) is working better. this morning I don't have error.

**Comment by PromoFaux** [comment]
Thanks the report - I never did get around to buying myself a macbook! (I'm sure my bank balance will thank me....)
