### ISSUE TITLE
No latest docker tag for 2024.06.0 (The "I can't believe it wasn't working on 32-bit machines for the past year" edition

### ISSUE THREAD

**Issue by corasaniti** [pi-hole/docker-pi-hole#1602]
It appears that the latest docker tag of version `2024.06.0`  is not available in the Docker registry. 
I get a notification that an update is available, but if I pull the latest tag I don't see any new versions.
I only see the change in the dev branch
Thanks in advance

**Comment by rdwebdesign** [comment]
Yeah... The build failed.
Thanks for reporting it.

We need to check what happened, but I'm not sure this will be done today.

**Comment by yubiuser** [comment]
Please try again now, should be working now.

**Comment by rdwebdesign** [comment]
Now it worked. 🤷‍♂️ 

<img src="https://github.com/pi-hole/docker-pi-hole/assets/1385443/0d29e4a6-5fc4-40a6-9870-80c3977bb0a6" width=600>
