### ISSUE TITLE
2024.07.0 is not listed as the latest release

### ISSUE THREAD

**Issue by korikori** [pi-hole/docker-pi-hole#1610]
This is a: Feature Request

## Details

This is not really a bug nor a feature request, but I noticed that the most recent 2024.07.0 release does not have the latest tag which I assume must not have been intentional.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **ENTER HERE** 
  * Hardware: 
  * Kernel Architecture: 
  * Docker Install Info and version: 
    - Software source: 
    - Supplimentary Software: 
  * Hardware architecture: 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by PromoFaux** [comment]
Interesting. Not quite sure why that would be.. didn't do anything different to usual!

**Comment by PromoFaux** [comment]
Ah, just the release on the repo. Thanks for pointing it out, I've sorted it. I must have unchecked something during the release process.

The image tag of `latest` should still point at `2024.07.0` though

**Comment by rdwebdesign** [comment]
Maybe related to Github actions issue, around the same time the image was released: https://www.githubstatus.com/incidents/5yx1d67vq9hg
