### ISSUE TITLE
Cannot access webui

### ISSUE THREAD

**Issue by vvirtues** [pi-hole/docker-pi-hole#1617]
This is a: **Run Issue**  

## Details

After installing, I cannot access the UI at all through any address. I can access the default lightpd page from `localhost` but nothing else (including `localhost/admin`)
## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **WSL (Ubuntu)** 
  * Hardware: PC
  * Kernel Architecture: assume x64/amd64
  * Docker Install Info and version: 
    - Software source: Docker Desktop (Windows)
    - Supplimentary Software: 
  * Hardware architecture: x64(?)

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
![image](https://github.com/user-attachments/assets/b835c92c-7acd-417e-a6e6-58f274deb8e2)
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by vvirtues** [comment]
btw im using firefox, tested with DoH on and off (same result)

**Comment by vvirtues** [comment]
seems volumes are not being used

**Comment by vvirtues** [comment]
wsl shell:
![image](https://github.com/user-attachments/assets/46a90025-cf36-442b-a4fe-96050c3a5dcd)
powershell: 
![image](https://github.com/user-attachments/assets/94d14ee8-68d0-4259-9946-791ec65be8ce)
have a feeling its related to that

**Comment by vvirtues** [comment]
still need help with this

**Comment by PromoFaux** [comment]
> Operating System: WSL (Ubuntu)

WSL or WSL2? I have a feeling WSL is not compatible - but it's been a while since I've tried.

I used Docker with the WSL2 based engine all the time for testing and am able to access the web UI from my PC....

**Comment by vvirtues** [comment]
wsl2, sorry for not specifying

**Comment by PromoFaux** [comment]
Works for me... interesting that it does not for you! Do you have any other web services running either in docker or otherwise on your Windows PC?

![image](https://github.com/user-attachments/assets/a3cc86de-f21a-4c15-8b37-b3b05470b1e1)

**Comment by PromoFaux** [comment]
OH. You're missing the `FTLCONF_LOCAL_IPV4` environment variable (It's listed in the [Readme](https://github.com/pi-hole/docker-pi-hole#recommended-variables) 😉)

Before:
![image](https://github.com/user-attachments/assets/5801f9e6-a7a8-4511-8ae5-b0c4876bfd2d)

After:
![image](https://github.com/user-attachments/assets/8db19417-96bf-45b6-b2cb-8142a6055e89)

This variable will not be needed in the upcoming V6 release

**Comment by vvirtues** [comment]
for some reason entering my local IP doesn't work #1658 

is it okay to set as localhost instead?

**Comment by vvirtues** [comment]
i realized you are not using host networking, thats one big thing @PromoFaux
