### ISSUE TITLE
Warning about non standard property "zoom" in page php files

### ISSUE THREAD

**Issue by speedbird182** [pi-hole/docker-pi-hole#1619]
This is a: Bug/Feature Request

## Details
When loading any page with the Developer Tools open, it produces a warning on every page load:

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

This shows as being in every page.

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 
Open Developer Tools in browser
Load any page
Error shows

1. Environment data
  * Operating System: Ubuntu
  * Hardware:RasPi 3B
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: portainer
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [Yes ] I have tried removing/destroying my container, and re-creating a new container
- [Yes] I have tried fresh volume data by backing up and moving/removing the old volume data
- [Yes ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [Yes] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [Yes ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by rdwebdesign** [comment]
This is not an issue. It's just a minor warning.
It is generated by the **Bootstrap CSS** used by the web interface. This Bootstrap version uses a few "hacks" for older browsers and newer browsers show a warning, but there is nothing wrong. Newer browsers simply ignore the hacks and use the correct CSS rules.

I will close this issue because we don't fix external bugs and this is just a warning.
