### ISSUE TITLE
Port mapping ignored in podman container

### ISSUE THREAD

**Issue by IKatsu** [pi-hole/docker-pi-hole#1631]
I'm not sure if this is a podman issue or pihole issue, but after updating my server (os + phole container) pihole is refusing to start because it is trying to bind to port 53 on the host's ip.
But I am telling it to map port 2053 to port 53 on the container so it shouldn't be touching be touching the host ip.

This is a: Run Issue (running Pi-hole container failing), 

## Details

I have an unusual setup where pi-hole is running as a container on a host that is also running bind/named.
DNS requests are sent to bind which then uses a forward rule to forward to port 2053 which is what pihole should be listening on in my setup.
This worked fine until the last round of updates, after which pihole keeps trying to use port 53.
Error: netavark: IO error: Error while applying dns entries: IO error: aardvark-dns failed to start: Error from child process
Error starting server failed to bind udp listener on 10.89.0.1:53: IO error: Address already in use (os error 98)
Error: unable to start container "801a8e291be111cd6397678777c0159e3fd29a98eac8b299f46fc63617e4d5fa": netavark: IO error: Error while applying dns entries: IO error: aardvark-dns failed to start: Error from child process
Error starting server failed to bind udp listener on 10.89.0.1:53: IO error: Address already in use (os error 98)
10.89.0.1 is the host's 'podman1' interface. And this message is absolutely correct because Bind is listening on port 53 as it should be.
But the container should NOT be mapping port 53, only port 2053 to 53 on its own IP.
pihole is actually forwarding its requests back to the .1 ip on port 53.

It's a bit weird but the chain is:
Bind on port 53 -> localhost 2053 which is mapped to pihole container:53 -> back to bind on the podman ip:53 -> internet
This is due to having to hide some internal dns zones overlapping public zones and a combination of wifi/vpn reasons.
But that part actually works :)
I just don't get why it is trying to bind to port 53 on the host's IP. There is no bit of config that I can find that should make it do that, and it didn't before, but I'm not that familiar with docker/podman.

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Fedora 39
  * Hardware: PC
  * Kernel Architecture: amd64
  * Docker Install Info and version: 
    - Software source: docker.io
    - Supplimentary Software: podman 4.9.4
  * Hardware architecture: Intel x86_64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "2053:53/tcp"
      - "2053:53/udp"
      - "2080:80/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD: 'password'
      DNSMASQ_LISTENING: 'all'
    volumes:
      - './etc-pihole/:/etc/pihole:z'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d:z'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

I tried downgrading the container to 2024.06.0 as well as downgrading podman/containerd/bind packages but neither fixed the issue.
Right now I'm assuming there is some lingering bit of config somewhere that I'm not seeing but IDK what's going on as it always just worked before.

**Comment by PromoFaux** [comment]
Strange, does the same symptom appear if you use `docker` instead of `podman`?

**Comment by IKatsu** [comment]
I accidentally stumbled on the cause of the problem while troubleshooting something else.
Somehow DNS was turned back on for the podman network. I'm assuming some rpm update went through the definitions and toggled it back on.
This triggered dnsmasq to try and start even though it's disabled on the host.
This is ONLY a problem if the host is actually running a DNS server as well, so probably a niche issue.
But if anyone else runs into this, check /etc/containers/networks to see if 'dns_enabled' is set to true, it should be false if bind/named is active on the host.
