### ISSUE TITLE
DNS Service is NOT running

### ISSUE THREAD

**Issue by alexanderniebuhr** [pi-hole/docker-pi-hole#164]
Hey folks,

I installed Pi-Hole on my Debian 9x docker host machine. While everything seems to work, I get a weird error when updating lists or trying to add domains to my whitelist directly via the browser

```
:::
::: Neutrino emissions detected...
:::
::: Pulling source lists into range... done!
:::
::: Getting raw.githubusercontent.com list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: Getting sysctl.org list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: Getting zeustracker.abuse.ch list... done
:::   Status: Status 000
:::   List download failed, using cached list (list not updated!)
::: Getting s3.amazonaws.com list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: Getting s3.amazonaws.com list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: Getting hosts-file.net list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: 
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 138463 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 113829 unique domains trapped in the event horizon.
:::
::: Adding adlist sources to the whitelist... done!
::: Whitelisting 19 domains... done!
::: Nothing to blacklist!
::: No wildcards used!
::: Formatting domains into a HOSTS file...::: Nothing to blacklist!
 done!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq... done!
::: DNS service is NOT running
```

Well I don't understand why the DNS service is not working correctly?

`DNS service is NOT running`

Any Ideas ?

Cheers
Alex

**Comment by phynias** [comment]
so digging around in gravity.sh it runs pihole status.
the weird thing is if you run pihole status on the command like yourself it will work fine.

....and so i think what is happening is the dnsmasq is restarting still when it does a status. if you throw a sleep 5 right before the script calls pihole status, it works.

**Comment by diginc** [comment]
This may just be the alpine 'service' fake command not working perfectly.  I money patch the service command into the s6-overlay service system to get pi-hole script compatibility.

https://github.com/diginc/docker-pi-hole/blob/master/s6/service

The  s6-svc commands have proved tricky to get right, but this one is probably running the `status` function or `s6-svstat`

**Comment by diginc** [comment]
even when I take the -T2500 timeout out of my service script it's still not fast enough to start DNSMasq back up in time for the netstat they're running to check if port 53 is online.  race lost :(

```
bash-4.3# service dnsmasq restart  ; sleep .09 ; netstat -plnt | grep -c ':53 '
s6-svc: warning: /var/run/s6/services/dnsmasq/notification-fd not present - ignoring request for readiness notification
2
bash-4.3# service dnsmasq restart  ; sleep .09 ; netstat -plnt | grep -c ':53 '
s6-svc: warning: /var/run/s6/services/dnsmasq/notification-fd not present - ignoring request for readiness notification
2
bash-4.3# service dnsmasq restart  ; sleep .09 ; netstat -plnt | grep -c ':53 '
s6-svc: warning: /var/run/s6/services/dnsmasq/notification-fd not present - ignoring request for readiness notification
2
bash-4.3# service dnsmasq restart  ; sleep .09 ; netstat -plnt | grep -c ':53 '
s6-svc: warning: /var/run/s6/services/dnsmasq/notification-fd not present - ignoring request for readiness notification
0
bash-4.3# service dnsmasq restart  ; sleep .09 ; netstat -plnt | grep -c ':53 '
s6-svc: warning: /var/run/s6/services/dnsmasq/notification-fd not present - ignoring request for readiness notification
1
bash-4.3# service dnsmasq restart  ; sleep .09 ; netstat -plnt | grep -c ':53 '
s6-svc: warning: /var/run/s6/services/dnsmasq/notification-fd not present - ignoring request for readiness notification
2
bash-4.3# service dnsmasq restart  ; sleep .09 ; netstat -plnt | grep -c ':53 '
s6-svc: warning: /var/run/s6/services/dnsmasq/notification-fd not present - ignoring request for readiness notification
2
```

**Comment by diginc** [comment]
Throwing bug label on this but it is not really blocking any functionality as far as I could tell, just makes reading the output of pihole list modifications confusing.

**Comment by Happyfeet01** [comment]
Is there an way to get pihole working?

**Comment by diginc** [comment]
This isn't a bug that prevents functionality of docker-pi-hole, it's more of a confusing print statement that is appearing due to differences in how I constructed the docker.  

@Happyfeet01 If you are having issues running the docker be sure to follow the readme's base docker run command instructions and slowly customize it, confirming functionality along the way.  If that still does not work for you feel free to open a new issue with details about what problem you're seeing.

**Comment by Happyfeet01** [comment]
@diginc pihole running. But I can't upate the lists in docker.

```

:::   List download failed, using cached list (list not updated!)
::: Getting raw.githubusercontent.com list... done
:::   Status: Status 000
:::   Download failed and no cached list available (list will not be considered)
:::
```

**Comment by diginc** [comment]
@Happyfeet01 that sounds more in line with this issue: https://github.com/diginc/docker-pi-hole/issues/145

He ended up setting --dns in the container run command to an external DNS server to prevent pi-hole from having a circular dependency on it's own dns server.

Personally I work around this by always having a secondary DNS server on my router set to an external DNS server instead of only having pi-hole.

**Comment by shivasurya** [comment]
still same issue

**Comment by diginc** [comment]
@shivasurya please make sure your docker run matches the 4.1.1 recommendations at the top of the readme here : https://github.com/pi-hole/docker-pi-hole#docker-pi-hole-v411-important-upgrade-notes

If it still is not working for you, please open a new issue instead of replying to an old one.
