### ISSUE TITLE
Can not set timezone in Docker version

### ISSUE THREAD

**Issue by MatejKovacic** [pi-hole/docker-pi-hole#1654]
### Versions
- Pi-hole version is v5.18.3 (Latest: v5.18.3)
- web version is v5.21 (Latest: v5.21)
- FTL version is v5.25.2 (Latest: v5.25.2)

### Platform
- OS and version: Debian 12.7
- Platform: Docker

### Expected behavior

When I run `docker-compose up -d`, timezone is not set.

### Actual behavior / bug

It seems that timezone parameter is not passed to Pihole docker?

### Steps to reproduce

In `docker-compose.yml` I have:
```
    environment:
      - TZ='Europe/Ljubljana'
```
When I log in to web interface, times are still in UTC and not in my timezone.

**Comment by yubiuser** [comment]
Do you see such line in your docker log?

```
[i] Added ENV to php:"
     "TZ" => "Europe/Ljubljana",
```

**Comment by MatejKovacic** [comment]
Yes, 

```
  [i] Added ENV to php:
                    "TZ" => "Europe/Ljubljana",

```

**Comment by yubiuser** [comment]
Please switch into your running container and check if `/etc/lighttpd/conf-available/15-pihole-admin.conf` contains the correct TZ env variable.

**Comment by rdwebdesign** [comment]
Running from the host, what is the output of this command (replace `Pihole` with the name of your container)?

```
docker exec Pihole bash -c 'echo $TZ'
```

**Comment by MatejKovacic** [comment]
```
docker exec pihole bash -c 'echo $TZ'
Europe/Ljubljana

```
But when I open a new domain and check the logs are exactly two hours back.

**Comment by MatejKovacic** [comment]
Wow, just found out that Firefox shows logs with -2 hours (in UTC), but Chromium shows times correctly (in Europe/Ljubljana).

Why??

**Comment by rdwebdesign** [comment]
Note sure...

Try adding this to your compose file:
```
  volumes: 
    - /etc/timezone:/etc/timezone:ro
```

**Comment by MatejKovacic** [comment]
OK, it seems to be crappy Firefox setting: under `about:config` I have `privacy.resistFingerprinting = true`. So it is not Pihole problem...
