### ISSUE TITLE
Auto-build and push multiarch images using travis ci

### ISSUE THREAD

**Issue by diginc** [pi-hole/docker-pi-hole#177]
Since travis-ci supports multiarch's qemu requirement we can build & push the multiarch based images there for armhf & aarch64.  To start I've pushed the images manually to : https://store.docker.com/community/images/diginc/pi-hole-multiarch/tags

I'd like not not remove the current py.test travis-ci functionality/config and merge with something similar to this: https://github.com/multiarch/alpine/blob/master/.travis.yml but only for master branch...this might be a little tricky.

Also readme needs to document the new non x86 images.

**Comment by shaf** [comment]
Possible but I first want to get my head around the tests as I wanted to add new ones for DNSSEC.

**Comment by diginc** [comment]
Let me know if you need assistance or have questions about the py.test framework I've built up.  I can keep updating the TESTING.md file with more details about the tests them selves and tips and tricks for running them.  

I think I may shelve the also testing related #169 and work on this one tonight.

**Comment by shaf** [comment]
Gotcha !

- Detach the docker build process from py.test
- Matrix performs the docker builds and calls the remaining application only py.tests

You do realise this is going to be a PITA ? :)

Sounds like fun, I'll give it a shot

**Comment by diginc** [comment]
> Detach the docker build process from py.test

yes/no,   I did already separate builds from py.test in #169 because tox was trying to run tests for images that hadn't been built yet due to poor ordering of parallelized tests.

see: https://github.com/diginc/docker-pi-hole/pull/169/files#diff-f2cd4e31da43109a164e8507a5d46ab7

Another approach would be py.test keeps building the images & the matrix actually only runs py.tests for one achitecture at time.  After all we would still want to tests the images for errors before pushing them.

py.test takes in an argument to filter tests by their name (paramatarized args included):  `py.test -k debian_amd64` would only run that Dockerfile theoretically.

**Comment by shaf** [comment]
Not going to be able to do this without a fair bit of refactoring /test/*

The tests in there must be OS and ARCH aware

The general principle works here though....
https://travis-ci.org/shaf/docker-pi-hole/builds/289734892

**Comment by diginc** [comment]
I think I got the matrix working in #169 - I updated my Dockerfile.py script to take in single os+arch combos instead of building everything and used the py.test -k arg to filter tests by name (os+arch aka tag pytest fixture is in the name).

Unfortunately part of the work revealed not all tests were even running for the multiarch images.  Once I enabled the persistent test builds it showed they were failing for legitimate reasons which need addressed :(

**Comment by shaf** [comment]
Indeed,

Your travis file is very similar to mine....
However I also see the very same problems, unfortunately my python is a little too weak at the moment to take on the tests I'm afraid.

But you must agree that the tests themselves need updating. I may revisit once I've strengthen my python exposure

All the best

**Comment by diginc** [comment]
https://wiki.musl-libc.org/porting/aarch64.html sadly doesn't look possible :(

I couldn't get multiarch/crossbuild working but multiarch-debootstrap:jessie-armhf + musl-tools worked fine to build armhf-musl.  https://travis-ci.org/diginc/FTL/jobs/292975023

Opening PR for FTL....I'll refactor #169 branch to just skip alpine_aarch64 unless the armhf would work on it?

**Comment by diginc** [comment]
Just pushed the new images for 3.2 debian

**Comment by basrieter** [comment]
Great! But there is no standard ARM for RaspberryPi? Or can we use v3.2_debian_armhf for that?

**Comment by diginc** [comment]
Yup armhf compatible will run on a Pi 2 or 3.  Armv6 which the Raspberry Pi 1 did not support armhf as far as I understand.  https://en.wikipedia.org/wiki/ARM_architecture#Floating-point_(VFP)

**Comment by basrieter** [comment]
NP, I run docker on a RPi3, so will give the armhf a try.

**Comment by basrieter** [comment]
Perhaps a quick last questions: I persist my data using:

```
-v "/home/pirate/docker_data/pihole/pihole:/etc/pihole" \
-v "/home/pirate/docker_data/pihole/dnsmasq.d:/etc/dnsmasq.d" \
```

If I would upgrade to 3.2, can I then still go back to the previous version? Or should I backup this data before upgrading?

**Comment by diginc** [comment]
You could back it up ahead of time or just start a new 3.2 volume folder (`/home/pirate/docker_data/pihole/pihole3.2`) if you want to keep the old one separate for easy restore just by pointing to a new folder.  

Keep in my 3.2's docker upgrade is still under development and may have some issues.

I rolled my volume forward and most of the web UI seemed to work except for the timeline graphs, looking into that.

**Comment by basrieter** [comment]
Tried the 3.2 images but I keep getting this error on boot:

> DNS resolution is currently unavailable

**Comment by diginc** [comment]
https://github.com/diginc/docker-pi-hole/issues/196#issuecomment-350840411

> About Docker-multiarch image...what about using estesp/manifest-tool in order to ease the pulling process? just running docker pull dicing/docker-pi-hole:debian and docker pull dicing/docker-pi-hole:alpine and docker will pull the image according to the architecture, either for arm or amd64.

@klud1  I haven't looked at manifest-tool but I did look at how docker official images does their multi architecture images using manifests and it wasn't supported by automated image builds (they manually push/don't use automated docker cloud builds like I do)

I'm not quite ready to delete diginc/pi-hole automated repo and re-create it as manual, the new multiarch images need some more manual/automated testing and deployment refined.  This is why the manual non autobuild repo pi-hole-multiarch ended up getting created.  It's a test image/repo to figure out how I want to refactor the build for multiarch.

Rather than doing it how official docker images do architectures right now where it auto-detects architectures of the client I kind of like having it right in the image tag, especially since there's a blind spot in my matrix of support:

| os | amd64 | armhf | aarch64 |
| --- | --- | --- | ---|
| alpine | O | O | X |
| debian | O | O | O |

**Comment by diginc** [comment]
This is needed even more now that pihole/pihole v4 is out and the build is not automated with dockerhub builds anymore.  I think spiking on performance of alternatives like circle-ci maybe worth while before committing to fully setting up travis.

**Comment by ulm0** [comment]
Nice move, you can even use GitLab CI for this purpose

**Comment by phikai** [comment]
Not sure if this is the most relevant, but it seems to be about building/tagging images. Would it be possible to get a "latest-<platform>" tag? This way when using something like Watchtower if could automatically pull the latest release? Specifically on the ARM branches we're forced to specify a version tag which means updating docker-compose builds or otherwise each time a new version is released.

**Comment by diginc** [comment]
> Would it be possible to get a "latest-" tag? 

If anyone stumbles upon this here's the newest news: we're currently using a script to deploy that works very well for both latest, version specific, and branch tags.  It has multi-architecture support so the latest tag is now all architectures, auto detected by your docker client.

I think we'll re-visit having a CI-CD pipeline/job for image pushing another time, we don't release every time a merge happens to master.  So it is very much on-demand for master / latest, but I wouldn't mind it automatically building/pushing on a green development test build.
