### ISSUE TITLE
ubuntu 17.10 systemd-resolved stopping pihole running port 53 udp

### ISSUE THREAD

**Issue by partymike** [pi-hole/docker-pi-hole#183]
cannot run this docker due to the conflict on port 53 with systemd-resolved running, so i took these steps to disable and remove systemd-resolved:

sudo systemctl disable systemd-resolved.service
sudo service systemd-resolved stop
Put the following line in the [main] section of your /etc/NetworkManager/NetworkManager.conf:

dns=default
Delete the symlink /etc/resolv.conf

rm /etc/resolv.conf
Restart network-manager

sudo service network-manager restart
------
However once the steps above are completed you can no longer run any docker instances as it cannot find /etc/resolv.conf - even though this should no longer be needed.

As there have been major changes in networking on 17.10 is there another way to remove systemd and not break docker?

**Comment by diginc** [comment]
You may need to re-create /etc/resolv.conf or maybe even put in some values in there.  Try entering a couple nameservers into it and see if that helps, something like:

```
nameserver <Your Router>
nameserver <Internet DNS>
```

per the change in #181 there were DNS service changes in 17.10, sounds like you were following the instructions linked to from that README change.  I've never used 17.10 my self but I do know docker is kinda weird about DNS settings, I've seen in older versions than yours that it defaults to Google DNS if it cannot find any DNS settings - maybe they changed it so it just won't start rather then presuming you want google DNS.

**Comment by diginc** [comment]
Any success?

**Comment by llwu** [comment]
This is what I do on Ubuntu 17.10 server: 

As above,
```
sudo systemctl disable systemd-resolved.service
sudo service systemd-resolved stop
```

Since 17.10 doesn't use NetworkManager, I instead skip the next step, and instead edit my `/etc/resolv.conf` to look like this:

# This file is managed by man:systemd-resolved(8). Do not edit.
#
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.
# nameserver 127.0.0.53

search [redacted]
nameserver 172.17.0.5
```

where `172.17.0.5` in this case I got from `docker inspect pihole`, yours will likely be different

**Comment by diginc** [comment]
Documented in readme:

* 17.10 should disable systemd-resolved service.  See this page: [How to disable systemd-resolved in Ubuntu](https://askubuntu.com/questions/907246/how-to-disable-systemd-resolved-in-ubuntu)
