### ISSUE TITLE
DNSCrypt

### ISSUE THREAD

**Issue by jfdhuiz** [pi-hole/docker-pi-hole#185]
Would you mind adding DNSCrypt support to this build? Or is there a way I can enable it right now?

**Comment by diginc** [comment]
There was a pull request that attempted to get this into the alpine image.  I had tested enabling dnssec through the web interface after the new images built but hadn't been able to get it working.  Are you using alpine?  I don't think I have tested debian yet.

**Comment by diginc** [comment]
I tested debian last night and it seemed OK so I'd recommend using the `debian` tag for now if you require DNSSec.

#175 was the PR attempting to fix alpine's dnsmasq.  

There is some background detailed in tickets linked from that link too.  Basically dnsmasq and dnsmasq-dnssec APK for alpine conflict in a weird way but dnssec requires the original dnsmasq package for it's setup of users.  The latest alpine I built last night did not have the dnsmasq-dnssec package, just dnsmasq when I looked at the apk package list however...

**Comment by jfdhuiz** [comment]
Yep, using alpine, can switch.

We're talking different subjects here though.

I wasn't talking about DNSSEC. DNSSEC is worthless to me, YMMV.

I was talking about DNSCrypt, see https://github.com/jedisct1/dnscrypt-proxy for the software I meant (or well, an implementation). Quoting:

> DNSCrypt is a protocol for securing communications between a client and a DNS resolver, using high-speed high-security elliptic-curve cryptography.
> 
> While not providing end-to-end security, it protects the local network, which is often the weakest point of the chain, against man-in-the-middle attacks.
> 
> dnscrypt-proxy is a client-implementation of the protocol. It requires a DNSCrypt server on the other end.

If that works, you kill 2 birds with 1 stone:

1) You have secure DNS, anonymous (between client and resolver, a resolver could log/sniff) requests on an otherwise hostile network (public WiFi, LTE, etc).
2) As well as ads filtered.

All via a container which can run locally on each client. Won't work on Android I suppose, but for example a roaming laptop/netbook wouldn't require a publicly available Pi-Hole (or a VPN to a Pi-Hole). That'd be my use-case. Say I'm on vacation and I don't want to keep a computer running at home running a Pi-Hole.

**Comment by diginc** [comment]
Oh yeah my bad, I confused the two since I had the other issue on my mind.

So something like this https://github.com/pi-hole/pi-hole/wiki/DNSCrypt ?

**Comment by jfdhuiz** [comment]
👍 yep that's it!

**Comment by rix1337** [comment]
Isn't the main concept behind docker to only have one task per container?
Fear not, I have a solution, but its unneccessary to implement in pi-hole

Here is how I set it up:
-Enable VLANS for your docker host, so you can give individual IPs to your containers (easy in UNRAID)
-Get my container for DNScrypt https://hub.docker.com/r/rix1337/docker-dnscrypt/
-Set the IP of your DNScrypt container as both resolvers in Pi-Hole

If you want, you can set up multiple DNScrypt containers for various resolvers. I am proxying three different DNScrypt servers at home.

**Comment by rix1337** [comment]
DNSmasq supports appending the Port like this 192.168.1.1#53
So we would not even need VLANs at all.

Currently, this container will fail with 
```
::: Starting docker specific setup for docker diginc/pi-hole
ERROR: ServerIP Environment variable (10.10.20.40#553) doesn't appear to be a valid IPv4 address
```

@diginc is there any chance you would allow the appended # Port format in your launch script?

**Comment by jfdhuiz** [comment]
They're never running one task. How many tasks a container runs, depends on how far you zoom in or out on the stack.

Given Pi-Hole already runs a resolver anyway, and given that there are more containers who combine stacks ([url=https://github.com/haugene/docker-transmission-openvpn]example[/url]), it isn't far fetched to have it officially included.

I think there's also a way to have a container within a container (or linking it?).

A downside of your solution is that one depends on one more supplier/maintainer of a container.

You already mentioned the upside.

Its a catch-22 IMO, an argument can be made for either solution.

**Comment by rix1337** [comment]
Okay, valid point. I too am guilty of doing a great many things (overall linked) in one container..

Just so you know. The solution above works right now and dnscrypt requires more maintenance.
I still support your request (using only dnscrypt at home), but I suppose diginc might cancel this issue because of the maintenance required.

This requires a wrapper script and a cron task to update the resolver list regularly (server certs are only valid for a limited time). Should be doable..

**Comment by mil1i** [comment]
@diginc Just a quick question on DNSSec as I am not very knowledgeable on it. I was using the debian tag pihole version with DNSSec enabled using Quad9/Google1 which both support DNSSec. I ran into an issue where I found two sites that I could not access due to DNSSec. Funny enough, one was https://pi-hole.com, the other was https://antergos.com. In pihole's log, if I remember correctly it returned a "DNSSec Bogus key returned" for those sites. In chromium, it gave an error "DNS Proxy Probe detected" when trying to access those sites.

Pretty much every other query did NOT return a successful DNSSec response, but from my limited understanding that's to be expected at this time.

**Comment by PromoFaux** [comment]
> Isn't the main concept behind docker to only have one task per container?

I'm inclined to agree

>Given Pi-Hole already runs a resolver anyway, and given that there are more containers who combine stacks (example) it isn't far fetched to have it officially included.

Aware I'm necroing an old post here (just going through the backlog) but I don't see us adding in any other resolvers to the container on top of `pihole-FTL`.
