### ISSUE TITLE
Status Unknown and balcklist issue 

### ISSUE THREAD

**Issue by AlTalai** [pi-hole/docker-pi-hole#197]
hi 
i have two problem , i install pi-hole in qnap ( container) it's working fine but the status is unknown
also i have issue when i add blacklist website it's not adding it's showing refresh the page but the website is not in the list , please refer to below screenshots 
![screen shot 2017-12-12 at 10 50 18 pm](https://user-images.githubusercontent.com/34488265/33902866-d92bd108-df8f-11e7-976b-572e003de072.png)
![screen shot 2017-12-12 at 10 53 24 pm](https://user-images.githubusercontent.com/34488265/33902867-d9753500-df8f-11e7-99ac-0b8d0c4cef9d.png)
![screen shot 2017-12-12 at 10 54 19 pm](https://user-images.githubusercontent.com/34488265/33902868-d9ab6fe4-df8f-11e7-9a41-743a8b5d7194.png)

**Comment by diginc** [comment]
I believe your gravity.sh failed to run when the container first started up, it is what seeds the blacklists.

Can you look farther back up into the history of the container logs by expanding the console (2nd screenshot)?  I don't have any experience with QNAP's containerStation but if you get to a terminal the commands would just be:

`docker ps` then find the pi-hole container name/id, `docker logs <pi-hole-container-name>`

**Comment by AlTalai** [comment]
nsmasq: bad address at /etc/pihole/gravity.list line 212076                                                                                                                                     
dnsmasq: bad address at /etc/pihole/gravity.list line 212078                                                                                                                                     
dnsmasq: bad address at /etc/pihole/gravity.list line 212080                                                                                                                                     
dnsmasq: bad address at /etc/pihole/gravity.list line 212082                                                                                                                                     
dnsmasq: bad address at /etc/pihole/gravity.list line 212084                                                                                                                                     
dnsmasq: bad address at /etc/pihole/gravity.list line 212086                                                                                                                                     
dnsmasq: bad address at /etc/pihole/gravity.list line 212088                                                                                                                                     
dnsmasq: bad address at /etc/pihole/gravity.list line 212090                                                                                                                                     
dnsmasq: bad address at /etc/pihole/gravity.list line 212092                                                                                                                                     
dnsmasq: bad address at /etc/pihole/gravity.list line 212094                                                                                                                                     
dnsmasq: bad address at /etc/pihole/gravity.list line 212096                                                                                                                                     
dnsmasq: bad address at /etc/pihole/gravity.list line 212098                                                                                                                                     
dnsmasq: bad address at /etc/pihole/gravity.list line 212100                                                                                                                                     
dnsmasq: bad name at /etc/pihole/gravity.list line 212101                                                                                                                                        
dnsmasq: bad address at /etc/pihole/gravity.list line 212102                                                                                                                                     
dnsmasq: read /etc/pihole/gravity.list - 106051 addresses                                                                                                                                        
dnsmasq: query[A] apis.google.com from 10.0.3.1                                                                                                                                                  
dnsmasq: forwarded apis.google.com to 8.8.4.4                                                                                                                                                    
dnsmasq: forwarded apis.google.com to 8.8.8.8                                                                                                                                                    
dnsmasq: query[A] download.qnap.com from 10.0.3.1                                                                                                                                                
dnsmasq: forwarded download.qnap.com to 8.8.4.4        

![screen shot 2017-12-13 at 12 18 21 am](https://user-images.githubusercontent.com/34488265/33906576-c5b7965a-df9b-11e7-8ba9-65027409b119.png)
![screen shot 2017-12-13 at 12 21 17 am](https://user-images.githubusercontent.com/34488265/33906579-c64cd0e4-df9b-11e7-9882-450983e7ed49.png)
![screen shot 2017-12-13 at 12 21 21 am](https://user-images.githubusercontent.com/34488265/33906581-c689495c-df9b-11e7-8e4d-b82a9c6aa4f8.png)
![screen shot 2017-12-13 at 12 21 23 am](https://user-images.githubusercontent.com/34488265/33906582-c70a061e-df9b-11e7-9574-e247563ea89d.png)
![screen shot 2017-12-13 at 12 21 26 am](https://user-images.githubusercontent.com/34488265/33906583-c74092ba-df9b-11e7-830d-bd59e165384e.png)

**Comment by diginc** [comment]
ServerIP docker environment variable is required.  You did not set ServerIP environment variable to the IP of your QNAP according to the 3rd screenshot.

**Comment by AlTalai** [comment]
I did , refer to below screenshot , if it's not correct please guide me to the location where I will find the IPserver in Pi-hole to edit the config file 
![untitled](https://user-images.githubusercontent.com/34488265/33907261-ff8ea86c-df9d-11e7-8434-d4d7275c26e0.jpg)

**Comment by diginc** [comment]
When you first create the container is the only time to pass in docker env vars.  Make sure the container is create with [ServerIP env var per my readme](https://github.com/diginc/docker-pi-hole#environment-variables) - not to be confused with the pi-hole setupVars you showed in your screenshot.

  My bet is you use the 'advanced' menu as shown [here](https://www.qnap.com/images/products/Application/notes/ContainerStation_en_10.png) (from [this tutorial](https://www.qnap.com/en/how-to/tutorial/article/how-to-use-container-station))

**Comment by Symbiot78** [comment]
I'm seeing the same issue with blacklist empty in GUI (though the blacklist text file is updated)
also no version etc.
Pi-hole Version N/A Web Interface Version N/A FTL Version N/A

**Comment by Symbiot78** [comment]
Did a complete repull etc. and made sure all variables were set before starting container but same issue.
Empty blacklist, no version etc.

**Comment by ShawnMcGough** [comment]
I'm also seeing this issue but only when launching the container on host network. 
![image](https://user-images.githubusercontent.com/64036/42396366-5d92d22a-812f-11e8-98c1-75230e4c561d.png)

When I run the container on the bridge network, I get a green status and correct version info. However, then all the client IPs are wrong (only the container IP) as documented here: #135 

I settled on launching the container on the host network and ignoring the 'unkown' status and missing version numbers.

**Comment by Azzhoe** [comment]
Same here on Synology NAS running DSM 6.2. Status is unknown but it still seems to be working, I see queries being blocked. Also doesn't show the version at the bottom right.

Any ideas why it's showing status as unknown? Like others, this only happens when i check 'Use the same network as Docker Host'

**Comment by filusATpsc** [comment]
Know this is closed, but I was having the same issues - staus "Unknown" and unable to add blacklists, though different circumstances - installing pi-hole on an already configured CentOS host, running apache.

The problem was the sudoers entry required by pihole was not being applied(and incorrect; "apache" vs "lighttpd"). Saw errors in '/var/log/secure'. Presumably for Debian/Ubuntu they would be in '/var/log/auth'

Again, our situation was very specific, but it's something easy to check. Would have saved a few hours of debugging, hoping it might help someone else.

**Comment by MichaelJahn2** [comment]
@filusATpsc : Really would like to thank you for this. I also run pi-hole with apache, had the orange status unknown issue. Your comment saved me a lot of work!
