### ISSUE TITLE
No Save Settings | No Files 

### ISSUE THREAD

**Issue by wuast94** [pi-hole/docker-pi-hole#198]
I followed the Instructions and its starts. but when i make changes in settings they dont save and i don´t see files in the pihole folder, cant update list and so on

**Comment by DomResc** [comment]
Same problem, Have you managed to solve it?

**Comment by diginc** [comment]
With the new version out I'll see if I can reproduce the issue

**Comment by josco95** [comment]
Just updated to the new version myself, still isn't saving changes if I map out static configuration locations. It writes the files (I wiped out everything in the directory before updating), just doesn't seem to honor them.

**Comment by josco95** [comment]
This continues to be an issue for me (and probably others). How can I help test? What information can I provide?

**Comment by gaijininjapan** [comment]
I'm having the same issue.  Worked fine until 3.3.  Scrubbing out the pihole folder used for storing changes, no go as well.

**Comment by PromoFaux** [comment]
Closed in place of the pinned #720
