### ISSUE TITLE
How to update dnsmasq

### ISSUE THREAD

**Issue by halkeye** [pi-hole/docker-pi-hole#223]
The version in stable/stretch still has one outstanding dnssec bug that prevents some domains from resolving properly due to a dnssec bug (ex mirrors.fedoraproject.org) so I wanted to use the testing version.

https://github.com/halkeye/docker-pi-hole/blob/master/Dockerfile

```
RUN echo 'APT::Default-Release "stretch";' > /etc/apt/apt.conf.d/99defaultrelease \
      && echo 'Dpkg::Options { "--force-confdef"; "--force-confold"; };' > /etc/apt/apt.conf.d/50unattended-upgrades \
      && cat /etc/apt/sources.list | perl -p -e 's/stretch|stable/testing/' > /etc/apt/sources.list.d/testing.list \
      && apt-get update -y \
      && apt-get dist-upgrade -y \
      && apt-get install -y -t testing dnsmasq \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*
```

Is what I ended up doing.

Not really an issue, but felt it was worth sharing

**Comment by diginc** [comment]
Maybe worth putting in an /install.sh script enabled by a Dockerfile ARG.
