### ISSUE TITLE
Using pihole via VPN

### ISSUE THREAD

**Issue by matrss** [pi-hole/docker-pi-hole#226]
Hey there!
First of all, thanks for the great Project!
About my problem: I have set up this docker image on my local server at home, using port mapping to forward 53 to the pihole container, and it's working as expected for all local devices. I also have an openvpn server running in docker on the same host, pushing the docker hosts ip as DNS; now if I connect to said vpn I can reach my docker host machine by pinging it's ip, but something like `host google.de <docker host ip>` results in `;; connection timed out; no servers could be reached`, and in general nameresolution doesn't work at all.
For standard pihole installations I've read that you have to allow DNS requests from the "tun0" interface for this to work, but that's seems not to be applicable here as the container doesn't have that interface.

So what could I do to make pihole work in the given use case?

Thanks in advance, and I'm sorry if this isn't the correct place to ask such questions.

**Comment by tonyklawrence** [comment]
You might want to take a look at the DNSMASQ_LISTENING environment variable so that pi-hole will listen to other network requests?

**Comment by Risebell** [comment]
Thanks for the suggestion, it seems like that could be the problem. I will test that as soon as possible.
Also, I found out that if I use the ip of the docker0 bridge on the host instead of it's LAN ip it actually works; I just don't like that solution as I would have different DNS server ip's for client's on the lan vs client's via vpn.

**Comment by diginc** [comment]
Has this been resolved?

Adding a OpenVPN + pihole docker-compose example has been on my backlog for quite some time but I've had a tough time picking an OpenVPN image to test.  There are many options with varying degrees of setup and customization.  Any suggestions?

**Comment by chrisob** [comment]
@diginc I've had luck with [kylemanna's image](https://github.com/kylemanna/docker-openvpn).  The image itself also contains a few scripts that make PKI management and client/server config pretty easy.  

Here's an example docker-compose service (note that `192.168.2.13` is the docker host on which my `pihole` container is running, but I haven't got it working 100% yet!):
```
  openvpn:
    # To generate OpenVPN config:
    #   docker-compose run --rm openvpn ovpn_genconfig -u udp://vpn.example.com:1194 -n 192.168.2.13 -n 192.168.2.1 -s 10.10.100.0/24 -C 'AES-256-CBC' -a 'SHA384' -z
    container_name: openvpn
    image: kylemanna/openvpn
    ports:
     - "1194:1194/udp"
    volumes:
      - openvpn-config:/etc/openvpn
    environment:
        EASYRSA_KEY_SIZE: 4096
    cap_add:
     - NET_ADMIN
```

**Comment by mr-bolle** [comment]
Hi, since some month i use follow solution.
https://github.com/mr-bolle/docker-compose/tree/dev/openvpn-pihole

Each time you start the computer / Docker update, the IP of the Pihole container changes, so OpenVPN must pass the IP as a DNS server. I would be grateful for a better solution.

**Comment by diginc** [comment]
@mr-bolle I'd recommend adding a static IP to your container.  Here is the docker-compose syntax for that

https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address

**Comment by MacFlurry** [comment]
Hello,

Could someone provide whatever docker compose etc for setting up pi-hole + openvpn ?

Thanks for your help 😊

**Comment by mr-bolle** [comment]
I try this solution from dignic, however it didn't work. I adjust a easy script, to create this OpenVPN certificate with the first client, this i will share soon as well.

**Comment by mr-bolle** [comment]
@MacFlurry now i update the documentation and add some scripts to create the OpenVPN Certificate and additional Clients. 

https://github.com/mr-bolle/docker-compose/tree/master/openvpn-pihole

**Comment by diginc** [comment]
>     since Pi-hole v4.1.1 i get follow error message, thats why i use the v4.1 from Pi-hole
> 
> vpn_pihole | kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
> vpn_pihole | Starting pihole-FTL (no-daemon)

Looks like you're missing the newly required arguments: https://github.com/pi-hole/docker-pi-hole#docker-pi-hole-v411-important-upgrade-notes

See if adding those helps.

**Comment by MacFlurry** [comment]
@mr-bolle thanks a lot !!! @diginc thanks a lot too :-)
guys saved me from doing it myself. thank you

**Comment by mr-bolle** [comment]
@diginc thank you for this information, tomorrow i will fix it.

Many thanks for your great support - i have to place a donation for you again

**Comment by MacFlurry** [comment]
yeah pi-hole deserve a donation.

**Comment by MacFlurry** [comment]
@mr-bolle let us know when the update will be available :-) thanks a lot

**Comment by mr-bolle** [comment]
@diginc Hi Adam, now i try with your Suggestion, and follow Change helps. And the donation was made, hopefully more User support your work as well.

@MacFlurry now you can clone the docker-compose again, follow changes fix the issue with the pi-hole v.4.1.1 https://github.com/mr-bolle/docker-compose/commit/adc63d8d626619f5d3e12558e65131c1b1219232
```
   pihole:
     cap_add:
       - NET_ADMIN
     environment:
       - DNS1=127.0.0.1     # necessarry 
       - DNS2=1.1.1.1         # custom change possible
```

**Comment by MacFlurry** [comment]
Thanks a lot dude! 🥰

**Comment by mr-bolle** [comment]
Hi, now i create a new repository for this implementation. https://github.com/mr-bolle/docker-openvpn-pihole and i made the first improvements with the script. You can add new ideas and help to fix this, over this issue https://github.com/mr-bolle/docker-openvpn-pihole/issues/1
