### ISSUE TITLE
[Issue] dnsmasq.d won't start

### ISSUE THREAD

**Issue by FireHelmet** [pi-hole/docker-pi-hole#232]
Hello,

I'm using a docker container with the tag diginc/pi-hole-multiarch:debian_aarch64 and dnsmasq.d cannot start :

> Using
> IPv4 and IPv6
> ::: Testing DNSmasq config:   [✗] DNS service is not running

The error log says :

>dnsmasq: bad option at line 1 of /etc/dnsmasq.d/setupVars.conf

In addition a lot of files are in /etc/dnsmasq.d like : localbranches, pihole-FTL.db, GitHubVersions

![image](https://user-images.githubusercontent.com/17533298/36490068-bdf9375c-1727-11e8-9835-a71fa11dd090.png)

but on a classic pi-hole installation only 01-pihole.conf reside in this location and when I clean all other file, dnsmasq.d start correctly.

Thanks for your support !

**Comment by diginc** [comment]
Hello, Here are what the stock folders look like.

```
root@6ccf4c1c4917:/# ls /etc/pihole/
GitHubVersions  gravity.list                              list.1.mirror1.malwaredomains.com.domains  list.3.zeustracker.abuse.ch.domains  list.5.s3.amazonaws.com.domains  list.preEventHorizon  localbranches  logrotate      setupVars.conf
adlists.list    list.0.raw.githubusercontent.com.domains  list.2.sysctl.org.domains                  list.4.s3.amazonaws.com.domains      list.6.hosts-file.net.domains    local.list            localversions  pihole-FTL.db  whitelist.txt
root@6ccf4c1c4917:/# ls /etc/dnsmasq.d/
01-pihole.conf  README
```

At first glance it looks kind of like the pihole and dnsmasq.d folders got crossed for your container/volumes somehow.
