### ISSUE TITLE
Implement ARMEL based debian image for ARMv6 support

### ISSUE THREAD

**Issue by diginc** [pi-hole/docker-pi-hole#245]
#218 reminded me of an old comment action item: to look at the effort needed to build on top of the multiarch/debian-debootstrap:armel tag for Armv4-Armv6 support.

S6/Tini init systems only shipped ARMHF/ARMV7 Support at the time I wrote the comment and that is possibly still true.  I could try to compile them my self as a work around perhaps.

**Comment by Kevin-De-Koninck** [comment]
I've built the image with the armel tag (https://github.com/diginc/docker-pi-hole/issues/242#issuecomment-374387114) and this seems to work. So the effort needed to build on top of this would be minimal (I think) and then this could be automated to?

Could be wrong, the docker world is new to me.

**Comment by mrksr** [comment]
I followed the instructions of @Kevin-De-Koninck and indeed, things just seem to work by using the `s6-overlay-armhf`-release on `armel`. I just copied `Dockerfile_debian_armhf` and applied the following changes:

```diff
--- Dockerfile_debian_armhf     2018-04-24 18:00:27.483696059 +0200
+++ Dockerfile_debian_armel     2018-04-24 18:03:16.432843843 +0200
@@ -1,11 +1,11 @@
-FROM multiarch/debian-debootstrap:armhf-stretch-slim
+FROM multiarch/debian-debootstrap:armel-stretch-slim

-LABEL image="diginc/pi-hole:debian_armhf"
+LABEL image="diginc/pi-hole:debian_armel"
 LABEL maintainer="adam@diginc.us"
 LABEL url="https://www.github.com/diginc/docker-pi-hole"

 ENV TAG debian
-ENV ARCH armhf
+ENV ARCH armel
 ENV PATH /opt/pihole:${PATH}

 COPY install.sh /usr/local/bin/docker-install.sh
```

**Comment by diginc** [comment]
I was excited to get an armel image out and working for v4 but it did not happen due to more technical roadbumps.  Here is what I learned during the Pi-hole v4 release.  

The new v4.0 FTL doesn't seem to work within docker armel based images since it is very much an armfh binary.  This is working as intended, native Pi-hole installs support said armhf binary. turns out armhf binaries will run on the older RBPi CPU, hard floats do work on the host system of an Armv6 Pi.  This surprised me, I tried it my self and it worked.

We've got a bit of a catch 22 here.  Pi-hole built the new FTL binary for armhf because RBPi1 works fine with that, but docker on RBPi1 only seems to want to run armel based images where the libraries won't support the armhf binary.

**Comment by mrksr** [comment]
Thank you for exploring the issue! I do not quite understand the technical problem. If I understand you correctly, the new Pi-hole will run on my RPi0 if installed natively. What are the issues when doing the same install in a Docker image? I would be glad to help if it is an issue of debugging and writing some code.

**Comment by gauravk88** [comment]
@diginc I checked pi-hole/FTL that indeed they are not providing armel docker files in the source repo.

I believe we can try building the FTL for armel by making relevant changes to this file :

https://github.com/pi-hole/FTL/blob/master/docker/armhf/Dockerfile

"
FROM debian:stretch

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -y --no-install-recommends nettle-dev:armhf gcc-arm-linux-gnueabihf libc6-dev-armhf-cross \
        make file wget netcat-traditional sqlite3 git ca-certificates ssh

ENV CC arm-linux-gnueabihf-gcc

"

What do you suggest?

**Comment by diginc** [comment]
> What are the issues when doing the same install in a Docker image?

The [gnueabi FTL binary](https://github.com/pi-hole/FTL/releases), which is used and works for the native Pi-hole RPi0/1 installs, simply won't run in any docker image running on the same platform when I tested it.  gnueabi is technically HF enabled, not armel.

Armel images seem to be the only docker images that will run on RPi0/1, this originally gave me a false impression the host machine was technically armel too, but it's better described as armv6HF I guess?  If you try to run an ARMHF image on RPi0/1 it will simply hang and return nothing.  Maybe docker compiles armhf images for armv7HF and not armv6hf?  Or maybe there's some other docker bug at play here.

**Comment by diginc** [comment]
https://github.com/pi-hole/FTL/issues/364 related

**Comment by DXPetti** [comment]
Lucky you haven't purged your old v3 images!

Seems that this issue comes down to two big factors; [Docker pulling (or wanting to pull) armel images due to manifest list issues](https://github.com/moby/moby/issues/34875) and [Pi v1 and Zero giving out mixed architecture signals](https://github.com/moby/moby/pull/36121#issuecomment-398328286)

**Comment by Alwaysin** [comment]
Any progress on this? Would love to use the docker image onmy RPi!

**Comment by JM1** [comment]
Pihole's latest docker image (image id `5e1627da5525`) does not work with my Raspberry Pi 1 Model B+:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
[cont-init.d] 20-start.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by PromoFaux** [comment]
D'oh - there was me hoping it would be as simple as adding `linux/arm/v6` to the platform section of the docker build command.

OK, Would you mind doing some additional troubleshooting? I don't currently have access to an ARMv6 device. Can you set the environment variable `PH_VERBOSE` to `1` and then attempt to run the image again? Hopefully that will give us some more helpful output to work with... :)

**Comment by JM1** [comment]
The output is always the same as shown above. I tested it with this [`docker-compose.yml`](https://github.com/JM1/shelp/blob/master/rpi_pi-hole_docker_setup.md) as well as different variations of:

```
docker run --rm -ti  --cap-add NET_ADMIN     -e PH_VERBOSE=1 -e ServerIP=10.10.0.2 --network=host --name pihole pihole/pihole
```

**Comment by PromoFaux** [comment]
the `PH_VERBOSE=1` should give a lot more output than that, [it basically runs the commands with `bash +x`](https://github.com/pi-hole/docker-pi-hole/blob/master/s6/debian-root/etc/cont-init.d/20-start.sh#L5)

So I'd expect to see something like this: 
![image](https://user-images.githubusercontent.com/1998970/140765190-4643c54a-ee35-4d1e-9461-16cde2231fe9.png)

**Comment by JM1** [comment]
Docker on the latest Raspberry Pi OS pulls the wrong architecture image for `debian:buster` and `pihole/pihole:latest` because of [Docker issue 37647](https://github.com/moby/moby/issues/37647). This issue was fixed in Docker `v20.10`, but the latest Raspberry Pi OS image is based on `Debian 10 (Buster)` and has Docker `v18.09` only.

Pulling a different arch of Debian's docker image works:

```
docker run -ti --entrypoint="" arm32v5/debian:buster /bin/sh
```

Pulling the linux/arm/v6 image of Pihole explicitly will run `/bin/sh` in Docker without a crash:

```
docker run --rm -ti --entrypoint="" pihole/pihole@sha256:03d2f032602594fc813c64d3aea59b37a1385da91c660d7954f818dd9effeb7f /bin/sh
```

Unfortunately, my SD card died a couple of minutes ago :grimacing: I will have to find another one before I can continue debugging..

**Comment by PromoFaux** [comment]
> but the latest Raspberry Pi OS image is based on Debian 10 (Buster)

Until today, that is 😏

https://www.raspberrypi.com/news/raspberry-pi-os-debian-bullseye/

**Comment by PromoFaux** [comment]
On my Pi4 
![image](https://user-images.githubusercontent.com/1998970/140779795-d44898f1-9ed0-4fff-ac08-3035ad72d8c3.png)

**Comment by JM1** [comment]
24 hours earlier and.. :expressionless: For completeness and out of curiosity I installed Docker Pihole on the Buster-based RPi OS image. Using the linux/arm/v6 image `pihole/pihole@sha256:03d2f032602594fc813c64d3aea59b37a1385da91c660d7954f818dd9effeb7f` explicitly it works. So the crash was really because the wrong image was being pulled ([Docker issue 37647](https://github.com/moby/moby/issues/37647)). Pihole's Docker image itself is fine :+1: 

PS: Will do tests with Bullseye-based RPi OS image on RPi 1 B+ later..

**Comment by PromoFaux** [comment]
> Pihole's Docker image itself is fine 👍

This is both welcoming and a little surprising, (if only because all we did for armv6 compatibility in the end was change the base image and tell it we wanted armv6 to be built ¯\_(ツ)_/¯)

**Comment by JM1** [comment]
Docker Pi-hole does not work on Bullseye-based RPi OS image because `containerd` on Bullseye is `1.4.5~ds1` which does not ship the patch mentioned in [Docker issue 37647](https://github.com/moby/moby/issues/37647), i.e. [`platforms/cpuinfo.go` on Bullseye](https://salsa.debian.org/go-team/packages/containerd/-/blob/debian/bullseye/platforms/cpuinfo.go) is missing [this patch](https://github.com/containerd/containerd/pull/4530/files). Because of this, Docker on Bullseye still pulls the wrong arch image of Pi-hole.

**Comment by PromoFaux** [comment]
But I guess it works if you pull explicitly like you did with `buster`?

If so, it seems like it works - but with extra steps. If that is the case - we may be able to document the extra steps and stick them in the README of this repo

**Comment by JM1** [comment]
An easy way to install an updated Docker is using [Docker's convenience script `get-docker.sh`](https://docs.docker.com/engine/install/debian/). Mimicking containerd's patch, one could conditionally install the updated Docker packages from Docker Inc. like this:

```
if [ "$(cut -d. -f1 /etc/debian_version)" -le 11 ] && \
   [ "$(awk '/model name/{ print(tolower($4)) }' /proc/cpuinfo)" = "armv6-compatible" ]; then
    # install Docker from Docker's repositories
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
else
    # install Docker from Raspberry Pi OS repositories
    apt-get install -y docker.io
fi
```

This works with the latest Raspberry Pi OS image and Docker Pi-hole on my RPi 1 B+. Strangely, `ctr plugins ls` still lists platform `linux/arm/v7` but it definitely uses the `linux/arm/v6` image.

Alternatively, one could use docker's `--platform` parameter (only on Bullseye):

```
docker run --platform linux/arm/v6 [...] pihole/pihole:latest
```

But this parameter is not supported by Docker Compose v3 spec.

Pulling an ARMv6 image with its sha256 digest also works on bullseye.

**Comment by JM1** [comment]
I have opened [bug report 998909](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=998909) in Debian. Maybe the Debian maintainers have time to backport the [containerd patch](https://github.com/containerd/containerd/commit/2055e12953bb538228d8d9fe627fa545d7cf82be) to Debian 11 (Bullseye). Then it would not take years before this is fixed in Raspberry Pi OS :see_no_evil:

**Comment by DXPetti** [comment]
Can confirm on my RPi 1 A+ running the latest Raspberry Pi OS and latest Docker version that pulling the image directly with SHA256 digest works correctly.

```
pi@galm:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

pi@galm:~ $ sudo docker version
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:33 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:40:50 2021
  OS/Arch:          linux/arm
  Experimental:     true
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

The pihole container up and running for good measure:

`Every 2.0s: sudo docker ps                                                           galm: Wed Nov 10 18:22:45 2021
CONTAINER ID   IMAGE           COMMAND      CREATED          STATUS                    PORTS
                                                                                      NAMES
9d98a0030775   pihole/pihole   "/s6-init"   14 minutes ago   Up 14 minutes (healthy)   0.0.0.0:53->53/tcp, :::53->53/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:53->53/udp, :::80->80/tcp, :::53->53/udp, 67/udp   pihole`

This is absolutely **excellent** team. Pretty much gave up on the older RaspberryPi's being able to run the latest Pi-Hole in a container but here we are :)

**Comment by JM1** [comment]
Shengjing Zhu has backported the [containerd patch to Debian 11 (Bullseye), uploaded a fixed package to proposed-updates and closed bug report 998909](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=998909) :smile:

**Comment by PromoFaux** [comment]
Excellent news - I'm a bit green with all this stuff - presumably we won't need to do anything to the image on this end?

**Comment by JM1** [comment]
[Raspbian's buildd has not yet picked up the fixed containerd package](https://buildd.raspbian.org/status/logs.php?pkg=containerd)). Skimming through their Github repos I could not find any info about Raspbian's packaging policy or buildd code, but i guess they take stable packages only (not [proposed-updates](https://www.debian.org/releases/proposed-updates.html)). Let's just wait till containerd lands in stable

**Comment by JM1** [comment]
[`containerd 1.4.12~ds1-1~deb11u1`](https://buildd.raspbian.org/status/logs.php?pkg=containerd&ver=1.4.12%7Eds1-1%7Edeb11u1&suite=bullseye-staging) is now available in Raspbian Bullseye. `ctr` correctly identifies my RPi 1 as `linux/arm/v6` (previously it was `linux/arm/v7`):

```
$ ctr plugins ls
TYPE                            ID                       PLATFORMS       STATUS
...
io.containerd.runtime.v1        linux                    linux/arm/v6    ok        
io.containerd.runtime.v2        task                     linux/arm/v6    ok        
io.containerd.monitor.v1        cgroups                  linux/arm/v6    ok        
```

Docker Pi-hole now works out-of-the-box on Raspberry Pi 0/1 🤩

Finally we can close this issue ^^
