### ISSUE TITLE
No reverse for Top clients in web interface

### ISSUE THREAD

**Issue by mathieulegrand** [pi-hole/docker-pi-hole#251]
-- following the template:
This is a Request for a new or modified feature.

## Description
The top client list in the web interface does not show the hostname, it only shows the IP address.

## Expected Behavior
A reverse lookup on the IP addresses is performed, but fails. I would expect the reverse lookup to get a correct result, therefore enabling the web interface to display hostnames instead of local IP addresses.

## Possible Fix
I reckon that the reserve lookup is done with the DNS server of the docker image. Currently this DNS server is set by the environment variables `DNS1` and `DNS2` that are used both to configure the upstream server for `dnsmasq`, and the content of `/etc/resolv.conf`. I would rather have `dnsmasq` itself to be the resolver inside the docker container (hence 127.0.0.1 should be in `/etc/resolv.conf`). However, we would need a way to set it that does not at the same time set the upstream resolver for `dnsmasq`…

## Steps to Reproduce and debugging done
1. `docker run -d […] -e DNS1="1.1.1.1" -e DNS2="1.0.0.1" […] diginc/pi-hole-multiarch:debian_aarch64`
2. open the web interface
3. log in and look at the top clients list
4. I would expect to see the names set in `addn-hosts=/etc/pihole/lan.list` via `dnsmasq.d/02-lan.conf`

## Debug steps I have tried
- [Yes] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [Yes] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [Yes] I have tried running without my volume data mounts to eliminate volumes as the cause
- [Yes] I have searched this repository for existing issues and pull requests that look similar

## Your Environment 
* Docker Host Operating System and OS Version: Debian ARMBIAN 9.4
* Docker Version: docker client/server version 18.03.0-ce
* Hardware architecture: aarch64

**Comment by diginc** [comment]
> Currently this DNS server is set by the environment variables DNS1 and DNS2 that are used both to configure the upstream server for dnsmasq, and the content of /etc/resolv.conf. I would rather have dnsmasq itself to be the resolver inside the docker container (hence 127.0.0.1 should be in /etc/resolv.conf). However, we would need a way to set it that does not at the same time set the upstream resolver for dnsmasq…

Sorry for taking so long to respond with such a simple answer.  I believe if you start your container with --dns 127.0.0.1 (docker throws a warning, ignore it) you can get exactly what you described there.

**Comment by diginc** [comment]
The --dns recommendation is now documented in the readme.
