### ISSUE TITLE
container update overriding existing upstream DNS setting

### ISSUE THREAD

**Issue by restfuladi** [pi-hole/docker-pi-hole#259]
I run my own upstream DNS server which supports encryption. If I deploy a new container (after new pull) with one (or none) upstream DNS server variables, the previous custom upstream setting gets changed to Google. Right now I have to enter a bogus IP for the second server to avoid this behavior. The config files are on a persistent volume. 

Seems like setupVars.conf gets edited to say the following even if I delete the lines:

PIHOLE_DNS_1=8.8.8.8
PIHOLE_DNS_2=8.8.4.4

Forwarding to Unbound or Stubby for TLS upstream is a popular use case and it would be nice to set one custom server in 01-pihole.conf or 02-custom-settings.conf and not worry about leaks if the container gets updated.

**Comment by diginc** [comment]
What does your `docker run` command look like? 

Are you setting DNS1 and DNS2 environment variables and re-creating your entire container?

PIHOLE_DNS_1 and 2 are set from DNS1/DNS2 on first boot only, to handle preservation of web UI modified settings when a container restarts.

```
 def test_override_default_servers_with_DNS_EnvVars(Docker, args, expected_stdout, dns1, dns2):
    ''' on first boot when DNS vars are NOT set explain default google DNS settings are used
                   or when DNS vars are set override the pihole DNS settings '''

 def test_DNS_Envs_are_secondary_to_setupvars(Docker, args, expected_stdout, dns1, dns2):
    ''' on second boot when DNS vars are set just use pihole DNS settings
                    or when DNS vars and FORCE_DNS var are set override the pihole DNS settings '''
```

Actual implementation is here: 
https://github.com/diginc/docker-pi-hole/blob/master/bash_functions.sh#L41-L68

**Comment by restfuladi** [comment]
```
docker run -d \
    --name pihole \
    --net=br0 \ # macvlan network
    --ip=xxx.xxx.xxx \ # static IP for container
    -v "local-path/pihole/:/etc/pihole/" \
    -v "local-path/dnsmasq.d/:/etc/dnsmasq.d/" \
    -e ServerIP=xxx.xxx.xxx.xxx
    -e TZ=America/New_York \
    --restart=unless-stopped \
    diginc/pi-hole:latest
```

**Comment by diginc** [comment]
> never force a DNS2 default.

Having redundant DNS is a good practice.  

The DNS settings are printed during startup.

**Comment by diginc** [comment]
I would suggest just setting DNS2 to the same as DNS1 in your case where you only have one upstream server.  I think that would have the least risk of causing any issues with DNSMasq functionality.  A bad hostname or IP address may cause errors or delays in querying.

I'm open to allowing a forced empty DNS2 value (which wouldn't break dnsmasq) to disable 2 servers, but I don't like it as a default.  The majority of people would probably be using 2 external servers since that is what the pihole web UI configuration page supports.

**Comment by restfuladi** [comment]
I tried using identical DSN1 and DNS2, dnsmasq freaks out. A forced empty DNS2 would be perfect. Thanks!

What would really be awesome is embedding proxy that supports encryption and applying the dual external servers there :)

**Comment by diginc** [comment]
Hmm really?  I thought the code prevented null values for DNS# and when I tried giberish it broke dnsmasq.  e.g. `-e DNS2=''` I still got google's secondary: `Using custom DNS servers: 1.1.1.1 & 8.8.4.4`

But setting it to the same server twice worked.

```
Using custom DNS servers: 1.1.1.1 & 1.1.1.1
...
dnsmasq: using nameserver 1.1.1.1#53
dnsmasq: using nameserver 1.1.1.1#53
```

**Comment by restfuladi** [comment]
Nevermind. I was pretty sure I remembered getting a dnsmasq error when doing this... must have been something else. Looks like it's working.

**Comment by diginc** [comment]
I believe a fix was added for both issues: not allowing ENVs to overwrite the SetupVars DNS and DNS2 can now be set to 'no'
