### ISSUE TITLE
Container becomes unkillable

### ISSUE THREAD

**Issue by JustinAiken** [pi-hole/docker-pi-hole#265]
After running pihole for a few days with nothing hitting it (0 DNS requests), the container became unkillable:

This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

```bash
root@Tower:~# docker ps
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS                PORTS               NAMES
62518c9bb052        diginc/pi-hole:latest   "/s6-init"          6 days ago          Up 4 days (healthy)                       pihole

root@Tower:~# docker stop pihole
# Hangs for a few minutes.  Eventually ctrl-c out

root@Tower:~# docker kill pihole
# Hangs forever
```

## Expected Behavior
It should stop.  Or at least be killable.

## Actual Behavior
- Once, was able to rescue everything by `kill -9`ing the processes manually, then killing the docker engine
- Once, had to hard reboot server

## Steps to Reproduce and debugging done
1. Have an unraid machine
2. Start pihole
3. ???
4.  Fail to profit

## Your Environment 

* Docker Host Operating System and OS Version: unRaid 6.5.0
* Docker Version: 12.12
* Hardware architecture: Intel x86

**Comment by diginc** [comment]
what about `docker rm -f pihole` ?

Do your system logs have any docker errors?

**Comment by JustinAiken** [comment]
> docker rm -f pihole

I'd tried that too, it just hung kill `docker kill pihole` did

> Do your system logs have any docker errors?

Not sure, I've since rebooted.

I started the container again, will let run for 24 hours then trying stopping again to see if it happens, and grab the docker log

**Comment by diginc** [comment]
The other open issue that just got resolved was because of a temporarily released bug to the pi-hole:latest image

I don't think I mentioned yet : make sure you've pulled the latest image with the fix to that bug.

```
$ docker image ls diginc/pi-hole:latest
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
diginc/pi-hole      latest              eb902c685095        9 days ago          367MB
$ docker pull diginc/pi-hole:latest
latest: Pulling from diginc/pi-hole
Digest: sha256:50479369dcff346cb3f8aef12557ec8ebaf787882eeb7c0f44c98d7bcac39a52
Status: Image is up to date for diginc/pi-hole:latest
```

**Comment by JustinAiken** [comment]
- Alright, on the latest (was before when error happened)
- Been running 24 hours without incident; was able to stop and restart
- Now using for DNS; will run over the weekend, then attempt to stop it and update accordingly
