### ISSUE TITLE
Startup script doesn't grab IP addresses correctly

### ISSUE THREAD

**Issue by mmcc-xx** [pi-hole/docker-pi-hole#273]
This is a... 

- [ ] Request for a new or modified feature
- [X ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
The startup script found here: https://github.com/diginc/docker-pi-hole/blob/master/docker_run.sh
doesn't seem to be able to grab IP addresses correctly

## Expected Behavior
Script determines correct current IPv4 and IPv6 addresses

## Actual Behavior
When I execute the following command
    echo "${IP:-$(ip route get 8.8.8.8 | awk '{ print $NF; exit }')}"
the returned value is "1000"

When I execute the following command from the script
   echo  "${IPv6:-$(ip -6 route get 2001:4860:4860::8888 | awk '{ print $10; exit }')}"
the returned value is "src"

## Possible Fix
I'm using Ubuntu Bionic - perhaps the return format of the route command changed

## Steps to Reproduce and debugging done
1. echo "${IP:-$(ip route get 8.8.8.8 | awk '{ print $NF; exit }')}"
2. echo  "${IPv6:-$(ip -6 route get 2001:4860:4860::8888 | awk '{ print $10; exit }')}"
3. 
4. 

## Debug steps I have tried

- [X] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [X] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Ubuntu Bionic
* Docker Version: 18.05.0-ce
* Hardware architecture: amd64

**Comment by eku** [comment]
Well, output of ```iproute``` depends on system and version.

**Comment by diginc** [comment]
When the auto lookup fails please just delete the whole first 4 IP lines and type in your IP to the variables like so:

```
IP="MyIP"
IPv6="MyIPv6"
```

The Lookup of IPs is a convenience thing for the majority of users.  Like eku said it varies by platform.  To make it 100% we'd need to know all the various platforms/network variants' outputs for the route get command.
