### ISSUE TITLE
Website taking too long to load

### ISSUE THREAD

**Issue by next2non** [pi-hole/docker-pi-hole#277]
Managed to run pi-hole on my synology and all works fine except when I visit 9to5mac.com it takes ages to load. Other websites are fine. Running the same setup on RPi3 and the same website loads fine. Any advice?

**Comment by nxadm** [comment]
It's probably related to scripts running on SSL. Have a look in the remark about it on the [Readme file](https://github.com/diginc/docker-pi-hole/blob/master/README.md)

> docker run -d \
>     --name pihole \
>     -p 53:53/tcp -p 53:53/udp -p 80:80 **-p 443:443** \
>     -v "${DOCKER_CONFIGS}/pihole/:/etc/pihole/" \
>     -v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/" \
>     -e ServerIP="${IP}" \
>     -e ServerIPv6="${IPv6}" \
>     --restart=unless-stopped \
>     diginc/pi-hole:latest
> 
> Scripts that try to reach a blocked domain on port 443 will timeout because the domain is redirected to the docker host, while no service listens on port 443. Pages on the client will load very slowly on sites doing this type of connection. Adding the port 443 forwarding to the container run results in a inmediate REJECT: the page will continue loading inmediately instead of waiting for the resource. An alternative is instead of binding port 443 is blocking it by the firewall of the docker host, e.g. with sudo ufw reject https.

**Comment by diginc** [comment]
As nxadm mentioned, adding the 443 port should help.  We recommend this by default in the README now.  We'll close this soon if there are no additional comments.
