### ISSUE TITLE
bash /opt/pihole/gravity.sh -g DNS resolution is currently unavailable

### ISSUE THREAD

**Issue by rrd911** [pi-hole/docker-pi-hole#280]
This is a... 

- [ ] Request for a new or modified feature
- [x ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

After a reboot of my server I have had no luck updating my block lists. I have a second pi-hole and it works fine and does not have the issue.

When I run
bash /opt/pihole/gravity.sh -g 

I get
DNS resolution is currently unavailable

I can nslookup and ping any domain o nthe system

## Expected Behavior

Black lists should update
bash /opt/pihole/gravity.sh -g should pull down updates

## Actual Behavior

 bash /opt/pihole/gravity.sh -g
  [✗] DNS resolution is currently unavailable
  [✗] DNS resolution is not available

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran

Pi-hole Version v3.3.1 Web Interface Version v3.3 FTL Version v3.0

I used  a compose file to build my docker
 pihole:
  restart: unless-stopped
  container_name: pihole
  image: diginc/pi-hole
  volumes:
    - ${USERDIR}/docker/pihole:/etc/pihole
    - ${USERDIR}/docker/shared:/shared
  environment:
    - ServerIP=X.X.X.X(ip hidden)
    - DNS1=208.67.222.222
    - DNS2=208.67.220.220
  cap_add:
    - NET_ADMIN
  ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "80:80"

## Debug steps I have tried

Compared working Pi-hole docker build that used the same compose file with server ip change Didn't see any difference
Search google for error and check resolv and host files, the two servers are 

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Context and extra information

unable to update black lists

## Your Environment 

* Docker Host Operating System and OS Version: Ubuntu 16.04
* Docker Version: Docker version 18.03.1-ce, build 9ee9f40
* Hardware architecture: x86 quad core amd Opteron system

**Comment by abhin4v** [comment]
I am facing the exactly same issue.

**Comment by nxadm** [comment]
On systems where systemd-resolve replaces resolv.conf (argh), port 53 is claimed on the localhost (127.0.0.1). This can conflict with services running on port 53. Becasue port 53 is already claimed on 127.0.0.1, you must specify the host IP to bind the port to:

>     ports:
>       - "172.16.1.5:53:53"
>       - "172.16.1.5:53:53/udp"
>       - "172.16.1.5:80:80"
>       - "172.16.1.5:443:443"

I don't know if this is your problem, but I have seen it a few times already.

**Comment by rrd911** [comment]
at startup I see

Using custom DNS servers: 208.67.222.222 & 208.67.220.220


DNSMasq binding to default interface: eth0


Added ENV to php:


			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",


			"ServerIP" => "10.1.1.13",


			"VIRTUAL_HOST" => "10.1.1.13",


Using IPv4 and IPv6


dnsmasq: syntax check OK.


::: Testing DNSmasq config: ::: Testing lighttpd config: Syntax OK


::: All config checks passed, starting ...


::: Docker start setup complete


  [✗] DNS resolution is currently unavailable

**Comment by abhin4v** [comment]
I stopped and disabled systemd-resolve on the host machine and changed the nameserver in /etc/resolve.conf to 127.0.0.1. That fixed the issue.

**Comment by QantumEntangled** [comment]
I ran into this issue on windows and determined that this happens when my host machine has default DNS set to 127.0.0.1 or an invalid DNS host, but when Host machine's DNS is set to valid DNS servers the docker container boots and works fine.
