### ISSUE TITLE
Have only a single DNS Server

### ISSUE THREAD

**Issue by StefanSchoof** [pi-hole/docker-pi-hole#281]
This is a... 

- [x] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
In the [pihole configuration guide for routers](https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server/245) has the second option ("Advertise Pi-hole’s IP address via dnsmasq in the router (if supported)") the section:

> On Pi-hole, login to the web interface http://pi.hole > Settings > DNS and instead of choosing upstream servers like Google or OpenDNS, set the upstream to be the IP address of the router as the only upstream DNS server. Do not define any other DNS entries for Pi-hole:

I found no way to do this in the docker image. In the [Environment Variables](https://github.com/diginc/docker-pi-hole#environment-variables) section is mention how to unset DNS2 and in a quick look into the [bash_functions.sh](https://github.com/diginc/docker-pi-hole/blob/8e2889ba561121a3644d97481137033aa19bdd2f/bash_functions.sh#L41) I see with my bash knowlage no way to do this.

## Expected Behavior
Having a way to have not default the second dns to 8.8.4.4.

## Actual Behavior
If no value is used for the second dns, it is always 8.8.4.4.

## Possible Fix
Do not set second dns if it has the value "0.0.0.0" or "unset".

**Comment by diginc** [comment]
Solved correct?

**Comment by StefanSchoof** [comment]
Tested on 4.0 and works.
