### ISSUE TITLE
Web Interface doesn't seem to work 

### ISSUE THREAD

**Issue by CrypticOne** [pi-hole/docker-pi-hole#286]
This is a... 

- [ ] Request for a new or modified feature
- [ X] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Running Pihole on Synology with newest fresh built docker image.
pihole -v reports

root@pihole:/# pihole -v
  Pi-hole version is v3.3.1 (Latest: v3.3.1)
  AdminLTE version is v3.3 (Latest: v3.3)
  FTL version is v3.0 (Latest: v3.0)

## Expected Behavior

Whitelisting site reports:

Adding to the Whitelist...
× Failure! Something went wrong.

Whitelisting from command prompt works properly. Issue should have been fixed in newest pihole but still exists in Docker image.

Pausing pihole from web interface starts count down but websites are still blocked.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Running in Docker with host networking Web port 9000
2. Install via this guide http://tonylawrence.com/post/unix/synology/running-pihole-inside-docker/
3. 
4. 

## Debug steps I have tried

- [ X] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Synology
* Docker Version:
* Hardware architecture:

**Comment by nxadm** [comment]
I am on the same boat. The webinterface used to work fine, but somewhere it broke on one of the upgrades. What I have tried:
- recreating the volumes
- update the debian packages
- build the container locally
- remove the volumes
- change the ownership and rights of pihole.log (even temporarely to 777).
- pihole -r
- removing the FTL database

Pihole works, the dashboard doesn't. Also some commands are broken in the web interface like tailing the log files or disabling query logging (it stays orange after the interface says it was disabled).

**Comment by CrypticOne** [comment]
Very frustrating. Seems like a fairly rare issue as well. Without being able to whitelist items easily I swapped back to normal DNS for the time being.  Are you running the web interface on a different port?

**Comment by nxadm** [comment]
In my case, white and blacklisting works.

**Comment by CrypticOne** [comment]
When you say works. Do you mean you can interact with the lists or just that they are displayed?

**Comment by diginc** [comment]
@nxadm are you also running a synology?  I do not have a synology and have generally had a hard time reproducing their issues :( 

@CrypticOne are you able to see any error regarding Lighttpd during the container setup if you re-create it with the environment variable PH_VERBOSE=1 ?

The container logs may not reveal the whole problem, some other steps to maybe look into.
- enter the container to interact with it
- `docker exec -it pihole bash`
- check if lighttpd is running:
- `ps -efH | grep light`
- check the lighttpd error logs:
- `cat /var/log/lighttpd/error.log`
- try lighttpd's configuration error check command
- `lighttpd -t -f /etc/lighttpd/lighttpd.conf `

**Comment by mackeyja92** [comment]
Having same issue. 

```text
root@65b0599f3c41:/# ps -efH | grep ligh
root       438   344  0 13:25 pts/0    00:00:00   grep ligh
```

```text
root@65b0599f3c41:/# cat /var/log/lighttpd/error.log
2018-07-28 13:20:43: (log.c.217) server started
2018-07-28 13:23:50: (server.c.1534) logfiles cycled UID = 0 PID = 773
2018-07-28 13:23:51: (server.c.1828) server stopped by UID = 0 PID = 773
```

```text
root@65b0599f3c41:/# lighttpd -t -f /etc/lighttpd/lighttpd.conf
Syntax OK
```


```text
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
+ bashCmd='bash -e -x'
+ dnsmasq -7 /etc/dnsmasq.d
+ bash -e -x /start.sh
+ export TAG
+ export ServerIP
+ export ServerIPv6
+ export PYTEST
+ export PHP_ENV_CONFIG
+ export PHP_ERROR_LOG
+ export HOSTNAME
+ export WEBLOGDIR
+ export DNS1
+ export DNS2
+ export INTERFACE
+ export IPv6
+ export WEBPASSWORD
+ export WEB_PORT
+ . /bash_functions.sh
++ . /opt/pihole/webpage.sh
+++ setupVars=/etc/pihole/setupVars.conf
+++ dnsmasqconfig=/etc/dnsmasq.d/01-pihole.conf
+++ dhcpconfig=/etc/dnsmasq.d/02-pihole-dhcp.conf
+++ dhcpstaticconfig=/etc/dnsmasq.d/04-pihole-static-dhcp.conf
+++ coltable=/opt/pihole/COL_TABLE
+++ [[ -f /opt/pihole/COL_TABLE ]]
+++ source /opt/pihole/COL_TABLE
++++ [[ -t 1 ]]
++++ COL_BOLD=
++++ COL_ULINE=
++++ COL_NC=
++++ COL_GRAY=
++++ COL_RED=
++++ COL_GREEN=
++++ COL_YELLOW=
++++ COL_BLUE=
++++ COL_PURPLE=
++++ COL_CYAN=
++++ COL_WHITE=
++++ COL_BLACK=
++++ COL_LIGHT_BLUE=
++++ COL_LIGHT_GREEN=
++++ COL_LIGHT_CYAN=
++++ COL_LIGHT_RED=
++++ COL_URG_RED=
++++ COL_LIGHT_PURPLE=
++++ COL_BROWN=
++++ COL_LIGHT_GRAY=
++++ COL_DARK_GRAY=
++++ TICK='[✓]'
++++ CROSS='[✗]'
++++ INFO='[i]'
++++ QST='[?]'
++++ DONE=' done!'
++++ OVER='\r'
++ setupVars=/etc/pihole/setupVars.conf
++ ServerIP=10.1.1.218
++ ServerIPv6=
++ IPv6=false
+ echo ' ::: Starting docker specific setup for docker diginc/pi-hole'
+ validate_env
 ::: Starting docker specific setup for docker diginc/pi-hole
+ '[' -z 10.1.1.218 ']'
++ nc -4 -w1 -z 10.1.1.218 53
+ [[ '' != '' ]]
+ ip route get 10.1.1.218
+ [[ -n '' ]]
+ prepare_setup_vars
+ touch /etc/pihole/setupVars.conf
+ change_setting IPV4_ADDRESS 10.1.1.218
+ delete_setting IPV4_ADDRESS
+ sed -i /IPV4_ADDRESS/d /etc/pihole/setupVars.conf
+ add_setting IPV4_ADDRESS 10.1.1.218
+ echo IPV4_ADDRESS=10.1.1.218
+ change_setting IPV6_ADDRESS ''
+ delete_setting IPV6_ADDRESS
+ sed -i /IPV6_ADDRESS/d /etc/pihole/setupVars.conf
+ add_setting IPV6_ADDRESS ''
+ echo IPV6_ADDRESS=
+ setup_web_port ''
+ local 'warning=WARNING: Custom WEB_PORT not used'
+ [[ -z '' ]]
+ return
+ setup_web_password *****
+ '[' -z x ']'
+ set -x
+ [[ Hb1kXzIaXZ22z2mV6UAL == '' ]]
+ pihole -a -p ***** *****
  [✓] New password set
Using custom DNS servers: 1.1.1.1 & 8.8.8.8
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "10.1.1.218",
			"VIRTUAL_HOST" => "https://pihole.custom.domain",
Using IPv4
dnsmasq: syntax check OK.
::: Testing DNSmasq config: ::: Testing lighttpd config: Syntax OK
::: All config checks passed, starting ...
::: Docker start setup complete
+ gravity.sh
  [✗] DNS resolution is currently unavailable
```

**Comment by nxadm** [comment]
@diginc 

> @nxadm are you also running a synology? I do not have a synology and have generally had a hard time reproducing their issues :(

No, I am running it as a docker container on Ubuntu 18.04. My docker-compose file looks like this:
`
version: '2'
services:
  pihole:
    build:
     # git clone of the latest tag of the repo
      context: /opt/docker/_upstream/docker-pi-hole
      dockerfile: Dockerfile_debian_amd64
    environment:
      - TZ='Europe/Brussels'
      - ServerIP=172.16.1.2
      - WEBPASSWORD=foobar
      - DNS1=8.8.8.8
      - DNS2=8.8.4.4
      - IPv6=False
    ports:
      - "172.16.1.5:53:53"
      - "172.16.1.5:53:53/udp"
      - "172.16.1.5:80:80"
      - "172.16.1.5:443:443"
    volumes:
      - /opt/docker/pihole/rw/pihole:/etc/pihole
      - /opt/docker/pihole/rw/dnsmasq.d:/etc/dnsmasq.d
    restart: always
`

**Comment by mackeyja92** [comment]
Rolling back to `alpine_v3.1` gives the error below

```text
Failed Host Check: pihole.custom.domain vs 10.1.1.218, , dockerpi.hole, pi.hole, localhost, https://pihole.custom.domain
```

Meaning my config for `"VIRTUAL_HOST" => "https://pihole.custom.domain"` is wrong. I had to strip off `https://` and just leave the domain.

It is working on the alpine image but is not working on `latest` with the same docker config.

**Comment by zimmertr** [comment]
I can confirm I'm also experiencing this issue.

**Comment by zimmertr** [comment]
For what it's worth, I followed @mackeyja92's advice and  switched over to `alpine_v3.1.4`. After I had everything running and stuff for a day I just tried to change the image over to `latest` in my `docker-compose.yaml` file and it started right up and I've been running latest since with no issues.

**Comment by diginc** [comment]
Interesting that using an old alpine version and then everything working.  I wonder if the /start.sh script in that fixed something on your volumes that persisted between images.  Thanks for the info.

I added a lot of volume file permission changes to the new v4.0 release which runs on startup to ensure volumes aren't missing permissions.  I'm not sure if that'll take care of this issue but in general I only try to support the latest version so please give it a try and if there are issues let me know.

**Comment by nxadm** [comment]
The newest release (v4.0) solves this problem for me. Thank you for your work!

**Comment by Haxy89** [comment]
@nxadm 
Can you show your docker run command? 
I have the same problem on the newest release. 
Can't run pi-hole docker on my raspberry with raspian

**Comment by nxadm** [comment]
@Haxy89 

I use docker-compose to manage my containers at my home server. The docker-compose file is printed above: https://github.com/pi-hole/docker-pi-hole/issues/286#issuecomment-408633112

You can recreate the docker run command by passing the environment values with -e, the volumes with -v and the ports with -p.

The name of the Dockerfile changed to Dockerfile-amd64 in the v4.0 release.

**Comment by Haxy89** [comment]
Need to add --dns 127.0.0.1 when starting pihole container

**Comment by CrypticOne** [comment]
I got around to installing 4.0 pihole/pihole image. Still no web interface interaction due to the sudo issue.

**Comment by travman19** [comment]
I have the i same issue. Using a synology 1817+ latest dsm, docker and repos release. any update on this issue by change?

**Comment by carbonide** [comment]
Yeah, I just wanted to chime in that I have the same issue on my Synology server: pihole works just fine, but I can't change anything using the GUI and there's no version displayed in the lower right part of the window (N/A).

**Comment by diginc** [comment]
Hi @carbonide - using the pihole/pihole image I assume?  Do you see any php errors in your `docker logs` output?

Anyone else with web issues I'd suggest searching for the same.  It may all be related to https://github.com/pi-hole/docker-pi-hole/issues/243

**Comment by carbonide** [comment]
Yep, I'm using pihole/pihole and there are errors after pihole started:

`14:30:01	sudo: unable to send audit message: Unknown error -1
14:30:01	sudo: pam_open_session: System error
14:30:01	sudo: policy plugin failed session initialization
14:30:01	sudo: unable to send audit message: Unknown error -1
14:30:01	sudo: pam_open_session: System error
14:30:01	sudo: policy plugin failed session initialization
14:30:01	sudo: unable to send audit message: Unknown error -1
14:30:01	sudo: pam_open_session: System error
14:30:01	sudo: policy plugin failed session initialization
14:30:18	sudo: unable to send audit message: Unknown error -1
14:30:18	sudo: pam_open_session: System error
14:30:18	sudo: policy plugin failed session initialization `

I'm not sure what pam is (pluggable authentication module?). :( But again, pihole seems to work just fine, except for the problems mentioned in my first post.

**Comment by diginc** [comment]
That looks the same as #243 - we had some progress on that but I haven't gotten a fixed image out yet.

Check out this comment for the solution https://github.com/pi-hole/docker-pi-hole/issues/243#issuecomment-431673392

**Comment by carbonide** [comment]
Sadly, I have no idea where to apply the fix. I can't find /etc/apt/sources.list on my Synology. I don't even know where Synology stores the docker containers, I'm only able to map container folders to a server folder and change files in there.

**Comment by diginc** [comment]
Don't worry about it, I'll work on getting the images fixed more tonight.
The latest comment pointed out what I most likely did wrong on my first
attempt.

**Comment by carbonide** [comment]
Great to here! Thanks for your work.

**Comment by travman19** [comment]
The latest version resolved all of my GUI issues!

**Comment by diginc** [comment]
https://github.com/pi-hole/docker-pi-hole/issues/243 is the main ticket for this, please use it for updates.

We had a fix working on a temporary image but I deleted it as it was a very large image and need optimized.  After optimizing and merging to development I somehow pushed an old copy of development instead of the fixed copy of development so please wait until a newer image gets pushed to development gets pushed.

`latest` tag image hasn't been updated to fix su/sudo/audit bugs yet.

**Comment by diginc** [comment]
The original submission was also about v3 problems, we're not on v4 images.  For synology issues please use #243.
