### ISSUE TITLE
DHCP

### ISSUE THREAD

**Issue by alazare619** [pi-hole/docker-pi-hole#292]
on dockerhub you should update the run command to include DHCP ports of 67/68 UDP required without which it will not run when done in bridged mode.

**Comment by diginc** [comment]
For more advanced use cases I like to document the docker run using docker-compose yaml files, like the [Traefik example](https://github.com/diginc/docker-pi-hole/blob/master/traefik-docker-compose-example.md).

This keeps the basic run command example minimal and without extra stuff not everyone uses.  I don't have insights into the percentage of people using DHCP but I consider it advanced and assume the majority of users do not get that advanced.

The readme docs section on DHCP currently suggests just running `--net host` (this is not based off experience, just out of ease).  Do you think the port forwarding of 67/68 alternative would better suit the majority of DHCP users?

Combining all the above I'd be open to:
- Writing a more detailed DHCP setup section with multiple networking configurations explained
- Having an example dhcp-docker-compose-example.yaml linked to from docs

**Comment by zefal** [comment]
Excuse my lack of knowledge here but I think is related to issue I have with this docker image and DHCP...

Got pi-hole running wonderfully on my QNAP on container station using your diginc/pi-hole image (thank you!). It works well as DNS etc but I then wanted to use it as my DHCP server to make local DNS resolution easier.
The only issue is that the DHCP server port UDP/67 is NOT exposed with this docker configuration. You can enable DHCP server in pi-hole via CLI or GUI and it enables it etc... you can see it running as process and on netstat within container:
# netstat -lnu                                                                                                                       
Active Internet connections (only servers)                                                                                           
Proto Recv-Q Send-Q Local Address           Foreign Address         State                                                            
udp        0      0 0.0.0.0:53              0.0.0.0:*                                                                                
udp        0      0 0.0.0.0:67              0.0.0.0:*                                                                                
udp        0      0 127.0.0.11:43127        0.0.0.0:*                                                                                
udp6       0      0 :::53                   :::*   

However it doesn't work and clients don't get IP addresses. I think I've narrowed down the issue that the DHCP port is not exposed on docker level using this image:
[~] # docker inspect 28f2b81fa598
<snipped>
"Config": {
            "Hostname": "pi-hole",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "53/tcp": {},
                "53/udp": {},
                "80/tcp": {}

I litterally only know how to create/download your image when creating image in container station on QNAP.... do you know how I can add the exposed port UDP/67? Maybe you could update it so it's defaults to exposing that port should someone enable DHCP server in config?

Thanks,

Paul

**Comment by diginc** [comment]
I think container station bases what ports it exposes of the Dockerfile's EXPOSE definitions, of which there is none for 67/68 currently.  I'll get it added and release an update.

**Comment by zefal** [comment]
That would be great, many thanks!

**Comment by diginc** [comment]
@alazare619 could you review the README / doc changes in #293 ?

@zefal the dev image should be re-building with the EXPOSE ports changed to have port 67 and 443 added.  Not sure if that really fixes your issue after doing a little more reading about QNAP containers.  I saw a few search results saying you needs to find the Advanced Networking section to ade exposed ports your self.  At first glance through their docs yesterday I did not see that.

**Comment by zefal** [comment]
I don't think that is the case with QNAP, there is no option in advanced networking to open ports. It seems it's directly in the docker configuration that exposed ports are configured.

**Comment by zefal** [comment]
To add more information about adding ports in QNAP. No you can't add exposed ports in advanced settings...
Not when container is in bridge mode anyway (separate IP than QNAP host).
You can set port forwards on whatever ports you need in NAT/Host networking mode, but again I very much doubt it will add exposed ports configuration on the docker side?
I have no idea how these things work in github, so I'm going to ask... is the update ready yet? LOL

**Comment by diginc** [comment]
No problem, when I pushed the change to my dev branch, docker's build service automatically rebuilt my changes and deployed a new image to docker hub which you can pull just by telling your docker client to use the image named `diginc/pi-hole:debian_dev` (updated 2 days ago according to https://hub.docker.com/r/diginc/pi-hole/tags/ ).  So you'll remove your current container, swap the image to `diginc/pi-hole:debian_dev` in the config, and up the new one in it's place using your previous volumes if you wish to persist your settings/logs.  Not having a QNAP it's tough to get more specific than that but I hope I helped.

**Comment by zefal** [comment]
Hi,
The _dev version doesn't work for me:

[fix-attrs.d] 01-resolver-resolv: exited 0.                                                                                                                  
[fix-attrs.d] done.                                                                                                                                          
[cont-init.d] executing container initialization scripts...                                                                                                  
[cont-init.d] 20-start.sh: executing...                                                                                                                      
 ::: Starting docker specific setup for docker diginc/pi-hole                                                                                                
ERROR: To function correctly you must pass an environment variables of 'ServerIP' into the docker container with the IP of your docker host from which you ar
e passing web (80) and dns (53) ports from                                                                                                                   
[cont-init.d] 20-start.sh: exited 1.                                                                                                                         
[cont-finish.d] executing container finish scripts...                                                                                                        
[cont-finish.d] done.                                                                                                                                        
[s6-finish] syncing disks.                                                                                                                                   
[s6-finish] sending all processes the TERM signal.                                                                                                           
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by diginc** [comment]
> ERROR: To function correctly you must pass an environment variables of 'ServerIP' into the docker container with the IP of your docker host from which you ar

^^^

**Comment by zefal** [comment]
Sorry you will have to humour me. I'm just deleting and recreating from scratch through continaer station.
If I use "latest" version, it works. I only change the network settings to bridge mode/DHCP.
If I use this _dev version. The container refuses to start with above error.

**Comment by diginc** [comment]
There was a bug in the previous version where "ServerIP" environment variable not being set was supposed to block starting the container.  The bug was fixed.  Just add an environment variable for ServerIP and set it to your QNAP's external IP address.

**Comment by zefal** [comment]
I'm sorry mate, I don't know how to change the environment variables.
I have option in container station to add some. Am I creating a new one? i.e. name = "ServerIP" and value = "192.168.x.x" and that is it?
This environment variable isn't present on the "latest" one BTW

**Comment by diginc** [comment]
No prob, sounds like you get it.  Add a new one, key of "ServerIP" value of your IP.

The environment variable has always been there (see [README](https://github.com/diginc/docker-pi-hole#environment-variables)), it's just the validation to make sure the user as set it wasn't working.

**Comment by zefal** [comment]
I've also worked out how to set shared volumes to keep my configs persistent after killing a container and re-creating with new image... so how do I subscribe to find out when latest image has been updated with these changes?

**Comment by diginc** [comment]
The Pi-hole web interface notifies you of updates so if you check your http://pi.hole/admin/ web interface it'll notify you that there's a new version out.  You can always watch / star this repo on github.

**Comment by zefal** [comment]
Perfect! Thanks again!

**Comment by alazare619** [comment]
@diginc  just reviewed that PR of the readme doc everything looks great.
