### ISSUE TITLE
Pihole v4 startup issues

### ISSUE THREAD

**Issue by eku** [pi-hole/docker-pi-hole#303]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Just pulled the new pihole v4 docker image ```docker.io/pihole/pihole```. Unfortuantely it has startup issues.

## Expected Behavior

Start without issues.

## Actual Behavior

```
Aug  5 10:54:28 journal[3285]: /start.sh: line 47: syntax error near unexpected token `newline'
Aug  5 10:54:28 journal[3285]: /start.sh: line 47: `echo <EOF>>'
```
## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar ## Your Environment 

* Docker Host Operating System and OS Version: Fedora 28
* Docker Version: Docker version 1.13.1, build bdb8293-unsupported
* Hardware architecture: x64

**Comment by diginc** [comment]
A new version has been pushed since this one accidentally went out, please pull the latest and try again.

**Comment by diginc** [comment]
Sorry, just spotted an error in the deploy script that most likely meant an old bugged version got pushed repeatedly so it looked updated when I checked, but was old.  It should be good now.
