### ISSUE TITLE
Docker image doesn't works on RaspberryPi with docker

### ISSUE THREAD

**Issue by Haxy89** [pi-hole/docker-pi-hole#306]
Run command:
`sudo docker run -d -p 53:53/tcp -p 53:53/udp -p 80:80 --name Pihole --restart=unless-stopped -v /home/pi/pihole/data/:/etc/pihole/ -v /home/pi/pihole/dns/:/etc/dnsmasq.d/ -e ServerIP=192.168.0.20 -e TZ=Europe/Warsaw -e WEBPASSWORD=pass -e IPv6=False pihole/pihole:v4.0_armhf`

Log:
`https://pastebin.com/YzyPE464`

**Comment by diginc** [comment]
I just found checking the dnsmasq configs was missed in our initial release.  Could you try running this to see if your DNSMasq configs are passing tests / valid ?

`
sudo docker run -d -p 53:53/tcp -p 53:53/udp -p 80:80 --name Pihole --restart=unless-stopped -v /home/pi/pihole/data/:/etc/pihole/ -v /home/pi/pihole/dns/:/etc/dnsmasq.d/ -e ServerIP=192.168.0.20 -e TZ=Europe/Warsaw -e WEBPASSWORD=pass -e IPv6=False --entrypoint=bash pihole/pihole:v4.0_armhf -c 'pihole-FTL dnsmasq-test'
`

**Comment by Haxy89** [comment]
@diginc 

```
sudo docker logs Pihole -f
dnsmasq: syntax check OK.
dnsmasq: syntax check OK.
dnsmasq: syntax check OK.
dnsmasq: syntax check OK.
dnsmasq: syntax check OK.
dnsmasq: syntax check OK.
dnsmasq: syntax check OK.
```

**Comment by manicmonkey** [comment]
I just set this up and it is working on my raspberry pi - maybe it's something environmental.

I noticed you are manually specifying the server IP - did you find that [this script](https://github.com/pi-hole/docker-pi-hole/blob/master/docker_run.sh) does not work for you? Maybe a routing issue?

**Comment by Haxy89** [comment]
@diginc 
I run your last docker run command:
```
sudo docker run -it --rm -p 53:53/tcp -p 53:53/udp -p 80:80 --name Pihole -v /home/pi/pihole/data/:/etc/pihole/ -v /home/pi/pihole/dns/:/etc/dnsmasq.d/ -e ServerIP=192.168.0.20 -e TZ=Europe/Warsaw -e WEBPASSWORD=pass -e IPv6=False --entrypoint=bash pihole/pihole:v4.0_armhf -c 'bash -ex gravity.sh'
```
New pastebin: `https://pastebin.com/Hr7pDkWK`

@manicmonkey 

> I noticed you are manually specifying the server IP - did you find that this script does not work for you? Maybe a routing issue?

It is my rasp IP in my local network (192.168.0.20). 
I don't want to use script because it contains unnecessary parameters. 
I use docker run command from it and tweak it a little. I am sure it is correct and should works:

```
sudo docker run -d -p 53:53/tcp -p 53:53/udp -p 80:80 --name Pihole --restart=unless-stopped -v /home/pi/pihole/data/:/etc/pihole/ -v /home/pi/pihole/dns/:/etc/dnsmasq.d/ -e ServerIP=192.168.0.20 -e TZ=Europe/Warsaw -e WEBPASSWORD=pass -e IPv6=False pihole/pihole:v4.0_armhf
```

**Comment by Haxy89** [comment]
@diginc 
pihole/data is empty

![image](https://user-images.githubusercontent.com/37550896/43843879-cc0d98f8-9b28-11e8-856f-580033d9bee5.png)

**Comment by diginc** [comment]
I forgot to ask the version of docker you had.  what does `docker version` say and what kernel are you on `uname -a` ?

The empty directory makes sense looking over the logs closer.  We're aborting the startup on error intentionally to prevent starting an inoperable container.  Some of the older docker versions seem to be throwing some really weird errors from what I've gathered so far.  If you are on a version that isn't from the past year I'd strongly suggest upgrading.

**Comment by Haxy89** [comment]
@diginc 
`Linux raspberrypi 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux
`

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:19:46 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:15:34 2018
  OS/Arch:          linux/arm
  Experimental:     false
```

**Comment by diginc** [comment]
That look good 👍 

How about if you run without volumes?

**Comment by oscarnyl** [comment]
Experiencing the same issue.

I suspect that 4.0 unveiled an underlying issue present in earlier versions (by adding `set -e` to `20-start.sh`). Gravity has always taken an unusual amount of time for me to start, likely caused by the 120 second timeout it has - output from gravity.sh before it exits is:

```[✗] DNS resolution is currently unavailable
[✗] DNS resolution is not available````

I will do some testing without volumes etc and get back with results.

**Comment by Haxy89** [comment]
@diginc 
without volumes: `sudo docker run -d -p 53:53/tcp -p 53:53/udp -p 80:80 --name Pihole --restart=unless-stopped -e ServerIP=192.168.0.20 -e TZ=Europe/Warsaw -e WEBPASSWORD=pass -e IPv6=False pihole/pihole:v4.0_armhf
`

The same problem: https://pastebin.com/QRkKfJnu

**Comment by oscarnyl** [comment]
Issue persists without volumes. Same behaviour.

**Comment by oscarnyl** [comment]
@manicmonkey I've done this as well! Quite likely that this is what's causing the issue then.

**Comment by Haxy89** [comment]
@manicmonkey
So what should I change? 
Currently my router always assign the same ip to my raspberry pi (I have DHCP server on my router and set up manual IP assignment for my raspberry), I also set ip of my raspberry pi as local network DNS on my router

**Comment by diginc** [comment]
/etc/resolv.conf in a docker container is read only because the docker daemon locks it down. 
 
To modify it you need to pass in dns to docker run or setup the docker daemon with a custom /etc/docker/daemon.json dns setting.  

Try `docker run --dns 127.0.0.1 --dns 1.1.1.1`

I only recommend the first DNS be localhost/127.0.0.1 because it will help with LAN IP to hostname conversion up in the web interface.  This is mainly needed if you're running DHCP or add any custom LAN addresses into /etc/hosts with docker extra_hosts.

**Comment by Haxy89** [comment]
@diginc 
Adding -e DNS1 does not help.

```sudo docker run -d -p 53:53/tcp -p 53:53/udp -p 80:80 --name Pihole --restart=unless-stopped -v /home/pi/pihole/data/:/etc/pihole/ -v /home/pi/pihole/dns/:/etc/dnsmasq.d/ -e DNS1=1.1.1.1 -e DNS2=1.0.0.1 -e ServerIP=192.168.0.20 -e TZ=Europe/Warsaw -e WEBPASSWORD=59%6g83@C98P8^ -e IPv6=False pihole/pihole:v4.0_armhf```

https://pastebin.com/QNtbmzhW

**Comment by oscarnyl** [comment]
Adding the DNS entries manually to the docker container start solved my problem. Cheers!

**Comment by SeanChristopherConway** [comment]
Oh thank you for this! Adding --dns 127.0.01 also fixed this issue. Was going bonkers.

**Comment by chilicheech** [comment]
This solved my issue. Adding `dns: 127.0.0.1` to my `docker-compose.yml` solved the problem. This should be documented somewhere to help other folks easily find it.

Cheers,
