### ISSUE TITLE
Docker image dies on Synology

### ISSUE THREAD

**Issue by gochito** [pi-hole/docker-pi-hole#310]
This is a Synology DS-216+II, running the dijinc/pi-hole 3.3 version just fine.
- [ ] Request for a new or modified feature
- [X] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I downloaded the version 4 image (Latest Tag) and stopped the v 3.3 image. The new container won't stay up... it just dies within 30 seconds from startup.

## Expected Behavior

Startup
## Actual Behavior

Dies before starting.
## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.
2. 
3. 
4. 

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: DSM 6.2-23739 Update 2, 
* Docker Version:Docker V 17.05.0-0379
* Hardware architecture: X86

**Comment by aptalca** [comment]
You should post a docker log, which will most likely show what the specific error is

**Comment by diginc** [comment]
Could you try updating to a 2018 version of docker?

Also please add `docker log` output with the error that is occurring during startup.  

Alternatively you can run it in the foreground with something like: `sudo docker run -it --rm --name pihole-test -e ServerIP=0.0.0.0 pihole/pihole` and report back where it dies.

**Comment by gochito** [comment]
Hello fellows... 17.05 is the latest docker package available for the Synology. 

Here is the log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific setup for docker pihole/pihole
ERROR: To function correctly you must pass an environment variables of 'ServerIP' into the docker container with the IP of your docker host from which you are passing web (80) and dns (53) ports from
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific setup for docker pihole/pihole
ERROR: To function correctly you must pass an environment variables of 'ServerIP' into the docker container with the IP of your docker host from which you are passing web (80) and dns (53) ports from
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by diginc** [comment]
> ERROR: To function correctly you must pass an environment variables of 'ServerIP' into the docker container with the IP of your docker host from which you are passing web (80) and dns (53) ports from

please add `-e ServerIP=0.0.0.0` to your `docker run` - alternatively your SynologyIP instead of 0.0.0.0.

**Comment by gochito** [comment]
There you go. Started fine.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific setup for docker pihole/pihole
ERROR: To function correctly you must pass an environment variables of 'ServerIP' into the docker container with the IP of your docker host from which you are passing web (80) and dns (53) ports from
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific setup for docker pihole/pihole
ERROR: To function correctly you must pass an environment variables of 'ServerIP' into the docker container with the IP of your docker host from which you are passing web (80) and dns (53) ports from
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific setup for docker pihole/pihole
  [i] Existing PHP installation detected : PHP version 7.0.30-0+deb9u1

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
+ [[ '' == '' ]]
+ pihole -a -p
+ echo ''

  [✓] Password Removed
+ '[' 0 -gt 0 ']'
+ setup_dnsmasq '' '' ''
+ local dns1=
+ local dns2=
+ local interface=
+ setup_dnsmasq_config_if_missing
+ '[' '!' -f /etc/dnsmasq.d/01-pihole.conf ']'
+ setup_dnsmasq_dns '' ''
+ . /opt/pihole/webpage.sh
++ setupVars=/etc/pihole/setupVars.conf
++ dnsmasqconfig=/etc/dnsmasq.d/01-pihole.conf
++ dhcpconfig=/etc/dnsmasq.d/02-pihole-dhcp.conf
++ FTLconf=/etc/pihole/pihole-FTL.conf
++ dhcpstaticconfig=/etc/dnsmasq.d/04-pihole-static-dhcp.conf
++ coltable=/opt/pihole/COL_TABLE
++ [[ -f /opt/pihole/COL_TABLE ]]
++ source /opt/pihole/COL_TABLE
+++ [[ -t 1 ]]
++++ tput colors
+++ [[ 8 -ge 8 ]]
+++ COL_BOLD=''
+++ COL_ULINE=''
+++ COL_NC=''
+++ COL_GRAY=''
+++ COL_RED=''
+++ COL_GREEN=''
+++ COL_YELLOW=''
+++ COL_BLUE=''
+++ COL_PURPLE=''
+++ COL_CYAN=''
+++ COL_WHITE=''
+++ COL_BLACK=''
+++ COL_LIGHT_BLUE=''
+++ COL_LIGHT_GREEN=''
+++ COL_LIGHT_CYAN=''
+++ COL_LIGHT_RED=''
+++ COL_URG_RED=''
+++ COL_LIGHT_PURPLE=''
+++ COL_BROWN=''
+++ COL_LIGHT_GRAY=''
+++ COL_DARK_GRAY=''
+++ TICK='[✓]'
+++ CROSS='[✗]'
+++ INFO='[i]'
+++ QST='[?]'
+++ DONE=' done!'
+++ OVER='\r'
+ local DNS1=8.8.8.8
+ local DNS2=8.8.4.4
+ local dnsType=default
+ '[' 8.8.8.8 '!=' 8.8.8.8 ']'
+ '[' 8.8.4.4 '!=' 8.8.4.4 ']'
+ '[' '!' -f /.piholeFirstBoot ']'
+ echo 'Using default DNS servers: 8.8.8.8 & 8.8.4.4'
Using default DNS servers: 8.8.8.8 & 8.8.4.4
+ [[ -n 8.8.8.8 ]]
+ [[ -z '' ]]
+ change_setting PIHOLE_DNS_1 8.8.8.8
+ delete_setting PIHOLE_DNS_1
+ sed -i /PIHOLE_DNS_1/d /etc/pihole/setupVars.conf
+ add_setting PIHOLE_DNS_1 8.8.8.8
+ echo PIHOLE_DNS_1=8.8.8.8
+ [[ -n 8.8.4.4 ]]
+ [[ -z '' ]]
+ '[' 8.8.4.4 = no ']'
+ change_setting PIHOLE_DNS_2 8.8.4.4
+ delete_setting PIHOLE_DNS_2
+ sed -i /PIHOLE_DNS_2/d /etc/pihole/setupVars.conf
+ add_setting PIHOLE_DNS_2 8.8.4.4
+ echo PIHOLE_DNS_2=8.8.4.4
+ setup_dnsmasq_interface ''
+ local interface=eth0
+ local interfaceType=default
+ '[' eth0 '!=' eth0 ']'
+ echo 'DNSMasq binding to default interface: eth0'
DNSMasq binding to default interface: eth0
+ '[' -n eth0 ']'
+ change_setting PIHOLE_INTERFACE eth0
+ delete_setting PIHOLE_INTERFACE
+ sed -i /PIHOLE_INTERFACE/d /etc/pihole/setupVars.conf
+ add_setting PIHOLE_INTERFACE eth0
+ echo PIHOLE_INTERFACE=eth0
+ ProcessDNSSettings
+ source /etc/pihole/setupVars.conf
++ QUERY_LOGGING=true
++ INSTALL_WEB_SERVER=true
++ INSTALL_WEB_INTERFACE=true
++ LIGHTTPD_ENABLED=true
++ IPV4_ADDRESS=0.0.0.0
++ IPV6_ADDRESS=
++ WEBPASSWORD=
++ PIHOLE_DNS_1=8.8.8.8
++ PIHOLE_DNS_2=8.8.4.4
++ PIHOLE_INTERFACE=eth0
+ delete_dnsmasq_setting server
+ sed -i /server/d /etc/dnsmasq.d/01-pihole.conf
+ COUNTER=1
+ [[ -n 1 ]]
+ var=PIHOLE_DNS_1
+ '[' -z 8.8.8.8 ']'
+ add_dnsmasq_setting server 8.8.8.8
+ [[ 8.8.8.8 != '' ]]
+ echo server=8.8.8.8
+ let COUNTER=COUNTER+1
+ [[ -n 1 ]]
+ var=PIHOLE_DNS_2
+ '[' -z 8.8.4.4 ']'
+ add_dnsmasq_setting server 8.8.4.4
+ [[ 8.8.4.4 != '' ]]
+ echo server=8.8.4.4
+ let COUNTER=COUNTER+1
+ [[ -n 1 ]]
+ var=PIHOLE_DNS_3
+ '[' -z '' ']'
+ break
+ '[' '!' -z '' ']'
+ delete_dnsmasq_setting domain-needed
+ sed -i /domain-needed/d /etc/dnsmasq.d/01-pihole.conf
+ [[ '' == true ]]
+ delete_dnsmasq_setting bogus-priv
+ sed -i /bogus-priv/d /etc/dnsmasq.d/01-pihole.conf
+ [[ '' == true ]]
+ delete_dnsmasq_setting dnssec
+ sed -i /dnssec/d /etc/dnsmasq.d/01-pihole.conf
+ delete_dnsmasq_setting trust-anchor=
+ sed -i /trust-anchor=/d /etc/dnsmasq.d/01-pihole.conf
+ [[ '' == true ]]
+ delete_dnsmasq_setting host-record
+ sed -i /host-record/d /etc/dnsmasq.d/01-pihole.conf
+ '[' '!' -z '' ']'
+ delete_dnsmasq_setting interface
+ sed -i /interface/d /etc/dnsmasq.d/01-pihole.conf
+ delete_dnsmasq_setting local-service
+ sed -i /local-service/d /etc/dnsmasq.d/01-pihole.conf
+ [[ '' == \a\l\l ]]
+ [[ '' == \l\o\c\a\l ]]
+ '[' -z eth0 ']'
+ add_dnsmasq_setting interface eth0
+ [[ eth0 != '' ]]
+ echo interface=eth0
+ [[ '' == true ]]
+ setup_php_env
+ '[' -z '' ']'
+ VIRTUAL_HOST=0.0.0.0
+ local 'vhost_line=\t\t\t"VIRTUAL_HOST" => "0.0.0.0",'
+ local 'serverip_line=\t\t\t"ServerIP" => "0.0.0.0",'
+ local 'php_error_line=\t\t\t"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",'
+ grep -qP '\t\t\t"VIRTUAL_HOST" => "0.0.0.0",' /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
+ sed -i '/bin-environment/ a\\t\t\t"VIRTUAL_HOST" => "0.0.0.0",' /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
+ grep -qP '\t\t\t"ServerIP" => "0.0.0.0",' /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
+ sed -i '/bin-environment/ a\\t\t\t"ServerIP" => "0.0.0.0",' /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
+ grep -qP '\t\t\t"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",' /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
+ sed -i '/bin-environment/ a\\t\t\t"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",' /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
+ echo 'Added ENV to php:'
Added ENV to php:
+ grep -E '(VIRTUAL_HOST|ServerIP|PHP_ERROR_LOG)' /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "0.0.0.0",
			"VIRTUAL_HOST" => "0.0.0.0",
+ setup_dnsmasq_hostnames 0.0.0.0 '' pihole-pihole1
+ local IPV4_ADDRESS=0.0.0.0
+ local IPV6_ADDRESS=
+ local hostname=pihole-pihole1
+ local dnsmasq_pihole_01_location=/etc/dnsmasq.d/01-pihole.conf
+ '[' -z pihole-pihole1 ']'
+ [[ 0.0.0.0 != '' ]]
+ tmp=0.0.0.0
+ sed -i s/@IPV4@/0.0.0.0/ /etc/dnsmasq.d/01-pihole.conf
+ [[ '' != '' ]]
+ sed -i '/^address=\/pi.hole\/@IPv6@/d' /etc/dnsmasq.d/01-pihole.conf
+ sed -i '/^address=\/@HOSTNAME@\/@IPv6@/d' /etc/dnsmasq.d/01-pihole.conf
+ [[ pihole-pihole1 != '' ]]
+ sed -i s/@HOSTNAME@/pihole-pihole1/ /etc/dnsmasq.d/01-pihole.conf
+ setup_ipv4_ipv6
+ local 'ip_versions=IPv4 and IPv6'
+ '[' True '!=' True ']'
+ echo 'Using IPv4 and IPv6'
Using IPv4 and IPv6
+ setup_lighttpd_bind 0.0.0.0
+ local serverip=0.0.0.0
+ grep -q docker /proc/net/dev
+ setup_blocklists
+ local blocklists=
+ exit_string='(exiting setup_blocklists early)'
+ '[' -n '' ']'
+ '[' -f /etc/pihole/adlists.list ']'
+ '[' -n '' ']'
+ echo '::: setup_blocklists now setting default blocklists up: '
::: setup_blocklists now setting default blocklists up: 
+ echo '::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot'
::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
+ echo https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
+ echo https://mirror1.malwaredomains.com/files/justdomains
+ echo http://sysctl.org/cameleon/hosts
+ echo 'https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist'
+ echo https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
+ echo https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
+ echo https://hosts-file.net/ad_servers.txt
+ echo '::: Blocklists (/etc/pihole/adlists.list) now set to:'
::: Blocklists (/etc/pihole/adlists.list) now set to:
+ cat /etc/pihole/adlists.list
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
http://sysctl.org/cameleon/hosts
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://hosts-file.net/ad_servers.txt
+ test_configs
+ set -e
+ echo -n '::: Testing pihole-FTL DNS: '
::: Testing pihole-FTL DNS: + pihole-FTL test
FTL started!
+ echo -n '::: Testing lighttpd config: '
::: Testing lighttpd config: + lighttpd -t -f /etc/lighttpd/lighttpd.conf
Syntax OK
+ set +e
+ echo '::: All config checks passed, cleared for startup ...'
::: All config checks passed, cleared for startup ...
+ '[' -f /.piholeFirstBoot ']'
+ rm /.piholeFirstBoot
+ echo ' ::: Docker start setup complete'
 ::: Docker start setup complete
+ echo '
:: ::: ::: ::: ::: ::: ::: ::: ::: :::
:: Image moved / deprecation notice
::    OLD IMAGE : diginc/pi-hole
::    NEW IMAGE : pihole/pihole
:: In order to get the latest updates 
:: please update your image references
:: ::: ::: ::: ::: ::: ::: ::: ::: :::
'

:: ::: ::: ::: ::: ::: ::: ::: ::: :::
:: Image moved / deprecation notice
::    OLD IMAGE : diginc/pi-hole
::    NEW IMAGE : pihole/pihole
:: In order to get the latest updates 
:: please update your image references
:: ::: ::: ::: ::: ::: ::: ::: ::: :::

  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [✓] Status: Retrieval successful

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [✓] Status: Retrieval successful

  [i] Target: sysctl.org (hosts)
  [✓] Status: Retrieval successful

  [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_ad.txt)
  [✓] Status: Retrieval successful

  [i] Target: hosts-file.net (ad_servers.txt)
  [✓] Status: Retrieval successful

  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
  [i] Number of domains being pulled in by gravity: 157595
  [✓] Removing duplicate domains
  [i] Number of unique domains trapped in the Event Horizon: 134366
  [i] Nothing to whitelist!
  [i] Number of regex filters: 0
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter

  [✓] Force-reloading DNS service
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting crond
Starting pihole-FTL (no-daemon)
Starting lighttpd
[services.d] done.
