### ISSUE TITLE
Editor not working in Image

### ISSUE THREAD

**Issue by Jeepersfinest** [pi-hole/docker-pi-hole#311]
This is a... 

- [ ] Request for a new or modified feature
- [x ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I use a Qnap TS-251 with newest firmware.
I want to edit some files in the image (trying to setup "unbound" as mentoined in the FTL-Docu).
Every editor "nano, vi, vim" will not start.
After "sudo vi" the terminal stops, no output, blinking cursor.

Any Ideas?

Best regards
Christian 

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. sudo vi ...
2. sudo nano ...
3. sudo vim ...
4. 

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Qnap 4.3.4.0644
* Docker Version: Container-Station 1.8.3103
* Hardware architecture: x86

**Comment by diginc** [comment]
This is a problem with docker in general and common in many images you may want to customize.  

You need to treat it as a stripped down debian server and install these things your self by running `apt-get update` and `apt-get install vim` or which ever apps you need.

**Comment by Jeepersfinest** [comment]
Thanks!
Okay, to clarify: i installed all editors without any problems. Stretch is uptodate, too.
But problems still there. :-(

**Comment by diginc** [comment]
The unbound setup guide was written for native Pi-hole, not docker Pi-hole :(

I've been thinking I should get around to testing it as some point.  Just to confirm, are you using [this guide](https://docs.pi-hole.net/guides/unbound/)?

Upon reviewing that, I can say for sure it will probably not work due to the fact docker uses s6 based services and it is using the unbound systemd service towards the very end.

**Comment by Jeepersfinest** [comment]
yes, i used this guide.

Without any editor i stopped at
Editing /etc/unbound/unbound.conf.d/pi-hole.conf: 
Just after installing it.

Thanks for your support!

**Comment by Jeepersfinest** [comment]
Only as an idea:
What about to preinstall all 3 options (unbound, DNS over HTTPS and OpenVpn) in this image?

**Comment by fxhx** [comment]
If you want unbound, add a unbound container.

**Comment by diginc** [comment]
I'm going to go ahead and close this and open a new issue asking for an example unbound docker-compose.  It's a pretty straight forward addition.
