### ISSUE TITLE
Possible to run without setting a server IP?

### ISSUE THREAD

**Issue by ndarilek** [pi-hole/docker-pi-hole#316]
This is a... 

- [ ] Request for a new or modified feature
- [x ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I'm using a Resin OS hotspot on an RPi as my main router. I'd like to run pihole directly on this Pi, disabling Resin's local dnsmasq and letting Pihole manage it.

But the external IP doesn't make much sense in this scenario, because my external IP is dynamically assigned by my ISP.

Is it possible to launch this container without setting a ServerIP? Or, at the very least, can I have it update my ServerIP based on changes to the IP of my remote interface, or set it to a dynamic DNS entry that is kept updated with my current IP?

## Expected Behavior

I should be able to run this on my router directly, as I've done with the non-Dockerized version.

## Actual Behavior

The docs indicate that ServerIP is required.

## Possible Fix

Take the IP directly from an interface, resetting it when the interface changes, or take it by resolving a DNS entry that is kept updated.

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture:

**Comment by diginc** [comment]
I had this on my internal backlog for a different reason.

The new default [BLOCKINGMODE=NULL setting](https://docs.pi-hole.net/ftldns/blockingmode/) doesn't set require ServerIP anymore, I just hadn't gotten around to the test re-writing / updating to cover the 4 different blocking modes.

The current required ServerIP behavior should only really apply if `BLOCKINGMODE=IP`

> Or, at the very least, can I have it update my ServerIP based on changes to the IP of my remote interface, or set it to a dynamic DNS entry that is kept updated with my current IP?

If you're wanting the IP Blocking mode (block pages) behavior instead of the NULL default, you could setup a script to constantly check your DynamicDNS, and if it has changed then run a script to modify the ServerIP setting in Pi-hole's configs.

**Comment by ndarilek** [comment]
Cool, so what happens if I just don't set it?

I'm asking rather than trying myself because my network has been broken 
for most of the day, so I gave up on Rasbian and tried Resin. Now things 
seem to be working, but I'm going to have to disable Resin's dnsmasq to 
get this working, which risks triggering more network failures. So I'd 
like to know if it will work and just warn me, or if it will not start 
up and claim the variable is required. :)

Thanks for the quick response.

**Comment by diginc** [comment]
ServerIP required by the container's startup scripting still, so it'd error out if not set.  

But setting ServerIP to '0.0.0.0' imitates the new Pi-hole v4.0 FTLDNS default blocking mode 'NULL'.  The link to the Pi-hole blocking mode settings has full details on the different blocking modes: https://docs.pi-hole.net/ftldns/blockingmode/

**Comment by ndarilek** [comment]
OK, I misunderstood this. In the docs I read "external IP" as "the IP assigned by my ISP". I think maybe "the IP at which you plan to access the server" might be better phrasing. I set this to 192.168.0.1, and things partially work.

I'll think about wording and submit a PR, unless you have other ideas. Thanks!

**Comment by diginc** [comment]
> "server's external IP" - the readme's ServerIP description

I can see that'd be easy to be confused by that wording.  

> "the IP at which you plan to access the server"

That is correct.

"The LAN* IP of your docker host" is how I often think about it.    Does that make sense too?

*WAN/Internet facing Pi-holes are strongly discouraged
