### ISSUE TITLE
/opt/pihole/chronometer.sh: line 246: route: command not found

### ISSUE THREAD

**Issue by itsthejb** [pi-hole/docker-pi-hole#319]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Trying to run the chronometer with `docker exec pi-hole /usr/local/bin/pihole -c -e` throws the error:

```
/opt/pihole/chronometer.sh: line 246: route: command not found
TERM environment variable not set.
|¯¯¯(¯)_|¯|_  ___|¯|___        Core: v4.0| ¯_/¯|_| ' \/ _ \ / -_)        Web: v4.0|_| |_| |_||_\___/_\___|        FTL: v4.0 ——————————————————————————————————————————————————————————
  Hostname: xxxx(Debian Stretch 9)
    Uptime: 2 days, 15:46:20
 Task Load: 0.03 0.07 0.12     (Active: 0 of 25 tasks)
 CPU usage: 0%                 (4x 3.2 GHz @ 301k)
 RAM usage: 56%                (Used: 9 GB of 15 GB)
 HDD usage: 8%                 (Used: 60 GB of 782 GB)
  LAN addr: 192.168.178.22     (Gateway: )
   Pi-hole: Active             (Blocking: 134762 sites)
 Ads Today: 9%                 (Total: 1694 of 18981)
Local Qrys: 9%                 (4 DNS servers)
   Blocked: xxxx
Top Advert: xxxx
Top Domain: xxx
Top Client: xxxx
```

## Expected Behavior

Chronometer works as if was installed locally (not Docker). 

## Actual Behavior

Chronometer doesn't appear to work.

## Possible Fix

Probably the image needs the `net-tools` package installed?
## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Install image as usual (otherwise working fine)
2. `docker exec pi-hole /usr/local/bin/pihole -c -e`

## Debug steps I have tried

```
root@pi-hole:/usr/bin# apt-get install net-tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  net-tools
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 248 kB of archives.
After this operation, 963 kB of additional disk space will be used.
Err:1 http://deb.debian.org/debian stretch/main amd64 net-tools amd64 1.60+git20161116.90da8a0-1
  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/n/net-tools/net-tools_1.60+git20161116.90da8a0-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
root@pi-hole:/usr/bin# exit
exit
```

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture: 

Image latest version, Centos 7.4, Docker version 18.06.0-ce, build 0ffa825

**Comment by chris400** [comment]
Cannot confirm. chronometer works.
Pi-hole Version v4.3.2 Web Interface Version v4.3.2 FTL Version v4.3.1
Debian 9
docker 19.03.5 CE

**Comment by itsthejb** [comment]
Closing: I moved to installing on a Raspberry Pi anyway
