### ISSUE TITLE
Thee admin interface of the webpanel shows binary code

### ISSUE THREAD

**Issue by Jimmy89** [pi-hole/docker-pi-hole#324]
This is a... 

- [ ] Request for a new or modified feature
- [X ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I am running docker on a Raspberry PI 3 ARM. I am using the latest version and haven't changed anything. When I open up the admin interface I get the following screen:
![Screenshot](https://user-images.githubusercontent.com/6030968/44604371-fc79f300-a7e5-11e8-8c6d-bd77aa2f7ea6.png)

Some pages (like whitelist) do not even provide an interface and only binary code. I guess PHP is not being compiled somehow. I have been trough all the logs, but I cannot find any error. The DNS server works, it is only the admin interface that has issues.

The way I initialize the docker image:
```
#!/bin/bash
IMAGE=${1:-'pihole/pihole:v4.0_armhf'}
NIC=${2:-'eth0'}
IP=$(ip addr show "$NIC" | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
#IP_LOOKUP="$(ip route get 8.8.8.8 | awk '{ print $NF; exit }')" # May not work for VPN / tun0
#IPv6_LOOKUP="$(ip -6 route get 2001:4860:4860::8888 | awk '{ print $10; exit }')" # May not work for VPN /
#tun0 IP="${IP:-$IP_LOOKUP}" # use $IP, if set, otherwise IP_LOOKUP IPv6="${IPv6:-$IPv6_LOOKUP}" # use $IPv6, if set, otherwise IP_LOOKUP

# Default ports + daemonized docker container
docker run -p 53:53/tcp -p 53:53/udp -p 80:80 \
  --network="host" \
  --cap-add=NET_ADMIN \
  -e ServerIP="$IP" \
  -e IPv6="False" \
  -e TZ='Europe/Amsterdam' \
  -e DNS1="127.0.10.1#1053" \
  -e DNS2="127.0.10.2#1054" \
  -e WEBPASSWORD="{PASSWORD}" \
  -v /home/jimmy/pihole/adlists.list:/etc/pihole/adlists.list:z \
  -v /home/jimmy/pihole/blacklist.txt:/etc/pihole/blacklist.txt:z \
  -v /home/jimmy/pihole/whitelist.txt:/etc/pihole/whitelist.txt:z \
  -v /home/jimmy/pihole/local.list:/etc/pihole/local.list:z \
  -v /var/log/pihole.log:/var/log/pihole.log:z \
  -v /var/log/pihole-FTL.log:/var/log/pihole-FTL.log:z \
  -v /home/jimmy/pihole/dnsmasq.d/02-dnscrypt.conf:/etc/dnsmasq.d/02-dnscrypt.conf:z \
  --restart=unless-stopped \
  --name pihole \
  -d "$IMAGE"
```

## Steps to Reproduce and debugging done

1. Start docker with the script shown above.
2. Go to the /admin page, login.
3. Weird binary shows up. 

## Debug steps I have tried

- [ X] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [X ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Fedora 27 ARM
* Docker Version: 1.13.1
* Hardware architecture: Raspberry PI 3 ARM (NOT the ARM64 version)

**Comment by diginc** [comment]
Still experiencing this issue?
