### ISSUE TITLE
Automatic Update Blocklists doesn´t work

### ISSUE THREAD

**Issue by DocUltra** [pi-hole/docker-pi-hole#326]
I have the docker installed on a qnap, but the automatic update blocklist doesn´t work.
I check the date of the files in etc/pihole, but the date was too old, when i update it manually then the date will be updated?

**Comment by nxadm** [comment]
Only if changes happened. It's not always the case. The webinterface shows if something changed:
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [✓] Status: Retrieval successful

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [✓] Status: No changes detected
...

**Comment by DocUltra** [comment]
But via webinterface the file date will be updated and apparently via automatic the date won´t be updated?

**Comment by nxadm** [comment]
@DocUltra I don't know. I would need to check that. I don't think most list are updated daily. Check the logs to verify.

**Comment by DocUltra** [comment]
Which logs do you mean, there is only the query log on the webinterface? Same behavior the lists haven´t been updated yet?

**Comment by AlTalai** [comment]
I had the same issue because I was using Safari browser , when I changed to chrome I was I was able to block 
 
Try with chrome probably it will work
