### ISSUE TITLE
Feature request to add frame options as docker env variable

### ISSUE THREAD

**Issue by oohlaf** [pi-hole/docker-pi-hole#327]
This is a... 

- [x] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
I would like to embed the pi.hole/admin interface in an iframe inside Home Assistant. But the "X-Frame-Options" => "DENY" inside lighttpd conf is preventing this.
I can't override it in external.conf as it won't allow a duplicate setting.

Can this be added as a env variable that replaces the setting during docker start?

**Comment by diginc** [comment]
Have you tried using a volume to overwrite the lighttpd conf?

**Comment by oohlaf** [comment]
Yes that would be one way to do it, but wouldn't it be nicer to be able to control it with a variable? That way any improvements to the main config would be kept on new releases without having to manually merge files.

**Comment by diginc** [comment]
I suppose it's not too difficult to add `sed -i '/X-Frame-Options/d' /etc/lighttpd/lighttpd.conf` controlled by an environment variable.

Until that happens, you could make a persistent customization that always runs on boot by adding the `sed` command to a bash script which is then volume mounted into the startup auto executed scripts folder.  `-v <your-script.sh>:/etc/cont-init.d/10-my-prestart-script.sh`

**Comment by Toxblh** [comment]
So real work solution 

1. Create a file `allow-iframe.sh` on host machine 
```shell
#!/usr/bin/with-contenv bash

# Remove header
sed -i '/X-Frame-Options/d' /etc/lighttpd/lighttpd.conf

# We stop it, watchdog will restart it with our conf
/etc/init.d/lighttpd stop
```

2. When you will start your docker image need to add a volume
`... -v </path/to/allow-iframe.sh>:/etc/cont-init.d/21-allow-iframe.sh`
21 - because we have 20-start.sh which replace lighttpd.conf to new. And that is cause why need to restart the lighttpd service

**Comment by shanehughes1990** [comment]
file would be owned by my user as its part of the git pull to that device, I am running OpenMediaVault so essentially debian 9, I will try to chown file to root and see what happens at work rn.

**Comment by Nosirus** [comment]
I can't do it too, the docker restarts endlessly (unraid)

**Comment by kamikaze2112** [comment]
@shanehughes1990 

> I have tried this fix multiple times with the same result @Toxblh, I am likely just missing something but I get permission denied when the script try's to run, this is my compose file for pihole
> 
>     volumes:
>        - pihole_config:/etc/pihole/
>        - pihole_dnsmasq.d:/etc/dnsmasq.d/
>        - ./config/allow-iframe.sh:/etc/cont-init.d/21-allow-iframe.sh
>     networks:
>       - ext_net
> ```

idk if it's just a typo or not, but take out the leading . on the line for the shell script and try that.  you're not executing it from that line, you're simply copying it to the container (if I understand this correctly, i'm still pretty new to docker) and then it runs in order because of the 21.  I setup this shell script in a config folder on the host and restarted the container using portainer, after adding this to the volume section and it worked a treat.  make sure you've chmodded the script so that it's executable as well.  

<img width="966" alt="Screen Shot 2019-10-10 at 10 23 53 AM" src="https://user-images.githubusercontent.com/22285554/66587749-48057280-eb48-11e9-878c-78e64ebe277a.png">

**Comment by tommyalatalo** [comment]
Seconding this, an environment variable for setting this would be great.

**Comment by guice** [comment]
FYI, you can add this to your `external.conf` to overwrite the default setting:
```
$SERVER["socket"] == ":443" {
    $HTTP["url"] =~ "^/admin/" {
          # Allow framin  (for my home-assistant)
          setenv.set-response-header += (
             "X-Frame-Options" => "Allow"
          )
    }
}
```

I have this with SSL. Should work if you change it to :80. I don't know lighttpd well enough to know of the $HTTP will work outside of the server block (didn't test it).

Add that to `external.conf` and mount it on start: 

```
   volumes: 
       - my-external.conf:/etc/lighthttpd/external.conf
```

It's a better solution than script using `sed`.

**Comment by ipatalas** [comment]
@guice as long as your answer is really great it doesn't work very well. 
Current Pi-Hole runs on Lighttpd **1.4.45** and _setenv.set-response-header_ is supported since **1.4.46** (!). So close... _add-response-header_ on the other hand throws an error because there's a duplicate.

**Comment by guice** [comment]
> @guice as long as your answer is really great (outside of Pi-Hole context) it doesn't work very well.
> Current Pi-Hole runs on Lighttpd **1.4.45** and _setenv.set-response-header_ is supported since **1.4.46** (!). So close... _add-response-header_ on the other hand throws an error because there's a duplicate.

😬

Sorry. I'm using a local-install of Pihole on RasPi. I didn't even look at lighttpd versions. This is the method I'm using there, but admittedly, it's lighttpd 1.4.53.

I just connected dots from there: external.conf is meant for external configurations, and you can mount it directly via docker. Didn't even think the `set-response-header` wouldn't work within the docker version due to _one_ (minor) version number. Sorry. :(

**Comment by ipatalas** [comment]
No worries, it's not your fault. It's really good, clean, solution. It just needs some time before we can use it 🙃 

In the meantime I think I need to fall back to mounting entire lighttpd.conf.

**Comment by diamant-x** [comment]
Hi, just dropping an idea. As this is a long-standing issue (2 years!), while the environment variables might take longer to be reworked, could the DENY value be changed to SAMEORIGIN, so that at least we can iframe it inside the same homeassistant docker site? Or is there any drawback to not use sameorigin either?
Thanks.

**Comment by jglezp** [comment]
> FYI, you can add this to your `external.conf` to overwrite the default setting:
> 
> ```
>     $HTTP["url"] =~ "^/admin/" {
>           # Allow framing  (for my home-assistant)
>           setenv.set-response-header += (
>              "X-Frame-Options" => "Allow"
>           )
>     }
> ```
> 
> Add that to `external.conf` and mount it on start:
> 
> ```
>    volumes: 
>        - my-external.conf:/etc/lighthttpd/external.conf
> ```
> 
> It's a better solution than script using `sed`.

I did it, but it logs me off after loging in, any solution on that?

**Comment by scobby** [comment]
> > FYI, you can add this to your `external.conf` to overwrite the default setting:
> > ```
> >     $HTTP["url"] =~ "^/admin/" {
> >           # Allow framing  (for my home-assistant)
> >           setenv.set-response-header += (
> >              "X-Frame-Options" => "Allow"
> >           )
> >     }
> > ```
> > 
> > 
> > Add that to `external.conf` and mount it on start:
> > ```
> >    volumes: 
> >        - my-external.conf:/etc/lighthttpd/external.conf
> > ```
> > 
> > 
> > It's a better solution than script using `sed`.
> 
> I did it, but it logs me off after loging in, any solution on that?

correct Docker-compose Volume Path is:
`volumes: 
      - ./my-external.conf:/etc/lighttpd/external.conf
`

**Comment by STaRDoGG** [comment]
If you use Nginx to reverse proxy a quick  fix would be to add this line to it's location block:

`proxy_hide_header X-Frame-Options;`

**Comment by PromoFaux** [comment]
> Current Pi-Hole runs on Lighttpd **1.4.45** and setenv.set-response-header is supported since 1.4.46 (!)

At this moment in time its:

```
root@222b35f401b9:/# lighttpd -v
lighttpd/1.4.53 (ssl) - a light and fast webserver
```

So you should be good to go

There are still a few things to look at around env vars before we can think about looking at this, but it is probably worth noting that `lighttpd` will be dropped in the future with Pi-hole 6.0 (no ETA) - so not 100% sure it's worth the work for this particular use case which has a perfectly adequate workaround in using `external.conf` for now

**Comment by maraid** [comment]
I'm leaving this here for anyone that finds this solution later. You need to mount the .conf file to /etc/lighttpd/conf-enabled as mentioned in [release 23.01](https://github.com/pi-hole/docker-pi-hole/releases/tag/2023.01)

**Comment by Def3nder** [comment]
tried the solution mentioned by the @pralor-bot and it actually fixes a part of the problem: the PiHole UI is displayed in the iframe now (inside the home assistand GUI).

However loggin in does not work - the login-screen will be displayed over and over again.

Does anyone has a suggestion ?
