### ISSUE TITLE
Error when changing ownership of lighttpd folder

### ISSUE THREAD

**Issue by skoeber** [pi-hole/docker-pi-hole#330]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

My pi-hole instance worked for weeks without any problems. Today I wanted to recreate the container for some testing. Unfortunately the creation of a fresh container fails. The container terminates automatically. At the moment I have no idea how to get the pi-hole docker running again.

## Expected Behavior

Successful startup.

## Actual Behavior

It seems that the setup process fails when setting up the internal webserver. I used PH_VERBOSE=1 to get more information about the issue.

See the relevant log:
```
+ sed -i '/^server=@DNS1@/d' /etc/dnsmasq.d/01-pihole.conf                                                                                                          
+ [[ '' != '' ]]                                                                                                                                                    
+ sed -i '/^server=@DNS2@/d' /etc/dnsmasq.d/01-pihole.conf                                                                                                          
+ sed -i 's/^#conf-dir=\/etc\/dnsmasq.d$/conf-dir=\/etc\/dnsmasq.d/' /etc/dnsmasq.conf                                                                              
+ [[ true == false ]]                                                                                                                                               
+ sed -i 's/^#log-queries/log-queries/' /etc/dnsmasq.d/01-pihole.conf                                                                                               
+ [[ ! -f /etc/pihole/pihole-FTL.conf ]]                                                                                                                            
+ [[ ! -f /etc/pihole/regex.list ]]                                                                                                                                 
+ [[ true == true ]]                                                                                                                                                
+ [[ ! -d /etc/lighttpd ]]                                                                                                                                          
+ [[ -f /etc/lighttpd/lighttpd.conf ]]                                                                                                                              
+ mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.orig                                                                                                   
+ cp /etc/.pihole/advanced/lighttpd.conf.debian /etc/lighttpd/lighttpd.conf                                                                                         
+ [[ -f /var/www/html/pihole/custom.php ]]                                                                                                                          
+ mkdir -p /var/run/lighttpd                                                                                                                                        
+ chown www-data:www-data /var/run/lighttpd                                                                                                                         
chown: changing ownership of '/var/run/lighttpd': Operation not permitted                                                                                           
[cont-init.d] 20-start.sh: exited 1.                                                                                                                                
[cont-finish.d] executing container finish scripts...                                                                                                               
[cont-finish.d] done.                                                                                                                                               
[s6-finish] syncing disks.                                                                                                                                          
[s6-finish] sending all processes the TERM signal.                                                                                                                  
[s6-finish] sending all processes the KILL signal and exiting.  
```

## Possible Fix

no idea

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. I simplified the run command, pulled the latest image, re-created a lot of times - all without any positive result
2. Simple run command: `docker run -d --name pihole1 -p 8888:80 -e ServerIP="192.168.178.5" -e IPv6="False" -e WEBPASSWORD="" -e PH_VERBOSE=1 pihole/pihole:latest`
3. Same command on my MAC host works.
4. 

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Context and extra information

Host system is a QNAP TS-251+ NAS (x86) with latest and previous firmware (I did a downgrade just because of this issue).

## Your Environment 

* Docker Host Operating System and OS Version: QNAP NAS (v4.3.4.0675) with Container Station
* Docker Version: 17.09.1-ce
* Hardware architecture: x86

**Comment by nxadm** [comment]
It looks like your container has no right to change the dir ownership. Is the directory mounted as a volume?

**Comment by skoeber** [comment]
Thanks for the fast reply!
My last try with a very simple run command has no volume mounts:
`docker run -d --name pihole1 -p 8888:80 -e ServerIP="192.168.178.5" -e IPv6="False" -e WEBPASSWORD="" -e PH_VERBOSE=1 pihole/pihole:latest`
I'm absolutly helpless at them moment. Using the web without pi-hole feels wrong.

**Comment by diginc** [comment]
Does QNAP have SELinux enabled or any other security features that may
impact permissions being modified?

**Comment by morris-j** [comment]
I had this exact issue with my Qnap NAS where it seems something got corrupted with either a QTS update or Container Station update. The solution was to delete Container Station and all data for it. After that setting up the pihole docker image worked perfectly.

**Comment by skoeber** [comment]
Thanks for the comments.
I don't know if there's SELinux enabled on the QNAP devices. If so, it must already be enabled when I installed pi-hole the first time because I didn't change any option about this.
I deleted Container Station and all of it's data several times without any positive effect. Other containers (e.g. openHAB2) works without problems. It seems my problem is QNAP specific. So, I will post my problem in the QNAP forums and comment here when there are any news.

**Comment by skoeber** [comment]
After another hour of install/uninstall/upgrade/whatever of Container Station on my QNAP, the pi-hole container now runs as espected. So it's verified that the Container Station caused the problem with the first startup of pi-hole.
Thanks again for your input on this topic.
