### ISSUE TITLE
no ipv6 (on my qnap)

### ISSUE THREAD

**Issue by overfl0w72** [pi-hole/docker-pi-hole#340]
Hello everyone, I have just installed the image on my QNAP NAS. So far it runs fine, but unfortunately my pihole gets no ipv6 address, although this is both in the container station and in the pihole configuration on.

Unfortunately, I do not know any further and would be grateful for any help.

best regards

**Comment by statte** [comment]
Hi, 
As far as I know , QNAP has no support for IPV6 in docker.
I have the same concern, This is why i disable the use of ipv6 in the docker command.

I Hope this helps

regards

**Comment by mil1i** [comment]
I just tested in the new pihole/pihole image, if I add a custom IPv6 DNS I cannot resolv any domains. I did not experience this with the diginc/pi-hole image.

I'm running on CentOS 7.5.

**Comment by ikkerus** [comment]
Same issue here. It seems the qnap container station doesn't support IPv6 (docker itself does). You can use portainer.io instead on a different machine (at least version 1.2.4) to run pi-hole on docker with ipv6 support. I don't see any other solution so far...
