### ISSUE TITLE
"latest" tag running on a raspberry pi

### ISSUE THREAD

**Issue by grolongo** [pi-hole/docker-pi-hole#345]
I have a question that's not related to a bug but something I don't understand.

I'm running a Raspberry Pi 3 B+ with Raspbian, armv7l.
Docker version is 18.06.1-ce.

On the docker hub page the tag "latest" says it's compatible for x86 architecture.

latest / v4.0 | x86 | Debian x86 image, container running lighttpd and dnsmasq
-- | -- | --

Out of curiosity I tried running it on my RPi and I had no problem so far (admin panel is opening fine and adlists are successfully loaded).

![dockerpiholelatest](https://user-images.githubusercontent.com/34292770/47226557-26ecc480-d3c1-11e8-8b90-87f658dcf128.jpg)

My question now is is this normal or should I expect problems later?
Shouldn't I have used `pihole/pihole:4.0.0-1_armhf` for my specific architecture?

**Comment by diginc** [comment]
The readme needs updated to indicate certain tags support all architectures now.

**Comment by grolongo** [comment]
fair enough, I'm closing.
