### ISSUE TITLE
Odd attempt to get local IP in docker_run.sh

### ISSUE THREAD

**Issue by dovecode** [pi-hole/docker-pi-hole#346]
[This line](https://github.com/pi-hole/docker-pi-hole/blob/c2903241859d6794a377d2a1d5dd4d94d4421f03/docker_run.sh#L3) of `docker_run.sh` appears to be an attempt to get the local v4 IP, but I don't see how it ever would. The piped awk script is:

    { print $NF; exit }

This looks like an attempt to print the number of fields in the first record of input. However, even this is wrong, as the "number of fields" special variable in awk should not be preceded by a dollar sign. As a result, the original line:

    ip route get 8.8.8.8 | awk '{ print $NF; exit }'

Will always return `0`, the awk variable $NF has not been initialized and wil default to `0`.

The really weird thing is that the [IPv6 script on the following line](https://github.com/pi-hole/docker-pi-hole/blob/c2903241859d6794a377d2a1d5dd4d94d4421f03/docker_run.sh#L4) would work if adjusted for IPv4, e.g.:

     ip route get 8.8.8.8 | awk '{for(i=1;i<=NF;i++) if ($i=="src") print $(i+1)}'

I can make a pull request for this change if you like, but I'm not sure if I understand the intention of that line given that it is so ... odd, and that it appears to have been there for [three months](https://github.com/pi-hole/docker-pi-hole/blame/c2903241859d6794a377d2a1d5dd4d94d4421f03/docker_run.sh#L3).

**Comment by diginc** [comment]
```
# Raw output for reference
$ ip route get 8.8.8.8
8.8.8.8 via 192.168.41.1 dev eth0  src 192.168.41.55
    cache
# Print last field of line (NF or num of fields)
$ ip route get 8.8.8.8 | awk '{ print $NF; exit }'
192.168.41.55
# Same as print string / column 7
$ ip route get 8.8.8.8 | awk '{ print $7; exit }'
192.168.41.55
```

**Comment by diginc** [comment]
The for loop is more universal so it probably would be smart to use it in the readme/docker_run.sh script.

**Comment by dovecode** [comment]
Yes. This is my ip route output on Ubuntu:

    $ ip route get 8.8.8.8
    8.8.8.8 via 192.168.1.1 dev enp2s0 src 192.168.1.111 uid 1000
        cache
