### ISSUE TITLE
IPv6 on Raspberry Pi doesn't work (RTNETLINK)

### ISSUE THREAD

**Issue by grolongo** [pi-hole/docker-pi-hole#354]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
When running the container with IPv6 enabled, IP variables for IPv4 and IPv6 are fetched correctly but the docker logs show an error with RTNETLINK which stops the deployment of the container.

## Expected Behavior
The container should deploy fully and go in healthy state.

## Actual Behavior
Checking what's happening with `docker logs pihole` this is what I get (password and IPv6 are scrambled):

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
 ::: Starting docker specific setup for docker pihole/pihole
Assigning random password: snB2vbVJ
RTNETLINK answers: Network is unreachable
ERROR: ServerIPv6 Environment variable (2a01:bc1c:4e4:p700:514e:20sp:3b27:3m8e) doesn't appear to be a valid IPv6 address
  TIP: If your server is not IPv6 enabled just remove '-e ServerIPv6' from your docker container
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

## Possible Fix
Maybe Docker isn't IPv6 enabled?

## Steps to Reproduce and debugging done
Here is my docker run:

```
local IP
IP="$(ip route get 8.8.8.8 | awk '{ print $NF; exit }')"

local IPv6
IPv6="$(ip -6 route get 2001:4860:4860::8888 | awk '{for(i=1;i<=NF;i++) if ($i=="src") print $(i+1)}')"

docker run -d \
          --name pihole \
          -p 53:53/tcp -p 53:53/udp \
          -p 80:80 \
          -p 443:443 \
          -v pihole:/etc/pihole \
          -v dnsmasq.d:/etc/dnsmasq.d \
          -e ServerIP="${IP}" \
          -e ServerIPv6="${IPv6}" \
          -e DNS1="1.1.1.1" \
          -e DNS2="1.0.0.1" \
          --dns=127.0.0.1 --dns=1.1.1.1 \
          --restart=always \
          pihole/pihole:latest
```

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

Tried to add `--cap-add=NET_ADMIN` as seen in a topic even though I don't need port 67 for DHCP server but without success.

Also running with only IPv4, so just by removing `-e ServerIPv6="${IPv6}"` works fine without any problem.

Just to show IPv6 connection works on the host machine:
```
grolongo@raspberry3:~ $ ping6 -c 10 2001:4860:4860::8888
PING 2001:4860:4860::8888(2001:4860:4860::8888) 56 data bytes
64 bytes from 2001:4860:4860::8888: icmp_seq=1 ttl=59 time=7.39 ms
64 bytes from 2001:4860:4860::8888: icmp_seq=2 ttl=59 time=6.35 ms
64 bytes from 2001:4860:4860::8888: icmp_seq=3 ttl=59 time=5.66 ms
64 bytes from 2001:4860:4860::8888: icmp_seq=4 ttl=59 time=5.75 ms
64 bytes from 2001:4860:4860::8888: icmp_seq=5 ttl=59 time=5.81 ms
64 bytes from 2001:4860:4860::8888: icmp_seq=6 ttl=59 time=5.67 ms
64 bytes from 2001:4860:4860::8888: icmp_seq=7 ttl=59 time=5.69 ms
64 bytes from 2001:4860:4860::8888: icmp_seq=8 ttl=59 time=5.76 ms
64 bytes from 2001:4860:4860::8888: icmp_seq=9 ttl=59 time=5.71 ms
64 bytes from 2001:4860:4860::8888: icmp_seq=10 ttl=59 time=5.74 ms

--- 2001:4860:4860::8888 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9016ms
rtt min/avg/max/mdev = 5.664/5.957/7.392/0.518 ms
```

## Your Environment 

* Hardware model: Raspberry Pi 3 B+
* Hardware architecture: ARMv7
* OS version: Raspbian 9 (stretch)
* Kernel version: 4.14.71-v7+
* Docker Version: 18.06.1-ce

**Comment by diginc** [comment]
You may need to setup ipv6 in the docker daemon first : https://docs.docker.com/config/daemon/ipv6/

**Comment by grolongo** [comment]
I found out the IPv6 variable in the script is returning a **global IPv6 public address**.
Shouldn't it return a **unique local address** instead (equivalent to private IPv4 addresses), so any address with the prefix `fd00::/8`?

Just like the IPv4 variable is returning a private IP like `192.168.1.10`, I thought IPv6 variable should do the same. Maybe the variable is broken for me and I will hardcode it but wan't to make sure first since I'm new to IPv6.

**Comment by grolongo** [comment]
Alright sorry for delay, found out that the main devs chose to prioritize GUA -> LUA -> LL for IPv6 selection.

Also to fully enable IPv6 for the docker0 interface (so without using --net=host) you must create/edit `/etc/docker/daemon.json` and specify the `fixed-cidr-v6`. That's not included in the original Docker docs linked above. So:

```
{
  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64"
}
```
followed by `systemctl restart docker`.
