### ISSUE TITLE
Pihole not resolving local hostnames for dashboard (or rather at all)

### ISSUE THREAD

**Issue by TrashCanMan** [pi-hole/docker-pi-hole#356]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
After reinstalling pihole (and upgrading to 4.0) i see on the dashboard ip addresses instead of hostnames, its more a convenience thing since everything else works, its blocking ads correctly, answering dns requests to clients correctly, everything works exept this...i have conditional forwarding active and pointing to my router and i have the 3 options on advanced dns settings disabled, also i have set to show everything on the privacy setting...as suggested [here](https://discourse.pi-hole.net/t/how-do-i-show-hostnames-instead-of-ip-addresses-in-the-dashboard/3530/12) i did a pair of digs from another device on my network but im not sure if this can help at all:
```
pi@valenpina:~ $ dig omv

; <<>> DiG 9.10.3-P4-Raspbian <<>> omv
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64851
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;omv.                           IN      A

;; ANSWER SECTION:
omv.                    0       IN      A       192.168.1.250

;; Query time: 6 msec
;; SERVER: 192.168.1.250#53(192.168.1.250)
;; WHEN: Mon Oct 29 08:51:30 -03 2018
;; MSG SIZE  rcvd: 48

pi@valenpina:~ $ dig DESKTOP-CMJK3LN

; <<>> DiG 9.10.3-P4-Raspbian <<>> DESKTOP-CMJK3LN
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49234
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;DESKTOP-CMJK3LN.               IN      A

;; ANSWER SECTION:
DESKTOP-CMJK3LN.        0       IN      A       192.168.1.214

;; Query time: 7 msec
;; SERVER: 192.168.1.250#53(192.168.1.250)
;; WHEN: Mon Oct 29 08:52:03 -03 2018
;; MSG SIZE  rcvd: 60

```

omv is the pihole1 SBC hostname and the other one is a w10 computer, also did the same from inside the pihole1 docker container:

```
root@rock64:/# dig DESKTOP-CMJK3LN

; <<>> DiG 9.10.3-P4-Debian <<>> DESKTOP-CMJK3LN
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 5459
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;DESKTOP-CMJK3LN.               IN      A

;; AUTHORITY SECTION:
.                       10611   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2018102900 1800 900 604800 86400

;; Query time: 11 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Mon Oct 29 08:57:28 -03 2018
;; MSG SIZE  rcvd: 119
```

Im totally noob on this but if i read that correctly pihole is asking directly outside and simply ignoring the conditional forwarding setting, the weird thing starts here, i have 2 piholes over dockers on 2 different rock64s both over very different OSs and , both set up exactly the same in regards to the container creation and pihole settings and on the second one i get this:
```
root@LibreELEC:/# dig DESKTOP-CMJK3LN

; <<>> DiG 9.10.3-P4-Debian <<>> DESKTOP-CMJK3LN
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40035
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;DESKTOP-CMJK3LN.               IN      A

;; ANSWER SECTION:
DESKTOP-CMJK3LN.        0       IN      A       192.168.1.214

;; Query time: 4 msec
;; SERVER: fd04:9daa:45af::250#53(fd04:9daa:45af::250)
;; WHEN: Mon Oct 29 09:06:34 -03 2018
;; MSG SIZE  rcvd: 60
```

on this second pihole i get what appears to be a correct answer but only for ipv4, i see ipv6 shown all over the dashboard, only difference between the 2 setups that i can think of is that the first pihole have a gid/uid set as a normal user (there is no file permission issues that i can see, options are saved, no error messages at all and i use the same user for other dockers and all work perfectly) and on the second pihole is set to run as root

## Expected Behavior
Hostnames shown on the dashboard for clients instead of ip addresses (both ipv4 and ipv6)

## Actual Behavior
IPs shown on the dashboard, both ipv4 and ipv6

## Possible Fix
No idea where is even the problem.

## Steps to Reproduce and debugging done
I have 2 piholes over dockers on 2 very different OSs and both do the same

e.g. your docker run command, pages to visit, CLI commands you ran
1.
2. 
3. 
4. 

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Context and extra information
Both dockers where created recently and both where completelly wiped and volume data too just in case, also both are set to only handle dns and my router do dhcp, on my router i have dhcp giving the pihole ip addresses (ipv4x2+ipv6x2) correctly for dns

Its not really a gamebreaking bug, just a convenience issue

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture: 
pihole1 is a pihole/pihole:v4.0_aarch64 docker over openmediavault on a rock64 sbc, pihole2 is a pihole/pihole:v4.0_aarch64 docker over libreelec on a rock64 sbc 
the docker creation command i use is:
```
docker create --name pihole \
--restart=unless-stopped \
--net=host \
-p 53:53/tcp -p 53:53/udp \
-p 67:67/udp \
-p 80:80 \
-p 443:443 \
-v /folderonthehost/:/etc/pihole/ \
-v /folderonthehost/dnsmasq.d/:/etc/dnsmasq.d/ \
-e ServerIP=192.168.1.251 \
-e ServerIPv6=fd04:9daa:45af::251 \
-e TZ=America/Argentina/Buenos_Aires \
-e WEBPASSWORD=mypassword \
-e PGID=0 -e PUID=0 \
--cap-add=NET_ADMIN \
pihole/pihole:v4.0_aarch64
docker start pihole
```
both use the same, only change are the ip addresses and pgid/puid, this second one is using root.
Assuming this is a weird permissions issue regarding network on the first pihole, why the second one dont resolve ipv6s either? can the ipv6 issue on the second pihole be an issue on my router? i can run the first pihole on root for a while if need be but IMHO if there is some permission issue it needs to be corrected
Again i repeat, this is simply an annoyance, not a gamebreaking problem...

**Comment by TrashCanMan** [comment]
Some extra bit of information:
- pihole1 hosts "uname -a": Linux rock64 4.4.138-rk3328 #14 SMP Mon Jul 16 10:45:46 PDT 2018 aarch64 GNU/Linux
- pihole2 hosts "uname -a": Linux LibreELEC 4.4.154 #1 SMP Sun Oct 7 09:36:03 BST 2018 aarch64 GNU/Linux
ask for anything else you need to debug this

**Comment by TrashCanMan** [comment]
I keep searching stuff and i found [https://github.com/kubernetes/kubernetes/issues/64864](this), can this be related? maybe on dockers we need to use --dns instead of using the internal conditional forwarding?

**Comment by diginc** [comment]
The fix to this is usually pass in `--dns 127.0.0.1 --dns 1.1.1.1` to your docker run.

PHP runs off what docker has set in it's docker run, and if it sets localhost then it properly knows about local hostnames.

**Comment by TrashCanMan** [comment]
Im a bit noob to all networking but shoundnt i set --dns to my router instead to 127.0.0.1? i can try both tho, thats what a docker is for, just dump it and create a new one...also, see at the second code block from my post (dig inside pihole1), why is it asking directly outside for the host? is that normal?

**Comment by TrashCanMan** [comment]
For some reason i had a "nameserver 1.1.1.1" on top of /etc/resolvconf/resolv.conf.d/head on the host wich in fact translated to that nameserver on /etc/resolv.conf wich translated on the nameserver on the pihole, i really have no remote idea of how that ended there but now its resolving again (exept temp ipv6 addresses, thats another can of worms)...the only thing i have installed related to dhcp/dns so im going to pay attention where that came from, for now im closing this, sorry for wasting your time.
