### ISSUE TITLE
Please release docker image with Pi-hole v4.1

### ISSUE THREAD

**Issue by Haxy89** [pi-hole/docker-pi-hole#369]
There is new version of Pihole: https://github.com/pi-hole/pi-hole/releases/tag/v4.1
The latest tag is for v4.0

**Comment by ase1590** [comment]
Seconding this.

**Comment by diginc** [comment]
I have #370 ready to go for review/testing.  I pushed the [dev image tag](https://hub.docker.com/r/pihole/pihole/tags/) with 4.1 which needs a little more testing before going to the prod tag.  There was one known issue with arm images (#361) I should really make sure is taken care of before releasing to production.

**Comment by ase1590** [comment]
Just pulled in `pihole/pihole:dev` from dockerhub on my x86_64 plex server.
Docker Digest: `sha256:5ff26713b6a9e81754c46a6e6de7e57376449b1d546a2588cd2ffd231a9db844`

The web interface still reports that it's 4.0...

**Comment by diginc** [comment]
Ah I think the deploy script has '4.0' hard coded in it and needs updated too, my bad.

**Comment by diginc** [comment]
OK I believe the real v4.1 is pushed to the dev tag now.

**Comment by ase1590** [comment]
I'm happy to report the dev tag now pulls in pihole 4.1! :)
________________________________

**Comment by yamlCase** [comment]
Can we also get the 'latest' tag to point to 4.1?

**Comment by ase1590** [comment]
@yamlCase please note that the `latest`tag is for working production releases. As this image is not yet widely tested, its likely not suitable just yet to move it from `dev` to `latest`.

**Comment by BigSnicker** [comment]
This build is problematic for me, unlike earlier versions... the install goes cleanly and works well, but it always breaks after a container restart.

Any chance there's word on 4.1.1 to see if that helps?

**Comment by diginc** [comment]
This release is done.  Anyone looking for resolution to issues take a look at the top of the readme : https://github.com/pi-hole/docker-pi-hole/blob/dev/README.md#docker-pi-hole-v411-important-upgrade-notes

I'll duplicate this data in the github release's notes when I merge dev to master tonight and cut a release with these improved checks for misconfiguration
