### ISSUE TITLE
pihole -up not disabled?

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/docker-pi-hole#371]
This is a... 

- [ ] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

As noted in this [thread on reddit](https://www.reddit.com/r/pihole/comments/a4pbxg/pihole_v41_is_now_available/ebgok2n/), it seems that users are able to run `pihole -up` from within the container. Something I thought was disabled by #203. Code still seems to be the same from that, so maybe it never worked! 

## Expected Behavior

`pihole -up` should be disabled

## Actual Behavior

User claims they were able to run `pihole -up`. (not tested myself)

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Enter Container
2. run `pihole -up`
3. 
4. 

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture:

**Comment by diginc** [comment]
Resolved
