### ISSUE TITLE
How to prevent reset /etc/hosts file after container restart?

### ISSUE THREAD

**Issue by Haxy89** [pi-hole/docker-pi-hole#376]
I edited /etc/hosts file in container to make client names resolution in my local network
Everytime i restart host or container the /etc/hosts file is cleared.

**Comment by diginc** [comment]
Docker  manages /etc/hosts to set whatever your container name and they want you to add custom host entries through their command line arguments.  Take a look at this section of their documentation : https://docs.docker.com/engine/reference/run/#managing-etchosts

[I also have a demo of this in my docker-compose example](https://github.com/pi-hole/docker-pi-hole/blob/master/doco-example.yml#L24)

**Comment by Mcat12** [comment]
`local.list` is not meant to be modified, as it is overwritten periodically.

**Comment by dajappie** [comment]
Yes @Mcat12 you’re right, better use a custom list like explained here https://discourse.pi-hole.net/t/howto-using-pi-hole-as-lan-dns-server/533

**Comment by Haxy89** [comment]
@dajappie your link redirect to post from 2016, what is the best solution to use domain for local lan host for pi-hole v4? Added hosts to /etc/hosts doesn't not work
