### ISSUE TITLE
Using pi-hole as LAN DNS server - Pi-hole on docker

### ISSUE THREAD

**Issue by Haxy89** [pi-hole/docker-pi-hole#385]
Docker run command:
```
sudo docker run --dns=127.0.0.1 --dns=1.1.1.1 -d -p 53:53/tcp -p 53:53/udp -p 80:80 -p 443:443 --add-host bitwarden:192.168.0.19 --name Pihole --hostname RaspberryPi --restart=unless-stopped -v /home/pi/pihole/data/:/etc/pihole/ -v /home/pi/pihole/dns/:/etc/dnsmasq.d/ -e DNS1=1.1.1.1 -e DNS2=1.0.0.1 -e ServerIP=192.168.0.20 -e TZ=Europe/Warsaw -e WEBPASSWORD=password -e IPv6=False pihole/pihole:latest
```
Using this to add host:
```
--add-host bitwarden:192.168.0.19
```

Tried ping command from windows but cant find host:

```
ping bitwarden
```

In pihole dashboard I can see bitwarden instead of server IP (192.168.0.19)

**Comment by diginc** [comment]
Sounds like you did it right.

What does a direct lookup against the pihole say?  `dig bitwarden @localhost +short` or `dig bitwarden @192.168.0.20 +short`

**Comment by diginc** [comment]
Also did you ever try a custom list instead of --add-host from your old issue?  https://discourse.pi-hole.net/t/howto-using-pi-hole-as-lan-dns-server/533

It is a more flexible solution, you can add hosts to a custom list and reload DNS from inside the container without having to re-create the entire container like -add-host makes you do.

**Comment by Haxy89** [comment]
How to prevent deleting custom list after pihole container recreation?
It is not a solution if I need to create custom list and add all entries everytime I recreate a container

**Comment by diginc** [comment]
Use docker volumes like in the readme example

https://github.com/pi-hole/docker-pi-hole#running-pi-hole-docker

> Volumes are stored in the directory $DOCKER_CONFIGS and are recommended for persisting data across docker re-creations for updating images. The IP lookup variables may not work for everyone, please review their values and hard code IP and IPv6 if necessary.
