### ISSUE TITLE
pihole-4.1.1 docker hub image has FTL_CMD set to debug

### ISSUE THREAD

**Issue by tanglebones** [pi-hole/docker-pi-hole#388]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Image runs but stdout get flooded with debug output. Changing FTL_CMD to no-daemon causes FTL to stop and get stuck in a restart loop. Using 4.0.0-1 works fine.

## Expected Behavior

stdout shouldn't be flooded with output (including all queries) by default, and no-daemon mode shouldn't be stuck in a stop/start loop.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. tried -f -- -d for FTL_CMD as well, still stuck in a loop
2. 
3. 
4. 

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: synology diskstation 6.2.1-23823u4
* Docker Version:  17.05.0-ce, build 9f07f0e-synology
* Hardware architecture: x86

**Comment by diginc** [comment]
I went ahead and release `dev` tag to latest along with the appropriate warnings about new required arguments at the top of the readme.
