### ISSUE TITLE
How do I disable DNS resolution so I can install the pihole container on Ubuntu 18.04 (server)

### ISSUE THREAD

**Issue by FutureTense** [pi-hole/docker-pi-hole#396]
This is a... 

- [ ] Request for a new or modified feature
- [ X] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I'm using docker-compose to try and build the container.  I'm getting the following error:

>Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:53088->[::1]:53: read: connection refused

I followed [this guide](https://www.smarthomebeginner.com/run-pihole-in-docker-on-ubuntu-with-reverse-proxy/) which says that you have to disable the host's DNS resolver since it will interfere with PiHole, which I can confirm did happen.  So I disabled the by:

```
sudo systemctl disable systemd-resolved.service
sudo systemctl stop systemd-resolved.service
```
I'm running Ubuntu 18.04 (server version) which doesn't have NetworkManager installed, so I wasn't able to follow the guide's instructions to modify `NetworkManager.conf` to include:

```
[main]
plugins=ifupdown,keyfile
dns=default
```
## Expected Behavior

The container should be built.
## Actual Behavior

If I don't disable systemd-resolved, I get an error message about a conflict on port 53.  If I do disable systemd-resolved I get:
>Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:53088->[::1]:53: read: connection refused

## Steps to Reproduce and debugging done

[my docker-compose.yaml](https://pastebin.com/VtiSFVEm)

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Ubuntu 18.04 (server) 
* Docker Version: 18.09.1
* Hardware architecture:  Windows NUC running VirtualBox

**Comment by diginc** [comment]
Just disabling your systemd resolver is enough since you're running server.  Looks like docker is still pointed at  your local systemd resolver resulting in DNS errors though.

You may have to edit your /etc/default/docker.json to have `{ "dns": [ "1.1.1.1" ] }` to provide a working resolver while you setup Pi-hole for the first time.  After Pi-hole is working and setup to auto-start you can probably remove that again, though you may have to test restarting your server to be sure that it starts up without issue.

**Comment by FutureTense** [comment]
Hey!  That kind of worked.  The container was created, though it’s looping on starting and stopping pihole.  Let’s leave this open because it might be related.  I’ll get some logs soon.

**Comment by FutureTense** [comment]
This is the [log](https://pastebin.com/1ySEdLib).  As you can see, it looks like PiHole is stuck on a loop of starting/stopping.  It also appears DNS is not running (line 46).  Any idea as to what I'm doing wrong?

**Comment by diginc** [comment]
You're likely missing the new required NET_ADMIN setting : https://github.com/pi-hole/docker-pi-hole#docker-pi-hole-v411-important-upgrade-notes

**Comment by DerRockWolf** [comment]
For anyone who stumbles across this issue:
View the "Installing on Ubuntu" part of the README.md [(link)](https://github.com/pi-hole/docker-pi-hole/#installing-on-ubuntu).

This issue is solved with the provided documentation.
