### ISSUE TITLE
Cannot seem to pass environment variables. What am I doing wrong?

### ISSUE THREAD

**Issue by DieKatzchen** [pi-hole/docker-pi-hole#399]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
I enter the incantation below
`docker run pihole/pihole -e ServerIP=192.168.1.2 -e TZ=America/New_York -e WEBPASSWORD=****** --net=host --restart=unless-stopped -v /mnt/nfs-1/pihole/:/etc/pihole -v /mnt/nfs-1/dnsmasq.d:/etc/dnsmasq.d --name pihole`

## Expected Behavior
pihole should run

## Actual Behavior
`ERROR: To function correctly you must pass an environment variables of 'ServerIP'`

`Assigning random password: sQ6vbxpe`

## Possible Fix
somehow I'm passing environment variables wrong, but I can't figure out how. I've tried no quotes, single quotes, double quotes...

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.
2. 
3. 
4. 

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture:

**Comment by dschaper** [comment]
Anything after the image name on the command line is considered to be an argument to the container's runtime. Your command line is passing everything as a string to pi-hole which doesn't do anything with them.

Move the image name to the end of the line and pass the arguments to the docker engine instead.

`docker run -e ServerIP=192.168.1.2 -e TZ=America/New_York -e WEBPASSWORD=****** --net=host --restart=unless-stopped -v /mnt/nfs-1/pihole/:/etc/pihole -v /mnt/nfs-1/dnsmasq.d:/etc/dnsmasq.d --name pihole pihole/pihole`

**Comment by DieKatzchen** [comment]
That fixed it. Should have known it was something stupid. Thanks a lot!

**Comment by dschaper** [comment]
Glad it's working for you now.
