### ISSUE TITLE
Setting "AAAA_QUERY_ANALYSIS=no" doesn't seem to have any effect

### ISSUE THREAD

**Issue by Loader23** [pi-hole/docker-pi-hole#400]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Setting AAAA_QUERY_ANALYSIS=no in the pihole-FTL.conf does not seem to work correctly, i can still see AAAA queries
## Expected Behavior

AAAA queris should be hidden in the log
## Actual Behavior

They are not
## Possible Fix

Its almost the same Issue like https://github.com/pi-hole/FTL/issues/250 but now for docker 
## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Iam using a QNAP, if thats important
2. 
3. 
4. 

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: QNAP
* Docker Version:
* Hardware architecture:  x86

**Comment by DL6ER** [comment]
I just confirmed that this is working for me on the latest version of FTL. We haven't touched the code in a while. Please ensure that somewhere in your `/var/log/pihole-FTL.conf`, you indeed see something like:
```
[...]
[2019-01-19 19:51:47.175] Starting config file parsing (/etc/pihole/pihole-FTL.conf)                                                                                                                               
[2019-01-19 19:51:47.175]    SOCKET_LISTENING: only local                                                                                                                                                          
[2019-01-19 19:51:47.175]    AAAA_QUERY_ANALYSIS: Hide AAAA queries
[...]
```

**Comment by DL6ER** [comment]
Please double-check your `pihole-FTL.conf` as
```
AAAA_QUERY_ANALYSIS: Show AAAA queries
```
shows that the setting wasn't correctly read in your case.

I will check these FATAL messages. They are not *that* fatal as they appear like, but nevertheless, they should not be there.

**Comment by Loader23** [comment]
I have found the issue and its a weird one.^^ 
After seeing the logs I wondered why the config file loaded some parts of it. I used pihole on my Raspberry before switching to docker and had the same conf file:

`AAAA_QUERY_ANALYSIS=no`
`MAXDBDAYS=0`
`DBFILE=`

But this one works:

`MAXDBDAYS=0`
`DBFILE=`
`AAAA_QUERY_ANALYSIS=no`

Didn't thought that the order matters, is that normal?

**Comment by DL6ER** [comment]
> Didn't thought that the order matters, is that normal?

No. I just tried to run FTL with the exact same conf file as you posted (`AAAA_QUERY_ANALYSIS=no` as first entry) and everything works as expected. Note that the parser is very sensitive and even an added space after the `no` will cause FTL to skip this option.

Works:
`AAAA_QUERY_ANALYSIS=no`

Does not work:
`AAAA_QUERY_ANALYSIS=no `
(note the extra space)

**Comment by DL6ER** [comment]
Just a quick note: https://github.com/pi-hole/FTL/pull/469 will make the config file parser become robust against leading/trailing spaces in config files.

**Comment by Loader23** [comment]
While the order wasn't that important for me I really wanted to know now what was causing that.^^ 
And I think I found the cause. First of all, there really was no space in the conf file, at least not a visible one. Iam using WinSCP and always edit files with Notepad++. Using this combo for years now without Problems - except now. Even filling the config per hand did not work. 
I then used the simpler built-in editor and now its working :-) I bet https://github.com/pi-hole/FTL/pull/469 will prevent that in the future.

So thanks alot for your help and have a nice day ;-)

**Comment by DL6ER** [comment]
@Loader23 Thanks for your reply. I have never used Win-machines myself and tend to forget about the strange extra line endings they use. Yes, this will be solved by my PR.

And the FATAL messages are fixed by https://github.com/pi-hole/FTL/pull/470
