### ISSUE TITLE
Accessing the web-ui without having to append /admin

### ISSUE THREAD

**Issue by FutureTense** [pi-hole/docker-pi-hole#401]
I've created a pihole docker container that I can access via [http://192.168.1.50:8182/admin](http://192.168.1.50:8182/admin), as well as [https://pihole.example.com/admin](https://pihole.example.com/admin).  However, I'd like to be able to access it via [https://pihole.example.com](https://pihole.example.com).  Is there a way to modify my docker-compose code to handle this?

&#x200B;

      pihole:
        container_name: pihole
        domainname: docker
        hostname: pihole
        image: pihole/pihole:latest
        ports:
          - '53:53/tcp'
          - '53:53/udp'
          - '8182:80'
          - '8183:443'
        restart: unless-stopped
        cap_add:
          - NET_ADMIN
        volumes:
          - ${USERDIR}/docker/pihole/pihole:/etc/pihole
          - ${USERDIR}/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
        environment:
          - ServerIP=${SERVER_IP}
          - PROXY_LOCATION=pihole
          - VIRTUAL_HOST=pihole.${DOMAINNAME}
          - VIRTUAL_PORT=80
          - TZ=${TZ}
          - WEBPASSWORD=${PIHOLE_PASSWORD}
          - DNS1=1.1.1.1
          - DNS2=1.0.0.1
        labels:
          - "traefik.enable=true"
          - "traefik.backend=hole"
          - "traefik.port=80"
          - "traefik.frontend.rule=HostRegexp:pihole.${DOMAINNAME},{catchall:.*}"
          - "traefik.frontend.priority=1"
          - traefik.frontend.headers.SSLRedirect=true
          - traefik.frontend.headers.STSSeconds=315360000
          - traefik.frontend.headers.browserXSSFilter=true
          - traefik.frontend.headers.contentTypeNosniff=true
          - traefik.frontend.headers.forceSTSHeader=true
          - traefik.frontend.headers.SSLHost=${DOMAINNAME}
          - traefik.frontend.headers.STSIncludeSubdomains=true
          - traefik.frontend.headers.STSPreload=true
          - traefik.frontend.headers.frameDeny=true
    

&#x200B;

**Comment by awmath** [comment]
You have to add the "AddPrefix:/admin" modifier to your traefik.frontend.rule [See the docs](https://docs.traefik.io/basics/#modifiers).

**Comment by tekand** [comment]
If somebody is looking for the current docs for @awmath's answer: https://docs.traefik.io/v2.0/middlewares/addprefix/

**Comment by devantler** [comment]
The mentioned approach only works in some cases. After logging in, the user is redirected to `/admin`, which will result in the path `/admin/admin` behind the scenes. To fix the issue strip prefix can be used along with add prefix to ensure the path is always `/admin/something`

```yml
    labels:
      ...omitted for brevity...
      - traefik.http.routers.pihole.middlewares=strip-prefix,add-prefix
      - traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/admin
      - traefik.http.middlewares.add-prefix.addprefix.prefix=/admin
      ...omitted for brevity...
```
