### ISSUE TITLE
Variable for static /etc/hosts entries in pihole docker

### ISSUE THREAD

**Issue by Exist2Resist** [pi-hole/docker-pi-hole#406]
This is a... 

- [ x] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
I would like to add a static entry to the /etc/hosts file in the pihole docker container.
Since pihole is the only dhcp server on my network and runs on unraid, I can not ping my unraid server even when I add it to static dhcp entry.

## Expected Behavior
Would like a variable where I can have persistence in the docker container when it is updated or new image pulled. 
Perhaps multiple hosts entries.

## Actual Behavior
If I add the entry manually upon update or new image pull the hosts entries are removed. 

## Possible Fix
Custom variable added on docker creation that allows to...
echo "192.168.1.151 tower" >> /etc/hosts

## Steps to Reproduce and debugging done
I run this in Unraid using a custom template I created.
https://github.com/Exist2Resist/docker-templates/blob/master/exist2resist/pihole.xml 

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 
* Docker Host Operating System and OS Version: Unraid 6.6.6
* Docker Version: 18.06.1-ce
* Hardware architecture: x86

**Comment by arnemoor** [comment]
My solution is simple: Create a hosts file on the host (outside the container) and do a read-only bind mount of that file to /etc/hosts inside the container.

**Comment by diginc** [comment]
Have you tried this instead ? https://docs.docker.com/engine/reference/run/#managing-etchosts ?

**Comment by arnemoor** [comment]
At least under QNAP Container Station the --add-host option is not passed through to the GUI, I'm not sure for RAID. 

At least Portainer offers this under the menus "Create container" and "Duplicate / Edit" via Advanced container settings / Network / Hosts file entries

**Comment by diginc** [comment]
GUIs should support what docker officially supports rather than containers having to re-invent a wheel to do something docker does out of the box.

Rather than /etc/hosts you can add custom entires through /etc/dnsmasq.d/ folder instead.

```
  address=/custom.local/127.0.0.1
  address=/custom.local/::1
```

**Comment by Exist2Resist** [comment]
If I were to put those entries into the dnsmasq.d folder do I add them to **04-pihole-static-dhcp.conf** file?

**Comment by eiddor** [comment]
@Exist2Resist This did the trick here: https://discourse.pi-hole.net/t/howto-using-pi-hole-as-lan-dns-server/533

**Comment by d-ognyanoff** [comment]
docker run -d \
--name pihole \
--cap-add NET_ADMIN \
-p 53:53/tcp \
-p 53:53/udp \
-p 80:80 \
-e DNS1=127.0.0.1 \
-e DNS2=1.1.1.1 \
-v /etc/localtime:/etc/localtime \
-v /storage/.config/pihole/:/etc/pihole \
-v /storage/.config/pihole/dnsmasq.d/:/etc/dnsmasq.d \
-v /storage/.config/pihole/html/:/var/www/html/html/ \

**-v /etc/hosts:/etc/hosts \**

-h $(cat /etc/hostname) \
-e ServerIP=$(ip route get 127.0.0.1 | awk '{ print $NF; exit }') \
-e WEBPASSWORD=password \
--restart=unless-stopped \
pihole/pihole:latest

**Comment by frakman1** [comment]
@Exist2Resist I too am using PiHole in my Unraid server and have a custom hosts file. I use the volume mount approach that @arnemoor suggested. See my post [here](https://forums.unraid.net/topic/48744-support-pihole-for-unraid-spants-repo/?do=findComment&comment=812693) on the Unraid forum for details:

**Comment by Exist2Resist** [comment]
> @Exist2Resist I too am using PiHole in my Unraid server and have a custom hosts file. I use the volume mount approach that @arnemoor suggested. See my post [here](https://forums.unraid.net/topic/48744-support-pihole-for-unraid-spants-repo/?do=findComment&comment=812693) on the Unraid forum for details:

Thanks for that I have figured it out since. 
Cheers.
