### ISSUE TITLE
Default number of PHP children

### ISSUE THREAD

**Issue by peleion** [pi-hole/docker-pi-hole#407]
This is a... 

- [x] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Simple request - thanks for the great docker that works flawlessly for me. I've run pi-hole on a vm for quite some time and set the default number of PHP children (php-cgi) to 1 with no noticeable performance decrease. Just might free up some resources that the host could use and make it leaner 

## Expected Behavior

php-cgi spawns 1 child by default

## Actual Behavior

php-cgi spawns 5 children by default

## Possible Fix

Change default # of children to 1 in ini file

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture:

**Comment by fabiodcorreia** [comment]
I also want to optimize this, specially for systems like Raspberry Pi it's useful to optimize this configurations. It's possible to make the customization at the moment?
