### ISSUE TITLE
--env DNS2=no still uses 8.8.4.4

### ISSUE THREAD

**Issue by musicsnob** [pi-hole/docker-pi-hole#408]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

--env DNS2=no doesn't seem to work as documented.

## Expected Behavior

When running the image with --env DNS2=no, Pihole should not use a second DNS server.

## Actual Behavior

Even with DNS2=no, queries are still sent to 8.8.4.4, shown in the `pihole -t` log.

## Steps to Reproduce and debugging done

```
docker run --name=pihole --hostname=pihole \
--network=dns-net \
--publish=53:53/tcp \
--publish=53:53/udp \
--publish=80:80 \
--publish=443:443 \
--cap-add=NET_ADMIN \
--dns=127.0.0.1 \
--dns=1.1.1.1 \
--env IPv6=false \
--env ServerIP=192.168.1.13 \
--env TZ=America/New_York \
--env WEBPASSWORD=xxyyzz \
--env DNS1=192.168.1.13#50053 \
--env DNS2=no \
--log-driver=json-file \
--restart=unless-stopped \
--detach=true \
pihole/pihole:latest
```

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 
This is may be related to #281. 

## Your Environment 

* Docker Host Operating System and OS Version: ESXi 6.7 and Photon OS 2.0
* Docker Version: 17.06.0-ce
* Hardware architecture: `Linux photon 4.9.53-5.ph2-esx #1-photon SMP Thu Oct 26 02:44:24 UTC 2017 x86_64 Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz GenuineIntel GNU/Linux`

**Comment by diginc** [comment]
Interesting, this passed automated testing here, maybe the test is somehow invalid?

https://github.com/pi-hole/docker-pi-hole/blob/master/test/test_bash_functions.py#L58

**Comment by musicsnob** [comment]
During setup/installation, are the DNS servers defaulted to 8.8.8.8 and 8.8.4.4, and then overwritten by the environment variables? So, if DNS1=1.2.3.4 and DNS2=no, PIHOLE_DNS_1=1.2.3.4 but PIHOLE_DNS_2 remains unchanged and =8.8.4.4. 

https://github.com/pi-hole/docker-pi-hole/blob/7ec893ae3f6c3a310c4cf7695b5e5266ae9de26f/install.sh#L28 perhaps?

**Comment by diginc** [comment]
Please try out `pihole/pihole:dev` docker image to see if it resolves this issue.

**Comment by WTell** [comment]
I'm experiencing this exact issue on Pi-hole v5.2.4. Was it resolved?

**Comment by WTell** [comment]
For those who come here through a Google search:

Setting DNS2 to the same value as DNS1 is a workaround that seems to address this, while suboptimal.
