### ISSUE TITLE
Default adlists not written on container startup

### ISSUE THREAD

**Issue by bassopenguin** [pi-hole/docker-pi-hole#419]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

When not mounting a docker volume for `/etc/pihole`, the default adlists are not written into  `/etc/pihole/adlists.list`.
When setting default adlists up, the file is `touch`-ed before calling `installDefaultBlocklists`. `installDefaultBlocklists` checks whether the file exists prior to writing the defaults:
```shell
    # If this file exists, we avoid overriding it.
    if [[ -f "${adlistFile}" ]]; then
        return;
    fi
```
This causes no adlists to be installed by default.

## Expected Behavior

Calling `installDefaultBlocklists` should create and write defaults into `/etc/pihole/adlists.list`.

## Actual Behavior

No adlists are installed by default. 0 blocked domains
## Possible Fix

Remove empty string redirection into `adlistFile` prior to calling `installDefaultBlocklists`:
```shell
echo "::: ${FUNCNAME[0]} now setting default blocklists up: "
echo "::: TIP: Use a docker volume for ${adlistFile} if you want to customize for first boot"
> "${adlistFile}" # TODO REMOVE THIS LINE
installDefaultBlocklists
```

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Pulled `latest` tag
2. Removed existing containers
3. Started new container without mounted volume for `/etc/pihole`
```shell
docker run -d \
    --name pihole \
    -p 53:53/tcp -p 53:53/udp \
    -p 80:80 \
    -p 443:443 \
    -e ServerIP="${IP}" \
    -e DNS1=1.1.1.1 \
    -e DNS2=1.0.0.1 \
    -e WEBPASSWORD="$WEBPASSWORD" \
    --cap-add=NET_ADMIN \
    --dns=127.0.0.1 --dns=1.1.1.1 \
    -v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/" \
    --restart=unless-stopped \
    pihole/pihole:latest
```
4. Observed _0 blocked domains_
5. Created directory to mount `/etc/pihole`
6. Removed existing container
7. Started new container
```shell
docker run -d \
    --name pihole \
    -p 53:53/tcp -p 53:53/udp \
    -p 80:80 \
    -p 443:443 \
    -e ServerIP="${IP}" \
    -e DNS1=1.1.1.1 \
    -e DNS2=1.0.0.1 \
    -e WEBPASSWORD="$WEBPASSWORD" \
    --cap-add=NET_ADMIN \
    --dns=127.0.0.1 --dns=1.1.1.1 \
    -v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/" \
    -v "${DOCKER_CONFIGS}/pihole/:/etc/pihole/" \
    --restart=unless-stopped \
    pihole/pihole:latest
```
8. Still observed _0 blocked domains_
9. Wrote default domains into `/path/to/pihole/adlists.list`
10. Removed existing container
11. Started new container with mounted volume
```shell
docker run -d \
    --name pihole \
    -p 53:53/tcp -p 53:53/udp \
    -p 80:80 \
    -p 443:443 \
    -e ServerIP="${IP}" \
    -e DNS1=1.1.1.1 \
    -e DNS2=1.0.0.1 \
    -e WEBPASSWORD="$WEBPASSWORD" \
    --cap-add=NET_ADMIN \
    --dns=127.0.0.1 --dns=1.1.1.1 \
    -v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/" \
    -v "${DOCKER_CONFIGS}/pihole/:/etc/pihole/" \
    --restart=unless-stopped \
    pihole/pihole:latest
```
12. Observed `::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))`
13. Identified possible cause in `bash_functions.sh`

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Context and extra information

Without a fix, no domains are blocked by default on first install.

## Your Environment 

* Docker Host Operating System and OS Version: raspian stretch lite
* Docker Version: Docker version 18.09.0, build 4d60db4
* Hardware architecture:  RPi 3 B+

**Comment by diginc** [comment]
I noticed this same problem while working last night #418.  Will dig into it more tonight.

**Comment by diginc** [comment]
Should be working on the latest `dev` image from last night.  You were right, the seeding of empty list file was breaking the install default list function.

**Comment by kibuan** [comment]
I just resolved this issue on my Pihole docker running on my Synology by using the "dev" version a few days ago. I have just upgraded to version 4.2.2 by pulling the "latest" version, and now I experience this problem again.
