### ISSUE TITLE
Block unwanted DNS clients

### ISSUE THREAD

**Issue by henning-krause** [pi-hole/docker-pi-hole#423]
The other day I saw a client making thousands of DNS queries to my pi-hole. I'd like to block clients if I know its not legit traffic. 

My question is: Is there a way to block an IP address? I tried

```bash
iptables -A INPUT -s <ipaddress> -j DROP
```
on the computer running the docker container, but that didn't work.

**Comment by dschaper** [comment]
Docker opens a new chain that forwards all traffic that is targeted for the IP of the container on the overlay network. Try inserting your rule in to the `DOCKER-USER` chain instead. (Insert in to position 1, do not append as there is an existing rule to RETURN all traffic, and if you append the rule it will never be hit.)
