### ISSUE TITLE
Pihole Container keeps restarting

### ISSUE THREAD

**Issue by Jezz3** [pi-hole/docker-pi-hole#424]
When i wanted to update my pihole container i deleted the old one and run the script docker_run.sh
The script exits with" Timed out waiting for Pi-hole start start, consult check your container logs for more info (`docker logs pihole`)"My docker logs pihole shows:

> `[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] 01-resolver-resolv: applying... 
> [fix-attrs.d] 01-resolver-resolv: exited 0.
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 20-start.sh: executing... 
> stty: 'standard input': Inappropriate ioctl for device
>  ::: Starting docker specific setup for docker pihole/pihole
> OK: Checks passed for /etc/resolv.conf DNS servers
> 
> nameserver 127.0.0.1
> nameserver 1.1.1.1
> stty: 'standard input': Inappropriate ioctl for device
>   [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u1
> 
>   [i] Installing configs from /etc/.pihole...
>   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
> cp: cannot create regular file '/etc/dnsmasq.d/01-pihole.conf': Structure needs cleaning
>   [i] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf...[cont-init.d] 20-start.sh: exited 1.
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] syncing disks.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting.
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] 01-resolver-resolv: applying... 
> [fix-attrs.d] 01-resolver-resolv: exited 0.
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 20-start.sh: executing... 
> stty: 'standard input': Inappropriate ioctl for device
>  ::: Starting docker specific setup for docker pihole/pihole
> OK: Checks passed for /etc/resolv.conf DNS servers
> `

I mounted /etc/dnsmasq.d/ to /home/pi/pihole/dnsmasq.d/
and /etc/pihole/ to /home/pi/pihole/pihole/
i think the problem has somethin todo with no 01-pihole.conf file in /home/pi/pihole/dnsmasq.d/ but i am no sure and dont know much about this topic. When i run docker ps i see the server restarting about every 1-2 min.
My docker_run.sh

> `
> Default of directory you run this from, update to where ever.
> DOCKER_CONFIGS="/home/pi/pihole/"
> 
> echo -e "### Make sure your IPs are correct, hard code ServerIP ENV VARs if necessary\nIP: ${IP}\nIPv6: ${IPv6}"
> 
> 
> docker run -d \
>     --name pihole \
>     --env-file piholescript.env \
>     -p 53:53/tcp -p 53:53/udp \
>     -p 80:80 \
>     -p 443:443 \
>     --cap-add=NET_ADMIN \
>     -v "${DOCKER_CONFIGS}/pihole/:/etc/pihole/" \
>     -v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/" \
>     -e ServerIP="${IP}" \
>     -e ServerIPv6="${IPv6}" \
>     --restart=unless-stopped \
>     -^-dns=127.0.0.1 --dns=1.1.1.1 \
>     pihole/pihole:latest
> `

This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

**Comment by Jezz3** [comment]
> When i wanted to update my pihole container i deleted the old one and run the script docker_run.sh
> The script exits with" Timed out waiting for Pi-hole start start, consult check your container logs for more info (`docker logs pihole`)"My docker logs pihole shows:
> 
> `[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] 01-resolver-resolv: applying...
> [fix-attrs.d] 01-resolver-resolv: exited 0.
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 20-start.sh: executing...
> stty: 'standard input': Inappropriate ioctl for device
> ::: Starting docker specific setup for docker pihole/pihole
> OK: Checks passed for /etc/resolv.conf DNS servers
> 
> nameserver 127.0.0.1
> nameserver 1.1.1.1
> stty: 'standard input': Inappropriate ioctl for device
> [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u1
> 
> [i] Installing configs from /etc/.pihole...
> [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
> cp: cannot create regular file '/etc/dnsmasq.d/01-pihole.conf': Structure needs cleaning
> [i] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf...[cont-init.d] 20-start.sh: exited 1.
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] syncing disks.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting.
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] 01-resolver-resolv: applying...
> [fix-attrs.d] 01-resolver-resolv: exited 0.
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 20-start.sh: executing...
> stty: 'standard input': Inappropriate ioctl for device
> ::: Starting docker specific setup for docker pihole/pihole
> OK: Checks passed for /etc/resolv.conf DNS servers
> `
> 
> I mounted /etc/dnsmasq.d/ to /home/pi/pihole/dnsmasq.d/
> and /etc/pihole/ to /home/pi/pihole/pihole/
> i think the problem has somethin todo with no 01-pihole.conf file in /home/pi/pihole/dnsmasq.d/ but i am no sure and dont know much about this topic. When i run docker ps i see the server restarting about every 1-2 min.
> My docker_run.sh
> 
> > `
> > Default of directory you run this from, update to where ever.
> > DOCKER_CONFIGS="/home/pi/pihole/"
> > echo -e "### Make sure your IPs are correct, hard code ServerIP ENV VARs if necessary\nIP: ${IP}\nIPv6: ${IPv6}"
> > # Default ports + daemonized docker container
> > # Environment variables for docker can be defined in --env-file .env file
> > docker run -d 
> > --name pihole 
> > --env-file piholescript.env 
> > -p 53:53/tcp -p 53:53/udp 
> > -p 80:80 
> > -p 443:443 
> > --cap-add=NET_ADMIN 
> > -v "${DOCKER_CONFIGS}/pihole/:/etc/pihole/" 
> > -v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/" 
> > -e ServerIP="${IP}" 
> > -e ServerIPv6="${IPv6}" 
> > --restart=unless-stopped 
> > -^-dns=127.0.0.1 --dns=1.1.1.1 
> > pihole/pihole:latest
> > `
> 
> This is a...
> 
>     * [ ]  Request for a new or modified feature
> 
>     * [x]  Issue trying to run the docker image
> 
>     * [ ]  Issue trying to build / test / develop the docker image

**Comment by ViViDboarder** [comment]
Did you resolve this? I'm seeing the same issue.

**Comment by diginc** [comment]
@ViViDboarder please open a new issue using the template and we'll try to help out.
