### ISSUE TITLE
Cannot Access Pi Hole Through Web Browser

### ISSUE THREAD

**Issue by JunkyardCat** [pi-hole/docker-pi-hole#427]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
I am using Ubuntu server 18.04 LTS on a NUC(Intels Mini PC). I have nextcloud snap ver runnning. I am trying to access the web interface but it cant be accessed. keep getting 404 not found.  please see steps below on additional info

## Expected Behavior
shows the Pi Hole console on the web browser

## Actual Behavior
404 Not Found

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Install ubuntu 18.04
2. Install Nextcloud Snap ver
3. Install Docker
4. Install Pi-Hole Docker Version
5. Update Routers DNS to ip address of my NUC not the docker image
6.  change config in /etc/systemd/resolved.conf to DNSStubListener=yes then i restarted performed this 2 command sudo systemctl reload-or-restart systemd-resolved and sudo systemctl reload-or-restart dnsmasq
7. made symlink using this command ln -sv /run/systemd/resolve/resolv.conf /etc/resolv.conf
6. type http://pi.hole/admin in mozilla firefox browser
7. get error message

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:Ubuntu Server 18.04
* Docker Version:Docker version 18.09.2, build 6247962
* Hardware architecture:

**Comment by spuder** [comment]
Did you find a resolution to this?

**Comment by diginc** [comment]
If pi.hole is not working then there are a few steps to debug:

0) Pre-req, always check your docker logs for any startup errors and resolve those first of all.  If things started OK then debug the following too
1) try hitting the docker host by IP address (external IP or 127.0.0.1) to see if docker port forwards are working.  This is assuming you have standard port forwards of `-p 80:80`, form the docker host run : `curl -vL http://<YOUR_IP>`
2) try to do a manual `nslookup` / `dig` against the docker container for pi.hole to see if it is working: `dig pi.hole @<YOUR_IP>`
  - If the lookup is working you shouldn't be having any trouble getting directed to the right IP of your container.  
  - If the previous step is also working then the web interface should load when these 2 things are both working together.
