### ISSUE TITLE
random password is rejected

### ISSUE THREAD

**Issue by cmurf** [pi-hole/docker-pi-hole#428]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Since docker image e0869bf1a536 (4.2.2), more often than not the listed password is rejected by the web interface. I am using the latest docker_run.sh script, only adding `:z` for selinux and changing timezone.

## Expected Behavior

I should be able to login to the web interface.

## Actual Behavior

Wrong password!

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. sudo docker rm pihole
2. sudo ./docker_run.sh
3. Go to web interface, input the password the script provides (which matches what I see with `sudo docker logs pihole`
4. 

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

If I `rm -rf etc-*` the problem doesn't happen. So something is being saved in there that's contributing to this problem. And another regression test is if I use the old password, it still works. The newly generated random password reported by the script doesn't work. So yeah, password is being saved in the volumes.

## Context and extra information

The bug is that the script says the password is Y but it's really X, and it's not really random. It's one time random and then it's assigned, and ends up disagreeing with the startup script's output.

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture: 

docker-1.13.1-65.git1185cfd.fc29.x86_64
4.20.12-200.fc29.x86_64

**Comment by diginc** [comment]
What do your docker logs say about the web password being set?

The only behavior that changed with 4.2.2 is now if you use a volume for /etc/pihole/ it should just say ` ::: Pre existing WEBPASSWORD found` from your previous container creations.

**Comment by stachrom** [comment]
yes  - ::: Pre existing WEBPASSWORD found 

If I like to generate a new random password - could I remove the password line (WEBPASSWORD=xxxxxxxxx) from setupVars.conf ?

**Comment by diginc** [comment]
Yes that is the current procedure to regenerate a new random password.

**Comment by cmurf** [comment]
The log says this:
```
Assigning random password: Mx15U9Gq
stty: 'standard input': Inappropriate ioctl for device
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u1
  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
::: Pre existing WEBPASSWORD found
Docker DNS variables not used
```

But the docker_run.sh says
```
$ sudo ./docker_run.sh
WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
e200f1fcf967cb1066ad4ece5947000fb2c8d01d562c541dd2538a0ecce46b48
Starting up pihole container .......... OK
Assigning random password: OZ2wuKAu for your pi-hole: https:///admin/
```

And that's simply wrong, that random password isn't assigned. The old one is assigned and is the only one that works. Also the script isn't reporting the correct admin page URL, I just noticed that, the old docker_run.sh script showed that correctly.

**Comment by airdrummingfool** [comment]
I just experienced this same issue - I was re-creating the Docker container a bunch of times while ironing out my config, and when it finally came time to login, the most recent "Assigning random password:" log entry did not work. Luckily I had logged the random password each time I created a new container, and was able to use trial-and-error to figure out which one was correct.

It was definitely confusing that a new password was being reported each time but not used, and doubly so because the `docker logs pihole | grep random` command (which is what is recommended by pihole to find your password) did not show the "Pre existing WEBPASSWORD found" log messages.

**Comment by diginc** [comment]
I think "Assigning random password" prints even when a pre existing password is there.  That message should probably actually say 'Generating random password for later assignment'.  

Could you review your full log and see if it also says the message "::: Pre existing WEBPASSWORD found" - which should mean it prevented the actual usage of the randomly generated password.

I'll add in logic to stop printing the 'Assigning random pass' to prevent confusion.

**Comment by BrianLakstins** [comment]
I'm having similar issue.  Each time restarts, assigns a new random password.  Getting error in settings that might be related: 

`PHP error (2): parse_ini_file(/etc/pihole/setupVars.conf): failed to open stream: Permission denied in /var/www/html/admin/settings.php:11 `

Tried setting password in environment variable and it would not be set.
