### ISSUE TITLE
Admin Interface Port Auto Redirect

### ISSUE THREAD

**Issue by xNuno** [pi-hole/docker-pi-hole#430]
This is a... 

- [ X ] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

When open the admin panel using reverse proxy it always tries to change the address from https://piholeadmin.duckdns.org/admin/ to https://piholeadmin.duckdns.org:4865/admin ... If I use other application like grafana it works like charm without always redirecting to app port number.

## Expected Behavior

Open pihole address running on port 4865 but without forcing the url redirection.

## Actual Behavior

Url gets redirect all the time to include the port number. This is the job for the reverse proxy, no need to be forced by pihole.

## Possible Fix

Disable the auto url redirection to include the port number.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Setup DuckDns to point your routers internet IP
2. Setup reverse proxy to look to duckdns URL alias
3. Open URL without port number using https

## Debug steps I have tried

- [ X ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ X ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ X ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ X ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Debian 9
* Docker Version: Lastest
* Hardware architecture:  x86

**Comment by xNuno** [comment]
Anyone?

**Comment by dschaper** [comment]
We don't redirect ports like that, we only use port 80. We also don't ship with an https mechanism. What modifications have you made to the standard docker image and what `docker run` string are you using?

**Comment by xNuno** [comment]
Hi @dschaper ,

Everytime that I open Pi-Hole it's forced to use 4865... What I want it's to use a reverse proxy and avoid this forcing of 4865 on the URL cause reverse proxy is already doing it... something is looking to the URL and force to have 4865 on it...

![2019-03-30 17_44_34-Window](https://user-images.githubusercontent.com/8095169/55279721-87d6dc00-5313-11e9-96db-26101fd3ea70.png)

**Comment by dschaper** [comment]
It's not any configuration that we use or ship. The only configuration files we have are for `lighttpd` on port 80.

**Comment by dschaper** [comment]
And we don't have a `Buy Me A Coffee` button, but I'd like to know where you got this version from and who is using our work for their own?

**Comment by dschaper** [comment]
Looks like that's from https://github.com/hassio-addons/addon-pi-hole

You'll need to ask them for support, we will not.
