### ISSUE TITLE
volume permissions

### ISSUE THREAD

**Issue by isriam** [pi-hole/docker-pi-hole#439]
This is a... 

- [ ] Request for a new or modified feature
- [X ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

with volume mounts to nfs share, even as root getting errors that can't read various dnsmasq.d files.

## Expected Behavior

should run and read setupVars.conf

## Actual Behavior

get error that setupVars.conf unreadable and other java errors in settings.

## Possible Fix

check why root user is unable to read/view files in static volume mappings.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.
2. 
3. 
4. 

## Debug steps I have tried

- x[ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture: 

docker-compose config:

version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Phoenix'
      WEBPASSWORD: 
      DNS1: 68.105.28.11
      DNS2: 1.1.1.1
      ServerIP: 192.168.1.26
      DNSMASQ_USER: root
    volumes:
       - "/mnt/docker/pihole/etc-pihole:/etc/pihole/"
       - "/mnt/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d/"
    dns:
      - 127.0.0.
      - 1.1.1.1
    user: 0:0
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"

**Comment by isriam** [comment]
it works fine when i don't use the nfs mounts.  it also works fine if i use the volumes and run older versions (diginc).

**Comment by diginc** [comment]
I would advise against running old versions as a work around, you may get other bugs. 

Your NFS server side settings are likely causing the problem based off the fact it only breaks when using that.  root squash is the most common NFS permission mangler https://duckduckgo.com/?q=nfs+root+squash you should look into.

It maybe something else but supporting and helping configure file shares is out of scope for Pi-hole.

Running docker as root does not actually change what user the container runs as.  There are non-root users inside the container who need access to files.

**Comment by isriam** [comment]
my nfs is mounted as 1000:1000 and i run all containers as that user.  root would supercede that and i run about 25 other containers as 1000:1000 and as root without problem.  I'm running pihole as root and dnsmasq as root therefore they should be able to edit/view/write all files in this mount, but they are not.  are there other users in the container is set/change?  i think thats the problem, even though i'm setting pihole to user: root and dnsmasq: root it still isn't working.  has nothing to do with my nfs mount, because as stated above, diginc version works just fine reading these mount points.  it only fails on the latest pihole image.

**Comment by diginc** [comment]
Print the process tree which should include users to confirm what user things run as please:

`docker exec pihole ps -efH`

**Comment by isriam** [comment]
Thanks.  Here's the output.  Also for awareness, I created a DHCP static binding, and it created a file in etc-dnsmasq.d called 04-pihole-static-dhcp.conf that is 3-0-0 and then errors in pihole gui.  i edit this file to 733 and pihole gui is content and reads it fine.

jeremy@ubuntu-nms:/mnt/docker/pihole$ docker exec pihole ps -efH
UID        PID  PPID  C STIME TTY          TIME CMD
root      3584     0  8 09:45 ?        00:00:00 ps -efH
root         1     0  0 09:07 ?        00:00:00 s6-svscan -t0 /var/run/s6/services
root        27     1  0 09:07 ?        00:00:00   s6-supervise s6-fdholderd
root      1106     1  0 09:07 ?        00:00:00   s6-supervise lighttpd
root      1110  1106  0 09:07 ?        00:00:00     bash ./run
www-data  1123  1110  0 09:07 ?        00:00:01       lighttpd -D -f /etc/lighttpd/lighttpd.conf
www-data  1151  1123  0 09:07 ?        00:00:00         /usr/bin/php-cgi
www-data  1152  1151  0 09:07 ?        00:00:00           /usr/bin/php-cgi
www-data  1153  1151  0 09:07 ?        00:00:00           /usr/bin/php-cgi
www-data  1154  1151  0 09:07 ?        00:00:00           /usr/bin/php-cgi
www-data  1155  1151  0 09:07 ?        00:00:00           /usr/bin/php-cgi
root      1107     1  0 09:07 ?        00:00:00   s6-supervise cron
root      1114  1107  0 09:07 ?        00:00:00     bash ./run
root      1127  1114  0 09:07 ?        00:00:00       /usr/sbin/cron -f
root      1108     1  0 09:07 ?        00:00:00   s6-supervise pihole-FTL
root      1112  1108  0 09:07 ?        00:00:00     bash ./run
root      1126  1112  0 09:07 ?        00:00:06       pihole-FTL no-daemon

for dhcp static config file:
There was a problem applying your settings.
Debugging information:
PHP error (2): fopen(/etc/dnsmasq.d/04-pihole-static-dhcp.conf): failed to open stream: No such file or directory in /var/www/html/admin/scripts/pi-hole/php/savesettings.php:68

-rw-rw----+ 1 root   root     46 Apr 11 09:48 04-pihole-static-dhcp.conf
-rwxr-xr-x+ 1 root   root   1013 Apr 10 20:01 04-pihole-static-dhcp.conf.bak*

**Comment by diginc** [comment]
As you see there www-data still needs to access the data, running lighttpd as root maybe a hacky work around.  If it works that'd be an interesting approach but I'd prefer to keep permissions one-to-one with normal pi-hole rather than make everything root just because a few users run on NAS volumes without standard linux permission capabilities setup.

**Comment by isriam** [comment]
yep, i figured www-data  was the problem however i'm just comparing to my other containers.  i'd rather run nothing as root, and since the files are readable as 1000:1000 is it possible to change the pid/gid of the pihole container to this?

**Comment by derekoharrow** [comment]
I've just installed this too, and am having the exact same problem. Is it possible to get the container to work with a specified UID/GID?

**Comment by matthewdennett** [comment]
I have the same issues here. I have a bunch of containers running with voolumes mapped to my nas with no issues. 

Did anyone find a nice workaround for this one?

**Comment by radicand** [comment]
I chmodded the share to 33:33 (www-data) on the nfs host, and this resolved the issues for me.
