### ISSUE TITLE
Pi-hole settings lost at docker reboot

### ISSUE THREAD

**Issue by TrapStoner** [pi-hole/docker-pi-hole#441]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

So i have set up docker and pi-hole around 3 days ago. Since then i haven't restarted my pc or docker. Yesterday i spent some time adding more blocklists and everything was fine. I have stopped pi-hole with `docker stop and docker rm` and then starting it again with `docker run` multiple times and haven't got any problems. Until today.... I just restarted my pc, ran pi-hole, opened the dashboard and was about to die. Total queries: 0, Queries blocked: 0, Percent blocked: 0, Domains on blocklist: 112,088 aka default. Tried to log in, but failed (yes ik i should of put my password in the run script lol). After logging in i saw that every setting i had changed has returned to its default value.
## Expected Behavior

Saving settings at docker/windows reboot, so you dont need to reconfigure it every time?
## Actual Behavior

It fails to do the expected behavior
## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Start Docker Desktop
2. Open Powershell
3. Run `docker run -d --name pihole -p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 80:80 -p 443:443 -v "${DOCKER_CONFIGS}/pihole/:/etc/pihole/" -v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/" -e ServerIP=10.0.75.1 --restart=unless-stopped --cap-add=NET_ADMIN --dns=127.0.0.1 --dns=1.1.1.1 pihole/pihole:latest`
4. Stop the container, then resstart docker desktop
5. Voila!

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Windows 10 1809
* Docker Version: 2.0.0.3 (31259)

**Comment by TrapStoner** [comment]
is this getting fixed? i can't use pi-hole until it is.

**Comment by diginc** [comment]
I've never lost data but I don't use windows so that makes me think that could be the key factor to your problem.  Being docker desktop that means it's a VM right?

Did you set DOCKER_CONFIGS variable?  I didn't see you mention your volume data at all, volumes are what preserve your data.  Have you found the location of your volumes on windows and checked those files' modified/creation dates?

Are you familiar with how does docker desktop handle volumes exactly?  There is likely some differentces from standard linux docker which I'm most used to.

**Comment by TrapStoner** [comment]
So first of all i am sorry for the late reply (the past month was busy af for me). Second, yes it's a VM and also no i haven't set any DOCKER_CONFIGS variables. For the volumes, i am not that familiar with docker at all (this is the first time using it) and the only thing i could check is location of the virtual hard drive and creation/modified dates. I mounted it with Ext2 Volume Manager but windows won't open it. So for the dates, the creation date is not changing at all, but the modified one is changing upon closing docker. So i think it is erasing everything upon closing it, because if you dont close docker, pi-hole settings are saved properly no matter what. The problem comes when you close docker.

**Comment by TrapStoner** [comment]
Ok so, idk if using -v "${DOCKER_CONFIGS} is not working properly OR i have to set the DOCKER_CONFIGS variable somewhere, but upon trying -v "pihole/:/etc/pihole/" -v "pihole-dns:/etc/dnsmasq.d/" it worked, it saved the settings! Also (i think it's visible) idk how to make both folders run on the same volume. Trying -v "pihole/dnsmasq/:/etc/dnsmasq.d/" gives `Error response from daemon: create pihole/dnsmasq: "pihole/dnsmasq" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.` Help!

**Comment by nitsmrinal** [comment]
I am using absolute path and it worked for me. -v option is to mount local directory to the container. For example Windows shares are to mounted like  -v //c/dir1/dir1:/mypath/in/container.  for pihole this is my sample run command

```docker run -d --name pihole -p 53:53/tcp -p 53:53/udp -p 80:80 -p 67:67 -p 443:443 -e TZ="America/Chicago" -v "//C/Users/nitsm/PIHOLE:/etc/pihole/" -v "//C/Users/nitsm/PIHOLE/dnsmasq.d:/etc/dnsmasq.d/" --dns=127.0.0.1 --dns=1.1.1.1 --restart=unless-stopped --hostname pi.hole -e VIRTUAL_HOST="pi.hole" -e PROXY_LOCATION="pi.hole" -e WEBPASSWORD="111" pihole/pihole:latest```

**Comment by PromoFaux** [comment]
Closed in place of the pinned #720

**Comment by bcaddy** [comment]
I am also getting the `invalid characters for local volume name` error but I'm not sure what the absolute path is in this case, I don't know much about Docker.  Here's is my `docker run` command

```
docker run -d --name pihole -e ServerIP=192.168.130.211 -e TZ=America/New_York -e WEBPASSWORD=trmWacFtfzyTxsjB -e DNS1=1.1.1.1 -e DNS2=1.0.0.1 -p 80:80 -p 53:53/tcp -p 53:53/udp -p 443:443 -v ~/pihole/:/etc/pihole/ --dns=127.0.0.1 --dns=1.1.1.1 --cap-add=NET_ADMIN --restart=unless-stopped pihole/pihole:latest
```

**Comment by bcaddy** [comment]
I am also getting the `invalid characters for local volume name` error but I'm not sure what the absolute path is in this case, I don't know much about Docker.  Here's is my `docker run` command

```
docker run -d --name pihole -e ServerIP=192.168.130.211 -e TZ=America/New_York -e WEBPASSWORD=PASSWORD -e DNS1=1.1.1.1 -e DNS2=1.0.0.1 -p 80:80 -p 53:53/tcp -p 53:53/udp -p 443:443 -v ~/pihole/:/etc/pihole/ --dns=127.0.0.1 --dns=1.1.1.1 --cap-add=NET_ADMIN --restart=unless-stopped pihole/pihole:latest
```

**Comment by dschaper** [comment]
> but I'm not sure what the absolute path is in this case

If you're mapping in `~` then use the full path to your home directory. 

Note: This isn't a Pi-hole issue and you'll probably get better assistance with a docker forum or your host OS support forum.

**Comment by bcaddy** [comment]
Thanks, that did it.
