### ISSUE TITLE
Owncloud, PiHole, Mosquitto(MQTT) and ioBroker over Docker on a MacMini

### ISSUE THREAD

**Issue by KBlobner** [pi-hole/docker-pi-hole#444]
Dear Community,

I have a question and hope you can help me out.
I will link a topic from the Owncloud forum here.

https://central.owncloud.org/t/owncloud-pihole-mosquitto-mqtt-and-iobroker-over-docker-on-a-macmini/19633

I try to get Owncloud, Mosquitto, PiHole and ioBroker to run from the same Server and ask for advice for the port-managing
Thank you very much
Kilian

**Comment by diginc** [comment]
> I have discovered some problems with my plan, running Owncloud and maybe PiHole and ioBroker on the same MacMini over Docker (not the ioBroker), because of the port interference.

> My question now would be how could I arrange the ports or is there an elegant workaround to run these services on one machine.

If these services are all in docker and require web ports, 80/443, then you should use a proxy like nginx or traefik

- https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose-traefik-proxy.md
- https://docs.traefik.io/ 
- https://github.com/jwilder/nginx-proxy
- https://github.com/jwilder/docker-gen (another option that I have not used)
