### ISSUE TITLE
Synology docker name

### ISSUE THREAD

**Issue by gmartinerm** [pi-hole/docker-pi-hole#446]
<how do I rename my docker host without breaking pihole?>

This is a... 

- [ ] Request for a new or modified feature
- [X ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
<How to rename the docker instance without breaking everything? Does the rename updates /etc/pihole/local.list ?>

## Actual Behavior
<I am affraid of trying anything because it makes the container unstable. I just want another name other than the default one  
```
bash-4.3# cat local.list
192.168.1.2 pihole-pihole1
192.168.1.2 pi.hole
```
pihole-pihole1 is the default

>

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.
2. 
3. 
4. 

## Debug steps I have tried

- [X ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version: 17.05.0-ce (Synology DS-1918+)
* Hardware architecture: 

```
[✓] Your debug token is: https://tricorder.pi-hole.net/ar5x8ymuih!

```

**Comment by diginc** [comment]
Restating your problem, you're looking to have a new hostname/container name for pi hole?  You're saying it breaks everything if you do try to rename it?  How did that happen exactly?

An alias hostname maybe easier than changing the real thing.  i.e. add a new hostname to dnsmasq pointed to your pi-hole IP you want.

**Comment by molgar** [comment]
In my experience, renaming the container does not brake it. However, changing any of the environment variables using the Synology Docker GUI does.
