### ISSUE TITLE
IPV6 only host - dns resolution fails

### ISSUE THREAD

**Issue by Rohmilchkaese** [pi-hole/docker-pi-hole#449]
Did someone already try to get this image running on an IPV6 only host ? 
DNS resolution fails and I can't its lists loaded. Therefore I never get to see the Web UI I guess.

This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
DNS resolution in setup fails regardless of whether I put an internal or external ipv6 adress for setup.

## Expected Behavior
should install. other containers in my docker setup to tend to have ipv6 out and inbound connectivity.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.Dockerfile:

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
     pub_ip6_block_net:
        ipv6_address: 2a0a:xxxx::xxx::x
    links:
      - ipv6_rec_dns
    ports:
      - "54:53/tcp"
      - "54:53/udp"
     # - "67:67/udp"
      - "8080:8080/tcp"
    #  - "443:443/tcp"
    environment:
      TZ: 'XX/XX'
      PROXY_LOCATION: pihole
      ServerIPv6: xxx
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades#
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 2606:4700:4700::1111
        # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

2. sudo docker-compose up -d

## Debug steps I have tried
Changing Dns from 127.0.0.1 to ::1 as it is an ipv6 only host

- [ x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Ubuntu 18.04 LTS
* Docker Version:18.09.5
* Hardware architecture: amd64

**Comment by troyfontaine** [comment]
Have you enabled experimental features and IPv6 in the Docker Daemon itself?  Instructions are [here](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/ipv6/).  This works for me.
