### ISSUE TITLE
Change port 443 & 80

### ISSUE THREAD

**Issue by misanthrophy** [pi-hole/docker-pi-hole#456]
This is a... 

- [ ] Request for a new or modified feature
- [X] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Hello, so I am pretty new to docker, basically thats the first time, I am ever using it, so please be patient with my veeery basic knowledge.

I am using the nextcloudPI image on my raspi, which in the background (apache2) is using port 80 and port 443. 

Due to that I've read online it is possible to run pihole in a docker, to make it working. 
Because for the beginning I preferred a GUI, I installed portainer to add all the necessary information on the right place. 

Unfortunately when I try to start the docker, it fails because both ports are already in usage by apache2. 

Changing external/host ports to 444/81 and route them internally to 443/80 at least allows to start the docker, but when I try to open IPaddress/admin automatically redirects me to nextcloud. 

## Expected Behavior

IPaddress/admin should open pihole

## Actual Behavior

IPaddress/admin redirects to nextcloud instead of pihole

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. I am using this guide: https://homenetworkguy.com/how-to/install-pihole-on-raspberry-pi-with-docker-and-portainer/
2. docker container starts if I set incorrect ports, but does open pihole
3. 
4. 

## Debug steps I have tried

- [X] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [X] I have searched this repository for existing issues and pull requests that look similar 

I already tried it redoing the volume/container/image with no success

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture: 

I am using the latest Raspian Stretch Full, on a Raspberry Pi 3B+, with the latest docker image and portainer image available. (Everything installed today)
All updates with apt-get update / apt-get upgrade were made. 

It is "only" a port issue, but similar to my docker knowledge, my network knowledge is very basic, so I don't know how to change ports, so that they will no longer interfere...

Thanks in advance for any help, it is much appreciated!!!

**Comment by diginc** [comment]
Try setting WEB_PORT from the https://github.com/pi-hole/docker-pi-hole#environment-variables section of the readme.

**Comment by thalesmaoa** [comment]
I'm also interested. If I understood correctly after read README file, if I change the ports from https://github.com/pi-hole/docker-pi-hole/blob/master/docker_run.sh, it means that it will run fine but with a different admin port (http://pihole:8000/admin). However, I'm still unsure about 443 port. Will it still filter https incoming packages if I change it for 444 for instance?

**Comment by lhzw** [comment]
I'd like to know that problem, too. I don't like it to listen on my 443 port, I use it for others.

**Comment by diginc** [comment]
For multiple applications listening on 80/443 in docker I recommend a proxy like traefik rather than binding to multiple ports, which we provide an example docker-compose stack for too.
