### ISSUE TITLE
dnsmasq: bad option at line 1 of /etc/dnsmasq.d/dns-servers.conf

### ISSUE THREAD

**Issue by aristosv** [pi-hole/docker-pi-hole#457]
I run this command to install pihole in a docker environment.

`docker run -d --restart always --name pihole -h pihole -p 53:53/tcp -p 53:53/udp -p 80:80 -p 443:443 -e PUID=1001 -e PGID=1001 -v /etc/localtime:/etc/localtime:ro -v pihole:/etc/pihole -v pihole:/etc/dnsmasq.d --dns=127.0.0.1 --dns=1.1.1.1 pihole/pihole`

In the log file I get the message

`dnsmasq: bad option at line 1 of /etc/dnsmasq.d/dns-servers.conf`

This is the contents of /var/lib/docker/volumes/pihole/_data/dns-servers.conf

```
Google (ECS);8.8.8.8;8.8.4.4;2001:4860:4860:0:0:0:0:8888;2001:4860:4860:0:0:0:0:8844
OpenDNS (ECS);208.67.222.222;208.67.220.220;2620:0:ccc::2;2620:0:ccd::2
Level3;4.2.2.1;4.2.2.2;;
Comodo;8.26.56.26;8.20.247.20;;
DNS.WATCH;84.200.69.80;84.200.70.40;2001:1608:10:25:0:0:1c04:b12f;2001:1608:10:25:0:0:9249:d69b
Quad9 (filtered, DNSSEC);9.9.9.9;149.112.112.112;2620:fe::fe;2620:fe::9
Quad9 (unfiltered, no DNSSEC);9.9.9.10;149.112.112.10;2620:fe::10;2620:fe::fe:10
Quad9 (filtered + ECS);9.9.9.11;149.112.112.11;2620:fe::11;
Cloudflare;1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001
```

**Comment by dschaper** [comment]
Check your mounts, you have the same mount point for `/etc/pihole` as `/etc/dnsmasq.d` and they are not interchangeable.

**Comment by aristosv** [comment]
I understand what you mean, but this is how I install all my containers. For example this is how I install mosquitto, and it works just fine.

`docker run -d --restart always --name mosquitto -h mosquitto -p 1883:1883 -p 9001:9001 -e PUID=1001 -e PGID=1001 -v /etc/localtime:/etc/localtime:ro -v mosquitto:/mosquitto/config -v mosquitto:/mosquitto/data -v mosquitto:/mosquitto/log eclipse-mosquitto`

**Comment by dschaper** [comment]
That may work for mosquitto, but not for Pi-hole. You have placed a configuration file that is meant for `/etc/pihole` in to the `/etc/dnsmasq.d` directory and that will cause the program to not start and present the error you see.

**Comment by diginc** [comment]
`-v pihole:/etc/pihole -v pihole:/etc/dnsmasq.d`

This shares the same folder for both /etc/pihole and dnsmasq.d and because dnsmasq.d (as many other *.d folders do) auto-loads anything it finds in it - it tries to load /etc/pihole configs which aren't valid for dnsmasq
