### ISSUE TITLE
The new network information table not showing any device

### ISSUE THREAD

**Issue by LightningRhino** [pi-hole/docker-pi-hole#458]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Version 4.3 not showing any devices in the new network information tab.

## Expected Behavior

It should display devices in my network using pihole.

## Actual Behavior

It only displays the docker containers gateway (172.17.0.1). 
Maybe only the network the docker container is running in is scanned for devices.
My devices running in the 192.168.178.0 network.

## Possible Fix

Scan the network where devices are running in. Container ist started with the -e ServerIP="192.168.178.2" flag, but the container has ip 172.17.0.2. 

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. 
2. 
3. 
4. 

## Debug steps I have tried

I deleted the /etc/pihole/pihole-FTL.db and restarted pihole, but result stays with not showing devices from 192.168.178.0 network.

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture: 
Raspberry Pi 3b.
Linux dockerpi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
Docker version 18.09.0, build 4d60db4

**Comment by diginc** [comment]
Are you using the default [network mode](https://docs.pi-hole.net/docker/DHCP/) - I have a feeling host / macvlan modes will be the only ones to work with this new feature.

**Comment by LightningRhino** [comment]
I'm not using host mode since I specify the ports in my run command.

> docker run -d \
>     --name mypihole \
>     -p 53:53/tcp -p 53:53/udp \
>     -p 80:80 \
>     -p 443:443 \
>     -v phlcnf-vol:/etc/pihole/ \
>     -v phldnsmsq-vol:/etc/dnsmasq.d/ \
>     -e ServerIP="192.168.178.2" \
>     -e TZ=Europe/Berlin \
>     --restart=always \
>     --dns=127.0.0.1 --dns=192.168.178.1 \
>     pihole/pihole:latest

**Comment by LightningRhino** [comment]
You were right. I started the container with --net=host instead the -p variables and now the network information is working.
I'm still not sure if I will go on using the container with the --net=host option.

**Comment by diginc** [comment]
MacVLAN mode is a good alternative to net host mode.  It gives a separate IP from the host from the host's subnet so you get the benefit of sharing the network (letting network info work) without the Port conflicts of host mode.

If you have containers you need connected together with Pi-hole you can also have secondary networks besides the macvlan, so containers that do use the default docker bridge mode can still be reliant on pi-hole with the container secondary network connection.

**Comment by glassbase** [comment]
I have network_mode: host in my compose file config and I don't get anything in network overview
