### ISSUE TITLE
Docker image for 4.3?

### ISSUE THREAD

**Issue by Haxy89** [pi-hole/docker-pi-hole#459]
Why there is no docker image for Pihole 4.3?

**Comment by dschaper** [comment]
There was one created 8 days ago. https://hub.docker.com/r/pihole/pihole/tags

**Comment by Haxy89** [comment]
So no news here: https://github.com/pi-hole/docker-pi-hole/releases ?

**Comment by Mcat12** [comment]
@diginc Can you update the releases with v4.3?
