### ISSUE TITLE
Lighttpd fails to start on Synology: (network.c.464) can't bind to port:  80 Address already in use

### ISSUE THREAD

**Issue by goncalossilva** [pi-hole/docker-pi-hole#464]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I've updated the image from 4.2.X and setup a fresh container, same volumes and environment variables as before. It fails to start, and the log contains these lines over and over:

```
Starting lighttpd
(network.c.464) can't bind to port:  80 Address already in use
Stopping lighttpd
lighttpd: no process found
```

## Expected Behavior
Container starts successfully.

## Actual Behavior
Container fails to start.

## Possible Fix
It seems that my `ServerIP` / `WEB_PORT` configuration is being ignored, as `/etc/lighttpd/lighttpd.conf` is trying to use port 80. Switching it to the same port as specified in `WEB_PORT` makes everything work again.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Download the latest image in Synology's Docker
2. Create a container, set the usual environment variables including `ServerIP`, `WEB_PORT` and `VIRTUAL_HOST`
3. Start the container

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Context and extra information
#432, but I have `ServerIP` specified

## Your Environment 

* Docker Host Operating System and OS Version: DSM 6.2.2-24922
* Docker Version: `Docker version 17.05.0-ce, build 371caef-synology`
* Hardware architecture: x86_64

**Comment by goncalossilva** [comment]
> I have tried running without my volume data mounts to eliminate volumes as the cause

I have now done this, and it's all sorted. Sorry for the spam!

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-mit-hue-sonos-iobroker-und-alexa/31042/14

**Comment by DennisYildirim** [comment]
Still they did not solve is not it. I'm using the latest version of pihole, on synology docker. Unbelievable

**Comment by PromoFaux** [comment]
If you believe you are having the same issue as OP, please provide some more detail. I can't do much with "unbelievable".

Here is the code that sets the custom web port:

https://github.com/pi-hole/docker-pi-hole/blob/a9ecd4e7a20ccdd5b404aa70169f11b938f3e70d/src/s6/debian-root/usr/local/bin/bash_functions.sh#L373-L394

Please run the container with the environment variable `PH_VERBOSE` set to `1`, and post your startup log - perhaps we will see what is happening.

Also, please provide the command or compose file you are using to configure/start your container.7

I am running on Synology with no issues...
