### ISSUE TITLE
VIRTUAL_HOST stopped working in 4.3.1-1

### ISSUE THREAD

**Issue by etiago** [pi-hole/docker-pi-hole#465]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I had a working `pihole/pihole:4.3_aarch64` installation which I could access via the domain I set on `VIRTUAL_HOST`. After I updated to `4.3.1-1_aarch64`, I get an error page saying that the website was blocked and is being flagged primarily as not being found on any blacklist.

I can still access it via `pi.hole`, but the `VIRTUAL_HOST` functionality is broken.

## Expected Behavior

When I access the PiHole via the domain set on `VIRTUAL_HOST`, it should work as normal.

## Actual Behavior
I can't use `VIRTUAL_HOST`.

## Possible Fix

I'm honestly not sure... Switching back to the old version works, but doesn't seem like a good idea.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Run version 4.3.1-1 and set `VIRTUAL_HOST`
2. Verify that you get an error while trying to access PiHole using that virtual host.

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture:

**Comment by ravensorb** [comment]
Any details on why this was closed?  I am running into the same type of issue (At least I think I am)
