### ISSUE TITLE
lighttpd does not use WEB_PORT variable anymore

### ISSUE THREAD

**Issue by N0tronic** [pi-hole/docker-pi-hole#466]
This is a... 

- [ ] Request for a new or modified feature
- [ x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
lighttpd does not use WEB_PORT variable anymore. Port 80 now is hardcoded in lighttpd.conf

## Expected Behavior
WEB_PORT variable set the webserver port

## Actual Behavior
webserver port ist hardcoded to port 80

## Possible Fix
change port in lighttpd.conf to WEB_PORT variable

## Context and extra information
Container not running if port 80 is still in use from another process

## Your Environment 
Synology NAS

**Comment by 10k-resistor** [comment]
I have the same problem.

**Comment by dschaper** [comment]
This issue was closed over a year ago, please open a new issue and fill out the template completely if you'd like to report.

**Comment by rbrown256** [comment]
I solved this by copying `lighttpd.conf` from the container, modifying it, then adding it to a bind mount:

Run your docker-pi-hole container then

`docker ps` - get your Container ID

`cd  /volume1/docker/pihole/` (or whatever location for your host)
`mkdir lighttpd`
`cd lighttpd`


```
docker cp <Container ID>:/etc/lighttpd/lighttpd.conf .
docker cp <Container ID>:/etc/lighttpd/conf-available .
docker cp <Container ID>:/etc/lighttpd/conf-conf-enabled .
```

`vim lighttpd.conf` and change `server.port` e.g.

```
server.port                 = 8000
```

**Optional:** I also enabled HTTPS via Tailscale by copying the certs to this folder and updating the config (also inside `lighttpd.conf`:

```
ssl.engine = "enable"
ssl.pemfile = "/etc/lighttpd/example.ts.net.crt"
ssl.privkey = "/etc/lighttpd/example.ts.net.key"
```

**Continued:**

Stop the container and in your compose file add the volume:

```
volumes:
  - /volume1/docker/pihole/lighttpd:/etc/lighttpd
```

I also updated my cronjob script to update the certs

[Original script](https://medium.com/@walid.karray/automating-tailscale-certificate-configuration-on-synology-dsm-8a3c3b79e010)

Added

`cp "$TEMPDIR/$TS_DNS.crt" "$TEMPDIR/$TS_DNS.key" /volume1/docker/pihole/lighttpd/`

Then rebuild and restart your project, and then pi-hole is now happy on your port of choice.
