### ISSUE TITLE
Pi-hole Version Info at Bottom of GUI Pages

### ISSUE THREAD

**Issue by mxmartins** [pi-hole/docker-pi-hole#469]
I'm running Pi-hole in a Synology Docker container.  I just updated Pi-hole to pull in the new FTL version (4.3.1).

I downloaded the latest Docker image and re-installed it.  On the bottom of the Dashboard GUI page (and most other GUI pages), I see the following information which does not appear correct.  Should it be displaying this information in this format?

Pi-hole Version vDev (HEAD, v4.3-0-g1d43c0a) Web Interface Version vDev (HEAD, v4.3-0-g44aff72) FTL Version v4.3.1

**Comment by diginc** [comment]
After pulling the latest image, make sure you've properly re-created your container with a full `docker rm` or `docker-compose stop` before running your docker with the latest image tag.  

We can compare output of `docker images | grep pihole` to see what image hash you have and if it is the latest.

**Comment by pssonline** [comment]
Also seeing the above issue running Pi-hole in a docker on an unRaid box. Output is 
pihole/pihole       latest              07d7ef169eb9        13 hours ago        273MB

Not entirely sure how to resolve this as I've not changed any of the template or repository settings?

**Comment by mxmartins** [comment]
I’ve deleted the container multiple times, and made sure all data files in Docker were deleted.  But I get the same problem…

Pi-hole Version vDev (HEAD, v4.3-0-g1d43c0a) Web Interface Version vDev (HEAD, v4.3-0-g44aff72) FTL Version v4.3.1

root@DiskStation:~# docker images | grep pihole
pihole/pihole       latest              07d7ef169eb9        5 hours ago         273MB
pihole/pihole       <none>              e4feea084a98        3 days ago          273MB
pihole/pihole       <none>              501ab5b47e04        2 weeks ago         304MB
pihole/pihole       <none>              fafd90299bac        3 months ago        299MB
root@DiskStation:~#

Can you please look at this output and tell me if something is not right?  I’m using the Latest image from the Synology Docker registry.  I’ve done updates before and never ran into this issue before.  I’m not sure what is really going on.

**Comment by diginc** [comment]
I confirmed this issue, it is because of the change in #454.  I've attempted to resolve this by running a git tag fetch but it seems broken due to the shallow clone still.  Will need to see what else can be done on the docker side, other wise maybe the web page can lookup the version the same way the command `pihole version` does, because that actually works.

**Comment by Mcat12** [comment]
You could clone a few commits further than just one, which is what pi-hole/pi-hole#2738 did to solve a similar issue.

**Comment by pssonline** [comment]
Apologies for the completely non-savvy post but where are we with this please?

**Comment by diginc** [comment]
The branch metadata had to be pulled in to fix, opening a PR to resolve now.

**Comment by mxmartins** [comment]
Problem resolved.  Thank you for the help…

**Comment by pssonline** [comment]
Thank you.

**Comment by tanasegabriel** [comment]
I'm not entirely sure this if fixed:

```
$ docker pull pihole/pihole
Using default tag: latest
latest: Pulling from pihole/pihole
Digest: sha256:1c79a9ffbf7941368a92aba917f5afd9ad76bf32d7a19f5295992d20a4c512bb
Status: Image is up to date for pihole/pihole:latest
$ docker image ls pihole/pihole
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
pihole/pihole       latest              78b86f95f464        7 days ago          285MB
$ date
Sun 30 Jun 20:33:08 BST 2019

```

![image](https://user-images.githubusercontent.com/20187768/60401222-17d82c00-9b76-11e9-8c62-329ae82f35d9.png)
