### ISSUE TITLE
Network latency overhead observed

### ISSUE THREAD

**Issue by kultigspritzig** [pi-hole/docker-pi-hole#473]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
I already reported it a while ago here:
https://www.reddit.com/r/docker/comments/boiyjr/docker_container_pihole_slow_over_the_network/

I use pihole inside a docker container (available at 10.0.0.2, for reference) on my router. I run some tests today and found some strange behavior. Namely, pihole is as slow as the Cloudflare when used from inside the Ethernet network, but not when used directly on the server. I fail to understand what's happening.
While on the router, everything is as expected – pihole caches the responses properly:

```
kultig@router:~$ dig @1.1.1.1 google.com 
;; Query time: 11 msec 
;; SERVER: 1.1.1.1#53(1.1.1.1) 

kultig@router:~$ dig @10.0.0.2 google.com 
;; Query time: 11 msec 
;; SERVER: 10.0.0.2#53(10.0.0.2)  

kultig@router:~$ dig @10.0.0.2 google.com 
;; Query time: 0 msec 
;; SERVER: 10.0.0.2#53(10.0.0.2)  

```

On my desktop connected over the ethernet, with a ping to pihole (10.0.0.2) being  <1ms, the responses are over 10ms. Effectively it takes as long as digging the external 1.1.1.1.

```
kultig@desktop:~$ ping 10.0.0.2                                                                                                                                       
PING 10.0.0.2 (10.0.0.2): 56 data bytes
64 bytes from 10.0.0.2: icmp_seq=0 ttl=64 time=0.423 ms
64 bytes from 10.0.0.2: icmp_seq=1 ttl=64 time=0.504 ms

kultig@desktop:~$ ping 1.1.1.1                                                                                                                                        
PING 1.1.1.1 (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: icmp_seq=0 ttl=57 time=10.476 ms
64 bytes from 1.1.1.1: icmp_seq=1 ttl=57 time=9.538 ms

kultig@desktop:~$ dig @10.0.0.2 google.com
;; Query time: 13 msec
;; SERVER: 10.0.0.2#53(10.0.0.2)

kultig@desktop:~$ dig @1.1.1.1 google.com
;; Query time: 10 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
```

Also note that digging 1.1.1.1 takes just as long on the router as on the desktop, proving that the overhead is not coming from the Ethernet network itself.

I am totally puzzled. What is going on here? Surely must be some docker/container/virtualized network/netfilter deficiency, but I don't even know where to start trying to debug it further.

## Expected Behavior
The second dig attempt to pihole from within Ethernet network should be as quick as the ping response from it (<1ms)

## Actual Behavior
There's an additional latency overhead causing the dig to pihole be as slow as a dig to a public DNS outside of the network

## Possible Fix
Possible docker networking configuration issue. 
Possible DNS racing condition caused by interference with Docker's own DNS. 

## Steps to Reproduce and debugging done
1. Try digging servers as explained in the description.

## Debug steps I have tried
- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

I did *not* try running in --net=host mode, which from what I understand may be an actual fix for this. My current setup unfortunately is too complicated for me to test this in my environment. 

## Your Environment 
* Docker Host Operating System and OS Version: Debian Buster/Sid
* Docker Version: docker.io 18.09.5-0ubuntu1
* Hardware architecture: x64

**Comment by gonzalezcalleja** [comment]
Hi, 

Finally find a solution? I have exactly the same issue here! 

Thanks!

**Comment by gonzalezcalleja** [comment]
I have found a solution, my issue wasn't in the server/docker/pihole ... was on the client side (macOS using ethernet), if you disable the firewall the time changes from 10-12ms to 0-2ms.
