### ISSUE TITLE
Changes to Pihole Configuration

### ISSUE THREAD

**Issue by XxAcielxX** [pi-hole/docker-pi-hole#475]
Hello,

I have my Pihole Container running on Arch Linux ARM on RPi3, but I would like to know where to make changes like:
```
DBINTERVAL=
DBFILE=
```

I know about the non docker version, but which file to edit for docker version? 

Regards~

**Comment by Mcat12** [comment]
Edit `pihole-FTL.conf` in the directory you mounted under `/etc/pihole`.
