### ISSUE TITLE
Protection for amplification attacks

### ISSUE THREAD

**Issue by AndreKoepke** [pi-hole/docker-pi-hole#488]
This is a... 

- [x] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
Iam using Pi-Hole on a server in the internet. Its very nice, but there always bots that try to use my server for amplification-attacks. To avoid these attacks, I use the following iptables rule (defined via ferm):
```
proto udp dport (53) {
   mod string from 40 algo bm hex-string "|0000ff0001|" DROP;
   ACCEPT;
}
```
I moved Pi-Hole to docker. And docker dont really like my manual iptables rules.  
So, its possible to put this rule into Pi-Hole-docker?

## Expected Behavior
Pi-Hole blocks any-queries (so it cant be used for dns amplification attacks),

**Comment by larssb** [comment]
Hi @AndreKoepke,

So Pi-hole is listening on the WAN interface? How does this work for you?

**Comment by HorayNarea** [comment]
Kinda off-topic but important:
Just blocking queries of type `ANY` is not sufficient to protect against amplification attacks, there are many more queries one could send to a DNS server and get a much bigger response back…

The correct solution would be rate limiting which can also be done with iptables (or using unbound as public resolver, setting the ip_ratelimit setting, forwarding queries to your pihole and let pihole listen local-only)

**Comment by AndreKoepke** [comment]
@larssb Very good (with my iptable-fix). As @HorayNarea mentioned there other ways to do a amplification-attack on - so you should have an eye on the traffic. But I never saw everything else on my server.  
With an public DNS you define your server as dns-server in your router (so all devices in your private network are ad-free). And for all public WLANs you can use your server directly. Its pretty nice.

@HorayNarea Rate-Limit is not a solution for me. If somebody attack my server, then are all my devices can not resolve hosts anymore.

For the topic: I was able to bring docker and iptables together, so PiHole is protected by my host-maschine (with iptables). 
See this for more details: https://unix.stackexchange.com/questions/552685/filter-docker-traffic

But as @HorayNarea said: There no guarantee that this protect against any amplification-attacks. How about a security-feature that PiHole only accepts "normal" dns-requests?

**Comment by HorayNarea** [comment]
> @HorayNarea Rate-Limit is not a solution for me. If somebody attack my server, then are all my devices can not resolve hosts anymore.

This depends on the implementation of ratelimiting, unbound's `ip-ratelimit` setting ratelimits _per IP_ so your normal queries are just fine, also you can define a percentage that is allowed even when ratelimited (so "desperate" clients still get hosts resolved when _they_ are ratelimited)


> But as @HorayNarea said: There no guarantee that this protects against any amplification-attacks. How about a security-feature that PiHole only accepts "normal" dns-requests?

You miss the point, there is no programmatic distinction between "normal" and "non-normal" dns-requests, they all look exactly the same… except for the rate at which they come in for a single RR/from a single client.

The only security-features PiHole could add (which btw should be suggested at [pi-hole/FTL](https://github.com/pi-hole/FTL) and not here where only the docker-version is maintained :D) would be:
  - rate-limiting per client IP and/or per requested RR, like [AdGuard Home](https://github.com/AdguardTeam/AdGuardHome) or [Unbound](https://nlnetlabs.nl/projects/unbound/about/) do it
  - permanently blacklisting IPs when you notice they are abusing your resolver (with a nice UI in the webinterface)

This is literally how every public resolver does it… (+ AI and other buzzwords :D)
