### ISSUE TITLE
Lighttpd does not start in container

### ISSUE THREAD

**Issue by haioken** [pi-hole/docker-pi-hole#490]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

When starting the container, container gets stuck attempting to start `lighttpd -D -f /etc/lighttpd/lighttpd.conf` over and over again.

## Expected Behavior

lighttpd should start and web server becomes available

## Actual Behavior

Logs from issue (docker logs pihole): https://pastebin.com/Vu069ZdH

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Clean any existing container with `docker rm pihole`
2. Clean any existing image with `docker rmi pihole/pihole`
3. Run container with `docker run -d --name pihole -p 53:53/tcp -p 53:53/udp -p 81:80 -e TZ="America/Chicago" -v "$(pwd)/etc-pihole/:/etc/pihole/" -v "$(pwd)/etc-dnsmasq.d/:/etc/dnsmasq.d/" --dns=127.0.0.1 --dns=1.1.1.1 --restart=unless-stopped pihole/pihole:latest`
4. Attempt to start lighttpd manually (same result) with `docker exec -it pihole lighttpd -D -f /etc/lighttpd/lighttpd.con`

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar, none found regarding this message

I have tried entering the container and running apt-get update/apt-get upgrade, tried enabling/disabling lighttpd modules.

## Context and extra information
Had run this container previously on centos host, but host has been reinstalled with openSUSE tumbleweed. Other containers I run seem unaffected.

## Your Environment 

* Docker Host Operating System and OS Version: openSUSE Tumbleweed 20190806
* Docker Version: 19.03.1, build 74b1e89e8ac6
* Hardware architecture: amd64

**Comment by kekec777** [comment]
Did anybody resolve this ?

**Comment by iamskok** [comment]
@haioken have you resolved this issue?

**Comment by areese** [comment]
I hit this with Podman, it turned out the my issue was missing the ```--dns 127.0.0.1``` before any other dns, but that is in the bug report.

For anyone using pod man, these are the configs I tested:

```
podman run -d \
    --name pihole \
    -p 53:53/tcp -p 53:53/udp \
    -p 80:80 \
    -p 443:443 \
    -e TZ="America/Chicago" \
    -v "${PIHOLE_BASE}/etc-pihole/:/etc/pihole/" \
    -v "${PIHOLE_BASE}/etc-dnsmasq.d/:/etc/dnsmasq.d/" \
    --dns=127.0.0.1 --dns=1.1.1.1 \
    --restart=unless-stopped \
    --hostname pi.hole \
    -e VIRTUAL_HOST="pi.hole" \
    -e PROXY_LOCATION="pi.hole" \
    -e ServerIP="127.0.0.1" \
    --healthcheck-start-period 1m --healthcheck-retries 5 --healthcheck-command "dig +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1" \
    --cap-add NET_ADMIN \
    --cap-add SYS_NICE \
    pihole/pihole:latest
```

To use a vlan bridge I used the following:
The dhcp server serves 192.168.1.2 for the mac 11:22:33:44:55:66
```
podman run -d \
    --net pihole-vlan \
    --name pihole \
    --publish-all \
    --mac-address=11:22:33:44:55:66 \
    -e TZ="America/Chicago" \
    --dns=127.0.0.1 \
    --dns=172.16.5.2 \
    -v "${PIHOLE_BASE}/etc/pihole/:/etc/pihole/" \
    -v "${PIHOLE_BASE}/etc/dnsmasq.d/:/etc/dnsmasq.d/" \
    --restart=unless-stopped \
    --hostname pi.hole \
    -e VIRTUAL_HOST="pi.hole" \
    -e PROXY_LOCATION="pi.hole" \
    -e ServerIP="127.0.0.1" \
    -e VIRTUAL_HOST="bitstripper.edvenull" \
    -e PROXY_LOCATION="bitstripper.edvenull" \
    -e ServerIP="127.0.0.1" \
    -e VIRTUAL_HOST="pi.hole" \
    -e PROXY_LOCATION="pi.hole" \
    -e ServerIP="127.0.0.1" \
    --healthcheck-start-period 1m --healthcheck-retries 5 --healthcheck-command "dig +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1" \
    --cap-add NET_ADMIN \
    --cap-add SYS_NICE \
    --ip 192.168.1.2 \
    pihole/pihole:latest
```

**Comment by areese** [comment]
One more thing to note, as I just hit this again.

If you have 2 dns servers specified, and one isn't responding (such as 172.16.5.2 in the case above) you will see this error:

For example:

```
podman exec -it pihole dig @172.16.5.2 raw.githubusercontent.com

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> @172.16.5.2 raw.githubusercontent.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Once I fixed the problem with seeing port 53 on the upstream dns, I got pihole working again.

Hope this helps.

**Comment by raypettersen** [comment]
In my case, the logdirectory lighttpd doesn't exist. After volume mounting and creating the logdir lighttpd starts just fine.

**Comment by areese** [comment]
@raypettersen it seems to me like the Dockerfile should be updated to create that log directory.  I didn't notice that, for me if it couldn't perform first time dns resolution lighttpd never got started.
