### ISSUE TITLE
Configuring pi-hole with network_mode: host leads to lighttpd unable to start.

### ISSUE THREAD

**Issue by sjmuniz** [pi-hole/docker-pi-hole#495]
New install over armbian on a cubieboard using docker; I can start the container from docker-compose correctly.
But setting network to network_mode: host causes lighttpd  to a restart loop unable to bind to 127.0.0.1:80
 

This is a... 

- [ ] Request for a new or modified feature
- [x ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Expected Behavior

Selecting "host" network mode in docker should allow lighttpd to bind correctly
## Actual Behavior

lighttpd is unable to start looping with the error:
pihole    | lighttpd: no process found
pihole    | Starting lighttpd
pihole    | 2019-08-15 03:58:02: (network.c.464) can't bind to port: 127.0.0.1 80 Address already in use
pihole    | Stopping lighttpd
pihole    | lighttpd: no process found
pihole    | Starting lighttpd
pihole    | 2019-08-15 03:58:03: (network.c.464) can't bind to port: 127.0.0.1 80 Address already in use
pihole    | Stopping lighttpd

## Possible Fix

As per bug #443 updating the docker-compose file with ServerIP fixed the issue.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.  mkdir pi-hole && cd pi-hole && wget -O docker-compose.yml https://gist.githubusercontent.com/sjmuniz/b67dbdc570c4617cf602dc15c714af05/raw/0dc657caf651485da5deb792eb070474b1c15791/docker-compose.yaml && docker-compose up
fails.
2. mkdir pi-hole && cd pi-hole && wget -O docker-compose.yml https://gist.githubusercontent.com/sjmuniz/1a6065e0d82b7fc8e45f16bde8817730/raw/f5454fef37f5b977b0c92a0486adc4649dc056d8/docker-compose.yaml && docker-compose up
Does not fail.

## Debug steps I have tried

- [x ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
smuniz@cubie:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
smuniz@cubie:~$ uname -a
Linux cubie 4.19.38-sunxi #5.85 SMP Wed May 8 14:20:48 CEST 2019 armv7l armv7l armv7l GNU/Linux

* Docker Version:
smuniz@cubie:~$ docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:43:10 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:01:09 2019
  OS/Arch:          linux/arm
  Experimental:     false

* Hardware architecture: 
ARMv7hf

**Comment by itcotta** [comment]
Setting the ServerIP variable didn't solve the issue for me. Perhaps there is something more to this issue?

docker-compose.yml:
`version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: 'Europe/Stockholm'
      WEBPASSWORD: 'p@ssword'
      ServerIP: '192.168.0.6'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
`

Output from docker:
https://gist.github.com/itcotta/371ab6506f6a7aea7698a9ac3b5e34e3

**Comment by larssb** [comment]
@itcotta & @sjmuniz 

The docs. tells the story. Network host mode is not supported on other OS than Linux. So either one have *Linux* or do not use network host mode.

So couldn't this case then be closed?

**Comment by J-Siu** [comment]
@larssb  I just encountered this on a linux box.

Host info:
```sh
╰─$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Within container:
```sh
root@door:/# pihole -v
  Pi-hole version is v4.3.2 (Latest: v4.3.2)
  AdminLTE version is v4.3.2 (Latest: v4.3.2)
  FTL version is v4.3.1 (Latest: v4.3.1)
```

**Comment by chedxb** [comment]
I have the same problem and the OS is Linux (Ubuntu 18.04.4 LTS (GNU/Linux 5.0.0-1036-azure x86_64)

When I deploy pi-hole docker instance on HOST mode, I keep getting the following messages;

2020-04-22 22:58:47: (network.c.464) can't bind to port: [Server IP address] 80 Cannot assign requested address 
Stopping lighttpd
ghttpd: no process found

When I deploy the docker instance on BRIDGE more, it don't get any error message.

Thoughts?

**Comment by mathieuruellan** [comment]
Same issue (Debian buster)

> (network.c.464) can't bind to port: 127.0.0.1 80 Address already in use.
> Stopping lighttpd
> 

I'm stuck with the bridge mode. 
I can reproduce with v4.4 or v5.0

**Comment by diginc** [comment]
Sounds like a simple port conflict. Something on the host is using port 80 already.

**Comment by mathieuruellan** [comment]
@diginc no it's not. Nothing is listening on this port. Same problem if i set another port with WEB_PORT env.

**Comment by jaysgrant** [comment]
I'm having the same problem running with docker on Ubuntu 20.04, deploying via docker-compose. 
I have verified nothing is running on port 80. I want to use host mode as I am planning on using the container for DHCP, along with DNS.
My compose manifest is as follows:

`version: "2.4"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'SuperSecretPassword'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    network_mode: host`

**Comment by dschaper** [comment]
What do you have for your `ports`?

**Comment by treitmayr** [comment]
I made the observation that this error only happens when I do *not* set the `ServerIP` environment variable. After setting it to my host IP address, lighttpd starts as expected.

From looking into /etc/lighttpd/lighttpd.conf one of the few differences between bridge and host networking mode is an additional line in the bad version:
`$SERVER["docket"] == "127.0.0.1:81" {}`

When commenting out this line, lighttpd starts happily - however I then run into an endless loop of reverse lookups (from localhost to localhost:53), which is a different issue.

**Comment by SuperSandro2000** [comment]
@treitmayr When lighttpd listens on 0.0.0.0 you can't make it listen to 127.0.0.1, too cause the same port there is already taken by 0.0.0.0. This probably needs a condition in the start script.

**Comment by mathieuruellan** [comment]
@treitmayr Thank you! I set ServerIP and now it works. Confusion in the doc. It's not written that this parameter is mandatory in host mode.
