### ISSUE TITLE
Pihole add static DNS entrys

### ISSUE THREAD

**Issue by BMWfan** [pi-hole/docker-pi-hole#496]
Hello together,

i found on any website a command how i can add a static dns entry to the /etc/hosts file inside of the pihole container with which i added mydomain.de. My problem is, i used it once it worked perfectly but i want to use it again but couldn't find this command again.
My /etc/hosts looks now like this:
####################
127.0.0.1       localhost
192.168.0.100   mydomain.de    raspberrypi
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       raspberrypi
####################

Knows someone perhaps such a command to realize this? The Line is by the way also there after a restart of the container.

Greetings

Daniel

**Comment by vandorjw** [comment]
`docker exec pihole /bin/sh -c "echo 192.168.0.100 mydomain.de >> /etc/hosts"`

That might be what you are looking for?

`docker exec pihole pihole restartdns`

Execute that line after you update /etc/hosts

**Comment by 0xERR0R** [comment]
You can create a new file "99-custom.conf" with following content:
`address=/myurl/192.168.x.x`
and mount this file in docker-compose to location "/etc/dnsmasq.d/99-custom.conf
