### ISSUE TITLE
Primary nameserver set to 127.0.0.11 in /etc/resolv.conf

### ISSUE THREAD

**Issue by imjeffxp** [pi-hole/docker-pi-hole#497]
This is a... 
- [ x ] Issue trying to run the docker image

## Description

This might be more of a warning than bug as the application still works although this comes up. It looks like the primary nameserver set on the latest image is 127.0.0.11 in /etc/resolv.conf. See below

`[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
stty: 'standard input': Inappropriate ioctl for device
 ::: Starting docker specific checks & setup for docker pihole/pihole
WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)

nameserver 127.0.0.11
options ndots:0`

This appears to happen every time I bring up a new container using docker-compose up.

## Steps to Reproduce and debugging done

1. Run the docker-compose file in the readme

**Comment by Dudemullet** [comment]
@imjeffxp I was seeing your exact same situation. Updating my docker fixed this issue. If updating docker is not an option look into alternative solutions. via @diginc [here](https://github.com/pi-hole/docker-pi-hole/issues/410#issuecomment-460515706). Also, might I suggest closing this issue as a duplicate from #410

**Comment by Haarolean** [comment]
This is not an issue. 127.0.0.11 is docker's internal DNS resolver, which in turn uses your system DNS servers.
