### ISSUE TITLE
Disabling systemd-resolved is not sufficient (or best practice) to run and use docker-pi-hole on Ubuntu

### ISSUE THREAD

**Issue by kaysond** [pi-hole/docker-pi-hole#503]
I tested this on a Ubuntu 18.04.3 VM.

The README suggests disabling the systemd-resolved service because the systemd-resolved stub resolver binds to port 53 by default, preventing pihole from starting. But its not necessary to disable the service entirely. And as this is the future of Ubuntu DNS resolution, I would worry that it could cause problems with other services (though admittedly I didn't actually have any problems).

The pi-hole automated-installation script simply disables the stub resolver with a configuration file change: https://github.com/pi-hole/pi-hole/blob/1a741f696eec2ee148fc59bc0dc98e862475e6ef/automated%20install/basic-install.sh#L1523-L1544

I would propose that the README be changed to suggest doing the same, rather than disabling the service entirely.

Furthermore, this may not be sufficient to actually use pi-hole as the local system's DNS resolver. In my case, I noticed the resolver still points to `127.0.0.53`. (And it still points here even if you disable the service entirely). This causes DNS resolution errors of `;; reply from unexpected source: 127.0.0.1#53, expected 127.0.0.53#53`. The "by design" way of fixing this is to change the `/etc/resolv.conf` symlink from `../run/systemd/resolve/stub-resolv.conf` to `../run/systemd/resolve/resolv.conf`.

systemd-resolved automatically manages both of these files, so manually setting the `nameserver` to `127.0.01` is not a good idea. But the `resolv.conf` version sets the nameserver appropriately based on the system settings (i.e. it appears to abide by the `netplan`) and seems to be the intended usage.

I think this should be added to the README as well, and I'd be happy to create a PR for both.

**Comment by diginc** [comment]
Great idea, I'm all for not causing more problems and keeping to best practices.

It'd be awesome if you made a PR, my one request would be provide some citation/link to it being a best practice or at least to references showing what systemd's resolved maybe needed for/what might go wrong from disabling it.

**Comment by kaysond** [comment]
> provide some citation/link to it being a best practice or at least to references showing what systemd's resolved maybe needed for/what might go wrong from disabling it

TBH I don't have a source exactly, but I'll see what I can find reference-wise.
But some reasons are:
- Just disabling the service breaks DNS resolution, which then prevents docker-pull from working, which is painful for automation
- There are apparently some bugs with resolving while using VPN connections (looks like fixed in later Ubuntu releases)
- If you disable the service, `netplan` stops working properly (i.e. if I configure an explicit nameserver in my netplan, then run `netplan apply`, it won't properly update `/etc/resolv.conf`)

So the Ubuntu deployment flow I would use is:
- Disable stub resolver by changing `/etc/systemd/resolved.conf`
- Move `/etc/resolv.conf` symlink to point to `/run/systemd/resolve/resolv.conf` (this file needs to be updated even if you straight up disable the service, and the documentation should definitely reflect that)
- Bring up docker container

During this deployment, dns resolution falls back to the system default, which is usually set by dhcp. If you had used netplan to set up a static nameserver, that would be used.

Once pihole is up and running, you can switch over to it in netplan, or you can update the dhcp server to point to it.
