### ISSUE TITLE
Pihole container keeps restarting on pizero (armv6l)

### ISSUE THREAD

**Issue by lewixlabs** [pi-hole/docker-pi-hole#507]
This is a... 

- [ ] Request for a new or modified feature
- [X] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

My machine:

- Raspberry Pi Zero W (armv6l) with HypriotOS (raspbian buster)

- Distributor ID:	Raspbian
- Description:	Raspbian GNU/Linux 10 (buster)
- Release:	10
- Codename:	buster
- Docker version: 19.03.2, build 6a30dfc
- Issue description: Docker container keeps restarting, these logs are obtained from "docker logs pihole"

> $ docker logs pihole
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
[cont-init.d] 20-start.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
[cont-init.d] 20-start.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
[cont-init.d] 20-start.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
[cont-init.d] 20-start.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
[cont-init.d] 20-start.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
[cont-init.d] 20-start.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
[cont-init.d] 20-start.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
[cont-init.d] 20-start.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

## Expected Behavior

Container must run without issues

## Actual Behavior

Container keeps restarting

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Create _docker-compose.yml_ file
> version: "3"
> 
> services:
>   pihole:
>     container_name: pihole
>     image: pihole/pihole:latest
>     restart: unless-stopped
>     ports:
>       - "53:53"
>       - "67:67"
>       - "80:80"
>       - "443:443"
>     environment:
>       TZ: "Europe/London"
>       WEBPASSWORD: "my_secret_password"
>     dns:
>       - 127.0.0.1
>       - 1.1.1.1
>     volumes:
>       - ./pihole/etc/:/etc/pihole/
>       - ./pihole/dnsmasq.d/:/etc/dnsmasq.d/
>       - ./pihole/pihole.log:/var/log/pihole.log
>     cap_add:
>       - NET_ADMIN

2. Execute command

> docker-compose up -d

Thanks to anyone which can help me

Lewix

**Comment by diginc** [comment]
PiZero isn't compatible with the armHF image tag which is leading to the binaries dying after the container spins up.  

Coincidentally a PR was opened to support an ARMEL build for Zero + RBP1 here : https://github.com/pi-hole/docker-pi-hole/pull/506

Once that is done and deployed we'll have something for you to try

**Comment by lewixlabs** [comment]
Thank you @diginc ,
meanwhile I will continue to use native pihole release (no docker) which works without issues.

Let me know if I can help testing your next docker preview pihole release.

Lewix

**Comment by lewixlabs** [comment]
Hi @diginc ,
I cloned build-ftl branch of @DHandspikerWade pihole repo and i put armel image on balena cloud project (edited on my local git repo)
https://github.com/klutchell/balena-pihole.git

Pihole seems working (service starts and blocks ads)  👍
![image](https://user-images.githubusercontent.com/7371215/64870104-f3530280-d642-11e9-917d-7fc3d07e17ea.png)

**Comment by chrisdeely** [comment]
@lewixlabs I've run into the same issue working with the balena cloud setup (https://github.com/klutchell/balena-pihole.git) are you able to share what changes are needed to get the build-ftl version to deploy? 

I'm new to Docker but it seems that I would need to change where pihole is sourced from by changing this line in the Dockerfile:
`FROM pihole/pihole:4.3.2-1_armhf`

**Comment by hombit** [comment]
Confirm problem for `pihole/pihole:5.0-armhf` image

**Comment by dsarlo** [comment]
Trying to get this working on my rpizero. Any updates???

**Comment by stevleibelt** [comment]
Trying to get [it](https://www.suse.com/c/pihole-podman-opensuse/) started on my raspberry pi 1. Still not working.

* OS: archlinuxarm 5.10.22-3-ARCH
* CPU: Raspberry Pi Model B Rev 2 ARMv6-compatible processor rev 7 (v6l)
* podman version 3.0.1

Any updates?
Building for the aur package is not working anymore :-\.

**Comment by dschaper** [comment]
https://aur.archlinux.org/packages/pi-hole-server/?O=10&PP=10#pinned-633053

**Comment by stevleibelt** [comment]
@dschaper 

Did I made a mistake? After reading all the comments here, I thought it is general "not running on raspberry pi 1" issue which is not related to archlinux arm.

**Comment by hombit** [comment]
Does anyone can confirm it work now?

**Comment by PromoFaux** [comment]
Here we go 

https://github.com/pi-hole/docker-pi-hole/issues/245#issuecomment-1001454523
