### ISSUE TITLE
Set web password from file

### ISSUE THREAD

**Issue by kaysond** [pi-hole/docker-pi-hole#509]
Is it possible to set the web password from a file rather than an environment variable? This way you don't have to leave your password in a docker-compose file or in the command history. It also makes it very convenient to use via docker secrets/ansible vaults.

**Comment by nxadm** [comment]
@kaysond Docker-compose has a built-in functionality for this. Have a look here:
https://docs.docker.com/compose/env-file/

**Comment by kaysond** [comment]
@nxadm I'm talking about a file within a container, not a file on the host.

**Comment by kaysond** [comment]
#512

**Comment by lightswitch05** [comment]
Implemented by #584 and now in the dev branch.
