### ISSUE TITLE
Update Docker Image with 4.3.2

### ISSUE THREAD

**Issue by mxmartins** [pi-hole/docker-pi-hole#510]
Hello,

Can you please update the Docker Images with the latest released version (4.3.2)?

Thank You.

**Comment by diginc** [comment]
Should have it out tonight, PR: https://github.com/pi-hole/docker-pi-hole/pull/511

**Comment by Erroneuz** [comment]
Heads-up, when updating to latest docker image, which is running Pi-hole Core v4.3.2, the web still runs at 4.3. Pi-hole web has also received an update to 4.3.2: https://github.com/pi-hole/AdminLTE/releases
