### ISSUE TITLE
Pihole does not respond to dchp discover pakets

### ISSUE THREAD

**Issue by rs-development** [pi-hole/docker-pi-hole#518]
- [ ] Request for a new or modified feature
- [X] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
Pihole does not serve DHCP Requests

## Expected Behavior
Pihole does serve a DHCP request with a Response 

## Actual Behavior
Pihole does not serve DHCP Requests

## Steps to Reproduce and debugging done
1. latest pihole docker container in host mode see docker-compose file

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

- tcpdump shows the request does reach the pihole
- I also tried removing the volumes and deleted all containers images and volumes

22:27:33.544500 IP (tos 0x10, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 318)
    0.0.0.0.68 > 255.255.255.255.67: BOOTP/DHCP, Request from e0:98:61:7c:ec:78, length 290, xid 0xd88a2267, secs 682, Flags [none]
	  Client-Ethernet-Address e0:98:61:7c:ec:78
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: Discover
	    Client-ID Option 61, length 7: ether e0:98:61:7c:ec:78
	    MSZ Option 57, length 2: 1500
	    Vendor-Class Option 60, length 18: "android-dhcp-8.1.0"
	    Parameter-Request Option 55, length 10: 
	      Subnet-Mask, Default-Gateway, Domain-Name-Server, Domain-Name
	      MTU, BR, Lease-Time, RN
	      RB, Vendor-Option

## Your Environment 

- Docker version 19.03.3, build a872fc2f86
- docker-compose version 1.24.1, build 4667896b
- f0b44e2c9340        pihole/pihole:latest
- Operating System: Debian GNU/Linux 9 (stretch)
- Kernel: Linux 4.9.0-11-amd64
- Architecture: x86-64

version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Berlin'
      ServerIP: 192.168.0.3
    # Volumes store your data between container upgrades
    volumes:
      - '/srv/appdata/pihole/etc-pihole/:/etc/pihole/'
      - '/srv/appdata/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    restart: unless-stopped

**Comment by UntouchedWagons** [comment]
I too, am having this issue. If I run `netstat -tan | grep 53` I can see the sockets that Pi-Hole creates listening on port 53.

**Comment by jmgascoriego** [comment]
@rs-development could you replace double quotes on network_mode value by single quotes?
