### ISSUE TITLE
systemctl command not found

### ISSUE THREAD

**Issue by rdiazr** [pi-hole/docker-pi-hole#520]
trying to configure dns over https following https://docs.pi-hole.net/guides/dns-over-https/ steps, when i need to create a service, i have not systemctl command.
how can i enable a service in pihole docker image?

**Comment by baysonfox** [comment]
Any OS environment information?

**Comment by rdiazr** [comment]
sorry,

* Docker Host Operating System and OS Version:

QNAP

* Docker Version:

#docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   0bbe3ac
 Built:        Wed Nov 27 03:52:27 2019
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   0bbe3ac
 Built:        Wed Nov 27 03:52:27 2019
 OS/Arch:      linux/amd64
 Experimental: false


* Hardware architecture: 

#uname -a
Linux 4.14.24-qnap #1 SMP Fri Dec 6 11:32:47 CST 2019 x86_64 GNU/Linux

im using that docker image under a QNAP NAS

**Comment by dschaper** [comment]
There's no way to create a service inside a container. (Bar the s6-init system). If you want to have another service like `cloudflared` then you'll need to create another container using an image with `cloudflared` and link the containers.
