### ISSUE TITLE
Connection refused for pihole admin panel on port 80 and ` Unhandled error message (Invalid domain!)` on port 443

### ISSUE THREAD

**Issue by maxiride** [pi-hole/docker-pi-hole#523]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
My `pihole -d` output: https://tricorder.pi-hole.net/tqx82t67n1

The docker-compose.yml I used to deploy pihole, the host ports are intentionally _not typed_ as I wanted random ports to be assigned as I will use Caddy to reverse proxy everything I need and set the randomly assigned ports in my router etc.
```
$ cat docker-compose.yml
version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53/tcp"
      - "53/udp"
      - "67/udp"
      - "80/tcp"
      - "443/tcp"
    environment:
      TZ: 'Europe/Rome'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # run `touch ./var-log/pihole.log` first unless you like errors
    # - './var-log/pihole.log:/var/log/pihole.log'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

## Expected Behavior
Being able to load the PiHole admin page.

## Actual Behavior
I get a connection refused on port 443 and the following error on port 80:
```
[ERROR]: Unable to parse results from queryads.php: Unhandled error message (Invalid domain!)
```

## Possible Fix

I "solved" thanks to this comment https://github.com/pi-hole/pi-hole/issues/2195#issuecomment-486854023
However, pihole should work out of the box and I have no clue what I actually did in applying that edit.

## Steps to Reproduce and debugging done

1. `docker-compose up -d`
2.  `docker ps` to check the randomly assigned ports
3.  try to open the corresponding pages on ports 80 and 443

## Your Environment 
The host machine is a RaspberryPi 3 B+
```
$ docker -v && docker-compose -v
Docker version 19.03.3, build a872fc2
docker-compose version 1.23.2, build 1110ad0
```

**Comment by leviwheatcroft** [comment]
There's a workaround [here from the pihole repo](https://github.com/pi-hole/pi-hole/issues/2195#issuecomment-486854023).
