### ISSUE TITLE
Cannot open Pihole on Docker Web UI 

### ISSUE THREAD

**Issue by giftedsheep** [pi-hole/docker-pi-hole#528]
Hi guys. I have taken on this big project for me (i am a newbie to coding and stuff like that) but i was able to get Docker installed on my Mac mini (running Mac OSX Sierra and Server 5.2) home server and was able to run Pihole. I think its running properly, i tested it with some websites and it seems like the ads are not going through. 
My issue is that i tried logging into the WEB UI with all methods that i could find on google pi.hole/admin, the IP and port... without port. nothing would bring it up. I think it has to do with the ports  because Server APP uses ports 80 and 443, so in the container i set up what i though its forwarding that should resolve the issue. But it still doesn't work. 

![Screen Shot 2019-11-03 at 9 39 18 PM](https://user-images.githubusercontent.com/57340720/68101447-83af0600-fe82-11e9-9a27-59e69b9fa3ce.png)
Please let me know if you can think of a fix. or if im doing something wrong. Below is my docker_run.sh file

```
#!/bin/bash

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

docker run -d \
    --name pihole \
    -e ServerIP=192.168.0.194\
    -p 53:53/tcp -p 53:53/udp \
    -p 8017:80/udp \
    -p 444:443/udp \
    -e TZ="America/Los_Angeles" \
    -e WEBPASSWORD=******\
    -e DNS1=1.1.1.1 -e DNS2=1.0.0.1\
    -v ~/pihole/:/etc/pihole\
    --dns=127.0.0.1 --dns=1.1.1.1 \
    --cap-add=NET_ADMIN\
    --restart=unless-stopped \
    pihole/pihole:latest

printf 'Starting up pihole container '
for i in $(seq 1 20); do
    if [ "$(docker inspect -f "{{.State.Health.Status}}" pihole)" == "healthy" ] ; then
        printf ' OK’
        echo -e "\n$(docker logs pihole 2> /dev/null | grep 'password:') for your pi-hole: https://${IP}/admin/"
        exit 0
    else
        sleep 3
        printf '.'
    fi

    if [ $i -eq 20 ] ; then
        echo -e "\nTimed out waiting for Pi-hole start, consult check your container logs for more info (\`docker logs pihole\`)"
        exit 1
    fi
done;
```

**Comment by dschaper** [comment]
From your snippet it should be http://pi.hole:8017/admin/

**Comment by giftedsheep** [comment]
> From your snippet it should be http://pi.hole:8017/admin/

Unfortunately, No success there, Safari cant find the server.

**Comment by dschaper** [comment]
Does the bare IP work? http://<ip.address>:8017/admin/?

**Comment by dschaper** [comment]
Oh, sorry, just noticed. You mapped 8017 to 80 udp, you need to do tcp instead.

**Comment by giftedsheep** [comment]
Changed to TCP , doesnt seem to resolve the issue

**Comment by giftedsheep** [comment]
> Oh, sorry, just noticed. You mapped 8017 to 80 udp, you need to do tcp instead.

EXCELLENT! Thank you so much! I was able to log in with http://<ip.address>:8017/admin/? 1
