### ISSUE TITLE
Create an Environment Variable to disable "X-Frame-Options" => "DENY"?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [pi-hole/docker-pi-hole#530]
I'm not very schooled in Linux but I was wondering if it's possible to add an environment var to this container to set a true/false value that when set to true disables that in the `lighttpd.conf` file?

More specifically, I want to be able to open the PH webui in Organizr, but PH has:

`"X-Frame-Options" => "DENY"` in `/etc/lighttpd/lighttpd.conf`

I read that it's only a minor security risk to comment that line out. I tried doing it myself, and then mounting the file:

` '/f/Sites/YWeb/.config/Pi-hole/lighttpd.conf:/etc/lighttpd/lighttpd.conf'`

but during container start it'll show this in the log:

> mv: cannot move '/etc/lighttpd/lighttpd.conf' to '/etc/lighttpd/lighttpd.conf.orig': Device or resource busy

and even though according to the log, the rest of PH appears to load, I'm not able to access the webui anymore, and none of my DNS work anymore.

I was wondering if perhaps a container Env Var could be made that allows us to set true or false our choice with that, and basically if set to True it'll load an edited `lighttpd.conf` with that line commented out; if set false, or nothing at all, it loads the original default `lighttpd.conf`?

As I mentioned, I'm pretty nuch a newbie at both Linux and docker so I'm not able to do this myself, I have no idea how to go about it. Could this be added? Or maybe is there just some other way I can do this that I didn't do properly?

Thanks!
Kacey

**Comment by lightswitch05** [comment]
This ticket is a duplicate of #327
