### ISSUE TITLE
Why 443 port is required if no one listens on that port in container

### ISSUE THREAD

**Issue by tomaxsas** [pi-hole/docker-pi-hole#535]
Original pihole on raspberry doesnt specify 443 port as required. Why docker setup needs it, as there is no one listening on that port anyway?

**Comment by diginc** [comment]
https://docs.pi-hole.net/ftldns/blockingmode/

It is a bit of a legacy thing for IP Blocking Mode.  See the disadvantage section there - the 443:433 forward to nothing resolves the timeout on HTTPS ads when IP Blocking mode is enabled.

If not using IP Blocking mode it can safely be removed.

**Comment by tomaxsas** [comment]
Got it! Thanks :)
