### ISSUE TITLE
DNS request from Windows 10 are still going though the router instead of Pi-hole

### ISSUE THREAD

**Issue by Axiol** [pi-hole/docker-pi-hole#539]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

DNS requests should go through Pi-hole

**Actual behaviour:**

DNS requests are still going through my ISP's router

**Steps to reproduce:**

I installed Pi-hole on a Pi with Docker at the IP `192.168.0.100`. As my ISP router won't let me change the DNS and while I'm waiting to get a other router, I changed the DNS in Windows settings

![Annotation 2019-12-01 152412](https://user-images.githubusercontent.com/578111/69915407-c7c80300-144e-11ea-9f9c-f938ee18fea5.png)

Pi-hole itself seems to work as when I open the admin, I can see request coming from Pi-hole directly.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`ro8ocvrjhh`

**Troubleshooting undertaken, and/or other relevant information:**

I already tried to flush the DNS with `ipconfig /flushdns` and rebooted the computer.

**Comment by fvth** [comment]
Windows 10 only accepts DNS over HTTPS. When PiHole isn't setup like this, Windows 10 will most likely not work with PiHole. But there is a fix: https://docs.pi-hole.net/guides/dns-over-https/ (in the official documentation). Which worked for me  at least.

**Comment by dschaper** [comment]
Can you link to some documentation that shows Windows 10 does not use DNS as standard anymore?

**Comment by fvth** [comment]
https://techcommunity.microsoft.com/t5/networking-blog/windows-will-improve-user-privacy-with-dns-over-https/ba-p/1014229 and a source from MS. They are switching from plain DNS to DoH. 

PiHole worked on all android and Linux devices for me. So my problem was windows 10 specific.


⁣BlueMail voor Android downloaden ​

Op 19 jan. 2020 22:16, om 22:16, Dan Schaper <notifications@github.com> schreef:

**Comment by mondeg0** [comment]
Hello, 

I'm facing a similar issue with my new installation of pihole. 

I tried to follow the instruction in the dns-over-https I get the google A table but when I put the cloudflared server (127.0.0.1#5053) in pihole i fail to connect to internet.

Do you have any idea why after adding the cloudflared service to pihole ?
(I'm runing pihole over docker)

Thanks

**Comment by dschaper** [comment]
What cloudflared docker image have you used?

**Comment by mondeg0** [comment]
I'm using a the docker compose file from docker pihole [https://github.com/pi-hole/docker-pi-hole](url) and followed the instructions here: [https://docs.pi-hole.net/guides/dns-over-https/](url).

So docker no docker for cloudflared.

**Comment by dschaper** [comment]
Oh, that won't work. The guide is for non-containerized installations. I'm surprised you were even able to install the cloudflared setup in to the running container?

**Comment by mondeg0** [comment]
No I did manage to setup cloudflare on the server... so what should I do to make it work ?

**Comment by dschaper** [comment]
No, we don't.

**Comment by mondeg0** [comment]
So if i understand write it's impossible to use pihole on windows 10 ?

**Comment by dschaper** [comment]
Windows 10 works fine as a client, but we don't have any instructions on running Pi-hole on Windows 10 as a server.

**Comment by mondeg0** [comment]
Ok maybe I did not explain the setup I have correctly. I have an ubuntu server where I have setup pihole with docker compose, I use it behind a reverse proxy (nginx) and the web interface works perfectly.

But on my windows 10, I try to change the dns with the IP of my server but the ads are not removed... So I found this issue and thought the problem was that windows needed dns over https,
I have installed cloudflared on the server by following the instructions and than my windows was not able any more to access internet...

**Comment by dschaper** [comment]
Windows 10 doesn't need DNS over https, I'm on Win 10 right now and it's all working. 

If you followed the guide then Pi-hole is forwarding it's upstream queries through `cloudflared`. Individual clients are not using `cloudflared` directly. But you shouldn't need `cloudflared` at all for Windows 10.

**Comment by mondeg0** [comment]
Thanks a lot, I figured it out!!!

The problem was coming from firefox where I had the option "avtivate dns over https".
