### ISSUE TITLE
Enable blacklist specification in docker-compose

### ISSUE THREAD

**Issue by mvnixon** [pi-hole/docker-pi-hole#541]
This is a... 

- [x ] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
Handy to have a way to specify additional block-list url's in the .yml docker-compose through an environmental variable or other some such.

## Possible Fix
Additional environmental variables.

## Your Environment 

* Docker Host Operating System and OS Version: Raspberry Pi 4 (swarm)

**Comment by mr-bolle** [comment]
Hi, if you prepare the host volume path ./etc-pihole/ and create a file **adlists.list** with your [Blocking List](https://firebog.net/) with your first run, all your files are available.

[docker-compose.yml](https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose.yml)

```
├── docker-compose.yml
└── etc-pihole
    └── adlists.list
```
