### ISSUE TITLE
Pi-hole repeatedly crashes

### ISSUE THREAD

**Issue by canoben** [pi-hole/docker-pi-hole#555]
This is a... 

- [ ] Request for a new or modified feature
- x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

After running Pi-hole for months without issues, I recently noticed that after logging in as admin I was greeted with a "connection lost" error.

I cleared the container, redownloaded the newest image and restarted the container. It worked yesterday in the evening, but this morning I was greeted again with the "connection lost" error.

Checking Pi-hole's log I noticed that Docker continually tries to restart the container after a crash. Here's what I'm seeing in the log file:

`./run: line 4: 18944 Bus error               (core dumped) s6-setuidgid ${DNSMASQ_USER} pihole-FTL $FTL_CMD > /dev/null 2>&1 | stdout
-- | --
kill: usage: kill [-s sigspec \| -n signum \| -sigspec] pid \| jobspec ... or kill -l [sigspec] | stdout
-- | --
`

This repeats ad infinitum.

## Expected Behavior

Docker container should run normally.

## Actual Behavior

Docker container crashes at start-up.

## Possible Fix

No idea.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Start container using GUI on Synology Docker app
2. Wait a while
3. Container crashes repeatedly.

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Context and extra information

Impossible to use Pi-hole.

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture: 

Docker 18.09 on Synology DSM 6.2.2u4

**Comment by Marcelovk** [comment]
Are you sure your DNS is not open to the internet? I had mine open on port 53 udp, and by closing to only my network fixed the issue. Turns out that I was probably facing an amplification attack

**Comment by hepto** [comment]
I am also seeing this issue recently with the abort every 5-30 mins.  It does not kill my container, but pihole-FTL is constantly being restarted with:

```
./run: line 4: 13796 Aborted                 (core dumped) s6-setuidgid ${DNSMASQ_USER} pihole-FTL $FTL_CMD > /dev/null 2>&1
Stopping pihole-FTL
Starting pihole-FTL (no-daemon) as root
```

Compared to @canoben's issue, and the other issues I have seen reported, the `kill` command is succeeding for me so `pihole-FTL` gets restarted as expected which is presumably why for me the abort is periodic rather than continuous, whereas for others it is not being killed so the abort is more frequent (?).

I've checked the usage on `/dev/shm` and it's about 220k so well within the limit of 64M.

I'm positive I don't have anything exposed to the internet as I don't have any ports exposed, or that there is an internal DNS amplification going on, and there is nothing in the query log to suggest this, but happy to provide more info if needed.

**Comment by canoben** [comment]
I've only one port open for my own cloud on a Synology server.

**Comment by dschaper** [comment]
If it's recently happening then it may be related to pi-hole/FTL#705. Are you using DNSSEC and/or Cloudflare as an upstream?

**Comment by hepto** [comment]
Yes, I am running Cloudflare as an upstream, though via cloudflared running in a different container. And yes I have DNSSEC enabled so that’s sounds exactly like my issue!

Thanks @dschaper I will follow that issue for a resolution. 👍

**Comment by koalalorenzo** [comment]
Same issue here, using Cloudflare with DNSSEC. Disabling DNSSEC solves the issue for now, but I wish I could enable it so keep this issue open plz! 😓

**Comment by kerberjg** [comment]
Same issue, not using Cloudflare or DNSSEC

**Comment by dschaper** [comment]
Then it's not the same issue.

Open a new issue and fill out the template please.
