### ISSUE TITLE
CONDITIONAL_FORWARDING[...] env variables not respected

### ISSUE THREAD

**Issue by HunterDG** [pi-hole/docker-pi-hole#557]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

CONDITIONAL_FORWARDING environment variables passed via docker run or docker-compose are visible in admin ui but not respected.

## Expected Behavior

Conditional forwarding environment variables should be respected

## Actual Behavior

queries to conditional forwarding domains are blocked by pi-hole/not forwarded until settings are manually saved (not modified) in admin UI

## Steps to Reproduce and debugging done

1. delete/disable etc-pihole volume/bind mount if exists
2. run container with conditional forwarding parameters
3. flush test device's dns cache
4. query for host in conditional forwarding domain, get NXDOMAIN response
5. in pi-hole admin ui, navigate to settings>dns and press "save" button
6. query again, get valid response.  

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: macOS (latest)
* Docker Version: Docker Desktop for Mac (latest)
* Hardware architecture:  x64

**Comment by crawford** [comment]
I'm seeing this behavior as well. Unfortunately, manually saving the settings is not sufficient in my case due to my use of `CONDITIONAL_FORWARDING_REVERSE` (I'm forwarding reverse lookups for a /16, rather than the default /24).

**Comment by dgholz** [comment]
For me, I noticed this when my `/etc/pihole/setupVars.conf` looked like:
```
[…]
CONDITIONAL_FORWARDING=
CONDITIONAL_FORWARDING_IP=
CONDITIONAL_FORWARDING_DOMAIN=
CONDITIONAL_FORWARDING_REVERSE=
```

Because `start.sh` sources `/etc/pihole/setupVars.conf` [via `prepare_configs`](https://github.com/pi-hole/docker-pi-hole/blob/931aad4cb14a9dbbfefb35902a37b251826f6999/bash_functions.sh#L68) [before setting config values from environment variables](https://github.com/pi-hole/docker-pi-hole/blob/931aad4cb14a9dbbfefb35902a37b251826f6999/start.sh#L47), it will never update a setting that already exists, even if it's blank.

I deleted the `CONDITIONAL_FORWARDING*` vars from my `setupVars.conf` and saw the environment variables correctly applied as settings the next time I started the container.

**Comment by HunterDG** [comment]
@dgholz can you try deleting your etc/pihole directory/volume? I have this problem with fresh volume.

**Comment by ahuffman** [comment]
I have the same issue here.  Env vars are not being taken if values exist in setupVars.conf.  

The startup process should probably read the set env vars, right them to setupVars.conf, and then source the setupVars.conf to add/merge the settings.

Quick work around is to `echo > /etc/pihole/setupVars.conf` to empty the config and restart the container/pod.

**Comment by dschaper** [comment]
> The startup process should probably read the set env vars, right them to setupVars.conf, and then source the setupVars.conf to add/merge the settings.

I like that!

**Comment by dschaper** [comment]
Other idea would be to do a bash version of an `isset`.

**Comment by ahuffman** [comment]
It would be really cool to get all the settings available in setupVars.conf as Env vars as well, such as `ADMIN_EMAIL`, `TEMPERATUREUNIT`, etc.  One more nit here, is the Docker Hub README.md does not contain all the available env vars. :). thanks for this project, it's fantastic.

**Comment by dschaper** [comment]
> It would be really cool to get all the settings available in setupVars.conf as Env vars as well

Fully agree.

**Comment by black-snake** [comment]
I've now really checked my configuration multiple times, googled and didn't succeed: I have the same problem as originally described in this bug report.

I have a `docker run` command with

```
-e REV_SERVER='True' \
-e REV_SERVER_TARGET='192.168.255.1' \
-e REV_SERVER_DOMAIN='fritz.box' \
-e REV_SERVER_CIDR='192.168.255.0/24' \
```

but when I run `cat /etc/dnsmasq.d/01-pihole.conf` after (re-) starting of the container, I see:
```
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Dnsmasq config for Pi-hole's FTLDNS
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

###############################################################################
#      FILE AUTOMATICALLY POPULATED BY PI-HOLE INSTALL/UPDATE PROCEDURE.      #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#        IF YOU WISH TO CHANGE THE UPSTREAM SERVERS, CHANGE THEM IN:          #
#                      /etc/pihole/setupVars.conf                             #
#                                                                             #
#        ANY OTHER CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE           #
#                    WITHIN /etc/dnsmasq.d/yourname.conf                      #
###############################################################################

addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list


localise-queries


no-resolv



cache-size=10000

log-queries
log-facility=/var/log/pihole.log

log-async
server=1.1.1.1
server=1.0.0.1
server=2606:4700:4700::1111
server=2606:4700:4700::1001
interface=eth0
```

Once I click save in the web UI under Settings -> DNS and I run `cat /etc/dnsmasq.d/01-pihole.conf` afterwards, I see:
```
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Dnsmasq config for Pi-hole's FTLDNS
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

###############################################################################
#      FILE AUTOMATICALLY POPULATED BY PI-HOLE INSTALL/UPDATE PROCEDURE.      #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#        IF YOU WISH TO CHANGE THE UPSTREAM SERVERS, CHANGE THEM IN:          #
#                      /etc/pihole/setupVars.conf                             #
#                                                                             #
#        ANY OTHER CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE           #
#                    WITHIN /etc/dnsmasq.d/yourname.conf                      #
###############################################################################

addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list


localise-queries


no-resolv



cache-size=10000

log-queries
log-facility=/var/log/pihole.log

log-async
server=1.1.1.1
server=1.0.0.1
server=2606:4700:4700::1111
server=2606:4700:4700::1001
dnssec
trust-anchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D

interface=eth0
rev-server=192.168.255.0/24,192.168.255.1
server=/fritz.box/192.168.255.1
server=//192.168.255.1
```

Then conditional forwarding finally works (until the container is restarted)...

I would really appreciate a fix for this.

Thanks for your engagement.
