### ISSUE TITLE
Gow to update linuxservers docker version?

### ISSUE THREAD

**Issue by BoBBer446** [pi-hole/docker-pi-hole#563]
Hey, i did not found the pi-hole repo here? But in offical repo from libre elec is can install it.
But the Version is out of date:
Pi-hole Version v3.3.1 (Update available!) Web Interface Version v3.3 (Update available!) FTL Version v3.0 (Update available!)

i can update lastest docker:

```
LibreELEC:~ # docker pull pihole/pihole
Using default tag: latest
latest: Pulling from pihole/pihole
7673d18d2eef: Pull complete
a4896c184ff4: Pull complete
f1860d529eec: Pull complete
cd51115d771b: Pull complete
495bdd313aea: Pull complete
a700aebfcd6f: Pull complete
e9e1729f7539: Pull complete
472c32e9da06: Pull complete
Digest: sha256:6334fa34207b4f31d91f9ea488fd6d39e26e0d8847be2555202296496565405e
Status: Downloaded newer image for pihole/pihole:latest
```
but i cant update pi hole:

```
LibreELEC:~ # pihole -up
-sh: pihole: not found
```
can anybody help me?

**Comment by dschaper** [comment]
Linuxservers is at https://github.com/linuxserver. We don't make that image.

Our latest image is at https://hub.docker.com/r/pihole/pihole

You can not upgrade `pihole` inside the docker container, you pull the latest image instead.
