### ISSUE TITLE
DNS1/DNS2 environment variables vs YAML "dns" keys

### ISSUE THREAD

**Issue by rgov** [pi-hole/docker-pi-hole#566]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

The README describes two ways of defining DNS servers. For the YAML file there is a `dns` key which has a list of DNS servers, the first of which should be 127.0.0.1. But then there is also a `DNS1` and a `DNS2` environment variable defaulting to 8.8.8.8 and 8.8.4.4.

Could you explain more about how these relate? I've seen comments on GitHub that suggest `DNS1` should be set to `127.0.0.1` also, but that doesn't align with what the default value is.

**Comment by shaderecker** [comment]
DNS1 & DNS2 are environment variables and specify the upstream DNS servers to which your clients traffic is forwarded (Pi-hole functionality).
The YAML dns keys are the DNS servers for the container itself (Docker functionality).

**Comment by thrubovc** [comment]
is my understanding of this correct?:
DNS1 & DNS2 are the upstream DNS servers that pihole gets name resolution from.
the two yaml dns keys are the DNS servers that docker gets name resolution from...? the first one is localhost (which are in fact the DNS1 & DNS2 servers within pihole) and the second one is a backup for those? so in fact I have 3 DNS servers in total?

**Comment by shaderecker** [comment]
> DNS1 & DNS2 are the upstream DNS servers that pihole gets name resolution from.
> 
Yes, upstream is right. The pihole resolves DNS queries from its clients using these servers.

> the two yaml dns keys are the DNS servers that docker gets name resolution from
>
These are the DNS servers inside the docker container.
You can check in the container with e.g. (the name of my container is pihole)
```
pi@raspberrypi:~ $ docker exec -it pihole /bin/bash
root@raspberrypi:/# cat /etc/resolv.conf
nameserver 127.0.0.1
nameserver 1.1.1.1
```

> the first one is localhost (which are in fact the DNS1 & DNS2 servers within pihole) and the second one is a backup for those?
>
See here: https://hub.docker.com/r/pihole/pihole/
![image](https://user-images.githubusercontent.com/16366556/76901065-d372f480-689a-11ea-9a7c-37f964f533c4.png)

> so in fact I have 3 DNS servers in total?
>
It depends on what functionality you are looking at:

1. I mean you have 2 DNS servers which serve your clients (DNS1 & DNS2).
2. And then you have your container internal DNS servers (yaml --dns keys).
The first yaml key points to localhost as you stated before and the second one is optional. You don't need it necessarily.
And those are only for the container system, not serving your clients.
