### ISSUE TITLE
How to add this filterlist to pi-hole?

### ISSUE THREAD

**Issue by BobWs** [pi-hole/docker-pi-hole#567]
Hi,
I tried to add this filterlist to pi-hole but I get an error in the logfile that the format isn't supported.
How can I add the list to the filters?
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

`
  [i] Target: adguardteam.github.io (filter.txt)`
  `[✓] Status: Retrieval successful`
 ` [✗] Format: Adblock (list type not supported)`

**Comment by PromoFaux** [comment]
Simply put: You don't :)

That type of list is for browser-based blockers, and not DNS. From the [README on the repo](https://github.com/AdguardTeam/AdguardSDNSFilter) that list is from:

>Please note, that to use this filter it is necessary to support basic ad blocking rules syntax. It does not make much sense to extract just the hosts file.
