### ISSUE TITLE
The docker image for :latest is still outdated at 4.3.2, even though docker hub shows it updated

### ISSUE THREAD

**Issue by TheGITofTeo997** [pi-hole/docker-pi-hole#580]
This is a... 

- [ ] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [x] Issue trying to build / test / develop the docker image

## Description

Hello, so basically i am running the official docker image of PiHole, but unluckily it can't be updated apparently

## Expected Behavior

The expected behaviour is to pull the :latest image from docker hub, which should spawn a new updated container

## Actual Behavior

When docker pulling, the system says the image is already up to date, but it's not, and it still spawns a container of the outdated 4.3.2, maybe the package is still old

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.
2. 
3. 
4. 

## Debug steps I have tried

Deleted all, container, image and did it from scratch, but it's still outdated

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Raspbian Buster as host, latest updates
* Docker Version: latest one as of now, i don't remember the number
* Hardware architecture:  ARM, on raspberry pi3

**Comment by PromoFaux** [comment]
`dev` has just been updated, we still need to merge the following PR:

https://github.com/pi-hole/docker-pi-hole/pull/577

Waiting on @diginc for his guidance before that happens though. Please bear with us...

**Comment by TheGITofTeo997** [comment]
@PromoFaux Oh, i'm sorry i didn't know this. Alright, don't worry and take the time needed.

**Comment by modem7** [comment]
Will this include the new 4.4 core in the update?

**Comment by PromoFaux** [comment]
It will do, there is a PR for 4.4 into `dev`, but just working through why the tests are failing:
https://github.com/pi-hole/docker-pi-hole/pull/581

**Comment by TheGITofTeo997** [comment]
Issue has been fixed and now latest is up to date
