### ISSUE TITLE
Dockerhub arm64 has wrong architecture

### ISSUE THREAD

**Issue by bernerha** [pi-hole/docker-pi-hole#588]
This is a...

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
I'm trying to pull the latest image from hub.docker for a raspberry 64bit and i get following message:
```
Trying to pull docker.io/pihole/pihole:v4.4-arm64...
  Image architecture mismatch: image uses "amd64", expecting "arm64"
```

## Expected Behavior
Image gets pulled

## Actual Behavior
Image doesn't get pulled

## Possible Fix
Set the correct os architecure

## Steps to Reproduce and debugging done
1. podman pull pihole/pihole:v4.4-arm64

## Debug steps I have tried
- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Linux 5.5.0-1-ARCH aarch64 GNU/Linux
* Docker Version:
```
podman
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.6
Git Commit:         b7ce1157b00af09f4a09e39b377aa3abff46ee05-dirty
Built:              Sat Jan 11 19:05:35 2020
OS/Arch:            linux/arm64
```
* Hardware architecture: ARM64

**Comment by denisok** [comment]
> skopeo inspect docker://docker.io/pihole/pihole:v4.4-armhf | jq

>   "Created": "2020-02-26T18:38:53.171294428Z",
>   "DockerVersion": "17.09.0-ce",
>   "Labels": {
>     "image": "pihole/pihole:v4.4_armhf",
>     "maintainer": "adam@diginc.us",
>     "url": "https://www.github.com/pi-hole/docker-pi-hole"
>   },
>   "Architecture": "amd64",
>   "Os": "linux",

returns "Architecture": "amd64"  and podman fails.
Fixed here: https://github.com/containers/image/pull/804

Should be fixed from podman 1.8.0: https://github.com/containers/libpod/blob/v1.8.0/go.mod#L15

I have podman 1.8.2 and now it is just info:
> INFO[0002] Image architecture mismatch: image uses "amd64", expecting "arm"

**Comment by dschaper** [comment]
I think you can just pull `pihole/pihole:v4.4`. That's the multiarch build. Pulling the specific architecture will get the image without the proper metadata. Not sure if this is intended or if there's a further tweak needed. @diginc 

```plain
docker run --rm mplatform/mquery pihole/pihole:v4.4
Image: pihole/pihole:v4.4
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm64
   - linux/arm/v6
   - linux/arm/v7
```

```plain
docker run --rm mplatform/mquery pihole/pihole:v4.4-armhf
Image: pihole/pihole:v4.4-armhf
 * Manifest List: No
 * Supports: amd64/linux
```

**Comment by bernerha** [comment]
Works for me.
