### ISSUE TITLE
pihole website is broken if using domain

### ISSUE THREAD

**Issue by Sveeeeeen** [pi-hole/docker-pi-hole#589]
Hello,

I have a new pihole container running. I can access the web interface over the IP and over the domain name "sub.domain.tld/admin". HTTP and HTTPS.

If I open the IP address in my browser everything is working fine. http://ip.here show me a pretty pihole website.

But when I try to open the same page with the domain, I just see a broken page. The resources are not loaded.

Website I visit: https://sub.domain.tld/
Resources loaded from: https://pi.hole/admin

Of course, it will fail since I do not have the SSL cert for pi.hole. Why is pihole changing the resource domain? How can I force pihole to load the resources always from the origin domain?

Thank you for your help!

**Comment by Ullarah** [comment]
Could be a number of different issues.  Make sure that the /etc/hosts file inside the container knows what domain to associate the IP address to.  It's also a good idea to update the same file on the host machine.  Once you've done that, run gravity.sh inside the container.

Another thing to check is your rewrite rules, for my configuration I use NGINX as a reverse proxy and pass http://ip.here/admin to https://pihole.example.tld with no issues.

```
location / {
    proxy_pass       http://192.168.5.190:8090/admin/;

    proxy_set_header Host            $host;
    proxy_set_header X-Real-IP       $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

**Comment by Sveeeeeen** [comment]
> Could be a number of different issues. Make sure that the /etc/hosts file inside the container knows what domain to associate the IP address to. It's also a good idea to update the same file on the host machine. Once you've done that, run gravity.sh inside the container.

I could do that. But in my opinion it's not the correct way. I do not own the domain "pi.hole". I can not get a SSL cert for it. Why should I add it to my IP?

> Another thing to check is your rewrite rules, for my configuration I use NGINX as a reverse proxy and pass http://ip.here/admin to https://pihole.example.tld with no issues.
Its not a problem with

I am also using Nginx-proxy as reverse proxy.
```
upstream sub.domain.tld {
                        # pi-hole container
                        server 172.17.0.5:80;
}

server {
        server_name sub.domain.tld;
        listen 80 default_server;
        access_log /var/log/nginx/access.log vhost;
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://sub.domain.tld;
        }
}
```

Now calling http://public-ip.here I get the fancy website. (because it's the default_server) 
Calling http://sub.domain.tld the HTML returns the wrong domain name for resources (server_name).

Why is the response different?
