### ISSUE TITLE
PI-HOLE stands on OMV and raspberry PI

### ISSUE THREAD

**Issue by galbeida** [pi-hole/docker-pi-hole#590]
Hi everyone, 

I've been trying to get pihole working for a while, but I always run into the same problem. I have assigned the ipserver 192.168.1.200, if I put in the browser 192.168.1.200/admin I can access the web, the problem is that my router does not allow me to change my DNS, so I go to my PC and I put it as DNS1 192.168 .1.200 and in DNS2 1.1.1.1 Everything works fine but at first I stop browsing, I try to ping from my PC to IP 192.168.1.200 and I have no answer. I try to access in the browser and it does not work, I have to delete the docker image and start again, in my router if I see a computer with the ip 192.168.1.200 (which is pihole) but I cannot ping from any computer, any ideas ?

 I use OMV 4.1.35-1 on a raspberry pi 4, although I also tried it on omv 5 and had the same problem. The PI has the fixed ip 192.168.1.150 and the router 192.168.1.1, there are no more computers on the network with the ip 192.168.1.200.

 Greetings

**Comment by naked123** [comment]
use macvlan

change your omv port to anything else other than 80

i am on omv5 with pihole + unbound in docker
