### ISSUE TITLE
Expose ability in docker container to specify php memory

### ISSUE THREAD

**Issue by evanrich** [pi-hole/docker-pi-hole#592]
Running the latest container here, on kubernetes.  I've given the pod a request of 256MB( raised to 1G), and a limit of 4G of ram, yet when the container runs, and I click on certain things like "long query" or "show all" in query log, I get an error "An unknown Error has occured". Looking at lighttpd error log, I see this

```
 Allowed memory size of 134217728 bytes exhausted (tried to allocate 16777224 bytes) in /var/www/html/admin/api_db.php on line 172
2020-03-24 19:09:42: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16777224 bytes) in /var/www/html/admin/api_db.php on line 172
```

Can you expose a variable to set for PHP memory usage?

**Comment by dannytsang** [comment]
I would also like this feature. I have also run into errors running queries.

Something like exposing a variable which can be set on a startup script prior to starting the webserver.

**Comment by dschaper** [comment]
Inside the container, at `/etc/php/7.0/cgi/php.ini` is `memory_limit = 128M` where you'd make the change. For now you might be able to volume map that file to something better for your environment.

I'm not sure if setting that value to `-1` in the image would work, that tells PHP to use all available. If you use that as the value then you could set the container's available memory and see if that's stable.

**Comment by BenMatheja** [comment]
I was also just wondering how to go on from here. Editing it inside the container will work for some time but will get overridden at next pull

**Comment by stephdl** [comment]
I hit myself this bug too, when I do a `Long term data > Query log`  more than the week, then I have this message in lighthttpd log

`FastCGI-stderr: PHP Fatal error: Allowed memory size of 134217728 bytes exhausted`

php.ini of cli is set to unlimited (-1), cgi php.ini is set to 128MB, it is not enough, either add a env Var or set to unlimited

**Comment by stephdl** [comment]
same issue here : https://github.com/pi-hole/docker-pi-hole/issues/595
