### ISSUE TITLE
Pass DHCP settings to container..

### ISSUE THREAD

**Issue by tbone2k-git** [pi-hole/docker-pi-hole#598]
This is a... 
- [ ] Request for a new or modified feature
- [X] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I try to activate the DHCP server and pass DHCP settings to pihole when running the container (for the first time and on).. Variables like "SERVERIP" or "WEBPASSWORD" seem to be documented and working fine when passing them into the container, "DHCP_ACTIVE" or DHCP_START/END seem to be ignored, although they seem to live in the same area in the code or the config file involved.
https://github.com/pi-hole/AdminLTE/blob/347994db169eb486954cbcff6f62955c77c1db4a/settings.php#L11

## Expected Behavior
PiHole using DHCP settings passed to the container via docker env option.

## Actual Behavior
PiHole does not seem to care, DHCP settings are still at default.

## Possible Fix
Not sure. o)

## Steps to Reproduce and debugging done
This is the service I defined in a docker-compose.yml.

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: xxx
    mac_address: xxx
    cap_add:
      - NET_ADMIN
    networks:
      pihole_network:
        ipv4_address: 192.168.0.6
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      DNS1: 192.168.0.2
      DNS2: ""
      ServerIP: 192.168.0.3
      ServerIPv6: ""
      VIRTUAL_HOST: pihole.xxx.net
      WEBPASSWORD: "password"
      TZ: "Europe/Amsterdam"
      DHCP_ACTIVE: 1
      DHCP_START: 192.168.0.111
      DHCP_END: 192.168.0.211
      DHCP_ROUTER: 192.168.0.2
      PIHOLE_DOMAIN: "xxx.xxx"

## Debug steps I have tried
None

- [X ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ X] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [X ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [X ] I have searched this repository for existing issues and pull requests that look similar 

## Context and extra information
My final goal is, to just put env variables into the docker-compose.yml, to have all IP configuration in once place and to avoid entering PiHole settings manually for each machine the container is to be run on.

## Your Environment 
RaspberryPi 3b + Raspbian Buster
* Docker Version: 19.03.8, build afacb8b
* Hardware architecture: ARM

Any feedback appreciated! o) Thank you!
ps:
Some folks on the web had the same issue, I found at least one person also using the DHCP_* variables in his docker-compose.yml, wonder if it worked for him or is actually not meant to be working at all.

**Comment by tbone2k-git** [comment]
I digged some more, it seems there is just no usage/support of all the DHCP_* variables in start.sh and bash_functions.sh -> prepare_configs(). So this cannot work.

Sorry for opening an issue first, I dealt with this for days, but opening the issue kinda helped to find the cause myself. Thank you! o)

Wouldn't it make sense to add support for the DHCP_* settings there?
Is there somebody with an opinion on that? o)

**Comment by ionutz89** [comment]
Any update on this ticket? I am trying to parse all dhcp variables on docker images but it seems to ignore it.

Any plan to fix this issue?

**Comment by tbone2k-git** [comment]
I guess they all moved on.. o)
I attempted to fix the problem by creating my own pihole image from this one and "just" adding missing configuration steps in my own image, but at that time it seemed not easily possible with docker (there is only one entrypoint you can run or something).
If anyone can help with this issue, I'd appreciate the input.

**Comment by ionutz89** [comment]
One way will be to have ready setupVars.conf prepared in and mounted /etc/pihole on your docker run.

It is working for me.

**Comment by PromoFaux** [comment]
I guess there is nothing to stop us from adding them as env variables, to be sourced, and stored in setupvars.conf (if they are not blank - similar to the others) here:

https://github.com/pi-hole/docker-pi-hole/blob/master/start.sh

And as @ionutz89 mentions, you can also just mount the `/etc/pihole` directory as a volume (or even just `setupVars.conf`) to persist it between restarts. I don't know enough about k8s to know what is going on there....

**Comment by ionutz89** [comment]
Can we ask this as a feature request? or what we should add this on your road map? @PromoFaux

**Comment by PromoFaux** [comment]
Can take a look at it if I remember later on.. though Pull requests welcome :)

**Comment by tbone2k-git** [comment]
I'd like this to work for the first run of the container, when pihole sets itself up.
Having the DHCP settings persistent later on (after using the pihole web-admin or by replacing files manually in the volume) wasn't the problem for me iirc. The setup just does not care about injected env-vars related to DHCP, it only looks into all the DNS related variables to build the pihole config files.

**Comment by PromoFaux** [comment]
That's because `start.sh` does not know about the `DHCP_` variables to be able to do anything with them. By adding them to that file, we should also be able to solve your issue.

**Comment by tbone2k-git** [comment]
Your welcome. o)
Yes, I think the pihole image itself (the setup routine for first container run) needs some work.  As far as my understanding goes, I could fork the image and re-upload a custom version, but I think this route is a bad one, since no one would care (about) it.

But i'd still think there must be a way to have an image run its setup and just add to it, I mean how do images build upon each other in the docker space if this is not possible? Anyway, thank you! o)

**Comment by PromoFaux** [comment]
Added here : https://github.com/pi-hole/docker-pi-hole/pull/769
