### ISSUE TITLE
pihole FTL restarting without cache

### ISSUE THREAD

**Issue by r2ixuz** [pi-hole/docker-pi-hole#612]
If setting cache-size=0 at 01-pihole.conf when DNSSEC validation at Pihole is activated the FTL daemon is constantly restarting. Resetting the value to 10000 let the FTL daemon running as normal again.

Latest Docker realse v5: `Pi-hole Version vDev (release/v5.0, v4.3.5-89-ge728d7f) Web Interface Version vDev (release/v5.0, v4.3.2-158-gb6d3d6c) FTL Version vDev (release/v5.0, vDev-c499c17)`

**Comment by DL6ER** [comment]
Disabling the cache with DNSSEC enabled is not possible. You should see a warning in `pihole.log`.

> Because the DNSSEC validation process uses the cache, it is not permitted to reduce the cache size below the default when DNSSEC is enabled.

http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html

**Comment by r2ixuz** [comment]
Ok sorry, thought it is due to the new version. :-) Thanks.
