### ISSUE TITLE
Pi-Hole v5.0 upgrade guide

### ISSUE THREAD

**Issue by zenman94** [pi-hole/docker-pi-hole#616]
Did you plan to publish some guidelines to upgrade docker-pi-hole to v5.0 ? 

It seems that a simple run of new docker image don't work.

/var/log/pihole-FTL.log grows up quickly with this message : 
```
dquery("UPDATE....") called but database is not available!
```

Thanks

**Comment by drio** [comment]
@zenman94 The upgrade guide worked for me: https://github.com/pi-hole/docker-pi-hole#upgrading--reconfiguring. 

What errors are you seeing?

**Comment by zenman94** [comment]
@drio my container was automaticaly upgraded by Ouroboros and this don't work, the docker volume is filled to saturation, but anything was launched. I will try manually and remove the docker volume before launch new container. Thanks for putting me in the right direction.

**Comment by zenman94** [comment]
tonight the docker volume for pihole grows up to 80Go. It seems to do the same thing now 
`4981f357e126        pihole/pihole                      "/s6-init"               7 minutes ago       Up 6 minutes (unhealthy)                                                                                pi-hole             1.66GB (virtual 1.95GB)`

I don't see error in log : 
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
 ::: Starting docker specific checks & setup for docker pihole/pihole
OK: Checks passed for /etc/resolv.conf DNS servers

nameserver 127.0.0.1
nameserver 1.1.1.1
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u7

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chown: cannot access '': No such file or directory
chmod: cannot access '': No such file or directory
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
Custom WEB_PORT set to 8081
INFO: Without proper router DNAT forwarding to 192.168.2.2:8081, you may not get any blocked websites on ads
::: Pre existing WEBPASSWORD found
Using custom DNS servers: 1.1.1.1 & 1.0.0.1
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "192.168.2.2",
			"VIRTUAL_HOST" => "192.168.2.2",
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
[...]
https://zerodot1.gitlab.io/CoinBlockerLists/hosts
`

**Comment by zenman94** [comment]
Ok with a bash I see /var/log/pihole-FTL.log that grows up quickly : 
```
dquery ("UPDATE....") called but database is not available!
```

**Comment by diginc** [comment]
Did you attempt a fresh container / volume? Not ideal I know but sometimes when things go wrong we don't have a choice.

**Comment by zenman94** [comment]
Yes I have removed the old one before start with the new docker image.

**Comment by drio** [comment]
@zenman94 What commands are you running to perform the upgrade?

**Comment by zenman94** [comment]
docker pull pihole/pihole 
docker-compose stop pihole
docker-compose rm -f pihole
change image in docker-compose.yml
docker-compose up -d pihole

**Comment by diginc** [comment]
Please move your old volume contents to a new location and try again.

If that doesn't work, what hardware are you on and what does your docker-compose.yml look like?

**Comment by zenman94** [comment]
The host is a Synology NAS with Docker 18.09.8. I use two config volume : /etc/pihole and /etc/dnsmas.d.

I retry the v5.0 but before I removed the pihole-FTL.conf and pihole-FTL.db from my shared config volume. Now PiHole seems to start. 
I'll keep you posted in a few minutes

**Comment by zenman94** [comment]
That's work ! 
Maybe something was stuck in the piholeFTL configuration.

Thanks all for your help.
