### ISSUE TITLE
Add/Enable/Make a guide for HTTPS

### ISSUE THREAD

**Issue by Ryonez** [pi-hole/docker-pi-hole#617]
This is a... 

- [x] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

Not sure here, marking two.

## Description

I'm trying to get https working with the docker image, mostly for secure access to the admin console. I do have certs I can give it.

## Expected Behavior

A guide for setup with docker/For it to work out of the box.

## Actual Behavior

there doesn't seems to be any https enable, browser returns `Unable to connect`. (Using firfox)

## Possible Fix

Not sure.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Run the docker image
2. Try to connect over https to it.

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 
Couldn't really find anything dealing with it, possibly under something with a odd name or an old issue somewhere. I didn't spot anything myself.

## Context and extra information

To access the admin console securely. 

## Your Environment 

* Docker Host Operating System and OS Version: unRaid 6.8.3
* Docker Version: 19.03.5, build 633a0ea838
* Hardware architecture: x86

**Comment by dschaper** [comment]
Best solution would be the Docker way and use a reverse proxy container in front of things.

**Comment by Ryonez** [comment]
I can't use my reverse proxy to achieve this. To get proper access over the network I give it it's own ip (The server host docker provides web access so pihole can't use those ports). If I use a proxy in this instance then all it does is "look" secure, but the traffic between the proxy and pi-hole would still be http over my lan network.

To note, the proxy normally server my other contain using a network only they can access. The pihole contain is the only one outside of this network.

**Comment by diginc** [comment]
I wouldn't recommend using any proxies outside of docker with docker containers, that would be highly uncommon.  If you have the need for a proxy outside of docker I'd leave it in charge of non-docker stuff only and jump aboard the docker https proxy train for any docker containers.

Traefik is a docker proxy that can do HTTPS, container discovery to avoid static IPs in docker, and much more.  Any unencrypted traffic would stay within docker's internal networks, encrypting trusted networks like that is overkill.

We just updated the docs for Traefik v2 + Docker Pi-hole here https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose-traefik-proxy.md

**Comment by Ryonez** [comment]
> I wouldn't recommend using any proxies outside of docker with docker containers

That why I'm requesting for https support for the pihole container. And also why I said "I can't use my reverse proxy to achieve this". The connection just wouldn't be secure.

> Traefik is a docker proxy that can do HTTPS

I use the letsencrypt by linuxserver, it's working fine.

> container discovery to avoid static IPs in docker

Only pihole has a static ip, as the server is serving websites. I don't use static ip's elsewhere.

> Any unencrypted traffic would stay within docker's internal networks, encrypting trusted networks like that is overkill.

And it does, apart from pihole, which needs it's own ip. That's why I'm requesting https support for this docker. If it was at least self certed, I could pipe it though the proxy and have it secure and served under a proper cert through my browser.

I'll be honest, I don't really follow that compose config that well. While I could probably figure it out after a while, I'm not looking to change my reverse proxy right now.

**Comment by diginc** [comment]
> I use the letsencrypt by linuxserver, it's working fine.

This looks like it is a HTTPS enabled docker reverse proxy.  Wouldn't that serve the purpose securely?

>  the traffic between the proxy and pi-hole would still be http over my lan network.

If your letsencrypt proxy container is connected using docker networking to pihole, the traffic stays within docker - not reaching your LAN unencrypted ever since docker's networking is isolated.

**Comment by Ryonez** [comment]
> If your letsencrypt proxy container is connected using docker networking to pihole, the traffic stays within docker - not reaching your LAN unencrypted ever since docker's networking is isolated.

It's not on the same network, pihole has it's own ip and isn't touching the docker network my reverse proxy is in.

**Comment by diginc** [comment]
Containers can have more than one network, so you could add the reverse proxy network to pihole or vise versa to fix that.  Or do you mean they're not on the same host?

**Comment by Ryonez** [comment]
No they are on the same host. Unraid's docker gui only lets you select on network though, not sure about connecting it to both.

Let me see if I can find what I need to say to pihole to add it to the other network.

**Comment by Ryonez** [comment]
```
/usr/bin/docker: Error response from daemon: Container cannot be connected to network endpoints: br0, docker-secure.
See '/usr/bin/docker run --help'.
```

Nope, did not work

**Comment by dschaper** [comment]
Have a look through the guides of https://www.youtube.com/channel/UCZDfnUn74N0WeAPvMqTOrtA/search?query=https to get some ideas of how to use Docker on unraid.

**Comment by Ryonez** [comment]
Do you maybe have a specific video in mind?
His pihole setup uses a bridge and static ip like mine, and the reverse proxy video uses a custom network and doesn't touch pihole.

Btw, the error above is dockers response to me trying to give it two networks. It's not so much an issue with knowing how to use docker on unRaid, but getting docker to give the container two networks.

**Comment by dschaper** [comment]
[How to Setup and Configure a Reverse Proxy on unRAID with LetsEncrypt & NGINX](https://www.youtube.com/watch?v=I0lhZc25Sro)

**Comment by Ryonez** [comment]
> the reverse proxy video uses a custom network and doesn't touch pihole.

Please read my messages.

And yes, his videos are very good.

**Comment by dschaper** [comment]
Then the next step would be to ask on the unRAID forums how to get the Pi-hole template to work on multiple networks. The limitation seems to be with unRAID and the template instead of the Pi-hole image. There's no plan or need to have the Pi-hole docker image add dependencies or configuration to do TLS on it's own.

**Comment by Ryonez** [comment]
The idea to add it to the network does seems like a good idea, but docker itself is throwing the error when I try to add it. 

I'm confident enough to tell docker what to do, even with the template and web gui, I just need to know what to tell it to add it to another network so it has two.

**Comment by dschaper** [comment]
> I'm confident enough to tell docker what to do, even with the template and web gui, I just need to know what to tell it to add it to another network so it has two.

That is where unRAID forums will be the best place to ask.

**Comment by Ryonez** [comment]
Alright, I'll try there then. Thank you.

**Comment by diginc** [comment]
Can you make them all in the same custom docker network instead of specifying multiple?

**Comment by Ryonez** [comment]
No, pi-hole needs it's own ip, so it has it's own presence on the lan. It cannot use the servers address.

**Comment by Panderine** [comment]
> No, pi-hole needs it's own ip, so it has it's own presence on the lan. It cannot use the servers address.

You need a whole new network only for Pihole or just want it to have a static IP and DHCP for the rest of the containers?. I have just finished setting up pihole in the same network as the rest of my containers and traefik doing TLS termination for all of them (including pihole). My pihole container has a static ip and so I can use it as DNS server for my whole network (both physical though port publishing in host AND docker containers though pihole container's static ip).

Is this what you are trying to achieve?

**Comment by dschaper** [comment]
@Panderine Do you have the configuration documented somewhere?

**Comment by Ryonez** [comment]
> My pihole container has a static ip and so I can use it as DNS server for my whole network (both physical though port publishing in host AND docker containers though pihole container's static ip).

Almost. I don't need it for the containers, but the reverse proxy container needs to see it through the docker network so I can secure the admin interface.

If I could, what is the docker run command you use for your pi-hole?

**Comment by Panderine** [comment]
> @Panderine Do you have the configuration documented somewhere?

I don't but basically:

**Network creation:**

`docker network create --subnet=172.18.0.0/16 --gateway=172.18.0.1  --ip-range=172.18.1.0/24 webproxy
`
The trick is with --ip-range this define where your containers start getting ip addresses. So my first DCHPed container will get 172.18.0.0

**PIhole static IP:**

`services:
        pihole:
                container_name: pihole
                image: pihole/pihole:latest
                networks:
                        webproxy:
                                ipv4_address: 172.18.0.2

                 environment:
                        - DNS1=1.1.1.1
                        - DNS2=1.0.0.1
                  dns:
                        - 127.0.0.1
                        - 1.1.1.1
`

Here under my network name (webproxy) I set a static IP for pihole container outside of the --ip-range=172.18.1.0/24 defined in network creation

Also  I have define in the host /etc/docker/daemon.json the pihole ip (172.18.0.2) as dns server for my containers:

`
{
        "ipv6": false,
        "dns": ["172.18.0.2", "8.8.8.8"],
        "dns-opts":["use-vc"]
}
`

Traefik has a standard config and all my containers attach only to "webproxy" network

**Comment by Ryonez** [comment]
Alright, this won't work for me. Pi-hole has an IP on the lan, not the docker network.

**Comment by erosenberg** [comment]
> We just updated the docs for Traefik v2 + Docker Pi-hole here https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose-traefik-proxy.md

This page seems to be missing now. Can you please re-upload this or update the link? I'm trying to get Pihole to work with Traefik and the two are fighting each other at the moment.

**Comment by Ryonez** [comment]
@dschaper This still isn't resolved, using a reverse proxy still leaves http traffic on the local network.

This need to be a setting for the docker container, even if it's just a self signed cert.
