### ISSUE TITLE
Upgrade to 5.0, lost whitelist

### ISSUE THREAD

**Issue by 1activegeek** [pi-hole/docker-pi-hole#622]
This is a: **Bug/Issue**  

## Details

My system is set to auto-update the docker container weekly on Sundays. I noticed today when checking something that I had the new 5.0 update. I also noticed that my whitelist was empty. Checking my files, I still see the whitelist.txt file with content (about 20 or so), but these have not made it into the current running PiHole. 

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

None found 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Docker - Official PiHole container** 
  * Hardware: unRAID 
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: Official PiHole
    - Supplimentary Software: 
  * Hardware architecture: x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
docker run -d --name='pihole' --net='br0' --ip='10.0.10.11' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'TCP_PORT_53'='53' -e 'UDP_PORT_53'='53' -e 'TCP_PORT_80'='80' -e 'PUID'='99' -e 'PGID'='100' -e 'ServerIP'='10.0.10.11' -e 'ServerIPv6'='' -e 'DNS1'='1.1.1.1' -e 'DNS2'='1.0.0.1' -e 'IPv6'='False' -e 'TZ'='America/New_York' -e 'WEBPASSWORD'='REDACTED' -e 'INTERFACE'='eth0' -e 'DNSMASQ_LISTENING'='all' -v '/mnt/user/appdata/pihole/pihole/':'/etc/pihole/':'rw' -v '/mnt/user/appdata/pihole/dnsmasq.d/':'/etc/dnsmasq.d/':'rw' --cap-add=NET_ADMIN --dns 127.0.0.1 --dns 1.1.1.1 --hostname=pihole --restart=unless-stopped 'pihole/pihole:latest'
```
3. any additional info to help reproduce

only relevant thing I found on forums: https://discourse.pi-hole.net/t/lack-of-whitelist-and-adlist/27987/5

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

None of the above fixed quite apply to helping the issue as this is a migration problem. Content from previous version/install did not get moved/migrated to new install.

**Comment by fermulator** [comment]
Is there a way to update to the latest `4.x` stable without accepting `5.x`? that would be my preference for now while v5 bugs are worked out

**Comment by 1activegeek** [comment]
@fermulator I would firstly suggest not posting information here not relevant to the issue listed, that's not helpful for the devs to fix issues. And for choosing a version, you can simply choose a docker image to use by specifying it which could be an older version.

**Comment by Kipjr** [comment]
Same issue with the 5.1.1 on Raspi 4. Beta 5.0 did not have this issue.
