### ISSUE TITLE
[PROPOSAL] Getting rid of 'Misconfigured DNS' messages

### ISSUE THREAD

**Issue by Haarolean** [pi-hole/docker-pi-hole#623]
This is a: Run Issue (running Pi-hole container failing)

## Details
I think such messages should not be displayed if pihole is being run in a docker container, since docker's forcing it's own internal DNS resolver as the only server.
```
pihole    | WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
pihole    | WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)
```

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 
https://github.com/pi-hole/docker-pi-hole/issues/497

**Comment by kanonengedonner** [comment]
same issue

**Comment by diginc** [comment]
https://github.com/pi-hole/docker-pi-hole/pull/618
