### ISSUE TITLE
Please update docker pihole:armel

### ISSUE THREAD

**Issue by agilob** [pi-hole/docker-pi-hole#624]
Docker on armel (rpi1 and rpi0) is out of date and using non-stable (`dev` tag) release.

https://hub.docker.com/r/pihole/pihole/tags?page=1&name=armel

**Comment by dschaper** [comment]
@diginc Are we building armel anymore?

**Comment by diginc** [comment]
nope, it wasn't working in a similar style to ARM64 last time I tried it.  Another recent issues corroborated it didn't work.

**Comment by dschaper** [comment]
Thanks, we can close this then.

**Comment by maroessler** [comment]
@diginc Can you explain what exactly does not work? I managed to build an armel Pihole v5 image by tinkering with the install script and it is currently running on my Pi 1. It seems to work as it should but maybe I’m overlooking something?
