### ISSUE TITLE
rasberrypi 4b docker pihole get some error

### ISSUE THREAD

**Issue by learnman1994** [pi-hole/docker-pi-hole#630]
Sorry my english is poor.
I run pihole in the docker,bu the logs shows me "couldn't get 'max filedescriptors' Operation not permitted Stopping lighttpd"

model:rasberrypi 4b
docker version: 19.03.11
system: ubuntu 20.04

Please help me.
It bothers me

**Comment by z3llin** [comment]
This error appears to be the same as this [post](https://github.com/pi-hole/docker-pi-hole/issues/593#issuecomment-612412791)
The issue lies within libseccomp and is an issue outside of PiHole and Docker.

**Comment by cattypapa** [comment]
> This error appears to be the same as the one in this [post.](https://github.com/pi-hole/docker-pi-hole/issues/593#issuecomment-612412791)
> The issue lies within libseccomp and is an issue outside of PiHole and Docker.

thank you
