### ISSUE TITLE
After reboot (non gracefully docker restart) i can't start the container anymore

### ISSUE THREAD

**Issue by erythana** [pi-hole/docker-pi-hole#636]
This is a:  Run Issue (running Pi-hole container failing)

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Raspberry Pi OS Lite 
  * Hardware: RasPi 3B+
  * Kernel Architecture: Arm32V7 (i think)
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software: 
  * Hardware architecture: ARMv7 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
Pretty much the github example file, with adjusted timezone
3. any additional info to help reproduce
Reboot the Host without first shutting down the container. After the system comes back up the pihole is in state "started" (not "healthy") and it doesnt start up at all - i can't connect to shell either because the system is not running. Log says 
"export: fatal: unable to exec /etc/s6/init/init-stage1: No such file or directory"
Rebuilding the container doesn't help either - i really have to delete everything and run the "docker-compose" again. After that everything works until i would restart/shutdown the pi again (when i forget to do it gracefully)...

Thanks!

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by erythana** [comment]
I think i found the problem. I was setting everything up, realized there is an error with the local ip (the 127.0.0.11 error) and changed that in the resolve config, also changed the network-mode to host. Only the latter one is required for my setup to run. If i change the resolve.conf to 127.0.0.1 the whole container seems to crash and don't come up again by itself or an rebuild.

**Comment by ndrwstn** [comment]
@erythana I think I'm suffering the same issue you had; is there any chance you can tell me what files you changed? I'm not familiar with the 127.0.0.11 error, I just can't get docker pinhole to come up on restart, but when I stop everything and restart it it works fine.

**Comment by erythana** [comment]
@ndrwstn Sorry, it's been quite a while so im not sure anymore. Its running without problems, had at least one power outtage in between and it worked.
What do you see in your docker logs? Pi-Hole should be printing all sort of debug information on startup.

As a resource regarding the 127.0.0.11 (see the 11, not a 1 for local host!) error, this might help: https://discourse.pi-hole.net/t/dns-resolution-unavailable-unless-local-list-is-deleted/14405/14 or https://www.reddit.com/r/pihole/comments/gnkee5/docker_container_init_complaining_about/
