### ISSUE TITLE
Pi-hole works if I set DNS in network preferences, but not if set on router with Bridge mode

### ISSUE THREAD

**Issue by vedranjaic** [pi-hole/docker-pi-hole#640]
Summary details:
```
ISP Router IP: 192.168.1.1
Linksys Router in Bridge mode: 192.168.1.2
Linux Pi-hole PC Static IP: 192.168.1.10
```

Hi,

I'm not a network expert so I could use a little help.
I have a small linux PC running docker with a pi-hole. This PC has static IP 192.168.1.10 and is connected via Wi-Fi on Linksys router (192.168.1.2) which is in Bridge mode with my ISP router (192.168.1.1).

All other computers are connected to the same Linksys router.

On any computer I can access pi-hole admin via 192.168.1.10/admin

Linksys router in Bridge mode has Connectivity settings:

```
IPv4: 192.168.1.2
Subnet mask: 255.255.255.0
Gateway: 192.168.1.1
DNS 1: 192.168.1.10
DNS 2: 1.1.1.1
```

On any computer, ads don't get blocked... If I set the pi-hole DNS in any of theirs network preferences, ads get blocked and it's working without problem.

So how come the ads don't get blocked if I set it on a router? I guess it's a small fix but feeling stuck in this after 2-3 days of fiddling around, and don't know what to do.

**Comment by dschaper** [comment]
The router will use both available DNS servers so 1.1.1.1 is being used.

**Comment by vedranjaic** [comment]
Doesn't matter, it doesn't work even if I enter only pihole IP

**Comment by dschaper** [comment]
Please us the topic you opened at https://discourse.pi-hole.net/t/pi-hole-works-if-i-set-dns-in-network-preferences-but-not-if-set-on-router-with-bridge-mode/34565
