### ISSUE TITLE
UDP port 67 missing from docker run script

### ISSUE THREAD

**Issue by nVertoletik** [pi-hole/docker-pi-hole#646]
Comparing the docker-compose configuration and the configuration used in [the docker run script](https://github.com/pi-hole/docker-pi-hole/blob/master/docker_run.sh) I found that in the later port 67/udp is missing.

This is a: **Feature Request**  

## Details

Besides the docker run script the [dockerfile](https://github.com/pi-hole/docker-pi-hole/blob/master/Dockerfile_arm64)s seem to indicate that the port is really used by the container. So more reason to change the script from the main page.

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for a section to ask about the project but wasn't able to find an official place/channel to ask about this type of issues.

## How to reproduce the issue 

1. Environment data
  * Operating System: **Ubuntu** 
  * Hardware: **RasPi 4B**
  * Kernel Architecture: **ArmV8 64bit**
  * Docker Install Info and version: 
    - Software source: **docker-ce**
    - Supplimentary Software: 
  * Hardware architecture: 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

docker run```

docker run -d \
    --name pihole \
    -p 53:53/tcp -p 53:53/udp \
    -p 80:80 \
    -p 443:443 \
    -e TZ="America/Chicago" \
    -v "$(pwd)/etc-pihole/:/etc/pihole/" \
    -v "$(pwd)/etc-dnsmasq.d/:/etc/dnsmasq.d/" \
    --dns=127.0.0.1 --dns=1.1.1.1 \
    --restart=unless-stopped \
    --hostname pi.hole \
    -e VIRTUAL_HOST="pi.hole" \
    -e PROXY_LOCATION="pi.hole" \
    -e ServerIP="127.0.0.1" \
    pihole/pihole:latest
```


dockerfile```


FROM multiarch/debian-debootstrap:arm64-stretch-slim

ENV ARCH arm64
ENV S6OVERLAY_RELEASE https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-aarch64.tar.gz

COPY install.sh /usr/local/bin/install.sh
COPY VERSION /etc/docker-pi-hole-version
ENV PIHOLE_INSTALL /root/ph_install.sh

RUN bash -ex install.sh 2>&1 && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

ENTRYPOINT [ "/s6-init" ]

ADD s6/debian-root /
COPY s6/service /usr/local/bin/service

# php config start passes special ENVs into
ENV PHP_ENV_CONFIG '/etc/lighttpd/conf-enabled/15-fastcgi-php.conf'
ENV PHP_ERROR_LOG '/var/log/lighttpd/error.log'
COPY ./start.sh /
COPY ./bash_functions.sh /

# IPv6 disable flag for networks/devices that do not support it
ENV IPv6 True

EXPOSE 53 53/udp
EXPOSE 67/udp
EXPOSE 80
EXPOSE 443

ENV S6_LOGGING 0
ENV S6_KEEP_ENV 1
ENV S6_BEHAVIOUR_IF_STAGE2_FAILS 2

ENV ServerIP 0.0.0.0
ENV FTL_CMD no-daemon
ENV DNSMASQ_USER root

ENV VERSION v5.0
ENV PATH /opt/pihole:${PATH}

LABEL image="pihole/pihole:v5.0_arm64"
LABEL maintainer="adam@diginc.us"
LABEL url="https://www.github.com/pi-hole/docker-pi-hole"

HEALTHCHECK CMD dig +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1

SHELL ["/bin/bash", "-c"]
```
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [ ] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by dschaper** [comment]
67/UDP is not required for Pi-hole unless you are using it as a DHCP server. If you are using Pi-hole as a DHCP server then you'd be following https://docs.pi-hole.net/docker/dhcp/#technical-details which details the need to add 67 as port.
