### ISSUE TITLE
Admin Panel is blocked through traefik reverseproxy

### ISSUE THREAD

**Issue by Motophan** [pi-hole/docker-pi-hole#647]
`    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole-rtr.entrypoints=https"
      - "traefik.http.routers.pihole-rtr.rule=Host(`pihole.nigg.er`)"
      - "traefik.http.routers.pihole-rtr.tls=true"
      - "traefik.http.routers.pihole-rtr.service=pihole-svc"
      - "traefik.http.services.pihole-svc.loadbalancer.server.port=80"
      - "traefik.http.middlewares.pihole.addPrefix.prefix=/admin"
`

This is a:  Run Issue

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **debian 10 x68_64 docker latest** 
  * Hardware: 
 x68_64 docker latest
  * Kernel Architecture: 
Linux webserver 5.4.0-0.bpo.4-amd64 #1 SMP Debian 5.4.19-1~bpo10+1 (2020-03-09) x86_64 GNU/Linux
  * Docker Install Info and version: 
`docker info
Client:
 Debug Mode: false

Server:
 Containers: 16
  Running: 16
  Paused: 0
  Stopped: 0
 Images: 131
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-0.bpo.4-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 13.6GiB
 Name: webserver
 ID: VJNI:VLID:VW52:PAHL:JH64:FZRY:GUZS:AELG:WOSE:LILM:DB2Y:SMMQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
`
    - Software source: 
    - Supplimentary Software: 
  * Hardware architecture: 
x68_64
2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
https://i.imgur.com/u8hr3R6.png
https://i.imgur.com/VMOsRft.png
3. any additional info to help reproduce
`  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
    networks:
      - t2_proxy
    environment:
      TZ: $TZ
      WEBPASSWORD: {$PASSWORD}
    volumes:
      - $USERDIR/docker/pihole/etc:/etc/pihole/
      - $USERDIR/docker/pihole/dnsmasq.d:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    privileged: True
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole-rtr.entrypoints=https"
      - "traefik.http.routers.pihole-rtr.rule=Host(`pihole.domain.tld`)"
      - "traefik.http.routers.pihole-rtr.tls=true"
      - "traefik.http.routers.pihole-rtr.service=pihole-svc"
      - "traefik.http.services.pihole-svc.loadbalancer.server.port=80"
      - "traefik.http.middlewares.pihole.addPrefix.prefix=/admin"
`

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by dschaper** [comment]
This doesn't seem to be a Pi-hole issue but a traefik issue. You'll need to ask them.

**Comment by Motophan** [comment]
I reposted this opened. My reverse proxy is operating correctly, there is either a documentation issue (needing a specific xrefer that is not mentioned, or similar thing like this) or a bug issue. All routing to other various containers are operating as designed.

**Comment by diginc** [comment]
Our documented examples don't have the `addPrefix.prefix=/admin` your setup shows - I'm think that'd force you to go to /admin/admin since traefik would be appending the admin prefix to that route.

https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose-traefik-proxy.md

Did you try exactly as was documented there?

**Comment by magnus919** [comment]
> Our documented examples don't have the `addPrefix.prefix=/admin` your setup shows - I'm think that'd force you to go to /admin/admin since traefik would be appending the admin prefix to that route.
> 
> https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose-traefik-proxy.md
> 
> Did you try exactly as was documented there?

Link is a 404.

**Comment by rdwebdesign** [comment]
This is an old comment. 
The file referenced in the link was removed over a year ago ([it was outdated](https://github.com/pi-hole/docker-pi-hole/pull/725)).

You can try at our Discourse Forum: https://discourse.pi-hole.net/
