### ISSUE TITLE
Please allow overriding cache-size

### ISSUE THREAD

**Issue by CodeSapiens** [pi-hole/docker-pi-hole#648]
This is a: **FILL ME IN**  
When setting up Pihole along with Unbound, it is best to disable DNSSEC and also set cache to 0, but restarting the Container sets the cache back to 10000.

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **ENTER HERE** 
  * Hardware: 
  * Kernel Architecture: 
  * Docker Install Info and version: 
    - Software source: 
    - Supplimentary Software: 
  * Hardware architecture: 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [ ] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by dschaper** [comment]
> When setting up Pihole along with Unbound, it is best to disable DNSSEC and also set cache to 0

Can you provide some documentation or evidence of this?

**Comment by CodeSapiens** [comment]
Sure. At least that is my understanding from reading these comments from the developers themselves:

https://github.com/anudeepND/pihole-unbound - See notes under "Important Steps"

https://github.com/pi-hole/docs/issues/207

https://www.reddit.com/r/pihole/comments/awbbyc/quick_question_on_dnssec_with_unbound/

Thanks for following up.
Jul 7, 2020, 2:09 AM by notifications@github.com:

**Comment by CodeSapiens** [comment]
I should add, that my own tests confirm that. Not so much with the cache, which apparently can never be entirely turned off (even when set to zero it still keeps showing hits in the logs). But DNSSEC for sure makes a noticeable difference.
When you think about it, it makes sense to turn off DNSSEC between Pihole and Unbound, as that is an internal hand-off of data with implicit trust. And there is no point in doubling down on something Unbound is going to do again when it forwards the request externally. Same rationale woud apply to cacheing. No sense in having two cache pools since Unbound also handles that very well, and it wouldn't make much sense disabling cache on Unbound.
Thoughts?

Jul 7, 2020, 2:09 AM by notifications@github.com:

**Comment by dschaper** [comment]
There's no need to disable DNSSEC on Pi-hole and as such no need to disable cache on Pi-hole.

**Comment by dschaper** [comment]
> from the developers themselves

None of those links have anything from the Pi-hole developers. DNSSEC used to be an issue but that information is outdated now that version 5 has been released.

**Comment by CodeSapiens** [comment]
So 10000 cache is the ultimate hard-set value that we can never override? What if someone needs to increase it?

I just don't think it would hurt to give control over that one setting to the user. I could be wrong.
Anyway, have a good night. Thanks for the reply.

Jul 7, 2020, 2:37 AM by notifications@github.com:

**Comment by x-Felix** [comment]
Then is it possible not reset `01-pihole.conf` file every time container restarts?

**Comment by vonorlow** [comment]
push

**Comment by PromoFaux** [comment]
No need to bump, this can be closed. It was implemented in: https://github.com/pi-hole/docker-pi-hole/pull/689

Docs here: https://github.com/pi-hole/docker-pi-hole#advanced-variables
