### ISSUE TITLE
5.1 Data Table Error on Local DNS record page - docker image

### ISSUE THREAD

**Issue by HarvsG** [pi-hole/docker-pi-hole#654]
*** This error is specific to the docker image, I have created an identical issue [on the pihole repo](https://github.com/pi-hole/pi-hole/issues/3553) please close one ***

**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](hattps://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behavior:**
Pi-hole v5.1.1 
Web Interface v5.1 
FTL v5.1
Docker: `pihole/pihole:latest`
Raspberry Pi 4 4GB

The Local DNS page would load and show me the configured Local DNS entries

**Actual behavior:**
I get the following error in a warning pop-up box:
`DataTables warning: table id=customDNSTable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1`
![image](https://user-images.githubusercontent.com/11440490/87645834-f678bc80-c745-11ea-8899-16937074aa46.png)

**Steps to reproduce:**
1. Spin up a `pihole/pihole` docker image
    - (I had the same volume bindings as my old 5.0 image, so all my settings would be retained)
2. Navigate to `Local DNS records`
3. See error

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/l14gt98rtb

**Troubleshooting undertaken, and/or other relevant information:**

I tried the same on an identical install (copied config files across) on bare metal on a raspi zero with no problems

![image](https://user-images.githubusercontent.com/11440490/87645694-c0d3d380-c745-11ea-9629-60b83b13b34d.png)

**Comment by MrHappy** [comment]
is it resolved if you change the owner of /etc/pihole/custom.list to pihole:pihole?
Or whatever the user is it runs pihole-FTL under... ;)
