### ISSUE TITLE
Pulling v5.1.1_armhf image tag fails on RasPi

### ISSUE THREAD

**Issue by shaderecker** [pi-hole/docker-pi-hole#656]
This is a: **Bug**  

## Details

When I want to explicitly pull the v5.1.1_armhf image tag, I get the following error message:

```
pi@raspberrypi-bkp:~ $ docker pull pihole/pihole:v5.1.1_armhf
Error response from daemon: manifest for pihole/pihole:v5.1.1_armhf not found: manifest unknown: manifest unknown
```

Pulling the generic (multiarch) v5.1.1 image tag works as expected.

Note:
I noticed that on Docker Hub the v5.1.1_armhf (or basically all armhf) is detected as linux/amd64 (shouldn't that be linux/arm/v7 ?).
Maybe this relates to the issue?
![image](https://user-images.githubusercontent.com/16366556/87700131-251e8380-c796-11ea-94a0-1fc906c09963.png)

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Rasbian** 
  * Hardware: RasPi 3B
  * Kernel Architecture: armv7l
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: none 
  * Hardware architecture: ARMv7 Processor rev 4 (v7l)

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
`docker pull pihole/pihole:v5.1.1-armhf`
3. any additional info to help reproduce
I tried it on two RasPis and got the same result.
However I was able to download the image on an Ubuntu Server 20.04 (amd64).

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
I am able to pull previous armhf tag versions.
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

**Comment by elreydetoda** [comment]
your command you used is: `docker pull pihole/pihole:v5.1.1_armhf`
but the image name is: `v5.1.1-armhf`
so you need to run: `docker pull pihole/pihole:v5.1.1-armhf`

the difference is you used a `_` compared to a `-`

**Comment by shaderecker** [comment]
:man_facepalming: omg, wow :grimacing: I have no words.
Thanks for pointing it out.
