### ISSUE TITLE
Reducing SD card wear

### ISSUE THREAD

**Issue by eggbean** [pi-hole/docker-pi-hole#659]
Which files are constantly written to disk while running this container and what can be done to reduce SD card wear?

I use [log2ram](https://github.com/azlux/log2ram) to put /var/log on a RAM disk which gets written to the SD card once a day. Is there anything similar I could do to reduce SD card wear when running this docker container (or docker containers in general)?

**Comment by Kipjr** [comment]
Install log2ram on host and add this to volume?
```
    volumes:
       - '/var/log/pihole:/var/log/'
```

**Comment by eggbean** [comment]
@Kipjr Thanks for answering. I found out that there are two settings which you can alter/add in ` /etc/pihole/pihole-FTL.conf`

```
DBINTERVAL=60
MAXDBDAYS=30
```
It's explained here: https://www.reddit.com/r/pihole/comments/a47qc5/if_youre_worried_about_logging_burning_out_your/

**Comment by eggbean** [comment]
> Install log2ram on host and add this to volume?
> 
> ```
>     volumes:
>        - '/var/log/pihole:/var/log/'
> ```

I tried what you suggested as well, to further reduce wear, but the log files aren't even in there.

https://github.com/pi-hole/pi-hole/issues/3041

**Comment by dschaper** [comment]
That volume mount will take the directory `/var/log/pihole` on the host and map that in to `/var/log` in the container. Every log Pi-hole writes to will be in `/var/log/` in the container. Check `/var/log/pihole` on the host and you'll find everything you need.

https://docs.docker.com/compose/compose-file/#short-syntax-3

**Comment by eggbean** [comment]
Yeah, that was the wrong way around, but I don't know what you meant by this?

> Check `/var/log/pihole` on the host and you'll find everything you need.

If the log files were in `/var/log/pihole/` in the container, the it would be able to be mounted on the host, but currently it cannot be done like that, so I'm not sure what you mean.

I wouldn't have thought that changing the location of the log files would be a difficult thing to change for you?

**Comment by dschaper** [comment]
If you mapped `/var/log/pihole/` on the host to `/var/log` in the container then `/var/log/pihole` should contain everything that is written to `/var/log` in the container. You should have `/var/log/pihole/pihole.log` `/var/log/pihole/pihole-FTL.log` and `/var/log/pihole/pihole/`. 

> I wouldn't have thought that changing the location of the log files would be a difficult thing to change for you?

We'd just have to change all the documentation, scripts that reference that location, support instructions...

**Comment by eggbean** [comment]
Oh, I see what you mean. Yeah, I'll try that then. Cheers.

**Comment by eggbean** [comment]
Hmmn, it doesn't seem to work unfortunately. When doing this, only `pihole.log`, `pihole-FTL.log`  and the empty `pihole` directory appear in `/var/log/pihole/` on the host and the web interface doesn't work, although the pihole appears to accept DNS queries. Errors appear in the FTL log. 
http://sprunge.us/dBRo7P

**Comment by dschaper** [comment]
Do the log files contain any content? Are the user ownership and permissions the same as the user running inside the container?

What does "web interface doesn't work" mean, screenshots or more detail that we can use to try and troubleshoot will be helpful.

Does a `dig pi.hole` against the IP address of the Pi-hole container return the right IP address? And a `dig` for doubleclick.net return the proper blocking address?

Honestly, you're probably causing yourself way more trouble than it's worth. SD cards don't die like they used to, and you're writing a lot more just by using Docker on the Raspberry Pi device than just installing Pi-hole direct.

**Comment by dschaper** [comment]
Pi-hole is working, it's blocking and forwarding for 4 clients.

```plain
[2020-07-27 05:24:34.021 1406M]  -> Total DNS queries: 20013
[2020-07-27 05:24:34.021 1406M]  -> Cached DNS queries: 1797
[2020-07-27 05:24:34.021 1406M]  -> Forwarded DNS queries: 12145
[2020-07-27 05:24:34.021 1406M]  -> Blocked DNS queries: 6071
[2020-07-27 05:24:34.021 1406M]  -> Unknown DNS queries: 0
[2020-07-27 05:24:34.021 1406M]  -> Unique domains: 1467
[2020-07-27 05:24:34.021 1406M]  -> Unique clients: 4
[2020-07-27 05:24:34.022 1406M]  -> Known forward destinations: 3
```

**Comment by eggbean** [comment]
The web interface is completely inaccessible. As in the Pi-Hole webpage. But the client machines using the Pi-Hole for DNS can access the internet with no problems. But obviously I need to access the web interface sometimes.

What I'll do is just continue to use the docker version on my secondary Pi-Hole on AWS, and put the normal version on the RasPi and have log2ram on the log directory. Thanks for your help.

**Comment by dschaper** [comment]
Okay, if you do want to continue troubleshooting then we'll need information like:

What URL are you entering. What is the browser displaying as a result. Are there any errors displayed. Is `lighttpd` logging any errors. Does `pihole -d` in the container process and display a debug log token.

**Comment by casperklein** [comment]
Maybe related: I also map the whole `/var/log` directory in the container to my host (same as you in https://github.com/pi-hole/docker-pi-hole/issues/659#issuecomment-664083239).

But to get this working, I had to fix the permissions afterwards `chown -R www-data: /var/log/lighttpd` in the container.

**Comment by eggbean** [comment]
@casperklein Thanks. I tried doing that, but when I execed into the container only the previously mentioned files were in `/var/log/`, so there wasn't any way to do that.

@dschaper There are no logs to look at apart from the one I linked to and the other one looked normal to me. The URLs I tried were the usual `fqdn.hostname/admin` and `IP/admin` which normally work.

Because I cannot run my DDNS firewall update script for gcloud in docker on ARM anyway (AWS is fine), it would make sense for me to just run vanilla Pi-Hole on the RasPi anyway. Cheers.

**Comment by casperklein** [comment]
Sorry, I was a bit unclear, what I did:

Mapping a host directory to container: `./data:/data` (both directorys are empty at this point)

Inside the container, move the existing data to `/data`, symlink it and fix permissions for lighttpd:

    mv /var/log /data/log
    ln -s /data/log /var/log
    chown -R www-data: /var/log/lighttpd

>I tried doing that, but when I execed into the container only the previously mentioned files were in `/var/log/`

I think, that could be the problem. When you just map a host directory to `/var/log`, then this directory will be empty. But afaik `/var/log/lighttpd` must exist (with correct permissions) for the Web UI to start properly.

**Comment by dschaper** [comment]
I agree that a non-docker installation would be the best option for this case.
