### ISSUE TITLE
chown & chmod error cannot access no such file or directory

### ISSUE THREAD

**Issue by sherrygopal** [pi-hole/docker-pi-hole#660]
This is a: Bug  

## Details

Starting pihole container shows the following message 
highlighted below by making lines bold.

>   [i] Installing configs from /etc/.pihole...
>   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
>   [i] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf...
>   [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
> **chown: cannot access '': No such file or directory
> chmod: cannot access '': No such file or directory**
> ::: Pre existing WEBPASSWORD found
> Docker DNS variables not used
> 

Looking into file `bash_functions.sh` I do see function `prepare_configs()` which makes the above call and hence throws the error that the file or directory not found. 

bash_functions.sh output:
```
50 chown pihole:pihole "${PI_HOLE_CONFIG_DIR}/pihole-FTL.conf" "/var/log/pihole" "${regexFile}"
....
53 chmod 777 "${regexFile}"
```
further reading into gravity.sh it seems that the possible file name could be `regex.list`. Therefore I created `regex.list` file by using following command `touch /etc/pihole/regex.list`

but this does not resolve it. However if i put path /etc/pihole/regex.list instead of ${regexFile} (variable) and have that touch file mentioned above the error goes away.
I realize this must be expecting some kind of file. I tired creating whitelist, blocklist, adlist & gravity update. But error still stays there.

It seems the return value of variable ${regexFile} is empty.

Workaround:
I have commented out ${regexFile} and the whole line number 53. Indeed error message has gone away.

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Raspbian 
  * Hardware: 3B
  * Kernel Architecture: Armv7
  * Docker Install Info and version: 
    - Software source: docker-ce
    - Supplementary Software: portainer
  * Hardware architecture: ARMv7

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

**Comment by harmvanderhaas** [comment]
Did all the same... after a day i see that it is an issue :D time well spent 👯‍♂️

**Comment by Noiden** [comment]
I also have this errors.

Running docker on an Ubuntu 20.04 server.

```
[i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
[✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chown: cannot access '': No such file or directory
chmod: cannot access '': No such file or directory
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory

```

Is this something I need to do something with? I'm running latest from the dockerhub.

Also, why does it says "it is not a Pi-hole file, leaving alone!"? I don't think I have manually added something there.

**Comment by AthrogatePEQ** [comment]
I don't see where the regexFile variable is set in any of the configuration or scripts.

Perhaps we could conditionally do the changes to ${regexfile}

if [[ -z ${regexfile} && -e ${regexfile} ]]; then
  chown pihole:pihole ${regexFile}
  chmod 777 ${regexfile}
fi

**Comment by gklanderman** [comment]
I noticed this as well.

AFAICT regexFile is never set, so those stray references should just be removed?

@diginc seems to have added these in two commits on Aug 22, 2018.. maybe they were relevant then?

**Comment by JimmyPesto** [comment]
I am facing the exact same issue starting the current master.

**Comment by hardwareadictos** [comment]
Having this exact same issue again :(
