### ISSUE TITLE
[5.1.1] pi-hole breaks DNSSEC

### ISSUE THREAD

**Issue by ihatemicrosoft-was-already-taken** [pi-hole/docker-pi-hole#662]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behavior:**

pi-hole should not break DNSSEC

**Actual behavior:**

pi-hole blocks DNSKEY lookups to domain '.', effectively breaking DNSSEC

**Steps to reproduce:**

1. Run pi-hole 5.0 in docker
2. Update docker container from 5.0 to 5.1.1
3. Wait a few minutes
4. pi-hole will block DNSKEY lookups to '.', as this domain is blocked by gravity

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Log not uploaded, don't know how to achieve this in a docker setup.

**Troubleshooting undertaken, and/or other relevant information:**

Mitigation:
- downgrade to 5.0
- disable filtering

I'm not sure blocking DNSKEY records is a good idea in any case, so maybe DNSKEY lookups shouldn't be blocked (or at least not to the '.' domain)?

**Comment by ihatemicrosoft-was-already-taken** [comment]
Well, I assume you've found the lookups that still work immediately after starting. That's why I've documented "Wait a few minutes" in the initial report.

**Comment by dschaper** [comment]
There's nothing that will magically stop DNSSEC from working after some indeterminate amount of time. If you want to show that DNSSEC is not working then provide logs that show DNSSEC is not working.

**Comment by ihatemicrosoft-was-already-taken** [comment]
> There's nothing that will magically stop DNSSEC from working after some indeterminate amount of time.

So you're saying I'm making stuff up?



> If you want to show that DNSSEC is not working then provide logs that show DNSSEC is not working.

I did, at least in a way that I replicated the conditions and then created the support logs. What else am I supposed to do?

**Comment by dschaper** [comment]
> So you're saying I'm making stuff up?

No, I'm saying what you have provided me shows that Pi-hole is working and DNSSEC is functioning correctly. 


> What else am I supposed to do?

Show me some kind of evidence that DNSSEC is broken or that the root is being blocked.

**Comment by ihatemicrosoft-was-already-taken** [comment]
Okay, so instead of trying to re-create the issue, I instead discarded _everything_ (because I didn't have that big of a whitelist and the rest of the configuration is in docker-compose anyway) and re-started the containers with a "clean slate". This way I am unable to replicate the issue with DNSKEY on '.' being blocked by gravity.

Closing
