### ISSUE TITLE
Setting hostname slows pi-hole GUI down

### ISSUE THREAD

**Issue by JuniperMS** [pi-hole/docker-pi-hole#669]
### Versions

- Pi-hole version is v5.1.1 (Latest: v5.1.1)
- AdminLTE version is v5.1 (Latest: v5.1)
- FTL version is v5.1 (Latest: v5.1)

### Platform

- OS and version: Raspbian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi 4

### Expected behavior

I expected to set the host name "pi-hole primary" without it slowing down the GUI.

### Actual behavior / bug

When you set the host name the GUI becomes extremely slow.

### Steps to reproduce

Set the host name.

## Debug Token

- URL:  https://tricorder.pi-hole.net/q9caxwo8mj -> This is **without** the hostname set
- URL:  ttps://tricorder.pi-hole.net/b4wlqrzyaa -> This is **with** the hostname set.

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
A couple of things to fix:

1. `/etc/pihole/setupVars.conf` has the IPv4 address for the Pi-hole set to 0.0.0.0, which isn't correct. That needs to be the actual IP address that you access the Pi-hole at.

2. You can't have spaces in host names.
>Valid characters for hostnames are ASCII(7) letters
       from a to z, the digits from 0 to 9, and the hyphen (-).  A hostname
       may not start with a hyphen.

**Comment by JuniperMS** [comment]
@dschaper - thank you for the swift reply.  I changed the host name to "pi-hole-primary" and that resolved it.  I also added the correct IP address as you suggested.  Thanks again!
