### ISSUE TITLE
How to set conditional forwarding local network?

### ISSUE THREAD

**Issue by sirpeanut** [pi-hole/docker-pi-hole#680]
This is a: Run Issue

## Details

I'm using the CONDITIONAL_FORWARDING_* environment variables to configure conditional forwarding. But I can't see how to configure the field "Local network in CIDR notation". Pi-Hole is defaulting to 10.0.0.0/24 (guessing it infers this from its own IP somehow?), but I actually need 10.0.0.0/8. Is there an environment variable that can set this?

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 
  * Hardware: Intel NUC 
  * Kernel Architecture: x86 
  * Docker Install Info and version: 
    - Software source: microk8s 1.18 
    - Supplimentary Software: 
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

Relevant environment variable config:

      - env:
        - name: CONDITIONAL_FORWARDING
          value: "true"
        - name: CONDITIONAL_FORWARDING_DOMAIN
          value: local
        - name: CONDITIONAL_FORWARDING_IP
          value: 10.0.0.1
        - name: ServerIP
          value: 10.0.2.2
        - name: VIRTUAL_HOST
          value: pi.hole

3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by sirpeanut** [comment]
I think I may have found a workaround, which is to add a rule to dnsmasq:

$ cat /etc/dnsmasq.d/02-custom.conf
rev-server=10.0.0.0/8,10.0.0.1

Not sure if this was the right thing to do, and it doesn't actually show up in the web UI anywhere, but it seems to be working?

**Comment by BastiG** [comment]
Digging through pi-hole sources it seems that upstream doesn't support this behaviour (see commit https://github.com/pi-hole/pi-hole/commit/3aaf9d89b3200d972d06dbb4722953853b0d5617#diff-07fdb76a08c83afbb2044a72ebb35896).

As long as your compose env contains CONDITIONAL_FORWARDING: true, container deployment will overwrite pi-hole config and replace the Local Network CIDR with the class-C network of CONDITIONAL_FORWARDING_IP.
Imho another environment variable like CONDITIONAL_FORWARDING_CIDR should fix that issue, the class-C network conversion would still be available as a fallback.

At the same time CONDITIONAL_FORWARDING_REVERSE was forgotten. As the commit dates back to July chances are that the implementation might still see a rework.

I'll create an issue on pi-hole upstream (also removing the limitation to fixed /8, /16 and /24 prefixes), it's not an issue of the docker-pi-hole project.

Until then I'll follow your approach using a custom config file.

**Comment by PromoFaux** [comment]
> (also removing the limitation to fixed /8, /16 and /24 prefixes)

The limitation on the prefixes is down to the underlying `dnsmasq` code. See here:

https://discourse.pi-hole.net/t/support-prefix-12-for-conditonal-forwarding/33975/7?u=promofaux

**Comment by BastiG** [comment]
Thanks, good point ... the free-form config file got me tempted. Looks like that also happened before.

**Comment by IngmarStein** [comment]
Does #707 close out this issue?
