### ISSUE TITLE
Many raw.githubusercontent.com requests in my docker PiHole

### ISSUE THREAD

**Issue by IrocStan** [pi-hole/docker-pi-hole#682]
### Versions

Pi-hole version is v5.1.2 (Latest: v5.1.2)
AdminLTE version is v5.1.1 (Latest: v5.1.1)
FTL version is v5.2 (Latest: v5.2)

### Platform
- OS and version: Raspian Buster
- Platform:  Raspberry Pi 3B+

### Expected behavior

I installed the Pihole for docker on my Raspberry 3B + (Raspian Buster) [https://www.github.com/pi-hole/docker-pi-hole] and everything works fine, except for one little thing:
4k DNS requests every day from the docker-Pihole-IP / Gateway (172.21.0.1).

Attached is a screenshot of the requests, every 30 seconds "**raw.githubusercontent.com**" is requested. Could you explain why this is the case and how I can possibly turn off these requests?

Here's my docker-compose.yml:

version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      ServerIP: 192.168.1.4'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
![pihole](https://user-images.githubusercontent.com/71307833/93173970-9b574c00-f72d-11ea-9cb9-dbafd02030dc.PNG)
![pihole_2](https://user-images.githubusercontent.com/71307833/93173972-9befe280-f72d-11ea-8cba-3b179bb66a10.jpg)

**Comment by TheHades** [comment]
Is this really from the PiHole itself or is it maybe from a client which uses PiHole as DNS?

**Comment by IrocStan** [comment]
Thanks for your answer, the local network is in the 192.168.1.xxx area and the requesting IP is here: 172.21.0.1 (see screenshots). So according to Portainer that is the docker / Pihole network or gateway.

![1](https://user-images.githubusercontent.com/71307833/95014679-bd672e80-0648-11eb-873f-407ea9f15d5b.PNG)
![2](https://user-images.githubusercontent.com/71307833/95014681-bdffc500-0648-11eb-944a-ebe31336b51c.PNG)

**Comment by DerRockWolf** [comment]
I also observe this behaviour.
The pihole container is the only resource located within the pihole_default network, whose gateway IP is 172.22.0.1.
I can also observe this behaviour on a newly created pi-hole running a newly installed Ubuntu 20.04 with no clients set up to use pihole.

These requests are likely to be primarily requests to retrieve the configured AdLists.
These are retrieved at every boot if the environment variable SKIPGRAVITYONBOOT is not set and at midnight (Automatic Ad List Updates).

But it still seems a bit much? 163 out of 500 requests are to raw.githubusercontent.com.

I will continue to monitor this.
