### ISSUE TITLE
Pihole non accessible after reboot on synology , loop in rebooting

### ISSUE THREAD

**Issue by UmbeMont** [pi-hole/docker-pi-hole#698]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  Docker 18.09.0-0513

- Platform:  Synology 

### Expected behavior

Fresh installation on docker.
Configured dhcp , dns , console reachable at IP:8080 

### Actual behavior / bug
After a restart of the synology , console is not reachable anymore, the docker is in loop of reeboting

### Steps to reproduce

1install pihole:latest
2set as dhcp
3choose dns
4reboot synology

## Debug Token

Not available , all network down

- URL:  

### Screenshots

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/60969724/98338060-78486a80-2001-11eb-9f43-23a1ece250fd.png">

### Additional context

WEBPASSWORD=
BLOCKING_ENABLED=true
ADMIN_EMAIL=
WEBUIBOXEDLAYOUT=boxed
WEBTHEME=default-dark
DHCP_ACTIVE=true
DHCP_START=192.168.0.10
DHCP_END=192.168.0.150
DHCP_ROUTER=192.168.0.1
DHCP_LEASETIME=24
PIHOLE_DOMAIN=lan
DHCP_IPv6=false
DHCP_rapid_commit=false
PIHOLE_DNS_1=127.0.0.1
PIHOLE_DNS_2=8.8.8.8
REV_SERVER=false
QUERY_LOGGING=true
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=
IPV4_ADDRESS=192.168.0.10
IPV6_ADDRESS=
DNS_BOGUS_PRIV=
DNS_FQDN_REQUIRED=
DNSSEC=
CONDITIONAL_FORWARDING=
CONDITIONAL_FORWARDING_IP=
CONDITIONAL_FORWARDING_DOMAIN=
CONDITIONAL_FORWARDING_REVERSE=
PIHOLE_INTERFACE=eth0
DNSMASQ_LISTENING=local

**Comment by dschaper** [comment]
We don't support Synology as a platform, you will get a better response with asking at https://discourse.pi-hole.net/ in the Synology section. The community may be able to give you advice and guidance.

**Comment by dschaper** [comment]
You should note the linke that says `unable to resolve host pihole-pihole1: Connection timed out`, that looks like it is the issue.

**Comment by UmbeMont** [comment]
Thanks , but no luck
