### ISSUE TITLE
Web interface not working (lighttpd error)

### ISSUE THREAD

**Issue by MGMehdi** [pi-hole/docker-pi-hole#699]
### Versions

- Pi-hole version is v5.1.2 (Latest: v5.1.2)
- AdminLTE version is v5.1.1 (Latest: v5.1.1)
- FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version: Alpine Linux v3.12 aarch64

- Platform: Raspberry Pi 3 Model B Plus Rev 1.3

### Expected behavior

Web interface working

### Actual behavior / bug

Web insterface not working. Get this message in logs in loop

```
Starting lighttpd
2020-11-09 15:15:28: (server.c.970) couldn't get 'max filedescriptors' Operation not permitted 
Stopping lighttpd
ghttpd: no process found
```

### Steps to reproduce

1. Copy docker-compose.yml exemple
2. Run it
3. Check logs 

## Debug Token

- URL:  https://tricorder.pi-hole.net/v2vrg176a7

**Comment by dschaper** [comment]
https://www.reddit.com/r/pihole/comments/gsm5yn/trouble_installing_pihole_latest_on_ubuntu_2004/

**Comment by MGMehdi** [comment]
Thanks it works but I must disable my access point (stop dnsmasq and hostapd services)

**Comment by dschaper** [comment]
Glad it works.
