### ISSUE TITLE
Missing dashboard info on v5.1.2

### ISSUE THREAD

**Issue by ayasystems** [pi-hole/docker-pi-hole#700]
### Versions
- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform

- OS and version:  DSM 6.2.3-25426 Update 2

- Platform:  Synology

### Expected behavior

Dashboard web is not showing info about total-queries, queries blocked and percent blocked

### Steps to reproduce

1. Go to /admin/index.php
2. See error

## Debug Token

- URL:  https://tricorder.pi-hole.net/uruahtjspe

### Screenshots

![pihole1](https://user-images.githubusercontent.com/7864168/98576981-96d98a80-22bb-11eb-85ba-a832f808655c.jpg)
![pihole2](https://user-images.githubusercontent.com/7864168/98576997-9a6d1180-22bb-11eb-8b83-e58f572156f7.jpg)

**Comment by dschaper** [comment]
Have you cleared your browser cache? That font URL has changed.

**Comment by ayasystems** [comment]
No, but i fixed it... wrong time zone settings on docker creation

 --volume /volume1/docker/pihole/etc/localtime:/etc/localtime:ro   \

Regards!!!

**Comment by dschaper** [comment]
Great! Though that's probably a coincidence and creating the new container is what solved it. That URL for the font doesn't exist anymore.
