### ISSUE TITLE
Network Tab in Docker only displays N/A

### ISSUE THREAD

**Issue by HerrHofrat** [pi-hole/docker-pi-hole#702]
I think I found an issue with FTL in the official docker image. The network table seems to be populated with [ip neigh show](https://github.com/pi-hole/FTL/blob/b522646b8812b3f43f0935369f6a037189209c6c/src/database/network-table.c#L299) - however, in case the docker container is not started with the --net=host option, the `ip neigh show` command only sees the docker gateway

```
root@pihole2:/# ip neigh show
172.21.0.1 dev eth0 lladdr 02:42:db:65:eb:0e REACHABLE
```

This results in a list that only displays N/A for hardware address and interface
![Bildschirmfoto vom 2020-11-11 13-05-36](https://user-images.githubusercontent.com/1681077/98809898-9d344780-241e-11eb-8d01-7912159bfe81.png)

Is there maybe a workaround to still display the values?

Test environment:
Raspberry PI 4/8GB with the latest Raspbian 64 
Latest Pihole docker image with Pihole 5.1.2 and FTL 5.2

**Comment by nathang21** [comment]
This section used to be populated for me, but as some of recent updates
it’s totally blank.

Happy to provide debug logs if that is helpful.

**Comment by DL6ER** [comment]
Does `arp` return any different than `ip neigh show` for you?

**Comment by HerrHofrat** [comment]
the `arp` binary is not part of the docker image - setting it as a volume from the host also returns just the docker gateway, so the same as `ip neigh show`

**Comment by DL6ER** [comment]
I shall not hide the reason for my question, I was on my phone previously, hence the brevity of my question.

Now to the details: Pi-hole initially used the `arp` command to gather this details shown in the network table page. We changed that at some point in favor of `ip neigh` as the latter includes the knowledge of the ARP (IPv4-only) but also the NEIGH (IPv6-only) cache. There was no other change at all so if it worked before (as you said), then you've either had a different `docker` configuration in some way *or* `docker` changed some default configuration *or* `docker` fixed a bug leaking information it sholdn't.

I honestly cannot see any other way the tab used to be populated before as FTL never used anything besides `arp` and `ip neigh`.

**Comment by dschaper** [comment]
If the Pi-hole container is working on a bridge interface then there really isn't a way for it to gain the knowledge of the foreign collision domain. That's why running without host mode networking requires a dhcp relay for Pi-hole to be a DHCP server in a bridge interface. `macvlan` should work as well, with the workaround of docker being needed for the docker host to be able to talk to the container.

**Comment by HerrHofrat** [comment]
Okay, I thought I've a wrong configuration or there might be an easy workaround.. Maybe I write a little companion service that gathers the infos on the host directly and then updates the database directly :thinking: otherwise I have to live without them :joy:  thanks guys!

**Comment by vdbrink** [comment]
Hi @HerrHofrat,
You can get the data in the pi-hole docker by ssh to the docker host and run there the command.
You can do this with: `ssh -i <path to private key> <username>@<docker host IP> ip neigh show`

Is there a way to inject this result into the pi-hole database?

**Comment by HerrHofrat** [comment]
This only works if you use --net=host for your container, otherwise it only sees the docker gateway
