### ISSUE TITLE
CONDITIONAL_FORWARDING_REVERSE in README.md

### ISSUE THREAD

**Issue by realizelol** [pi-hole/docker-pi-hole#713]
No need of template...

Please note that CONDITIONAL_FORWARDING_REVERSE has to be in CIDR notation:
| Docker Environment Var. | Description |
| ----------------------- | ----------- |
| `CONDITIONAL_FORWARDING_REVERSE: <Reverse DNS>`<br/> *Optional* | If conditional forwarding is enabled, set the reverse DNS of the local network router (e.g. `0.168.192.in-addr.arpa`)

should  be:
| Docker Environment Var. | Description |
| ----------------------- | ----------- |
| `CONDITIONAL_FORWARDING_REVERSE:`<br/>`<Network in CIDR>`<br/> *Optional* | If conditional forwarding is enabled, set the network of your local network router in CIDR notation (e.g. `192.168.0.0/24`)

Otherwise you'll have an boot loop or an error `pihole    | dnsmasq: error at line 45 of /etc/dnsmasq.d/01-pihole.conf`

This would have saved me hours.

best regards
realizelol

**Comment by PromoFaux** [comment]
There is a pull to fix the documentation here:
https://github.com/pi-hole/docker-pi-hole/pull/707

However also a pull to auto fix it here for backward compatibility:
https://github.com/pi-hole/docker-pi-hole/pull/712

**Comment by realizelol** [comment]
oh damn, exactly when I decided to change from docker run to docker-composed 🤙🏻 

So I didn't know that's an actual issue.

#CLOSED
