### ISSUE TITLE
No Hostnames

### ISSUE THREAD

**Issue by AlphaOmega2020** [pi-hole/docker-pi-hole#723]
### Versions
  Pi-hole version is v5.2.1 (Latest: v5.2.1)
  AdminLTE version is v5.2.1 (Latest: v5.2.1)
  FTL version is v5.3.2 (Latest: v5.3.2)

### Platform
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:18:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

### Expected behavior

Reverse lookup to router for registered hostnames against IP's

### Actual behavior / bug

No hostnames are shown, only IP's. When it "tools > Network Overview" i do not see any MAC addresses 

## Debug Token

- URL:  https://tricorder.pi-hole.net/rqzclxk35p

### Additional context

docker-compose
    pihole:
        container_name: pihole
        network_mode: bridge
        environment:
            - 'PUID=1000'
            - 'PGID=100'
            - 'TZ=Europe/London'
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "80:80/tcp"
            - "443:443/tcp"
        volumes:
            - '/root/docker/appdata/pihole/config/etc-pihole/:/etc/pihole/'
            - '/root/docker/appdata/pihole/config/etc-dnsmasq.d/:/etc/dnsmasq.d/'
           cap_add:
          - NET_ADMIN
        restart: unless-stopped
        image: pihole/pihole:latest

**Comment by dschaper** [comment]
First, in bridge mode there is no way for MAC addressing to be seen inside the container. They are on different broadcast domains.

Secondly, unless Pi-hole is the DHCP server, you'll need to use Conditional Forwarding to point Pi-hole to an authoritative DNS server that knows the IP to hostname mapping. (Or add that mapping to the `/etc/hosts` or custom DNS host records.)

**Comment by AlphaOmega2020** [comment]
Interesting as it worked when i had it hosted on a qnap system with Docker, i simply pointed it to my router and it resolved corrected.

**Comment by AlphaOmega2020** [comment]
putting network into host mode doesnt work either.

**Comment by dschaper** [comment]
What IP do you have set for the conditional forwarding, and what device is answering the PTR record queries?

**Comment by AlphaOmega2020** [comment]
192.168.0.1 - pfSense Firewall that is running DHCP. 

Im running exactly the same config as when i was hosting piHole on a QNAP with docker, instead now its running on ProxMox.

**Comment by dschaper** [comment]
Do `dig` queries to 192.168.0.1 return a valid hostname when you try to ask it directly?

And ProxMox uses bridge interfaces so I don't expect running Docker on Proxmox (even in host mode) to be on the same broadcast domain as your clients. Does the Pi-hole container have an IP address in the 192.168.0.0/24 range?

**Comment by AlphaOmega2020** [comment]
```
; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57954
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;.                              IN      NS

;; ANSWER SECTION:
.                       85071   IN      NS      a.root-servers.net.
.                       85071   IN      NS      b.root-servers.net.
.                       85071   IN      NS      c.root-servers.net.
.                       85071   IN      NS      d.root-servers.net.
.                       85071   IN      NS      e.root-servers.net.
.                       85071   IN      NS      f.root-servers.net.
.                       85071   IN      NS      g.root-servers.net.
.                       85071   IN      NS      h.root-servers.net.
.                       85071   IN      NS      i.root-servers.net.
.                       85071   IN      NS      j.root-servers.net.
.                       85071   IN      NS      k.root-servers.net.
.                       85071   IN      NS      l.root-servers.net.
.                       85071   IN      NS      m.root-servers.net.

;; Query time: 1 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Fri Dec 11 23:23:37 GMT 2020
;; MSG SIZE  rcvd: 239
```

its using the same IP as the proxmox host 192.168.0.2

**Comment by AlphaOmega2020** [comment]
tbh its running outside of proxmox so not sure if its relevant. Docker is installed directly onto Debian.

**Comment by dschaper** [comment]
That `dig` doesn't say anything.

**Comment by AlphaOmega2020** [comment]
yeah just realised to didnt and cannot get into the container, normally i use one of the following:

docker exec -it pihole /bin/bash
or
docker exec -it pihole /bin/sh

neither work...

**Comment by dschaper** [comment]
You don't need to be in the container to check with a dig. Pick the IP address of a host you'd like to see and then run

```
dig -x <IP> @192.168.0.1
```

That should return the hostname, if it doesn't then conditional forwarding is not going to work.

**Comment by AlphaOmega2020** [comment]
that worked

root@pve:/# dig -x 192.168.0.10 @192.168.0.1

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> -x 192.168.0.10 @192.168.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7471
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1432
;; QUESTION SECTION:
;10.0.168.192.in-addr.arpa.     IN      PTR

;; ANSWER SECTION:
10.0.168.192.in-addr.arpa. 3600 IN      PTR     Nexus-Core.local.

;; Query time: 0 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Fri Dec 11 23:38:47 GMT 2020
;; MSG SIZE  rcvd: 90

**Comment by dschaper** [comment]
And what do you see in the query log on the admin webpage for that client? An IP address or a hostname?

**Comment by AlphaOmega2020** [comment]
ok now this is really odd as its working... i dont see IP's at all now, only hostnames..

**Comment by dschaper** [comment]
Side note: Check the domain you're using for conditional forwarding, you've set it up to be `Nexus.local` which will search for `host.Nexus.local`. 

Also, don't use `.local`, you'll cause issues with bonjour and mDNS>

**Comment by AlphaOmega2020** [comment]
thanks, this is very confusing as it seems just running that dig command kicked things into shape but makes no sense.

**Comment by dschaper** [comment]
Changing from bridge networking to host networking will affect things, this may be what caused the fix.

**Comment by AlphaOmega2020** [comment]
maybe but ive just tested by going back to bridge and its still working O_o

**Comment by dschaper** [comment]
I would be surprised if MAC addresses were passed in bridge mode.

**Comment by dschaper** [comment]
Nevertheless, looks solved now. Please re-open if you see the same issues.
