### ISSUE TITLE
web interface for two instances on machine both show stats/log from same instance

### ISSUE THREAD

**Issue by gklanderman** [pi-hole/docker-pi-hole#732]
### Versions
 Pi-hole version is v5.2.1 (Latest: v5.2.1)
  AdminLTE version is v5.2.1 (Latest: v5.2.1)
  FTL version is v5.3.2 (Latest: v5.3.2)

### Platform
- OS and version:   Raspbian GNU/Linux 10 (buster)
- Platform:   RPi 2b+, docker

### Expected behavior

See Issue #726 where I am tracking issues with starting multiple instances on a machine.
Having worked around those issues, I expect the web interface associated with each instance to show stats/logs pertaining to that instance.

### Actual behavior / bug

Web interface for both instances are showing stats/logs pertaining to the same instance

If I go to Settings -> DNS on each web instance (different IPs) I can see that each correctly shows the correct upstream DNS servers (one is pointing to Google and the other to cleanbrowsing.org family filter)

However, the stats on the Dashboard as well as the Query Log for both instances are both showing data from the same instance (the cleanbrowsing one).

Looking at the logs /var/log/pihole.log in each instance shows that each instance is operating correctly, contacting the correct upstream DNS servers and serving the correct cached entries from its own instance.

Would appreciate any help from developers on where to look to debug further.

I'll attach my docker run script in a moment.

thank you,
Greg

**Comment by gklanderman** [comment]
docker run script (had to add .txt suffix to upload)

[run-pihole-docker.txt](https://github.com/pi-hole/docker-pi-hole/files/5721430/run-pihole-docker.txt)

**Comment by PromoFaux** [comment]
> Web interface for both instances are showing stats/logs pertaining to the same instance

I can't see how this is possible - if both are separate instances, with separate persisted volumes it seems, how can one container be displaying information from the other?

**Comment by gklanderman** [comment]
Hi Adam, I agree it seems like it should not be possible.  I will try to find some time to reproduce the problem.. have been meaning to get back to pi-hole anyway: the multiple instances I started manually just over a year ago are still up and running, but I'd prefer to resolve issue #726 so manual intervention is not needed.
