### ISSUE TITLE
Wrong platform architecture on Docker Hub Images

### ISSUE THREAD

**Issue by shaderecker** [pi-hole/docker-pi-hole#735]
### Platform

- OS and version:  Debian Buster (I used that, but it also impacts stretch and multi-arch images)

- Platform:  Raspberry Pi

### Expected behavior

The right platform architecture is assigned to the respective images.

### Actual behavior / bug

The arch specific images are tagged with the wrong platform architecture.
Currently they all show amd64 as architecture regardless if they are specific arm or arm64 images.
Check for example the [v5.2.1-armhf-buster](https://hub.docker.com/layers/pihole/pihole/v5.2.1-armhf-buster/images/sha256-b2bdc30dd2024d1770f4e1358ea4fdf507ed9e63ae79d9e6fac9ececa2da00e6)
This armhf images wrongly displays amd64 as its architecture.
![image](https://user-images.githubusercontent.com/16366556/102833287-f4034880-43f0-11eb-8404-32c1b9c28d2c.png)

When using the image in my deployment it still works in the end, but Ansible complains with a warning that the image has the wrong architecture:
```
[WARNING]: Docker warning: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
```

I also tried the multi-arch image (e.g. [v5.2.1-buster](https://hub.docker.com/layers/pihole/pihole/v5.2.1-buster/images/sha256-5281797ed544ae438cd3c458171212d1e0cbf5c219a1cffe28b042a9f9821791)) which shows at least all three architectures (amd64/arm/arm64) in Docker Hub, but this also gives the same warning. So even there, the arch detection is somewhat broken.

Can you please have a look into this. Thanks.

**Comment by dschaper** [comment]
Does the issue still show with using the plain `pihole/pihole:v5.2.1`? There shouldn't be a need to use the buster specific variant.

**Comment by shaderecker** [comment]
Yes, I just tried the ```pihole/pihole:v5.2.1``` tag. It has the same issue

**Comment by dschaper** [comment]
Hmm, on a Raspberry Pi I just tried:
```plain
dan@raspberrypi:~ $ docker run -it --rm --entrypoint pihole-FTL pihole/pihole:v5.2.1 -vv
Unable to find image 'pihole/pihole:v5.2.1' locally
v5.2.1: Pulling from pihole/pihole
9159b6bb9431: Pull complete
af6c343a3853: Pull complete
c26d8a26526d: Pull complete
a9605594d712: Pull complete
f45b672ae3e8: Pull complete
37b3444e8040: Pull complete
1292910fb137: Pull complete
a54bdd0520cd: Pull complete
Digest: sha256:7888e89f4d435673c75896c546fefe3177379c99c8766c89be25a905f8def533
Status: Downloaded newer image for pihole/pihole:v5.2.1
****************************** FTL **********************************
Version:         v5.3.2

****************************** dnsmasq ******************************
Version:         pi-hole-2.81
Compile options: IPv6 GNU-getopt no-DBus no-UBus no-i18n IDN DHCP DHCPv6 Lua TFTP no-conntrack ipset auth DNSSEC loop-detect inotify dumpfile

****************************** SQLite3 ******************************
Version:         3.31.1
Compile options: COMPILER=gcc-6.3.0 20170516 DEFAULT_FOREIGN_KEYS OMIT_DEPRECATED OMIT_LOAD_EXTENSION OMIT_MEMORYDB OMIT_PROGRESS_CALLBACK THREADSAFE=1
******************************** LUA ********************************
Lua 5.4.1  Copyright (C) 1994-2020 Lua.org, PUC-Rio
```

**Comment by shaderecker** [comment]
Ok that is really weird, I ran the same command as you did and still got the error:
```
pi@pihole-2:~ $ docker run -it --rm --entrypoint pihole-FTL pihole/pihole:v5.2.1 -vv
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
****************************** FTL **********************************
Version:         v5.3.2

****************************** dnsmasq ******************************
Version:         pi-hole-2.81
Compile options: IPv6 GNU-getopt no-DBus no-UBus no-i18n IDN DHCP DHCPv6 Lua TFTP no-conntrack ipset auth DNSSEC loop-detect inotify dumpfile

****************************** SQLite3 ******************************
Version:         3.31.1
Compile options: COMPILER=gcc-6.3.0 20170516 DEFAULT_FOREIGN_KEYS OMIT_DEPRECATED OMIT_LOAD_EXTENSION OMIT_MEMORYDB OMIT_PROGRESS_CALLBACK THREADSAFE=1
******************************** LUA ********************************
Lua 5.4.1  Copyright (C) 1994-2020 Lua.org, PUC-Rio

```
```
pi@pihole-2:~ $ uname -a
Linux pihole-2 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux
```

**Comment by dschaper** [comment]
What does your `docker images` show?

```plain
dan@raspberrypi:~ $ docker images
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
pihole/pihole                              v5.2.1              3803f333ac15        2 weeks ago         329MB
```

And try `rm`ing the image you have downloaded. The `buster` and `stretch` says the OS used to build the image, not the OS version that is required to run. You should just use the plain tag by itself.

Also, what does `docker info` show?

```plain
 Kernel Version: 5.4.72-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
```

**Comment by dschaper** [comment]
And I think this came up before, but the way you install docker can cause problems. If this is Raspbian Buster then you can't `apt` install it:

https://docs.docker.com/engine/install/debian/#install-using-the-repository

**Comment by shaderecker** [comment]
Ok was too late with my previous edit :D 
I also tried removing all pihole containers and images from my raspberry and let it re-pull during the run command, but still the same warning.


Other output:
```
pi@pihole-2:~ $ docker images
REPOSITORY      TAG       IMAGE ID       CREATED       SIZE
pihole/pihole   v5.2.1    3803f333ac15   2 weeks ago   329MB
```

```
pi@pihole-2:~ $ docker info | grep -A 3 Kernel
 Kernel Version: 5.4.79-v7+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
```

**Comment by shaderecker** [comment]
Regarding the Docker installation on Raspbian: I am aware of the complications.
I deploy Docker with my Ansible role, which covers the official Debian Install guide: https://github.com/shaderecker/ansible-pihole/blob/master/roles/docker/tasks/main.yaml

**Comment by dschaper** [comment]
Looks like we have different kernel versions and docker versions.

What version of Raspberry Pi is the hardware, and what does

```
sudo apt-cache policy raspberrypi-kernel
```
show?

**Comment by shaderecker** [comment]
```
pi@pihole-2:~ $ sudo apt-cache policy raspberrypi-kernel
raspberrypi-kernel:
  Installed: 1.20201201-1
  Candidate: 1.20201201-1
  Version table:
 *** 1.20201201-1 500
        500 http://archive.raspberrypi.org/debian buster/main armhf Packages
        100 /var/lib/dpkg/status

```

**Comment by shaderecker** [comment]
The Raspberry Pi is a "Raspberry Pi 3 Model B Plus Rev 1.3"

**Comment by dschaper** [comment]
I see a similar report that mirrors what we are seeing. Docker 20 fails, docker 19 works:

https://github.com/portainer/portainer/issues/4585

**Comment by shaderecker** [comment]
Hmm yes this seems to be the issue. I just downgraded to ```docker-ce/buster,now 5:19.03.14~3-0~raspbian-buster armhf``` and there it also works correctly.

**Comment by shaderecker** [comment]
Maybe another thing:
Regardless of the Docker version, the Image always reports back amd64 as its architecture.

```
pi@pihole-2:~ $ docker image inspect pihole/pihole:v5.2.1 | grep Arch
        "Architecture": "amd64",
```

Even the v5.2.1-armhf-buster image says "Architecture": "amd64"

I found moby/moby#36552 where the issue about wrong archs is being discussed for quite some time.

Might it be that the arch is wrongly declared during the image build process somehow?

**Comment by dschaper** [comment]
> Might it be that the arch is wrongly declared during the image build process somehow?

If it is then its affecting multiple projects and thus I would consider that to be a problem with docker and not with the multiple projects that work fine in version 19.

**Comment by dschaper** [comment]
In re: that moby issue, it's rather clear that the `Architecture` config is from the environment that built the image. And indeed, we build the arm images on `amd64` hardware. There's no real CI way to do otherwise without building our own CI runners on actual arm hardware.

**Comment by shaderecker** [comment]
I was trying to figure out the build process of the pihole containers but I am struggling with that.
How is it currently done? 
I found this [Dockerfile_build](https://github.com/pi-hole/docker-pi-hole/blob/master/Dockerfile_build) which seems to build the images in a own docker container. But not sure if this is still used? At least the building of said container fails since the link to the docker-compose binary on Github is broken.

The other thing I found were scripts for Github Actions, which I assume are used now.
Maybe  some explanation/update of the build process would help here.

Another thing: I tried building an arm container on an amd64 machine with docker buildx, following this [guide](https://medium.com/@artur.klauser/building-multi-architecture-docker-images-with-buildx-27d80f7e2408). And this worked successfully.
In short sth like (you can also directly build multiarch images):
```
docker buildx build -t "testimg:latest" --platform linux/armhf --load .
```
And then ```docker image inspect testimg:latest``` correctly says:
```
"Architecture": "arm",
```

And then docker correctly! complains about the image, since I tried to run it on my amd64 machine:
```
ubuntu@docker-build-host:~/testimg$ docker run -it --rm testimg:latest 
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64) and no specific platform was requested
“Running on armv7l”
```

So maybe the image build process needs an improvement or update.
I am currently trying to build the pihole as an arm container, but this is more complicated since I am not fully understanding the current build process yet :D

**Comment by dschaper** [comment]
`docker buildx` is an experimental feature and not used in general release.

**Comment by dschaper** [comment]
@lightswitch05 Do you have any advice?

**Comment by lightswitch05** [comment]
How the base images are built: https://github.com/pi-hole/docker-base-images/blob/master/tag-and-push.sh#L3-L6

Images are built and pushed with `./gh-actions-test.sh`

`gh-actions-deploy.sh` then takes all the built images and builds the multi-arch manifest for it. Nothing it using buildx as far as I know.

**Comment by dschaper** [comment]
When it comes down to it, it works in 19, doesn't in 20. That tells me that docker broke something in 20. And again, there are multiple projects that are seeing this same issue so we're not a one-off. 

If you want to improve the build process, then please do. But if it's a process that then works in 20 and doesn't work in 19 we're in the same boat.

I'd wait to see what docker says as far as why 20 doesn't work.

**Comment by shaderecker** [comment]
Thank you two for your input. 
Discussion in docker/for-linux#1170 is ongoing. Let's see what comes out of it first.

**Comment by thaJeztah** [comment]
Did some further digging, and I suspect these images are cross-compiled on a amd64 (x86) machine, and have the incorrect architecture set in the image manifest (https://github.com/docker/for-linux/issues/1170#issuecomment-750363830)


https://github.com/docker/for-linux/issues/1170#issuecomment-750371249

> So concluding;
> 
> * looks like for this case, the issue is actually with the images having the incorrect architecture set in their metadata
> * docker 20.10 now prints a warning ("WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested"). Older versions of docker silently tried to run the image (which in this case would work, because the image _is_ an arm image, just "labeled" incorrectly
> * docker 20.10 now produces an error if the architecture of the image isn't supported by the engine (which it bases on the architecture specified in the image's manifest)
>


Perhaps a "I know what I'm doing; ignore what the image says" flag would be needed to allow running existing invalid images?

**Comment by thaJeztah** [comment]
Slightly more detail under what circumstances it fails (due to the image being invalid / having incorrect os/architecture in the metadata); https://github.com/docker/for-linux/issues/1170#issuecomment-750478242

**Comment by thaJeztah** [comment]
I think the correct fix for this would be to use `buildx` to do the cross-compile, instead of the https://github.com/pi-hole/docker-pi-hole/blob/a779c7fc37a38d911b66bc78fb714de782e0d519/gh-actions-test.sh#L18-L28

With [docker/build-push-action@v2](https://github.com/docker/build-push-action#usage) it should be possible to build (and push) a multi-arch image in oneusing buildx (and no need to manually set up qemu);

See the example here; https://github.com/docker/build-push-action#multi-platform-image; 

> ### Multi-platform image
> 
> ```yaml
> name: ci
> 
> on:
>   push:
>     branches: master
> 
> jobs:
>   multi:
>     runs-on: ubuntu-latest
>     steps:
>       -
>         name: Checkout
>         uses: actions/checkout@v2
>       -
>         name: Set up QEMU
>         uses: docker/setup-qemu-action@v1
>       -
>         name: Set up Docker Buildx
>         uses: docker/setup-buildx-action@v1
>       -
>         name: Login to DockerHub
>         uses: docker/login-action@v1 
>         with:
>           username: ${{ secrets.DOCKERHUB_USERNAME }}
>           password: ${{ secrets.DOCKERHUB_TOKEN }}
>       -
>         name: Build and push
>         uses: docker/build-push-action@v2
>         with:
>           context: .
>           file: ./Dockerfile
>           platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
>           push: true
>           tags: |
>             user/app:latest
>             user/app:1.0.0
> ```

but perhaps @crazy-max or @tonistiigi has additional hints

**Comment by dschaper** [comment]
> I think the correct fix for this would be to use `buildx` to do the cross-compile

Happy to investigate this. As long as it's a backwards compatible fix and won't bork the installs still on 19.

**Comment by thaJeztah** [comment]
It should be backward compatible; The existing images are technically invalid, and the reason it worked on docker 19.03 (and before) was that it happened to fully ignore the architecture in the image-metadata once the image was pulled.

**Comment by dschaper** [comment]
Thanks! Will review.

**Comment by thaJeztah** [comment]
Let me know if help is needed! I can try calling in the cavalry to assist 😅

**Comment by dschaper** [comment]
😄 Thanks! PR's are always welcome!

**Comment by crazy-max** [comment]
@dschaper I can make a shot with a PR if you willing to :)

**Comment by dschaper** [comment]
Please do!

**Comment by lightswitch05** [comment]
We purposely didn't use existing actions so that the build could be easily tested locally. I would rather see the existing logic updated to use buildx instead of the entire action replaced

**Comment by PromoFaux** [comment]
Yeah, have to agree there that being able to just run `./gh-actions-test.sh` locally is a godsend

**Comment by crazy-max** [comment]
@lightswitch05 Yep that's what I think too. Be able to repro locally and we could leverage [bake](https://github.com/docker/buildx#buildx-bake-options-target) for that.

**Comment by dschaper** [comment]
Any updates on this?

**Comment by PromoFaux** [comment]
Hey @crazy-max , appreciate you're probably busy, just wondering if you had made any progress on this. Or where we would need to start looking?

**Comment by crazy-max** [comment]
@dschaper @PromoFaux 

I had started to work on updating the workflow but I find it very difficult to understand and apprehend this repository. We depend on shell and python scripts whereas a simple docker build should be enough.

So I started again and made a new image from scratch but the study of the [`basic-install.sh` script](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh) is complicated to take into account. A lot of static items and system dependencies prevent us from a generic and agnostic approach to create a simple image.

Sorry I know that this is not the purpose of this issue but we should start to reduce the technical debt. IMHO we should first refactor `basic-install.sh` into several files to have a clearer view of it and understand the prerequisites.

As for the Docker image, here's where I'm at at the moment:

```Dockerfile
FROM --platform=${TARGETPLATFORM:-linux/amd64} crazymax/alpine-s6:3.12 as builder
RUN apk --update --no-cache add \
    autoconf \
    automake \
    binutils \
    build-base \
    cmake \
    git \
    gettext-dev \
    gmp-dev \
    libidn-dev \
    linux-headers \
    m4 \
    nettle-dev \
    nettle-static \
    openssl-dev \
    readline-dev \
    tar \
  && rm -rf /tmp/*

ENV FTL_VERSION="5.3.3"
WORKDIR /tmp/ftl
RUN git clone --branch v${FTL_VERSION} https://github.com/pi-hole/FTL . \
  && mkdir -p cmake \
  && cd cmake \
  && cmake .. \
  && cmake --help \
  && cmake --build . -- -j $(nproc)

ENV ADMINLTE_VERSION="5.2.2"
WORKDIR /tmp/adminlte
RUN git clone --branch v${ADMINLTE_VERSION} https://github.com/pi-hole/AdminLTE .

ENV PIHOLE_VERSION="5.2.2"
WORKDIR /tmp/pihole
RUN git clone --branch v${PIHOLE_VERSION} https://github.com/pi-hole/pi-hole .

ARG TARGETPLATFORM
FROM --platform=${TARGETPLATFORM:-linux/amd64} crazymax/alpine-s6:3.12

ENV S6_BEHAVIOUR_IF_STAGE2_FAILS="2" \
  TZ="UTC" \
  PUID="1500" \
  PGID="1500"

RUN apk --update --no-cache add \
    bash \
    ca-certificates \
    curl \
    gettext \
    gmp \
    libidn \
    libgsasl \
    libsecret \
    nettle \
    nettle-static \
    openssl \
    procps \
    readline \
    shadow \
    su-exec \
    tzdata \
  && mkdir -p /var/www \
  && addgroup -g ${PGID} pihole \
  && adduser -D -h /var/www/pihole -u ${PUID} -G pihole -s /bin/bash -D pihole \
  && rm -rf /tmp/* /var/cache/apk/*

COPY --from=builder /tmp/ftl/cmake/pihole-FTL /usr/bin/
COPY --from=builder /tmp/adminlte /var/www/admin/
COPY --from=builder /tmp/pihole /var/www/pihole/
COPY rootfs /

RUN echo "pihole-FTL $(pihole-FTL version)" \
  && setcap CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_NET_ADMIN,CAP_SYS_NICE+eip "$(which pihole-FTL)"

ENTRYPOINT [ "/init" ]
```

**Comment by thaJeztah** [comment]
Thanks; just some quick blurbs from a cursory glance

FWIW, `apk --no-cache add` / `api add --no-cache` always refreshes the package cache, and doesn't require cleaning up afterwards (so no `rm -rf /tmp/* /var/cache/apk/*` should be needed).

Assuming `PIHOLE_VERSION` determines what version to build, probably would be good to allow overriding the version (similar to other ones), e.g.;

(I tend to put these at the top / global args)

```dockerfile
ARG PIHOLE_VERSION=5.2.2
```

And if the version should be preserved in the final image, copy it to an env (or `LABEL`, which could use the standard annotations; https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md#pre-defined-annotation-keys);

```dockerfile
ENV PIHOLE_VERSION=$PIHOLE_VERSION
LABEL org.opencontainers.image.version=$PIHOLE_VERSION
```

From the look of it (just a cursory glance), it looks like `` and `` could be separate stages; that way they can be built in parallel;

```dockerfile
ARG FTL_VERSION=5.3.3

FROM --platform=${TARGETPLATFORM:-linux/amd64} crazymax/alpine-s6:3.12 AS builder
# .....

FROM builder AS ftl
ARG FTL_VERSION
WORKDIR /tmp/ftl
# ...

# final stage
COPY --from= ftl /tmp/ftl/cmake/pihole-FTL /usr/bin/
```

Potentially, the `git clone` for these could even be a platform-agnostic stage (it wouldn't be platform-specific, so `git clone` could be done _once_ using a "generic" alpine image (e.g.), then copied (or mounted with `--mount`) in platform/architecture-specific stages

**Comment by crazy-max** [comment]
@thaJeztah Oh this Dockerfile is just a draft but yeah I get what you mean. Basically labels will be created at build time through something like [this action](https://github.com/crazy-max/ghaction-docker-meta#about).

**Comment by thaJeztah** [comment]
> Basically labels will be created at build time through something like this action to reflect repo metadata.

Ah, right;  in this case I'm not sure that would be the desired info, as this repository only contains the scripts to build the Dockerfile, not the source-code 🤔 (at least, I somewhat would expect the image to contain info about `pihole` itself)

**Comment by crazy-max** [comment]
@thaJeztah Yes sure you can [overwrite labels](https://github.com/crazy-max/ghaction-docker-meta#overwrite-labels) too.

**Comment by PromoFaux** [comment]
> So I started again and made a new image from scratch but the study of the [`basic-install.sh` script](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh) is complicated to take into account.

Ahem, yes that script has grown quite organically over the years - I like to think I know it like the back of my hand - but appreciate that others get lost in it, If you have any questions.... 

At some point, we're going to be looking at really paring down `basic-install` - especially as we move closer toward things being in a a single binary (e.g upcoming 6.0 will no longer require `lighttpd` or `php` to be installed as it will ship with an embedded web server - and also RESTful API) So there will be lots that the install script is doing that can essentially go away at some point.

**Comment by dschaper** [comment]
Thanks for the help everyone!

Before things get too far, musl and `pihole-FTL` are not friendly with each other. `pihole-FTL` is a statically linked binary and doesn't do well on Alpine.

**Comment by dschaper** [comment]
@DL6ER Any thoughts on musl?

**Comment by DL6ER** [comment]
Sorry for the late reply. I'm back in operation now.

FTL is designed to be able to be fully statically linked (including the crypto library, LUA and everything else). This is reflected by the [architecture tests](https://github.com/pi-hole/FTL/blob/da89cc669f57fcefc6a171a5aa72c874f3ad0e78/test/arch_test.sh#L82-L88) *each* CI build has to comply with to pass the tests for this commit:
``` bash
elif [[ "${CIRCLE_JOB}" == "x86_64-musl" ]]; then

  check_machine "ELF64" "Advanced Micro Devices X86-64"
  check_static # Binary should not rely on any dynamic interpreter
  check_libs "" # No dependency on any shared library is intended
  check_file "ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped"
```

If there would be a single dynamic dependency, this test would fail and the binary would be rejected.

The reason for a missing pre-compiled `musl-arm/aarch64` binary is rather that nobody ever asked for it :-)
I vaguely recall having been asked to add the the current `x86_64-musl` CI build specifically for `docker` somewhen in 2019.

So I'm not exactly sure what the question is here, @crazy-max do you see any issues `(c)make`ing FTL ?

**Comment by guodajun** [comment]
sudo docker run -it --platform=linux/arm64  /bin/bash

**Comment by dschaper** [comment]
If anyone at all can help with this, please help!

**Comment by jorgeml** [comment]
This is causing issues with Podman 3.2 as reported here: https://github.com/containers/podman/issues/10682

**Comment by PromoFaux** [comment]
Hullo all, sorry for taking such a long time to get around to this... it should now be fixed in the latest `:dev` tag. Can you please check it out and report back?

**Comment by shaderecker** [comment]
Hi @PromoFaux, this looks really good now.
I just tested the dev tag on my Raspberry Pi and I got the correct arch from the image:
```
        "Architecture": "arm",
        "Variant": "v7",
```
Thank you for your work! 😀

**Comment by PromoFaux** [comment]
Good news, then my entire day yesterday was not wasted! (So even better news 😜)

Will hopefully will through with the next main tag/release currently in the process of checking which arch's build ( on branch `this-will-break`)

**Comment by shaderecker** [comment]
I tried the new image `pihole/pihole:2021.10` and this works like a charm 😀 
Thank you again for making that happen @PromoFaux!
I will close this now.

**Comment by PromoFaux** [comment]
There are probably more improvements that can come in time with this, but just want to say thanks to @crazy-max and @thaJeztah for their hints and pointers above. `buildx` is definitely the way forward!

**Comment by thaJeztah** [comment]
Thanks! Happy to see it works well for you. If you have feedback to either the [buildx cli](https://github.com/docker/buildx), [buildkit](https://github.com/moby/buildkit) (which does the actual build), or the [github actions](https://github.com/docker/?q=-action&type=&language=typescript&sort=); feel free to open tickets there (I linked the repositories) 🤗
