### ISSUE TITLE
Healthcheck failing in Docker PiHole 5.2.2

### ISSUE THREAD

**Issue by modem7** [pi-hole/docker-pi-hole#742]
### Versions

- Pi-hole:  5.2.2
- AdminLTE:  5.2.2
- FTL:  5.2.2

### Platform

- OS and version:  Fedora 27

- Platform:  Docker

### Expected behavior

For healthchecks not to fail

### Actual behavior / bug

5.2.1 works with no issues, 5.2.2 has intermittent healthcheck issues
![image](https://user-images.githubusercontent.com/4349962/103155408-8f9d0c00-4797-11eb-8dc9-c71ebbe2ffa8.png)

### Steps to reproduce

5.2.2 docker image. 

## Debug Token

Can't get as healthcheck renders image inoperable.

**Comment by PromoFaux** [comment]
Please try [`:v5.3.4`](https://github.com/pi-hole/docker-pi-hole/releases/tag/v5.3.4) docker image, there was an issue with FTL 5.3.3 that was affecting some installs.

**Comment by modem7** [comment]
Doing so now, thank you! Will close issue tonight if I see no issues.

**Comment by modem7** [comment]
No errors in several hours, will consider this resolved.
