### ISSUE TITLE
Persistently Disable Query Log

### ISSUE THREAD

**Issue by christoph-lucas** [pi-hole/docker-pi-hole#744]
### Versions

-  Pi-hole version is v5.2.1 (Latest: v5.2.1)                                                                                                                       
 - AdminLTE version is v5.2.1 (Latest: v5.2.1)                                                                                                                      
 - FTL version is v5.3.2 (Latest: v5.3.2)                                                                                                                           

### Platform

- OS and version:  pihole/pihole:latest

- Platform:  Docker

### Expected behavior

Being able to persistently disable query logging, in a way that survives Container restart and / or recreation.

### Actual behavior / bug

After a container restart, a disabled query logging is enabled again.

### Steps to reproduce

1. Go to Settings -> Disable Query Logging
2. Restart the container
3. Check if Query Logging is still disabled.

### Additional context

As far as I can see, there are two ways to disable query logging in pi-hole:

* Either using the WebGUI (Settings -> Button "Disable Query Logging"). Unfortunately, this setting is not made persistent. Hence, when the container is restarted, query logging is enabled again. This is the case even when mounting the dnsmasq.d config folder as a volume (i.e., the corresponding change in 01-pihole.conf gets overridden on restart).
* Or by starting pi-hole with the command line option "-l off noflush". Unfortunately, I could not find a way to pass command line options to the pi-hole command.

I am by far not an Docker expert. Yet, as far as I understand, the entrypoint to the Docker container is the s6 service, and not the pi-hole command itself. Therefore, adding command line options to the docker run command does not work (at least the container did not start any more when I tried it). I could not find any details in the documentation. Is there may be an undocumented option for that? Any help would be highly appreciated.

**Comment by cheesemacfly** [comment]
There's actually a environment variable for it too: `QUERY_LOGGING`. But same behavior, it doesn't stop the query logging.

**Comment by puddlewitt** [comment]
I added `QUERY_LOGGING: 'False'` environment variable thinking the query logging button
![image](https://user-images.githubusercontent.com/2998294/103918631-f0690480-5106-11eb-94a0-751405630d84.png) would default to off. It doesn't seem to.

**Comment by PromoFaux** [comment]
Closing as I believe this falls under #720 

(also, I have a fix in the works for this)
