### ISSUE TITLE
how update Pi-hole FTL v5.3.4

### ISSUE THREAD

**Issue by ramunozp** [pi-hole/docker-pi-hole#746]
### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  

- Platform:  

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

_A clear and concise description of what the bug is._

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/docker-pi-hole#upgrading-persistence-and-customizations
