### ISSUE TITLE
DNS lookup of container host shows 127.0.1.1 due to entry in /etc/hosts

### ISSUE THREAD

**Issue by sophonet** [pi-hole/docker-pi-hole#756]
### Versions
  Pi-hole version is v5.2.2 (Latest: v5.2.2)
  AdminLTE version is v5.2.2 (Latest: v5.2.2)
  FTL version is v5.3.4 (Latest: v5.3.4)

### Platform
- OS and version: Container host: Ubuntu 20.04
- Platform:  Docker (Podman)

### Expected behavior

When looking up host name of container host, valid IP should be returned, e.g. (example with ``192.168.0.10`` and host name ``container-host`` on which the container runs is given below, this how I would have expected it)

```
% dig container-host

; <<>> DiG 9.10.6 <<>> container-host
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1187
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;container-host.			IN	A

;; ANSWER SECTION:
container-host.		2	IN	A	192.168.0.10

;; Query time: 0 msec
;; SERVER: 192.168.0.10#53(192.168.0.10)
;; WHEN: Sun Jan 10 11:41:12 CET 2021
;; MSG SIZE  rcvd: 56
```

### Actual behavior / bug

Depending on the parameter ``--hostname`` when starting the container, the returned IP address is wrong both times:

1. If (according to the example above) the container is started with ``--hostname=container-host``, the dig command returns the container-internal IP address (eg. ``10.88.0.10`` in my case).
2. If the container is started with a different hostname parameter, e.g. the FQDN, the dig command returns localhost (``127.0.1.1``).

### Steps to reproduce

Launch the container with the launch script that is suggested by docker-pi-hole (I am using podman, I guess docker leads to the same issue):

```
# Note: ServerIP should be replaced with your external ip.
podman run --rm \
    --name pihole \
    -p 53:53/tcp -p 53:53/udp \
    -p 8080:80 \
    -p 443:443 \
    -e TZ="Europe/Berlin" \
    -v "${PIHOLE_BASE}/etc-pihole/:/etc/pihole/" \
    -v "${PIHOLE_BASE}/etc-dnsmasq.d/:/etc/dnsmasq.d/" \
    --dns=127.0.0.1 --dns=1.1.1.1 \
    --restart=no \
    --hostname XXXXXXXX \
    -e VIRTUAL_HOST="pi.hole" \
    -e PROXY_LOCATION="pi.hole" \
    -e ServerIP="192.168.0.10" \
    -e IPv6='true' \
    -e ServerIPv6='fd00::XXXXXXXX' \
    pihole/pihole:latest
```

Here, XXXXX... relate to the IPv6 address (not so relevant for this problem) and the hostname, which are explained in (1.) and (2.) above.

### Additional context

Both behaviors mentioned above appear correct to me, since, when launching the container, a file ``/etc/hosts`` is generated by docker/podman that contains the ``127.0.1.1`` as a copy from the hosts' ``/etc/hosts`` file, and another entry with the container-internal IP address for the hostname entry.

There is an option to ignore /etc/hosts for dnsmasq (``no_host``), but it is not enabled in ``/etc/dnsmasq.d/01-pihole.conf``. So it seems that even though the correct IPv4 and IPv6 addresses appear in ``/etc/pihole/local.list`` (for the container-host as wells  for the name pi.hole, both refer to ``192.168.0.10``, probably they have been generated by the ServerIP environment variables in the call above), they are not used for the reply.

**Comment by nimbius** [comment]
this is like the third or fourth instance of this bug reported.  happening to me too.

**Comment by PromoFaux** [comment]
Is this still an issue in latest tag?
