### ISSUE TITLE
tag v5.4 does not equal to latest

### ISSUE THREAD

**Issue by kbaikov** [pi-hole/docker-pi-hole#759]
### Platform

- OS and version:  

- Platform:  Raspberry Pi, docker/podman

### Expected behavior

docker pull pihole/pihole:v5.4 should yield the same image as docker pull pihole/pihole:latest

**Comment by dschaper** [comment]
Yep, looks like we need to update https://github.com/pi-hole/docker-pi-hole/blob/master/gh-actions-vars.sh#L44 to use `Location:` as well. GitHub's API now has a CSP that declares `location` as well.

**Comment by dschaper** [comment]
Usual caveat: Don't use `latest`, always pin to a versioned tag.

**Comment by kbaikov** [comment]
@dschaper just verified the fix. It works.
Thank you for a prompt reply.
