### ISSUE TITLE
Aborting installation: iproute2 and iproute packages were not found in APT repository

### ISSUE THREAD

**Issue by LiloBzH** [pi-hole/docker-pi-hole#762]
### Versions

- Pi-hole:  /
- AdminLTE: /  
- FTL:  /

### Platform

- OS and version:  Docker Synology

- Platform:  

### Steps to reproduce

Since new version v5.4

New install or update : 

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 **::: Starting docker specific checks & setup for docker pihole/pihole
Failed to set capabilities on file `/usr/bin/pihole-FTL' (Operation not supported)**
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
Assigning random password: t8NELHi9
  [i] Update local cache of available packages...
  [✓] Update local cache of available packages
  **[✗] Aborting installation: iproute2 and iproute packages were not found in APT repository.**
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

I suppose the problem is here : **iproute2 and iproute packages were not found in APT repository**

**Comment by MichlW** [comment]
I actually updated my docker pihole with the new version 5.4 and than it did not came up anymore using my existing config paths. I had a lot of trouble to recover but with 5.3.4 everything is working again.

something is wrong with 5.4... I can not provide any logs, because I had to recover as fast as I can. sorry.

Maybe this issue was the problem also?

**Comment by decruns** [comment]
Can confirm, I'm having the exact same issue.  Just restored the previous image and everything is working normally again.

**Comment by PromoFaux** [comment]
Thanks for the reports. Currently unable to reproduce this. v5.3.4 -> v5.4 when fine on my system (albeit I did it via the `:dev` tag to test it before it was released)

looking into it...

**Comment by dschaper** [comment]
What is the output from

`docker run -it --rm pihole/pihole:latest`

**Comment by LiloBzH** [comment]
```
root@NAS:/# docker run -it --rm pihole/pihole:latest
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
 ::: Starting docker specific checks & setup for docker pihole/pihole
Failed to set capabilities on file `/usr/bin/pihole-FTL' (Operation not supported)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
Assigning random password: JvYfoxWf
  [✓] Update local cache of available packages
  [✗] Aborting installation: iproute2 and iproute packages were not found in APT repository.
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
^C[s6-finish] sending all processes the KILL signal and exiting.

```

PS : Upgrade ok on Raspberry too

**Comment by dschaper** [comment]
What version of docker and what image ID?

**Comment by dschaper** [comment]
Try with the tagged version and not latest:

```plain
docker run -it --rm pihole/pihole:v5.4
Unable to find image 'pihole/pihole:v5.4' locally
v5.4: Pulling from pihole/pihole
Digest: sha256:10346b90481cc02336157dbd08867e4fc41249d85b4f0def9f9d59a94052a917
Status: Downloaded newer image for pihole/pihole:v5.4
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
 ::: Starting docker specific checks & setup for docker pihole/pihole
Assigning random password: qu_5d7b-
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.19-1~deb10u1

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chown: cannot access '': No such file or directory
chmod: cannot access '': No such file or directory
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
Existing DNS servers detected in setupVars.conf. Leaving them alone
Setting password: qu_5d7b-
+ pihole -a -p qu_5d7b- qu_5d7b-
  [✓] New password set
DNSMasq binding to default interface: eth0
Added ENV to php:
                        "PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
                        "ServerIP" => "0.0.0.0",
                        "VIRTUAL_HOST" => "0.0.0.0",
Using IPv4 and IPv6
::: setup_blocklists now setting default blocklists up:
::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
::: Blocklists (/etc/pihole/adlists.list) now set to:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
::: Testing pihole-FTL DNS: FTL started!
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
::: Enabling Query Logging
  [i] Enabling logging...
  [✓] Restarting DNS server
  [✓] Logging has been enabled!
 ::: Docker start setup complete
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range
```

**Comment by LiloBzH** [comment]
```
root@NAS:/# docker run -it --rm pihole/pihole:v5.4-amd64-buster
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
 ::: Starting docker specific checks & setup for docker pihole/pihole
Failed to set capabilities on file `/usr/bin/pihole-FTL' (Operation not supported)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
Assigning random password: 1vQXxN_B
  [✓] Update local cache of available packages
  [✗] Aborting installation: iproute2 and iproute packages were not found in APT repository.
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
^C[s6-finish] sending all processes the KILL signal and exiting.

```

**Comment by dschaper** [comment]
Use the exact image I asked please.

**Comment by LiloBzH** [comment]
```
root@NAS:/# docker run -it --rm pihole/pihole:v5.4
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
 ::: Starting docker specific checks & setup for docker pihole/pihole
Failed to set capabilities on file `/usr/bin/pihole-FTL' (Operation not supported)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
Assigning random password: _ImnHwJD
  [✓] Update local cache of available packages
  [✗] Aborting installation: iproute2 and iproute packages were not found in APT repository.
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by reedriley** [comment]
This repros for me as well; here's the output when I run `pihole/pihole:v5.4`, if that helps:

```
❯ docker run -it --rm pihole/pihole:v5.4
Unable to find image 'pihole/pihole:v5.4' locally
v5.4: Pulling from pihole/pihole
Digest: sha256:10346b90481cc02336157dbd08867e4fc41249d85b4f0def9f9d59a94052a917
Status: Downloaded newer image for pihole/pihole:v5.4
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
 ::: Starting docker specific checks & setup for docker pihole/pihole
Assigning random password: G5NKZmgI
  [✓] Update local cache of available packages
  [✗] Aborting installation: iproute2 and iproute packages were not found in APT repository.
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by dschaper** [comment]
Okay, post your `docker info` and `docker images`. I'm trying to find out what host platform you are using and the image your are running. Running images for other architectures will do odd things.

**Comment by PromoFaux** [comment]
OK, we need to find some sort of commonality here.

OP is running on Synology - not working. I am running on Synology - working.
Also seeing reports above of debian 10, and raspberry pis....

**Comment by decruns** [comment]
```
root@debian:/var/lib/docker/image#` docker info
Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 7
  Paused: 0
  Stopped: 4
 Images: 184
 Server Version: 19.03.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-9-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.719GiB
 Name: debian
 ID: LDDU:6FD7:RLYZ:KMW4:45LN:7J76:ZO2W:NMIG:AH7I:AUWZ:JW4N:3ND6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
root@debian:/var/lib/docker/image# docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
pihole/pihole                      latest              3ff7d452edd7        3 hours ago         332MB
linuxserver/sonarr                 preview             664755a49350        21 hours ago        627MB
linuxserver/jellyfin               latest              fa3398d45003        41 hours ago        599MB
linuxserver/jackett                latest              bb1576bdf079        2 days ago          260MB
linuxserver/plex                   latest              4ace97ec22bc        3 days ago          678MB
ghcr.io/linuxserver/transmission   latest              0e104184c021        6 days ago          90.2MB
pihole/pihole                      v5.3.4              4e527559577f        3 weeks ago         330MB
```

**Comment by reedriley** [comment]
```
❯ docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 21
  Running: 20
  Paused: 0
  Stopped: 1
 Images: 233
 Server Version: dev
 Storage Driver: btrfs
  Build Version: Btrfs v5.4.1
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: de40ad007797e0dcd8b7126f27bb87401d224240)
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.10.7-gentoo
 Operating System: Gentoo/Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.24GiB
 Name: <redacted>
 ID: <redacted>
 Docker Root Dir: <redacted>
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  http://localhost:5000/
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support

❯ docker images | grep pihole
pihole/pihole                     latest                      3ff7d452edd7   3 hours ago         332MB
pihole/pihole                     v5.4                        3ff7d452edd7   3 hours ago         332MB
pihole/pihole                     <none>                      4e527559577f   3 weeks ago         330MB
```

**Comment by jwalker343** [comment]
repro'd here as well.

docker: Docker version 19.03.6, build 369ce74a3c
ubuntu: Ubuntu 18.04.2 LTS
using image: pihole/pihole:latest 

## Make sure on latest
```
root@ns1:/home/ubuntu# docker pull pihole/pihole
Using default tag: latest
latest: Pulling from pihole/pihole
Digest: sha256:10346b90481cc02336157dbd08867e4fc41249d85b4f0def9f9d59a94052a917
Status: Image is up to date for pihole/pihole:latest
docker.io/pihole/pihole:latest
```


## Logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
 ::: Starting docker specific checks & setup for docker pihole/pihole
  [✓] Update local cache of available packages
  [✗] Aborting installation: iproute2 and iproute packages were not found in APT repository.
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

## Docker info
```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 6
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-122-generic
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.947GiB
 Name: ns1
 ID: BMVI:T7QM:UOO7:QDHN:DOBI:BQZD:WLLG:ESLU:LNJT:TSNL:STTM:4XW4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 ```

**Comment by ldekamps** [comment]
Running into the exact same issues on my Raspberry Pi. Decided to downgrade to v5.3.4 and everything is running flawless again.

`> docker info
Client:
 Debug Mode: false

Server:
 Containers: 10
  Running: 7
  Paused: 0
  Stopped: 3
 Images: 17
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.97-v7+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 926.1MiB
 Name: raspberrypi
 ID: D2BA:AQ5M:XZGP:R5P7:ES2I:G667:BDRT:FXSS:LPY3:OTWX:VU6N:SPUY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support`

`> docker images | grep pihole
pihole/pihole           latest              1292321698ac        3 hours ago         328MB
pihole/pihole           v5.3.4              3660ad7469fb        3 weeks ago         326MB
`

**Comment by PromoFaux** [comment]
OK I've finally been able to reproduce this on my system. 

On the host machine, make sure the nameserver is NOT set to `127.0.0.1`, or whatever the Pi-hole IP is. Set it to something like `8.8.8.8` 

(check the content of `/etc/resolv.conf`)

**Comment by decruns** [comment]
Mine sadly already was set to 8.8.8.8

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 8.8.8.8

```

**Comment by ldekamps** [comment]
I also use other nameservers on the host machine, so that doesn't seem to be the issue.
```
cat /etc/resolv.conf
# Generated by resolvconf
nameserver 1.1.1.1
nameserver 1.0.0.1
```

**Comment by PromoFaux** [comment]
OK, worth a shot. The only way I can get it to reproduce on my machine is to set the host's nameserver to that of the Pi-hole container.

What do your run scripts / compose files look like?

**Comment by LiloBzH** [comment]
Sorry for my question but you ignore message in LOG ?

**iproute2 and iproute packages were not found in APT repository**

You  think it's another problem ?

**Comment by PromoFaux** [comment]
No, not ignoring. That seems to be the common error here. And the only way I could reproduce that error was to effectively break name resolution.

**Comment by decruns** [comment]
```
version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
      - SERVERURL=192.168.1.13
      - WEBPASSWORD=webbydiffy
    volumes:
      - /home/docker/pihole:/etc/pihole
      - /home/docker/dnsmasq:/etc/dnsmasq.d
    ports:
      - 80:80
      - 53:53/tcp
      - 53:53/udp
    dns:
      - 127.0.0.1
```

**Comment by reedriley** [comment]
@PromoFaux: If you think that name resolution may cause that error; is it possible that the step `Update local cache of available packages` is failing silently?

**Comment by PromoFaux** [comment]
>is it possible that the step Update local cache of available packages is failing silently?

Absolutely this. It's the only way I can get it to fail consistently on multiple machines. 

@decruns can you try changing:

```
dns:
 - 127.0.0.1
```

to:

```
dns:
 - 8.8.8.8
```

and then try again with `:v5.4`

**Comment by ldekamps** [comment]
Confirmed, it's running now. I also had the DNS values within the docker-compose-file at 127.0.0.1 and after changing to 8.8.8.8, image 5.4 is working again.

**Comment by decruns** [comment]
Yes that was the fix for me, thanks!

**Comment by jwalker343** [comment]
The Official documentation states that 127.0.0.1 must be the first DNS resolver. 

https://hub.docker.com/r/pihole/pihole
> 
> Starting with the v4.1.1 release your Pi-hole container may encounter issues starting the DNS service unless ran with the following setting:
> 
> --dns=127.0.0.1 --dns=1.1.1.1 The second server can be any DNS IP of your choosing, but the first dns must be 127.0.0.1
> A WARNING stating "Misconfigured DNS in /etc/resolv.conf" may show in docker logs without this.

**Comment by PromoFaux** [comment]
🎉 Yep. So the answer, I believe, is that I was right with my hunch above, I was just looking to solve it in the wrong place.


>The Official documentation states that 127.0.0.1 must be the first DNS resolver.

Yep, you're right, however I think that may be outdated. A few months back we stopped FTL from setting itself as the resolver for a machine, I guess that hasn't fully translated over to the docker image yet. 

That all said, you'll probably find it still works when setting both `--dns 127.0.0.1` and `--dns [whatever else]` too.

**Comment by decruns** [comment]
> That all said, you'll probably find it still works when setting both `--dns 127.0.0.1` and `--dns [whatever else]` too.

That doesn't work for me. Only setting another DNS as the first option works.

**Comment by PromoFaux** [comment]
Thanks for that feedback 👍

**Comment by PromoFaux** [comment]
@LiloBzH , @MichlW, @reedriley , @jwalker343 

does changing the container's DNS work for you?

**Comment by LiloBzH** [comment]
that's ok too

I have add nameserver 9.9.9.9 in share file  /etc/resolv.conf and upgrade / new install is ok

**Comment by MichlW** [comment]
> @LiloBzH , @MichlW, @reedriley , @jwalker343
> 
> does changing the container's DNS work for you?

Yes, thank you!
When starting the docker container with `--dns 1.1.1.1` everything is ok. I removed `--dns 127.0.0.1` (as actually recoomended in the documentation) now completely and hope thats the best way for new versions.

**Comment by MichlW** [comment]
Does anybody know how I can configure an upstream cloudflared container in Pi-Hole dockers `--dns` parameter which is running on different port e.g. 5053 ?

The problem on this issue was that Pi-Hole itself (127.0.0.1) was not able to resolve queries on port 53. But in my case there is also running a cloudflared on port 5053. So I do not need to resolve that issue by setting `--dns 1.1.1.1` and want to use something like `--dns 172.17.0.1#5053`.

Any ideas?

**Comment by PromoFaux** [comment]
@MichlW use the `PIHOLE_DNS_` [environment variable](https://github.com/pi-hole/docker-pi-hole#environment-variables) to tell Pi-hole to use cloudflared as the upstream. I'm unsure about setting a port number for the resolv.conf in the actual container, though. (Marking your question, and my answer off-topic to keep things tidy.. Please feel free to ask the community at https://discourse.pi-hole.net)

**Comment by johntdavis84** [comment]
Hello,

I just found this thread tonight, after having this exact issue on a brand new Linode Ubuntu install I (tried) to set up today.

I removed the `127.0.0.1` entry from my compose file, but it doesn't seem to have fixed the problem. I removed the image and had docker-compose force recreate/rebuild the container, but still no change.

I've included my system info + compose file below. What am I missing?

> setsuna@localhost:/docker/images/pihole$ docker --version
> Docker version 20.10.2, build 2291f61
> setsuna@localhost:/docker/images/pihole$ docker-compose --version
> docker-compose version 1.27.4, build 40524192

> $ uname -a
> Linux localhost 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> 
> $ cat docker-compose.yml 
> version: '3.4'
> services:
> 
>    Pihole:
>     container_name: pihole_with_ipv6_support
>     image: pihole/pihole:latest
>     hostname: SinisterPisces-DNSService
>     ports:
>       - "53:53/tcp"
>       - "53:53/udp"
>       - "43080:80/tcp"
>       - "4343:443/tcp"
>     environment:
>       TZ: America/Chicago 
>       DNS1: 1.1.1.2
>       DNS2: 1.0.0.2
>       WEBPASSWORD: REDACTED
>       ServerIP: REDACTED
>       enable_ipv6: "true"
>       ServerIPv6: REDACTED
>     volumes:
>        - '/docker/images/pihole/etc-pihole/:/etc/pihole/'
>        - '/docker/images/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
>     dns:
>       - 1.1.1.2
>     cap_add:
>       - NET_ADMIN
>     restart: unless-stopped
> 
> networks:
>   default:
>     external:
>       name: pihole_v6_net

**Comment by robert36580** [comment]
- [ ] [![image](https://user-images.githubusercontent.com/75908711/104893947-103bcc00-5942-11eb-976f-7c72ea4caa5d.png)]()

**Comment by robert36580** [comment]
Sorry my bad y'all

**Comment by PromoFaux** [comment]
The patch in core that caused this to happen has been reverted, and this should now be reflected in `:v5.5`

**Comment by MichlW** [comment]
v5.5 works for me even when configured with `--dns 127.0.0.1`.
Thanks for that!

**Comment by mlavi** [comment]
Confirmed `--dns 127.0.0.1` works as the only setting with **v5.5.1**, whereas before I had to make a list with 127.0.0.1 (first) and a public DNS server (second) to allow APT repo access with **v5.4**.

**Comment by johntdavis84** [comment]
You know, I’ve never asked, but … what does the APT repo do? Is it checking to see if there are pihole updates available?

**Comment by PromoFaux** [comment]
It's checking on the dependencies. In all honesty it probably shouldn't be calling those functions on container start, as all the dependencies are sorted out when the container is built (via `install.sh`)

When I get a chance, I'll take a deep dive into `start.sh` and try to trim out some of the unnecessary stuff.

**Comment by johntdavis84** [comment]
Cool. Thanks for the info, and for making time to look deeper into it.

It did confuse me a bit that a container was apparently trying to update itself outside the usual docker-based update process…

	- JTD.

**Comment by edgd1er** [comment]
if that helps:
start.sh ->prepare_config (bash_fonctions.sh) -> distro_check (basic-install.sh)
