### ISSUE TITLE
Typo in v5.5 release notes

### ISSUE THREAD

**Issue by casperklein** [pi-hole/docker-pi-hole#766]
@PromoFaux 

See https://github.com/pi-hole/docker-pi-hole/releases/tag/v5.5

I think, in the release notes, _https://github.com/pi-hole/AdminLTE/releases/tag/v5.1_ should be _https://github.com/pi-hole/AdminLTE/releases/tag/v5.3.1_

**Comment by PromoFaux** [comment]
Thanks! Sorted
