### ISSUE TITLE
PiHole (Docker) in Synology stopped working.

### ISSUE THREAD

**Issue by mdstoll** [pi-hole/docker-pi-hole#768]
### Versions

- Pi-hole:  V5.2.3
- AdminLTE:  V5.3
- FTL:  V5.4

### Platform

- OS and version:  Synology NAS DSM 6.2.3-25426 Update 2 [Linux]

- Platform:  Linux

### Expected behavior

_Created a Docker PiHole installation some months ago by following this guide: https://mariushosting.com/how-to-install-pi-hole-on-your-synology-nas/. After boot, expecting docker pihole to launch and to work properly. Unfortunately since last weekend the WebUI and DNS services are unresponsive. Docker container is running though (displayed and looking at the logs). Last line is [services.d] done._

### Actual behavior / bug

_Webpage isn't displaying; DNS filtering service isn't working. Had to reset the DNS server on my devices to regain internet. This happened at random (maybe watchtower updated the container, not 100% sure)._

### Steps to reproduce

Can't really reproduce it. It just seems broken, without me doing anything. 
I've tried to recreate the container from scratch but that didn't work for me.

## Debug Token

- URL:  https://tricorder.pi-hole.net/8o27wei02a

## Screenshot:

Variables:
<img width="1000" alt="Schermafbeelding 2021-01-21 om 16 07 03" src="https://user-images.githubusercontent.com/22054619/105369382-c9302e00-5c02-11eb-96f3-f7bed96bd5af.png">

**Comment by buckaroogeek** [comment]
I just updated by 5.2.2 pihole docker instance on Synology DSM 6.2.3-25426
Update 3. Result is

   - *Pi-hole* v5.2.4 <https://github.com/pi-hole/pi-hole/releases/v5.2.4>
   - *Web Interface* v5.3.1
   <https://github.com/pi-hole/AdminLTE/releases/v5.3.1>
   - *FTL* v5.5.1 <https://github.com/pi-hole/FTL/releases/v5.5.1>

So far, web interface is working and pihole is working.

Brad

**Comment by PromoFaux** [comment]
> I just updated by 5.2.2 pihole docker instance on Synology DSM 6.2.3-25426

Hopefully by this you mean you pulled the latest `:v5.5.1` docker image?

@mdstoll have you tried `:v5.5.1`?

**Comment by buckaroogeek** [comment]
I used docker-compose pull with the following compose yaml fragment so
it would have pulled pihole:latest:
services:
  pihole:     # Pi Hole dns server for local network
    container_name: SageCreek-Pi-Hole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: lan
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      macvlan1:
        ipv4_address: 192.168.110.201

**Comment by mdstoll** [comment]
Thanks for all the replies.

Just followed steps as described here in order to update the container: https://community.synology.com/enu/forum/1/post/123646

Currently running:

```
  Pi-hole version is v5.2.4 (Latest: v5.2.3)                                                                                                                                                                                             
  AdminLTE version is v5.3.1 (Latest: v5.3)                                                                                                                                                                                              
  FTL version is v5.5.1 (Latest: v5.4) 
```

The webpage still doesn't start. 

These are the last lines of the log:

```
[cont-init.d] 20-start.sh: exited 0.                                                                                                                                                                                                     
[cont-init.d] done.                                                                                                                                                                                                                      
[services.d] starting services                                                                                                                                                                                                           
Starting crond                                                                                                                                                                                                                           
Starting lighttpd                                                                                                                                                                                                                        
Starting pihole-FTL (no-daemon) as root                                                                                                                                                                                                  
[services.d] done.   
```

**Comment by PromoFaux** [comment]
```
  Pi-hole version is v5.2.4 (Latest: v5.2.3)                                                                                                                                                                                             
  AdminLTE version is v5.3.1 (Latest: v5.3)                                                                                                                                                                                              
  FTL version is v5.5.1 (Latest: v5.4) 
```

Something _very_ wrong here

If you create a brand new container - without pulling across any of the configs/volumes from the previous one - does it launch? (It should do!) Are you using the synology gui, or the command line?

**Comment by PromoFaux** [comment]
Regardless, though, this appears to be a configuration issue rather than one with the container (which I know runs 😉)

I think our forums are probably a better place to ask for configuration help, we have a specific docker category there, and the community don't bite too hard!

https://discourse.pi-hole.net/c/bugs-problems-issues/docker/30
