### ISSUE TITLE
pihole sets its own ipv4 address to 0.0.0.0

### ISSUE THREAD

**Issue by composingmotion** [pi-hole/docker-pi-hole#770]
### Versions
  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.3.1 (Latest: v5.3.1)
  FTL version is v5.5.1 (Latest: v5.5.1)

### Platform
Server Arch Linux
##Secondary Platform
podman  

### Expected behavior
podman run -d --name=pihole -e TZ=America/Chicago -e WEBPASSWORD=Password -e SERVERIP=10.1.0.1 -v pihole:/etc/pihole -v dnsmasq:/etc/dnsmasq.d --restart=unless-stopped --ip 10.1.0.70 --network celest.podman.default pihole/pihole

will result in pihole setting its address to 10.1.0.70

### Actual behavior / bug

pihole set its IP to 0.0.0.0

### Steps to reproduce

podman network create --subnet 10.1.0.0/24 --gateway 10.1.0.1 --ip-range 10.1.0.0/24 celest.podman.default

podman run -d --name=pihole -e TZ=America/Chicago -e WEBPASSWORD=Jegjames90 -e SERVERIP=10.1.0.1 -v pihole:/etc/pihole -v dnsmasq:/etc/dnsmasq.d --restart=unless-stopped --ip 10.1.0.70 --network celest.podman.default pihole/pihole

podman exec -it pihole /bin/bash

pihole -d

## Debug Token

- URL:  https://tricorder.pi-hole.net/resq26os65

### Additional context
containers starts and is available at 10.1.0.70.. but I get all kinds of problems.. 
cannot set network domain name.. 
pihole -r Hangs.  "  Error: Neither IPv4 or IPv6 selected"
pihole -d also clearly unhappy

attempts to resolve. edit /etc/pihole/setVars.conf
changes do not persist or have any effect

also Hopeing this is also related as to why I cannot access the the admin page using pihole.admin.home

**Comment by shaderecker** [comment]
Hi, one thing I noticed: Your SERVERIP env var should not be all uppercase (use "ServerIP" instead of SERVERIP).
Also see: https://github.com/pi-hole/docker-pi-hole#environment-variables

**Comment by nimbius** [comment]
ServerIP seems to get ignored in favor of the dcker/podman local IP in /etc/hosts when its compiled into local.list

**Comment by hulleyrob** [comment]
Has anyone found a way round this?

I set this up using the instructions at https://servicemax.com.au/tips/pi-hole-in-docker-on-synology-the-best-way/ and have the same problem, setting or deleting the server ServerIP env does nothing. 

Even overwriting every instance I can find of 0.0.0.0 with the correct ip in the volume files just gets restart when the container is created.

**Comment by hulleyrob** [comment]
after many hours of fiddling gave up and googled only to find this much simpler guide:

https://kevq.uk/how-to-setup-pi-hole-on-a-synology-nas/

and it worked straight away.

**Comment by swifty99** [comment]
Same here. On a 5.2 backup system it seems OK. 
Any updates?

**Comment by dschaper** [comment]
What's your docker-compose look like?

**Comment by swifty99** [comment]
I use portainer, it looks like this:
![grafik](https://user-images.githubusercontent.com/6912030/134338556-573d7f35-1f75-4065-9830-982533bd1395.png)
is that the relevant information?

I recreated pihole with latest. It seems to work now. However, the networking tab inside pihole to see the wrong IP has moved where I don't find it.

The debug log gives me:

`*** [ DIAGNOSING ]: Discovering active DHCP servers (takes 10 seconds)
   Scanning all your interfaces for DHCP servers
   Timeout: 10 seconds
   
   * Received 318 bytes from eth0:192.168.42.1
     Offered IP address: 192.168.42.146
     Server IP address: N/A
     Relay-agent IP address: N/A
     BOOTP server: (empty)
     BOOTP file: (empty)
     DHCP options:
      Message type: DHCPOFFER (2)
      server-identifier: 192.168.42.1
      lease-time: 86400 ( 1d )
      netmask: 255.255.255.0
      router: 192.168.42.1
      dns-server: 192.168.42.225
      dns-server: 192.168.42.226
         renewal-time: 43200 ( 12h )
      rebinding-time: 75600 ( 21h )
      domain-name: "localdomain"
      --- end of options ---
    
   DHCP packets received on interface lo: 0
   DHCP packets received on interface eth0: 1

*** [ DIAGNOSING ]: Pi-hole processes
[✗] lighttpd daemon is inactive
[✗] pihole-FTL daemon is inactive

*** [ DIAGNOSING ]: Pi-hole-FTL full status
[i] systemctl:  command not found

*** [ DIAGNOSING ]: Setup variables
    BLOCKING_ENABLED=true
    IPV4_ADDRESS=0.0.0.0
    INSTALL_WEB_SERVER=true
    INSTALL_WEB_INTERFACE=true
    PIHOLE_DNS_1=8.8.8.8
    PIHOLE_DNS_2=192.168.42.1
    PIHOLE_INTERFACE=eth0
    QUERY_LOGGING=true`


To note: I have two piholes running on two pies for redundancy. 

And why is my code formatting always not working?

**Comment by bscottm** [comment]
+1 for this issue. 

`pihole-FTL` works outstandingly, but `pihole` in a container with `network_mode: host` has the same issue: the IPv4 address of the host (e.g., "resolver.example.com" where the container runs and listens to port 53, et. al) is "0.0.0.0". Generating a debug log is inoperative within the container.

All of the configuration files are the same; I simply copied the `/etc/dnsmasq.d` and `/etc/pihole` directories to local `etc-dnsmasq.d` and `etc-pihole` as specified in the quick start `docker-compose.yml`.
