### ISSUE TITLE
FTL update available

### ISSUE THREAD

**Issue by adrianmihalko** [pi-hole/docker-pi-hole#775]
### Versions

pihole    |   Pi-hole version is v5.2.4 (Latest: v5.2.4)
pihole    |   AdminLTE version is v5.3.1 (Latest: v5.3.1)
pihole    |   FTL version is v5.5.1 (Latest: v5.5.1)

### Platform

- OS and version:  Debian 10

- Platform:  VM

### Expected behavior

I setup PiHole docker using provided docker-compose.yml file, but I am getting Update available message for FTL:

<img width="422" alt="Screenshot 2021-01-26 at 15 41 33" src="https://user-images.githubusercontent.com/733361/105860112-88169000-5fed-11eb-8070-d1a68b25b5c5.png">
 

### Actual behavior / bug

I am getting Update available message for FTL even when it seem to be latest version is installed.

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by fermulator** [comment]
(i think this is just a release timing thing -- `pihole` core can easily release updates (which it'll detect) but pihole docker hasn't been updated/released to get it?
