### ISSUE TITLE
Change theme through docker-compose.yml

### ISSUE THREAD

**Issue by Mellbourn** [pi-hole/docker-pi-hole#778]
The `API/Web interface` settings tab now contains an `Interface appearance` section where you can set `Pi hole midnight theme (dark)`. It would be awesome if that was configurable in the `docker-compose.yml` file.

**Comment by PromoFaux** [comment]
The ability to do this was introduced in [`:v5.8.1`](https://github.com/pi-hole/docker-pi-hole/releases/tag/v5.8.1)
