### ISSUE TITLE
Teleporter is not available in comandline in docker container

### ISSUE THREAD

**Issue by stepanovdg** [pi-hole/docker-pi-hole#779]
### Versions

 - Pi-hole version is v5.2.4 (Latest: v5.2.4)
 - AdminLTE version is v5.3.1 (Latest: v5.3.2)
 - FTL version is v5.5.1 (Latest: v5.6)

### Platform

- OS and version:  Docker

- Platform:  Docker

### Expected behavior

_
I expect to use teleporter in order to backup config of pihole running in docker.
Rather then use rsync.  According to https://github.com/pi-hole/pi-hole/pull/1298 such option should exist in cmd.
Previoulsy was using rsync of some files. Some version ago groups were introduced. So currently have no idea which file store that config and dont want to rsync db files. 
I found that FAQ a bit outdated https://discourse.pi-hole.net/t/what-files-does-pi-hole-use/1684 

So if it is was by purpose disabled - could you please help me with better backup option?
_

### Actual behavior / bug
_
docker exec -it pihole /bin/bash pihole -a 
Usage: pihole -a [options]
Example: pihole -a -p password
Set options for the Admin Console

Options:
  -p, password        Set Admin Console password
  -c, celsius         Set Celsius as preferred temperature unit
  -f, fahrenheit      Set Fahrenheit as preferred temperature unit
  -k, kelvin          Set Kelvin as preferred temperature unit
  -e, email           Set an administrative contact address for the Block Page
  -h, --help          Show this help dialog
  -i, interface       Specify dnsmasq's interface listening behavior
  -l, privacylevel    Set privacy level (0 = lowest, 3 = highest)
_

### Steps to reproduce

1. docker exec -it pihole /bin/bash pihole -a

**Comment by dschaper** [comment]
Did you try using the command in the PR that you linked?

```plain
docker exec -it pihole /bin/bash pihole -a -t
```
And as the PR notes, you'll need to have a volume mounted for the file otherwise it's kind of a pointless exercise.

```plain
docker run --name pihole --rm -d pihole/pihole:latest
a15c705d1f6fbc1e4180308e93c08b927befde67d3abaecd6e3198b5b60e6d8d

docker exec -it pihole /bin/bash pihole -a -t
docker exec -it pihole ls -la
total 128
drwxr-xr-x   1 root root  4096 Jan 30 03:50 .
drwxr-xr-x   1 root root  4096 Jan 30 03:50 ..
-rwxr-xr-x   1 root root     0 Jan 30 03:50 .dockerenv
-rw-r--r--   1 root root 11809 Jan 16 20:14 bash_functions.sh
drwxr-xr-x   1 root root 12288 Jan 16 20:17 bin
drwxr-xr-x   2 root root  4096 Nov 22 12:37 boot
drwxr-xr-x   5 root root   340 Jan 30 03:50 dev
drwxr-xr-x   1 root root  4096 Jan 30 03:50 etc
drwxr-xr-x   2 root root  4096 Nov 22 12:37 home
drwxr-xr-x   1 root root  4096 Jan 16 20:16 lib
drwxr-xr-x   2 root root  4096 Dec  9 23:22 lib64
drwxr-xr-x   2 root root  4096 Oct  9 15:21 libexec
drwxr-xr-x   2 root root  4096 Dec  9 23:22 media
drwxr-xr-x   2 root root  4096 Dec  9 23:22 mnt
drwxr-xr-x   1 root root  4096 Jan 16 20:16 opt
-rw-r--r--   1 root root  1559 Jan 30 03:50 pi-hole-teleporter_2021-01-30_03-50-40.tar.gz
dr-xr-xr-x 221 root root     0 Jan 30 03:50 proc
drwx------   1 root root  4096 Jan 16 20:16 root
drwxr-xr-x   1 root root  4096 Jan 30 03:50 run
-rwxr-xr-x   1 root root   389 Oct 20 12:52 s6-init
drwxr-xr-x   1 root root  4096 Jan 16 20:16 sbin
drwxr-xr-x   2 root root  4096 Dec  9 23:22 srv
-rwxr-xr-x   1 root root  6099 Jan 16 20:14 start.sh
dr-xr-xr-x  11 root root     0 Jan 30 03:50 sys
drwxrwxrwt   1 root root  4096 Jan 30 03:51 tmp
drwxr-xr-x   1 root root  4096 Jan 16 20:14 usr
drwxr-xr-x   1 root root  4096 Jan 16 20:16 var
```

**Comment by stepanovdg** [comment]
@dschaper  Thank you. 
It was stupid of me not to check. I just check console output for -a in order to be sure for parameters if possible (like path) and forgot to try to run.

**Comment by stepanovdg** [comment]
@dschaper  By the way is it possible to apply config with the same api? Maybe like 
docker exec -it pihole /bin/bash pihole -a -t filename.tar.gz

**Comment by dschaper** [comment]
Not currently, no.
