### ISSUE TITLE
Docker manifest for the arm64 architecture is wrong

### ISSUE THREAD

**Issue by Sergong** [pi-hole/docker-pi-hole#780]
### Versions

- Pi-hole:  latest
- AdminLTE:  latest
- FTL:  latest

### Platform

- OS and version: Ubuntu 20.10  

- Platform:  Raspberry Pi, Docker
- Docker version: 

### Expected behavior
when doing `docker pull pihole/pihole:latest` I expect the latest pihole docker container to be pulled for my correct platform (Raspberry PI v4 with Ubuntu 20.10 and docker

### Actual behavior / bug
manifest contains following (snippet of relevant output):
`            "Labels": {
                "image": "pihole/pihole:v5.2.4_arm64",
                "maintainer": "adam@diginc.us",
                "url": "https://www.github.com/pi-hole/docker-pi-hole"
            },
            "Shell": [
                "/bin/bash",
                "-c"
            ]
        },
        "Architecture": "amd64",
`
As you can see the Architecture incorrectly states its amd64

### Steps to reproduce

1. Run sudo docker pull pihole/pihole:latest
2. Run docker inspect b537a7cd0edf
3. See that Architecture is incorrect
4. Cannot run the container

## Debug Token

- URL:  N/A

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/docker-pi-hole/issues/735
