### ISSUE TITLE
pihole container restarts every 3 or 4 minutes - dnsmasq receives a SIGTERM

### ISSUE THREAD

**Issue by SillaRizzoli** [pi-hole/docker-pi-hole#783]
### Versions
- Pi-hole:  5.2.4
- AdminLTE:  5.3.2
- FTL:  5.6

### Platform
- OS and version:  Raspbian Buster 10 32bit
- Platform:  Raspberry Pi 4 8 GB

### Expected behavior

I expect pihole to run normally.

### Actual behavior / bug

pihole container restarts every 3 or 4 minutes. The last message on pihole.log before restart is:
dnsmasq[325]: exiting on receipt of SIGTERM

### Steps to reproduce

Install pihole via
docker pull pihole/pihole:latest
Run using the docker-compose script

## Debug Token

pihole debug can't upload the debug log so  I don't have a debug token

### Screenshots

No screenshot

### Additional context

Raspbian is fully updated.
Docker version is 20.10.3

**Comment by HenningRath** [comment]
I had the exact same behaviour yesterday after updating kernel + docker + pihole container to your versions and it turns out it was caused by my system having itself configured as nameserver.

I added "dns-nameservers 1.1.1.1 8.8.8.8 8.8.4.4" to my network configuration file /etc/network/interfaces.d/eth0 and the container came up without any problems

**Comment by SillaRizzoli** [comment]
Well, what do you know, I changed the name server of the host and now everything works.
However, I think I'd prefer to use pihole as the nameserver for the raspberry, too.
I don't see any reason why it shouldn't be possible. Any ideas of what is causing the problem?

**Comment by SillaRizzoli** [comment]
For those who, like me, are using dhcp for address assignment, you have to modify /etc/dhcpcd.conf and insert a line like:

static domain_name_servers=8.8.8.8 8.8.4.4

to force the use of specific dns server with dhcp.

**Comment by xBelladonna** [comment]
I just want to add that I've also experienced this issue, along with a warning that the image pulled is for amd64 despite requesting armv7. It appears this is not true as the binaries execute on an arm system and is some kind of regression in Docker and/or associated build systems and is unrelated. As suggested, changing the system nameserver to my router's DNS fixed the issue.

**Comment by velosol** [comment]
I was seeing the same (while `attach`ed it showed a timeout causing the SIGTERM and then a restart of the container) and changed the README.md file to include the following under the `pihole:` entry:
```
dns:
  - 127.0.0.1
  - <whatever other dns server you want>
```

Killing the container (docker stop or Ctrl-C while attached) and then `docker-compose up --detach` and I could again reach the web UI and am not seeing constant restarts anymore.  I also removed the 443:443 port assignment as discussed in several other issues.
