### ISSUE TITLE
Mac M1 Docker setup: pi-hole conflict with port 53

### ISSUE THREAD

**Issue by verity-s** [pi-hole/docker-pi-hole#791]
### Versions
I just installed the Docker M1 tech preview 7 and Pi-hole v5.2.4 (results in in pihole start "WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested") 

### Platform
MacBook Air M1
macOS big sur 11.2.1
Docker M1 tech preview 7 (engine 20.10.0) 
Pi-hole v5.2.4

### Expected behavior

Commands:
```
% docker pull pihole/pihole
% docker run -d --name pihole -e ServerIP=xx.xx.xx.xx -e TZ=America/New_York -e WEBPASSWORD=xxxxxxxx -e DNS1=1.1.1.1 -e DNS2=1.0.0.1 -p 80:80 -p 53:53/tcp -p 53:53/udp -p 443:443 -v ~/pihole/:/etc/pihole/ --dns=127.0.0.1 --dns=8.8.8.8 --cap-add=NET_ADMIN --restart=unless-stopped pihole/pihole:latest
```

### Actual behavior / bug

Error in using port 53:
```
WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
703334bfa82cfa5e9aebd5f484764b8613bde1c01170d23a73d2ad1dfc69ac12
docker: Error response from daemon: Ports are not available: listen udp 0.0.0.0:53: bind: address already in use.
```
From searching I understand port 53 is already in use by mac OS mdnResponder.

### Question

How should I start pi-hole replacing port 53 with some other value to avoid conflict with mdnResponder?

Thank you!

**Comment by dschaper** [comment]
You can't have Pi-hole on a port other than 53. (Unless you have some way of telling the clients to use another port for DNS.)

You'll have to do the opposite, fix mdnResponder.

**Comment by verity-s** [comment]
Thanks! I did some more searching and it looks like a docker issue. As soon as I start docker, mDNSresponder starts listening on port 53. Quit docker and the line below goes away. No idea how to fix that.

```
% sudo lsof -nP -i4TCP:53
COMMAND   PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
mDNSRespo 456 _mdnsresponder   80u  IPv4 0x44f11e400a37bbab      0t0  TCP *:53 (LISTEN)
```

**Comment by initconf** [comment]
any idea how to fix mdnsResponder ? 

I tried : 

% sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
/System/Library/LaunchDaemons/com.apple.mDNSResponder.plist: Operation not permitted while System Integrity Protection is engaged

**Comment by semsuddin** [comment]
> Thanks! I did some more searching and it looks like a docker issue. As soon as I start docker, mDNSresponder starts listening on port 53. Quit docker and the line below goes away. No idea how to fix that.
> 
> ```
> % sudo lsof -nP -i4TCP:53
> COMMAND   PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
> mDNSRespo 456 _mdnsresponder   80u  IPv4 0x44f11e400a37bbab      0t0  TCP *:53 (LISTEN)
> ```

Same here. Still looking for a solution.

**Comment by PromoFaux** [comment]
Likely this is something that needs to be solved on the  `docker` end, rather than with this container

https://github.com/docker/for-mac/issues/5335

**Comment by dimohamdy** [comment]
This solution works well with me, kill all processes that use port **53** in the terminal like this

```
sudo lsof -t -i :53 | xargs sudo kill -9

docker run -d 
    --name pihole 
    -p 53:53/tcp -p 53:53/udp 
    -p 80:80 
    -p 443:443 
    -e TZ="Europe/Amsterdam" 
    -v "$(pwd)/etc-pihole/:/etc/pihole/" 
    -v "$(pwd)/etc-dnsmasq.d/:/etc/dnsmasq.d/" 
    --restart=unless-stopped 
    pihole/pihole:latest
```

**Comment by NullVoxPopuli** [comment]
This _doesn't_ work for me:
```
sudo lsof -t -i :53 | xargs sudo kill -9
docker compose --file ./pi.hole.yml up --detach 
```

I still get
```
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:53 -> 127.0.0.1:0: listen tcp 0.0.0.0:53: bind: address already in use
```

**Comment by rdwebdesign** [comment]
Maybe the service is restarting right after you kill it.
Did you check if there is still something using port `53` after your `lsof` command?

Usually the best way to do it is stopping and disabling the service.

**Comment by NullVoxPopuli** [comment]
yeah, the mdns thing always starts up again very quickly.
