### ISSUE TITLE
pi-hole only listens to tcp6/udp6 (ipv6)

### ISSUE THREAD

**Issue by misterwrong** [pi-hole/docker-pi-hole#799]
### Versions

- Pi-hole:  v5.2.4 
- AdminLTE:  v5.4
- FTL:  v5.7

### Platform
- OS and version:  Debian Buster
- Platform:  Docker

### Expected behavior

Expected pi-hole to listen on tcp/udp (ipv4)

### Actual behavior / bug

pi-hole only listens to tcp6/udp6 (ipv6)

### Steps to reproduce

(sensitive data replaced with "secret")
```
# docker pull pihole/pihole:v5.7
# docker run -d --name pihole --restart=always -p 7080:80 -p 53:53/tcp -p 53:53/udp -e TZ=secret/secret -e WEBPASSWORD=secret -e ServerIP=192.168.1.100 -e IPv6=False -v /secret/pihole/pihole:/etc/pihole -v /secret/pihole/dnsmasq:/etc/dnsmasq.d pihole/pihole:v5.7

# netstat -tulpen | grep :53
tcp6       0      0 :::53                   :::*                    LISTEN      0          15927816   3804/docker-proxy   
udp        0      0 0.0.0.0:53289           0.0.0.0:*                           0          30391      685/rpc.mountd      
udp6       0      0 :::53                   :::*                                0          15927855   3819/docker-proxy
```

## Debug Token

- URL:  https://tricorder.pi-hole.net/etpm95sf7b

### Additional context

* When configuring my router to use 192.168.1.100 for DNS requests, none reach the container and the client receives no DNS.
* I have tried both the tags v5.7 and latest, and the problem occurs with both versions.

**Comment by dschaper** [comment]
The `netstat` shows `docker-proxy` as the process that is on those ports, not `pihole-FTL`. 

Did you run `netstat` inside the container or on the host? You'd need to do it inside the container to see what Pi-hole is listening on, otherwise this looks like an issue with your docker daemon and network, not Pi-hole.

**Comment by misterwrong** [comment]
I ran netstat on the host. If I expose the ports (see runcommand) to the host, I expect the host to listen to them.

**Comment by dschaper** [comment]
Then you'll need to find out why the docker daemon isn't doing that.

**Comment by misterwrong** [comment]
Inside the container the ipv4 ports appear to be exposed. Thank you.
