### ISSUE TITLE
PiHole isn't blocking anything after update to the current version.

### ISSUE THREAD

**Issue by grisu280871** [pi-hole/docker-pi-hole#801]
### Versions

- Pi-hole:  5.2.4
- AdminLTE:   Web Interface v5.4 
- FTL:  5.7

### Platform

- OS and version:  nextcloudpi v1.34.7 Kernel 5.10.11-v7+

- Platform:  Raspberry Pi 3b

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug
After the last update the PiHole isn't blocking anything anymore
_A clear and concise description of what the bug is._

### Steps to reproduce

My steps to update the docker-pi-hole:
1. Stop Pi-Hole-Container: _docker stop pihole_
2. Download latest version: _docker pull pihole/pihole:latest_
3. Delete old Container: _docker rm -f pihole_
4. Start new container: 
docker run -d \
--name pihole \
-p 53:53/tcp \
-p 53:53/udp \
-p 67:67/udp \
-p 88:80 \
-p 8080:443 \
-e PUID=1000 -e PGID=1000 \
-e TZ=Europe/Berlin \
-v /mnt/pihole/pihole/:/etc/pihole/ \
-v /mnt/pihole/dnsmasq.d/:/etc/dnsmasq.d/ \
-e 8.8.8.8 \
-e 1.1.1.1 \
--restart=unless-stopped \
pihole/pihole:latest

## Debug Token

- URL:  https://tricorder.pi-hole.net/oipezd346v

### Screenshots
![PiHole Dash-Board](https://user-images.githubusercontent.com/76910610/108418952-30f18d00-7232-11eb-903c-3642533961bf.png)

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
It doesn't look like you have any clients actually querying the new container.

**Comment by dschaper** [comment]
Side Note: Don't use the `latest` tag. Pin to a version.

**Comment by grisu280871** [comment]
The question is why the clients aren't or aren't able to querying the container.
There was no change to the clients and my Router is still set up to use the pihole as main DNS Server.

**Comment by grisu280871** [comment]
BTW I am getting this Warning when starting the container:

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
5ddf0276edbf30bf25d57910629a534f4d3276c7b619b0aac1c24e777bd337dd

**Comment by PromoFaux** [comment]
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

This should actually be resolved with latest images. Closing out for now, feel free to re-open if you're still having issues
