### ISSUE TITLE
Ubuntu 16.X and 18.X PHP 8.0 update failure

### ISSUE THREAD

**Issue by Guyverix** [pi-hole/docker-pi-hole#804]
Recent update of PiHole attempts to install PHP 8.0.  I installed the PPA and got PHP8 installed however, a dependency appears missing.  the installer says it cannot find php8.0-json. 

 According to PHP, it comes default and is not a separate package:
[https://php.watch/articles/php-8.0-installation-update-guide-debian-ubuntu](url)

This is a: Bug 

## Details
`  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php8.0-common
  [✓] Checking for php8.0-cgi
  [✓] Checking for php8.0-sqlite3
  [i] Checking for php8.0-xml (will be installed)
  [i] Checking for php8.0-json (will be installed)
  [✓] Checking for php8.0-intl
  [i] Processing apt-get install(s) for: php8.0-xml php8.0-json, please wait...
--------------------------------------------------------------------------------
E: Package 'php8.0-json' has no installation candidate
chubbard@infra01:~$ sudo apt search php8.0 | grep json
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
chubbard@infra01:~$ 

`

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 16.X AND 18.X 
  * Hardware: KVM PC 
  * Kernel Architecture: x86/amd64 
  * Docker Install Info and version: NA straight daemon
    - Software source: curl updater 
    - Supplimentary Software: NA 
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce

## These common fixes didn't work for my issue: NA

- [ ] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by dschaper** [comment]
We don't attempt to install `php-8`, we see that you have installed `php-8` (why you did this in a docker container, you'll have to explain) and often the OS version doesn't have packages for `php-8` so things break.

**Comment by Guyverix** [comment]
This is not a docker container, just a straight install via the curl command.  I installed PHP8 becuase the installer was attempting to do so.

**Comment by dschaper** [comment]
This is the Docker repo.

**Comment by Guyverix** [comment]
well I am a doofus.. Sorry about that.  Will recreate in the correct area.
