### ISSUE TITLE
docker-compose.yml.example has invalid touch command suggested

### ISSUE THREAD

**Issue by Soccertanker** [pi-hole/docker-pi-hole#809]
This is a: **Bug**  

## Details

docker-compose.yml.example says to:
`
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
`

1. Is this still necessary? I ran docker-compose up --detach, as suggested in the README.md without issues, without creating ./var-log/pihole.log
2. 'touch ./var-log/pihole.log' is an invalid command as touch can not create directories, and ./var-log does not exist (it's in the .gitignore).

The correct command to create ./var-log/pihole.log is 'mkdir ./var-log && touch ./var-log/pihole.log'

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Clone repository.
2. cd into repo's root directory.
3. Run 'touch ./var-log/pihole.log'

1. Environment data
  * Operating System: **Ubuntu** 
  * Hardware: RasPi 4B
  * Kernel Architecture: ArmV8 64bit
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: none
  * Hardware architecture: 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [ ] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by PromoFaux** [comment]
I don't think this is necessary at all, to be honest - Not an awful lot of sense in mounting that log file out to the host. I've updated the example files
