### ISSUE TITLE
Latest version when enableing DHCP throws a DNSMasq Error

### ISSUE THREAD

**Issue by andersonm66** [pi-hole/docker-pi-hole#814]
When enabling DHCP the latest docker container throws the following error:

DNSMASQ_CONFIG FTL failed to start due to process is missing required capability NET_ADMIN

I cant find any more information. I have removed DNSUtils from the docker host just in case it was conflicting there....

**Comment by andersonm66** [comment]
It appears that running the container in privileged mode corrects this error

**Comment by edgd1er** [comment]
either that or add the capability requested: NET_ADMIN as suggested in the docker-compose.yml or in the docs: https://haugene.github.io/docker-transmission-openvpn/run-container/

```
docker run --cap-add=NET_ADMIN -d \
              -v /your/storage/path/:/data \
              -e OPENVPN_PROVIDER=PIA \
              -e OPENVPN_CONFIG=france \..........
```

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
