### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by vncloudsco** [pi-hole/docker-pi-hole#815]
i use docker version i am having full cpu. How can I handle it.
![image](https://user-images.githubusercontent.com/41409442/111901604-cbc8cb80-8a6b-11eb-9d32-416ab82db5c9.png)

**Comment by PromoFaux** [comment]
Please direct any configuration queries to https://discourse.pi-hole.net

Also you'll probably need to provide a lot more information if you want someone to help :)
