### ISSUE TITLE
DNS service NOT started/DNS is not listening v5.8

### ISSUE THREAD

**Issue by squirtbrnr** [pi-hole/docker-pi-hole#835]
This is a: Run Issue

## Details

I run PiHole on a Synology NAS via docker.  I have been running v5.7 with no issues.  I tried updating to v5.8 and the log stops at the error "`[x] DNS service is NOT started`".  If I add the command `--dns=1.1.1.1` to my docker run command, the container starts but now I get "`[x] DNS service is NOT listening`".
## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://github.com/pi-hole/docker-pi-hole/issues/834

## How to reproduce the issue 

1. Environment data
  * Operating System: Synology DSM 6.2.4-25556 
  * Hardware: Synology 
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: Synology Package Center Docker 18.09.0-0519
    - Supplimentary Software: 
  * Hardware architecture: x86

2. `sudo docker create --name=pihole --restart always -v /etc/localtime:/etc/localtime:ro -v /volume1/docker/pihole/pihole:/etc/pihole -v /volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d -e TZ=America/Chicago -e PUID=1037 -e PGID=100 -e WEB_PORT=8082 -e ServerIP=192.168.1.95 -e WEBPASSWORD=xxxxxxxx -e IPv6=False -e DNSMASQ_LISTENING=all --dns=127.0.0.1 --net=host pihole/pihole:v5.7`
3. add `--dns=1.1.1.1` after the existing dns variable and the container starts, but DNS is now not listening.

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
- v5.7 works just fine with my run command.

Add any other debugging steps you've taken or theories on root cause that may help.
- Adding the other dns variable `--dns=1.1.1.1` allows the DNS service to start, but then I get the DNS not listening similar to the other GitHub issue linked above.
- I have UniFi network equipment which hands out DHCP and my NAS IP as the DNS server.
- My NAS uses LACP/LAG with the network switch and I have manually configured the interface as follows:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/35356217/114810350-85684300-9d71-11eb-96ee-2249a17064a6.png">

**Comment by Animal-UK** [comment]
Hi, i have the same issue, reverting to 5.7 works again

Versions
Pi-hole version is v5.3.1 (Latest: v5.2.4)
AdminLTE version is v5.5 (Latest: v5.4)
FTL version is v5.8 (Latest: v5.7)

Platform
OS and version: QTS 4.3.6 (20210322)
Platform: Docker
Expected behavior
[✓] Logging has been enabled!,
::: Docker start setup complete,
[✓] DNS service is running,

Actual behavior / bug
upon startup i get:
[✓] Logging has been enabled!,
::: Docker start setup complete,
[✗] DNS service is not running,

Steps to reproduce
Steps to reproduce the behavior:

download latest pihole
start with docker
Debug Token
URL: N/A
Additional context
[_pihole_logs.txt](https://github.com/pi-hole/docker-pi-hole/files/6316711/_pihole_logs.txt)

**Comment by dennisfabri** [comment]
Same issue with an Intel NUC and Ubuntu 20.10 on v5.8, while reverting back to v5.7 works.

**Comment by PromoFaux** [comment]
All, just a hunch.. what is the output of `docker --version` on your affected machines?

**Comment by PromoFaux** [comment]
Closing as duplicate

https://github.com/pi-hole/docker-pi-hole/issues/834
