### ISSUE TITLE
Change default web port

### ISSUE THREAD

**Issue by buurman** [pi-hole/docker-pi-hole#85]
Could you change the default port to something else? Port 80 is a pain on my server, at the moment I just mount a custom lighttpd.conf (changed 80 to 8088) to /etc/lighttpd/lighttpd.conf and it works like a charm.

The reverse proxy solution isn't always easy and this is a quick solution, you could just load an editted conf file with the dockerfile.

**Comment by diginc** [comment]
have you tried changing the port with docker's NAT?  e.g.  `docker run -p 8088:80` ?

I was under the impression this style of ad blocking required pi-hole be the default server in charge of port 80, this way when hitting a random ad domain over http (port 80) it gets the empty ad blocked page.

**Comment by buurman** [comment]
I did, but that's only useful when using a bridged network connection, and when doing it like so it doesn't pickup de client ip's and it sees all the requests as coming from the docker container IP. Setting the serverip doesn't help.

Maybe it's because i'm running it on a Synology NAS? Either way, mounting a different conf is working great. Didn't encounter any issues so far.

**Comment by diginc** [comment]
so you're running --net host or another non bridged (NAT) style?  Could you post your entire docker run command so I could play around with running in that style?

I assume synology also runs it's web interface on port 80 so you're getting around that.

**Comment by buurman** [comment]
I don't know the command, it's nice gui from Synology itself, but yes it's --net. The only reason I get around port 80 is that I adjusted the port in the lighttpd.conf file of the docker container to 8088.

**Comment by diginc** [comment]
I'll see about adding the customization of port option after #84 is finished.

**Comment by buurman** [comment]
Nice, thanks for the effort!

**Comment by diginc** [comment]
Related: https://github.com/diginc/docker-pi-hole/issues/88.

I think the recommendation I made in #88 to make pi-hole your top most apache VHOST should work for you too.

**Comment by buurman** [comment]
I tried it before and it wasn't helping.. I rather not want to manually chance configs on the NAS.

**Comment by tonyklawrence** [comment]
I've been looking into this as I also run pi-hole in docker on my DS916+.  I've posted an article on how I solved the issue.  I know you don't want to manually change configs, but unless Synology add support for this there is no other option available.

http://tonylawrence.com/post/unix/synology/freeing-port-80/

**Comment by buurman** [comment]
When using your NAS also as a webserver this is not a great solution so I will stick to my current solution/workaround which is loading/mounting a custom lighttpd.conf file. This is still working flawless as far as I can judge.

**Comment by tonyklawrence** [comment]
Buurman, would you mind explaining your full solution?  I'm not sure how you can get pi-hole to dns your docker container if it's not running on port 80?

**Comment by buurman** [comment]
I can give it a try this evening. Could you explain to me what shouldn't be working according to you?

**Comment by tonyklawrence** [comment]
When pi-hole decides it need to block an advert, the DNS server will return your configured server ip - in this case the IP address of the Synology.  This means that when the webpage attempts to download the advert instead of asking the ad-server it asks the Synology which *should* return a blank page.

However, because DSM is listening on port 80, instead of returning a black page it returns the Synology 404 page as the requested advert does not exist.  This is especially problematic if you have Synology redirect HTTP to HTTPS as this then creates certificate warnings.

I've not tried running a web server on the Synology so I don't know what this involves but it *might* mean that instead of attempting to load the advert from the DSM it is instead requesting from your own website that is running on port 80 and returning your websites 404 page?

**Comment by buurman** [comment]
Aha I understand.. my 'solution' is a solution for the Admin page and not for the 'block page'.

I performed a small test by trying to go to 'googleadservices.com' and instead I ended at my NAS root webpage.. which for my use is fine because it's a blank page that says 'Nope..' :-) None of my websites are in the rootfolder so the result is simular as the pi-hole block page.

**Comment by tonyklawrence** [comment]
So an alternative could be to run your own website on the Synology with a blank root page?  Is this something that is easy through the UI?

**Comment by buurman** [comment]
I guess most people playing with Synology/Docker/Pi-Hole should be able to do this. But it depends how they manage their websites.

But essentialy it can be done in three steps:
Step 1) Install 'Webstation' if not already installed
Step 2) Create file index.html in the /volume#/web folder.
Step 3) Open index.html with a texteditor en paste something like:
`<HTML>
	<HEAD>
		<title>Website Blocked</title>
	</HEAD>
	<BODY>
		Nope.. blocked!
	</BODY>
</HTML>`

Done..

**Comment by tonyklawrence** [comment]
Yes, that's what I'm playing with atm.  Only just installed webstation.
I'm guessing the default is to look in /web and if you update that like you said then you don't need to add any virtual hosts.  I'm going to have a play.

Last thing, instead of modifying the lighttpd.conf to allow access to admin, would it not be possible to add a name based reverse proxy that would forward all traffic to pihole.myhost.com -> pi-hole.docker ??

**Comment by buurman** [comment]
It would be possible, DSM6 can do this (Application Portal / Reverse proxy). 
But you have to make sure pihole.myhost.com gets rewritten to /admin inside the docker container.

**Comment by tonyklawrence** [comment]
Thanks for your help, I think setting up a blank root website is a good alternative to modifying the templates (who knows what this might break in future releases).

I've decided to reverse proxy my pihole docker and just bookmark the host with /admin, this seems to work ok.

**Comment by dschaper** [comment]
We really don't try to break existing installations too often, it just looks a lot like that. :)

**Comment by tonyklawrence** [comment]
I was talking more about breaking future Synology DSM releases (it's those templates i edited) rather than pi-hole itself.

**Comment by dschaper** [comment]
Eventually one of us Pi-hole developers will have to break down and pick up a Synology device so we can be of more assistance and help diginc out a little more with Docker on Synology.

**Comment by buurman** [comment]
If you or diginc need volunteers for testing.. count me in.

**Comment by tonyklawrence** [comment]
An alternative to buying a Synology is running Xpenology (can run inside VMWare I believe).
I've no experience with this but could be an option initially?

**Comment by dschaper** [comment]
Thanks, I'll take a look at that.

**Comment by buurman** [comment]
I've got a Synology DS412+ as well as a Xpenology server (on a HP Gen8 Microserver).. both work great but be aware that a Xpenology server depends on community updates.

**Comment by MattPark** [comment]
@buurman Did you get the DHCP part working in Synology Docker, btw?

**Comment by buurman** [comment]
Nope, don't need it so I didn't test it

**Comment by diginc** [comment]
Checkout the latest `alpine_dev` and `debian_dev` tags for this new features.  I'll merge to the production tags ASAP.

**Comment by tonyklawrence** [comment]
I can confirm that the alpine_dev tag works for me on my synology running using host networking.  I can change the http port so there is no clash.
The other thing I needed to do was to specify DNSMASQ_LISTENING=all as en0 does not exist in this case.

**Comment by tERB00** [comment]
Docker WEB_PORT variable does not work for some reason... It still listens for 80 port. Anybody know why?

**Comment by Tatsh** [comment]
I changed this in the Debian image by modifying the lighttpd.conf file and forcing it to be readonly in the volume mount:

```sh
docker ... -v ~/dev/pihole/lighttpd.conf:/etc/lighttpd/lighttpd.conf:ro ...`
```

The file has this line:

```ini
server.port              = 37337
```

Then in nginx locally running on this machine I have this configuration file loaded:

```nginx
upstream pihole {
    server 192.168.1.254:37337;
}

server {
    listen 80;
    server_name "~^.*$";
    access_log off;

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_pass http://pihole;
    }
}
```

Yes, it works. I would like to not have to override `lighttpd.conf`.

**Comment by keithah** [comment]
I was following @tonyklawrence's instructions and can confirm WEB_PORT is no longer respected as well. 'latest' nor 'debian_dev' works, I did have it working with 'debian' however.

**Comment by PromoFaux** [comment]
the `WEB_PORT` variable appears to be working fine in the latest image. Feel free to reopen if this is still an issue for you

![image](https://user-images.githubusercontent.com/1998970/149011291-6e667cb5-6375-4a9c-af3d-7e0b9d067105.png)
