### ISSUE TITLE
Dashboard showing -2 domains on blocklist

### ISSUE THREAD

**Issue by xhanrot** [pi-hole/docker-pi-hole#859]
This is a: **Run Issue**  

## Details

In Dashboard, Pihole shows a negative value for domains on blocklist (-2)
## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://discourse.pi-hole.net/t/domains-on-blocklist-gives-2-on-qnap-docker/29956

## How to reproduce the issue 

1. Environment data
  * Operating System: **Synology DSM** 
  * Hardware:  Synology 
  * Kernel Architecture:  x86/amd64 
  * Docker Install Info and version: 
    - Software source: OS provided package 
    - Supplimentary Software: Synology, portainer
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
![image](https://user-images.githubusercontent.com/10545334/119963786-c9717900-bfa8-11eb-8266-a8db32b0bad7.png)

![image](https://user-images.githubusercontent.com/10545334/119963908-ead26500-bfa8-11eb-8899-f4f87cb6d22f.png)

3. any additional info to help reproduce

Just install Docker and run admin UI

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by dschaper** [comment]
I think this is something you'd be better off asking at a Synology support forum. Or asking the source of the guide that you followed to set up the images.

**Comment by hardwareadictos** [comment]
Same issue here using docker on raspberry pi 4, reported it also here: https://github.com/pi-hole/docker-pi-hole/issues/860

**Comment by TheUntouchable** [comment]
Same here with an raspberrypi 3..

**Comment by hardwareadictos** [comment]
Still having the same issue, even trying to run the container with root...

**Comment by mike-lloyd03** [comment]
Also having this same problem running on an RPI4 with archlinux.

**Comment by PromoFaux** [comment]
Closing as related to #860 - the -2 domains should be fixed in core at some point in the near future
