### ISSUE TITLE
imported blacklist via Teleporter don't work, Pi-hole do not block the dns request.

### ISSUE THREAD

**Issue by linzack** [pi-hole/docker-pi-hole#900]
### Versions

source Raspberry Pi:
- Pi-hole:   v5.1.1
- AdminLTE:  v5.1
- FTL:  v5.1

target Synology Docker:
- Pi-hole:   v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform

- OS and version:  

- Platform:  Synology Docker

### Expected behavior
the data is imported to synology docker Pi-hole via Teleporter, original source is Pi-hole on Raspberry Pi.
I can check the blacklist exist on synology docker by command:
```
$ sudo docker exec -it {container_id} pihole -q test.uno
 Match found in regex blacklist
   \.uno$
```
so ideally the domain "test.uno" should be blocked.

### Actual behavior / bug
But if I query the domain on another device to ask the Pi-hole docker by:
```
nslookup test.uno
server:  pihole
Address:  192.168.x.x

*** pihole can't find test.uno: Non-existent domain
```
the dns request is actually forwarded to dns.google#53, and not blocked by Pi-hole.

### Steps to reproduce

1. on raspberry pi, Pi-hole, go settings -> Teleporter -> backup -> get tar.gz file
2. on synology docker, Pi-hole, go settings -> Teleporter -> restore -> choose the tar.gz file to restore
3. test if the blacklist imported from raspberry pi really work.
4. I tried deleted the blacklist entry doesn't work and add it back again, it worked! New blacklisted dns query is blocked.
5. I tried settings -> restart dns resolver -> don't work
6. I tried restart synology docker Pi-hole container -> don't work

## Debug Token

- URL:  https://tricorder.pi-hole.net/Q172gNQt/

**Comment by dschaper** [comment]
Your configuration doesn't seem to be correct either. Did you follow a guide or documentation to set up on Docker on Synology?

```plain
*** [ DIAGNOSING ]: Setup variables
    TEMPERATUREUNIT=C
    ADMIN_EMAIL=
    WEBUIBOXEDLAYOUT=traditional
    BLOCKING_ENABLED=true
    PIHOLE_DNS_2=8.8.4.4
    LIGHTTPD_ENABLED=
    IPV6_ADDRESS=
    DNS_BOGUS_PRIV=
    DNS_FQDN_REQUIRED=
    DNSSEC=
    REV_SERVER=
    REV_SERVER_DOMAIN=
    REV_SERVER_TARGET=
    REV_SERVER_CIDR=
    CONDITIONAL_FORWARDING=
    CONDITIONAL_FORWARDING_IP=
    CONDITIONAL_FORWARDING_DOMAIN=
    CONDITIONAL_FORWARDING_REVERSE=
    INSTALL_WEB_SERVER=true
    INSTALL_WEB_INTERFACE=true
    IPV4_ADDRESS=0.0.0.0
    PIHOLE_DNS_1=8.8.8.8
    PIHOLE_INTERFACE=eth0
    QUERY_LOGGING=true
```

**Comment by linzack** [comment]
Hi, 
the blocked results look like:
```
 nslookup arc.msn.com
server:  pihole
Address:  192.168.x.x

名稱:    arc.msn.com
Addresses:  ::
          0.0.0.0
```
it's because the test domain "test.uno" is not a real domain.

Ahhh, sorry, I don't know this repository when I setup my synology docker lol. But it works until I find this issue...

Thank you!

**Comment by dschaper** [comment]
What does the result look like when it's not blocking what you expect it to block?

**Comment by linzack** [comment]
Hi, yes!
if the domain is not blocked but list on the blacklist, the nslookup will show IPs from dns query.

**Comment by linzack** [comment]
Hi, 
I have recreated the Synology Pi-hole docker container by using docker-compose method described in https://github.com/pi-hole/docker-pi-hole/blob/master/README.md
but the new container still do not block the domain if it was imported from Teleporter.

Maybe there is something wrong in my gravity.db?

**Comment by linzack** [comment]
Hi,
when check the gravity.db, in table "vw_blacklist", I find the domain imported from Teleporter have a "NULL" group_id,
and other manually add domain have "integer 0" group_id.
The domain with "NULL" group_id is not blocked when using command nslookup, while the domain with "integer 0" group_id is blocked without issue.

It seems like the Teleporter do not assign group_id "0" when importing domains, include tables like "vw_blacklist" or "vw_regex_blacklist"... and maybe this behavior cause the domain will not be blocked.

**Comment by dschaper** [comment]
Thanks for the update. @PromoFaux does this sound like something in docker or something with the import?

**Comment by PromoFaux** [comment]
AFAIK the docker image does not make any modifications to any of the core teleport functions

**Comment by linzack** [comment]
Hi,
in the Pi-hole admin page > Group management > Domains,
I find a lot domains have "Group assignment" column set to "none selected".
For example, a domain "j6hek.voluumtrk3.com" have "Group assignment" column set to "none selected".
![group](https://user-images.githubusercontent.com/8398628/133137280-e7fb3646-76de-499a-a5d1-5c07d297d3a3.png)

```
$ nslookup j6hek.voluumtrk3.com 8.8.8.8
server:  dns.google
Address:  8.8.8.8
response:
name:    j6hek.voluumtrk3.com
Addresses:  35.154.132.87

$ nslookup j6hek.voluumtrk3.com
server:  pihole
Address:  192.168.x.x
response:
name:    j6hek.voluumtrk3.com
Addresses: 35.154.132.87
```
and if I modify "Group assignment" column to "Default".
```
$ nslookup j6hek.voluumtrk3.com
server:  pihole
Address:  192.168.x.x
response:
name:    j6hek.voluumtrk3.com
Addresses:  ::
          0.0.0.0
```
the request is blocked by Pi-hole.
Maybe there is some relationship between Teleporter and "Group assignment" column?

By the way, is there a way to batch modify thousands of domains "Group assignment" column to "Default" ?
Thank you!

**Comment by PromoFaux** [comment]
@linzack before I dig into this one, is this still an issue in the latest version?
