### ISSUE TITLE
Latest docker image using 5.2.4 and not 5.3.1

### ISSUE THREAD

**Issue by fractalf** [pi-hole/docker-pi-hole#911]
Is there a reason the docker image is not updated?

```sh
root@c0d1bb333b1f:/# pihole -v
  Pi-hole version is v5.2.4 (Latest: v5.3.1)
  AdminLTE version is v5.5.1 (Latest: v5.5.1)
  FTL version is v5.8.1 (Latest: v5.8.1)
```

I was hoping to get a fix for the bug where Groups doesn't show in the blacklists..

![image](https://user-images.githubusercontent.com/5707457/131232393-c16e9a73-5782-4817-8226-4240a7b32d13.png)

Cheers

**Comment by dschaper** [comment]
It would help to know what tag you are using.

**Comment by dschaper** [comment]
```plain
 docker container run -it --rm --entrypoint /bin/bash pihole/pihole:latest pihole -v
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5.1 (Latest: v5.5.1)
  FTL version is v5.8.1 (Latest: v5.8.1)
```

**Comment by fractalf** [comment]
Thank you for you quick response. Yes, sorry for not providing enough info here. Dug in now and this is strange..

I'm using docker-compose

```yml
version: "3"

services:
    pihole:
        container_name: pihole
        image: pihole/pihole:v5.8.1-buster
        restart: always
       ...
```

```sh
-> % docker images|grep pihole       
pihole/pihole                            latest          b78927657a42   3 weeks ago    338MB
pihole/pihole                            v5.8.1-buster   b78927657a42   3 weeks ago    338MB

-> % docker pull pihole/pihole:v5.8.1-buster
v5.8.1-buster: Pulling from pihole/pihole
Digest: sha256:b51628bfa49b71ce4af4831b34e276693a6d647b82037151d8eb0d34da504432
Status: Image is up to date for pihole/pihole:v5.8.1-buster
docker.io/pihole/pihole:v5.8.1-buster

-> % docker-compose up -d
Pulling pihole (pihole/pihole:v5.8.1-buster)...
v5.8.1-buster: Pulling from pihole/pihole
Digest: sha256:b51628bfa49b71ce4af4831b34e276693a6d647b82037151d8eb0d34da504432
Status: Downloaded newer image for pihole/pihole:v5.8.1-buster
Creating pihole ... done

-> % docker exec -it pihole /bin/bash
root@c3032ec5d5a2:/# pihole -v
  Pi-hole version is v5.2.4 (Latest: v5.3.1)
  AdminLTE version is v5.5.1 (Latest: v5.5.1)
  FTL version is v5.8.1 (Latest: v5.8.1)

```

The strange thing here is that the hash i get when pulling these images doesn't match those on the docker hub web page. I'm no noob when it comes to docker, but I feel like I'm missing something here..

https://hub.docker.com/layers/pihole/pihole/latest/images/sha256-31f2653d2a5fd56f14165fc9e51ba22338af99ac04eeaa2dea574810a76c0a01

![image](https://user-images.githubusercontent.com/5707457/131387348-18543570-f276-46ad-9e2a-6edc6f93b31c.png)

https://hub.docker.com/layers/pihole/pihole/v5.8.1-buster/images/sha256-31f2653d2a5fd56f14165fc9e51ba22338af99ac04eeaa2dea574810a76c0a01

![image](https://user-images.githubusercontent.com/5707457/131387495-ccf67c60-c32a-4a73-be83-f82d111b9118.png)

**Comment by dschaper** [comment]
Seems that there is something amiss on the host system. 

You ran `docker pull pihole/pihole:v5.8.1-buster` and saw `Status: Image is up to date for pihole/pihole:v5.8.1-buster` but then a `docker-compose up -d` resulted in `Status: Downloaded newer image for pihole/pihole:v5.8.1-buster` which shouldn't have happened if the `docker pull` was already up to date.

As an aside, you don't need to use `v5.8.1-buster` , `v5.8.1` tag is enough.

**Comment by dschaper** [comment]
What does:
```plain
docker container run -it --rm --entrypoint /bin/bash pihole/pihole:v5.8.1 pihole -v
```
Return as a result for you?

**Comment by fractalf** [comment]
Well, now I **am** confused

```sh
-> % docker container run -it --rm --entrypoint /bin/bash pihole/pihole:latest pihole -v

Unable to find image 'pihole/pihole:latest' locally
latest: Pulling from pihole/pihole
Digest: sha256:b51628bfa49b71ce4af4831b34e276693a6d647b82037151d8eb0d34da504432
Status: Downloaded newer image for pihole/pihole:latest
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5.1 (Latest: v5.5.1)
  FTL version is v5.8.1 (Latest: v5.8.1)
```

I guess my docker knowledge comes short here, somethings fishy when I run this with `docker-compose`, hmm..

**Comment by dschaper** [comment]
Try `docker-compose down` and then `docker-compose up -d` to make sure the old container is removed.

**Comment by fractalf** [comment]
Yes, that's what I did earlier when I wanted to upgrade pi-hole

```sh
-> % docker-compose down
Network proxy is external, skipping

-> % docker ps -a       
CONTAINER ID   IMAGE                                        COMMAND                  CREATED        STATUS       PORTS                                          NAMES
84018e641983   nginx:stable-alpine                          "/docker-entrypoint.…"   5 months ago   Up 5 weeks   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp       proxy-web
4525d0ffaac2   jrcs/letsencrypt-nginx-proxy-companion:2.0   "/bin/bash /app/entr…"   5 months ago   Up 5 weeks                                                  letsencrypt-companion
2af0b1dfa663   jwilder/docker-gen:latest                    "/usr/local/bin/dock…"   5 months ago   Up 5 weeks                                                  docker-gen
143fb3d6dc16   gitea/gitea:1.13.4                           "/usr/bin/entrypoint…"   5 months ago   Up 5 weeks   0.0.0.0:xxxx->xxxx/tcp, 0.0.0.0:xxxx->22/tcp   gitea

-> % docker-compose up -d
Creating pihole ... done

-> % docker exec -it pihole /bin/bash
root@e9a4915aac6b:/# pihole -v
  Pi-hole version is v5.2.4 (Latest: v5.3.1)
  AdminLTE version is v5.5.1 (Latest: v5.5.1)
  FTL version is v5.8.1 (Latest: v5.8.1)
```

**Comment by dschaper** [comment]
That's very odd. The hash for the image that is giving the right answer matches the hash for the container that isn't. 

I'm not sure where to go from here really?

**Comment by fractalf** [comment]
Yes I know, super frustrating :/ Anyway, thanks a lot for your help, at least it looks like it's nothing very very obvious. I'll keep digging..

**Comment by fractalf** [comment]
Ah, found it. I should have pasted the whole `docker-compose.yml` right away, you'd probably see this immediately :)

```yml
version: "3"

services:
    pihole:
        container_name: pihole
        image: pihole/pihole:v5.8.1-buster
        restart: always
        environment:
            ...
        volumes:
            - pihole:/etc
        ports:
            ...
        dns:
            ...
        cap_add:
            - NET_ADMIN

networks:
    default:
        external:
            name: proxy

volumes:
    pihole:
        driver_opts:
            type: none
            o: bind
            device: /mnt/ssd/docker/pihole
```

I don't know why I created  the volume for `/etc` like this, probably did it to have a persistent "backup" of all config files in case of, I dunno, something. It's been a while since I set this up..

Anyway, removing that volume fixed it!

**Comment by fractalf** [comment]
Unfortunately it didn't fix the issue I had, which was my reason for updating. Doh! Maybe the fix isn't merged yet.

**Comment by dschaper** [comment]
You can try the `v5.9-beta` tag and see if that has what you are looking for?

**Comment by fractalf** [comment]
I just noticed that the thing i thought missing was present in another view

Blacklist:

![image](https://user-images.githubusercontent.com/5707457/131508447-3b2a1cf7-b05f-4fd5-a31c-b29ff40b1cd0.png)

Group Management > Domains:

![image](https://user-images.githubusercontent.com/5707457/131508529-599ebfd5-7cde-43fc-821d-38f7592348af.png)


I would expect these to be the same, but obviously they're not. I'm not sure if this is intended or a bug, but it's certainly out of scope regarding this issue. ..just to fill in the gaps.

Thanks a lot for your help m8! :)

**Comment by PromoFaux** [comment]
> I'm not sure if this is intended or a bug,

Intended. The blacklist and whitelist individual pages are probably best looked at as the basic version (i.e for those that have no interest in creating/managing groups).
