### ISSUE TITLE
 Failed to unlock SHM lock: Operation not permitted (solution)

### ISSUE THREAD

**Issue by FrankIJskes** [pi-hole/docker-pi-hole#914]
This is a: Omission in the docker-compose.yml

## Details

When running pihole in a docker-container on an Ubuntu 20lts intel server, i had regular timeouts and found ' Failed to unlock SHM lock: Operation not permitted' in the logs, also the message 'FATAL: Trying to access query ID -1, but maximum is 32768' was seen just above this line and with the same time stamp. 

I also found the error about missing capabilities in my docker logs, so the following worked out for me as to stop having hangups and erros:

ADD the following sections to the docker-compose.yml
  cap_add:
    - NET_ADMIN
    - CAP_SYS_NICE
    - CAP_CHOWN
    - CAP_IPC_LOCK

The CAP_SYS_NICE is needed so the process can change priority.
The CAP_IPC_LOCK is needed to elminate the shm error message.
(Not sure about the need for CAP_CHOWN, but I finally have a working system, so not tweaking this aymore)

## Related Issues
- [x ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

Non found that were a match for my issue.

## How to reproduce the issue 

1. Environment data
  * Operating System: **Ubuntu** 
  * Hardware: Intel NUC
  * Kernel Architecture: x86
  * Docker Install Info and version: 
    - Software source: docker hub
    - Supplimentary Software: 
  * Hardware architecture: x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
My full docker-compose:
# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

pihole:
  container_name: pihole
  hostname: pihole
  image: pihole/pihole:latest
  # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
  #ports:
  #    - "53:53/tcp"
  #    - "53:53/udp"
  #      #      - "127.0.0.1:53:53/tcp"
  #      #- "127.0.0.1:53:53/udp"
  #    - "67:67/udp"
  #    - "80:80/tcp"
  #    - "443:443/tcp"
  environment:
      PUID: 3333
      PGID: 3333
      TZ: 'Europe/Amsterdam'
      UMASK: 022
      # WEBPASSWORD: 'set a secure password here or it will be random'
      # Volumes store your data between container upgrades
  volumes:
       - './hosts:/etc/hosts'
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
       - './tmp/:/tmp/'
       - './tmp/:/var/lib/php/sessions/'
       - './php-73.ini:/etc/php/7.3/cgi/php.ini'
       - './pihole-log/:/var/log/pihole-log/'
       - './pihole-log/:/var/log/lighttpd/'
    # run `touch ./var-log/pihole.log` first unless you like errors
    # - './var-log/pihole.log:/var/log/pihole.log'
  dns:
      - 127.0.0.1
      - 1.1.1.1
  # Recommended but not required (DHCP needs NET_ADMIN)
  #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
  cap_add:
    - NET_ADMIN
    - CAP_SYS_NICE
    - CAP_CHOWN
    - CAP_IPC_LOCK
  restart: unless-stopped
  mem_limit: 2G
  net: "host"
  log_opt:
    max-file: "10"
    max-size: "100000"

3. any additional info to help reproduce

## These common fixes didn't work for my issue

The problem persisted a longer time and i regularly updated my docker to the latest (and used docker-compose down -v && docker-compse up -d to update to the latest version), but only recently I had issues in performance and starting debugging.

- [x ] I have tried removing/destroying my container, and re-creating a new container
- [x ] I have tried fresh volume data by always deleting old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by DL6ER** [comment]
You should have seen something like
```
WARNING: Required Linux capability CAP_SYS_NICE not available
```
in your log when the capability was missing.

@PromoFaux Does this need editing some docker documentation?

FTL needs
- CAP_NET_ADMIN
- CAP_NET_RAW
- CAP_NET_BIND_SERVICE
- CAP_SYS_NICE
- CAP_IPC_LOCK
- CAP_CHOWN

**Comment by FrankIJskes** [comment]
Yes, the cap_sys_nice message was indeed present. But is never mentioned in the docs, only in the error logs. 
And only solves 1 issue but not the others. 



On 6 September 2021 21:41:45 CEST, DL6ER ***@***.***> wrote:
>You should have seen something like
>```
>WARNING: Required Linux capability CAP_SYS_NICE not available
>```
>in your log when the capability was missing.
>
***@***.*** Does this need editing some docker documentation?

**Comment by DL6ER** [comment]
I edited https://github.com/pi-hole/docker-pi-hole#note-on-capabilities already.

**Comment by PromoFaux** [comment]
Closing as this is now in the docs
