### ISSUE TITLE
The Web interface should reports just the image tag version

### ISSUE THREAD

**Issue by scara** [pi-hole/docker-pi-hole#920]
This is a: **Feature Request** 

## Details
https://github.com/pi-hole/docker-pi-hole/releases/tag/2021.09 added the `PIHOLE_TAG` environment variable which is actually the image tag i.e `pihole/pihole:2021.09-armhf-buster`.
Since https://github.com/pi-hole/docker-pi-hole/commit/3865e77c6e9edeb48475c7aa34ff3ea16445ce05 and https://github.com/pi-hole/docker-pi-hole/commit/56f49332376c93ee159cd3d8e179901b616d8991 report it into the Web Interface it should be IMHO evaluated with just the actual image tag version i.e. just `2021.09-armhf-buster`.
https://github.com/pi-hole/docker-pi-hole/blob/3865e77c6e9edeb48475c7aa34ff3ea16445ce05/Dockerfile.py#L11 tells about that value:
```
Usage:
  Dockerfile.py [--hub_tag=<tag>] [--arch=<arch> ...] [--debian=<version> ...] [-v] [-t] [--no-build] [--no-cache] [--fail-fast]
Options:
...
    --hub_tag=<tag>      What the Docker Hub Image should be tagged as [default: None]```
...
```
which is actually the image tag required by the Registry.

It would be better to use just the image "version" from that image tag:
``` bash
$ PIHOLE_TAG="pihole/pihole:2021.09-armhf-buster"; echo ${PIHOLE_TAG#*:}
2021.09-armhf-buster
```
i.e. something like:
``` diff
diff --git a/install.sh b/install.sh
index e608807..e0a310b 100644
--- a/install.sh
+++ b/install.sh
@@ -92,8 +92,8 @@ sed -i $'s/)\s*uninstallFunc/) unsupportedFunc/g' /usr/local/bin/pihole
 sed -i $'s/echo_current_diagnostic "Operating system"/echo_current_diagnostic "Operating system"\\\n    log_write "${INFO} Pi-hole Docker Container: ${PIHOLE_TAG:-PIHOLE_TAG is unset}"/g' /opt/pihole/piholeDebug.sh

 # Inject container tag into web interface footer...
-sed -i $"s/<ul class=\"list-unstyled\">/<ul class=\"list-unstyled\">\\n<strong><li>Docker Tag<\/strong> ${PIHOLE_TAG//\//\\/}<\/li>/g" /var/www/html/admin/scripts/pi-hole/php/footer.php
-sed -i $"s/<ul class=\"list-inline\">/<strong>Docker Tag<\/strong> ${PIHOLE_TAG//\//\\/}\\n<ul class=\"list-inline\">/g" /var/www/html/admin/scripts/pi-hole/php/footer.php
+sed -i $"s/<ul class=\"list-unstyled\">/<ul class=\"list-unstyled\">\\n<strong><li>Docker Tag<\/strong> ${PIHOLE_TAG#*:}<\/li>/g" /var/www/html/admin/scripts/pi-hole/php/footer.php
+sed -i $"s/<ul class=\"list-inline\">/<strong>Docker Tag<\/strong> ${PIHOLE_TAG#*:}\\n<ul class=\"list-inline\">/g" /var/www/html/admin/scripts/pi-hole/php/footer.php

 touch /.piholeFirstBoot
```
If the proposal above will sound good, I'll provide a PR.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue
``` bash
$ docker inspect --format '{{ .Config.Env }}'  pihole/pihole:2021.09-armhf-buster
[PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin ARCH=armv7l UBUNTU_SUITE=buster DOCKER_REPO=docker.io/pihole/debian-debootstrap PIHOLE_ARCH=arm PIHOLE_TAG=pihole/pihole:2021.09-armhf-buster S6OVERLAY_RELEASE=https://github.com/just-containers/s6-overlay/releases/download/v2.1.0.2/s6-overlay-arm.tar.gz PIHOLE_INSTALL=/etc/.pihole/automated install/basic-install.sh PHP_ENV_CONFIG=/etc/lighttpd/conf-enabled/15-fastcgi-php.conf PHP_ERROR_LOG=/var/log/lighttpd/error.log IPv6=True S6_LOGGING=0 S6_KEEP_ENV=1 S6_BEHAVIOUR_IF_STAGE2_FAILS=2 ServerIP=0.0.0.0 FTL_CMD=no-daemon DNSMASQ_USER=root VERSION=v5.9]
```

**Comment by PromoFaux** [comment]
Hi there, yeah I guess the `pihole/pihole:` part is superfluous. 

The main point of the variable at the start was for it to go into the debug log output, so that we have an easy way of determining that it had been run on (our) docker image rather than a barebones install. Adding it to the web footer was an afterthought! I think my thought process was that leaving the `owner/repo:` part in could identify if someone had built the container themselves and pushed to their own namespace. But that's probably a rare enough occurrence that we can lose it on the output... Please feel free to PR!

> `VERSION=v5.9]`


Side note, Need to change this part in the `docker inspect` output to read, for example, `VERSION=2021.09` - but that can be a separate PR

**Comment by scara** [comment]
Hi @PromoFaux,
> Please feel free to PR!

Will do.

> Side note, Need to change this part in the `docker inspect` output to read, for example, `VERSION=2021.09` - but that can be a separate PR

Just saw at the time of filing this issue: I'll try to address the "version" issue too, this evening in a separate PR.

HTH,
Matteo

**Comment by PromoFaux** [comment]
> I'll try to address the "version" issue too, this evening in a separate PR.

I might already have this sorted, just brushing up on my python for string manipulation. Unfortunately the parameter expansion you noted above does not work directly inside the Dockerfile

**Comment by PromoFaux** [comment]
Actually.. I might even have killed two birds with one stone here. Watch this space!

**Comment by PromoFaux** [comment]
Sorted it, Will push something soon

On an untagged commit:

![image](https://user-images.githubusercontent.com/1998970/132990022-8e983f7e-5940-4c7a-bc7b-a9d1ba6347f0.png)

On a tagged commit:

![image](https://user-images.githubusercontent.com/1998970/132990137-430399ec-46bf-4b7f-b2b5-58113af78924.png)


In both cases, the version footer omits the `pihole/pihole:` part:

![image](https://user-images.githubusercontent.com/1998970/132990203-fb4542a9-7499-45bc-a4f3-1cce2d3f45b6.png)

![image](https://user-images.githubusercontent.com/1998970/132990248-f517a768-1202-4661-bf18-32c7e1ab22ef.png)

**Comment by scara** [comment]
> Sorted it, Will push something soon

Thanks!
Matteo

**Comment by scara** [comment]
Hi @PromoFaux,
given the availability of the `2021.10` release, this issue can be closed!

HTH,
Matteo

**Comment by PromoFaux** [comment]
Thanks, I'm bad at going through issues and closing them :D
