### ISSUE TITLE
Pihole keeps crashing after upgrade

### ISSUE THREAD

**Issue by UryDanko** [pi-hole/docker-pi-hole#922]
This is a: Run issue  

## Details

After upgrade to a newest version of Pihole I can't start it anymore. 
Pihole log:
```
pihole           | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole           | [s6-init] ensuring user provided files have correct perms...exited 0.
pihole           | [fix-attrs.d] applying ownership & permissions fixes...
pihole           | [fix-attrs.d] 01-resolver-resolv: applying...
pihole           | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole           | [fix-attrs.d] done.
pihole           | [cont-init.d] executing container initialization scripts...
pihole           | [cont-init.d] 20-start.sh: executing...
pihole           |  ::: Starting docker specific checks & setup for docker pihole/pihole
pihole           | Assigning random password: yNlWOoIF
pihole           |
pihole           |   [i] Installing configs from /etc/.pihole...
pihole           |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
pihole           | sed: cannot rename /etc/pihole/sedjiaqIV: Device or resource busy
pihole           | [cont-init.d] 20-start.sh: exited 4.
pihole           | [cont-finish.d] executing container finish scripts...
pihole           | [cont-finish.d] done.
pihole           | [s6-finish] waiting for services.
pihole           | [s6-finish] sending all processes the TERM signal.
pihole           | [s6-finish] sending all processes the KILL signal and exiting.
pihole           | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole           | [s6-init] ensuring user provided files have correct perms...exited 0.
pihole           | [fix-attrs.d] applying ownership & permissions fixes...
pihole           | [fix-attrs.d] 01-resolver-resolv: applying...
pihole           | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole           | [fix-attrs.d] done.
pihole           | [cont-init.d] executing container initialization scripts...
pihole           | [cont-init.d] 20-start.sh: executing...
pihole           |  ::: Starting docker specific checks & setup for docker pihole/pihole
pihole           | Assigning random password: o5lztVC0
pihole           |
pihole           |   [i] Installing configs from /etc/.pihole...
pihole           |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
pihole           | sed: cannot rename /etc/pihole/sednAGmC1: Device or resource busy
pihole           | [cont-init.d] 20-start.sh: exited 4.
pihole           | [cont-finish.d] executing container finish scripts...
pihole           | [cont-finish.d] done.
pihole           | [s6-finish] waiting for services.
pihole           | [s6-finish] sending all processes the TERM signal.
pihole           | [s6-finish] sending all processes the KILL signal and exiting.
pihole           | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole           | [s6-init] ensuring user provided files have correct perms...exited 0.
pihole           | [fix-attrs.d] applying ownership & permissions fixes...
pihole           | [fix-attrs.d] 01-resolver-resolv: applying...
pihole           | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole           | [fix-attrs.d] done.
pihole           | [cont-init.d] executing container initialization scripts...
pihole           | [cont-init.d] 20-start.sh: executing...
pihole           |  ::: Starting docker specific checks & setup for docker pihole/pihole
pihole           | Assigning random password: 6cgD9vR8
pihole           |
pihole           |   [i] Installing configs from /etc/.pihole...
pihole           |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
pihole           | sed: cannot rename /etc/pihole/sed98enT1: Device or resource busy
pihole           | [cont-init.d] 20-start.sh: exited 4.
pihole           | [cont-finish.d] executing container finish scripts...
pihole           | [cont-finish.d] done.
pihole           | [s6-finish] waiting for services.
pihole           | [s6-finish] sending all processes the TERM signal.
pihole           | [s6-finish] sending all processes the KILL signal and exiting.
```

If I rollback to pihole/pihole:v5.8.1 - everything works fine.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Raspbian GNU/Linux 10
  * Hardware: Raspberry PI 4
  * Kernel Architecture: armv7l
  * Docker Install Info and version: 
    - Software source: docker-ce, docker-compose 
    - Supplimentary Software: 
  * Hardware architecture: ARMv7 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi-hole
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      # - 67/udp # Uncomment if you want to use Pi-Hole for DHCP
      - 80/tcp
    #      - 22/tcp
    environment:
      ServerIP: 192.168.88.5
    # WEBPASSWORD: ${WEBPASSWORD}
      DNS1: 192.168.88.6
    volumes:
      - ./work_pihole:/etc/pihole:rw
      - ./config-pihole/hosts:/etc/hosts:ro
      - ./config-pihole/resolv.conf:/etc/resolv.conf:ro
      - ./config-pihole/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro
      - ./config-pihole/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro
    networks:
      home:
        ipv4_address: 192.168.88.5
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    hostname: syn-unbound
    mac_address: d0:ca:ab:cd:ef:02
    ports:
      - 53/tcp
      - 53/udp
    volumes:
      - ./config-unbound:/opt/unbound/etc/unbound:rw
    networks:
      home:
        ipv4_address: 192.168.88.6
    restart: unless-stopped
```
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by Verguldebarman** [comment]
Same here. Downgraded my docker container to pihole/pihole:v5.8.1_arm64 and it works again!

**Comment by dschaper** [comment]
Is that `docker-compose.yml` exactly what you are using? It's not valid but that may be a copy/paste error.

**Comment by UryDanko** [comment]
> Is that `docker-compose.yml` exactly what you are using? It's not valid but that may be a copy/paste error.

no, I didn't past whole docker-compose because there are other, not relevant, services. I pasted only part related to pihole (and unbound, because they worked together).

**Comment by timreuscher** [comment]
Similar results here. Always crashes on my Synology NAS with an x64 cpu. Removed my data from the equation, and it still crashed.

**Comment by rpthms** [comment]
I'm suspecting this is happening because you have mounted `/etc/pihole/pihole-FTL.conf` as read only. The Docker image's start.sh script will try to add the REPLY_ADDR4 variable to `pihole-FTL.conf` because of the ENV statement in the Dockerfile.

https://github.com/pi-hole/docker-pi-hole/blob/9b106e6275cf9095ee8822f498c0cc907419da78/Dockerfile#L48

https://github.com/pi-hole/docker-pi-hole/blob/9b106e6275cf9095ee8822f498c0cc907419da78/start.sh#L79

Try removing the `:ro` at the end of the `./config-pihole/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro` line and see if it makes a difference.

**Comment by timreuscher** [comment]
> I'm suspecting this is happening because you have mounted `/etc/pihole/pihole-FTL.conf` as read only. The Docker image's start.sh script will try to add the REPLY_ADDR4 variable to `pihole-FTL.conf` because of the ENV statement in the Dockerfile.
> 
> https://github.com/pi-hole/docker-pi-hole/blob/9b106e6275cf9095ee8822f498c0cc907419da78/Dockerfile#L48
> 
> https://github.com/pi-hole/docker-pi-hole/blob/9b106e6275cf9095ee8822f498c0cc907419da78/start.sh#L79
> 
> Try removing the `:ro` at the end of the `./config-pihole/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro` line and see if it makes a difference.

I have the /etc/pihole/ path mapped, not as read-only, and still have the issue.

**Comment by rpthms** [comment]
> > I'm suspecting this is happening because you have mounted `/etc/pihole/pihole-FTL.conf` as read only. The Docker image's start.sh script will try to add the REPLY_ADDR4 variable to `pihole-FTL.conf` because of the ENV statement in the Dockerfile.
> > https://github.com/pi-hole/docker-pi-hole/blob/9b106e6275cf9095ee8822f498c0cc907419da78/Dockerfile#L48
> > 
> > https://github.com/pi-hole/docker-pi-hole/blob/9b106e6275cf9095ee8822f498c0cc907419da78/start.sh#L79
> > 
> > Try removing the `:ro` at the end of the `./config-pihole/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro` line and see if it makes a difference.
> 
> I have the /etc/pihole/ path mapped, not as read-only, and still have the issue.

I was referring specifically to the `/etc/pihole/pihole-FTL.conf` file. Check if you have a volume that only bind mounts that one file and check if that volume is read only.

**Comment by PromoFaux** [comment]
> `/etc/pihole/pihole-FTL.conf` as read only

Thanks, Sorry I saw this issue the other day but was busy and then just forgot.... 😬

But yeah, that was going to be my suggestion. Start the container up with no volumes mounted at all. If it works, then there is a read/write permission issue on the volume mounts. FWIW, "works on my machine"

**Comment by timreuscher** [comment]
Ok, well for my part, on the Synology, I started from scratch and am now up and running again. Even used the same data files and it's fine. It's possible some of the default environmental variables got changed between Pihole versions and that's what's causing the issue. Given the Synology method of updating a Docker image (download updated image, reset current image, and start it up again), if those default environmental variables get changed, it's going to screw up every time.

**Comment by PromoFaux** [comment]
> Given the Synology method of updating a Docker image

I've never bumped into any issues updating Pi-hole on my DSM218+, that said - I'm using CLI and `docker-compose` and always `docker-compose pull && docker-compose down && docker-compose up -d`

**Comment by AlexandreRatte** [comment]
This issue can also be seen when ```pihole-FTL.conf``` is volume-mounted as a ConfigMap, which are [intentionally mounted read-only](https://github.com/kubernetes/kubernetes/issues/62099) in Kubernetes:

**ConfigMap definition:**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-ftl.conf
data:
  pihole-FTL.conf: |
    MAXDBDAYS=7
    LOGFILE=/var/log/pihole/pihole-FTL.log
```
**Volume mount:**
```
      volumes:
      - name: ftlconf
        configMap:
          name: pihole-ftl.conf
          items:
            - key: pihole-FTL.conf
              path: pihole-FTL.conf
```

**Comment by UryDanko** [comment]
> I'm suspecting this is happening because you have mounted `/etc/pihole/pihole-FTL.conf` as read only. The Docker image's start.sh script will try to add the REPLY_ADDR4 variable to `pihole-FTL.conf` because of the ENV statement in the Dockerfile.
> 
> https://github.com/pi-hole/docker-pi-hole/blob/9b106e6275cf9095ee8822f498c0cc907419da78/Dockerfile#L48
> 
> https://github.com/pi-hole/docker-pi-hole/blob/9b106e6275cf9095ee8822f498c0cc907419da78/start.sh#L79
> 
> Try removing the `:ro` at the end of the `./config-pihole/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro` line and see if it makes a difference.

SOLVED. I removed RO from pihole-FTL.conf mount and it started to work.
kinda unexpected.

**Comment by UryDanko** [comment]
> > > I'm suspecting this is happening because you have mounted `/etc/pihole/pihole-FTL.conf` as read only. The Docker image's start.sh script will try to add the REPLY_ADDR4 variable to `pihole-FTL.conf` because of the ENV statement in the Dockerfile.
> > > https://github.com/pi-hole/docker-pi-hole/blob/9b106e6275cf9095ee8822f498c0cc907419da78/Dockerfile#L48
> > > 
> > > https://github.com/pi-hole/docker-pi-hole/blob/9b106e6275cf9095ee8822f498c0cc907419da78/start.sh#L79
> > > 
> > > Try removing the `:ro` at the end of the `./config-pihole/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro` line and see if it makes a difference.
> > 
> > 
> > I have the /etc/pihole/ path mapped, not as read-only, and still have the issue.
> 
> I was referring specifically to the `/etc/pihole/pihole-FTL.conf` file. Check if you have a volume that only bind mounts that one file and check if that volume is read only.

now my volumes mount look like
```
      - ./work_pihole:/etc/pihole:rw
      - ./config-pihole/hosts:/etc/hosts:ro
      - ./config-pihole/resolv.conf:/etc/resolv.conf:ro
      - ./config-pihole/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro
      - ./config-pihole/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf
```
however the issue still remains.

**Comment by UryDanko** [comment]
> > Given the Synology method of updating a Docker image
> 
> I've never bumped into any issues updating Pi-hole on my DSM218+, that said - I'm using CLI and `docker-compose` and always `docker-compose pull && docker-compose down && docker-compose up -d`

not sure you really need to do `docker-compose down` because if thee is a new image - container will be restarted anyway. 
But also this was my usual way to upgrade the service.

**Comment by joshau** [comment]
Haven't dove in deep, but this PR seemed relevant. https://github.com/pi-hole/pi-hole/pull/4282
For now, rolling back to 5.8.1 keeps me going.

**Comment by PromoFaux** [comment]
Can anyone that is seeing this please set the env var `PH_VERBOSE: 1` and paste in a copy of the startup logs afterwards please?

**Comment by joshau** [comment]
```

**Comment by joshau** [comment]
truncated to the end, lmk if you need more.
```
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
+ echo 'Google (ECS);8.8.8.8;8.8.4.4;2001:4860:4860:0:0:0:0:8888;2001:4860:4860:0:0:0:0:8844
OpenDNS (ECS, DNSSEC);208.67.222.222;208.67.220.220;2620:119:35::35;2620:119:53::53
Level3;4.2.2.1;4.2.2.2;;
Comodo;8.26.56.26;8.20.247.20;;
DNS.WATCH;84.200.69.80;84.200.70.40;2001:1608:10:25:0:0:1c04:b12f;2001:1608:10:25:0:0:9249:d69b
Quad9 (filtered, DNSSEC);9.9.9.9;149.112.112.112;2620:fe::fe;2620:fe::9
Quad9 (unfiltered, no DNSSEC);9.9.9.10;149.112.112.10;2620:fe::10;2620:fe::fe:10
Quad9 (filtered + ECS);9.9.9.11;149.112.112.11;2620:fe::11;2620:fe::fe:11
Cloudflare;1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001'
+ chmod 644 /etc/pihole/dns-servers.conf
+ [[ ! -r /etc/pihole/pihole-FTL.conf ]]
+ [[ ! -r /etc/pihole/custom.list ]]
+ [[ true == true ]]
+ [[ ! -d /etc/lighttpd ]]
+ [[ -f /etc/lighttpd/lighttpd.conf ]]
+ mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.orig
+ install -D -m 644 -T /etc/.pihole/advanced/lighttpd.conf.debian /etc/lighttpd/lighttpd.conf
+ touch /etc/lighttpd/external.conf
+ chmod 644 /etc/lighttpd/external.conf
+ [[ -f /var/www/html/pihole/custom.php ]]
+ mkdir -p /run/lighttpd
+ chown www-data:www-data /run/lighttpd
+ mkdir -p /var/cache/lighttpd/compress
+ chown www-data:www-data /var/cache/lighttpd/compress
+ mkdir -p /var/cache/lighttpd/uploads
+ chown www-data:www-data /var/cache/lighttpd/uploads
+ touch /etc/pihole/setupVars.conf
+ set +e
+ mkdir -p /var/run/pihole /var/log/pihole
+ chown pihole:root /etc/lighttpd
+ chown pihole:pihole /etc/pihole/pihole-FTL.conf /var/log/pihole
+ chmod 644 /etc/pihole/pihole-FTL.conf
+ touch /var/log/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port /var/log/pihole.log
+ chown pihole:pihole /var/run/pihole /var/log/pihole
+ test -f /var/run/pihole/FTL.sock
+ chown pihole:pihole /var/log/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port /etc/pihole /var/log/pihole.log
+ [[ -e /etc/pihole/dhcp.leases ]]
+ chmod 0644 /var/log/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port /var/log/pihole.log
+ set -e
+ pihole updatechecker
+ [[ -e /etc/pihole/setupVars.conf ]]
+ cp -f /etc/pihole/setupVars.conf /etc/pihole/setupVars.conf.update.bak
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n true ']'
+ change_setting INSTALL_WEB_SERVER true
+ delete_setting INSTALL_WEB_SERVER
+ sed -i '/^INSTALL_WEB_SERVER/d' /etc/pihole/setupVars.conf
+ add_setting INSTALL_WEB_SERVER true
+ echo INSTALL_WEB_SERVER=true
+ '[' -n true ']'
+ change_setting INSTALL_WEB_INTERFACE true
+ delete_setting INSTALL_WEB_INTERFACE
+ sed -i '/^INSTALL_WEB_INTERFACE/d' /etc/pihole/setupVars.conf
+ add_setting INSTALL_WEB_INTERFACE true
+ echo INSTALL_WEB_INTERFACE=true
+ '[' -n '' ']'
+ '[' -n 192.168.1.3 ']'
+ changeFTLsetting REPLY_ADDR4 192.168.1.3
+ deleteFTLsetting REPLY_ADDR4
+ sed -i '/^REPLY_ADDR4/d' /etc/pihole/pihole-FTL.conf
sed: cannot rename /etc/pihole/sedE4Eblx: Device or resource busy
[cont-init.d] 20-start.sh: exited 4.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by dschaper** [comment]
https://unix.stackexchange.com/a/632478

```plain
+ changeFTLsetting REPLY_ADDR4 192.168.1.3
+ deleteFTLsetting REPLY_ADDR4
+ sed -i '/^REPLY_ADDR4/d' /etc/pihole/pihole-FTL.conf
sed: cannot rename /etc/pihole/sedE4Eblx: Device or resource busy
```

**Comment by dschaper** [comment]
We `+ touch /etc/pihole/setupVars.conf` which creates the file inside the docker container and doesn't cause any docker issues. We don't `touch` `pihole-FTL.conf` so the file is external and `sed` moves files when doing in-place edits. The SE suggestion is to use the `copy` mode instead of move for `sed -i` so that a new file is created from the `sed` process.

**Comment by PromoFaux** [comment]
OK, no idea if this will work or not, as I've been unable to reproduce, but try the tag `:test-touch-ftl` and see if that makes a difference...

**Comment by joshau** [comment]
same over here:
```
+ touch /etc/pihole/setupVars.conf
+ touch /etc/pihole/pihole-FTL.conf
+ set +e
+ mkdir -p /var/run/pihole /var/log/pihole
+ chown pihole:root /etc/lighttpd
+ chown pihole:pihole /etc/pihole/pihole-FTL.conf /var/log/pihole
+ chmod 644 /etc/pihole/pihole-FTL.conf
+ touch /var/log/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port /var/log/pihole.log
+ chown pihole:pihole /var/run/pihole /var/log/pihole
+ test -f /var/run/pihole/FTL.sock
+ chown pihole:pihole /var/log/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port /etc/pihole /var/log/pihole.log
+ [[ -e /etc/pihole/dhcp.leases ]]
+ chmod 0644 /var/log/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port /var/log/pihole.log
+ set -e
+ pihole updatechecker
+ [[ -e /etc/pihole/setupVars.conf ]]
+ cp -f /etc/pihole/setupVars.conf /etc/pihole/setupVars.conf.update.bak
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n true ']'
+ change_setting INSTALL_WEB_SERVER true
+ delete_setting INSTALL_WEB_SERVER
+ sed -i '/^INSTALL_WEB_SERVER/d' /etc/pihole/setupVars.conf
+ add_setting INSTALL_WEB_SERVER true
+ echo INSTALL_WEB_SERVER=true
+ '[' -n true ']'
+ change_setting INSTALL_WEB_INTERFACE true
+ delete_setting INSTALL_WEB_INTERFACE
+ sed -i '/^INSTALL_WEB_INTERFACE/d' /etc/pihole/setupVars.conf
+ add_setting INSTALL_WEB_INTERFACE true
+ echo INSTALL_WEB_INTERFACE=true
+ '[' -n '' ']'
+ '[' -n 192.168.1.3 ']'
+ changeFTLsetting REPLY_ADDR4 192.168.1.3
+ deleteFTLsetting REPLY_ADDR4
+ sed -i '/^REPLY_ADDR4/d' /etc/pihole/pihole-FTL.conf
sed: cannot rename /etc/pihole/sedbMb6nR: Device or resource busy
[cont-init.d] 20-start.sh: exited 4.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
I'll attempt an adjustment to the sed command (to include the `-c` flag), later on to see if that has any affect.

**Comment by AlexandreRatte** [comment]
> https://unix.stackexchange.com/a/632478
> 
> ```
> + changeFTLsetting REPLY_ADDR4 192.168.1.3
> + deleteFTLsetting REPLY_ADDR4
> + sed -i '/^REPLY_ADDR4/d' /etc/pihole/pihole-FTL.conf
> sed: cannot rename /etc/pihole/sedE4Eblx: Device or resource busy
> ```

I attempted to refactor the `deleteFTLsetting()` function in `webpage.sh` with the tricks mentioned in that page but they just don't work when `pihole-FTL.conf` is volume-mounted using a ConfigMap in Kubernetes, as the filesystem is read-only.

I'm thinking the only way around this would be to add error handling in `changeFTLsetting()` to prevent `20-start.sh` from exiting ungracefully, when a setting cannot be changed. I can have a stab at this in a few hours, if this is deemed an acceptable solution.

**Comment by PromoFaux** [comment]
> is volume-mounted using a ConfigMap in Kubernetes, as the filesystem is read-only.

I'm v naïve when it comes to k8s (and _most_ docker stuff tbh). What is the advantage of a ConfigMap in this case, rather than just mounting the `/etc/pihole` directory fully? (which at least in OP's compose file - that is also done)

**Comment by AlexandreRatte** [comment]
@PromoFaux it was a convenient way to deploy preconfigured redundant Pi-hole pods without the need for persistent volumes or Init Containers. I'm supplying the contents of `pihole-FTL.conf` on startup primarily to control data retention for queries.

```
MAXDBDAYS=7
LOGFILE=/var/log/pihole/pihole-FTL.log
```

Unfortunately, with the current implementation for managing the `REPLY_ADDR*` settings, using a ConfigMap is not possible anymore.

**Comment by AlexandreRatte** [comment]
A strong argument is being made in https://github.com/pi-hole/pi-hole/pull/4334 to not perform error handling on `changeFTLsetting()` and in looking into porting the error handling into this repository's `start.sh`, I think the same argument applies.

Considering the primary reason I was supplying a ConfigMap to my Pi-hole DaemonSet was to customize FTL's `MAXDBDAYS`, I'm thinking a better way to address my particular use case would be to contribute an additional environment variable to customize FTL's query data retention, in a similar fashion as https://github.com/pi-hole/docker-pi-hole/pull/902.

That being said, I think it would also make sense to mention that using read-only filesystems for `pihole-FTL.conf` should be avoided, perhaps in the `Upgrading, Persistence, and Customizations` section of the `README.md` file. Maybe something along the lines of:

> The standard Pi-hole customization abilities apply to this docker, but with docker twists such as using docker volume mounts to map host stored file configurations over the container defaults. **However, mounting these configuration files as read-only should be avoided.**

Thoughts?

**Comment by srfoster1** [comment]
I have exactly the same problem.

These are/were the offending lines in my compose file
      - /volume1/docker/${LOCAL_PATH}/pihole:/etc/pihole:rw
      - /volume1/docker/${LOCAL_PATH}/config/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf

I made the pihole-FTL.conf mapping rw, and still had the problem.

The temporary solution I have taken is to remove the mapping for pihole-FTL.conf, and manually edit the file created by pihole. Not ideal, but it does allow me to use the latest docker images.

**Comment by AlexandreRatte** [comment]
For folks eager to regain the ability to customize `pihole-FTL.conf`, as of today, the `pihole:dev` tag now allows you to customize any [FTLDNS setting](https://docs.pi-hole.net/ftldns/configfile/) using environment variables having the `FTLCONF_` prefix, so volume mounting that file should not be necessary anymore, for most cases! Refer to the `README.md` file for more details.

Here are excerpts from my Kubernetes DaemonSet:

**pihole-daemonset.yml**:
```
    spec:
      containers:
      - env:
        - name: FTLCONF_MAXDBDAYS
          value: "7"
```

**pihole-FTL.log**:
```
root@pihole-5mqqt:/# grep -B3 MAXDBDAYS /var/log/pihole-FTL.log
[2021-11-26 16:29:53.209 351M] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
[2021-11-26 16:29:53.209 351M]    SOCKET_LISTENING: only local
[2021-11-26 16:29:53.209 351M]    AAAA_QUERY_ANALYSIS: Show AAAA queries
[2021-11-26 16:29:53.209 351M]    MAXDBDAYS: max age for stored queries is 7 days
```

**Comment by PromoFaux** [comment]
Keep in mind the `dev` tag also uses development versions of the main Pi-hole components, so may not be stable.

I've just pushed a [`2021.11`](https://github.com/pi-hole/docker-pi-hole/releases/tag/2021.11) tag to incorporate these changes : should be on docker.io and ghcr.io in about 30 mins:

https://github.com/pi-hole/docker-pi-hole/actions/runs/1509224809

**Comment by AlexandreRatte** [comment]
Good to know! I've amended my comment to prevent misleading any readers.

**Comment by PromoFaux** [comment]
> Keep in mind the `dev` tag also uses development versions of the main Pi-hole components, so may not be stable.

I changed my mind about this recently - `dev` tag now includes whatever the latest released versions of Pi-hole components are - only the `nightly` has the `development` branches of each component by default.

In the `dev` tag, though, you _can_ use `pihole checkout` to try out other branches, which is disabled on the versioned/latest tag for docker
