### ISSUE TITLE
Redirect crontab to persistent file

### ISSUE THREAD

**Issue by MrSimmo** [pi-hole/docker-pi-hole#925]
This is a need in the user community to adjust the frequency that Pihole refreshes the gravity list.

The Pihole devs have suggested to 'just update the crontab' to change the frequency but that to my knowledge isn't possible  in the docker container at the moment.

Would it be possible to make a change to somehow allow us to update this?

Cheers

**Comment by dschaper** [comment]
You should be able to mount the file in with a bind/volume mount.

**Comment by MrSimmo** [comment]
Cheers - will give it a try
