### ISSUE TITLE
No "/etc/pihole" config folder? 

### ISSUE THREAD

**Issue by BrodyStone21** [pi-hole/docker-pi-hole#927]
My pihole server is running just fine with no issues. However, I don't have a /etc/pihole folder even though I have set its location inside of my docker run command. You can find this command below. Let me know how I can troubleshoot this issue. 

`docker run -d \
  --name=pihole \
  -e TZ=America/Indianapolis \
  -e SERVERIP=192.168.1.x \
  -e WEBPASSWORD=MyPasswordHere \
  -v pihole:/etc/pihole \
  -v dnsmasq:/etc/dnsmasq.d \
  -p 53:53/tcp \
  -p 53:53/udp \
  -p 67:67/udp \
  -p 80:80/tcp \
  --restart unless-stopped \
  pihole/pihole`

I'm running the latest version of everything. OS is Ubuntu Server 20.04 LTS

**Comment by PromoFaux** [comment]
What you're doing there, is creating a volume.

https://docs.docker.com/storage/volumes/

If you want to mount it on the physical filesystem use `-v /full/path/to/pihole:/etc/pihole`

Better still, look at using docker-compose, it's much easier to read than a docker run command!

**Comment by BrodyStone21** [comment]
> What you're doing there, is creating a volume.
> 
> https://docs.docker.com/storage/volumes/
> 
> If you want to mount it on the physical filesystem use `-v /full/path/to/pihole:/etc/pihole`
> 
> Better still, look at using docker-compose, it's much easier to read than a docker run command!

Is there a way that I can access a created a volume or should I mount it and then access it?

I've been meaning to look into docker-compose but I just haven't gotten around to it yet. Are there any advantages besides easier updating?

**Comment by PromoFaux** [comment]
Personally I just find it easier to read a `docker-compose.yml` :)

To be honest, I'm a total novice when it comes to docker stuff. I'm pretty sure most of the stuff I run at home would not be considered "best practice" by the docker-elite but it works for me and that's good enough!
