### ISSUE TITLE
set single DNS server using PIHOLE_DNS_ environment variable

### ISSUE THREAD

**Issue by r0bj** [pi-hole/docker-pi-hole#929]
This is a: Bug

## Details

Using deprecated environment variables I can set only one DNS server with:
DNS1=1.1.1.1
DNS2=no

Since `DNS1` and `DNS2` are deprecated in favor of `PIHOLE_DNS_`, I don't see any way to set single DNS server using PIHOLE_DNS_ environment variable.

Example:
PIHOLE_DNS_=1.1.1.1 - previous secondary is used, it's just not affecting secondary DNS setting

docker-pi-hole version: 2021.10

**Comment by PromoFaux** [comment]
@r0bj I'm not sure I understand. using, for example, `PIHOLE_DNS_=1.1.1.1` appears to only set a single DNS as expected?

![image](https://user-images.githubusercontent.com/1998970/148654077-d04d3a7e-953e-42ba-a04f-5a8a89386aed.png)

**Comment by r0bj** [comment]
@PromoFaux Yes, if you previously had empty secondary DNS this is what you get. But try to set both DNS servers and then use `PIHOLE_DNS_=1.1.1.1`. You will get 1.1.1.1 as a primary DNS and previous secondary as a secondary DNS (secondary is not cleared from previous setup with setting PIHOLE_DNS_=1.1.1.1).

**Comment by PromoFaux** [comment]
OK, I think I get it. I vaguely recall a discussion about this in the past - especially when it comes to mixing environment variables and persisted settings storage. Which one should take precedence over the other? 

Say you spin up a container with only 1 DNS server in the env var, but then at some later stage decide to add another one via the web interface. When you destroy the container, and then recreate it - do you want the second value stored in `setupVars.conf` to still be around, or do you want it to fall back to being only 1 DNS server as set in the environment?

**Comment by PromoFaux** [comment]
@r0bj see the above PR for a solution that should fix this behaviour to be more along the lines of what you are expecting. In fact I think it makes more sense to do it this way

**Comment by r0bj** [comment]
@PromoFaux Thanks. It make more sense to me that explicitly set parameters (e.g. via env vars) override others stored somewhere else. It's useful during any sort of automated bootstrapping, when clicking via web GUI is not a good option.

**Comment by tarmacalastair** [comment]
Just installed pihole docker today. 

All good but I want 2 x upstream DNS servers. If I use PIHOLE_DNS_= on two lines then only one is used. Also if I try PIHOLE_DNS2= on the second line then that is ignored too.
I can't see how to get 2 servers.

**Comment by PromoFaux** [comment]
`PIHOLE_DNS=1.1.1.1;2.2.2.2;3.3.3.3` etc etc etc

It's on the [Readme page](https://github.com/pi-hole/docker-pi-hole#optional-variables) 😉

**Comment by tarmacalastair** [comment]
> `PIHOLE_DNS=1.1.1.1;2.2.2.2;3.3.3.3` etc etc etc
> 
> It's on the [Readme page](https://github.com/pi-hole/docker-pi-hole#optional-variables) wink

Oops, sorry!
