### ISSUE TITLE
Fading lists

### ISSUE THREAD

**Issue by DFlexy** [pi-hole/docker-pi-hole#933]
Good Morning;
I'm having problems with my adlist
They are being removed every day,
This issue started to occur in the last 2 updates.
Can someone help me please ?

My config docker

```
docker run -d \
  --name pihole \
  --hostname pihole \
  -e TZ=America/Sao_Paulo \
  -v pihole:/etc/pihole/ \
  -v dnsmasq:/etc/dnsmasq.d/ \
  -e DNS1=172.20.0.2#5053 \
  -e DNSMASQ_LISTENING=local \
  --cap-add=sys_nice \
  --cap-add=NET_ADMIN \
  --network=host \
  --restart=unless-stopped \
  pihole/pihole
```

**Comment by PromoFaux** [comment]
There are only two things I can think of here.. someone else has access to your Pi-hole instance/interface and is deleting the entries, or there is something wrong clearing/breaking the volume mounts:

```
 -v pihole:/etc/pihole/ \
  -v dnsmasq:/etc/dnsmasq.d/ \
```

Out of interest, do you still see the same issues if you don't mount any volumes? And/Or if you directly mount to the host filesystem?

**Comment by DFlexy** [comment]
I believe I found the problem but I don't know why it occurs.
When disabling a CRON the problem stopped.
follow below the CRON

#CRON PARA UPDATE PIHOLE ADLIST
* 4 * * * docker exec pihole pihole -g >/dev/null 2>&1

**Comment by PromoFaux** [comment]
@DFlexy Is this still an issue in the latest tag?
