### ISSUE TITLE
duplicate PIHOLE_DOCKER_TAG after upgrade

### ISSUE THREAD

**Issue by mfschumann** [pi-hole/docker-pi-hole#952]
### Versions

- Pi-hole:  v5.7
- AdminLTE:  v5.9
- FTL:  v5.12

### Platform

- OS and version:  Fedora 35

- Platform:  Docker

### Expected behavior

Pihole should work after upgrading the docker container to the newest available version of the pihole image.

### Actual behavior / bug

The upgrade adds an additional 'PIHOLE_DOCKER_TAG' line to the config in lighttpd/conf-enabled/15-fastcgi-php.conf. That causes pihole to fail starting because of the duplicate PIHOLE_DOCKER_TAG.

### Steps to reproduce

1. Set up pihole docker.
2. Delete the docker container, but keep the config.
3. Set up a newer version of the pihole docker container, using the same config files as before.

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

My current 15-fastcgi-php.conf:

```
# -*- depends: fastcgi -*-
# /usr/share/doc/lighttpd/fastcgi.txt.gz
# http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs:ConfigurationOptions#mod_fastcgi-fastcgi

## Start an FastCGI server for php (needs the php5-cgi package)
fastcgi.server += ( ".php" => 
	((
		"bin-path" => "/usr/bin/php-cgi",
		"socket" => "/var/run/lighttpd/php.socket",
		"max-procs" => 1,
		"bin-environment" => ( 
			"PIHOLE_DOCKER_TAG" => "2021.12",
			"CORS_HOSTS" => "",
			"VIRTUAL_HOST" => "dns.mfs.name",
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "192.168.0.50",
			"PHP_FCGI_CHILDREN" => "4",
			"PHP_FCGI_MAX_REQUESTS" => "10000"
		),
		"bin-copy-environment" => (
			"PATH", "SHELL", "USER"
		),
		"broken-scriptfilename" => "enable"
	))
)
```
Immediately after the upgrade from 2021.11 to 2021.12, an additional line reading
```
"PIHOLE_DOCKER_TAG" => "2021.11",
```
was present directly below the line containing PIHOLE_DOCKER_TAG in the current config. I removed the additional line to make pihole start again.

**Comment by jpspgd** [comment]
I experienced the same problem upgrading from 2021.11 to 2021.12. Removing the duplicate PIHOLE_DOCKER_TAG also fixed it for me.

**Comment by PromoFaux** [comment]
This is the section of code that adds it to `15-fastcgi-php.conf`:

https://github.com/pi-hole/docker-pi-hole/blob/master/bash_functions.sh#L197-L221

I did make this change that touched that area of code:

https://github.com/pi-hole/docker-pi-hole/commit/9a9ee41a45d0c29a66a2fae320aee23ad1673f5b

Not sure why that would have affected it. When you updated, did you do a complete container destruction and rebuild? (i.e docker-compose down && docker-compose up -d)?

**Comment by mfschumann** [comment]
I run the container with podman and use its auto-update functionality. That is supposed to pull the new image, stop, delete the old container and run a new container off the updated image. 

Btw, I have had the issue in the upgrade from 2021.10 to .11 and from .11 to .12. Your commit has been made after .11 was out, so it's unlikely to be causing the issue I'd say.

**Comment by PromoFaux** [comment]
And it is just that variable that gets duplicated? I can't see anything difference in the how the others are populated and this one.. 🤔

I get the feeling it will be one of those "when you see it.." moments, but... nothing is sticking out at the moment

**Comment by jpspgd** [comment]
@mfschumann jogged my memory: I also had the same problem upgrading from 2021.10 to .11. I have a similar setup: I initially deployed months ago via docker run (pasted from my bash history below) but I periodically update via Portainer by stop/delete/deploy with the new image. The duplicate variable persists in /etc.

`docker run -d     --name pihole     -p 53:53/tcp -p 53:53/udp     -p 80:80     -e TZ="America/New_York"     --dns=8.8.8.8 --dns=8.8.4.4     --restart=unless-stopped     --hostname pi.hole     -e VIRTUAL_HOST="pi.hole"     -e PROXY_LOCATION="pi.hole"     -e ServerIP="192.168.1.251" -v pihole:/etc  -e WEBPASSWORD="MerryChristmas" pihole/pihole:latest`

**Comment by mfschumann** [comment]
I looked through my logs and found that when starting pihole after the upgrade from 2021.11 to .12, `setup_php_env` has been called with both PIHOLE_DOCKER_TAGS for some reason:
```
 Added ENV to php:
                         "PIHOLE_DOCKER_TAG" => "2021.12",
                         "PIHOLE_DOCKER_TAG" => "2021.11",
                         "VIRTUAL_HOST" => "correct.host.name",
                         "CORS_HOSTS" => "",
                         "PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
                         "ServerIP" => "10.0.0.100",
```

**Comment by mfschumann** [comment]
After meditating over what `setup_php_env` does I think I found the problem:
```
    grep -qP "$pihole_docker_tag_line" "$PHP_ENV_CONFIG" || \
        sed -i "/bin-environment/ a\\${pihole_docker_tag_line}" "$PHP_ENV_CONFIG"
```
We look for `$pihole_docker_tag_line` and if it's not found, a new line containing `$pihole_docker_tag_line` is added. After an upgrade of the docker container, `$pihole_docker_tag_line` already contains the new docker tag, which cannot be found in the config file, so a new line will be added.

The same issue is bound to occur when changing one of the other env variables (e.g. ServerIP) and restarting the container.

I'll prepare a pull request fixing this issue.

**Comment by PromoFaux** [comment]
Thanks for the PR @mfschumann on reviewing it, I had a thought:

I think I just realised why @jpspgd, at least, is seeing this:

> `-v pihole:/etc`

This is probably overkill, one doesn't need to map the _entire_ `/etc/` directory!

@mfschumann - do you also have this file mapped out to a physical file on the host machine?

I have never seen this when running Pi-hole container myself, and I do not map and files in the `/etc/lighttpd` directory...

**Comment by mfschumann** [comment]
@PromoFaux I do map /etc/lighttpd indeed because I thought it would be good to have it persistent. Are you saying all config in /etc/lighttpd is generated dynamically, so there is no need to persist it in the first place?

**Comment by jpspgd** [comment]
> Thanks for the PR @mfschumann on reviewing it, I had a thought:
> 
> I think I just realised why @jpspgd, at least, is seeing this:
> 
> > `-v pihole:/etc`
> 
> This is probably overkill, one doesn't need to map the _entire_ `/etc/` directory!
> 
> @mfschumann - do you also have this file mapped out to a physical file on the host machine?
> 
> I have never seen this when running Pi-hole container myself, and I do not map and files in the `/etc/lighttpd` directory...

LOL You're proooobably right. I migrated from a bare-metal non-container install on an actual Pi with some dnsmasq and other customizations. Lazy me just mapped out /etc and copied over those configs. I can probably scale that back... ;)

**Comment by PromoFaux** [comment]
> so there is no need to persist it in the first place?

Correct :) There isn't really anything in there that you would need to persist, tbh - unless you made some customisation to lighttpd's config file, but I don't see that happen a lot. Regardless, though, thanks for your PR - I think it makes that section of code easier to read/

> I can probably scale that back... ;)

Probably wise!
