### ISSUE TITLE
DNSMASQ_WARN: interface eth0 does not currently exist

### ISSUE THREAD

**Issue by realiis** [pi-hole/docker-pi-hole#954]
After starting the container (docker and podman, pihole container version 2021.12.1), I see the following message in `/admin/messages.php`:
![image](https://user-images.githubusercontent.com/39202026/147422894-0363537d-9607-48b4-b60e-16cae9d808f0.png)

This is a: Bug

## Details

A `tap0` interface is created in the container instead of `eth0`
```
root@9c86623fa1f8:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tap0: <BROADCAST,UP,LOWER_UP> mtu 65520 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 42:49:17:e5:bd:99 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.100/24 brd 10.0.2.255 scope global tap0
       valid_lft forever preferred_lft forever
    inet6 fe80::4049:17ff:fee5:bd99/64 scope link 
       valid_lft forever preferred_lft forever
```
## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

I tried this https://discourse.pi-hole.net/t/interface-eth0-does-not-currently-exist/51810/6 but it doesn't work

## How to reproduce the issue 

1. Environment data
  * Operating System: Fedora CoreOS 
  * Hardware: PC 
  * Kernel Architecture: amd64 
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software:  NIL 
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```version: "3"
services:
  pihole:
    container_name: pihole_compose
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8000:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'password'
    volumes:
      - './etc-pihole/:/etc/pihole/:Z'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/:Z'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

**Comment by jkossis** [comment]
Just wanted to bump this, as I am running into the same issue as well.

**Comment by yubiuser** [comment]
The reason is that FTL starts faster than your interface is ready. Try adding `DELAY_STARTUP=5` to `/etc/pihole/pihole-FTL.conf` to delay the startup of FTL for 5 sec.

https://docs.pi-hole.net/ftldns/configfile/#delay_startup

**Comment by PromoFaux** [comment]
As it is in a container, add `FTLCONF_DELAY_STARTUP=5` as an environment variable

**Comment by jkossis** [comment]
@yubiuser @PromoFaux as OP mentioned in the `Related Issues` section, this does not solve the issue. I tried both of your suggestions to no avail.

It seems like the incorrect interface (`tap0`) is being used.

**Comment by PromoFaux** [comment]
Can we please get a debug token from within the container? `pihole -d` and then choose to upload

**Comment by PromoFaux** [comment]
Sorry, been having some issues with getting the latest release ready... can you please try the following environment variable:

`INTERFACE=tap0` (or whatever your interface name is)

per https://github.com/pi-hole/docker-pi-hole#advanced-variables

No guarantees, but I've been looking at this section of code for the last 2 hours, and I _think_ it should work...

**Comment by jkossis** [comment]
@PromoFaux the INTERFACE env did the trick. Thank you!

**Comment by Maximilian-tek** [comment]
should stay open, dear bot :)

**Comment by dschaper** [comment]
Did the fix of setting the `INTERFACE` environment variable not work for you?

**Comment by Maximilian-tek** [comment]
Fixed it - thank you.
