### ISSUE TITLE
Disk shortage warning

### ISSUE THREAD

**Issue by DL6ER** [pi-hole/docker-pi-hole#955]
I'm seeing the same error but on a raspberry Pi 4, fresh install

_Originally posted by @krillin666 in https://github.com/pi-hole/docker-pi-hole/issues/951#issuecomment-1001059425_

**Comment by DL6ER** [comment]
Further replies:

> @krillin666 which operating system are you using? Are you running Pi-hole in a docker container? How does `df -h` look like?

by @DL6ER

> > @krillin666 which operating system are you using? Are you running Pi-hole in a docker container? How does `df -h` look like?
> 
> Hi @DL6ER , I'm running raspbian OS. Running `df -h` i get:
> 
> ```
> Filesystem      Size  Used Avail Use% Mounted on
> /dev/root       440G  398G   25G  95% /
> devtmpfs        3.7G     0  3.7G   0% /dev
> tmpfs           3.9G     0  3.9G   0% /dev/shm
> tmpfs           3.9G  9.3M  3.9G   1% /run
> tmpfs           5.0M  4.0K  5.0M   1% /run/lock
> tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
> /dev/sda1       253M   49M  204M  20% /boot
> tmpfs           790M     0  790M   0% /run/user/1000
> 
> ```
> 
> Also the errors on the Admin interface:
> 
> ![image](https://user-images.githubusercontent.com/60305303/147421977-51c4f7a2-2f33-4369-b71a-4345b88e676a.png)
> 

by @krillin666

> > I'm running raspbian OS
>
> Are you running Pi-hole in docker? If not - then please open a thread on discourse.pi-hole.net
>
> This thread is to track a specific issue with this warning showing up in docker containers

by @PromoFaux

**Comment by DL6ER** [comment]
I sort of moved your issue over here, unfortunately, Github doesn't allow to really isolate + move posts when it is appropriate.

As you `df` snippt shows, you are not affected by any bug. Indeed the warning is correct as the default is to warn if more than 90% of disk space is used, for your it is `95%`:

> ```
> Filesystem      Size  Used Avail Use% Mounted on
> /dev/root       440G  398G   25G  95% /
> ```

You can either increase the limit to silence the warning until you hit again a threshold (say `CHECK_DISK=98`) or disable the check altogether (not recommended, but possible with `CHECK_DISK=0`). See [here](https://docs.pi-hole.net/ftldns/configfile/#check_disk) for more information.

**Comment by Campkom** [comment]
Hey,

i also noticed exactly the same problem with my docker running on a debian VM. Pihole (exact same versions) is also reporting disk shortage.

Will there be a fix in the future?

Thanks already.
