### ISSUE TITLE
Cannot delete diagnosis LOAD message

### ISSUE THREAD

**Issue by r2ixuz** [pi-hole/docker-pi-hole#958]
### Platform

Docker Tag 2021.12.1 Pi-hole v5.7 FTL v5.12.1 Web Interface v5.9 

### Expected behavior

Able to delete any diagnosis message.

### Actual behavior / bug

Unable to delete LOAD diagnosis message: "Error, something went wrong! While executing message statement: attempt to write a readonly database"

### Steps to reproduce

Use latest stable Docker Image and wait for high system load. ;-)

### Screenshots

<img width="1203" alt="screenshot" src="https://user-images.githubusercontent.com/15087554/147651027-ca28a27f-47ca-4d8a-af58-806f9702b5cb.png">

### Additional context

My DB is writeable as any other stuff in Pi-Hole works as normal. Just deleting this message is not possible.

**Comment by yubiuser** [comment]
Have a look here: https://discourse.pi-hole.net/t/error-while-deleting-diagnosis-entry/51814

The solution there might be also fix your issue.

**Comment by r2ixuz** [comment]
Yes, changing permissions for pihole-FTL.db to the Docker containers user "pihole" (ID 999) works.

Originally it was owned by root:root. And FTL process is running as root, so it should have been working as it was. There is something wrong.

On the other hand, these 3 files in /etc/pihole are already owned by "pihole": gravity.db, gravity_old.db, pihole-FTL.conf.

Removing the pihole-FTL.db file and restarting/recreating the containers sets the permissions again wrong to root.

**Comment by DL6ER** [comment]
FTL creates the database itself. Hence, it is root owned. In your case, the web interface wants to modify the database. This is done by another process not running as root.

Either we chown the database or run FTL as user pihole as we do on native installs (FTL is *never* running as root here). I'd prefer the later.

**Comment by DL6ER** [comment]
The question is also: What changed in the docket scripts? The database is there for years, however, the reports for this permission issues are all rather new. Suggesting a change having happened rather recently.
@PromoFaux

**Comment by yubiuser** [comment]
Maybe: https://github.com/pi-hole/AdminLTE/pull/1886

Needed change of permission in FTL (https://github.com/pi-hole/FTL/pull/1162)  and core (https://github.com/pi-hole/pi-hole/pull/4328)

**Comment by DL6ER** [comment]
You are right. The delete button is the new element in the equation. It has always been like this but it wasn't really discovered before ... flushing the network table is one other thing but that isn't done very often.

FTL sets the permissions correctly as per the mentioned PR, this issue is about the ownership.
The `service` file isn't used in `docker`.

**Comment by r2ixuz** [comment]
Don't know when or where a missing DB is created at container boot, but I guess chown for the DB is missing here: https://github.com/pi-hole/docker-pi-hole/blob/master/bash_functions.sh ?

**Comment by doodlemania2** [comment]
Thanks @yubiuser
