### ISSUE TITLE
custom.list file is not editable through pi-hole webinterface when volume mounted (docker -v) 

### ISSUE THREAD

**Issue by benlenau** [pi-hole/docker-pi-hole#972]
Changes are ignored when trying to add/remove Pi-hole DNS Records via admin webinterface when custom.list-file is mounted through docker.

This is a: BUG

## Details

On every add/remove of DNS Records docker log provides the following error:

> sed: cannot rename /etc/pihole/sed0MyUj5: Device or resource busy

custom.list fileownership has been validated and is that of the docker container. Also tried setting this to both root and 999:999 (that of the container pihole user) and r/w for everyone. And DNSMASQ_USER has been both root and pihole (default).

Guess: my guess is that the sed command isn't allowed to move its temp file from inside the container and overwrite that of the mounted custom.list file.

Note: I only want dns records to be persistent across container installs. And that's why I'm only mounting custom.list and not the whole /etc/pihole-dir.

Update: I'm able to add dns records but NOT remove them. 

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Debian 11 
  * Hardware: Lenovo ThinkCentre 
  * Kernel Architecture: x86/amd64 
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software: 
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
docker run -d \
        --name="pihole" \
        --hostname="pihole" \
        -p 8080:80 \
        -p 53:53/udp \
        -p 53:53/tcp \
        -v "$(pwd)/config/custom.list:/etc/pihole/custom.list" \
        -e PIHOLE_DNS_="1.1.1.1;1.0.0.1" \
        -e DNSMASQ_USER="root" \
        --dns=1.1.1.1 \
        --dns=1.0.0.1 \
        --restart=unless-stopped \
        pihole/pihole:latest
```
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by dschaper** [comment]
What version are you seeing when you go to the admin page?

All of the `sed` calls should be `sed -i` for in-place editing.

**Comment by benlenau** [comment]
Latest.

![image](https://user-images.githubusercontent.com/70938462/148560183-1e824a1d-bb4b-4fca-8feb-42b310af072d.png)

**Comment by PromoFaux** [comment]
Hmmm, I thought I was unable to repro this - as I was able to add items to the list with no issues, but when It try to delete an entry, that's when it goes wrong. Let me see if I can track it down. In the mean time - can you just confirm that it works fine for you if you bind mount the whole of the `/etc/pihole` directory instead of just that one file?

**Comment by benlenau** [comment]
> Hmmm, I thought I was unable to repro this - as I was able to add items to the list with no issues, but when It try to delete an entry, that's when it goes wrong. Let me see if I can track it down. In the mean time - can you just confirm that it works fine for you if you bind mount the whole of the `/etc/pihole` directory instead of just that one file?

Good to know I'm not crazy. 

Forgot to mention that I also can add entries. Was so focused on what didn't work. 

I can confirm that dir mount works fine - Both adding and removing entries.

**Comment by PromoFaux** [comment]
So researching a little into this, I found the following here on a [mirror of the docker docs for 1.10](https://apimirror.com/docker~1.10/engine/userguide/containers/dockervolumes/index)

>Note: Many tools used to edit files including `vi` and `sed --in-place` may result in an inode change. Since Docker v1.1.0, this will produce an error such as “sed: cannot rename ./sedKdJ9Dy: Device or resource busy”. In the case where you want to edit the mounted file, it is often easiest to instead mount the parent directory.

I can't find the same thing in the latest docs though - but that's not to say it's not still an issue/limitation on the docker side of things because it clearly is!

**Comment by benlenau** [comment]
> So researching a little into this, I found the following here on a [mirror of the docker docs for 1.10](https://apimirror.com/docker~1.10/engine/userguide/containers/dockervolumes/index)
> 
> 
> 
> >Note: Many tools used to edit files including `vi` and `sed --in-place` may result in an inode change. Since Docker v1.1.0, this will produce an error such as “sed: cannot rename ./sedKdJ9Dy: Device or resource busy”. In the case where you want to edit the mounted file, it is often easiest to instead mount the parent directory.
> 
> 
> 
> I can't find the same thing in the latest docs though - but that's not to say it's not still an issue/limitation on the docker side of things because it clearly is! 

Excellent digging you did there 🙂 It surely seems and looks like the error in question.

**Comment by PromoFaux** [comment]
https://medium.com/@jonsbun/why-need-to-be-careful-when-mounting-single-files-into-a-docker-container-4f929340834

>So what to do? In my opinion, there are at least three options:
> - As often as possible use not a single file but directory bind mount
> - Restart Docker container after any mounted single file modification
> - Use editors only without swap files or disable this feature

I would suggest that option 1 is the only real thing to do here.

I'm going to close this issue out as it is not really an issue with Pi-hole, per-se, rather a limitation of Docker in terms of mounting single files
